Normation/rudder

rudder-core/src/main/scala/com/normation/rudder/services/policies/JavascriptEngine.scala, rudder-core/src/test/scala/com/normation/rudder/services/policies/TestJsEngine.scala
https://www.rudder-project.org/redmine/issues/8936
=> Fixes #8936: JS scripting engine is broken with IBM JDK 7 (and 8)

rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
https://www.rudder-project.org/redmine/issues/8867
=> Fixes #8867: Webapp: sorting by recent changes doesn't work

rudder-web/src/main/webapp/style/login.css
https://www.rudder-project.org/redmine/issues/8939
=> Fixes #8939: Wrong input icon alignment in login page

pom.xml, rudder-core/pom.xml, rudder-templates-cli/pom.xml, rudder-templates-cli/src/main/scala/com/normation/templates/cli/TemplateCli.scala, rudder-templates/pom.xml, rudder-web/pom.xml, rudder-web/src/main/webapp/index.html, rudder-web/src/main/webapp/templates-hidden/common-layout.html
https://www.rudder-project.org/redmine/issues/8934
=> Fixes #8934: Rename Rudder 3.3 to 4.0

rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/RestExtractorService.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/RestUtils.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/changeRequest/ChangeRequestAPIService3.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/directive/DirectiveAPI2.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/directive/DirectiveAPIService2.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/group/GroupAPI6.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/group/GroupAPIService2.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/group/GroupAPIService6.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/node/NodeAPIService5.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/parameters/ParameterApiService2.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/rule/RuleAPI6.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/rule/RuleAPIService2.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/rule/RuleAPIService6.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/technique/TechniqueAPI6.scala
https://www.rudder-project.org/redmine/issues/8957
=> Fixes #8957: Web API doesn't process uuid for newly added directive

rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/compliance/ComplianceAPIData.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/compliance/ComplianceAPIService.scala
https://www.rudder-project.org/redmine/issues/9083
=> Fixes #9083: Add item names in compliance API

rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala, rudder-web/src/main/scala/com/normation/rudder/web/model/DirectiveEditor.scala, rudder-web/src/main/scala/com/normation/rudder/web/model/DirectiveFieldEditors.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PropertiesManagement.scala, rudder-web/src/main/webapp/javascript/rudder/angular/textForm.js, rudder-web/src/main/webapp/style/rudder-bootstrap.css, rudder-web/src/main/webapp/style/rudder.css, rudder-web/src/main/webapp/templates-hidden/components/ComponentDirectiveEditForm.html, rudder-web/src/main/webapp/templates-hidden/components/directiveInput.html, rudder-web/src/test/scala/com/normation/rudder/web/services/Section2FieldServiceTest.scala
https://www.rudder-project.org/redmine/issues/9090
=> Fixes #9090: Allow to use JS script in text/textarea 

rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchBackendImpl.scala, rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchService.scala
https://www.rudder-project.org/redmine/issues/9121
=> Fixes #9121: Quicksearch is not looking for multiline inputs

rudder-web/src/main/webapp/javascript/rudder/angular/quicksearch.js, rudder-web/src/main/webapp/style/rudder-bootstrap.css, rudder-web/src/main/webapp/style/rudder-quicksearch.css, rudder-web/src/main/webapp/templates-hidden/common-layout.html
https://www.rudder-project.org/redmine/issues/9102
=> Fixes #9102: Make the new Quicksearch UI beautiful

rudder-web/src/main/webapp/secure/administration/policyServerManagement.html, rudder-web/src/main/webapp/templates-hidden/common-layout.html
https://www.rudder-project.org/redmine/issues/9129
=> Fixes #9129: Bad title style for quicksearch activation in admin tab

rudder-web/src/main/webapp/templates-hidden/common-layout.html
https://www.rudder-project.org/redmine/issues/9134
=> Fixes #9134: The link to the quicksearch doc is wrong in 3.1

rudder-web/src/main/webapp/javascript/jquery/jquery-timepicker/jquery-ui-timepicker-addon-en.js, rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js, rudder-web/src/main/webapp/secure/utilities/eventLogs.html, rudder-web/src/main/webapp/style/rudder.css, rudder-web/src/main/webapp/templates-hidden/common-layout.html, rudder-web/src/main/webapp/templates-hidden/node_logs_tabs.html
https://www.rudder-project.org/redmine/issues/9135
=> Fixes #9135: Improve technical and event log datepicker UX

rudder-web/src/main/webapp/templates-hidden/common-layout.html
https://www.rudder-project.org/redmine/issues/9136
=> Fixes #9136: The link to the quicksearch doc is wrong in 3.2

rudder-web/src/main/webapp/templates-hidden/common-layout.html
https://www.rudder-project.org/redmine/issues/9150
=> Fixes #9150: Repair quicksearch in 3.2

rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala
https://www.rudder-project.org/redmine/issues/9141
=> Fixes #9141: When there is missing and received reports, we don't see the received one

rudder-web/src/main/webapp/secure/administration/policyServerManagement.html
https://www.rudder-project.org/redmine/issues/9162
=> Fixes #9162: Correct node properties documentation link in Rudder 3.2

rudder-web/src/main/webapp/secure/administration/policyServerManagement.html
https://www.rudder-project.org/redmine/issues/9161
=> Fixes #9161: Correct node properties documentation link in Rudder 3.1

rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala, rudder-web/src/main/scala/com/normation/rudder/web/services/ComplianceData.scala, rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
https://www.rudder-project.org/redmine/issues/9159
=> Fixes #9159: The computing of missing+other status is not correct

rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala, rudder-web/src/main/webapp/javascript/rudder/angular/apiAccount.js
https://www.rudder-project.org/redmine/issues/9168
=> Fixes #9168: Empty page "Rudder -API settings"

rudder-core/src/test/scala/com/normation/rudder/services/reports/ExecutionBatchTest.scala
https://www.rudder-project.org/redmine/issues/9178
=> Fixes #9178: Broken test since compliance computation changed

rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PropertiesManagement.scala
https://www.rudder-project.org/redmine/issues/9185
=> Fixes #9185: Cannot change twice the setting for node properties and quicksearch

rudder-web/src/main/webapp/secure/administration/policyServerManagement.html
https://www.rudder-project.org/redmine/issues/9180
=> Fixes #9180: Typo in doc for new scripts evaluation and node properties

rudder-web/src/main/webapp/style/rudder-quicksearch.css
https://www.rudder-project.org/redmine/issues/9186
=> Fixes #9186: We must not use proprietary font "segoeui.ttf"

rudder-web/src/main/scala/com/normation/rudder/web/rest/directive/DirectiveAPIService2.scala
https://www.rudder-project.org/redmine/issues/9194
=> Fixes #9194: Two level of 'directives' in directive API

rudder-web/src/main/webapp/javascript/rudder/angular/quicksearch.js
https://www.rudder-project.org/redmine/issues/9197
=> Fixes #9197: Quicksearch does not redirect to a rule when you are on the rule page. 

rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchBackendImpl.scala
https://www.rudder-project.org/redmine/issues/9183
=> Fixes #9183: quicksearch returns system rules/directives/groups

rudder-web/src/main/webapp/secure/administration/policyServerManagement.html
https://www.rudder-project.org/redmine/issues/9198
=> Fixes #9198: Script evaluation is not limited to password fields anymore - settings page

rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchBackendImpl.scala
https://www.rudder-project.org/redmine/issues/9212
=> Fixes #9212: Quisearch does not show system nodes

rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchBackendImpl.scala
https://www.rudder-project.org/redmine/issues/9221
=> Fixes #9221: When searching for a node "in:xxx", we see node id in place of node name

rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchBackendImpl.scala
https://www.rudder-project.org/redmine/issues/9219
=> Fixes #9219: Searching on os type does not work

rudder-core/src/main/scala/com/normation/rudder/domain/eventlog/EventLogCategories.scala, rudder-core/src/main/scala/com/normation/rudder/domain/eventlog/NodeEventLog.scala, rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogDetailsService.scala, rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogFactory.scala, rudder-core/src/test/scala/com/normation/rudder/services/eventlog/NodeEventLogFormatV6Test.scala, rudder-web/src/main/scala/com/normation/rudder/web/services/EventListDisplayer.scala
https://www.rudder-project.org/redmine/issues/9204
=> Fixes #9204: Clean up unused NodeXXXModified events

rudder-core/src/main/scala/com/normation/rudder/domain/policies/PolicyMode.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/write/BuildBundleSequence.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/write/Cf3PromisesFileWriterService.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PrepareTemplateVariables.scala, rudder-core/src/test/scala/com/normation/rudder/domain/policies/PolicyModeTest.scala
https://www.rudder-project.org/redmine/issues/9227
=> Fixes #9227: Generation must fail if a node has non compatible audit/enforce mode on multi-instance technique

rudder-core/src/test/scala/com/normation/rudder/db/DBCommon.scala
https://www.rudder-project.org/redmine/issues/9259
=> Fixes #9259: Removal of maven parameter for database test

rudder-core/src/main/scala/com/normation/rudder/domain/nodes/NodeInfo.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/SystemVariableService.scala
https://www.rudder-project.org/redmine/issues/9252
=> Fixes #9252: System variable "MANAGED_NODES_KEY" is empty

rudder-core/src/test/scala/com/normation/rudder/domain/nodes/CFEngineRSAKeyHashTest.scala
https://www.rudder-project.org/redmine/issues/9260
=> Fixes #9260: Broken test after parent ticket #9252

rudder-web/src/main/resources/default.properties
https://www.rudder-project.org/redmine/issues/9264
=> Fixes #9264: Virtual machine detection does not recognize HyperV machines (webapp rendering)

rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/EventLogJdbcRepository.scala, rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/HistorizationJdbcRepository.scala, rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ReportsJdbcRepository.scala
https://www.rudder-project.org/redmine/issues/9263
=> Fixes #9263: Error on report batch: NULL for non option type & on eventlog

rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/HistorizationJdbcRepository.scala
https://www.rudder-project.org/redmine/issues/9275
=> Fixes #9275: Could not update the rules historization information in base

rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ExpectedReportsJdbcRepository.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/ExpectedReportsUpdate.scala, rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/GitModificationRepositoryTest.scala, rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/HistorizationRepositoryTest.scala, rudder-web/src/main/scala/com/normation/rudder/web/services/LogDisplayer.scala
https://www.rudder-project.org/redmine/issues/9281
=> Fixes #9281: Error when generating policies: java.util.NoSuchElementException: key not found: XXXX

rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ReportsJdbcRepository.scala
https://www.rudder-project.org/redmine/issues/9287
=> Fixes #9287: Database size doesn't show up on the Reports database

rudder-web/src/main/webapp/templates-hidden/common-layout.html
https://www.rudder-project.org/redmine/issues/9250
=> Fixes #9250: JS error on Rudder 4.0 that prevent compliance & software display

rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/9276
=> Fixes #9276: The \"fail\" cross in generation is in success-green

rudder-web/src/main/scala/com/normation/rudder/web/components/ShowNodeDetailsFromNode.scala, rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala, rudder-web/src/main/scala/com/normation/rudder/web/services/LogDisplayer.scala, rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala, rudder-web/src/main/webapp/style/rudder/rudder.css
https://www.rudder-project.org/redmine/issues/9217
=> Fixes #9217: Broken CSS in inventory tabs

rudder-web/src/main/webapp/index.html
https://www.rudder-project.org/redmine/issues/9215
=> Fixes #9215: Clicking on Enter does not log in atfer entering credentials

rudder-web/src/main/scala/com/normation/rudder/web/model/DirectiveEditor.scala
https://www.rudder-project.org/redmine/issues/9272
=> Fixes #9272: Directive edit form takes only 1/3 of the width

rudder-web/src/main/scala/com/normation/rudder/web/snippet/BaseUrl.scala, rudder-web/src/main/webapp/javascript/rudder/angular/auditMode.js
https://www.rudder-project.org/redmine/issues/9282
=> Fixes #9282: Setting API has hardcoded context "/rudder/" in its urls path

rudder-web/src/main/scala/com/normation/rudder/web/components/RuleEditForm.scala, rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala, rudder-web/src/main/scala/com/normation/rudder/web/services/LogDisplayer.scala, rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala
https://www.rudder-project.org/redmine/issues/9316
=> Fixes #9316: Compliance and Software don't show on the node details page

rudder-web/src/main/scala/com/normation/rudder/web/model/DirectiveFieldEditors.scala, rudder-web/src/main/webapp/templates-hidden/components/directiveInput.html
https://www.rudder-project.org/redmine/issues/9243
=> Fixes #9243: Technique "Enforce a file content" breaks carriage returns

rudder-core/src/main/scala/com/normation/rudder/services/policies/nodeconfig/NodeConfigurationCacheRepository.scala
https://www.rudder-project.org/redmine/issues/9320
=> Fixes #9320: Rule & directive order is not taken into account for nodeConfig cache invalidation

rudder-core/src/main/scala/com/normation/rudder/services/policies/nodeconfig/NodeConfigurationCacheRepository.scala
https://www.rudder-project.org/redmine/issues/9303
=> Fixes #9303: Policy Mode is not used to know if a node configuration changed

rudder-core/src/main/scala/com/normation/cfclerk/domain/Constraint.scala, rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala
https://www.rudder-project.org/redmine/issues/9318
=> Fixes #9318: Add Support for shared file input in metadata.xml

rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala, rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/settings/SettingsApi.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/sharedFiles/SharedFilesAPI.scala
https://www.rudder-project.org/redmine/issues/9232
=> Fixes #9232: Add an API to list shared files properties

rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ReportsJdbcRepository.scala
https://www.rudder-project.org/redmine/issues/9288
=> Fixes #9288: Jobs are failling to clean database 

rudder-web/src/main/webapp/style/rudder/rudder-jquery-ui.css
https://www.rudder-project.org/redmine/issues/9337
=> Fixes #9337: 404 error on node details page

rudder-web/src/main/webapp/style/rudder/rudder-jquery-ui.css
https://www.rudder-project.org/redmine/issues/9270
=> Fixes #9270: Missing month selection arrows in eventlog datetime picker

rudder-web/src/main/webapp/style/rudder/rudder.css
https://www.rudder-project.org/redmine/issues/9313
=> Fixes #9313: Text on button on Parameters page are not centered

rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
https://www.rudder-project.org/redmine/issues/9346
=> Fixes #9346: Compilation error because RestSharedFolder not found

rudder-web/src/main/scala/com/normation/rudder/web/rest/RestExtractorService.scala
https://www.rudder-project.org/redmine/issues/9326
=> Fixes #9326: Setting nodeProperty over API does fail on bad key order

rudder-web/src/main/webapp/style/rudder/rudder-menu.css, rudder-web/src/main/webapp/style/rudder/rudder-quicksearch.css, rudder-web/src/main/webapp/templates-hidden/common-layout.html
https://www.rudder-project.org/redmine/issues/9294
=> Fixes #9294: Quicksearch doesn't display results at all

rudder-web/src/main/webapp/style/rudder.css
https://www.rudder-project.org/redmine/issues/9267
=> Fixes #9267: Missing top of eventLog datetime picker on small screen 

rudder-web/src/main/scala/com/normation/rudder/web/components/RuleDisplayer.scala, rudder-web/src/main/webapp/secure/configurationManager/parameterManagement.html, rudder-web/src/main/webapp/secure/nodeManager/searchNodes.html, rudder-web/src/main/webapp/style/rudder/rudder-menu.css, rudder-web/src/main/webapp/style/rudder/rudder.css
https://www.rudder-project.org/redmine/issues/9352
=> Fixes #9352: Prettify pages title

rudder-web/src/main/webapp/secure/utilities/techniqueEditor.html, rudder-web/src/main/webapp/style/rudder/rudder-bootstrap.css
https://www.rudder-project.org/redmine/issues/9349
=> Fixes #9349: Improve UI of technique editor page 

rudder-web/src/main/webapp/index.html, rudder-web/src/main/webapp/templates-hidden/common-layout.html
https://www.rudder-project.org/redmine/issues/9383
=> Fixes #9383: Change hardcoded version number in Rudder

rudder-web/src/main/scala/com/normation/rudder/web/rest/node/NodeAPI8.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/node/NodeAPIService8.scala
https://www.rudder-project.org/redmine/issues/9374
=> Fixes #9374: Add an API to run agent on all Nodes

rudder-web/src/main/webapp/index.html
https://www.rudder-project.org/redmine/issues/8070
=> Fixes #8070: Rudder version on login page: not useful and potentially dangerous

rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js, rudder-web/src/main/webapp/style/rudder/rudder-progress-bar.css
https://www.rudder-project.org/redmine/issues/9314
=> Fixes #9314: Correct display of compliance for compliance error, non compliance

rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/ParameterManagement.scala
https://www.rudder-project.org/redmine/issues/9342
=> Fixes #9342: Error when trying  to create a new Parameter

rudder-core/src/main/scala/com/normation/rudder/repository/ExpectedReportsRepository.scala, rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ExpectedReportsJdbcRepository.scala, rudder-core/src/main/scala/com/normation/rudder/services/servers/RemoveNodeService.scala, rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala
https://www.rudder-project.org/redmine/issues/9401
=> Fixes #9401: Deleting a node should close its expected configuration

rudder-core/src/main/scala/com/normation/rudder/services/policies/write/BuildBundleSequence.scala
https://www.rudder-project.org/redmine/issues/9295
=> Fixes #9295: The old bundlesequence system variable contains contains Bundle(...)

rudder-web/src/main/resources/logback.xml
https://www.rudder-project.org/redmine/issues/9397
=> Fixes #9397: logback.xml doesn't contains most entries in 4.0

rudder-core/src/main/scala/com/normation/rudder/services/policies/nodeconfig/NodeConfigurationCacheRepository.scala
https://www.rudder-project.org/redmine/issues/9402
=> Fixes #9402: Node properties update doesn't invalidate node configuration hash

rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/AcceptNode.scala, rudder-web/src/main/webapp/templates-hidden/components/NodeGroupForm.html
https://www.rudder-project.org/redmine/issues/9400
=> Fixes #9400: On accept node page, [Accept] button should be on right. Or green. Or both.

rudder-web/src/main/webapp/templates-hidden/components/ComponentComplianceMode.html
https://www.rudder-project.org/redmine/issues/9261
=> Fixes #9261: \"change only\" reporting mode is not accurate for \"audit\" policy mode 

rudder-core/src/main/scala/com/normation/rudder/services/policies/write/BuildBundleSequence.scala
https://www.rudder-project.org/redmine/issues/9297
=> Fixes #9297: When generation failed due to mixed mode on one technique, error says "plop"

rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala, rudder-web/src/main/webapp/javascript/rudder/angular/auditMode.js, rudder-web/src/main/webapp/javascript/rudder/rudder.js
https://www.rudder-project.org/redmine/issues/9311
=> Fixes #9311: On Search nodes page, if I click on "Include Rudder server components" checkbox, I get a JS error

rudder-web/src/main/webapp/style/rudder/rudder.css
https://www.rudder-project.org/redmine/issues/9425
=> Fixes #9425: When a component value is on mixed mode, the message goes out of the compliance table

rudder-web/src/main/webapp/secure/administration/apiManagement.html
https://www.rudder-project.org/redmine/issues/9427
=> Fixes #9427: Error message is displayed while loading API accounts table

rudder-web/src/main/scala/com/normation/rudder/web/comet/AsyncDeployment.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupCategoryForm.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/TechniqueCategoryEditForm.scala, rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala, rudder-web/src/main/webapp/secure/administration/techniqueLibraryManagement.html, rudder-web/src/main/webapp/secure/configurationManager/directiveManagement.html, rudder-web/src/main/webapp/secure/configurationManager/parameterManagement.html, rudder-web/src/main/webapp/secure/configurationManager/ruleManagement.html, rudder-web/src/main/webapp/secure/nodeManager/groups.html, rudder-web/src/main/webapp/secure/nodeManager/searchNodes.html, rudder-web/src/main/webapp/secure/utilities/changeRequest.html, rudder-web/src/main/webapp/templates-hidden/Popup/accept_new_server.html, rudder-web/src/main/webapp/templates-hidden/Popup/expected_policy_popup.html, rudder-web/src/main/webapp/templates-hidden/Popup/refuse_new_server.html, rudder-web/src/main/webapp/templates-hidden/common-layout.html, rudder-web/src/main/webapp/templates-hidden/components/ComponentChangeRequest.html, rudder-web/src/main/webapp/templates-hidden/components/ComponentDirectiveEditForm.html, rudder-web/src/main/webapp/templates-hidden/components/ComponentRuleEditForm.html, rudder-web/src/main/webapp/templates-hidden/components/ComponentTechniqueEditForm.html, rudder-web/src/main/webapp/templates-hidden/components/NodeGroupForm.html
https://www.rudder-project.org/redmine/issues/9428
=> Fixes #9428: Popups should be closable/navigable with the keybord

rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js, rudder-web/src/main/webapp/javascript/rudder/rudder.js
https://www.rudder-project.org/redmine/issues/9437
=> Fixes #9437: Unclear popup on compliance bar

rudder-web/src/main/webapp/style/rudder/rudder-bootstrap.css
https://www.rudder-project.org/redmine/issues/9424
=> Fixes #9424: Scrollbar appears on technique editor page

rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/Groups.scala, rudder-web/src/main/webapp/templates-hidden/components/NodeGroupForm.html
https://www.rudder-project.org/redmine/issues/9443
=> Fixes #9443: When clicking on the "edit group" on the Rule details, we don't get redirected to the said group

rudder-web/src/main/webapp/templates-hidden/common-layout.html
https://www.rudder-project.org/redmine/issues/9438
=> Fixes #9438: The link in the Rudder interface should not use french Normation website link

rudder-web/src/main/resources/configuration.properties.sample
Hello,
Here is a quick typo fix.
Thanks.
=> Fix typo in configuration.properties.sample

rudder-web/src/main/scala/com/normation/rudder/web/components/ChangeRequestEditForm.scala, rudder-web/src/main/scala/com/normation/rudder/web/model/RudderBaseField.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/ChangeRequestDetails.scala, rudder-web/src/main/webapp/secure/utilities/changeRequest.html, rudder-web/src/main/webapp/style/rudder/rudder-menu.css, rudder-web/src/main/webapp/style/rudder/rudder.css, rudder-web/src/main/webapp/templates-hidden/components/ComponentChangeRequest.html
https://www.rudder-project.org/redmine/issues/9372
=> Fixes #9372: Repaire and improve Change Request page

rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala, rudder-web/src/main/webapp/javascript/rudder/tree.js
https://www.rudder-project.org/redmine/issues/9271
=> Fixes #9271: Selected directive in directive tree doesn't remain highlighed

rudder-core/src/main/scala/com/normation/rudder/reports/execution/ReportsExecutionRepositoryImpl.scala
https://www.rudder-project.org/redmine/issues/9465
=> Fixes #9465: Super slow query on dashboard loading

rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/settings/SettingsApi.scala
https://www.rudder-project.org/redmine/issues/9455
=> Fixes #9455: Changed compliance mode to allow overridable mode, but promises where not regenerated, and reporting was invalid

rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/9404
=> Fixes #9404: The \"Search Anything\" in the search bar is not readable

rudder-core/src/main/resources/Migration/dbMigration-3.2.x-4.0-add-archived-tables.sql, rudder-core/src/main/resources/reportsSchema.sql
https://www.rudder-project.org/redmine/issues/9475
=> Fixes #9475: Create the tables for archived nodeconfiguration

rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/RudderPropertiesRepository.scala
https://www.rudder-project.org/redmine/issues/9477
=> Fixes #9477: Empty table rudderproperties

rudder-core/src/main/scala/com/normation/rudder/batch/AutomaticReportLogger.scala
https://www.rudder-project.org/redmine/issues/9479
=> Fixes #9479: non-compliant-reports.log does not contain audit logs

rudder-web/src/main/scala/com/normation/rudder/web/components/RuleGrid.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/HomePage.scala, rudder-web/src/main/webapp/javascript/rudder/angular/apiAccount.js, rudder-web/src/main/webapp/javascript/rudder/homePage.js, rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js, rudder-web/src/main/webapp/style/rudder/rudder-progress-bar.css
https://www.rudder-project.org/redmine/issues/9469
=> Fixes #9469: Change Unknown / Missing color

rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala, rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala, rudder-web/src/main/scala/com/normation/rudder/appconfig/ConfigService.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/ShowNodeDetailsFromNode.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/settings/SettingsApi.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PropertiesManagement.scala
https://www.rudder-project.org/redmine/issues/9478
=> Fixes #9478: Settings API

rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala
https://www.rudder-project.org/redmine/issues/9486
=> Fixes #9486: An alert appears when saving changes in the Settings > Change Request form

rudder-core/src/main/scala/com/normation/rudder/db/DB.scala, rudder-core/src/main/scala/com/normation/rudder/domain/reports/ExpectedReports.scala, rudder-core/src/main/scala/com/normation/rudder/repository/ExpectedReportsRepository.scala, rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ExpectedReportsJdbcRepository.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/ExpectedReportsUpdate.scala, rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala, rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ExpectedReportTest.scala, rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala, rudder-core/src/test/scala/com/normation/rudder/services/reports/ExecutionBatchTest.scala, rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala
https://www.rudder-project.org/redmine/issues/9417
=> Fixes #9417: Correct test on expected reports and clean code

rudder-web/src/main/resources/rudder-apache-common.conf
https://www.rudder-project.org/redmine/issues/7134
=> Fixes #7134: Rudder API timeouts when passing wrong parameters

rudder-web/src/main/webapp/secure/administration/apiManagement.html, rudder-web/src/main/webapp/style/rudder/rudder-progress-bar.css, rudder-web/src/main/webapp/style/rudder/rudder.css
https://www.rudder-project.org/redmine/issues/9473
=> Fixes #9473: No background on audit component compliance status

rudder-web/src/main/resources/logback.xml
https://www.rudder-project.org/redmine/issues/9407
=> Fixes #9407: We should not hide exceptions in logs

rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
https://www.rudder-project.org/redmine/issues/9493
=> Fixes #9493: DataTable warning when clicking in Software in Node details

rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js, rudder-web/src/main/webapp/style/rudder/rudder.css
https://www.rudder-project.org/redmine/issues/9498
=> Fixes #9498: Remove stripped progress bars animation

rudder-web/src/main/webapp/templates-hidden/components/ComponentAgentPolicyMode.html, rudder-web/src/main/webapp/templates-hidden/components/directiveInput.html, rudder-web/src/main/webapp/templates-hidden/components/passwordInput.html
https://www.rudder-project.org/redmine/issues/9470
=> Fixes #9470: In some forms, we see variables names before page loading in finished

rudder-web/src/main/scala/com/normation/rudder/web/components/ShowNodeDetailsFromNode.scala
https://www.rudder-project.org/redmine/issues/9472
=> Fixes #9472: Wrong display of node details tabs while loading

rudder-core/src/main/scala/com/normation/rudder/domain/nodes/NodeInfo.scala, rudder-core/src/main/scala/com/normation/rudder/domain/queries/CmdbQuery.scala, rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/write/Cf3PromisesFileWriterService.scala, rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/compliance/ComplianceAPIData.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/node/NodeDetailLevel.scala, rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
https://www.rudder-project.org/redmine/issues/9504
=> Fixes #9504: Correct use of agent info

rudder-web/src/main/scala/com/normation/rudder/web/components/RuleEditForm.scala, rudder-web/src/main/webapp/style/rudder/rudder-menu.css, rudder-web/src/main/webapp/style/rudder/rudder.css, rudder-web/src/main/webapp/templates-hidden/components/ComponentRuleEditForm.html
https://www.rudder-project.org/redmine/issues/9494
=> Fixes #9494: Add bootstrap on Rules form

rudder-core/src/main/scala/com/normation/rudder/services/policies/ExpectedReportsUpdate.scala
https://www.rudder-project.org/redmine/issues/9513
=> Fixes #9513: WARN level debug message

rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala, rudder-web/src/main/webapp/style/rudder/rudder-menu.css, rudder-web/src/main/webapp/style/rudder/rudder.css, rudder-web/src/main/webapp/templates-hidden/components/ComponentDirectiveEditForm.html
https://www.rudder-project.org/redmine/issues/9509
=> Fixes #9509: LIttle improvements on Directive form display (bootstrap on general informations)

rudder-web/src/main/webapp/style/login.css
https://www.rudder-project.org/redmine/issues/9514
=> Fixes #9514: Wrong input icon alignment in login page

rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala
https://www.rudder-project.org/redmine/issues/9533
=> Fixes #9533: Compliance not display in node details from direct link

rudder-web/src/main/webapp/style/rudder/rudder.css
https://www.rudder-project.org/redmine/issues/9548
=> Fixes #9548: No background on 'Compliant' and 'NonCompliant' compliance status

rudder-web/src/main/webapp/javascript/rudder/angular/auditMode.js
https://www.rudder-project.org/redmine/issues/9541
=> Fixes #9541: When changing policy mode on a node, it changes the global policy mode for the application

rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/DatabaseManagement.scala, rudder-web/src/main/webapp/secure/administration/databaseManagement.html, rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/9529
=> Fixes #9529: Old icon when cleaning report datatbase

rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PropertiesManagement.scala, rudder-web/src/main/webapp/secure/administration/policyServerManagement.html, rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/9526
=> Fixes #9526: The \"info\" icon should be replaced

rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/DyngroupReloading.scala
https://www.rudder-project.org/redmine/issues/9532
=> Fixes #9532: Inconsitent naming of buttons in setting actions

rudder-web/src/main/scala/com/normation/rudder/web/components/popup/ModificationValidationPopup.scala
https://www.rudder-project.org/redmine/issues/9523
=> Fixes #9523: Wrong warning in directive save popup

rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala, rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala
https://www.rudder-project.org/redmine/issues/9549
=> Fixes #9549: When the node reports an abort run for bad policy mode, nothing is displayed

rudder-core/src/main/scala/com/normation/rudder/repository/ExpectedReportsRepository.scala, rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ExpectedReportsJdbcRepository.scala, rudder-core/src/main/scala/com/normation/rudder/services/system/DatabaseManager.scala
https://www.rudder-project.org/redmine/issues/8444
=> Fixes #8444: NodeConfigurations and reportsexecutions are not archived in the same way as reports

rudder-web/src/main/scala/com/normation/rudder/web/snippet/QuickSearchNode.scala, rudder-web/src/main/webapp/javascript/rudder/angular/quicksearch.js, rudder-web/src/main/webapp/style/rudder/rudder-quicksearch.css, rudder-web/src/main/webapp/templates-hidden/common-layout.html
https://www.rudder-project.org/redmine/issues/9537
=> Fixes #9537: The link to the quick search doc has disappeared in 4.0

rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ReportsJdbcRepository.scala
https://www.rudder-project.org/redmine/issues/9550
=> Fixes #9550: Recent change column title is incorrect for status

rudder-web/src/main/scala/com/normation/rudder/web/components/RuleEditForm.scala, rudder-web/src/main/webapp/javascript/rudder/angular/groupManagement.js
https://www.rudder-project.org/redmine/issues/9603
=> Fixes #9603: We cannot add group exception in rules settings

rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/9599
=> Fixes #9599: The technique tree does not reach the bottom of the screen

rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
https://www.rudder-project.org/redmine/issues/9601
=> Fixes #9601: In rules list, the category column is as wide as the name column

rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala, rudder-web/src/main/scala/com/normation/rudder/web/services/NodeGrid.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/ParameterManagement.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/AcceptNode.scala
https://www.rudder-project.org/redmine/issues/9606
=> Fixes #9606: Some tables still have 10 entries by default

rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/9600
=> Fixes #9600: There is a cursor under Global compliance details in the home page

rudder-core/src/main/scala/com/normation/rudder/domain/policies/PolicyMode.scala
https://www.rudder-project.org/redmine/issues/9610
=> Fixes #9610: Null pointer exception when changing policy mode on the Directive screen

rudder-web/src/main/resources/logback.xml
https://www.rudder-project.org/redmine/issues/9406
=> Fixes #9406: Missing logger information for quicksearch in logback.xml

rudder-web/src/main/scala/com/normation/rudder/web/rest/settings/SettingsApi.scala
https://www.rudder-project.org/redmine/issues/9611
=> Fixes #9611: Changing policy mode in the setting screen spams the webapp log

rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/9619
=> Fixes #9619: Too large fields in directive form

rudder-web/src/main/scala/com/normation/rudder/appconfig/ConfigService.scala
https://www.rudder-project.org/redmine/issues/9605
=> Fixes #9605: We do not allow overriding the policy mode by default

rudder-web/src/main/resources/rudder-vhost.conf
https://www.rudder-project.org/redmine/issues/9637
=> Fixes #9637: rudder error pages should not change transport

rudder-web/src/main/scala/com/normation/rudder/web/components/RuleGrid.scala, rudder-web/src/main/scala/com/normation/rudder/web/services/ComplianceData.scala, rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/9593
=> Fixes #9593: If i override compliance on a node to "audit", it is still shows "enforce" in its details

rudder-web/src/main/webapp/javascript/rudder/angular/auditMode.js, rudder-web/src/main/webapp/templates-hidden/components/ComponentAgentPolicyMode.html
https://www.rudder-project.org/redmine/issues/9642
=> Fixes #9642: Link to setting from node preference doesn't work

rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
https://www.rudder-project.org/redmine/issues/9256
=> Fixes #9256: Filter rules by application in the directive page

rudder-web/src/main/webapp/templates-hidden/components/ComponentAgentPolicyMode.html
https://www.rudder-project.org/redmine/issues/9655
=> Fixes #9655: Can not click on Audit button in Settings

rudder-web/src/main/webapp/index.html, rudder-web/src/main/webapp/style/login.css
https://www.rudder-project.org/redmine/issues/9656
=> Fixes #9656: Login page broken when window is widened

README.asciidoc
The new README is *excellent*! So much so I felt inclined to fix the few typos that were nagging me, and clarify the last section about building in *this* repo.
Ping @fanf
=> Fix typos and a couple of clarifications in README

rudder-web/src/main/webapp/style/rudder/rudder-bootstrap.css, rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/9657
=> Fixes #9657: Pop-up bottom is rounded, but top is not

rudder-web/src/main/webapp/style/rudder/rudder-bootstrap.css
https://www.rudder-project.org/redmine/issues/9429
=> Fixes #9429: An horizontal scrollbar appears on the dashboard when hovering over the right graph

rudder-web/src/main/webapp/style/rudder/rudder.css
https://www.rudder-project.org/redmine/issues/9492
=> Fixes #9492: Display disabled rules with a tag in place is grey italic

rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/AcceptNode.scala, rudder-web/src/main/webapp/secure/nodeManager/manageNewNode.html, rudder-web/src/main/webapp/style/rudder/rudder-bootstrap.css
https://www.rudder-project.org/redmine/issues/9436
=> Fixes #9436: Error message when failing to accept a new node is hard to find

rudder-web/src/main/webapp/templates-hidden/components/ComponentRuleEditForm.html
https://www.rudder-project.org/redmine/issues/6143
=> Fixes #6143: Rule details text can be misleading

rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/9681
=> Fixes #9681: Rounded corner inside status menu

rudder-web/src/main/resources/configuration.properties.sample
https://www.rudder-project.org/redmine/issues/9685
=> Fixes #9685: Add a warning comment for password change in rudder-web.properties

pom.xml, rudder-core/pom.xml, rudder-templates-cli/pom.xml, rudder-templates/pom.xml, rudder-web/pom.xml
https://www.rudder-project.org/redmine/issues/9686
=> Fixes #9686: Change pom version on master to 4.1

rudder-web/src/main/scala/com/normation/rudder/web/rest/node/NodeAPIService2.scala
https://www.rudder-project.org/redmine/issues/9718
=> Fixes #9718: Bad action name when deleting a node. 

rudder-web/src/test/scala/com/normation/rudder/web/rest/TestRestFromFileDef.scala
https://www.rudder-project.org/redmine/issues/9720
=> Fixes #9720: The code is not valid in 3.2

rudder-core/src/main/scala/com/normation/rudder/datasources/DataSource.scala
https://www.rudder-project.org/redmine/issues/9725
=> Fixes #9725: Data source Scala model

rudder-web/src/main/scala/com/normation/rudder/web/rest/RestAPI.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/RestUtils.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/node/NodeApi.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/settings/SettingsApi.scala
https://www.rudder-project.org/redmine/issues/9747
=> Fixes #9747: 

rudder-web/src/main/scala/com/normation/rudder/web/rest/RestExtractorService.scala
https://www.rudder-project.org/redmine/issues/9741
=> Fixes #9741: Creating an empty group with no search criteria messes up GUI

rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeGroupRepository.scala
https://www.rudder-project.org/redmine/issues/9742
=> Fixes #9742: API allows to create duplicate UUIDs at group creation

rudder-web/src/main/scala/com/normation/rudder/web/services/EventListDisplayer.scala, rudder-web/src/main/webapp/secure/utilities/eventLogs.html
https://www.rudder-project.org/redmine/issues/5963
=> Fixes #5963: If an event logs contains long lines it is not displayed properly

rudder-web/src/main/webapp/style/rudder-bootstrap.css, rudder-web/src/main/webapp/templates-hidden/components/directiveInput.html
https://www.rudder-project.org/redmine/issues/9703
=> Fixes #9703: Rudder v.3.2.9 web UI \"Content of the file\" field design was degraded.

rudder-web/src/main/webapp/index.html, rudder-web/src/main/webapp/style/login.css
https://www.rudder-project.org/redmine/issues/9778
=> Fixes #9778: Broken login page css on latest Chrome version

rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js, rudder-web/src/main/webapp/secure/utilities/changeRequests.html, rudder-web/src/main/webapp/style/rudder-changeRequests.css
https://www.rudder-project.org/redmine/issues/6142
=> Fixes #6142: Change request link is too small

rudder-core/src/main/scala/com/normation/cfclerk/services/impl/SystemVariableSpecServiceImpl.scala, rudder-core/src/main/scala/com/normation/rudder/domain/nodes/NodeInfo.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/SystemVariableService.scala, rudder-core/src/test/scala/com/normation/rudder/domain/nodes/CFEngineRSAKeyHashTest.scala
https://www.rudder-project.org/redmine/issues/9729
=> Fixes #9729: New system variables

rudder-core/pom.xml, rudder-core/src/main/resources/hooks.d/policy-generation-finished/50-sigup-cf-serverd, rudder-core/src/main/resources/hooks.d/policy-generation-finished/hook-template, rudder-core/src/main/resources/hooks.d/policy-generation-finished/readme.txt, rudder-core/src/main/resources/hooks.d/policy-generation-node-finished/hook-template, rudder-core/src/main/resources/hooks.d/policy-generation-node-finished/readme.txt, rudder-core/src/main/resources/hooks.d/policy-generation-node-ready/10-cf-promise-check, rudder-core/src/main/resources/hooks.d/policy-generation-node-ready/42-error_disabled, rudder-core/src/main/resources/hooks.d/policy-generation-node-ready/90-change-perm, rudder-core/src/main/resources/hooks.d/policy-generation-node-ready/hook-template, rudder-core/src/main/resources/hooks.d/policy-generation-node-ready/readme.txt, rudder-core/src/main/resources/hooks.d/policy-generation-started/hook-template, rudder-core/src/main/resources/hooks.d/policy-generation-started/readme.txt, rudder-core/src/main/scala/com/normation/rudder/hooks/RunHooks.scala, rudder-core/src/main/scala/com/normation/rudder/hooks/RunNuCommand.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/write/Cf3PromisesFileWriterService.scala, rudder-core/src/test/scala/com/normation/rudder/services/policies/write/WriteSystemTechniquesTest.scala, rudder-web/pom.xml, rudder-web/src/main/resources/configuration.properties.sample, rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala
https://www.rudder-project.org/redmine/issues/8353
=> Fixes #8353: Implement notifications for different server-side actions and events (hooks)

rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/EventLogJdbcRepository.scala
https://www.rudder-project.org/redmine/issues/9790
=> Fixes #9790: Error when accessing change request

rudder-web/src/main/webapp/templates-hidden/components/directiveInput.html
https://www.rudder-project.org/redmine/issues/9804
=> Fixes #9804: Shared files input does not appear on in directives form

rudder-core/src/main/scala/com/normation/rudder/datasources/DataSource.scala, rudder-core/src/main/scala/com/normation/rudder/datasources/DataSourceRepository.scala, rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/RestDataSerializer.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/RestExtractorService.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/datasource/DataSourceApi.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/datasource/DataSourceApi9.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/datasource/DataSourceApiService.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/directive/DirectiveAPI2.scala, rudder-web/src/test/scala/com/normation/rudder/web/rest/RestDataSourceTest.scala, rudder-web/src/test/scala/com/normation/rudder/web/rest/RestTestSetUp.scala, rudder-web/src/test/scala/com/normation/rudder/web/rest/TestRestFromFileDef.scala
https://www.rudder-project.org/redmine/issues/9700
=> Fixes #9700: API Rest to define Data sources

rudder-core/src/main/scala/com/normation/rudder/hooks/RunHooks.scala
https://www.rudder-project.org/redmine/issues/9843
=> Fixes #9843: Broken policy generation in Rudder 4.1

rudder-core/src/main/scala/com/normation/rudder/services/policies/SystemVariableService.scala
https://www.rudder-project.org/redmine/issues/9847
=> Fixes #9847: StackOverflowError on policy generation

rudder-core/src/main/scala/com/normation/rudder/domain/reports/ComplianceLevel.scala
https://www.rudder-project.org/redmine/issues/9869
=> Fixes #9869: Compliance on all reports is always computed, even when not necessary

rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ExpectedReportsJdbcRepository.scala, rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala, rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala, rudder-core/src/test/scala/com/normation/rudder/services/reports/ExecutionBatchTest.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/HomePage.scala
https://www.rudder-project.org/redmine/issues/9853
=> Fixes #9853: Incomplete logging in debug_timming

rudder-core/src/main/scala/com/normation/rudder/domain/policies/Tags.scala, rudder-core/src/test/scala/com/normation/rudder/domain/policies/TagsTest.scala
https://www.rudder-project.org/redmine/issues/9870
=> Fixes #9870: Improve tests and detection of invalid serialization for Tags

rudder-core/pom.xml, rudder-core/src/main/scala/com/normation/rudder/datasources/DataSourceLogger.scala, rudder-core/src/main/scala/com/normation/rudder/datasources/DataSourceRepository.scala, rudder-core/src/main/scala/com/normation/rudder/datasources/DataSourceScheduler.scala, rudder-core/src/main/scala/com/normation/rudder/datasources/DataSourceService.scala, rudder-core/src/main/scala/com/normation/rudder/datasources/UpdateHttpDataset.scala, rudder-core/src/main/scala/com/normation/rudder/db/Doobie.scala, rudder-core/src/main/scala/com/normation/rudder/domain/nodes/Node.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala, rudder-core/src/main/scala/com/normation/rudder/services/servers/NewNodeManager.scala, rudder-core/src/test/scala/com/normation/rudder/datasources/JsonPathTest.scala, rudder-core/src/test/scala/com/normation/rudder/datasources/RestServer.scala, rudder-core/src/test/scala/com/normation/rudder/datasources/UpdateHttpDatasetTest.scala, rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala, rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala, rudder-web/src/main/resources/logback.xml, rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/ComplianceModeEditForm.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/RestExtractorService.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/datasource/DataSourceApiService.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/node/NodeAPI9.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/node/NodeAPIService9.scala, rudder-web/src/test/scala/com/normation/rudder/web/rest/RestTestSetUp.scala
https://www.rudder-project.org/redmine/issues/9724
Replacing previous PR: https://github.com/Normation/rudder/pull/1392
=> Fixes #9724: Query HTTP datasource

rudder-core/src/main/resources/ldap/bootstrap.ldif
https://www.rudder-project.org/redmine/issues/9884
=> Fixes #9884: Typo in root of policy libray tree name

rudder-core/src/main/scala/com/normation/rudder/hooks/RunHooks.scala
https://www.rudder-project.org/redmine/issues/9883
=> Fixes #9883: Impovre logger on hooks 

rudder-web/src/main/scala/com/normation/rudder/web/rest/RestDataSerializer.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/RestExtractorService.scala
https://www.rudder-project.org/redmine/issues/9897
=> Fixes #9897: Move datasource parameters into a specific entry in rest json

rudder-web/src/main/scala/com/normation/rudder/web/rest/RestDataSerializer.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/RestExtractorService.scala, rudder-web/src/test/scala/com/normation/rudder/web/rest/RestDataSourceTest.scala
https://www.rudder-project.org/redmine/issues/9899
=> Fixes #9899: Change format of time duration in datasource Rest API

rudder-core/src/main/scala/com/normation/rudder/datasources/UpdateHttpDataset.scala
https://www.rudder-project.org/redmine/issues/9898
=> Fixes #9898: 404 on request should empty the properties on Node

rudder-core/src/main/scala/com/normation/rudder/domain/policies/Directive.scala, rudder-core/src/main/scala/com/normation/rudder/domain/policies/Rule.scala, rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDiffMapper.scala, rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/RestDataSerializer.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/RestExtractorService.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/directive/DirectiveApi.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/rule/RuleApi.scala
https://www.rudder-project.org/redmine/issues/9916
=> Fixes #9916: Add tags in Rule/directives API

rudder-core/src/main/scala/com/normation/rudder/datasources/DataSourceRepository.scala, rudder-core/src/main/scala/com/normation/rudder/datasources/UpdateHttpDataset.scala, rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala, rudder-web/src/main/scala/bootstrap/liftweb/checks/InitDataSourceScheduler.scala
https://www.rudder-project.org/redmine/issues/9910
=> Fixes #9910: Bugs on datasource initilization and update

rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala
https://www.rudder-project.org/redmine/issues/9835
=> Fixes #9835: When we receive reports from node with old reports, caches are not used for compliance computation

rudder-core/src/test/scala/com/normation/rudder/datasources/UpdateHttpDatasetTest.scala, rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/RestDataSerializer.scala
http://www.rudder-project.org/redmine/issues/9931
=> Fixes #9931: correct tests in UpdateHttpDatasetTest

rudder-core/src/main/scala/com/normation/rudder/domain/policies/Tags.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/RuleCompliance.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/RuleGrid.scala, rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala
https://www.rudder-project.org/redmine/issues/9933
=> Fixes #9933: Fix compilation issue after changin tags model

rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala
https://www.rudder-project.org/redmine/issues/9930
=> Fixes #9930: If node is sending unexpected report, we get an invalid text

rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala
https://www.rudder-project.org/redmine/issues/9939
=> Fixes #9939: Broken build in 4.x since the merge of parent ticket

rudder-core/src/main/resources/Migration/dbMigration-4.0.x-4.1-add-compliance-table.sql, rudder-core/src/main/resources/reportsSchema.sql
https://www.rudder-project.org/redmine/issues/9943
=> Fixes #9943: Migration script to add compliance table

rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala, rudder-web/src/main/webapp/style/rudder/rudder-menu.css, rudder-web/src/main/webapp/templates-hidden/components/ComponentTags.html
https://www.rudder-project.org/redmine/issues/9935
=> Fixes #9935: Put in bold "Technique version" label

rudder-core/src/test/scala/com/normation/rudder/datasources/UpdateHttpDatasetTest.scala
https://www.rudder-project.org/redmine/issues/9947
=> Fixes #9947: Build broken (missed refactoring)

rudder-web/src/main/scala/com/normation/rudder/web/components/RuleGrid.scala
https://www.rudder-project.org/redmine/issues/9948
=> Fixes #9948: Nothing happens when trying to save a Directive

rudder-web/src/main/webapp/javascript/rudder/angular/filters.js
https://www.rudder-project.org/redmine/issues/9964
=> Fixes #9964: "Clear all tags" button doesn't do anything on Rule page

rudder-core/src/main/scala/com/normation/rudder/services/policies/SystemVariableService.scala
https://www.rudder-project.org/redmine/issues/9958
=> Fixes #9958: Nodeslist file is empty on a root server with one node

rudder-web/src/main/webapp/templates-hidden/components/ComponentRuleEditForm.html
https://www.rudder-project.org/redmine/issues/9955
=> Fixes #9955: Remove the "disabled rule" notice 

rudder-web/src/main/scala/com/normation/rudder/web/components/RuleEditForm.scala
https://www.rudder-project.org/redmine/issues/9949
=> Fixes #9949: Put in bold rule form's required fields label

rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala, rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/9984
=> Fixes #9984: Improve Json display in the Nodes properties tab

rudder-core/src/main/scala/com/normation/rudder/hooks/RunHooks.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/write/Cf3PromisesFileWriterService.scala, rudder-web/src/main/resources/logback.xml
https://www.rudder-project.org/redmine/issues/9950
=> Fixes #9950: Policy generation fails in 4.1 with 'kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]'

rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/ChangeRequestManagement.scala, rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/10012
=> Fixes #10012: Cannot select by status on the "Change Requests" page

rudder-web/src/main/scala/com/normation/rudder/web/components/RuleGrid.scala, rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala, rudder-web/src/main/webapp/javascript/rudder/angular/filters.js
https://www.rudder-project.org/redmine/issues/10010
=> Fixes #10010: When I save a Directive, after cliking "save", it's not possible to scroll anymore in the Directive tree

rudder-core/src/test/scala/com/normation/cfclerk/services/JGitPackageReaderTest.scala, rudder-core/src/test/scala/com/normation/rudder/repository/xml/TestGitFindUtils.scala, rudder-core/src/test/scala/com/normation/rudder/services/policies/TestJsEngine.scala, rudder-core/src/test/scala/com/normation/rudder/services/policies/write/WriteSystemTechniquesTest.scala, rudder-templates-cli/src/test/scala/com/normation/templates/cli/TemplateCliTest.scala, rudder-templates/src/test/resources/logback-test.xml, rudder-web/src/test/resources/logback-test.xml
https://www.rudder-project.org/redmine/issues/10030
=> Fixes #10030: Clean test files (rudder-project)

rudder-core/src/main/scala/com/normation/rudder/datasources/UpdateHttpDataset.scala
https://www.rudder-project.org/redmine/issues/10026
=> Fixes #10026: Datasource config: missing interpolation of rudder params in request header

rudder-core/pom.xml, rudder-core/src/main/scala/com/normation/rudder/datasources/DataSource.scala, rudder-core/src/main/scala/com/normation/rudder/datasources/DataSourceRepository.scala, rudder-core/src/main/scala/com/normation/rudder/datasources/DataSourceScheduler.scala, rudder-core/src/main/scala/com/normation/rudder/datasources/DataSourceSerializer.scala, rudder-core/src/main/scala/com/normation/rudder/datasources/DataSourceService.scala, rudder-core/src/main/scala/com/normation/rudder/datasources/UpdateHttpDataset.scala, rudder-core/src/main/scala/com/normation/rudder/db/Doobie.scala, rudder-core/src/main/scala/com/normation/rudder/repository/json/JsonExctractorUtils.scala, rudder-core/src/test/scala/com/normation/rudder/datasources/RestServer.scala, rudder-core/src/test/scala/com/normation/rudder/datasources/UpdateHttpDatasetTest.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/RestExtractorService.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/datasource/DataSourceApi.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/datasource/DataSourceApiService.scala, rudder-web/src/test/scala/com/normation/rudder/web/rest/RestDataSourceTest.scala
https://www.rudder-project.org/redmine/issues/10027
=> Fixes #10027: Add a POST option for datasource queries

rudder-core/pom.xml, rudder-core/src/main/scala/com/normation/rudder/datasources/DataSourceRepository.scala, rudder-core/src/main/scala/com/normation/rudder/db/DB.scala, rudder-core/src/main/scala/com/normation/rudder/db/Doobie.scala, rudder-core/src/main/scala/com/normation/rudder/reports/execution/LastProcessedReportRepository.scala, rudder-core/src/main/scala/com/normation/rudder/reports/execution/ReportsExecutionRepositoryImpl.scala, rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ComplianceRepository.scala, rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/EventLogJdbcRepository.scala, rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ExpectedReportsJdbcRepository.scala, rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/HistorizationJdbcRepository.scala
https://www.rudder-project.org/redmine/issues/10042
=> Fixes #10042: The build is broken since dependencies update

rudder-core/src/main/scala/com/normation/rudder/datasources/DataSourceRepository.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/node/NodeAPI9.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/node/NodeAPIService9.scala
https://www.rudder-project.org/redmine/issues/10043
=> Fixes #10043: Missing refresh API for one data source only

rudder-core/src/main/scala/com/normation/rudder/db/Doobie.scala, rudder-core/src/main/scala/com/normation/rudder/domain/policies/Tags.scala, rudder-core/src/main/scala/com/normation/rudder/repository/json/JsonExctractorUtils.scala, rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala, rudder-core/src/test/scala/com/normation/rudder/domain/policies/TagsTest.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/RuleCompliance.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/RuleEditForm.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/RuleGrid.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/TagsEditForm.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/RestExtractorService.scala, rudder-web/src/main/webapp/javascript/rudder/angular/filters.js, rudder-web/src/main/webapp/javascript/rudder/angular/tags.js, rudder-web/src/main/webapp/javascript/rudder/tree-tag-plugin.js, rudder-web/src/main/webapp/secure/configurationManager/directiveManagement.html, rudder-web/src/main/webapp/style/rudder/rudder-tags.css, rudder-web/src/main/webapp/templates-hidden/common-layout.html, rudder-web/src/main/webapp/templates-hidden/components/ComponentRuleEditForm.html, rudder-web/src/main/webapp/templates-hidden/components/ComponentTags.html, rudder-web/src/test/scala/com/normation/rudder/web/rest/RestDataSourceTest.scala
https://www.rudder-project.org/redmine/issues/10036
=> Fixes #10036: UI to define tags on Rules/Directives

rudder-core/pom.xml
https://www.rudder-project.org/redmine/issues/10053
=> Fixes #10053: Java error in webapp

pom.xml, rudder-core/pom.xml
https://www.rudder-project.org/redmine/issues/10064
=> Fixes #10064: Remove dependecies inherited from parent-pom dependencyManagement in rudder-core

rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchBackendImpl.scala, rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchDomain.scala
https://www.rudder-project.org/redmine/issues/10062
=> Fixes #10062: Add tag search in quicksearch

rudder-web/src/main/scala/com/normation/rudder/web/components/RuleDisplayer.scala
https://www.rudder-project.org/redmine/issues/10076
=> Fixes #10076: Cannot save directive due to a wrong tag in rule page

rudder-web/pom.xml, rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
https://www.rudder-project.org/redmine/issues/10077
=> Fixes #10077: (old) Autocomplete jar is still present

rudder-web/src/main/resources/configuration.properties.sample, rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/node/NodeAPIService8.scala
https://www.rudder-project.org/redmine/issues/9714
=> Fixes #9714: Remote run API should use relay API

rudder-web/src/main/scala/com/normation/rudder/web/components/RuleDisplayer.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/RuleEditForm.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/TagsEditForm.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateRulePopup.scala, rudder-web/src/main/webapp/style/rudder/rudder-menu.css, rudder-web/src/main/webapp/templates-hidden/components/ComponentRuleEditForm.html
https://www.rudder-project.org/redmine/issues/10082
=> Fixes #10082: Cannot save rules on the rule page on 4.1 beta

rudder-web/src/main/scala/com/normation/rudder/web/components/RuleDisplayer.scala, rudder-web/src/main/webapp/secure/configurationManager/directiveManagement.html, rudder-web/src/main/webapp/style/rudder/rudder-menu.css, rudder-web/src/main/webapp/templates-hidden/components/ComponentDirectiveEditForm.html
https://www.rudder-project.org/redmine/issues/10074
=> Fixes #10074: Rules display is broken in the directives page

rudder-web/src/main/scala/com/normation/rudder/web/rest/node/NodeAPIService8.scala
https://www.rudder-project.org/redmine/issues/10101
=> Fixes #10101: Rudder server remote run api should bypass ssl verification

rudder-core/pom.xml, rudder-web/pom.xml, rudder-web/src/main/resources/applicationContext-security.xml
https://www.rudder-project.org/redmine/issues/10097
=> Fixes #10097: Configured Hicari-CP is not the java8 version

rudder-web/src/main/webapp/templates-hidden/common-layout.html
https://www.rudder-project.org/redmine/issues/9891
=> Fixes #9891: Automatically set year in Rudder interface at build time

rudder-web/pom.xml, rudder-web/src/main/scala/com/normation/rudder/web/rest/node/NodeAPI8.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/node/NodeAPIService8.scala
https://www.rudder-project.org/redmine/issues/10106
=> Fixes #10106: Remote run api does not read correctly the output of rellay request

rudder-web/src/main/webapp/style/rudder/rudder-bootstrap.css
https://www.rudder-project.org/redmine/issues/10108
=> Fixes #10108: Audit info tooltip title for first rule is not visible

pom.xml
https://www.rudder-project.org/redmine/issues/10124
=> Fixes #10124: Use correct repository definition in pom.xml

rudder-web/src/main/scala/com/normation/rudder/web/rest/node/NodeAPIService8.scala
https://www.rudder-project.org/redmine/issues/10136
=> Fixes #10136: apply policy should use asynchronous call when getting output of one node

rudder-core/pom.xml, rudder-web/pom.xml
https://www.rudder-project.org/redmine/issues/10145
=> Fixes #10145: We need to produce tests-jar for plugin to depend on

rudder-core/pom.xml
https://www.rudder-project.org/redmine/issues/10146
=> Fixes #10146: warning: Class javax.annotation.Nonnull not found - continuing with a stub.

rudder-core/pom.xml, rudder-web/pom.xml
https://www.rudder-project.org/redmine/issues/10147
=> Fixes #10147: Test broken with "FileNotFoundException /ldap/bootstrap.ldif"

rudder-core/src/test/resources/configuration-repository/expected-share/root-default-install/properties.d/properties.json, rudder-core/src/test/resources/configuration-repository/expected-share/root-with-two-directives/properties.d/properties.json, rudder-core/src/test/scala/com/normation/rudder/services/policies/write/WriteSystemTechniquesTest.scala, rudder-web/src/test/scala/com/normation/rudder/web/rest/RestStatusTest.scala, rudder-web/src/test/scala/com/normation/rudder/web/rest/TestRestFromFileDef.scala, rudder-web/src/test/scala/com/normation/rudder/web/services/Section2FieldServiceTest.scala
https://www.rudder-project.org/redmine/issues/10150
=> Fixes #10150: Renable WriteSystemTechniquesTest

rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ExpectedReportsJdbcRepository.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/ExpectedReportsUpdate.scala, rudder-web/src/main/resources/logback.xml
https://www.rudder-project.org/redmine/issues/10143
=> Fixes #10143: Incomplete logging in expected reports computation

rudder-core/src/main/scala/com/normation/rudder/domain/logger/PolicyLogger.scala
https://www.rudder-project.org/redmine/issues/10158
=> Fixes #10158: Missing logger definition file in parent ticket

rudder-web/src/main/scala/com/normation/rudder/web/model/DirectiveFieldEditors.scala
https://www.rudder-project.org/redmine/issues/10164
=> Fixes #10164: Broken text fields in directive form

rudder-web/src/main/scala/com/normation/rudder/web/comet/AsyncDeployment.scala
https://www.rudder-project.org/redmine/issues/10133
=> Fixes #10133: Included "time ended" in Status dropdown

rudder-web/src/main/webapp/javascript/rudder/homePage.js, rudder-web/src/main/webapp/style/rudder.css
https://www.rudder-project.org/redmine/issues/7422
=> Fixes #7422: Node breakdown - show actual numbers

rudder-web/src/main/scala/com/normation/rudder/web/comet/AsyncDeployment.scala, rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/10177
=> Fixes #10177: Status dropdown's display is broken

rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PropertiesManagement.scala, rudder-web/src/main/webapp/secure/administration/policyServerManagement.html, rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/10173
=> Fixes #10173: Display of new "Display compliance and recent changes columns on rule summary" setting is broken

rudder-web/src/main/scala/com/normation/rudder/web/rest/node/NodeAPIService8.scala
https://www.rudder-project.org/redmine/issues/10179
=> Fixes #10179: Reapply 10106 after change to scala 2.12/lift 3

rudder-web/src/main/scala/com/normation/rudder/web/rest/node/NodeAPIService8.scala
https://www.rudder-project.org/redmine/issues/10180
=> Fixes #10180: Errors are silenced when contacting remote-run api

rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ReportsJdbcRepository.scala
https://www.rudder-project.org/redmine/issues/10171
=> Fixes #10171: If the Rudder Web Interface is interrupted during the second step of reports archiving, then it won't never succeed in archiving again

rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
https://www.rudder-project.org/redmine/issues/10196
=> Fixes #10196: If we set a short description for a Rule, it won't show up anymore in the rule list

rudder-web/src/main/scala/com/normation/rudder/web/components/RuleGrid.scala, rudder-web/src/main/scala/com/normation/rudder/web/services/NodeGrid.scala
https://www.rudder-project.org/redmine/issues/10174
=> Fixes #10174: Can not see details of pending node

rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/ParameterManagement.scala
https://www.rudder-project.org/redmine/issues/10197
=> Fixes #10197: Parameters description won't show up in 4.1

rudder-web/src/main/webapp/templates-hidden/components/ComponentRuleEditForm.html
https://www.rudder-project.org/redmine/issues/10182
=> Fixes #10182: Broken display in Rule popup creation

rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeRepository.scala
https://www.rudder-project.org/redmine/issues/10198
=> Fixes #10198: EventLog at promise generation for datasources change, even if nothing changed

rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateCategoryOrGroupPopup.scala
https://www.rudder-project.org/redmine/issues/10193
=> Fixes #10193: Spurious println introduced in parent ticket

rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ReportsJdbcRepository.scala
https://www.rudder-project.org/redmine/issues/10188
=> Fixes #10188: Spurious println introduced in parent ticket

rudder-web/src/main/webapp/secure/utilities/eventLogs.html, rudder-web/src/main/webapp/style/rudder/rudder.css
https://www.rudder-project.org/redmine/issues/10219
=> Fixes #10219: Vertically center the filter line in the event logs page

rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
https://www.rudder-project.org/redmine/issues/10194
=> Fixes #10194: Recent changes aren't display sometimes on Rules list

rudder-web/src/main/webapp/templates-hidden/components/ComponentAgentPolicyMode.html
https://www.rudder-project.org/redmine/issues/10217
=> Fixes #10217: Unconsistent titles style in the Settings page

rudder-web/src/main/scala/com/normation/rudder/web/rest/settings/SettingsApi.scala
https://www.rudder-project.org/redmine/issues/9936
=> Fixes #9936: Users with "node_all" security role can not change Agent Policy Mode

rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PropertiesManagement.scala
https://www.rudder-project.org/redmine/issues/10211
=> Fixes #10211: If we change the status of "Display rule compliance columns", we need to refresh the page to be able to revert to previous value

rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala, rudder-web/src/main/webapp/templates-hidden/components/ComponentDirectiveEditForm.html
https://www.rudder-project.org/redmine/issues/9859
=> Fixes #9859: Broken directive migration in Rudder 4.0.2

rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala
https://www.rudder-project.org/redmine/issues/10228
=> Fixes #10228: Reorder Techniques in Directive tree 

rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala, rudder-web/src/main/webapp/style/rudder/rudder-directives.css, rudder-web/src/main/webapp/style/rudder/rudder-menu.css, rudder-web/src/main/webapp/templates-hidden/components/ComponentDirectiveEditForm.html
https://www.rudder-project.org/redmine/issues/9938
=> Fixes #9938: The "Technique version" select and "Migrate" button should be aligned

rudder-web/src/main/scala/com/normation/plugins/RudderPlugin.scala
https://www.rudder-project.org/redmine/issues/10244
=> Fixes #10244: Add a generic parsing method for plugin version

rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchBackendImpl.scala, rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchDomain.scala, rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchQueryParser.scala, rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala, rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/RuleDisplayer.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/TagsEditForm.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/RestCompletion.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/RestQuicksearch.scala, rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala, rudder-web/src/main/webapp/javascript/rudder/angular/filters.js, rudder-web/src/main/webapp/javascript/rudder/angular/tags.js, rudder-web/src/main/webapp/secure/configurationManager/directiveManagement.html, rudder-web/src/main/webapp/style/rudder/rudder-tags.css, rudder-web/src/main/webapp/templates-hidden/components/ComponentTags.html
https://www.rudder-project.org/redmine/issues/10192
=> Fixes #10192: Add autocomplete on rule/directive tags

rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateCategoryOrGroupPopup.scala
https://www.rudder-project.org/redmine/issues/10249
=> Fixes #10249: Cannot choose between Group or category when creating a Group

rudder-web/src/main/webapp/templates-hidden/components/ComponentRuleEditForm.html
https://www.rudder-project.org/redmine/issues/10202
=> Fixes #10202: Rules form fields are too wide

rudder-web/src/main/webapp/javascript/rudder/rudder.js
https://www.rudder-project.org/redmine/issues/10252
=> Fixes #10252: Adjust the height box height's css property instead of max-height 

rudder-web/pom.xml, rudder-web/src/main/webapp/index.html, rudder-web/src/main/webapp/templates-hidden/common-layout.html
https://www.rudder-project.org/redmine/issues/10107
=> Fixes #10107: version is not properly set in web interface

rudder-web/src/main/scala/com/normation/rudder/web/comet/AsyncDeployment.scala, rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/10175
=> Fixes #10175: Promise validation errors (cf-promises) are unreadable

rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/ParameterManagement.scala, rudder-web/src/main/webapp/secure/administration/apiManagement.html, rudder-web/src/main/webapp/secure/configurationManager/parameterManagement.html, rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/10257
=> Fixes #10257: Button are not correctly aligned compared to tables in 4.1

rudder-web/src/main/webapp/secure/administration/policyServerManagement.html
https://www.rudder-project.org/redmine/issues/10261
Replacing previous PR: https://github.com/Normation/rudder/pull/1525
=> Fixes #10261: Setting title are barelly outstanding

rudder-web/src/main/webapp/secure/administration/apiManagement.html
https://www.rudder-project.org/redmine/issues/10266
=> Fixes #10266: When trying to create a new API account that has the same name as an existing acocunt, nothing happen (in 4.0)

rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
https://www.rudder-project.org/redmine/issues/10262
=> Fixes #10262: When clicking refresh in rules, grid header height change

rudder-web/src/main/scala/com/normation/rudder/web/components/RuleDisplayer.scala, rudder-web/src/main/webapp/javascript/rudder/angular/filters.js, rudder-web/src/main/webapp/secure/configurationManager/directiveManagement.html
https://www.rudder-project.org/redmine/issues/10272
=> Fixes #10272: Tag filter creation greyed out after creating a tag filter

rudder-web/src/main/scala/com/normation/rudder/web/rest/RestExtractorService.scala
https://www.rudder-project.org/redmine/issues/10225
=> Fixes #10225: API "Create a new Group" is broken in Rudder 4.1.0 beta 3

rudder-core/src/main/scala/com/normation/rudder/domain/nodes/Node.scala, rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala, rudder-web/src/main/webapp/javascript/rudder/angular/nodeProperties.js, rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/10235
=> Fixes #10235: Improve management of rights and other metadata of node properties

rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala
https://www.rudder-project.org/redmine/issues/10290
=> Fixes #10290: There is no error logged when an error occurs when updating information of Node in Node cache

rudder-core/src/main/scala/com/normation/rudder/domain/nodes/NodeInfo.scala, rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala, rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala, rudder-core/src/test/scala/com/normation/rudder/domain/policies/RuleTargetTest.scala, rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/node/NodeDetailLevel.scala
https://www.rudder-project.org/redmine/issues/10280
=> Fixes #10280: Missing timezone information in API "node details"

rudder-web/src/main/scala/com/normation/rudder/web/rest/RestUtils.scala
https://www.rudder-project.org/redmine/issues/10295
=> Fixes #10295: Log an error when Rest API fails 

rudder-core/src/main/scala/com/normation/rudder/domain/policies/Tags.scala, rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlSerialisationImpl.scala, rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchBackendImpl.scala, rudder-core/src/test/scala/com/normation/rudder/domain/policies/TagsTest.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/RuleGrid.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/RestCompletion.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/RestDataSerializer.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/RestExtractorService.scala, rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala
https://www.rudder-project.org/redmine/issues/9934
=> Fixes #9934: Clean tags data model 

rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/Groups.scala, rudder-web/src/main/webapp/secure/nodeManager/groups.html, rudder-web/src/main/webapp/style/rudder/rudder-groups.css, rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/10281
=> Fixes #10281: Lost space at the bottom of the group page

rudder-web/src/main/resources/applicationContext-security.xml, rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala
https://www.rudder-project.org/redmine/issues/10259
=> Fixes #10259: Log for failed login attempt is not (correctly) reported

rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateCloneGroupPopup.scala
https://www.rudder-project.org/redmine/issues/10307
=> Fixes #10307: Clone group popup is broken

rudder-web/src/main/scala/com/normation/rudder/web/rest/RestExtractorService.scala
https://www.rudder-project.org/redmine/issues/10316
=> Fixes #10316: Missing import deletion about rights, breaks compilation

rudder-web/src/main/webapp/javascript/rudder/angular/nodeProperties.js, rudder-web/src/main/webapp/style/rudder/rudder-menu.css, rudder-web/src/main/webapp/style/rudder/rudder.css
https://www.rudder-project.org/redmine/issues/10302
=> Fixes #10302: Display provider of node properties if defined

rudder-web/src/main/webapp/javascript/rudder/angular/agentSchedule.js, rudder-web/src/main/webapp/javascript/rudder/rudder.js
https://www.rudder-project.org/redmine/issues/10306
=> Fixes #10306: JS Error: twoDigitsFormator is not defined

rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
https://www.rudder-project.org/redmine/issues/10317
=> Fixes #10317: Change graph in rule detail have a wrong vertical axis (can be negative)

rudder-web/src/main/scala/com/normation/rudder/web/components/ShowNodeDetailsFromNode.scala
https://www.rudder-project.org/redmine/issues/10318
=> Fixes #10318: Cannot change schedule on Node 

rudder-web/src/main/webapp/templates-hidden/components/ComponentRuleEditForm.html
https://www.rudder-project.org/redmine/issues/10325
=> Fixes #10325: Unconsistent titles style in Rule settings

rudder-web/src/main/webapp/style/rudder/rudder.css
https://www.rudder-project.org/redmine/issues/10323
=> Fixes #10323: Disabled label disappear passing the mouse over the policy mode label

rudder-web/src/main/webapp/javascript/rudder/angular/nodeProperties.js
https://www.rudder-project.org/redmine/issues/10320
=> Fixes #10320: Adjust providers display in the node properties tab

rudder-web/src/main/webapp/style/rudder/rudder-filemanager.css
https://www.rudder-project.org/redmine/issues/10329
=> Fixes #10329: Display of shared files popup is broken

rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala, rudder-web/src/main/scala/com/normation/rudder/appconfig/ConfigService.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/RestDataSerializer.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PropertiesManagement.scala, rudder-web/src/main/webapp/secure/administration/policyServerManagement.html, rudder-web/src/test/scala/com/normation/rudder/web/rest/RestTestSetUp.scala
https://www.rudder-project.org/redmine/issues/10322
=> Fixes #10322: API compatibility feature switch must be removed in 4.1

rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js, rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/10321
=> Fixes #10321: Compliance bar isn't display the same way in 'List nodes' and 'Rules' pages

rudder-web/src/main/scala/com/normation/rudder/appconfig/ConfigService.scala
https://www.rudder-project.org/redmine/issues/10339
=> Fixes #10339: Compliance/Recent change column should not be present by default in directive screen

rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js, rudder-web/src/main/webapp/javascript/rudder/rudder.js
https://www.rudder-project.org/redmine/issues/9323
=> Fixes #9323: Compliance display when hoverving over the compliance bar is too precise

rudder-web/src/main/webapp/javascript/rudder/angular/apiAccount.js
https://www.rudder-project.org/redmine/issues/10203
=> Fixes #10203: Wrong action named in API accounts table

rudder-web/src/main/webapp/javascript/rudder/rudder.js
https://www.rudder-project.org/redmine/issues/10248
=> Fixes #10248: If there is an error in the Parameter edition/creation popup, its shape change

rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateCategoryOrGroupPopup.scala, rudder-web/src/main/webapp/style/rudder/rudder-bootstrap.css
https://www.rudder-project.org/redmine/issues/10330
=> Fixes #10330: Group Type order should be switched

rudder-web/src/main/webapp/templates-hidden/components/ComponentAgentPolicyMode.html
https://www.rudder-project.org/redmine/issues/9819
=> Fixes #9819: Save button shown even no permission to change it

rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala, rudder-web/src/main/webapp/secure/administration/apiManagement.html, rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/9545
=> Fixes #9545: Inconsistent capitalization of titles in the menu

rudder-web/src/main/webapp/style/rudder/rudder-directives.css
https://www.rudder-project.org/redmine/issues/10360
=> Fixes #10360: Directive "Migrate" button is stuck to the version dropdown list

rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
https://www.rudder-project.org/redmine/issues/10369
=> Fixes #10369: merge error prevent compliance bar display when there is no report

rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/10359
=> Fixes #10359: "Delete <component> #1" button in directive form's text is not centered

rudder-web/src/main/resources/apache2-sysconfig, rudder-web/src/main/resources/rudder-apache-common.conf
https://www.rudder-project.org/redmine/issues/10365
=> Fixes #10365: Enable gzip compression on text resources

rudder-web/src/main/webapp/secure/administration/policyServerManagement.html, rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/9426
=> Fixes #9426: Inconsistent message style in settings page

rudder-web/src/main/webapp/javascript/rudder/homePage.js, rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
https://www.rudder-project.org/redmine/issues/10305
=> Fixes #10305: Add hover and onlick to dashboard caption

rudder-web/src/main/webapp/WEB-INF/web.xml
https://www.rudder-project.org/redmine/issues/10381
=> Fixes #10381: Remove gzipfilter from jetty to handle compression in Apache2

rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
https://www.rudder-project.org/redmine/issues/10260
=> Fixes #10260: Lift security policy violated

rudder-web/src/main/resources/content-types.properties, rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala, rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
https://www.rudder-project.org/redmine/issues/10387
=> Fixes #10387: Rudder (svg) logo aren't displayed with chrome 

rudder-web/pom.xml
https://www.rudder-project.org/redmine/issues/10394
=> Fixes #10394: Update Monix (rudder-web)

rudder-core/pom.xml, rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateActiveTechniqueCategoryPopup.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateCategoryOrGroupPopup.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateCloneDirectivePopup.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateCloneGroupPopup.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateRulePopup.scala, rudder-web/src/main/scala/com/normation/rudder/web/model/RudderBaseField.scala, rudder-web/src/main/webapp/templates-hidden/Popup/createCategoryOrGroup.html
https://www.rudder-project.org/redmine/issues/10328
=> Fixes #10328: No error message in group creation popup if no name is set

rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js, rudder-web/src/main/webapp/style/rudder/rudder.css
https://www.rudder-project.org/redmine/issues/10389
=> Fixes #10389: Tooltips are broken in Rule tables

rudder-core/pom.xml
https://www.rudder-project.org/redmine/issues/10399
=> Fixes #10399: Remove plugin jar/war version in children projects

rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PropertiesManagement.scala, rudder-web/src/main/webapp/secure/administration/policyServerManagement.html
https://www.rudder-project.org/redmine/issues/9328
=> Fixes #9328: Checkboxes in Administration menu are not locked for users with missing permissions

rudder-web/src/main/webapp/style/rudder/rudder-menu.css, rudder-web/src/main/webapp/style/rudder/rudder-quicksearch.css
https://www.rudder-project.org/redmine/issues/10400
=> Fixes #10400: Quick search text has gone a hard to read gray

rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala, rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNodeGroupTree.scala, rudder-web/src/main/webapp/secure/configurationManager/directiveManagement.html, rudder-web/src/main/webapp/style/rudder/rudder-directives.css, rudder-web/src/main/webapp/style/rudder/rudder-menu.css, rudder-web/src/main/webapp/style/rudder/rudder-tags.css, rudder-web/src/main/webapp/style/rudder/rudder.css
https://www.rudder-project.org/redmine/issues/10384
=> Fixes #10384: Fix some details in Directives page

rudder-web/src/main/scala/com/normation/rudder/web/rest/RestQuicksearch.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/QuickSearchNode.scala
https://www.rudder-project.org/redmine/issues/10407
=> Fixes #10407: Cannot use slashes in quick search

rudder-web/src/main/resources/rudder-apache-common.conf
https://www.rudder-project.org/redmine/issues/10416
=> Fixes #10416: Invalid apache config on 3.1

rudder-web/src/main/webapp/secure/configurationManager/directiveManagement.html
https://www.rudder-project.org/redmine/issues/10358
=> Fixes #10358: "Create with latest version" button text is cut off in new directive page

rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNodeGroupTree.scala
https://www.rudder-project.org/redmine/issues/10414
=> Fixes #10414: Missing groups from root category

rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala, rudder-web/src/main/webapp/style/rudder/rudder-directives.css, rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/10229
=> Fixes #10229: Find a way to display "deprecated" techniques which still contain directives in the directives tree

rudder-web/src/main/webapp/javascript/rudder/homePage.js, rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js, rudder-web/src/main/webapp/javascript/rudder/rudder.js
https://www.rudder-project.org/redmine/issues/10378
=> Fixes #10378: Legend box may be cut on right

rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala
https://www.rudder-project.org/redmine/issues/10422
=> Fixes #10422: Directive from a whole deprecated technique are not displayed

rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateRulePopup.scala
https://www.rudder-project.org/redmine/issues/10345
=> Fixes #10345: On the Rule details, if I click on "Clone", then cancel action, I get switched to Settings tab

rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala, rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/10420
=> Fixes #10420: Add icon for directives which use deprecated technique

rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala, rudder-web/src/main/webapp/style/rudder/rudder-directives.css, rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/10421
=> Fixes #10421: Add icon for directives which can be migrated to an upper technique version

rudder-web/src/main/webapp/style/rudder/rudder.css
https://www.rudder-project.org/redmine/issues/10340
=> Fixes #10340: In the rule table, Recent changes column change size during page loading

rudder-web/src/main/webapp/style/rudder.css
https://www.rudder-project.org/redmine/issues/10361
=> Fixes #10361: Dropdown lists in directive forms are not wide enough and hide the contents of options

rudder-web/src/main/webapp/style/rudder/rudder-menu.css, rudder-web/src/main/webapp/templates-hidden/Popup/accept_new_server.html
https://www.rudder-project.org/redmine/issues/10458
=> Fixes #10458: Weird appearance of accet new nodes popup

rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/AcceptNode.scala, rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js, rudder-web/src/main/webapp/style/rudder.css
https://www.rudder-project.org/redmine/issues/9165
=> Fixes #9165: Display issue on "Accept new Nodes" page

rudder-core/src/main/resources/hooks.d/policy-generation-finished/50-reload-policy-file-server, rudder-core/src/main/resources/hooks.d/policy-generation-node-ready/10-cf-promise-check, rudder-core/src/main/resources/hooks.d/policy-generation-node-ready/90-change-perm
https://www.rudder-project.org/redmine/issues/10449
=> Fixes #10449: validation hooks should execute cf-promises by exec

rudder-web/src/main/webapp/style/rudder.css
https://www.rudder-project.org/redmine/issues/10465
=> Fixes #10465: padding-down instead of padding-bottom in rudder.css

rudder-core/src/main/scala/com/normation/rudder/db/Doobie.scala, rudder-core/src/main/scala/com/normation/rudder/reports/execution/ReportsExecutionRepositoryImpl.scala, rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ExpectedReportsJdbcRepository.scala, rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/HistorizationJdbcRepository.scala, rudder-web/src/main/resources/logback.xml
https://www.rudder-project.org/redmine/issues/10456
=> Fixes #10456: Several core features don't work anymore with more than 1000 nodes

rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckInitUserTemplateLibrary.scala
https://www.rudder-project.org/redmine/issues/10480
=> Fixes #10480: No generation triggered on technique reload if it was partially loaded before

rudder-core/pom.xml, rudder-core/src/main/scala/com/normation/rudder/services/policies/write/Cf3PromisesFileWriterService.scala, rudder-web/pom.xml
https://www.rudder-project.org/redmine/issues/10457
=> Fixes #10457: Hook failed with fork: retry: No child processes

rudder-core/src/main/scala/com/normation/rudder/batch/AsyncWorkflowInfo.scala, rudder-web/src/main/webapp/templates-hidden/common-layout.html
https://www.rudder-project.org/redmine/issues/10499
=> Fixes #10499: When activating change requests, the CR zone doesn't appear in the main bar

rudder-web/src/main/resources/rudder-apache-common.conf
https://www.rudder-project.org/redmine/issues/10452
=> Fixes #10452: GUI breaks completely with IE 11

rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala
https://www.rudder-project.org/redmine/issues/10501
=> Fixes #10501: Directive page not displaying with "None.get" in logs

rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala, rudder-web/src/main/webapp/javascript/rudder/rudder.js, rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/10509
=> Fixes #10509: Some tooltips can't overflow their container

rudder-web/src/main/scala/com/normation/rudder/web/components/RuleDisplayer.scala, rudder-web/src/main/webapp/style/rudder/rudder-rules.css
https://www.rudder-project.org/redmine/issues/10510
=> Fixes #10510: "New category" button hides "Categories" title on small screens

rudder-core/src/main/scala/com/normation/rudder/domain/nodes/Node.scala, rudder-core/src/test/scala/com/normation/rudder/domain/nodes/NodePropertiesTest.scala
https://www.rudder-project.org/redmine/issues/10520
=> Fixes #10520: Dataource can not override an existing property

rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/10528
=> Fixes #10528: Buttons left-right padding is inconsistent

rudder-web/src/main/webapp/style/rudder/rudder.css
https://www.rudder-project.org/redmine/issues/8517
=> Fixes #8517: The tab under mouse hover in black on black backgroud in inventory

rudder-web/src/main/webapp/style/rudder/rudder-bootstrap.css
https://www.rudder-project.org/redmine/issues/10392
=> Fixes #10392: Compliance bar graph doesn't show small compliance numbers

rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
https://www.rudder-project.org/redmine/issues/10525
=> Fixes #10525: A magnifier icon appears in the filter fild after displaying directives that would be applied in pending nodes page

rudder-web/src/main/webapp/secure/nodeManager/manageNewNode.html
https://www.rudder-project.org/redmine/issues/10524
=> Fixes #10524: Different icons for magnifier in pending nodes page

rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
https://www.rudder-project.org/redmine/issues/10526
=> Fixes #10526: Group type order  is different between popup and group page

rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PropertiesManagement.scala
https://www.rudder-project.org/redmine/issues/9391
=> Fixes #9391: "Reset to default" action in "Change Audit Logs" doesn't reset to install version

rudder-web/src/main/scala/com/normation/rudder/web/services/NodeGrid.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/AcceptNode.scala
https://www.rudder-project.org/redmine/issues/10513
=> Fixes #10513: Directive column of pending nodes table is not wide enough.

rudder-core/src/main/scala/com/normation/rudder/domain/policies/Tags.scala, rudder-core/src/main/scala/com/normation/rudder/repository/json/JsonExctractorUtils.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/RestExtractorService.scala
https://www.rudder-project.org/redmine/issues/10547
=> Fixes #10547: Cannot insert a directive via the API in Rudder 4.1

rudder-web/src/main/scala/com/normation/rudder/web/rest/RestUtils.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/directive/DirectiveAPI2.scala
https://www.rudder-project.org/redmine/issues/10554
=> Fixes #10554: Wrong error message on directive API

rudder-core/src/main/scala/com/normation/rudder/repository/xml/ItemArchiveManagerImpl.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/RestGetGitCommitAsZip.scala
https://www.rudder-project.org/redmine/issues/9448
=> Fixes #9448: Missing "user techniques" in the technique editor when exporting / importing archive

rudder-core/src/main/scala/com/normation/rudder/domain/queries/CmdbQuery.scala, rudder-core/src/main/scala/com/normation/rudder/domain/queries/DitQueryData.scala, rudder-core/src/main/scala/com/normation/rudder/services/queries/LdapQueryProcessor.scala, rudder-core/src/test/scala/com/normation/rudder/domain/queries/CmdbQueryTest.scala, rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala
https://www.rudder-project.org/redmine/issues/10570
=> Fixes #10570: Regex search on node properties is broken: returns all node

rudder-web/src/main/webapp/secure/utilities/archiveManagement.html
https://www.rudder-project.org/redmine/issues/10615
=> Fixes #10615: Selects in Archives page are not wide enough

rudder-web/src/main/webapp/style/rudder-bootstrap.css
https://www.rudder-project.org/redmine/issues/9780
=> Fixes #9780: Mono Font text in directive form are not correctly displayed in Chrome

rudder-web/src/main/scala/com/normation/rudder/web/components/RuleDisplayer.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/TechniqueLibraryManagement.scala, rudder-web/src/main/webapp/secure/configurationManager/directiveManagement.html, rudder-web/src/main/webapp/style/rudder/rudder-directives.css, rudder-web/src/main/webapp/style/rudder/rudder-rules.css
https://www.rudder-project.org/redmine/issues/10630
=> Fixes #10630: "New" buttons should be renamed "Add"

rudder-web/src/main/webapp/style/rudder.css
https://www.rudder-project.org/redmine/issues/6257
=> Fixes #6257: There is small display glitch in change request display 

rudder-core/src/main/resources/hooks.d/node-post-deletion/hook-template, rudder-core/src/main/resources/hooks.d/node-post-deletion/readme.adoc, rudder-core/src/main/resources/hooks.d/node-pre-deletion/hook-template, rudder-core/src/main/resources/hooks.d/node-pre-deletion/readme.adoc, rudder-core/src/main/scala/com/normation/rudder/hooks/RunHooks.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/write/Cf3PromisesFileWriterService.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PathComputer.scala, rudder-core/src/main/scala/com/normation/rudder/services/servers/RemoveNodeService.scala, rudder-core/src/test/scala/com/normation/rudder/services/policies/write/PathComputerTest.scala, rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala, rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
https://www.rudder-project.org/redmine/issues/10568
=> Fixes #10568: Create a hook for pre and post node deletion event

rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala, rudder-web/src/main/webapp/javascript/rudder/rudder.js, rudder-web/src/main/webapp/secure/configurationManager/directiveManagement.html
https://www.rudder-project.org/redmine/issues/10552
=> Fixes #10552: On some resolution, top bar is on two line and we can't see the whole directive tree

rudder-web/src/main/webapp/javascript/rudder/angular/auditMode.js
https://www.rudder-project.org/redmine/issues/10638
=> Fixes #10638:  Cannot change policy mode when audit message is mandatory (4.0)

rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
https://www.rudder-project.org/redmine/issues/8790
=> Fixes #8790: 

rudder-web/src/main/webapp/javascript/rudder/rudder.js
https://www.rudder-project.org/redmine/issues/10515
=> Fixes #10515: Cannot go back to the previous page on node details

rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala
https://www.rudder-project.org/redmine/issues/6145
=> Fixes #6145: Tooltips don't disapear on safari

rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala, rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala, rudder-web/src/main/scala/bootstrap/liftweb/LiftInitContextListener.scala, rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckDIT.scala
https://www.rudder-project.org/redmine/issues/1974
=> Fixes #1974: If an error happen during boostrap, the webapp starts but is in a zombie state and the error page is not displayed

rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/10529
=> Fixes #10529: Logout hover background is too wide

rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
https://www.rudder-project.org/redmine/issues/8105
=> Fixes #8105: A user connected with the inventory role has access to change requests.

rudder-web/src/main/scala/com/normation/rudder/web/services/ComplianceData.scala
https://www.rudder-project.org/redmine/issues/5718
=> Fixes #5718: In reports list, if the directive contains < >, then the part in < > doesn't appear in the reports

rudder-web/src/main/scala/com/normation/rudder/web/components/RuleEditForm.scala
https://www.rudder-project.org/redmine/issues/9805
=> Fixes #9805: Directive is still marked unused after using it

rudder-web/src/main/scala/bootstrap/liftweb/LiftInitContextListener.scala, rudder-web/src/main/scala/bootstrap/liftweb/ThrowIllegalAccessException.java, rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckDIT.scala
https://www.rudder-project.org/redmine/issues/10567
=> Fixes #10567: Infinite "rudder is loading" page if rudder-init didn't run

rudder-web/src/main/scala/bootstrap/liftweb/LiftInitContextListener.scala
https://www.rudder-project.org/redmine/issues/10657
=> Fixes #10657: Warning during compilation

rudder-web/src/main/resources/load-page/rudder-not-loaded.html
https://www.rudder-project.org/redmine/issues/10658
=> Fixes #10658: Modify Rudder 404 page to speak about rudder-init

rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala, rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/10660
=> Fixes #10660: We have no way to know that a Technique is disabled

rudder-web/src/main/scala/com/normation/rudder/web/snippet/HomePage.scala
https://www.rudder-project.org/redmine/issues/10727
=> Fixes #10727: In Rudder 4.1 dashboard, Nova agent are "unknown"

rudder-core/src/main/scala/com/normation/rudder/services/policies/SystemVariableService.scala
https://www.rudder-project.org/redmine/issues/10745
=> Fixes #10745: Cannot generate promises when invalid character in a group name (double quote here)

rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala, rudder-web/src/main/webapp/secure/configurationManager/directiveManagement.html, rudder-web/src/main/webapp/style/rudder/rudder-tags.css
https://www.rudder-project.org/redmine/issues/10705
=> Fixes #10705: When folding directive tree filter, the directive tree stays at its initial size

rudder-core/src/main/resources/hooks.d/policy-generation-node-ready/90-change-perm
https://www.rudder-project.org/redmine/issues/10778
Replacing previous PR: https://github.com/Normation/rudder/pull/1655
=> Fixes #10778: Share promises with apache

rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala
https://www.rudder-project.org/redmine/issues/10735
=> Fixes #10735: Directives tree overflows the page

rudder-core/src/main/scala/com/normation/rudder/services/policies/write/Cf3PolicyDraft.scala
https://www.rudder-project.org/redmine/issues/10825
=> Fixes #10825: Bad comparison in unique variable

rudder-web/src/main/scala/com/normation/rudder/web/snippet/HomePage.scala
https://www.rudder-project.org/redmine/issues/10836
=> Fixes #10836: Display rudder-agent dsc version on Dashboard

rudder-core/src/main/scala/com/normation/rudder/domain/licenses/NovaLicense.scala, rudder-core/src/main/scala/com/normation/rudder/domain/nodes/NodeInfo.scala, rudder-core/src/main/scala/com/normation/rudder/repository/LicenseRepository.scala, rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala, rudder-core/src/main/scala/com/normation/rudder/repository/xml/LicenseRepositoryXML.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/SystemVariableService.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/write/Cf3PromisesFileWriterService.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PathComputer.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PrepareTemplateVariables.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PromiseWriteDataStructures.scala, rudder-core/src/test/scala/com/normation/rudder/domain/policies/RuleTargetTest.scala, rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala, rudder-core/src/test/scala/com/normation/rudder/services/policies/write/PathComputerTest.scala, rudder-core/src/test/scala/com/normation/rudder/services/policies/write/WriteSystemTechniquesTest.scala, rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/node/NodeDetailLevel.scala, rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/HomePage.scala
https://www.rudder-project.org/redmine/issues/10880
=> Fixes #10880: Adapt changes to Rudder to support agent certificate

rudder-web/src/main/webapp/secure/nodeManager/groups.html, rudder-web/src/main/webapp/style/rudder.css
https://www.rudder-project.org/redmine/issues/10659
=> Fixes #10659: Node search input field are tiny and a nightmare to use

rudder-core/src/main/scala/com/normation/rudder/services/policies/write/BuildBundleSequence.scala, rudder-core/src/test/resources/ldap-data/inventory-sample-data.ldif
https://www.rudder-project.org/redmine/issues/10903
=> Fixes #10903: Fix tests and compilation

rudder-web/src/main/scala/com/normation/rudder/web/components/DateFormaterService.scala
https://www.rudder-project.org/redmine/issues/9302
=> Fixes #9302: Time since last generation is limited to hours

rudder-core/src/main/scala/com/normation/rudder/domain/queries/CmdbQuery.scala
https://www.rudder-project.org/redmine/issues/10911
=> Fixes #10911: Add option in search engine to search for DSC agent

rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala, rudder-web/src/main/webapp/style/rudder-bootstrap.css
https://www.rudder-project.org/redmine/issues/10923
=> Fixes #10923: Broken display on directive screen on 3.1.20

rudder-core/src/main/resources/hooks.d/policy-generation-node-ready/91-compress-dsc-policies
https://www.rudder-project.org/redmine/issues/10905
=> Fixes #10905: Zip promises post generation for dsc agent

rudder-core/src/main/scala/com/normation/rudder/services/workflows/WorkflowService.scala
https://www.rudder-project.org/redmine/issues/10938
=> Fixes #10938: Match non exaustive on workflow step: log on error

rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeGroupRepository.scala, rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala
https://www.rudder-project.org/redmine/issues/10967
=> Fixes #10967: Broken test

rudder-core/src/main/scala/com/normation/rudder/services/policies/write/BuildBundleSequence.scala
https://www.rudder-project.org/redmine/issues/10969
Replacing previous PR: https://github.com/Normation/rudder/pull/1675
=> Fixes #10969: Unhelpful error message when applying a tehcnique with invalid agent type to a node

rudder-core/src/main/scala/com/normation/rudder/services/policies/write/BuildBundleSequence.scala
https://www.rudder-project.org/redmine/issues/10974
=> Fixes #10974: Audit only flag does not take parameter rudder-directives.ps1

pom.xml, rudder-core/pom.xml, rudder-core/src/main/scala/com/normation/rudder/services/policies/write/BuildBundleSequence.scala, rudder-templates-cli/pom.xml, rudder-templates/pom.xml, rudder-web/pom.xml
https://www.rudder-project.org/redmine/issues/10979
Replacing previous PR: https://github.com/Normation/rudder/pull/1678
=> Fixes #10979: Pom version in rudder

rudder-core/src/main/scala/com/normation/rudder/services/policies/write/BuildBundleSequence.scala, rudder-core/src/test/resources/configuration-repository/expected-share/node-dsc-with-one-directive/rules/dsc/rudder-directives.ps1, rudder-core/src/test/resources/configuration-repository/expected-share/node-dsc-with-one-directive/rules/dsc/rudder.json
https://www.rudder-project.org/redmine/issues/10980
=> Fixes #10980: Broken test WriteSystemTechniquesTest

rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckCfengineSystemRuleTargets.scala
https://www.rudder-project.org/redmine/issues/10992
=> Fixes #10992: Check on path before classpath for bootstrap.ldif

rudder-core/src/main/resources/ldap/init-policy-server.ldif
https://www.rudder-project.org/redmine/issues/10995
=> Fixes #10995: Missing publicKey in init-policy-server.ldif

rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckDSCSystemPolicy.scala
https://www.rudder-project.org/redmine/issues/10996
=> Fixes #10996: Bad query for all-dsc-node

rudder-core/src/main/scala/com/normation/rudder/hooks/RunHooks.scala
https://www.rudder-project.org/redmine/issues/11010
=> Fixes #11010: Bad semantic for system error on hooks

rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckDSCSystemPolicy.scala
https://www.rudder-project.org/redmine/issues/11014
=> Fixes #11014: Generation error "bad algorithm" with DSC nodes

rudder-core/src/main/scala/com/normation/cfclerk/services/impl/GitTechniqueReader.scala
https://www.rudder-project.org/redmine/issues/11061
=> Fixes #11061: Backporting correction in cf-clerck into Rudder

rudder-core/src/main/scala/com/normation/rudder/services/policies/write/BuildBundleSequence.scala, rudder-core/src/test/resources/configuration-repository/expected-share/node-dsc-with-one-directive/rules/dsc/rudder-directives.ps1, rudder-core/src/test/resources/configuration-repository/expected-share/node-dsc-with-one-directive/rules/dsc/rudder.json
https://www.rudder-project.org/redmine/issues/11071
=> Fixes #11071: Generated technique name for dsc technique in rudder-directives.ps1 contains forbiden chars

rudder-core/src/main/scala/com/normation/rudder/services/policies/write/AgentSpecificLogic.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/write/BuildBundleSequence.scala, rudder-core/src/test/resources/configuration-repository/expected-share/node-dsc-with-one-directive/rules/dsc/rudder.json
https://www.rudder-project.org/redmine/issues/11076
=> Fixes #11076: Missing included list of ps1 in rudder-directive.ps1

rudder-core/src/test/scala/com/normation/rudder/services/policies/write/PrepareTemplateVariableTest.scala
https://www.rudder-project.org/redmine/issues/11081
=> Fixes #11081: Missing update in test in the backport

rudder-web/src/main/webapp/style/rudder/rudder.css
https://www.rudder-project.org/redmine/issues/11028
=> Fixes #11028: Repaired does not appear as yellow anymore

rudder-web/src/main/webapp/style/rudder/rudder.css
https://www.rudder-project.org/redmine/issues/11083
=> Fixes #11083: Add a margin between the filters and the table in Technical logs tab

rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala
https://www.rudder-project.org/redmine/issues/11095
=> Fixes #11095: NPE due to order initialisation of services

rudder-web/src/main/webapp/javascript/rudder/rudder.js, rudder-web/src/main/webapp/templates-hidden/common-layout.html
https://www.rudder-project.org/redmine/issues/10955
=> Fixes #10955: Keep (open/folded) menu state in cache

rudder-web/src/main/scala/com/normation/rudder/web/services/EventListDisplayer.scala
https://www.rudder-project.org/redmine/issues/10951
=> Fixes #10951: Wrong XML identation in event log

rudder-web/src/main/webapp/style/rudder/rudder-tags.css
https://www.rudder-project.org/redmine/issues/11118
=> Fixes #11118: In Directive details, tags input is broken on Iceweasel

rudder-web/src/main/scala/com/normation/rudder/web/rest/settings/SettingsApi.scala, rudder-web/src/main/webapp/javascript/rudder/angular/auditMode.js, rudder-web/src/main/webapp/templates-hidden/components/ComponentAgentPolicyMode.html
https://www.rudder-project.org/redmine/issues/11075
=> Fixes #11075: Users with "node_all" security role can not change Agent Policy Mode

rudder-web/src/main/scala/com/normation/rudder/web/components/RuleEditForm.scala
https://www.rudder-project.org/redmine/issues/10754
=> Fixes #10754: Cannot add a directive with a " in its name in Rule

rudder-core/src/main/scala/com/normation/rudder/domain/Constants.scala
https://www.rudder-project.org/redmine/issues/11155
=> Fixes #11155: Warn on risk of updating file format

rudder-web/src/main/resources/rudder-vhost-ssl.conf
https://www.rudder-project.org/redmine/issues/11159
=> Fixes #11159: 

rudder-web/src/main/webapp/templates-hidden/common-layout.html
https://www.rudder-project.org/redmine/issues/11182
=> Fixes #11182: Typo in unauthorized acces message

rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckCfengineSystemRuleTargets.scala
https://www.rudder-project.org/redmine/issues/11171
=> Fixes #11171: Error when trying to remove a node

rudder-core/src/main/resources/hooks.d/node-post-acceptance/hook-template, rudder-core/src/main/resources/hooks.d/node-post-acceptance/readme.adoc, rudder-core/src/main/scala/com/normation/rudder/services/servers/NewNodeManager.scala, rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala
https://www.rudder-project.org/redmine/issues/11218
=> Fixes #11218: Back-port node-post-acceptation hook in 4.1

rudder-core/src/main/scala/com/normation/rudder/services/policies/RudderPromiseWriterServiceImpl.scala
https://www.rudder-project.org/redmine/issues/11088
=> Fixes #11088: Backport "rudder.json" system variable files to 3.1

rudder-core/src/main/resources/hooks.d/node-post-deletion/hook-template, rudder-core/src/main/resources/hooks.d/node-post-deletion/readme.adoc, rudder-core/src/main/resources/hooks.d/node-pre-deletion/hook-template, rudder-core/src/main/resources/hooks.d/node-pre-deletion/readme.adoc, rudder-core/src/main/resources/hooks.d/policy-generation-finished/50-reload-policy-file-server, rudder-core/src/main/resources/hooks.d/policy-generation-finished/hook-template, rudder-core/src/main/resources/hooks.d/policy-generation-finished/readme.adoc, rudder-core/src/main/resources/hooks.d/policy-generation-node-finished/hook-template, rudder-core/src/main/resources/hooks.d/policy-generation-node-finished/readme.adoc, rudder-core/src/main/resources/hooks.d/policy-generation-node-ready/10-cf-promise-check, rudder-core/src/main/resources/hooks.d/policy-generation-node-ready/42-ignore_disabled_non_exec, rudder-core/src/main/resources/hooks.d/policy-generation-node-ready/42-ignore_extension.disabled, rudder-core/src/main/resources/hooks.d/policy-generation-node-ready/90-change-perm, rudder-core/src/main/resources/hooks.d/policy-generation-node-ready/hook-template, rudder-core/src/main/resources/hooks.d/policy-generation-node-ready/readme.adoc, rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/write/Cf3PromisesFileWriterService.scala, rudder-core/src/main/scala/com/normation/rudder/services/servers/RemoveNodeService.scala
https://www.rudder-project.org/redmine/issues/11213
=> Fixes #11213: Non normalize hooks env var names for node info

rudder-core/src/main/scala/com/normation/cfclerk/domain/Constraint.scala, rudder-core/src/main/scala/com/normation/cfclerk/domain/RegexConstraint.scala
https://www.rudder-project.org/redmine/issues/11217
=> Fixes #11217: Ipv6 constraint NOT PORTED to Rudder 4.0 and up

rudder-core/src/main/scala/com/normation/rudder/domain/logger/ReportLogger.scala
https://www.rudder-project.org/redmine/issues/11223
=> Fixes #11223: /var/log/webapp/compliance/non-compliant-reports does not contain non-compliant (audit) report

rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/11205
=> Fixes #11205: Disabled Rules status is invisible

rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
https://www.rudder-project.org/redmine/issues/11232
=> Fixes #11232: Typo in generation error

rudder-core/src/main/scala/com/normation/cfclerk/domain/AixPasswordHashAlgo.scala, rudder-core/src/main/scala/com/normation/cfclerk/domain/HashAlgoConstraint.scala
https://www.rudder-project.org/redmine/issues/11233
=> Fixes #11233: Same for 4.1

rudder-core/src/main/scala/com/normation/rudder/services/servers/RemoveNodeService.scala, rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
https://www.rudder-project.org/redmine/issues/11231
=> Fixes #11231: Impossible to delete a node when policy server has been deleted

rudder-web/src/main/scala/com/normation/rudder/web/components/RuleGrid.scala, rudder-web/src/main/webapp/style/rudder/rudder.css
https://www.rudder-project.org/redmine/issues/11123
=> Fixes #11123: If a Rule is enabled but applies no Directive, it is displayed as Disabled

rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala
https://www.rudder-project.org/redmine/issues/11152
=> Fixes #11152: Reporting on old techniqe fail in audit mode

rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/DyngroupReloading.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/EditPolicyServerAllowedNetwork.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PropertiesManagement.scala, rudder-web/src/main/webapp/javascript/rudder/rudder.js, rudder-web/src/main/webapp/secure/administration/policyServerManagement.html, rudder-web/src/main/webapp/style/rudder/rudder-menu.css, rudder-web/src/main/webapp/style/rudder/rudder.css, rudder-web/src/main/webapp/templates-hidden/components/ComponentAgentPolicyMode.html, rudder-web/src/main/webapp/templates-hidden/components/ComponentAgentSchedule.html, rudder-web/src/main/webapp/templates-hidden/components/ComponentComplianceMode.html
https://www.rudder-project.org/redmine/issues/9587
=> Fixes #9587: Improve General Settings page

rudder-web/src/main/webapp/templates-hidden/reports_server.html
https://www.rudder-project.org/redmine/issues/11270
=> Fixes #11270: "no report" explanation is not correct in node details

rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/Groups.scala
https://www.rudder-project.org/redmine/issues/11300
=> Fixes #11300: Fold automatically Group categories if there are too many of them

rudder-core/src/main/scala/com/normation/cfclerk/domain/Technique.scala, rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala, rudder-web/src/main/webapp/images/dsc-icon.svg, rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/11286
=> Fixes #11286: Highlight DSC compatible directives

rudder-web/src/main/webapp/secure/nodeManager/groups.html
https://www.rudder-project.org/redmine/issues/11287
=> Fixes #11287: The description of the group tree mentions drag and drop which does not work

rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala, rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/10852
=> Fixes #10852: Node key display differences

rudder-web/src/main/resources/demo-rudder-users.xml, rudder-web/src/main/scala/com/normation/rudder/authorization/Authz.scala
https://www.rudder-project.org/redmine/issues/11185
=> Fixes #11185: "compliance" role is broken

rudder-core/src/main/scala/com/normation/rudder/repository/ExpectedReportsRepository.scala, rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ExpectedReportsJdbcRepository.scala, rudder-core/src/main/scala/com/normation/rudder/services/system/DatabaseManager.scala
https://www.rudder-project.org/redmine/issues/11314
=> Fixes #11314: Node compliance are never archived

rudder-core/src/main/resources/ldap/init-policy-server.ldif, rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckCfengineSystemRuleTargets.scala
https://www.rudder-project.org/redmine/issues/11183
=> Fixes #11183: Group "All nodes known by Rudder directly connected to the XXXX server" excludes DSC nodes

rudder-core/src/main/resources/ldap/bootstrap.ldif, rudder-core/src/main/resources/ldap/init-policy-server.ldif, rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckCfengineSystemRuleTargets.scala
https://www.rudder-project.org/redmine/issues/11334
=> Fixes #11334: rename CFEngine to classic in system groups

rudder-web/src/main/webapp/secure/administration/policyServerManagement.html, rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/11351
=> Fixes #11351: Allowed networks UI is broken in Chromium

rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/write/BuildBundleSequence.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/write/Cf3PolicyDraft.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PrepareTemplateVariables.scala, rudder-core/src/test/scala/com/normation/rudder/services/policies/write/PolicyInstanceAgregationTest.scala, rudder-core/src/test/scala/com/normation/rudder/services/policies/write/WriteSystemTechniquesTest.scala
https://www.rudder-project.org/redmine/issues/11326
=> Fixes #11326: chars are not escaped correctly in dsc techniques

rudder-core/src/main/scala/com/normation/rudder/services/policies/write/Cf3PolicyDraft.scala, rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-two-directives/rules/cfengine-community/packageManagement/1.0/packageManagement.cf, rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-two-directives/rules/cfengine-community/rudder_expected_reports.csv
https://www.rudder-project.org/redmine/issues/11384
=> Fixes #11384: Broken policy generation with internal error

rudder-web/src/main/webapp/secure/configurationManager/directiveManagement.html
https://www.rudder-project.org/redmine/issues/11393
=> Fixes #11393: Cannot select version of directive to create if technique desciption contains curly braces 

rudder-core/src/test/scala/com/normation/rudder/services/policies/write/WriteSystemTechniquesTest.scala
https://www.rudder-project.org/redmine/issues/11397
Replacing previous PR: https://github.com/Normation/rudder/pull/1740
=> Fixes #11397: Refactor policy generation tests

rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPParameterRepository.scala, rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPRuleRepository.scala, rudder-core/src/main/scala/com/normation/rudder/repository/xml/module.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/RestArchiving.scala
https://www.rudder-project.org/redmine/issues/11408
=> Fixes #11408: Archives API list returns badly formatted date

rudder-core/src/main/scala/com/normation/rudder/domain/Constants.scala, rudder-core/src/main/scala/com/normation/rudder/domain/nodes/Node.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/write/Cf3PromisesFileWriterService.scala, rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-two-directives/rules/cfengine-community/rudder-parameters.json, rudder-core/src/test/resources/configuration-repository/expected-share/root-default-install/rudder-parameters.json, rudder-core/src/test/resources/configuration-repository/expected-share/root-with-two-directives/rudder-parameters.json
https://www.rudder-project.org/redmine/issues/11406
=> Fixes #11406: Generate a rudder-parameters.json file containing global parameters

rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PolicyWriterService.scala
https://www.rudder-project.org/redmine/issues/11415
=> Fixes #11415: Fix compilation issue after #11406

rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/TechniqueLibraryManagement.scala, rudder-web/src/main/webapp/javascript/rudder/tree.js, rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/11297
=> Fixes #11297: Highlight techniques that have at least one version compatible with the dsc agent

rudder-core/src/main/scala/com/normation/rudder/services/policies/RuleValService.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/write/AgentSpecificLogic.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/write/BuildBundleSequence.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PrepareTemplateVariables.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PromiseWriteDataStructures.scala, rudder-web/src/main/scala/com/normation/plugins/RudderPlugin.scala
https://www.rudder-project.org/redmine/issues/11431
=> Fixes #11431: Update generation process to make it plugable by agenttype AND by os

rudder-web/src/main/scala/com/normation/plugins/RudderPlugin.scala, rudder-web/src/main/scala/com/normation/plugins/SnippetExtensionRegister.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PluginManagement.scala, rudder-web/src/main/webapp/secure/administration/pluginManagement.html
https://www.rudder-project.org/redmine/issues/11427
=> Fixes #11427: Add in rudder core apis to display license information from plugins. 

rudder-web/src/main/scala/com/normation/plugins/PluginStatus.scala
https://www.rudder-project.org/redmine/issues/11432
=> Fixes #11432: Missing file in parent commit

rudder-web/src/main/webapp/style/rudder/rudder-bootstrap.css, rudder-web/src/main/webapp/style/rudder/rudder-directives.css
https://www.rudder-project.org/redmine/issues/11584
=> Fixes #11584: Update Directive popup is broken on firefox 38.6.1esr 

rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/ParameterManagement.scala, rudder-web/src/main/webapp/secure/configurationManager/parameterManagement.html, rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/11585
=> Fixes #11585: Global parameters UI now showing Edit/Delete button on long lines

rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala, rudder-web/src/main/webapp/secure/configurationManager/directiveManagement.html
https://www.rudder-project.org/redmine/issues/11439
=> Fixes #11439: Highlight techniques that have at least one version compatible with the dsc agent

rudder-core/src/main/scala/com/normation/rudder/batch/UpdateDynamicGroups.scala, rudder-core/src/main/scala/com/normation/rudder/repository/xml/ItemArchiveManagerImpl.scala, rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala
https://www.rudder-project.org/redmine/issues/11244
=> Fixes #11244: Groups are not reloaded after restoring from archive

rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateOrUpdateGlobalParameterPopup.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/RestExtractorService.scala
https://www.rudder-project.org/redmine/issues/11588
=> Fixes #11588: Parameter name requires at least 3 characters

rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDirectiveRepository.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala
See https://www.rudder-project.org/redmine/issues/5203#note-47 for screenshot of the proposed solution.
=> Fixes #5203: There is no way to remove a Directive based on a Technique that no longer exists

rudder-core/src/main/scala/com/normation/rudder/domain/queries/CmdbQuery.scala, rudder-core/src/test/resources/ldap-data/inventory-sample-data.ldif, rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala
https://www.rudder-project.org/redmine/issues/11634
=> Fixes #11634: CFengine agent are not more matched after parent-ticket correction

rudder-web/src/main/webapp/javascript/rudder/homePage.js, rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js, rudder-web/src/main/webapp/style/rudder/rudder-bootstrap.css, rudder-web/src/main/webapp/style/rudder/rudder-menu.css, rudder-web/src/main/webapp/style/rudder/rudder-progress-bar.css
https://www.rudder-project.org/redmine/issues/10761
=> Fixes #10761: Screen estate in compliance graph

rudder-core/src/main/scala/com/normation/rudder/domain/queries/CmdbQuery.scala, rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala
https://www.rudder-project.org/redmine/issues/11646
=> Fixes #11646: Query to search Only Rudder-agent or cfengine-community only does not match

rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala
https://www.rudder-project.org/redmine/issues/11642
=> Fixes #11642: Display message if there are no parameters in Directive details 

rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js, rudder-web/src/main/webapp/style/rudder/rudder.css
https://www.rudder-project.org/redmine/issues/11679
=> Fixes #11679: Fix some CSS issues in Rule's compliance tables

rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala, rudder-web/src/main/webapp/secure/configurationManager/directiveManagement.html, rudder-web/src/main/webapp/templates-hidden/components/ComponentDirectiveEditForm.html
https://www.rudder-project.org/redmine/issues/9354
=> Fixes #9354: Add a jumbotron next to Directives list

rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js, rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/11643
=> Fixes #11643: On Nodes table, put the link to node details on node's name instead of on magnifying glass icon

rudder-core/pom.xml, rudder-core/src/main/scala/com/normation/rudder/db/Doobie.scala, rudder-core/src/main/scala/com/normation/rudder/repository/WorkflowRepository.scala, rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ChangeRequestJdbcRepository.scala, rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/EventLogJdbcRepository.scala, rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ReportsJdbcRepository.scala, rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/WorkflowJdbcRepository.scala, rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala
https://www.rudder-project.org/redmine/issues/11667
No more spring-jdbc \o/
=> Fixes #11667: Remove remaining use of spring-jdbc

rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala
https://www.rudder-project.org/redmine/issues/11713
=> Fixes #11713: Can't edit a new Directive parameters, message "This directive has no parameters" displayed instead

rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala
https://www.rudder-project.org/redmine/issues/11725
=> Fixes #11725: "Priority" level mean the contrary to what is thought

rudder-web/src/main/resources/load-page/rudder-not-loaded.html
https://www.rudder-project.org/redmine/issues/11731
=> Fixes #11731: Add a new reason why rudder might not be loaded

rudder-core/src/main/resources/ldap/rudder.schema, rudder-core/src/main/scala/com/normation/rudder/domain/RudderLDAPConstants.scala, rudder-core/src/main/scala/com/normation/rudder/domain/nodes/Node.scala, rudder-core/src/main/scala/com/normation/rudder/domain/nodes/NodeInfo.scala, rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/HistorizationJdbcRepository.scala, rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala, rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/write/BuildBundleSequence.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PolicyWriterService.scala, rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala, rudder-core/src/main/scala/com/normation/rudder/services/servers/NewNodeManager.scala, rudder-core/src/test/scala/com/normation/rudder/domain/policies/RuleTargetTest.scala, rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala, rudder-rest/src/main/scala/com/normation/rudder/rest/RestDataSerializer.scala, rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala, rudder-rest/src/main/scala/com/normation/rudder/rest/node/NodeAPIService8.scala, rudder-rest/src/main/scala/com/normation/rudder/rest/node/NodeApi.scala, rudder-rest/src/main/scala/com/normation/rudder/rest/node/NodeDetailLevel.scala, rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala
https://www.rudder-project.org/redmine/issues/11748
=> Fixes #11748: Node lifecycle: add a node state

rudder-core/src/main/scala/com/normation/rudder/domain/queries/CmdbQuery.scala, rudder-core/src/test/scala/com/normation/rudder/domain/queries/CmdbQueryTest.scala
https://www.rudder-project.org/redmine/issues/11751
=> Fixes #11751: Impossible to search or build groups based on JSON values in node properties

rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala
https://www.rudder-project.org/redmine/issues/11753
=> Fixes #11753: Deprecate API v7 and remove API v5 and v6

rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala
https://www.rudder-project.org/redmine/issues/11761
=> Fixes #11761: Null Pointer Exception error on Event Log page

rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
https://www.rudder-project.org/redmine/issues/11750
=> Fixes #11750: Missing node state information in node details

rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala
https://www.rudder-project.org/redmine/issues/11765
=> Fixes #11765: Another Null Pointer Exception on eventlog page

rudder-core/pom.xml, rudder-core/src/main/scala/com/normation/rudder/db/DB.scala, rudder-core/src/main/scala/com/normation/rudder/db/Doobie.scala, rudder-core/src/main/scala/com/normation/rudder/domain/policies/Tags.scala, rudder-core/src/main/scala/com/normation/rudder/migration/XmlEntityMigration.scala, rudder-core/src/main/scala/com/normation/rudder/migration/XmlFileFormatMigrationEntities.scala, rudder-core/src/main/scala/com/normation/rudder/reports/execution/LastProcessedReportRepository.scala, rudder-core/src/main/scala/com/normation/rudder/reports/execution/ReportsExecutionRepositoryImpl.scala, rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ChangeRequestJdbcRepository.scala, rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ComplianceRepository.scala, rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/EventLogJdbcRepository.scala, rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ExpectedReportsJdbcRepository.scala, rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/GitModificationRepository.scala, rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/HistorizationJdbcRepository.scala, rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ReportsJdbcRepository.scala, rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/RudderPropertiesRepository.scala, rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/WorkflowJdbcRepository.scala, rudder-core/src/main/scala/com/normation/rudder/repository/json/JsonExctractorUtils.scala, rudder-core/src/test/scala/com/normation/rudder/db/DBCommon.scala, rudder-core/src/test/scala/com/normation/rudder/migration/TestDbMigration.scala, rudder-core/src/test/scala/com/normation/rudder/migration/TestManageMigration.scala, rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ExpectedReportTest.scala, rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/GitModificationRepositoryTest.scala, rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportExecutionTest.scala, rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala, rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportsProgressTest.scala, rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportsTest.scala, rudder-templates-cli/src/test/resources/templates1/expected/cf-served, rudder-templates/src/main/scala/com/normation/templates/FillTemplatesService.scala
https://www.rudder-project.org/redmine/issues/11776
=> Fixes #11776: Switch to cats ecosystem

rudder-core/src/main/scala/com/normation/rudder/ncf/Technique.scala, rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala, rudder-core/src/main/scala/com/normation/rudder/repository/json/JsonExctractorUtils.scala, rudder-core/src/test/resources/configuration-repository/dsc/ncf/50_techniques/technique_by_Rudder/1.0/technique_by_Rudder.ps1, rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/metadata.xml, rudder-core/src/test/scala/com/normation/rudder/ncf/TestTechniqueWriter.scala, rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/RestExtractorService.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/ncf/NcfApi9.scala
https://www.rudder-project.org/redmine/issues/11749
=> Fixes #11749: Add ncf logic to create file into Rudder instead of ncf

rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/InterpolatedValueCompiler.scala, rudder-core/src/test/resources/configuration-repository/dsc/ncf/50_techniques/technique_by_Rudder/1.0/technique_by_Rudder.ps1, rudder-core/src/test/scala/com/normation/rudder/ncf/TestTechniqueWriter.scala, rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala
https://www.rudder-project.org/redmine/issues/11445
=> Fixes #11445: Node properties syntax is not the same for Windows agent

rudder-core/src/main/scala/com/normation/rudder/repository/json/JsonExctractorUtils.scala, rudder-rest/src/main/scala/com/normation/rudder/rest/ncf/NcfApi9.scala, rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala
https://www.rudder-project.org/redmine/issues/11783
=> Fixes #11783: Add logic to generate ncf Technique files into Rudder

rudder-core/src/main/scala/com/normation/rudder/domain/queries/CmdbQuery.scala
https://www.rudder-project.org/redmine/issues/11785
=> Fixes #11785: There's an "UTF-8"s in place of "UTF-8" in a method parameter

rudder-web/src/main/scala/com/normation/rudder/web/components/ComplianceModeEditForm.scala
https://www.rudder-project.org/redmine/issues/11784
=> Fixes #11784: Remove an "unchecked because eliminated by erasure"

rudder-core/pom.xml
https://www.rudder-project.org/redmine/issues/11788
=> Fixes #11788: Revert exclusion of rhino - webapp fails to start

rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDirectiveRepository.scala
https://www.rudder-project.org/redmine/issues/11789
=> Fixes #11789: Clean-up tribial warnings

rudder-web/src/main/scala/com/normation/rudder/web/snippet/HomePage.scala
https://www.rudder-project.org/redmine/issues/11652
=> Fixes #11652: CentOS is written "Centos" in the OS graph on the dashboard

rudder-core/src/main/scala/com/normation/rudder/batch/AbstractScheduler.scala, rudder-core/src/main/scala/com/normation/rudder/batch/AsyncDeploymentAgent.scala, rudder-core/src/main/scala/com/normation/rudder/batch/AsyncWorkflowInfo.scala, rudder-core/src/main/scala/com/normation/rudder/batch/AutomaticReportLogger.scala, rudder-core/src/main/scala/com/normation/rudder/batch/AutomaticReportsCleaner.scala, rudder-core/src/main/scala/com/normation/rudder/batch/CheckPolicyTemplateLibrary.scala, rudder-core/src/main/scala/com/normation/rudder/batch/UpdateDynamicGroups.scala
https://www.rudder-project.org/redmine/issues/11800
=> Fixes #11800: Use scheduledJob logged for scheduledJob

rudder-core/src/main/scala/com/normation/rudder/domain/nodes/Node.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala, rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala, rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala
https://www.rudder-project.org/redmine/issues/11809
=> Fixes #11809: Make node states behavior and name clearer 

rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/write/Cf3PromisesFileWriterService.scala
https://www.rudder-project.org/redmine/issues/11819
=> Fixes #11819: Missing node id in log message on generaction error

rudder-core/src/main/scala/com/normation/rudder/api/ApiAccountRepository.scala, rudder-core/src/main/scala/com/normation/rudder/repository/json/JsonExctractorUtils.scala, rudder-web/pom.xml, rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala, rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala, rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala, rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckNcfTechniqueUpdate.scala, rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckTechniqueLibraryReload.scala, rudder-web/src/main/scala/bootstrap/liftweb/checks/CreateSystemToken.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/RestApiAccounts.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/RestAuthentication.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/RestExtractorService.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/ncf/NcfApi9.scala
https://www.rudder-project.org/redmine/issues/11771
=> Fixes #11771: Add a flag to regenerate all techniques on rudder webapp restart

rudder-web/src/main/scala/com/normation/rudder/web/components/ChangeRequestEditForm.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupCategoryForm.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/RuleEditForm.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/TechniqueCategoryEditForm.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateActiveTechniqueCategoryPopup.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateCategoryOrGroupPopup.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateCloneDirectivePopup.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateCloneGroupPopup.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateOrUpdateGlobalParameterPopup.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateRulePopup.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/popup/ModificationValidationPopup.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/popup/RuleModificationValidationPopup.scala
https://www.rudder-project.org/redmine/issues/11801
=> Fixes #11801: Category name must have 3 caracters

rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala
https://www.rudder-project.org/redmine/issues/11805
=> Fixes #11805: Null pointer exception when restoring group archive.

rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala, rudder-core/src/test/resources/configuration-repository/dsc/ncf/50_techniques/technique_any/1.0/technique_any.ps1, rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/1.0/metadata.xml, rudder-core/src/test/scala/com/normation/rudder/ncf/TestTechniqueWriter.scala
https://www.rudder-project.org/redmine/issues/11833
=> Fixes #11833: rudder_reporting is added in metadata.xml if all condition are any

rudder-core/src/main/scala/com/normation/rudder/ncf/Technique.scala, rudder-core/src/test/resources/configuration-repository/dsc/ncf/50_techniques/technique_any/1.0/technique_any.ps1, rudder-core/src/test/resources/configuration-repository/dsc/ncf/50_techniques/technique_by_Rudder/1.0/technique_by_Rudder.ps1
https://www.rudder-project.org/redmine/issues/11850
=> Fixes #11850: dsc methods parameters do not have a dash between words like cfengine one who have underscore 

rudder-web/src/main/scala/com/normation/rudder/web/services/AsyncComplianceService.scala
https://www.rudder-project.org/redmine/issues/7281
=> Fixes #7281: Compliance keeps on loading while node is not online and "last seen" is not "never"

rudder-web/src/main/scala/com/normation/rudder/web/model/DirectiveEditor.scala
https://www.rudder-project.org/redmine/issues/11841
=> Fixes #11841: Input text for repository in apt repository management is too small

rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala
https://www.rudder-project.org/redmine/issues/11834
=> Fixes #11834: Runaway quotation mark at Node report

rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala, rudder-web/src/main/webapp/javascript/rudder/rudder.js, rudder-web/src/main/webapp/templates-hidden/components/ComponentAgentPolicyMode.html
https://www.rudder-project.org/redmine/issues/11837
=> Fixes #11837: "Agent policy mode" should be "Node policy mode" 

rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js, rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/11849
=> Fixes #11849: add margin to the magnifying glass icon in the Nodes table

rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala, rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/metadata.xml
https://www.rudder-project.org/redmine/issues/11871
=> Fixes #11871: rudder_reporting file is invalid on nodes if it contains '&&' in one of its parameter

rudder-web/src/main/resources/configuration.properties.sample
https://www.rudder-project.org/redmine/issues/10664
=> Fixes #10664: Configuration file of Rudder mention that we may change "LDAP DIT configuration", which is wrong

rudder-core/src/main/scala/com/normation/cfclerk/domain/Technique.scala, rudder-core/src/main/scala/com/normation/cfclerk/domain/VariableAndSectionSpec.scala, rudder-core/src/main/scala/com/normation/rudder/ncf/Technique.scala, rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/DataStructures.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/write/BuildBundleSequence.scala, rudder-core/src/test/scala/com/normation/rudder/ncf/TestTechniqueWriter.scala, rudder-core/src/test/scala/com/normation/rudder/services/policies/write/PrepareTemplateVariableTest.scala, rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala, rudder-rest/src/main/scala/com/normation/rudder/web/model/DirectiveEditor.scala, rudder-rest/src/main/scala/com/normation/rudder/web/services/DirectiveEditorService.scala, rudder-rest/src/main/scala/com/normation/rudder/web/services/Section2FieldService.scala
https://www.rudder-project.org/redmine/issues/5665
=> Fixes #5665: Adapt Rudder to allows to have ncf technique with parameter

rudder-core/src/main/scala/com/normation/cfclerk/domain/VariableAndSectionSpec.scala, rudder-core/src/main/scala/com/normation/cfclerk/services/impl/SystemVariableSpecServiceImpl.scala, rudder-core/src/main/scala/com/normation/cfclerk/xmlparsers/VariableSpecParser.scala, rudder-core/src/main/scala/com/normation/cfclerk/xmlwriters/SectionSpecWriter.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/DataStructures.scala, rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeExpectedReportTest.scala
https://www.rudder-project.org/redmine/issues/11940
=> Fixes #11940: Warn if an "uniqueVariable" is found in a technique

rudder-web/src/main/resources/default.properties, rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
https://www.rudder-project.org/redmine/issues/11943
=> Fixes #11943: Display of node state could be improved

rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupCategoryForm.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/RuleEditForm.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/TechniqueCategoryEditForm.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/TechniqueEditForm.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateActiveTechniqueCategoryPopup.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateCategoryOrGroupPopup.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateCloneDirectivePopup.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateCloneGroupPopup.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateOrUpdateGlobalParameterPopup.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateRulePopup.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/popup/ModificationValidationPopup.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/popup/RuleCategoryPopup.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/popup/RuleModificationValidationPopup.scala, rudder-web/src/main/scala/com/normation/rudder/web/services/NodeGrid.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/ChangeRequestDetails.scala
https://www.rudder-project.org/redmine/issues/11968
=> Fixes #11968: Remove "N-uple adaptation" warning

rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateCategoryOrGroupPopup.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateCloneDirectivePopup.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateCloneGroupPopup.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateOrUpdateGlobalParameterPopup.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateRulePopup.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/popup/GiveReasonPopup.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/popup/ModificationValidationPopup.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/popup/RuleModificationValidationPopup.scala, rudder-web/src/main/scala/com/normation/rudder/web/model/DirectiveFieldEditors.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/ChangeRequestDetails.scala
https://www.rudder-project.org/redmine/issues/11969
=> Fixes #11969: Remove "non-uniry def overrides unary def"

rudder-rest/src/main/scala/com/normation/rudder/rest/internal/RestQuicksearch.scala, rudder-rest/src/main/scala/com/normation/rudder/rest/lift/InfoApi.scala, rudder-rest/src/main/scala/com/normation/rudder/web/model/FilePermissions.scala, rudder-templates/src/test/scala/com/normation/templates/TemplateTest.scala, rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala, rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/AutoCompleteAutoSubmit.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/TechniqueEditForm.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/Util.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala
https://www.rudder-project.org/redmine/issues/11970
=> Fixes #11970: Some more warning with -Ywarn-unused:... 

rudder-core/src/main/scala/com/normation/rudder/domain/nodes/Node.scala, rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ReportsJdbcRepository.scala, rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDirectiveRepository.scala, rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala, rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeGroupRepository.scala, rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPParameterRepository.scala, rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPRuleRepository.scala, rudder-core/src/main/scala/com/normation/rudder/rule/category/LDAPRuleCategoryRepository.scala, rudder-rest/src/main/scala/com/normation/rudder/web/model/FilePermissions.scala
https://www.rudder-project.org/redmine/issues/11975
=> Fixes #11975: Remove "N-uple adaptation" warning (missing one)

rudder-core/src/main/scala/com/normation/rudder/batch/AutomaticReportsCleaner.scala, rudder-core/src/main/scala/com/normation/rudder/domain/reports/CleanReportsAction.scala, rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala
https://www.rudder-project.org/redmine/issues/11977
=> Fixes #11977: Initialization errors

rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala
https://www.rudder-project.org/redmine/issues/11670
=> Fixes #11670: Directives tree is not filtered after saving changes

rudder-core/src/main/scala/com/normation/rudder/domain/reports/ExpectedReports.scala
https://www.rudder-project.org/redmine/issues/11995
=> Fixes #11995: Error when deserializing JSON for expected node configuration in Rudder 4.3

rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeExpectedReportTest.scala
https://www.rudder-project.org/redmine/issues/12003
=> Fixes #12003: Error when deserializing JSON for expected node configuration in Rudder 4.3

rudder-core/src/main/scala/com/normation/rudder/domain/queries/CmdbQuery.scala, rudder-core/src/main/scala/com/normation/rudder/domain/queries/DitQueryData.scala, rudder-core/src/main/scala/com/normation/rudder/services/queries/DynGroupService.scala, rudder-core/src/main/scala/com/normation/rudder/services/queries/LdapQueryProcessor.scala, rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala, rudder-web/src/main/resources/ldapObjectAndAttributes.properties, rudder-web/src/main/resources/logback.xml, rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/SearchNodeComponent.scala
https://www.rudder-project.org/redmine/issues/6982
=> Fixes #6982: Be able to create a groups containing Nodes list from an other group

rudder-core/pom.xml
https://www.rudder-project.org/redmine/issues/11973
=> Fixes #11973: ERROR: canceling statement due to user request

rudder-rest/src/main/scala/com/normation/rudder/Authorizations.scala
https://www.rudder-project.org/redmine/issues/12055
=> Fixes #12055: Admin user cannot create Rules with Rudder 4.3

rudder-core/src/test/scala/com/normation/rudder/services/policies/write/PrepareTemplateVariableTest.scala
https://www.rudder-project.org/redmine/issues/12085
=> Fixes #12085: Add information about technique name/id to directive context

rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitArchiverUtils.scala
https://www.rudder-project.org/redmine/issues/2278
=> Fixes #2278: Remove ListTag workaround when JGit version > 1.2

rudder-core/src/test/resources/ldap-data/schema/099-0-inventory.ldif
https://www.rudder-project.org/redmine/issues/12107
=> Fixes #12107: Update test inventory-schema

rudder-core/src/main/scala/com/normation/rudder/services/servers/NewNodeManager.scala, rudder-rest/src/main/scala/com/normation/appconfig/ConfigService.scala, rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SettingsApi.scala, rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PropertiesManagement.scala, rudder-web/src/main/webapp/secure/administration/policyServerManagement.html
https://www.rudder-project.org/redmine/issues/11811
=> Fixes #11811: Make node post-acceptation properties configurable

rudder-core/src/main/scala/com/normation/rudder/domain/nodes/Node.scala, rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala, rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala, rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchBackendImpl.scala, rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchDomain.scala, rudder-rest/src/main/scala/com/normation/rudder/rest/internal/RestQuicksearch.scala, rudder-rest/src/main/scala/com/normation/rudder/rest/lift/InfoApi.scala, rudder-rest/src/main/scala/com/normation/rudder/web/model/FilePermissions.scala, rudder-templates/src/test/scala/com/normation/templates/TemplateTest.scala, rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala, rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/AutoCompleteAutoSubmit.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/TechniqueEditForm.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/Util.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala
https://www.rudder-project.org/redmine/issues/4670
=> Fixes #4670: Allows inventories to be augmented by the user

rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala
https://www.rudder-project.org/redmine/issues/12110
=> Fixes #12110: Compilation error

rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupCategoryForm.scala
https://www.rudder-project.org/redmine/issues/11782
=> Fixes #11782: Update / Delete buttons on group Category modification should be separated

rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/CommonLayout.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/HomePage.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/Login.scala, rudder-web/src/main/webapp/index.html, rudder-web/src/main/webapp/templates-hidden/common-layout.html
https://www.rudder-project.org/redmine/issues/12093
=> Fixes #12093: Make Rudder UI pluggable (login + common layout)

rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
https://www.rudder-project.org/redmine/issues/5931
=> Fixes #5931: Api does not fail on bad JSON

rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PropertiesManagement.scala, rudder-web/src/main/webapp/secure/administration/policyServerManagement.html, rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/12129
=> Fixes #12129: Adapt style of Relay synchronization method to match 4.2 style

rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PropertiesManagement.scala
https://www.rudder-project.org/redmine/issues/12148
=> Fixes #12148: On Settings page, in branch 4.2, current value for Synchronization method from Relay servers is not selected

rudder-core/src/main/scala/com/normation/rudder/services/servers/PolicyServerManagementService.scala, rudder-core/src/test/scala/com/normation/rudder/services/policies/write/WriteSystemTechniquesTest.scala, rudder-web/src/main/scala/com/normation/rudder/appconfig/ConfigService.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/settings/SettingsApi.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PropertiesManagement.scala, rudder-web/src/main/webapp/secure/administration/policyServerManagement.html
https://www.rudder-project.org/redmine/issues/12150
Replacing previous PR: https://github.com/Normation/rudder/pull/1862
=> Fixes #12150: Cannot save relay synch method form twice

rudder-core/src/main/resources/hooks.d/policy-generation-node-ready/90-change-perm
https://www.rudder-project.org/redmine/issues/12169
=> Fixes #12169: Promises shared with apache are group executable

rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
https://www.rudder-project.org/redmine/issues/12174
=> Fixes #12174:  Rename class to condition in the interface

rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/EventLogJdbcRepository.scala, rudder-core/src/main/scala/com/normation/rudder/repository/json/JsonExctractorUtils.scala
https://www.rudder-project.org/redmine/issues/12200
=> Fixes #12200: Dependencies update consequences

rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala
https://www.rudder-project.org/redmine/issues/12034
=> Fixes #12034: On a fresh Rudder 4.3 centos6 install, error about ncf API in logs

rudder-core/src/main/scala/com/normation/rudder/services/policies/write/AgentSpecificLogic.scala, rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-two-directives/rules/cfengine-community/rudder_expected_reports.csv
https://www.rudder-project.org/redmine/issues/12225
=> Fixes #12225: Do not generate and copy rudder_expected_reports.csv anymore

rudder-rest/src/main/scala/com/normation/rudder/rest/RestDataSerializer.scala, rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala, rudder-rest/src/main/scala/com/normation/rudder/rest/internal/RestApiAccounts.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/RuleDisplayer.scala, rudder-web/src/main/webapp/javascript/rudder/angular/apiAccount.js, rudder-web/src/main/webapp/javascript/rudder/angular/nodeProperties.js, rudder-web/src/main/webapp/secure/administration/apiManagement.html, rudder-web/src/main/webapp/style/rudder/rudder-bootstrap.css, rudder-web/src/main/webapp/style/rudder/rudder-menu.css, rudder-web/src/main/webapp/style/rudder/rudder.css
https://www.rudder-project.org/redmine/issues/12202
=> Fixes #12202: Missing information/bad UX in API authorization UI 

rudder-rest/pom.xml, rudder-web/pom.xml, rudder-web/src/main/resources/applicationContext-security.xml, rudder-web/src/main/webapp/WEB-INF/web.xml
https://www.rudder-project.org/redmine/issues/12002
=> Fixes #12002: JS error when starting Rudder 4.3 with jetty 9

rudder-core/src/main/scala/com/normation/rudder/api/ApiAccountRepository.scala, rudder-rest/src/main/scala/com/normation/rudder/rest/internal/RestApiAccounts.scala
https://www.rudder-project.org/redmine/issues/12281
=> Fixes #12281: Filter out non-standard API token in API token management page

rudder-core/src/main/scala/com/normation/rudder/services/policies/write/Cf3PromisesFileWriterService.scala
https://www.rudder-project.org/redmine/issues/12314
=> Fixes #12314: Typo in agent build error "reource""

rudder-core/src/main/scala/com/normation/rudder/services/policies/write/BuildBundleSequence.scala
https://www.rudder-project.org/redmine/issues/12310
=> Fixes #12310: Add name of the parameter to bundle parameter when generation bundle sequence

rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala, rudder-core/src/test/resources/configuration-repository/dsc/ncf/50_techniques/technique_any/1.0/technique_any.ps1, rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/1.0/metadata.xml, rudder-core/src/test/scala/com/normation/rudder/ncf/TestTechniqueWriter.scala
https://www.rudder-project.org/redmine/issues/12289
=> Fixes #12289: Generate dsc technique parameter

rudder-core/src/main/scala/com/normation/rudder/api/ApiAccountDiff.scala, rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDiffMapper.scala
https://www.rudder-project.org/redmine/issues/12260
=> Fixes #12260: Error on first save after api token edit

rudder-core/src/main/scala/com/normation/rudder/services/queries/LdapQueryProcessor.scala
https://www.rudder-project.org/redmine/issues/12343
=> Fixes #12343: LDAP query checker must succeed when criteria is empty

rudder-core/src/main/scala/com/normation/rudder/services/queries/DynGroupService.scala, rudder-core/src/test/scala/com/normation/rudder/services/queries/TestPendingNodePolicies.scala
https://www.rudder-project.org/redmine/issues/12338
=> Fixes #12338: "Error when trying to find dependencies for that group" when accepting a node

rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeExpectedReportTest.scala, rudder-core/src/test/scala/com/normation/rudder/services/policies/write/PrepareTemplateVariableTest.scala
https://www.rudder-project.org/redmine/issues/12361
=> Fixes #12361: compilation error due to missing refactoring pieces

rudder-web/src/main/webapp/WEB-INF/web.xml
https://www.rudder-project.org/redmine/issues/12367
=> Fixes #12367: Bad session counting block user login after three session created

rudder-rest/src/main/scala/com/normation/rudder/rest/internal/RestApiAccounts.scala, rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/ApiAccounts.scala, rudder-web/src/main/webapp/javascript/rudder/angular/apiAccount.js, rudder-web/src/main/webapp/secure/administration/apiManagement.html
https://www.rudder-project.org/redmine/issues/12375
=> Fixes #12375: Make API account page pluggable

rudder-web/src/main/webapp/templates-hidden/components/ComponentNodeState.html
https://www.rudder-project.org/redmine/issues/12388
=> Fixes #12388: Node agent schedule cannot be changed due to a JS Error

rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeRepository.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/ShowNodeDetailsFromNode.scala
https://www.rudder-project.org/redmine/issues/12324
=> Fixes #12324: Root server can be disable with node lifecycle "ignore" "set empty policies"

rudder-web/src/main/webapp/style/rudder/rudder-menu.css, rudder-web/src/main/webapp/templates-hidden/components/ComponentNodeState.html
https://www.rudder-project.org/redmine/issues/12048
=> Fixes #12048: Lifecycle UI elements (dropdown menu & display) looks bad

rudder-web/src/main/webapp/javascript/rudder/homePage.js
https://www.rudder-project.org/redmine/issues/12358
=> Fixes #12358: Make dashboard graphs clickable

rudder-web/src/main/scala/com/normation/rudder/web/rest/group/GroupApi.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/rule/RuleApi.scala
https://www.rudder-project.org/redmine/issues/12419
=> Fixes #12419: Make Groups and Rules API accessible for internal use

rudder-core/src/test/scala/com/normation/cfclerk/domain/VariableTest.scala
https://www.rudder-project.org/redmine/issues/12424
=> Fixes #12424: Fix test on boolean variable

rudder-core/src/main/scala/com/normation/rudder/domain/queries/CmdbQuery.scala, rudder-core/src/main/scala/com/normation/rudder/domain/queries/DitQueryData.scala, rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala, rudder-core/src/main/scala/com/normation/rudder/services/queries/LdapQueryProcessor.scala, rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala, rudder-web/src/main/resources/ldapObjectAndAttributes.properties, rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/SearchNodeComponent.scala
https://www.rudder-project.org/redmine/issues/12380
=> Fixes #12380: Allow to search on machine type in search nodes request

rudder-core/src/main/scala/com/normation/rudder/domain/queries/CmdbQuery.scala, rudder-core/src/main/scala/com/normation/rudder/domain/queries/DitQueryData.scala, rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala, rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala
https://www.rudder-project.org/redmine/issues/12311
=> Fixes #12311: NodeGroupId picker for subgroup selection

rudder-web/src/main/webapp/javascript/rudder/homePage.js, rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/12438
=> Fixes #12438: Modify the mouse cursor when hovering the chart

rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala, rudder-web/src/main/webapp/secure/configurationManager/directiveManagement.html, rudder-web/src/main/webapp/style/rudder/rudder-directives.css
https://www.rudder-project.org/redmine/issues/11846
=> Fixes #11846: Display in web interface that technique support multivalued version

rudder-core/src/main/scala/com/normation/rudder/services/policies/JavascriptEngine.scala
https://www.rudder-project.org/redmine/issues/12448
=> Fixes #12448: java.lang.NoClassDefFoundError: Could not initialize class javax.crypto.JceSecurity

rudder-core/src/main/scala/com/normation/rudder/domain/nodes/NodeInfo.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/SystemVariableService.scala, rudder-core/src/test/scala/com/normation/rudder/domain/nodes/CFEngineRSAKeyHashTest.scala
https://www.rudder-project.org/redmine/issues/12458
=> Fixes #12458: Compute SHA key, and change key identification for enterprise node

rudder-web/src/main/webapp/secure/administration/apiManagement.html
https://www.rudder-project.org/redmine/issues/12518
=> Fixes #12518: Switch's css is broken on the Api accounts page

rudder-web/src/main/webapp/secure/utilities/eventLogs.html
https://www.rudder-project.org/redmine/issues/12515
=> Fixes #12515: Add space between filter and Event logs table

rudder-web/src/main/webapp/templates-hidden/components/directiveInput.html
https://www.rudder-project.org/redmine/issues/12514
=> Fixes #12514: CSS of txt/json inputs is broken

rudder-web/src/main/webapp/secure/utilities/archiveManagement.html
https://www.rudder-project.org/redmine/issues/12513
=> Fixes #12513: Add margin between selects and button groups in Archives page

rudder-web/src/main/webapp/secure/administration/policyServerManagement.html, rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/12236
=> Fixes #12236: Missing border in Default policy mode setting

rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
https://www.rudder-project.org/redmine/issues/12533
=> Fixes #12533: Wrong parameter used to create dsc ncf techniques

rudder-core/src/test/resources/configuration-repository/dsc/ncf/50_techniques/technique_any/1.0/technique_any.ps1
https://www.rudder-project.org/redmine/issues/12536
=> Fixes #12536: fix tests after changes in parent ticket

rudder-web/src/main/webapp/javascript/rudder/homePage.js, rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
https://www.rudder-project.org/redmine/issues/12429
=> Fixes #12429: make the compliance graph clickable

rudder-web/src/main/scala/com/normation/rudder/web/components/RuleDisplayer.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateOrUpdateGlobalParameterPopup.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/TechniqueLibraryManagement.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/ParameterManagement.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/Groups.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/SearchNodes.scala, rudder-web/src/main/webapp/secure/administration/apiManagement.html, rudder-web/src/main/webapp/secure/administration/techniqueLibraryManagement.html, rudder-web/src/main/webapp/secure/configurationManager/directiveManagement.html, rudder-web/src/main/webapp/secure/nodeManager/groups.html, rudder-web/src/main/webapp/style/rudder/rudder-groups.css, rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/12512
=> Fixes #12512: Buttons don't follow a straight design

rudder-web/src/main/scala/com/normation/rudder/web/components/RuleGrid.scala, rudder-web/src/main/webapp/style/rudder/rudder-menu.css, rudder-web/src/main/webapp/style/rudder/rudder.css
https://www.rudder-project.org/redmine/issues/12364
=> Fixes #12364: Inconsistent font for status of rule in accept new node page, when looking at the Rules to be applied

rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
https://www.rudder-project.org/redmine/issues/12585
=> Fixes #12585: Custom acl are not parsed by api account API 

rudder-web/src/main/scala/com/normation/rudder/web/components/popup/ModificationValidationPopup.scala
https://www.rudder-project.org/redmine/issues/12552
=> Fixes #12552: COnfirmation popup do not confirm

rudder-web/src/main/scala/com/normation/rudder/web/rest/node/NodeAPIService8.scala
https://www.rudder-project.org/redmine/issues/12556
=> Fixes #12556: NumberFormatException in NodeAPI 8 (runResponse)

rudder-web/src/main/scala/com/normation/rudder/web/comet/AsyncDeployment.scala, rudder-web/src/main/scala/com/normation/rudder/web/comet/WorkflowInformation.scala
https://www.rudder-project.org/redmine/issues/12644
=> Fixes #12644: Stacktrace when displaying comet components

rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala, rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SystemApi.scala, rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala
https://www.rudder-project.org/redmine/issues/12578
=> Fixes #12578: API : reload endpoints

rudder-core/src/main/resources/Migration/dbMigration-4.1.x-4.1.12-add-compliancelevel-table.sql, rudder-core/src/main/resources/reportsSchema.sql, rudder-core/src/main/scala/com/normation/rudder/batch/AutomaticReportsCleaner.scala, rudder-core/src/main/scala/com/normation/rudder/domain/reports/CleanReportsAction.scala, rudder-core/src/main/scala/com/normation/rudder/repository/ExpectedReportsRepository.scala, rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ComplianceRepository.scala, rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ExpectedReportsJdbcRepository.scala, rudder-core/src/main/scala/com/normation/rudder/services/system/DatabaseManager.scala, rudder-core/src/test/scala/com/normation/rudder/db/GenerateCompliance.scala, rudder-web/src/main/resources/configuration.properties.sample, rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala
https://www.rudder-project.org/redmine/issues/12621
=> Fixes #12621: Explore alternative format for compliance table

rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala
https://www.rudder-project.org/redmine/issues/12661
=> Fixes #12661: Rudder fails to boot because cleaning TTL property is added after rudder reboot by migration script

rudder-web/src/test/resources/rudder-js, rudder-web/src/test/scala/com/normation/rudder/javascript/CalculateComplianceTest.scala
https://www.rudder-project.org/redmine/issues/12682
=> Fixes #12682: JS test template

rudder-web/src/main/webapp/javascript/rudder/angular/filters.js
https://www.rudder-project.org/redmine/issues/12650
=> Fixes #12650: Directive  tree filter is very slow

rudder-web/src/main/webapp/javascript/rudder/angular/filters.js
https://www.rudder-project.org/redmine/issues/12690
=> Fixes #12690: Rule tree filter is a bit slow

rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
https://www.rudder-project.org/redmine/issues/12643
=> Fixes #12643: Compliance bar appears partially white in some graphes

rudder-web/src/main/webapp/javascript/rudder/angular/apiAccount.js
https://www.rudder-project.org/redmine/issues/12638
=> Fixes #12638: When deleting an API account the removed row is not the good one

rudder-web/src/main/scala/com/normation/rudder/web/rest/RestArchiving.scala
https://www.rudder-project.org/redmine/issues/12705
=> Fixes #12705: API : correct response

rudder-web/src/main/webapp/style/rudder/rudder.css
https://www.rudder-project.org/redmine/issues/12283
=> Fixes #12283: GUI problem with long strings in reporting

rudder-core/src/main/scala/com/normation/rudder/batch/AsyncDeploymentAgent.scala, rudder-core/src/main/scala/com/normation/rudder/services/ClearCacheService.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/nodeconfig/NodeConfigurationCacheRepository.scala, rudder-core/src/main/scala/com/normation/rudder/services/servers/RemoveNodeService.scala, rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala, rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SystemApi.scala, rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala, rudder-web/src/main/scala/com/normation/rudder/web/comet/AsyncDeployment.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/ClearCache.scala
https://www.rudder-project.org/redmine/issues/12623
=> Fixes #12623: API : policies update

rudder-web/src/main/resources/ldapObjectAndAttributes.properties
https://www.rudder-project.org/redmine/issues/12733
=> Fixes #12733: Correctly display in the web interface the Slackware

rudder-core/src/main/scala/com/normation/rudder/services/policies/write/Cf3PromisesFileWriterService.scala
https://www.rudder-project.org/redmine/issues/12725
=> Fixes #12725: We are missing a lot of timing measurement in policy generation

rudder-core/src/main/scala/com/normation/rudder/repository/xml/ItemArchiveManagerImpl.scala, rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala, rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SystemApi.scala, rudder-rest/src/main/scala/com/normation/rudder/rest/v1/RestArchiving.scala, rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala
https://www.rudder-project.org/redmine/issues/12695
=> Fixes #12695: API : archive endpoints

rudder-core/pom.xml, rudder-core/src/main/scala/com/normation/rudder/domain/queries/CmdbQuery.scala, rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala, rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala, rudder-core/src/main/scala/com/normation/rudder/services/queries/LdapQueryProcessor.scala, rudder-core/src/test/resources/ldap-data/inventory-sample-data.ldif, rudder-core/src/test/resources/ldap-data/schema/099-1-rudder.ldif, rudder-core/src/test/scala/com/normation/rudder/domain/queries/CmdbQueryTest.scala, rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala, rudder-core/src/test/scala/com/normation/rudder/services/policies/TestJsEngine.scala, rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala, rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala, rudder-templates/src/test/scala/com/normation/templates/TemplateTest.scala, rudder-web/src/main/resources/ldapObjectAndAttributes.properties, rudder-web/src/main/scala/com/normation/rudder/web/components/ShowNodeDetailsFromNode.scala, rudder-web/src/test/scala/com/normation/rudder/javascript/CalculateComplianceTest.scala
https://www.rudder-project.org/redmine/issues/12572
This PR: 
- change the way the backend is running for NodeInfo related properties (see description in ticket), 
- remove the save of custom inventory properties from rudder nodes
The part where JsonSelect via JSONPath is done is added in PR: https://github.com/Normation/rudder/pull/1961
=> Fixes #12572: node properties from inventory are not well loaded when executing queries on the web Interface

rudder-core/pom.xml, rudder-core/src/main/scala/com/normation/rudder/domain/queries/CmdbQuery.scala, rudder-core/src/main/scala/com/normation/rudder/domain/queries/JsonSelect.scala, rudder-core/src/test/resources/ldap-data/inventory-sample-data.ldif, rudder-core/src/test/scala/com/normation/rudder/domain/queries/JsonSelectTest.scala, rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala, rudder-web/src/main/resources/ldapObjectAndAttributes.properties
https://www.rudder-project.org/redmine/issues/9299
Explanation here: https://www.rudder-project.org/redmine/issues/9299#note-12
=> Fixes #9299: Extend groups search capabilities for complex JSON Properties / JsonPath

rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/write/BuildBundleSequence.scala, rudder-core/src/test/resources/configuration-repository/dsc/ncf/50_techniques/technique_by_Rudder/1.0/technique_by_Rudder.ps1, rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/Create_file/1.0/metadata.xml, rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/metadata.xml, rudder-core/src/test/scala/com/normation/rudder/ncf/TestTechniqueWriter.scala, rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala
https://www.rudder-project.org/redmine/issues/12743
=> Fixes #12743: Id of the ncf technique parameter used when generating Rudder technique parameter instead of it's name

rudder-web/src/main/resources/load-page/rudder-loading.html, rudder-web/src/main/resources/load-page/rudder-not-loaded.html
https://www.rudder-project.org/redmine/issues/12736
=> Fixes #12736: loading page and 404 page does not use correct style when redirected by apache

rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
https://www.rudder-project.org/redmine/issues/12754
=> Fixes #12754: No reports on dsc only techniques on a Linux Node

rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
https://www.rudder-project.org/redmine/issues/12758
=> Fixes #12758: Invalid policies generated when using an ncf Technique with generic method non compatible with the agent

rudder-web/src/main/scala/com/normation/rudder/web/comet/AsyncDeployment.scala, rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/11889
=> Fixes #11889: The red cross in case of generation problem is not visible enough

rudder-web/src/main/scala/com/normation/rudder/web/model/DirectiveEditor.scala
https://www.rudder-project.org/redmine/issues/12662
=> Fixes #12662: Some more buttons to make consistent

rudder-core/pom.xml, rudder-core/src/test/scala/com/normation/rudder/hooks/RunNuCommandTest.scala
https://www.rudder-project.org/redmine/issues/12604
There was a bug in NuProcess that was making child process inherit all file descriptors of the parent. They have corrected it 2 weeks ago :)
=> Fixes #12604: Generation gets stuck when cf-serverd is not running

rudder-core/src/main/scala/com/normation/rudder/domain/policies/Tags.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/RestExtractorService.scala
https://www.rudder-project.org/redmine/issues/12355
=> Fixes #12355: Tags in directives are ignored in POST API

rudder-core/src/main/scala/com/normation/rudder/domain/policies/Tags.scala
https://www.rudder-project.org/redmine/issues/12796
=> Fixes #12796: Compilation is broken with #12355 upmerge

rudder-web/src/main/scala/com/normation/rudder/web/comet/AsyncDeployment.scala, rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/12814
=> Fixes #12814: The generation status does not show ongoing generation anymore

rudder-web/src/main/webapp/javascript/rudder/angular/nodeProperties.js, rudder-web/src/main/webapp/style/rudder/rudder-menu.css, rudder-web/src/main/webapp/templates-hidden/components/ComponentNodeProperties.html
https://www.rudder-project.org/redmine/issues/12360
=> Fixes #12360: It's difficult to know if the node property added is valid json 

rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
https://www.rudder-project.org/redmine/issues/12893
=> Fixes #12893: In inventory, "motherboardid" is not the mother board id but the machine id

rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
https://www.rudder-project.org/redmine/issues/12919
=> Fixes #12919: Declared plugin APIs not correctly regirstered in Rudder

rudder-web/src/main/scala/com/normation/rudder/web/model/DirectiveEditor.scala
https://www.rudder-project.org/redmine/issues/12916
=> Fixes #12916: When we add a section in the directive editor, it clears the content of the previous section

rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala, rudder-core/src/test/resources/configuration-repository/dsc/ncf/50_techniques/technique_any/1.0/technique_any.ps1, rudder-core/src/test/resources/configuration-repository/dsc/ncf/50_techniques/technique_by_Rudder/1.0/technique_by_Rudder.ps1, rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/Create_file/1.0/Create_file.ps1, rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/metadata.xml, rudder-core/src/test/scala/com/normation/rudder/ncf/TestTechniqueWriter.scala
https://www.rudder-project.org/redmine/issues/12471
=> Fixes #12471: wrong text encoding in technique editor

rudder-web/src/main/webapp/javascript/rudder/angular/apiAccount.js, rudder-web/src/main/webapp/secure/administration/apiManagement.html
https://www.rudder-project.org/redmine/issues/12940
That variable is just not used anymore.
=> Fixes #12940: Can not create token

rudder-web/src/main/webapp/javascript/rudder/angular/apiAccount.js, rudder-web/src/main/webapp/secure/administration/apiManagement.html
https://www.rudder-project.org/redmine/issues/12947
=> Fixes #12947: JS error when changing the status of an api token

rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala, rudder-core/src/test/scala/com/normation/rudder/repository/ldap/InventoryNodeInfoCompatTest.scala
https://www.rudder-project.org/redmine/issues/12474
=> Fixes #12474: root node disapeared while upgrading from 4.1 to 4.3 on debian 9

rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala
https://www.rudder-project.org/redmine/issues/12988
=> Fixes #12988: NodeInfoCache is precise to the second but we need it to be precise to the millisecond

rudder-web/src/main/scala/com/normation/rudder/web/comet/AsyncDeployment.scala
https://www.rudder-project.org/redmine/issues/12668
=> Fixes #12668: Remove the "Update policy" button

rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala, rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/12923
=> Fixes #12923: Display Rudder Machine ID color scheme is surprising

rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/12816
=> Fixes #12816: Strange behavior of the generation status icon background

rudder-core/src/main/scala/com/normation/rudder/batch/AsyncDeploymentActor.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/write/AgentSpecificLogic.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/write/BuildBundleSequence.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PrepareTemplateVariables.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PromiseWriteDataStructures.scala
https://www.rudder-project.org/redmine/issues/12885
=> Fixes #12885: Make scale-out (relay) server a plugin

rudder-rest/src/test/scala/com/normation/rudder/web/rest/SystemApiTest.scala
https://www.rudder-project.org/redmine/issues/13028
Replacing previous PR: https://github.com/Normation/rudder/pull/2003
=> Fixes #13028: Compilation warnings in master

rudder-core/src/main/resources/Migration/dbMigration-4.1.x-4.1.12-add-compliancelevel-table.sql
https://www.rudder-project.org/redmine/issues/13084
=> Fixes #13084: Add back missing migration script in 5.0

rudder-core/src/main/scala/com/normation/rudder/services/workflows/WorkflowService.scala, rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala, rudder-core/src/test/scala/com/normation/rudder/services/policies/write/PathComputerTest.scala, rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala, rudder-web/src/main/scala/com/normation/plugins/ExtendableSnippet.scala, rudder-web/src/main/scala/com/normation/plugins/PluginStatus.scala
https://www.rudder-project.org/redmine/issues/13073
=> Fixes #13073: Missing real-time check of license capabilities for api and others plugins

rudder-core/src/main/scala/com/normation/rudder/hooks/RunHooks.scala, rudder-core/src/main/scala/com/normation/rudder/hooks/RunNuCommand.scala, rudder-core/src/main/scala/com/normation/rudder/services/system/SupportInfoService.scala, rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala, rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SystemApi.scala, rudder-rest/src/test/scala/com/normation/rudder/web/rest/RestTestSetUp.scala, rudder-rest/src/test/scala/com/normation/rudder/web/rest/SystemApiTest.scala, rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/SupportScript.scala, rudder-web/src/main/webapp/secure/administration/policyServerManagement.html
https://www.rudder-project.org/redmine/issues/13008
=> Fixes #13008: Make the support info script available from the rudder interface

rudder-core/src/main/scala/com/normation/rudder/services/system/SupportInfoService.scala, rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SystemApi.scala, rudder-rest/src/test/scala/com/normation/rudder/web/rest/RestTestSetUp.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/SupportScript.scala, rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/13227
=> Fixes #13227: Incorrect name of support info file result used

rudder-web/src/main/scala/com/normation/rudder/web/components/SearchNodeComponent.scala, rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PropertiesManagement.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/SearchNodes.scala, rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js, rudder-web/src/main/webapp/secure/index.html, rudder-web/src/main/webapp/secure/nodeManager/manageNewNode.html, rudder-web/src/main/webapp/style/rudder/rudder-bootstrap.css, rudder-web/src/main/webapp/style/rudder/rudder-menu.css, rudder-web/src/main/webapp/style/rudder/rudder-rules.css, rudder-web/src/main/webapp/style/rudder/rudder.css, rudder-web/src/main/webapp/templates-hidden/components/ComponentComplianceMode.html, rudder-web/src/main/webapp/templates-hidden/components/ComponentNodeProperties.html, rudder-web/src/main/webapp/templates-hidden/components/ComponentTechniqueEditForm.html, rudder-web/src/main/webapp/templates-hidden/components/passwordInput.html, rudder-web/src/main/webapp/templates-hidden/node_logs_tabs.html, rudder-web/src/main/webapp/templates-hidden/server/server_details.html
https://www.rudder-project.org/redmine/issues/13078
=> Fixes #13078: Remove the "tw-bs" css hack (part 2)

rudder-templates-cli/src/main/scala/com/normation/templates/cli/TemplateCli.scala
https://www.rudder-project.org/redmine/issues/13343
=> Fixes #13343: IOUtils import also removed by error in Rudder

rudder-web/src/main/webapp/javascript/rudder/angular/auditMode.js
https://www.rudder-project.org/redmine/issues/13356
=> Fixes #13356: "//" in rudder-web/secure/api//settings/global_policy_mode cause browser/spring error

rudder-web/src/main/webapp/style/rudder/rudder-bootstrap.css, rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/13362
=> Fixes #13362: Clicking on Status/Details leads to a disabled screen in Rudder 5.0

rudder-web/src/main/webapp/style/rudder/rudder-bootstrap.css
https://www.rudder-project.org/redmine/issues/13372
=> Fixes #13372: In directives pages, Text selector and input field are not correctly allligned in Rudder 5.0

rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/13368
=> Fixes #13368: Save button in group page is not readable in Rudder 5.0

rudder-web/src/main/webapp/style/rudder/rudder-menu.css, rudder-web/src/main/webapp/style/rudder/rudder.css
https://www.rudder-project.org/redmine/issues/13364
=> Fixes #13364: Fonts changed in Rudder 5.0

rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala
https://www.rudder-project.org/redmine/issues/13416
=> Fixes #13416: Rudder system api token only have RO access

rudder-web/src/main/resources/applicationContext-security.xml
https://www.rudder-project.org/redmine/issues/13426
=> Fixes #13426: POST/PUT/DELETE API requests gives 403

rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ComplianceRepository.scala
https://www.rudder-project.org/redmine/issues/13427
=> Fixes #13427: On error on nodecompliance SQL, logs are huge

rudder-web/src/main/scala/com/normation/rudder/web/model/DirectiveFieldEditors.scala, rudder-web/src/main/webapp/style/rudder/rudder-bootstrap.css, rudder-web/src/main/webapp/templates-hidden/components/passwordInput.html
https://www.rudder-project.org/redmine/issues/13446
=> Fixes #13446: In Rudder 5.0, Password fields in directive is empty

README.asciidoc, rudder-core/src/main/scala/com/normation/rudder/services/reports/NodeChangesService.scala, rudder-web/src/main/resources/demo-rudder-users.xml, rudder-web/src/main/scala/com/normation/rudder/web/components/RuleCompliance.scala, rudder-web/src/main/webapp/secure/administration/policyServerManagement.html, rudder-web/src/main/webapp/templates-hidden/common-layout.html, rudder-web/src/main/webapp/templates-hidden/components/passwordInput.html
https://www.rudder-project.org/redmine/issues/13445
=> Fixes #13445: Use new doc links in Rudder

rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/RuleManagement.scala
https://www.rudder-project.org/redmine/issues/13469
=> Fixes #13469: JS error when loading Rules pages

rudder-web/src/main/webapp/style/rudder/rudder.css
https://www.rudder-project.org/redmine/issues/13417
=> Fixes #13417: fields are not correctly aligned in group page

rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala, rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SystemApi.scala, rudder-rest/src/test/scala/com/normation/rudder/web/rest/SystemApiTest.scala
https://www.rudder-project.org/redmine/issues/13471
=> Fixes #13471: Harmonize URLs of system API

rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SystemApi.scala
https://www.rudder-project.org/redmine/issues/13488
=> Fixes #13488: Adapt Archives POST output

rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/Groups.scala
https://www.rudder-project.org/redmine/issues/13428
=> Fixes #13428: Dual scrolling bars on the right of group details in Rudder 5
