Normation/rudder

rudder-web/src/main/webapp/javascript/rudder/angular/nodeProperties.js

https://www.rudder-project.org/redmine/issues/13456

Fixes #13456: Tooltip on the source of property is not dislpayed in Rudder 5.0

---

rudder-web/src/main/webapp/style/rudder/rudder-menu.css

https://www.rudder-project.org/redmine/issues/13168

Fixes #13168: Blue text color in node details tabs

---

rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/RudderDatasourceProvider.scala

https://www.rudder-project.org/redmine/issues/13582

Fixes #13582: Hikari pool autocomit is badly configured, which can impact performance

---

rudder-core/src/main/scala/com/normation/rudder/migration/XmlEntityMigration.scala
rudder-core/src/main/scala/com/normation/rudder/migration/XmlFileFormatMigrationEntities.scala
rudder-core/src/main/scala/com/normation/rudder/reports/execution/LastProcessedReportRepository.scala
rudder-core/src/main/scala/com/normation/rudder/reports/execution/ReportsExecutionRepositoryImpl.scala
rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ComplianceRepository.scala
rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/EventLogJdbcRepository.scala
rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ExpectedReportsJdbcRepository.scala
rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/GitModificationRepository.scala
rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ReportsJdbcRepository.scala
rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/RudderPropertiesRepository.scala
rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ExpectedReportTest.scala

https://www.rudder-project.org/redmine/issues/13517

Fixes #13517: Policy generation fails definitively when postgresql is shut down during policy generation

---

rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala

https://www.rudder-project.org/redmine/issues/13629

Fixes #13629: Api User Account doesn't have User role

---

rudder-web/src/main/scala/bootstrap/liftweb/RudderUserDetails.scala
rudder-web/src/test/scala/bootstrap/liftweb/RudderUserDetailsTest.scala

https://www.rudder-project.org/redmine/issues/13643

Fixes #13643: In Rudder 5.0, user password encoding is broken for some passwords. 

---

rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala

https://www.rudder-project.org/redmine/issues/13649

Fixes #13649: Node group with 'OR' multi criteria fails

---

rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala

https://www.rudder-project.org/redmine/issues/13653

Fixes #13653: fix test after 13649

---

rudder-core/src/main/scala/com/normation/rudder/services/queries/LdapQueryProcessor.scala
rudder-core/src/test/resources/ldap-data/inventory-sample-data.ldif
rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala

https://www.rudder-project.org/redmine/issues/13424

Fixes #13424: Group of group is empty if we use the AND combinator

---

rudder-web/src/main/webapp/style/rudder/rudder.css

https://www.rudder-project.org/redmine/issues/13694

Fixes #13694: Broken display of popup to delete node property in Rudder 5.0.1

---

rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala
rudder-web/src/main/scala/com/normation/rudder/web/components/TechniqueEditForm.scala
rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala
rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/TechniqueLibraryManagement.scala
rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala
rudder-web/src/main/webapp/secure/configurationManager/directiveManagement.html
rudder-web/src/main/webapp/style/rudder/rudder-menu.css
rudder-web/src/main/webapp/style/rudder/rudder.css
rudder-web/src/main/webapp/templates-hidden/components/ComponentDirectiveEditForm.html
rudder-web/src/main/webapp/templates-hidden/components/ComponentTechniqueEditForm.html

https://www.rudder-project.org/redmine/issues/12829

Fixes #12829:  We have no way to know that a Technique is disabled

---

rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala

https://www.rudder-project.org/redmine/issues/13776

Fixes #13776: Fix compiling issue after "disabled Technique" display was upmerged in 5.0

---

rudder-core/src/main/resources/ldap/bootstrap.ldif

https://www.rudder-project.org/redmine/issues/13792

Fixes #13792: Init check on group All classic Nodes known by Rudder (Using a CFEngine based agent) always tries to rewrite the group

---

rudder-web/src/main/webapp/style/rudder/rudder-jquery-ui.css

https://issues.rudder.io/issues/13688

Fixes #13688: In accept new nodes, the hardware tabs don't show up (css?)

---

rudder-web/src/main/webapp/style/rudder/rudder.css

https://issues.rudder.io/issues/13511

Fixes #13511: In directive page, tooltip is not correctly aligned with text 

---

rudder-core/src/test/resources/ldap-data/inventory-sample-data.ldif
rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala

https://issues.rudder.io/issues/13772

Fixes #13772: Network group criteria not working

---

rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala

https://issues.rudder.io/issues/13779

Fixes #13779: Button to enable a technique in Directive Screen is not working, should be a link to the Technique

---

rudder-web/src/main/scala/com/normation/rudder/web/rest/RestExtractorService.scala

https://issues.rudder.io/issues/13374

Fixes #13374:  Tags in rules are ignored in POST API

---

rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala

https://issues.rudder.io/issues/13815

Fixes #13815: Adding tests in #13772 borke other ones

---

rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala

https://issues.rudder.io/issues/13804

Fixes #13804: Missing gateway, network in network interface details

---

rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala

https://issues.rudder.io/issues/13418

Fixes #13418: Invalid value reported for Node expected reports saved in base in Rudder log

---

rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/DatabaseManagement.scala
rudder-web/src/main/webapp/style/rudder/rudder.css

https://issues.rudder.io/issues/13476

Fixes #13476: Bad display of radio button on the Reports Database page in Rudder 5.0

---

rudder-web/src/main/webapp/secure/administration/policyServerManagement.html

https://issues.rudder.io/issues/12462

Fixes #12462: "Configure the default state" is lacking explanations

---

rudder-web/src/main/webapp/templates-hidden/components/passwordInput.html

https://issues.rudder.io/issues/13457

Fixes #13457: Remove static ids in Password section

---

rudder-web/src/main/webapp/secure/administration/policyServerManagement.html

https://issues.rudder.io/issues/13820

Fixes #13820: Correct link for documentation of states in Rudder 5.0

---

rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PolicyWriterService.scala

https://issues.rudder.io/issues/10917

Fixes #10917: "Not copying missing license file into" in webapp log

---

rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SystemApi.scala
rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala

https://issues.rudder.io/issues/13654

Fixes #13654: [API] Can you add rudder server version to the API ?

---

rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
rudder-web/src/main/resources/logback.xml

https://issues.rudder.io/issues/9512

Fixes #9512: Bad log level during generation

---

rudder-web/src/main/webapp/secure/administration/policyServerManagement.html
rudder-web/src/main/webapp/style/rudder/rudder-directives.css
rudder-web/src/main/webapp/style/rudder/rudder-menu.css

https://issues.rudder.io/issues/13512

Fixes #13512: Imperfect alignement of radio button

---

rudder-web/src/main/webapp/javascript/rudder/homePage.js

https://issues.rudder.io/issues/12233

Fixes #12233: On Dashboard, when we have 100% of something, the pie is including a confusing white line

---

rudder-web/src/main/webapp/style/rudder/rudder-menu.css

https://issues.rudder.io/issues/12926

Fixes #12926: No color difference on hover on the user menu

---

rudder-core/src/main/scala/com/normation/rudder/services/servers/RemoveNodeService.scala
rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala

https://issues.rudder.io/issues/9149

Fixes #9149: Inventory keeps its key certified when node is deleted

---

rudder-web/src/main/scala/com/normation/rudder/web/model/DirectiveFieldEditors.scala
rudder-web/src/main/scala/com/normation/rudder/web/services/AsyncComplianceService.scala
rudder-web/src/main/webapp/javascript/rudder/angular/passwordForm.js
rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js

https://issues.rudder.io/issues/12649

Fixes #12649: Spinning compliance in nodes list on a disabled node

---

rudder-core/src/main/scala/com/normation/rudder/services/servers/RemoveNodeService.scala

https://issues.rudder.io/issues/5154

Fixes #5154: Node key not deleted after deleting a node in the web ui

---

rudder-web/src/main/scala/com/normation/rudder/web/model/DirectiveFieldEditors.scala
rudder-web/src/main/webapp/javascript/rudder/angular/passwordForm.js

https://issues.rudder.io/issues/12198

Fixes #12198: The password field allows storing a password without any selected hash

---

rudder-web/src/main/webapp/style/rudder/rudder-menu.css

https://issues.rudder.io/issues/13835

Fixes #13835: Fix datatable headers text color

---

rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js

https://issues.rudder.io/issues/13840

Fixes #13840: Default number of nodes displayed is one

---

rudder-core/src/main/scala/com/normation/rudder/services/policies/InterpolatedValueCompiler.scala

https://issues.rudder.io/issues/13841

Fixes #13841: cannot use policyMode variable in directive due to case matching

---

rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala

https://issues.rudder.io/issues/13845

Fixes #13845: After a node is deleted, a policy generation is started every 5 secondes

---

rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala

https://issues.rudder.io/issues/13910

Fixes #13910: Root admin account login throws exception

---

rudder-web/src/main/webapp/style/rudder/rudder-menu.css

https://issues.rudder.io/issues/13889

Fixes #13889: Alignement of radio button on Settings page is still imperfect

---

.gitignore
rudder-web/src/main/scala/com/normation/rudder/web/components/AgentScheduleEditForm.scala
rudder-web/src/main/scala/com/normation/rudder/web/components/ComplianceModeEditForm.scala
rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala
rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupCategoryForm.scala
rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
rudder-web/src/main/scala/com/normation/rudder/web/components/RuleEditForm.scala
rudder-web/src/main/scala/com/normation/rudder/web/components/TechniqueCategoryEditForm.scala
rudder-web/src/main/scala/com/normation/rudder/web/components/TechniqueEditForm.scala
rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/Archives.scala
rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/ClearCache.scala
rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/DyngroupReloading.scala
rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/EditPolicyServerAllowedNetwork.scala
rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PropertiesManagement.scala
rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/SupportScript.scala
rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/TechniqueLibraryManagement.scala
rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/ParameterManagement.scala
rudder-web/src/main/webapp/elm/rudder-notifications/build-app.sh
rudder-web/src/main/webapp/elm/rudder-notifications/elm-package.json
rudder-web/src/main/webapp/elm/rudder-notifications/sources/rudder-notifications.elm
rudder-web/src/main/webapp/javascript/rudder/angular/auditMode.js
rudder-web/src/main/webapp/javascript/rudder/angular/complianceMode.js
rudder-web/src/main/webapp/javascript/rudder/elm/rudder-elm.js
rudder-web/src/main/webapp/secure/administration/policyServerManagement.html
rudder-web/src/main/webapp/style/rudder/rudder-notifications.css
rudder-web/src/main/webapp/templates-hidden/common-layout.html
rudder-web/src/main/webapp/templates-hidden/components/ComponentAgentPolicyMode.html
rudder-web/src/main/webapp/templates-hidden/components/ComponentAgentSchedule.html
rudder-web/src/main/webapp/templates-hidden/components/ComponentComplianceMode.html

https://issues.rudder.io/issues/9629

Fixes #9629: Replace non important popups by notifications

---

rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PolicyWriterService.scala
rudder-templates/src/main/scala/com/normation/templates/FillTemplatesService.scala

https://issues.rudder.io/issues/13987

Fixes #13987: Massive performance penalty in policy generation due to invalid usage of StringTemplate

---

rudder-core/src/main/scala/com/normation/rudder/db/Doobie.scala

https://issues.rudder.io/issues/14014

Fixes #14014: A lot of space is wasted on table nodecompliance due to pretty jsonification

---

rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala

https://issues.rudder.io/issues/13834

Fixes #13834: In the node details, clicking on the link to the policy server doesn't redirect to the policy server

---

rudder-core/src/main/resources/Migration/dbMigration-4.3.x-4.3.8-correct-indexes-on-compliancelevel.sql
rudder-core/src/main/resources/reportsSchema.sql

https://issues.rudder.io/issues/14007

Fixes #14007: indexes on nodecompliancelevels table are not valid and table ArchivedReportsExecution is never used

---

rudder-core/src/main/resources/hooks.d/policy-generation-finished/50-reload-policy-file-server

https://issues.rudder.io/issues/14057

Fixes #14057: Move reload cf-serverd to hook directly

---

rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/RudderDatasourceProvider.scala

https://issues.rudder.io/issues/14056

Fixes #14056: Change request cannot be created -  "Couldn't find newly created entry when saving Change Request"

---

rudder-core/src/main/resources/Migration/dbMigration-4.3.x-4.3.8-correct-indexes-on-compliancelevel.sql

https://issues.rudder.io/issues/14107

Fixes #14107: Syntax error in migration script

---

rudder-core/src/main/scala/com/normation/rudder/batch/AsyncDeploymentAgent.scala
rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala
rudder-web/src/main/scala/bootstrap/liftweb/checks/TriggerPolicyUpdate.scala

https://issues.rudder.io/issues/14050

Fixes #14050: Missing flag file to trigger a policy generation

---

rudder-web/src/main/scala/bootstrap/liftweb/checks/TriggerPolicyUpdate.scala

https://issues.rudder.io/issues/14119

Fixes #14119: Compilation error on 5.0 after generation flag feature

---

rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala

https://issues.rudder.io/issues/14138

Fixes #14138: Add handling of specific log message for ol agent

---

rudder-core/src/main/resources/reportsSchema.sql

https://issues.rudder.io/issues/14149

Fixes #14149: Index nodeid_idx is not used and consumes a lot of disk space for nothing

---

rudder-core/src/main/scala/com/normation/rudder/ncf/Technique.scala
rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/1.0/metadata.xml
rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/metadata.xml
rudder-core/src/test/scala/com/normation/rudder/ncf/TestTechniqueWriter.scala
rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala

https://issues.rudder.io/issues/14091

Fixes #14091: Configure report value of technique from technique editor

---

rudder-web/src/main/webapp/style/rudder/rudder-menu.css

https://issues.rudder.io/issues/14199

Fixes #14199: API token expiration date form appears behind the popup

---

rudder-web/src/main/webapp/style/rudder/rudder-directives.css

https://issues.rudder.io/issues/14185

Fixes #14185: Enable/DIsable button text should be capitalized

---

rudder-web/src/main/scala/com/normation/rudder/web/components/RuleEditForm.scala
rudder-web/src/main/scala/com/normation/rudder/web/components/RuleGrid.scala
rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateRulePopup.scala
rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/RuleManagement.scala
rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js

https://issues.rudder.io/issues/4904

Fixes #4904: When refreshing a rule details, the current tab is not memorized

---

rudder-web/src/main/webapp/index.html

https://issues.rudder.io/issues/14205

Fixes #14205: Update links in Rudder interface

---

rudder-web/src/main/scala/com/normation/rudder/web/snippet/WithCachedResource.scala
rudder-web/src/main/webapp/secure/utilities/techniqueEditor.html

https://issues.rudder.io/issues/14212

Fixes #14212: In technique editor, ncf index is cached which defeats #14194 correction on migration

---

rudder-core/src/main/resources/reportsSchema.sql

https://issues.rudder.io/issues/14218

Fixes #14218: Constraint on table nodecompliancelevels are not valid

---

rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateRulePopup.scala

https://issues.rudder.io/issues/14219

Fixes #14219: A var, leading to compilation error, was introduced

---

rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala

https://issues.rudder.io/issues/14220

Fixes #14220: Log "Missing API authorizations level kind for token 'admin' with id 'admin'"

---

rudder-web/src/main/scala/com/normation/rudder/web/services/JsTableData.scala
rudder-web/src/main/scala/com/normation/rudder/web/services/LogDisplayer.scala
rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js

https://issues.rudder.io/issues/14221

Fixes #14221: (un)escape html entities where needed

---

rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/ChangeRequestManagement.scala

https://issues.rudder.io/issues/14231

Fixes #14231: 

---

rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala

https://issues.rudder.io/issues/14234

Fixes #14234: Component is not configured on windows dsc technique 

---

rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
rudder-core/src/test/resources/configuration-repository/dsc/ncf/50_techniques/technique_any/1.0/technique_any.ps1
rudder-core/src/test/resources/configuration-repository/dsc/ncf/50_techniques/technique_by_Rudder/1.0/technique_by_Rudder.ps1

https://issues.rudder.io/issues/14236

Fixes #14236: escape component Name on windows (and fix tests )

---

rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala

https://issues.rudder.io/issues/14243

Fixes #14243: Rudder node id is confused with machine id and not selectable by triple-click

---

rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/RuleManagement.scala

https://issues.rudder.io/issues/14245

Fixes #14245: Error when creating a rule

---

rudder-core/pom.xml

https://issues.rudder.io/issues/14248

Fixes #14248: Duplicate dependency "jsr305" in rudder-core/pom.xml

---

rudder-templates-cli/pom.xml

https://issues.rudder.io/issues/14247

Fixes #14247: Update very old maven-assembly version used for template-cli

---

rudder-web/src/main/scala/com/normation/rudder/web/components/RuleGrid.scala

https://issues.rudder.io/issues/14271

Fixes #14271: JS in directive name is executed on rule table if the directive is disabled

---

rudder-core/src/main/scala/com/normation/rudder/domain/reports/ComplianceLevel.scala
rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
rudder-web/src/main/webapp/style/rudder/rudder.css

https://issues.rudder.io/issues/10773

Fixes #10773: Rounding error in compliance bar

---

rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js

https://issues.rudder.io/issues/14272

Fixes #14272: Sort by compliance broken

---

webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/PostUnmarshallCheckConsistency.scala
webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-report/windows2016-incomplete.ocs
webapp/sources/ldap-inventory/inventory-fusion/src/test/scala/com/normation/inventory/provisioning/fusion/TestReportParsing.scala

https://issues.rudder.io/issues/13962

Fixes #13962: Mandatory fields in the Inventory are not correctly checked during consistency check

---

qa-test

https://issues.rudder.io/issues/14289

Fixes #14289: qa-test break because of repository layout change

---

webapp/sources/rudder-parent-pom/pom.xml
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/db/Doobie.scala

https://issues.rudder.io/issues/14290

Fixes #14290: Compilation fails with Java 11

---

webapp/sources/scala-ldap/src/main/scala/com/normation/ldap/sdk/LDAPEntry.scala
webapp/sources/scala-ldap/src/main/scala/com/normation/ldap/sdk/LDAPTree.scala

https://issues.rudder.io/issues/14291

Fixes #14291: Remove deprecated (and not use) code causing warning

---

webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-progress-bar.css

https://issues.rudder.io/issues/14294

Fixes #14294: Fix compliance bars text color

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/HistorizationService.scala

https://issues.rudder.io/issues/14346

Fixes #14346: We are comparing Option[String] and String

---

README.asciidoc

https://issues.rudder.io/issues/14283

Fixes #14283: Improve Rudder README in the repo

---

webapp/sources/rudder/rudder-core/src/main/resources/Migration/dbMigration-5.0.x-5.0.7-tune-autovacuum_on_table_basis.sql
webapp/sources/rudder/rudder-core/src/main/resources/reportsSchema.sql

https://issues.rudder.io/issues/14336

Fixes #14336: Rudder database grows with time because of defaults values for  autovacuum that don't fit our needs

---

webapp/sources/rudder/rudder-templates/src/main/scala/com/normation/templates/FillTemplatesService.scala

https://issues.rudder.io/issues/14322

Fixes #14322: directives are mixed

---

webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/NodeInventory.scala
webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/FusionReportUnmarshaller.scala
webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-report/windows2019.ocs
webapp/sources/ldap-inventory/inventory-fusion/src/test/scala/com/normation/inventory/provisioning/fusion/TestReportParsing.scala
webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/InventoryMapper.scala
webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/LDAPConstants.scala
webapp/sources/rudder/rudder-web/src/main/resources/ldapObjectAndAttributes.properties

https://issues.rudder.io/issues/14362

Fixes #14362: Windows 2019 doesn't show up correctly in node list

---

qa-test
webapp/sources/ldap-inventory/inventory-provisioning-web/pom.xml
webapp/sources/rudder-parent-pom/pom.xml
webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-finished/60-trigger-node-update
webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-finished/60-trigger-node-update.properties
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
webapp/sources/rudder/rudder-core/src/test/resources/hooks.d/test-hooks.sh
webapp/sources/rudder/rudder-web/pom.xml
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PropertiesManagement.scala
webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/policyServerManagement.html

https://issues.rudder.io/issues/14331

Fixes #14331: We are forced to wait agent next run before getting a newly generated policy applied

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleCompliance.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/EventListDisplayer.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/NodeGrid.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/TechniqueLibraryManagement.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/ParameterManagement.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/PendingHistoryGrid.scala
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder.js
webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/apiManagement.html
webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/parameterManagement.html
webapp/sources/rudder/rudder-web/src/main/webapp/secure/utilities/eventLogs.html
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-bootstrap.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-datatable.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-directives.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-groups.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-rules.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder.css
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/Popup/accept_new_server.html
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/Popup/expected_policy_popup.html
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/Popup/refuse_new_server.html
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/common-layout.html

https://issues.rudder.io/issues/9557

Fixes #9557: Change Datatables style

---

webapp/sources/rudder/rudder-core/src/main/resources/Migration/dbMigration-4.1.x-4.1.21-drop-rulesgroupjoin-constraint.sql
webapp/sources/rudder/rudder-core/src/main/resources/reportsSchema.sql

https://issues.rudder.io/issues/14392

Fixes #14392: If rules uses too much groups, policy generation fails because historisation fails

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/AgentSpecificLogic.scala

https://issues.rudder.io/issues/14426

Fixes #14426: Typo in error message when aix plugin is not there

---

webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-datatable.css

https://issues.rudder.io/issues/14463

Fixes #14463: Fix some CSS issues following the style change of the Datatables

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestDataSerializer.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/NodeDetailLevel.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/7922

Fixes #7922: [API] Extend node information by "Last seen"

---

webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/NodeInventory.scala
webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/FusionReportUnmarshaller.scala
webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/InventoryMapper.scala
webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/LDAPConstants.scala
webapp/sources/rudder/rudder-web/src/main/resources/ldapObjectAndAttributes.properties

https://issues.rudder.io/issues/14295

Fixes #14295: Windows 10 inventory is not fully supported

---

webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/FullInventoryRepositoryImpl.scala

https://issues.rudder.io/issues/14522

Fixes #14522: Error about fail move of machine doesn't give sufficient context information

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/model/JsInitContextLinkUtil.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleGrid.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateCategoryOrGroupPopup.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateCloneGroupPopup.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNodeGroupTree.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/Groups.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/SearchNodes.scala
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/NodeGroupForm.html

https://issues.rudder.io/issues/11796

Fixes #11796: System groups should display their list of nodes 

---

webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-finished/60-trigger-node-update.properties
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PropertiesManagement.scala

https://issues.rudder.io/issues/14386

Fixes #14386: UI management of 10-cf-promise-check works inconsistently

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/NewNodeManager.scala

https://issues.rudder.io/issues/14430

Fixes #14430: We can successfully accept a node even if Node entry wasn't created

---

webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/RudderUncaughtExceptionExample.scala

https://issues.rudder.io/issues/14281

Fixes #14281: Error at rudder restart liftActor:NoClassDefFoundError

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala

https://issues.rudder.io/issues/14380

Fixes #14380: Misleading message on node compliance when node has report out of date

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/NodeDetailLevel.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/Groups.scala

https://issues.rudder.io/issues/14552

Fixes #14552: API node details "lastRunDate" only available for node list

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PropertiesManagement.scala

https://issues.rudder.io/issues/14550

Fixes #14550:  UI "settings" for management of hooks need Unix right

---

webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentRuleEditForm.html

https://issues.rudder.io/issues/14573

Fixes #14573: JS error in rule pages, and Directives don't show in the list of directives

---

webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js

https://issues.rudder.io/issues/14434

Fixes #14434: There is no visual indication of current sort in node list table

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleEditForm.scala
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-groups.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-rules.css
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentRuleEditForm.html

https://issues.rudder.io/issues/14611

Fixes #14611: We cannot remove excluded groups from the list

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/AcceptNode.scala
webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/manageNewNode.html
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder.css

https://issues.rudder.io/issues/14478

Fixes #14478: Select/deselect all is not correctly positionned in Accept new node

---

webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-node-ready/90-change-perm

https://issues.rudder.io/issues/14594

Fixes #14594: policies generated by rudder 5.0 have wrong permission for root

---

webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-node-ready/90-change-perm

https://issues.rudder.io/issues/14626

Fixes #14626: parent ticket broke agent on the server

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleEditForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNodeGroupTree.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/groupManagement.js
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-rules.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder.css

https://issues.rudder.io/issues/14619

Fixes #14619: Group/directive selection in rule not consistant

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNodeGroupTree.scala
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-rules.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder.css

https://issues.rudder.io/issues/14629

Fixes #14629: Buttons to select Groups or Directives in Rule details are too small

---

relay/sources/relayd/Cargo.lock
relay/sources/relayd/Cargo.toml
relay/sources/relayd/src/lib.rs
relay/sources/relayd/src/processing.rs
relay/sources/relayd/tests/reports_database.rs

https://issues.rudder.io/issues/14658

Fixes #14658: Set correct dev version number in cargo.toml

---

relay/sources/Makefile
relay/sources/docopt.py
relay/sources/openssl.cnf
relay/sources/relay-api/.gitignore
relay/sources/relay-api/README
relay/sources/relay-api/apache/relay-api.wsgi
relay/sources/relay-api/cleanup.sh
relay/sources/relay-api/nodeslist.json.example
relay/sources/relay-api/relay_api/__init__.py
relay/sources/relay-api/relay_api/common.py
relay/sources/relay-api/relay_api/remote_run.py
relay/sources/relay-api/relay_api/shared_files.py
relay/sources/relay-api/relay_api/views.py
relay/sources/relay-api/requirements.txt
relay/sources/relay-api/run.py
relay/sources/rudder-apache-relay-common.conf
relay/sources/rudder-apache-relay-nossl.conf
relay/sources/rudder-apache-relay-ssl.conf
relay/sources/rudder-networks-24.conf
relay/sources/rudder-networks-policy-server-24.conf
relay/sources/rudder-pkg
relay/sources/rudder-relay-apache
relay/sources/rudder-relay.cron
relay/sources/rudder-relay.fc
relay/sources/rudder-relay.sudo
relay/sources/rudder-relay.te
relay/sources/rudder-vhost.conf

https://issues.rudder.io/issues/14660

Fixes #14660: Import relay sources into rudder repo

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SystemApi.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/web/rest/SystemApiTest.scala

https://issues.rudder.io/issues/14652

Fixes #14652: Api tests are broken  

---

relay/sources/Makefile
relay/sources/docopt.py
relay/sources/openssl.cnf
relay/sources/relay-api/.gitignore
relay/sources/relay-api/README
relay/sources/relay-api/apache/relay-api.wsgi
relay/sources/relay-api/cleanup.sh
relay/sources/relay-api/nodeslist.json.example
relay/sources/relay-api/relay_api/__init__.py
relay/sources/relay-api/relay_api/common.py
relay/sources/relay-api/relay_api/remote_run.py
relay/sources/relay-api/relay_api/shared_files.py
relay/sources/relay-api/relay_api/views.py
relay/sources/relay-api/requirements.txt
relay/sources/relay-api/run.py
relay/sources/rudder-apache-relay-common.conf
relay/sources/rudder-apache-relay-nossl.conf
relay/sources/rudder-apache-relay-ssl.conf
relay/sources/rudder-networks-24.conf
relay/sources/rudder-networks-policy-server-24.conf
relay/sources/rudder-pkg
relay/sources/rudder-relay-apache
relay/sources/rudder-relay.cron
relay/sources/rudder-relay.fc
relay/sources/rudder-relay.sudo
relay/sources/rudder-relay.te
relay/sources/rudder-server-relay-postinst
relay/sources/rudder-vhost.conf

https://issues.rudder.io/issues/14667

Fixes #14667: Import 5.1 relay sources into rudder repo

---

webapp/sources/pom.xml
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/db/Doobie.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/migration/XmlEntityMigration.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/migration/XmlFileFormatMigrationEntities.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/reports/execution/LastProcessedReportRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/reports/execution/ReportsExecutionRepositoryImpl.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ComplianceRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/EventLogJdbcRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ExpectedReportsJdbcRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/GitModificationRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/HistorizationJdbcRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ReportsJdbcRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/RudderPropertiesRepository.scala
webapp/sources/rudder/rudder-core/src/test/resources/database.properties
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/db/DBCommon.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/db/GenerateCompliance.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/migration/TestDbMigration.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/migration/TestManageMigration.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/GitModificationRepositoryTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportExecutionTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportsProgressTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportsTest.scala

https://issues.rudder.io/issues/14598

Fixes #14598: Upgrade to Doobie .0.6.0 and related dependencies

---

relay/sources/Makefile

https://issues.rudder.io/issues/14680

Fixes #14680: Remove http1.1 parameter from curl - relay package

---

relay/sources/relay-api/relay_api/remote_run.py

https://issues.rudder.io/issues/14684

Fixes #14684: Add annotation to disable useless pylint warning 

---

qa-test
relay/sources/Makefile

https://issues.rudder.io/issues/14685

Fixes #14685: Add shellcheck linting to shell scripts in the rudder repo

---

relay/sources/Makefile

https://issues.rudder.io/issues/14700

Fixes #14700: Build relay man page separately

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala

https://issues.rudder.io/issues/14771

Fixes #14771: use of unitialized value error when restoring archive

---

relay/sources/rudder-server-relay-postinst
relay/sources/systemd/rudder-relayd.service

https://issues.rudder.io/issues/14710

Fixes #14710: Start the Rudder relay service in post install

---

webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/groupManagement.js
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/ruleDirectives.js
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-rules.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder.css
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentRuleEditForm.html

https://issues.rudder.io/issues/14783

Fixes #14783: Make the Directive and Group sections foldable

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/model/DirectiveEditor.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala
webapp/sources/rudder/rudder-web/src/main/webapp/images/ajax-loader-white.svg
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder.js
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder.css
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/reports_server.html

https://issues.rudder.io/issues/14647

Fixes #14647: Add a Button to trigger an agent run through the UI

---

webapp/sources/rudder/rudder-core/pom.xml
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/RudderDatasourceProvider.scala

https://issues.rudder.io/issues/14789

Fixes #14789: postgres fills up and can't be vaccumed

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala

https://issues.rudder.io/issues/14809

Fixes #14809: Restore binary compatibility for API order (zz method) 

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/xmlparsers/TechniqueParser.scala
webapp/sources/rudder/rudder-core/src/test/resources/parseTechnique/technique_1_agent_no_default.xml
webapp/sources/rudder/rudder-core/src/test/resources/parseTechnique/technique_2_agent_id.xml
webapp/sources/rudder/rudder-core/src/test/resources/parseTechnique/technique_one_default_one_agent_id.xml
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/cfclerk/xmlparsers/ParseTechniqueTest.scala

https://issues.rudder.io/issues/14797

Fixes #14797: A technique can have two agent section for the same kind of agent 

---

webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample

https://issues.rudder.io/issues/14834

Fixes #14834: Default archive retention is too large, which cause very large disk usage 

---

webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample

https://issues.rudder.io/issues/14844

Fixes #14844: correct disk usage in rudder configuration file 

---

webapp/sources/rudder/rudder-core/src/main/resources/ldap/init-policy-server.ldif

https://issues.rudder.io/issues/14689

Fixes #14689: In node compliance, the rule name for root server is "distributePolicy", which is not really great  

---

webapp/sources/rudder/rudder-core/src/main/resources/ldap/bootstrap.ldif

https://issues.rudder.io/issues/14627

Fixes #14627: Sometimes, root server shows up with "No machine inventory" after install

---

relay/sources/rudder-pkg

https://issues.rudder.io/issues/14883

Fixes #14883: Move away from python 2 to python 3 in rudder-pkg

---

relay/sources/Makefile
relay/sources/relay-api/run.py
webapp/sources/rudder/rudder-core/src/test/resources/convertOpenLDAPSchema.py

https://issues.rudder.io/issues/14886

Fixes #14886: Move away from python 2 to python 3 in relay-api

---

relay/sources/relayd/benches/runlog.rs
relay/sources/relayd/src/input.rs

https://issues.rudder.io/issues/14885

Fixes #14885: Fix benchmark in relayd

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala

https://issues.rudder.io/issues/14918

Fixes #14918: "Dynamic group update time-outed (waited for 10 secondes to finish)" 

---

webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/14932

Fixes #14932: Remove unused property "base_url"  

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleEditForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/filters.js
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/groupManagement.js
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/ruleDirectives.js
webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/ruleManagement.html
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-rules.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-tags.css
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentRuleEditForm.html

https://issues.rudder.io/issues/14803

Fixes #14803: Improve Directives' filter in Rule details

---

relay/sources/relay-api/relay_api/remote_run.py

https://issues.rudder.io/issues/14976

Fixes #14976: 

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/14946

Fixes #14946: 

---

webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/ldap/LoadDemoDataTest.scala

https://issues.rudder.io/issues/3591

Fixes #3591: Using move into non existing branch failed but delete the source

---

webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample

https://issues.rudder.io/issues/14862

Fixes #14862: Don't archive reports anymore on Rudder 5.1

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/Compliance.scala

https://issues.rudder.io/issues/14241

Fixes #14241: Missing rule name in compliance API

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/DynGroupUpdaterService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/LdapQueryProcessor.scala
webapp/sources/rudder/rudder-web/src/main/resources/logback.xml

https://issues.rudder.io/issues/14922

Fixes #14922: Missing timing logs in ldap queries (especially for dynamic groups) 

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ExecutionBatchTest.scala

https://issues.rudder.io/issues/15007

Fixes #15007: Missing reports in directives 

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/PurgeDeletedInventories.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/RemoveNodeService.scala
webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/9609

Fixes #9609: Deleted node should be periodically fully erased in LDAP (after some ttl)

---

webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/DataTypes.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/PurgeDeletedInventories.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/ldap/LoadDemoDataTest.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/15034

Fixes #15034: DecoderException: unable to decode base64 string: invalid characters encountered in base64 data 

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala

https://issues.rudder.io/issues/15035

Fixes #15035: Inefficient fetch of nodeconfigurations when runs are received 

---

relay/sources/Makefile
relay/sources/apache/rudder-apache-relay-common.conf
relay/sources/rudder-server-relay-postinst
relay/sources/selinux/rudder-relay.fc

https://issues.rudder.io/issues/15037

Fixes #15037: Add reports endpoint to apache configs

---

relay/sources/relayd/src/data/report.rs
relay/sources/relayd/src/output/database.rs

https://issues.rudder.io/issues/15036

Fixes #15036: Update relay component - improve report parsing

---

SECURITY.adoc

https://issues.rudder.io/issues/15026

Fixes #15026: Add the security vulnerability reporting policy to the rudder repo

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala

https://issues.rudder.io/issues/15039

Fixes #15039: Group Clone popup does not refresh group list and does not close, making an error when clicking a second time on clone ... 

---

relay/sources/relayd/Cargo.lock
relay/sources/relayd/Cargo.toml
relay/sources/relayd/src/api.rs
relay/sources/relayd/src/data/node.rs
relay/sources/relayd/src/error.rs
relay/sources/relayd/src/lib.rs
relay/sources/relayd/src/remote_run.rs
relay/sources/relayd/tests/files/nodeslist.json

https://issues.rudder.io/issues/14947

Fixes #14947: Add logs to Relay API

---

relay/sources/relayd/src/data/node.rs
relay/sources/relayd/src/remote_run.rs

https://issues.rudder.io/issues/15057

Fixes #15057: Repair broken nodeslist tests after parent ticket

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/comet/AsyncDeployment.scala

https://issues.rudder.io/issues/14941

Fixes #14941: Start generation date in status is actually page load date

---

webapp/sources/rudder/rudder-core/src/main/resources/Migration/dbMigration-5.0.x-5.0.12-composite-index-on-ruddersysevents.sql
webapp/sources/rudder/rudder-core/src/main/resources/reportsSchema.sql

https://issues.rudder.io/issues/15063

Fixes #15063: Change index on ruddersysevents to remove inefficient component index and replace it by a composite index 

---

webapp/sources/ldap-inventory/inventory-provisioning-web/src/main/scala/com/normation/inventory/provisioning/endpoint/InventoryFileWatcher.scala
webapp/sources/pom.xml
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/CheckInventoryUpdate.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/LdapQueryProcessor.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
webapp/sources/utils/src/main/scala/com/normation/ZioCommons.scala
webapp/sources/utils/src/test/scala/com/normation/ZioCommonsTest.scala

https://issues.rudder.io/issues/15040

Fixes #15040: Upgrade to ZIO rc5

---

webapp/sources/ldap-inventory/inventory-provisioning-web/src/main/scala/com/normation/inventory/provisioning/endpoint/InventoryFileWatcher.scala
webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/ReadOnlySoftwareInventoryDAOImpl.scala
webapp/sources/ldap-inventory/inventory-repository/src/test/scala/com/normation/inventory/ldap/core/TestInventory.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/PurgeDeletedInventories.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/workflows/CommitAndDeployChangeRequestService.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/15069

Fixes #15069: Merge error broke the build

---

webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/15060

Fixes #15060: Make the numbre of LDAP connection of connection pool configuration 

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleEditForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateRulePopup.scala
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/filters.js

https://issues.rudder.io/issues/15070

Fixes #15070: Rule table search filter is broken

---

webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder.css

https://issues.rudder.io/issues/14562

Fixes #14562: Supersized font in "recent changes"

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ReportsJdbcRepository.scala

https://issues.rudder.io/issues/15076

Fixes #15076: typo in query from parent ticket

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/JavascriptEngine.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/nodeconfig/NodeConfigurationCacheRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PolicyWriterService.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestJsEngine.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/write/WriteTechniquesTest.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/appconfig/ConfigService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SettingsApi.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/test/scala/com/normation/rudder/javascript/CalculateComplianceTest.scala

https://issues.rudder.io/issues/14465

Fixes #14465: Exception: Task java.util.concurrent.FutureTask rejected from java.util.concurrent.ThreadPoolExecutor

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/UpdateDynamicGroups.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/reports/execution/ReportsExecutionService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ComplianceRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/JavascriptEngine.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/nodeconfig/NodeConfigurationCacheRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PolicyWriterService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/NodeChangesService.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestJsEngine.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/write/WriteTechniquesTest.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/appconfig/ConfigService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SettingsApi.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/test/scala/com/normation/rudder/javascript/CalculateComplianceTest.scala

https://issues.rudder.io/issues/15073

Fixes #15073: Add switch to disable some feature for performance

---

relay/sources/man/rudder-relayd.1.adoc
relay/sources/relayd/src/api.rs
relay/sources/relayd/src/configuration.rs
relay/sources/relayd/src/data/node.rs
relay/sources/relayd/src/lib.rs
relay/sources/relayd/src/remote_run.rs
relay/sources/relayd/src/status.rs
relay/sources/relayd/tests/files/config/logging.conf
relay/sources/relayd/tests/files/config/main.conf
relay/sources/relayd/tests/reports_database.rs
relay/sources/relayd/tests/test_simple/config/logging.conf
relay/sources/relayd/tests/test_simple/config/main.conf
relay/sources/relayd/tools/config/logging.conf
relay/sources/relayd/tools/config/main.conf

https://issues.rudder.io/issues/15077

Fixes #15077: Split logging configuration

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ReportsJdbcRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/appconfig/ConfigService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SettingsApi.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/15078

Fixes #15078: Add an option to fail or not during policy generation if NodeConfigurations cannot be created

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala

https://issues.rudder.io/issues/15083

Fixes #15083: In policy generation summary, time to do full generation is not correctly displayed

---

relay/sources/Makefile

https://issues.rudder.io/issues/15084

Fixes #15084: Missing change in makefile for config file rename

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala

https://issues.rudder.io/issues/15085

Fixes #15085: At the end of policy generation, there is a message about all the nodes that didn't need to be updated that is an error message

---

relay/sources/Makefile

https://issues.rudder.io/issues/15089

Fixes #15089: Missing directory creation for relayd config

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/hooks/RunHooks.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PolicyWriterService.scala

https://issues.rudder.io/issues/15095

Fixes #15095: Missing log on hooks for generation

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/reports/execution/ReportsExecutionService.scala

https://issues.rudder.io/issues/15096

Fixes #15096: Compute change hook need to be on a dedicated threadpool

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PolicyWriterService.scala

https://issues.rudder.io/issues/15098

Fixes #15098: Duration import is PolicyWriterService.scala

---

webapp/sources/rudder/rudder-web/src/main/resources/load-page/rudder-loading.html

https://issues.rudder.io/issues/15105

Fixes #15105: RUDDER loading animation is broken

---

webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css

https://issues.rudder.io/issues/15106

Fixes #15106: There is no line break in the text of menu items

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleGrid.scala
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder.css

https://issues.rudder.io/issues/15101

Fixes #15101: the "disabled" label next to rule name isn't present anymore

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleEditForm.scala

https://issues.rudder.io/issues/15099

Fixes #15099: Clicking on a group in rule configuration does not lead to the group

---

webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/nodeProperties.js
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-datatable.css
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentNodeProperties.html

https://issues.rudder.io/issues/10612

Fixes #10612: Make node properties editable on the GUI

---

webapp/sources/rudder/rudder-core/pom.xml
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/Reports.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/reports/execution/ReportsExecutionService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ReportsRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ReportsJdbcRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/NodeChangesService.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/15042

Fixes #15042: Updating changes/repairs (probably) uses too much memory 

---

webapp/sources/rudder/rudder-core/pom.xml
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/reports/execution/ReportsExecutionService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PolicyWriterService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/NodeChangesService.scala

https://issues.rudder.io/issues/15129
This is a partial revert of commit 2da49536d4075658bf6168508ca43899608792a6

Fixes #15129: Queuing "changes" must be done in 5.1 

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala

https://issues.rudder.io/issues/15130

Fixes #15130: New directives don't show up in rules compliance nor in node details

---

webapp/sources/rudder/rudder-core/pom.xml
webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-finished/50-reload-policy-file-server
webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-finished/60-trigger-node-update
webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-finished/hook-template
webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-finished/readme.adoc
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
webapp/sources/rudder/rudder-core/src/test/resources/hooks.d/test-hooks.sh
webapp/sources/rudder/rudder-web/pom.xml
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/15011

Fixes #15011: Error at the end of a policy generation with too many nodes 

---

webapp/sources/rudder/pom.xml
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/Technique.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/system/DebugInfoService.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/hooks/HooksTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestTechniqueWriter.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/SharedFilesAPI.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NcfApi.scala

https://issues.rudder.io/issues/14657

Fixes #14657: Add managed/technique private files for technique editor

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckNcfTechniqueUpdate.scala

https://issues.rudder.io/issues/15159

Fixes #15159: Webapp stops at ncf boot check

---

relay/sources/relayd/Cargo.lock
relay/sources/relayd/Cargo.toml
relay/sources/relayd/src/data/report.rs
relay/sources/relayd/src/data/runlog.rs
relay/sources/relayd/src/lib.rs
relay/sources/relayd/src/relayd.rs
relay/sources/relayd/src/status.rs
relay/sources/relayd/tests/reports_database.rs

https://issues.rudder.io/issues/15164

Fixes #15164: Improve logging

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/workflows/CommitAndDeployChangeRequestService.scala

https://issues.rudder.io/issues/15187

Fixes #15187: Parameters of a directive are not correctly checked by change requests

---

relay/sources/relayd/Cargo.lock
relay/sources/relayd/src/api.rs
relay/sources/relayd/src/data/node.rs
relay/sources/relayd/src/data/runinfo.rs
relay/sources/relayd/src/data/runlog.rs
relay/sources/relayd/src/input.rs
relay/sources/relayd/src/input/watch.rs
relay/sources/relayd/src/output/database.rs
relay/sources/relayd/src/processing.rs
relay/sources/relayd/src/remote_run.rs
relay/sources/relayd/src/shared_files.rs
relay/sources/relayd/src/stats.rs
relay/sources/relayd/src/status.rs
relay/sources/relayd/tests/api_tests.rs

https://issues.rudder.io/issues/15195

Fixes #15195: Update relay component - fix warnings

---

relay/sources/relayd/Cargo.lock
relay/sources/relayd/Cargo.toml
relay/sources/relayd/src/data/report.rs
relay/sources/relayd/src/data/runinfo.rs
relay/sources/relayd/src/data/runlog.rs
relay/sources/relayd/tests/runlogs/normal.log
relay/sources/relayd/tests/test_simple/config/logging.conf

https://issues.rudder.io/issues/15199

Fixes #15199: Update relay component - handle broken reports

---

relay/sources/relayd/src/configuration.rs
relay/sources/relayd/src/remote_run.rs
relay/sources/relayd/tests/files/config/main.conf
relay/sources/relayd/tests/test_simple/config/main.conf
relay/sources/relayd/tools/config/main.conf

https://issues.rudder.io/issues/15196

Fixes #15196: make the  remote run agent parameters configurable

---

webapp/sources/rudder/rudder-core/pom.xml

https://issues.rudder.io/issues/14389

Fixes #14389: Duplicate dependency "jsr305" in rudder-core/pom.xml

---

relay/sources/relayd/src/remote_run.rs

https://issues.rudder.io/issues/15201

Fixes #15201: support "classes" and "conditions" as parameters in the remote-run API

---

relay/sources/relayd/src/configuration.rs
relay/sources/relayd/src/lib.rs
relay/sources/relayd/tests/files/config/main.conf
relay/sources/relayd/tests/test_simple/config/main.conf
relay/sources/relayd/tools/config/main.conf

https://issues.rudder.io/issues/15204

Fixes #15204: Update relay component - Make tokio runtime configurable

---

relay/sources/relayd/benches/runlog.rs

https://issues.rudder.io/issues/15210

Fixes #15210: Fix benchmarks after parent

---

relay/sources/relayd/benches/runlog.rs

https://issues.rudder.io/issues/15213

Fixes #15213: Fix benchmarks after parent

---

relay/sources/relayd/Cargo.lock
relay/sources/relayd/src/api.rs
relay/sources/relayd/src/lib.rs
relay/sources/relayd/tests/reports_database.rs

https://issues.rudder.io/issues/15214

Fixes #15214: Add an API endpoint to reload config

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/workflows/CommitAndDeployChangeRequestService.scala

https://issues.rudder.io/issues/15207

Fixes #15207: Error when modifying a Directive when having the Change Request plugin

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/policies/Tags.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/Technique.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/json/JsonExctractorUtils.scala
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/dsc/ncf/50_techniques/technique_by_Rudder/1.0/technique_by_Rudder.ps1
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/1.0/metadata.xml
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/1.0/technique.cf
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/metadata.xml
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/rudder_reporting.cf
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/technique.cf
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestTechniqueWriter.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NcfApi.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/web/rest/RestTestSetUp.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckNcfTechniqueUpdate.scala

https://issues.rudder.io/issues/15134

Fixes #15134: Migrate ncf write technique api to Rudder

---

relay/sources/Makefile
relay/sources/relayd/tests/relay_api.rs

https://issues.rudder.io/issues/15228

Fixes #15228: Update test and lint configuration

---

webapp/sources/ldap-inventory/inventory-api/src/test/scala/com/normation/inventory/domain/AgentTypesTest.scala
webapp/sources/ldap-inventory/inventory-provisioning-web/src/main/scala/com/normation/inventory/provisioning/endpoint/FusionReportEndpoint.scala
webapp/sources/ldap-inventory/inventory-provisioning-web/src/main/scala/com/normation/inventory/provisioning/endpoint/InventoryFileWatcher.scala
webapp/sources/pom.xml
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/CheckInventoryUpdate.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/xml/TestGitFindUtils.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckNcfTechniqueUpdate.scala
webapp/sources/utils/src/main/scala/com/normation/ZioCommons.scala
webapp/sources/utils/src/test/scala/com/normation/ZioCommonsTest.scala

https://issues.rudder.io/issues/15205

Fixes #15205: Use blocking threadpool for unsafeRun()

---

relay/sources/relayd/Cargo.lock
relay/sources/relayd/Cargo.toml
relay/sources/relayd/src/error.rs
relay/sources/relayd/src/shared_files.rs
relay/sources/relayd/tests/relay_api.rs

https://issues.rudder.io/issues/15233

Fixes #15233: public key and key-hash comparison not consistent in Rust's version of shared-file API

---

relay/sources/relayd/src/remote_run.rs
relay/sources/relayd/tests/relay_api.rs

https://issues.rudder.io/issues/15245

Fixes #15245: Limiting conditions length to 1024 characters

---

relay/sources/relayd/tools/config/main.conf
relay/sources/rudder-server-relay-postinst

https://issues.rudder.io/issues/15238

Fixes #15238: Move /opt/rudder/etc/ssl/nodeslist.cert to /var/rudder/lib/ssl

---

relay/sources/relayd/Cargo.lock
relay/sources/relayd/src/data/runinfo.rs

https://issues.rudder.io/issues/15244

Fixes #15244: Remove forgotten debug macro in parser

---

relay/sources/relayd/src/configuration.rs
relay/sources/relayd/src/data/report.rs
relay/sources/relayd/src/data/runlog.rs
relay/sources/relayd/src/processing.rs
relay/sources/relayd/src/shared_files.rs
relay/sources/relayd/tests/files/config/main.conf
relay/sources/relayd/tests/test_simple/config/main.conf
relay/sources/relayd/tools/config/main.conf

https://issues.rudder.io/issues/15251

Fixes #15251: Add an option to allow disabling log_ reports insertion

---

webapp/sources/ldap-inventory/inventory-fusion/src/test/scala/com/normation/inventory/provisioning/fusion/TestPreUnmarshaller.scala
webapp/sources/ldap-inventory/inventory-fusion/src/test/scala/com/normation/inventory/provisioning/fusion/TestSignatureService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/Lock.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitArchiverUtils.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitFindUtils.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/ItemArchiveManagerImpl.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/ZipUtils.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/WriteNodeCertificatesPem.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestWriteNodeCertificatesPem.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SystemApi.scala
webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/utils/src/main/scala/com/normation/ZioCommons.scala
webapp/sources/utils/src/test/scala/com/normation/ZioCommonsTest.scala

https://issues.rudder.io/issues/15212

Fixes #15212: Generate a file on root server containing all nodes certificate

---

qa-test
relay/sources/Makefile

https://issues.rudder.io/issues/15254

Fixes #15254: Remove relayd tests from qa-test

---

relay/sources/relayd/Cargo.lock
relay/sources/relayd/Cargo.toml
relay/sources/relayd/src/configuration.rs
relay/sources/relayd/src/lib.rs
relay/sources/relayd/tests/files/config/logging.conf
relay/sources/relayd/tests/test_simple/config/logging.conf
relay/sources/relayd/tools/config/logging.conf

https://issues.rudder.io/issues/15261

Fixes #15261: Update relay component - allow arbitrary log filter

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NcfApi.scala

https://issues.rudder.io/issues/15269

Fixes #15269: Rename ncf api to technique api

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PolicyWriterService.scala
webapp/sources/rudder/rudder-templates-cli/src/main/scala/com/normation/templates/cli/TemplateCli.scala
webapp/sources/rudder/rudder-templates-cli/src/test/scala/com/normation/templates/cli/JsonVariablesTest.scala
webapp/sources/rudder/rudder-templates-cli/src/test/scala/com/normation/templates/cli/TemplateCliTest.scala
webapp/sources/rudder/rudder-templates/src/main/scala/com/normation/templates/FillTemplatesService.scala

https://issues.rudder.io/issues/15260

Fixes #15260: Port string template processing to zio

---

relay/sources/Makefile
relay/sources/rudder-server-relay-postinst

https://issues.rudder.io/issues/15292

Fixes #15292: Move /opt/rudder/etc/ssl/nodeslist.cert to /var/rudder/lib/ssl

---

relay/sources/Makefile

https://issues.rudder.io/issues/15301

Fixes #15301: Move /opt/rudder/etc/ssl/nodeslist.cert to /var/rudder/lib/ssl

---

webapp/sources/pom.xml
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/WriteNodeCertificatesPem.scala

https://issues.rudder.io/issues/15302

Fixes #15302: Update silencer plugin to version 1.4

---

README.asciidoc
webapp/sources/ldap-inventory/README.asciidoc
webapp/sources/rudder-commons/README.asciidoc
webapp/sources/rudder-parent-pom/README.asciidoc
webapp/sources/scala-ldap/README.asciidoc

https://issues.rudder.io/issues/15305

Fixes #15305: Update link in readme to rudder.io

---

webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css

https://issues.rudder.io/issues/15203

Fixes #15203: "node management" and "config policy" menu should always be open

---

webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-quicksearch.css

https://issues.rudder.io/issues/15165

Fixes #15165: Quicksearch bar is misplaced when branding plugin is enabled

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/plugins/PluginStatus.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/plugins/RudderPlugin.scala

https://issues.rudder.io/issues/15275

Fixes #15275: Take care of number of nodes in plugin license check

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala

https://issues.rudder.io/issues/15313

Fixes #15313: Policy generation error is not clear in log anymore

---

webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-bootstrap.css

https://issues.rudder.io/issues/15158

Fixes #15158: When we have a branding header, an annoying scrollbar appears on the technique editor page

---

webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css

https://issues.rudder.io/issues/15328

Fixes #15328: Navigation menu is broken when it is folded

---

relay/sources/systemd/rudder-relayd.service

https://issues.rudder.io/issues/15333

Fixes #15333: Use relay reload command in relayd unit

---

relay/sources/relayd/Cargo.lock
relay/sources/relayd/Cargo.toml
relay/sources/relayd/src/api.rs
relay/sources/relayd/src/error.rs
relay/sources/relayd/src/shared_files.rs

https://issues.rudder.io/issues/15253

Fixes #15253: Sending & Receiving files with the shared-files API

---

webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/DataTypes.scala
webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/services/provisioning/CheckInventoryDigest.scala
webapp/sources/ldap-inventory/inventory-provisioning-web/src/main/scala/com/normation/inventory/provisioning/endpoint/InventoryProcessor.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/Node.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/NodeInfo.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/NodeRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogDetailsService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogFactory.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/eventlog/NodeEventLogFormatV6Test.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/RestData.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/EventListDisplayer.scala

https://issues.rudder.io/issues/15344

Fixes #15344: API for node key management

---

relay/sources/relayd/src/shared_files.rs

https://issues.rudder.io/issues/15352

Fixes #15352: Fix 5.1 relay-api build

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/15353

Fixes #15353: Deprecate API up to 10

---

webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/ReadOnlySoftwareInventoryDAOImpl.scala
webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/SoftwareService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/ReportLogger.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/reports/execution/ReportsExecutionService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ReportsRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ReportsJdbcRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/NodeChangesService.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleCompliance.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleGrid.scala
webapp/sources/utils/src/main/scala/com/normation/ZioCommons.scala

https://issues.rudder.io/issues/15117
This need to be tested in the load test plateform to check that it didn't make things worse.

Fixes #15117: Use a queue for "changes" cache update

---

webapp/sources/rudder/rudder-core/src/main/resources/ldap/init-policy-server.ldif

https://issues.rudder.io/issues/15357

Fixes #15357: Initial ldif values for root need to have certificate

---

webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestTechniqueWriter.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/write/WriteTechniquesTest.scala

https://issues.rudder.io/issues/15364

Fixes #15364: Test in 5.1 for webapp are broken

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/SystemVariableService.scala

https://issues.rudder.io/issues/15355

Fixes #15355: MANAGED_NODES_NAME is still needed for CFE nodes

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/PurgeDeletedInventories.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/PurgeUnreferencedSoftwares.scala

https://issues.rudder.io/issues/15376

Fixes #15376: Forget to fork backend batch

---

relay/sources/rudder-server-relay-postinst

https://issues.rudder.io/issues/15377

Fixes #15377: Warnings during relay postinstall

---

webapp/sources/scala-ldap/src/main/scala/com/normation/ldap/sdk/LDAPIOResult.scala
webapp/sources/utils/src/main/scala/com/normation/ZioCommons.scala

https://issues.rudder.io/issues/15381

Fixes #15381: Add more info on LDAP backend error

---

webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/15386

Fixes #15386: webapp fail to reload relay

---

webapp/sources/pom.xml
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/GitTechniqueReader.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/CheckInventoryUpdate.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/ClearCacheService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/NodeChangesService.scala
webapp/sources/scala-ldap/src/main/scala/com/normation/ldap/listener/InMemoryDsConnectionProvider.scala
webapp/sources/scala-ldap/src/main/scala/com/normation/ldap/sdk/LDAPConnectionProvider.scala
webapp/sources/scala-ldap/src/main/scala/com/normation/ldap/sdk/LDAPIOResult.scala

https://issues.rudder.io/issues/15383

Fixes #15383: Unhandled error if the LDAP connection is unavailable

---

relay/sources/relay-api/apache/relay-api.wsgi

https://issues.rudder.io/issues/15399

Fixes #15399: relay api doesn't support python2 and python 3

---

webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/write/PrepareTemplateVariableTest.scala

https://issues.rudder.io/issues/15400

Fixes #15400: The list of directive bundles broke test

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/WriteNodeCertificatesPem.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestWriteNodeCertificatesPem.scala
webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/15403

Fixes #15403: Wrong name for all nodes certificates files

---

relay/sources/relayd/src/processing.rs

https://issues.rudder.io/issues/15405

Fixes #15405: Only treat file with report extension in relayd

---

webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/MachineInventory.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/SystemVariableSpecServiceImpl.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/SystemVariableService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PolicyWriterService.scala

https://issues.rudder.io/issues/3112

Fixes #3112: Allow to get informations from the node inventory to use them in Directives and ncf techniques

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/BuildBundleSequence.scala
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-500-directives/rules/cfengine-community/rudder-directives.cf
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-500-directives/rules/cfengine-community/rudder-system-directives.cf
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-two-directives/rules/cfengine-community/rudder-directives.cf
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-two-directives/rules/cfengine-community/rudder-system-directives.cf
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-gen-var-def-override/rules/cfengine-community/rudder-directives.cf
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-gen-var-def-override/rules/cfengine-community/rudder-system-directives.cf
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-default-install/rudder-system-directives.cf
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-one-multipolicy/rudder-directives.cf
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-one-multipolicy/rudder-system-directives.cf
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-two-directives/rudder-directives.cf
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-two-directives/rudder-system-directives.cf
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/write/PrepareTemplateVariableTest.scala

https://issues.rudder.io/issues/15410

Fixes #15410: Generated policies are invalid, as the bundles list are not in a methods: section

---

webapp/sources/rudder/rudder-core/src/main/resources/Migration/dbMigration-5.0.x-5.0.13-remove-autovacuum-on-ruddersysevents.sql
webapp/sources/rudder/rudder-core/src/main/resources/reportsSchema.sql

https://issues.rudder.io/issues/15413

Fixes #15413: Autovacuum may never finish, or take more than one day, on busy Rudder instance, because of resources attrition

---

relay/sources/relayd/src/data/runlog.rs

https://issues.rudder.io/issues/15425

Fixes #15425: relayd should only control run date consistency inside the runlog

---

relay/sources/relayd/Cargo.lock
relay/sources/relayd/src/data/runlog.rs
relay/sources/relayd/src/input/watch.rs
relay/sources/relayd/src/lib.rs
relay/sources/relayd/src/processing.rs

https://issues.rudder.io/issues/15427

Fixes #15427: relayd watcher does not catch moved files

---

webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-elm.js

https://issues.rudder.io/issues/15438

Fixes #15438: Fix rudder-elm notifications init

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/WriteNodeCertificatesPem.scala
webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/15441

Fixes #15441: change call to rudder relay reload to check permission of generated file

---

relay/sources/relayd/Cargo.lock
relay/sources/relayd/src/configuration/logging.rs
relay/sources/relayd/src/configuration/main.rs
relay/sources/relayd/src/data/report.rs
relay/sources/relayd/src/error.rs
relay/sources/relayd/src/input/watch.rs
relay/sources/relayd/src/lib.rs
relay/sources/relayd/src/output.rs
relay/sources/relayd/src/output/database.rs
relay/sources/relayd/src/output/upstream.rs
relay/sources/relayd/src/processing.rs
relay/sources/relayd/src/processing/reporting.rs
relay/sources/relayd/tests/files/config/logging.conf
relay/sources/relayd/tests/files/config/main.conf
relay/sources/relayd/tests/test_simple/config/logging.conf
relay/sources/relayd/tests/test_simple/config/main.conf
relay/sources/relayd/tools/config/main.conf

https://issues.rudder.io/issues/15435

Fixes #15435: Forward reports to upper relays in relayd

---

relay/sources/relayd/src/output/upstream.rs

https://issues.rudder.io/issues/15461

Fixes #15461: reports are not forwarded to the server du to errer

---

relay/sources/Makefile
relay/sources/relayd/Cargo.lock
relay/sources/relayd/src/data/report.rs
relay/sources/relayd/src/output/database.rs

https://issues.rudder.io/issues/15467

Fixes #15467: Remove \r in reports in relayd

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SettingsApi.scala

https://issues.rudder.io/issues/15472

Fixes #15472: upgrade API settings to v12 to include default report protocol and syslog protocol disabled 

---

relay/sources/Makefile

https://issues.rudder.io/issues/15480

Fixes #15480: Typo in rudder Makefile

---

relay/sources/Makefile

https://issues.rudder.io/issues/15481

Fixes #15481: Rudder-pkg try to copy a folder with install command instead of using a recursive cp

---

relay/sources/relayd/Cargo.lock
relay/sources/relayd/src/output/upstream.rs

https://issues.rudder.io/issues/15482

Fixes #15482: Report PUT is missing the file name

---

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py
relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py

https://issues.rudder.io/issues/15477

Fixes #15477: Make rudder-pkg handle confiparser in python 2 and 3

---

relay/sources/rudder-pkg/rudder-pkg

https://issues.rudder.io/issues/15486

Fixes #15486: Change rudder-pkg to use python3 by default

---

relay/sources/Makefile

https://issues.rudder.io/issues/15490

Fixes #15490: Make clean doesn't remove all python files downloaded and generated on rudder-relay

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/BuildBundleSequence.scala
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-500-directives/rules/cfengine-community/rudder-system-directives.cf
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-500-directives/rules/cfengine-community/rudder.json
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-two-directives/rules/cfengine-community/rudder-system-directives.cf
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-two-directives/rules/cfengine-community/rudder.json
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-gen-var-def-override/rules/cfengine-community/rudder-system-directives.cf
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-gen-var-def-override/rules/cfengine-community/rudder.json

https://issues.rudder.io/issues/15494

Fixes #15494: Policy mode of system directives are invalid

---

relay/sources/relayd/src/remote_run.rs
relay/sources/relayd/tests/remote_run.rs

https://issues.rudder.io/issues/15501

Fixes #15501: Unknown option in remote-run command

---

relay/sources/relayd/Cargo.lock
relay/sources/relayd/src/api.rs
relay/sources/relayd/src/lib.rs
relay/sources/relayd/src/output/database.rs
relay/sources/relayd/src/output/upstream.rs
relay/sources/relayd/src/processing.rs
relay/sources/relayd/src/processing/inventory.rs
relay/sources/relayd/src/processing/reporting.rs
relay/sources/relayd/src/shared_files.rs

https://issues.rudder.io/issues/15497

Fixes #15497: Add inventory forwarding on relays in relayd

---

relay/sources/Makefile

https://issues.rudder.io/issues/15527

Fixes #15527: change permission of config file in makefile

---

relay/sources/Makefile
relay/sources/rudder-pkg/rudder-pkg
relay/sources/rudder-server-relay-postinst

https://issues.rudder.io/issues/15502

Fixes #15502: Add autocompletion to rudder-pkg

---

relay/sources/Makefile

https://issues.rudder.io/issues/15529

Fixes #15529: Add autocompletion to rudder-pkg

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/Technique.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestTechniqueWriter.scala

https://issues.rudder.io/issues/15314

Fixes #15314: In rudder 5.1 we can no more put multiple lines in technique editor fields

---

relay/sources/Makefile

https://issues.rudder.io/issues/15546

Fixes #15546: Parent does not work because subcommand is not interpreted

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/NodeInfo.scala

https://issues.rudder.io/issues/15547

Fixes #15547: Empty keyhashes in nodeslist.json on Linux nodes

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/AsyncDeploymentActor.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/EventLogJdbcRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/ClearCacheService.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/UserSessionLogEvent.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/UserInformation.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/EditPolicyServerAllowedNetwork.scala
webapp/sources/utils/src/main/scala/com/normation/ZioCommons.scala

https://issues.rudder.io/issues/15307

Fixes #15307: Generation status is empty and grey at every connection

---

relay/sources/Makefile
relay/sources/rudder-server-relay-postinst

https://issues.rudder.io/issues/15567

Fixes #15567: rudder-pkg command in /opt/rudder/bin should not be created in postinst but at build time

---

relay/sources/Makefile
relay/sources/rudder-server-relay-prerm

https://issues.rudder.io/issues/15566

Fixes #15566: add a prerm script to rudder-server-relay

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/plugins/RudderPlugin.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/PluginExpirationInfo.scala
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/common-layout.html

https://issues.rudder.io/issues/15568

Fixes #15568: Display warning when plugin license is near expiration date 

---

webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/MachineInventory.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/WriteNodeCertificatesPem.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestTechniqueWriter.scala

https://issues.rudder.io/issues/15574

Fixes #15574: Correct scala compilation warnings

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/TechniqueAcceptationDatetimeUpdater.scala

https://issues.rudder.io/issues/15575

Fixes #15575: Avoid duplicating technique category when changing category name

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/EventListDisplayer.scala
webapp/sources/rudder/rudder-web/src/main/webapp/secure/utilities/eventLogs.html

https://issues.rudder.io/issues/9445

Fixes #9445: If we filter event logs with only a start or end date, we get a super ugly error

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/plugins/RudderPluginJson.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PluginManagement.scala
webapp/sources/rudder/rudder-web/src/test/scala/com/normation/plugins/RudderPluginJsonTest.scala

https://issues.rudder.io/issues/15556

Fixes #15556: List all plugin in plugin status page

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/filters.js
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/tags.js
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/tree-tag-plugin.js
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentTags.html

https://issues.rudder.io/issues/15423

Fixes #15423: Filtering tags with more than one tag with same "key" did not return correct results

---

webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/tags.js

https://issues.rudder.io/issues/15419

Fixes #15419: Tags are not properly set when changing only value field before new insertion

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/DatabaseManagement.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala
webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/apiManagement.html
webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/databaseManagement.html
webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/policyServerManagement.html
webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/techniqueLibraryManagement.html
webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/parameterManagement.html
webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/manageNewNode.html
webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/searchNodes.html
webapp/sources/rudder/rudder-web/src/main/webapp/secure/plugins/pluginInformation.html
webapp/sources/rudder/rudder-web/src/main/webapp/secure/utilities/archiveManagement.html
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/common-layout.html
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentAgentPolicyMode.html
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentAgentSchedule.html
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentComplianceMode.html
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentDirectiveEditForm.html
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentNodeState.html
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentRuleEditForm.html

https://issues.rudder.io/issues/15587

Fixes #15587: Change introduction and description fields look in Rudder web interface

---

relay/sources/relayd/Cargo.lock
relay/sources/relayd/Cargo.toml
relay/sources/relayd/src/configuration/cli.rs

https://issues.rudder.io/issues/15610

Fixes #15610: Update structopt

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/RudderDit.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDirectiveRepository.scala

https://issues.rudder.io/issues/15623

Fixes #15623: Moving a category fails with "missing ldap attribute"

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/NodeInfo.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/queries/CmdbQuery.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DataStructures.scala

https://issues.rudder.io/issues/15637

Fixes #15637: NodeInfo should not extend loggable

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/queries/CmdbQuery.scala

https://issues.rudder.io/issues/15638

Fixes #15638: Error in parent ticket - CmdbQuery is missing a Logger

---

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py
relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py

https://issues.rudder.io/issues/15634

Fixes #15634: Rudder-pkg can not find itself the path to licenses on the rudder repo

---

relay/sources/Makefile

https://issues.rudder.io/issues/15629

Fixes #15629: Rudder-pkg create a symlink pointing to a non existing path

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/TechniqueLibraryUpdateNotification.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/TechniqueRepositoryImpl.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/cfclerk/services/TechniqueRepositoryTest.scala

https://issues.rudder.io/issues/15651

Fixes #15651: Moving a category from a subcategory to root fails

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/domain/VariableAndSection.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DataStructures.scala

https://issues.rudder.io/issues/15665

Fixes #15665: Variable should not extend loggable

---

relay/sources/relayd/Cargo.lock
relay/sources/relayd/Cargo.toml
relay/sources/relayd/fuzz/Cargo.lock
relay/sources/relayd/src/data/node.rs

https://issues.rudder.io/issues/15664

Fixes #15664: Remove avoidable dependencies

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/queries/CmdbQuery.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/BootstrapChecks.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckApiTokenAutorizationKind.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckCfengineSystemRuleTargets.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckConnections.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckDIT.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckInitUserTemplateLibrary.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckInitXmlExport.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckNashornWarning.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckNcfTechniqueUpdate.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckRuleCategoryExport.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckSystemGroups.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckTechniqueLibraryReload.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/CreateSystemToken.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/ResumePolicyUpdateRunning.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/TriggerPolicyUpdate.scala

https://issues.rudder.io/issues/15670

Fixes #15670: Compilation error on 5.1 branch

---

webapp/sources/rudder/rudder-core/src/test/scala/com/normation/cfclerk/services/TechniqueRepositoryTest.scala

https://issues.rudder.io/issues/15673

Fixes #15673: Parent ticket didn't corrected the problem when a category is moved to root

---

relay/sources/relayd/Cargo.lock
relay/sources/relayd/Cargo.toml
relay/sources/relayd/src/api.rs
relay/sources/relayd/src/data/node.rs
relay/sources/relayd/src/data/report.rs
relay/sources/relayd/src/data/runlog.rs
relay/sources/relayd/src/error.rs
relay/sources/relayd/src/shared_files.rs

https://issues.rudder.io/issues/15668

Fixes #15668: Fix PUT in shared-files API

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DataStructures.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/MergePolicyService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/RuleValService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/BuildBundleSequence.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PrepareTemplateVariables.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeExpectedReportTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/write/PolicyAgregationTest.scala

https://issues.rudder.io/issues/15255

Fixes #15255: Keep directive and rule name in Policy data structure

---

relay/sources/rudder-server-relay-postinst

https://issues.rudder.io/issues/15680

Fixes #15680: Updating Apache's reverse proxy configuration to handle HTTPS requests on remote-run API

---

webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/services/provisioning/CheckInventoryDigest.scala

https://issues.rudder.io/issues/14209

Fixes #14209: Impossible to reset the status of a Node using rudder-keys cli

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/InterpolatedValueCompiler.scala

https://issues.rudder.io/issues/15743

Fixes #15743: Millions of objects are instanciated while doing the policy generation for variable interpolation

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala
webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/directiveManagement.html
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-directives.css
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentDirectiveEditForm.html

https://issues.rudder.io/issues/15672

Fixes #15672: Add technique ID in UI

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/Archives.scala
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-elm.js

https://issues.rudder.io/issues/15315

Fixes #15315: Missing notification for archive page

---

webapp/sources/ldap-inventory/inventory-provisioning-web/src/main/scala/com/normation/inventory/provisioning/endpoint/InventoryFileWatcher.scala
webapp/sources/ldap-inventory/inventory-repository/pom.xml
webapp/sources/pom.xml
webapp/sources/rudder/rudder-core/pom.xml
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/db/Doobie.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDirectiveRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeGroupRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/rule/category/LDAPRuleCategoryRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/JavascriptEngine.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/WriteNodeCertificatesPem.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PolicyWriterService.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestJsEngine.scala
webapp/sources/rudder/rudder-rest/pom.xml
webapp/sources/rudder/rudder-templates-cli/pom.xml
webapp/sources/rudder/rudder-web/pom.xml
webapp/sources/utils/src/main/scala/com/normation/ZioCommons.scala

https://issues.rudder.io/issues/15740

Fixes #15740: Update libraries to last minor versions

---

webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/PreUnmarshallCheckConsistency.scala

https://issues.rudder.io/issues/15749

Fixes #15749: A lot of memory (and ressources) seems to be used in PreUnmarshallCheckConsistency

---

webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/PreUnmarshallCheckConsistency.scala
webapp/sources/ldap-inventory/inventory-fusion/src/test/scala/com/normation/inventory/provisioning/fusion/TestPreUnmarshaller.scala
webapp/sources/ldap-inventory/inventory-provisioning-web/src/main/scala/com/normation/inventory/provisioning/endpoint/InventoryProcessor.scala
webapp/sources/ldap-inventory/inventory-provisioning-web/src/test/scala/com/normation/inventory/provisioning/endpoint/InventoryFileWatcherTest.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/web/rest/SystemApiTest.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/Archives.scala

https://issues.rudder.io/issues/15773

Fixes #15773: Test in 5.1 are in error following change in fusion parsing

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/ComplianceModeEditForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/ShowNodeDetailsFromNode.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PropertiesManagement.scala
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/complianceMode.js
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentComplianceMode.html

https://issues.rudder.io/issues/15684

Fixes #15684: Disable HTTPS reporting protocol option if changes only is enabled and vice versa

---

webapp/sources/pom.xml

https://issues.rudder.io/issues/15776

Fixes #15776: error at start of Rudder 

---

webapp/sources/ldap-inventory/inventory-provisioning-web/src/main/scala/com/normation/inventory/provisioning/endpoint/InventoryFileWatcher.scala

https://issues.rudder.io/issues/15747

Fixes #15747: When receving pleinty of inventories at the same time, the web interface starts to parse them all at once (branch 5.0)

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/SystemVariableService.scala

https://issues.rudder.io/issues/15786

Fixes #15786: When computing system variables, we compute for each nodes the mapping all nodes<->each policy server

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestAuthentication.scala

https://issues.rudder.io/issues/15790

Fixes #15790: Rudder authentication api refuse api account even if they could have access

---

webapp/sources/ldap-inventory/inventory-provisioning-core/src/main/scala/com/normation/inventory/ldap/provisioning/DefaultReportSaver.scala
webapp/sources/ldap-inventory/inventory-provisioning-core/src/main/scala/com/normation/inventory/ldap/provisioning/SoftwareIdFinder.scala
webapp/sources/ldap-inventory/inventory-repository/src/test/scala/com/normation/inventory/ldap/core/TestInventory.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala

https://issues.rudder.io/issues/15171

Fixes #15171: Cannot get Rule tree with the API in Rudder 5.0

---

webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-failed/hook-template
webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-failed/readme.adoc
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/hooks/RunHooks.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/15791

Fixes #15791: Missing generation failure hook

---

webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css

https://issues.rudder.io/issues/15795

Fixes #15795: if screen height is too small, it's impossible to access settings in the rudder menu

---

relay/sources/relayd/Cargo.lock
relay/sources/relayd/src/data/node.rs
relay/sources/relayd/tests/fake_agent.sh
relay/sources/relayd/tests/remote_run.rs

https://issues.rudder.io/issues/15808

Fixes #15808: Fix synchronous remote run test

---

relay/sources/rudder-server-relay-postinst

https://issues.rudder.io/issues/15810

Fixes #15810: Incorrect permission on /var/rudder/reports

---

relay/sources/relayd/src/remote_run.rs

https://issues.rudder.io/issues/15814

Fixes #15814: Incorrect remote run command when used with sudo

---

relay/sources/Makefile

https://issues.rudder.io/issues/15826

Fixes #15826: Create /var/rudder/reports/failed at install

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/Authorizations.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RoleApiMapping.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/RestQuicksearch.scala
webapp/sources/rudder/rudder-web/src/main/resources/demo-rudder-users.xml
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/ParameterManagement.scala

https://issues.rudder.io/issues/15104

Fixes #15104: 

---

webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/ReadOnlySoftwareInventoryDAOImpl.scala

https://issues.rudder.io/issues/15827

Fixes #15827: Job to clean unreference software may delete software for pending nodes

---

webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/NodeGroupForm.html

https://issues.rudder.io/issues/15599

Fixes #15599: Rules are shown in "Applied rules" on groups where they are not applied

---

relay/sources/relayd/src/remote_run.rs

https://issues.rudder.io/issues/15832

Fixes #15832: relayd should accept empty condition field in remote-run

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/AutomaticReportsCleaner.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ReportsRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ReportsJdbcRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/system/DatabaseManager.scala
webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/15802

Fixes #15802: Clean up report with level log info more than once a day

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/AutomaticReportsCleaner.scala

https://issues.rudder.io/issues/15849

Fixes #15849: Missing a fork for clean report info batch

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/EventLogRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/EventLogJdbcRepository.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/EventLogAPI.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/EventLogDetailsGenerator.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/EventListDisplayer.scala
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js

https://issues.rudder.io/issues/15862

Fixes #15862: Fixes to event log pagination

---

relay/sources/apache/rudder-apache-relay-common.conf
relay/sources/relayd/Cargo.lock
relay/sources/relayd/fuzz/Cargo.lock
relay/sources/relayd/src/api.rs
relay/sources/relayd/src/data/node.rs
relay/sources/relayd/src/status.rs
relay/sources/relayd/tests/api_info.rs
relay/sources/relayd/tests/api_status.rs
relay/sources/relayd/tests/common.rs
relay/sources/relayd/tests/remote_run.rs
relay/sources/relayd/tests/remote_run_error.rs
relay/sources/relayd/tests/reports_database.rs
relay/sources/relayd/tests/shared_files.rs
relay/sources/relayd/tests/shared_folder.rs

https://issues.rudder.io/issues/15866

Fixes #15866: Improve relayd API

---

relay/sources/Makefile

https://issues.rudder.io/issues/15882

Fixes #15882: Cache relayd builds

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/AutomaticReportsCleaner.scala

https://issues.rudder.io/issues/15890

Fixes #15890: Batch which deletes log reports displays an error when default run interval is not defined

---

webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/FusionReportUnmarshaller.scala
webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/history/impl/FileHistoryLogRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/AbstractScheduler.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/UpdateDynamicGroups.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/system/DebugInfoService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestDataSerializer.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/NodeDetailLevel.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/EventLogAPI.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SystemApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/components/DateFormaterService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/EventLogDetailsGenerator.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/web/rest/RestTestSetUp.scala
webapp/sources/rudder/rudder-web/src/main/resources/logback.xml
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ComplianceData.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/SrvGrid.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/Archives.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/DatabaseManagement.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/AcceptNode.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/PendingHistoryGrid.scala

https://issues.rudder.io/issues/15896

Fixes #15896: Normalize datetime format to ISO8601/rfc3339

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/ParameterManagement.scala

https://issues.rudder.io/issues/15904

Fixes #15904: "add global param" button still available for read-only role

---

relay/sources/Makefile

https://issues.rudder.io/issues/15906

Fixes #15906: Only cache dependencies

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestAuthentication.scala

https://issues.rudder.io/issues/15919

Fixes #15919: Remove unwanted logger

---

relay/sources/Makefile

https://issues.rudder.io/issues/15920

Fixes #15920: Only cache dependencies

---

relay/sources/Makefile

https://issues.rudder.io/issues/15923

Fixes #15923: Only cache dependencies

---

webapp/sources/pom.xml

https://issues.rudder.io/issues/15941

Fixes #15941: Login page on Rudder 6.0 shows version 5.1

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/DynGroupUpdaterService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/LdapQueryProcessor.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/QueryProcessor.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/GroupsApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala

https://issues.rudder.io/issues/15858

Fixes #15858: Computing dynamic groups is very memory intensive, and can lead to FGC or OOM

---

webapp/sources/rudder/rudder-web/src/main/resources/logback.xml

https://issues.rudder.io/issues/15916

Fixes #15916: Missing some logger documentation in logback.xml

---

webapp/sources/scala-ldap/src/main/scala/com/normation/ldap/sdk/LDAPEntry.scala

https://issues.rudder.io/issues/15965

Fixes #15965: Changing LdapEntry broke tests

---

relay/sources/relayd/Cargo.lock
relay/sources/relayd/Cargo.toml
relay/sources/relayd/src/api.rs
relay/sources/relayd/src/api/remote_run.rs
relay/sources/relayd/src/error.rs
relay/sources/relayd/src/hashing.rs
relay/sources/relayd/tests/remote_run_error.rs

https://issues.rudder.io/issues/15949

Fixes #15949: Improve error type definitions

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/EventLogAPI.scala
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js

https://issues.rudder.io/issues/15870

Fixes #15870: Add support for sort in pagination

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala

https://issues.rudder.io/issues/14354

Fixes #14354: New techniques are not added to directive tree

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/EventLogJdbcRepository.scala
webapp/sources/utils/src/main/scala/com/normation/ZioCommons.scala
webapp/sources/utils/src/test/scala/com/normation/ZioCommonsTest.scala

https://issues.rudder.io/issues/15982

Fixes #15982: Webapp does not start when only one proc is available (deadlock)

---

relay/sources/relayd/Cargo.lock
relay/sources/relayd/src/api/remote_run.rs
relay/sources/relayd/tests/remote_run.rs

https://issues.rudder.io/issues/15990

Fixes #15990: Remote-run returns empty output

---

relay/sources/relayd/src/data/node.rs

https://issues.rudder.io/issues/15992

Fixes #15992: Don't fail on nodeslist or certificate file absence

---

relay/sources/relayd/Cargo.lock
relay/sources/relayd/src/api.rs
relay/sources/relayd/src/processing/reporting.rs
relay/sources/relayd/tests/api_reload.rs
relay/sources/relayd/tests/reports_database.rs

https://issues.rudder.io/issues/15999

Fixes #15999: Receiving a report for an unkown node crashes the watcher

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/HomePage.scala

https://issues.rudder.io/issues/16004

Fixes #16004: Unexpected crash of webapp on 6.0

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/EventLogAPI.scala

https://issues.rudder.io/issues/15945

Fixes #15945: Display date in event log list is not really human friendly

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala

https://issues.rudder.io/issues/16008

Fixes #16008: Policy generation fails when we have technique ressources

---

webapp/sources/rudder/rudder-core/src/test/resources/ldap-data/inventory-sample-data.ldif
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala

https://issues.rudder.io/issues/16030

Fixes #16030: add a test on group of groups

---

relay/sources/apache/rudder-apache-relay-ssl.conf
relay/sources/man/rudder-relayd.1.adoc
relay/sources/relayd/Cargo.lock
relay/sources/relayd/Makefile
relay/sources/relayd/fuzz/Cargo.lock
relay/sources/relayd/src/api.rs
relay/sources/relayd/src/api/shared_files.rs
relay/sources/relayd/src/api/shared_folder.rs
relay/sources/relayd/src/configuration/cli.rs
relay/sources/relayd/tests/shared_folder.rs

https://issues.rudder.io/issues/16001

Fixes #16001: Add logging contexts

---

webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-finished/40-nodelist-relay-configuration

https://issues.rudder.io/issues/16017

Fixes #16017: nodeslist.json can take up to 5 minutes to be updated after accepting a node

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala

https://issues.rudder.io/issues/16033

Fixes #16033: Resources in technique are not put in the correct folder

---

relay/sources/relayd/src/data/node.rs

https://issues.rudder.io/issues/16043

Fixes #16043: Parent fix does not work for nodeslist

---

webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/1.0/technique.cf
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/technique.cf

https://issues.rudder.io/issues/16046

Fixes #16046: parent ticket broke test

---

relay/sources/relayd/benches/benches.rs
relay/sources/relayd/src/configuration.rs
relay/sources/relayd/src/configuration/main.rs
relay/sources/relayd/src/output/database.rs
relay/sources/relayd/src/output/upstream.rs
relay/sources/relayd/tests/files/config/main.conf
relay/sources/relayd/tests/test_simple/config/main.conf
relay/sources/relayd/tools/config/main.conf

https://issues.rudder.io/issues/16040

Fixes #16040: Passwords can appear in relayd logs

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/SharedFilesAPI.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NcfApi.scala

https://issues.rudder.io/issues/16042

Fixes #16042: New api endpoint to manage new technique resources

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala

https://issues.rudder.io/issues/15048

Fixes #15048: Error message in technique editor when using wrong syntax for node properties is REALLY not clear enough 

---

relay/sources/relayd/Cargo.lock
relay/sources/relayd/fuzz/Cargo.lock
relay/sources/relayd/src/api/remote_run.rs
relay/sources/relayd/src/data/node.rs
relay/sources/relayd/tests/fake_agent.sh
relay/sources/relayd/tests/remote_run.rs

https://issues.rudder.io/issues/16047

Fixes #16047: Remote-run sometimes returns empty outpout or output with missing newlines

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/rudder_reporting.cf

https://issues.rudder.io/issues/16069

Fixes #16069: Policy generation is broken when using condition on generic methds

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/rudder_reporting.cf

https://issues.rudder.io/issues/16070

Fixes #16070: several typos in generated policies with technique editor

---

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py

https://issues.rudder.io/issues/15952

Fixes #15952: Rudder package does not work when there are no plugin compatible with the current version of Rudder

---

relay/sources/relayd/src/api.rs
relay/sources/relayd/src/error.rs
relay/sources/relayd/src/input.rs
relay/sources/relayd/src/lib.rs
relay/sources/relayd/src/relayd.rs
relay/sources/relayd/tests/api_remote_run.rs
relay/sources/relayd/tests/api_shared_folder.rs
relay/sources/relayd/tests/api_system_info.rs
relay/sources/relayd/tests/api_system_reload.rs
relay/sources/relayd/tests/api_system_status.rs

https://issues.rudder.io/issues/16076

Fixes #16076: relayd should stop when a thread panics

---

relay/sources/relayd/src/data/node.rs
relay/sources/relayd/src/relayd.rs

https://issues.rudder.io/issues/16079

Fixes #16079: Allow overriding RUST_BACKTRACE

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestDataSerializer.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/components/DateFormaterService.scala

https://issues.rudder.io/issues/15943

Fixes #15943: Date handling in API Token Creation is broken

---

relay/sources/systemd/rudder-relayd-hardening

https://issues.rudder.io/issues/16148

Fixes #16148: Systemd sandboxing options prevent remote-run from executing

---

relay/sources/rudder-relay-apache

https://issues.rudder.io/issues/16108

Fixes #16108: relay postinst fails on SLES15

---

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py

https://issues.rudder.io/issues/16161

Fixes #16161: os.makedirs 'exist_ok' parameter does not exist in python 2.7

---

webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder.js
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentRuleEditForm.html

https://issues.rudder.io/issues/11644

Fixes #11644: Improve Rules tabs visibility

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/NodeChangesService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/InfoApi.scala
webapp/sources/rudder/rudder-web/src/main/resources/load-page/rudder-loading.html
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleCompliance.scala
webapp/sources/rudder/rudder-web/src/main/webapp/secure/plugins/pluginInformation.html
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/common-layout.html

https://issues.rudder.io/issues/16121

Fixes #16121: Update URLs to our websites

---

webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/MemorySize.scala
webapp/sources/ldap-inventory/inventory-api/src/test/scala/com/normation/inventory/domain/MemoryTest.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/queries/CmdbQuery.scala

https://issues.rudder.io/issues/16158

Fixes #16158: Error message when serching for RAM size says we can use Mo

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder.js

https://issues.rudder.io/issues/15953

Fixes #15953: In node details, clicking on policy server id redirect to original node

---

webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample

https://issues.rudder.io/issues/13870

Fixes #13870: Mark Git configuration option deprecated 

---

webapp/sources/scala-ldap/src/main/scala/com/normation/ldap/sdk/LDAPConnection.scala
webapp/sources/scala-ldap/src/test/resources/ldap-data/bootstrap.ldif
webapp/sources/scala-ldap/src/test/resources/ldap-data/schema/00-core.ldif
webapp/sources/scala-ldap/src/test/resources/ldap-data/schema/01-pwpolicy.ldif
webapp/sources/scala-ldap/src/test/resources/ldap-data/schema/04-rfc2307bis.ldif
webapp/sources/scala-ldap/src/test/resources/ldap-data/schema/05-rfc4876.ldif
webapp/sources/scala-ldap/src/test/scala/com/normation/ldap/sdk/LoadDemoDataTest.scala

https://issues.rudder.io/issues/10067

Fixes #10067: If LDAP attribute is missing, related LDAP error are not reported in UI (silent fail)

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/rule/category/RuleCategory.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/RuleApi.scala

https://issues.rudder.io/issues/16164

Fixes #16164: We cannot get the rules categories with the API

---

webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample

https://issues.rudder.io/issues/16072

Fixes #16072: Change documentation in rudder-web.properties about backup folder

---

webapp/sources/rudder/rudder-core/src/main/resources/ldap/bootstrap.ldif
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/ldap/LoadDemoDataTest.scala
webapp/sources/scala-ldap/src/test/resources/ldap-data/bootstrap.ldif

https://issues.rudder.io/issues/15878

Fixes #15878: We still have an LDAP entry "ou=Nodes Configuration,..." which is not used anymore

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/queries/CmdbQuery.scala

https://issues.rudder.io/issues/14267

Fixes #14267: Error in group page when searching "Last inventory date" / is defined

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-directives.css
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentDirectiveEditForm.html

https://issues.rudder.io/issues/13531

Fixes #13531: Audit/Enforce button in directive page should be similar than node page

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PluginManagement.scala
webapp/sources/rudder/rudder-web/src/main/webapp/secure/plugins/pluginInformation.html

https://issues.rudder.io/issues/11101

Fixes #11101: Plugin id on plugin page is a bit rough

---

relay/sources/Makefile
relay/sources/relay-cleanup
relay/sources/rudder-relay.cron

https://issues.rudder.io/issues/16149

Fixes #16149: Broken relay shared-files cleanup cron

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/RuleValService.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleEditForm.scala
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentRuleEditForm.html

https://issues.rudder.io/issues/14790

Fixes #14790: Deleted directive are not always remove from rule and not actionnable

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala

https://issues.rudder.io/issues/16185

Fixes #16185: Now, "skipped" directive appears even if directive is not skipped in rule

---

webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala

https://issues.rudder.io/issues/16186

Fixes #16186: tests in rudder are broken

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/SrvGrid.scala
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/jquery/datatables/datatables-natural-sorting-1.10.20.js
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/common-layout.html

https://issues.rudder.io/issues/14433

Fixes #14433: OS version sort in nodes list is broken

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleGrid.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ComplianceData.scala

https://issues.rudder.io/issues/15124

Fixes #15124: Rule tag is "Enforce" whereas it has both enforce and audit nodes

---

webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-finished/60-trigger-node-update

https://issues.rudder.io/issues/14332

Fixes #14332: Document hook that trigger an agent run on update

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleCompliance.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ComplianceData.scala

https://issues.rudder.io/issues/14379

Fixes #14379: Directive appear in "mixed" mode in a rule applied on only one node

---

webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/techniqueEditor.html
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-bootstrap.css

https://issues.rudder.io/issues/16188

Fixes #16188: Remove unnecessary borders and padding around the Technique Editor

---

webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentComplianceMode.html

https://issues.rudder.io/issues/16191

Fixes #16191: In Node settings, "override global value" fields should have the same display 

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PropertiesManagement.scala

https://issues.rudder.io/issues/13508

Fixes #13508: JS Error when setting the "Send anonymous usage statistics " value

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchBackendImpl.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchService.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/14431

Fixes #14431: Accepted inventory without matching rudder node appears in quicksearch

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/reports/execution/ReportsExecutionService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ReportsRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ReportsJdbcRepository.scala

https://issues.rudder.io/issues/16189

Fixes #16189: Error when retrieving reports at application start

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala

https://issues.rudder.io/issues/14859

Fixes #14859: Directive creation must not display the "migrate" field 

---

CONTRIBUTING.adoc
contributing/rust.adoc

https://issues.rudder.io/issues/16196

Fixes #16196: Update Rust environment setup instructions

---

webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentNodeProperties.html

https://issues.rudder.io/issues/16194

Fixes #16194: Make the "Add node property" form more visible

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/RudderDit.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/PolicyServerManagementService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/RemoveNodeService.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/14464

Fixes #14464: If a relay is deleted (node->delete) a system rule for it remains

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala

https://issues.rudder.io/issues/16199

Fixes #16199: Missing timing info on Home Page

---

webapp/sources/pom.xml
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/AutomaticReportsCleaner.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/CheckInventoryUpdate.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/PurgeDeletedInventories.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/PurgeUnreferencedSoftwares.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/hooks/RunHooks.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryFileWatcher.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/Lock.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PolicyWriterService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/NodeChangesService.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/db/GenerateCompliance.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/hooks/RunNuCommandTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/scala-ldap/src/main/scala/com/normation/ldap/listener/InMemoryDsConnectionProvider.scala
webapp/sources/utils/src/main/scala/com/normation/ZioCommons.scala
webapp/sources/utils/src/test/scala/com/normation/ZioCommonsTest.scala

https://issues.rudder.io/issues/16206

Fixes #16206: Upgrade to ZIO 1.0-RC17

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchBackendImpl.scala

https://issues.rudder.io/issues/16203

Fixes #16203: Quicksearch leads to stacktrace since parent ticket correction

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala

https://issues.rudder.io/issues/16210

Fixes #16210: Inconsistent capitalization in menu items

---

webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/MemorySize.scala
webapp/sources/ldap-inventory/inventory-api/src/test/scala/com/normation/inventory/domain/MemoryTest.scala

https://issues.rudder.io/issues/16211

Fixes #16211: Keep "Mo" in group search for RAM

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/PolicyLogger.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ExpectedReportsJdbcRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/PolicyServerManagementService.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/HomePage.scala

https://issues.rudder.io/issues/16213

Fixes #16213: Log metrics about configuration object at start of generation

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/reports/execution/ReportsExecutionRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala

https://issues.rudder.io/issues/16200

Fixes #16200: missing timing info in complince computation

---

relay/sources/selinux/rudder-relay.fc
relay/sources/systemd/rudder-relayd-hardening

https://issues.rudder.io/issues/16227

Fixes #16227: Missing SELinux/systemd context for relayd on shared-files folder

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/reports/execution/ReportsExecutionRepositoryImpl.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportExecutionTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/16228

Fixes #16228: Fetching nodes last run is not batched

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ExecutionBatchTest.scala

https://issues.rudder.io/issues/16208

Fixes #16208: On a loaded system, the compliance computation is fairly expensive

---

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py

https://issues.rudder.io/issues/16261

Fixes #16261: Rudder package fails on a python error

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/16252

Fixes #16252: Unknown property "rudder.dir.techniques" at boot

---

webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/16264

Fixes #16264: Unkown property "rudder.techniqueLibrary.git.refs.path" at boot

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/GroupsApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala

https://issues.rudder.io/issues/16269

Fixes #16269: Could not get Group tree details cause is: Could not find Group tree.

---

webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/15989

Fixes #15989: Nova license path in log is misleading for plugin licenses

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ReportsRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ReportsJdbcRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportsTest.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/16256

Fixes #16256: Deadlock on compliance on Rudder 5.0

---

webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js

https://issues.rudder.io/issues/16231

Fixes #16231: In rule list, click on edit leads to compliance tab

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/GroupsApi.scala

https://issues.rudder.io/issues/16281

Fixes #16281: API query to get group tree fetch group

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/ShowNodeDetailsFromNode.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentNodeProperties.html
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/server/server_details.html

https://issues.rudder.io/issues/16223

Fixes #16223: Regroup tabs from "Hardware" to "Virtual Machines" into one

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ReportingServiceTest.scala

https://issues.rudder.io/issues/16280

Fixes #16280: Directives appears both skipped and enforce

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala

https://issues.rudder.io/issues/16285

Fixes #16285: Software are not async loaded anymore

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/GroupsApi.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/ShowNodeDetailsFromNode.scala

https://issues.rudder.io/issues/16286

Fixes #16286: Upmerge breaks 6.0

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/EventLogAPI.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
webapp/sources/rudder/rudder-web/src/main/webapp/secure/utilities/eventLogs.html

https://issues.rudder.io/issues/15733

Fixes #15733: Add rollback to event log pagination

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateRulePopup.scala

https://issues.rudder.io/issues/16292

Fixes #16292: When creating a rule, we reach compliance tab not setting one

---

rudder-lang/Cargo.lock
rudder-lang/Cargo.toml
rudder-lang/README.adoc

https://issues.rudder.io/issues/16304

Fixes #16304: Improve rendering of rudder-lang readme

---

rudder-lang/Cargo.toml
rudder-lang/src/ast.rs
rudder-lang/src/ast/context.rs
rudder-lang/src/ast/enums.rs
rudder-lang/src/ast/resource.rs
rudder-lang/src/ast/value.rs
rudder-lang/src/error.rs
rudder-lang/src/generators.rs
rudder-lang/src/generators/cfengine.rs
rudder-lang/src/main.rs
rudder-lang/src/parser.rs
rudder-lang/src/parser/error.rs
rudder-lang/src/parser/tests.rs
rudder-lang/src/parser/token.rs
rudder-lang/src/technique.rs

https://issues.rudder.io/issues/16305

Fixes #16305: Add license information to rudder-lang

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/EventLogRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/EventLogJdbcRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogServiceImpl.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/EventLogAPI.scala

https://issues.rudder.io/issues/15944

Fixes #15944: Filtering on eventlogs doesn't filter

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ComplianceData.scala

https://issues.rudder.io/issues/16310

Fixes #16310: Directive skipped in several place appear duplicated

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/SystemVariableSpecServiceImpl.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/MergePolicyService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PathComputer.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PolicyWriterService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PrepareTemplateVariables.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/write/WriteTechniquesTest.scala
webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample

https://issues.rudder.io/issues/16307

Fixes #16307: policy generation logs still mention promises

---

rudder-lang/src/ast.rs
rudder-lang/src/ast/enums.rs
rudder-lang/src/ast/resource.rs
rudder-lang/src/ast/value.rs
rudder-lang/src/error.rs
rudder-lang/src/generators/cfengine.rs
rudder-lang/src/main.rs
rudder-lang/src/parser.rs
rudder-lang/src/parser/error.rs
rudder-lang/src/technique.rs

https://issues.rudder.io/issues/16308

Bug 16308/fix warnings displayed by cargo clippy linter

---

SECURITY.adoc

https://issues.rudder.io/issues/16329

Fixes #16329: Update URL of our GPG key

---

webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/manageNewNode.html
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-datatable.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-node.css
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/server/server_details.html

https://issues.rudder.io/issues/16315

Fixes #16315: Node details display is broken in "Accept new nodes page"

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PropertiesManagement.scala
webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/policyServerManagement.html

https://issues.rudder.io/issues/16306

Fixes #16306: UI settings for new certificate validation system variable

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/Technique.scala

https://issues.rudder.io/issues/16316

Fixes #16316: Default values of parameters in methods cannot be used in technique editor

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-node.css

https://issues.rudder.io/issues/16321

Fixes #16321: "Security information" in node details should end by details

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/Technique.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDiffMapper.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestTechniqueWriter.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/16338

Fixes #16338: Support parameter type of technique method within Rudder

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/model/JsInitContextLinkUtil.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/Node.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/SearchNodes.scala
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder.js
webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/node.html

https://issues.rudder.io/issues/16337

Fixes #16337: Node details displays "search" form during page loading

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/Node.scala
webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/node.html

https://issues.rudder.io/issues/16352

Fixes #16352: Compilation error (classname clash)

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-node.css

https://issues.rudder.io/issues/16339

Fixes #16339: Inventory tab is missing in a pending node details

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ReportsRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ReportsJdbcRepository.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/LogDisplayer.scala

https://issues.rudder.io/issues/16353

Fixes #16353: error when searching by date on Technical Logs

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/TechniqueLibraryManagement.scala
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css

https://issues.rudder.io/issues/16320

Fixes #16320: "Reload techniques" button has a slighly different color

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala

https://issues.rudder.io/issues/16384

Fixes #16384: Invalid value in class prefix when there is a double quote in parameter

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RoleApiMapping.scala

https://issues.rudder.io/issues/16386

Fixes #16386: Technique editor access authorization seems incorect 

---

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py
relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py

https://issues.rudder.io/issues/16391

Fixes #16391: Rudder package list command should not list plugins that are not available for the user

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/components/DateFormaterService.scala

https://issues.rudder.io/issues/16389

Fixes #16389: UI - Node List - incorrect template for Hour?

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/ParameterManagement.scala
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-datatable.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-node.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-progress-bar.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-rules.css

https://issues.rudder.io/issues/16406

Fixes #16406: Wrong vertical alignement of numerous items

---

webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css

https://issues.rudder.io/issues/16113

Fixes #16113: Ttitle are too big in doc blocks of the settings page

---

relay/sources/rudder-pkg/lib/rudder-pkg/plugin.py
relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py

https://issues.rudder.io/issues/16398

Fixes #16398: Rudder-pkg fails to show installed plugins when they are not available in the configurated repo if any

---

relay/sources/rudder-pkg/lib/rudder-pkg/rpkg.py

https://issues.rudder.io/issues/16422

Fixes #16422: Rudder-pkg fails to parse new plugin nightly version

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/comet/AsyncDeployment.scala

https://issues.rudder.io/issues/16434

Fixes #16434:  scroll-issue after policy-rebuild on the GUI

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/AbstractScheduler.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/FetchNodeExecutions.scala

https://issues.rudder.io/issues/16439

Fixes #16439: Not report compliance because of scala.UninitializedFieldError

---

webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/rudder_reporting.cf

https://issues.rudder.io/issues/16409

Fixes #16409: Fixing tests after change in class used in rudder_reporting

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/comet/AsyncDeployment.scala

https://issues.rudder.io/issues/16392

Fixes #16392: Missing timezone in generation "started at" 

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala

https://issues.rudder.io/issues/16446

Fixes #16446: Technique resource are not copied to the correct path

---

webapp/sources/rudder/rudder-core/src/test/resources/hooks.d/test/echoCODE.sh
webapp/sources/rudder/rudder-core/src/test/resources/hooks.d/test/error10.sh
webapp/sources/rudder/rudder-core/src/test/resources/hooks.d/test/success.sh
webapp/sources/rudder/rudder-core/src/test/resources/hooks.d/test/warning50.sh
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/hooks/HooksTest.scala

https://issues.rudder.io/issues/16438

Fixes #16438: Backport test on Hooks to 5.0

---

webapp/sources/rudder/rudder-core/src/main/resources/ldap/bootstrap.ldif
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala

https://issues.rudder.io/issues/16458

Fixes #16458: Set HTTPS mode by default for new install, keep syslog for upgrade

---

rudder-lang/Cargo.lock
rudder-lang/Cargo.toml
rudder-lang/src/ast.rs
rudder-lang/src/ast/enums.rs
rudder-lang/src/ast/resource.rs
rudder-lang/src/data/err_fuzzy.rl
rudder-lang/src/data/test.cf
rudder-lang/src/data/test.json
rudder-lang/src/data/test.rl
rudder-lang/src/data/test.rl.cf
rudder-lang/src/data/test.rl.json
rudder-lang/src/error.rs

https://issues.rudder.io/issues/16449
Compiling and implemented fuzzy string matching feature which is a useful tool to have when dealing with compilation errors such as type or variable not found. Finds a similar variable/type name available in the actual context (global + current scope) and indicates similar names.

Fixes #16449: fuzzy matching to help with error messages

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DataStructures.scala

https://issues.rudder.io/issues/16467

Fixes #16467: A lot of data is computed and stored in Policy object, that is either never used, or used only once

---

webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder.css

https://issues.rudder.io/issues/16303

Fixes #16303: Markdown numbered list description are not correctly rendered

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NcfApi.scala

https://issues.rudder.io/issues/16383

Fixes #16383: Cannot import technique with missing component in 6.0

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/LogDisplayer.scala
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js

https://issues.rudder.io/issues/15964

Fixes #15964: Improve display of status in technical logs table

---

relay/sources/rudder-server-relay-postinst

https://issues.rudder.io/issues/16485

Fixes #16485: We mention HTTP/S in install logs

---

webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/NodeInventory.scala
webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/FusionReportUnmarshaller.scala
webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/InventoryMapper.scala
webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/LDAPConstants.scala
webapp/sources/rudder/rudder-web/src/main/resources/ldapObjectAndAttributes.properties

https://issues.rudder.io/issues/16486

Fixes #16486: Amazon Linux appears as "Other Linux 2" in nodes list

---

relay/sources/relayd/Cargo.lock
relay/sources/relayd/fuzz/Cargo.lock
relay/sources/relayd/src/configuration.rs
relay/sources/relayd/src/configuration/main.rs

https://issues.rudder.io/issues/16480

Fixes #16480: Add default values for relayd configs whenever possible

---

webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/reports/StatusReportTest.scala

https://issues.rudder.io/issues/16496

Fixes #16496: StatusReportTest leads to inconsistant results

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/hooks/RunNuCommand.scala

https://issues.rudder.io/issues/16525

Fixes #16525: Improve hook performance caused test errors

---

relay/sources/rudder-server-relay-postinst

https://issues.rudder.io/issues/16509

Fixes #16509: on centos8 relay, service relayd is not started after installation

---

relay/sources/relayd/tools/config/main.conf

https://issues.rudder.io/issues/16511

Fixes #16511: Default relayd config should have disabled reporting output

---

webapp/sources/rudder/rudder-core/src/main/resources/ldap/bootstrap.ldif
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala

https://issues.rudder.io/issues/16527

Fixes #16527: Set HTTPS mode to pure HTTPS for install, rather than HTTPS+syslogcompat

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala

https://issues.rudder.io/issues/16537

Fixes #16537: Node never updated because of nonEmpty in place of isEmpty

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/domain/Constraint.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/domain/HashAlgoConstraint.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/domain/RegexConstraint.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/domain/VariableAndSection.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DataStructures.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/InterpolatedValueCompiler.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/RuleValService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/BuildBundleSequence.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PolicyWriterService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PrepareTemplateVariables.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/cfclerk/domain/ConstraintsTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/cfclerk/domain/VariableTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/RuleValServiceTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestBuildNodeConfiguration.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestNodeAndParameterLookup.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/model/DirectiveFieldEditors.scala
webapp/sources/utils/src/main/scala/com/normation/ZioCommons.scala
webapp/sources/utils/src/test/scala/com/normation/ZioCommonsTest.scala

https://issues.rudder.io/issues/16504

Fixes #16504: Remove Box from STValidation

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/reports/execution/ReportsExecutionService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala

https://issues.rudder.io/issues/16540

Fixes #16540: We still have one lonely Future which use yet another threadpool

---

relay/sources/Makefile
relay/sources/rudder-server-relay-postinst

https://issues.rudder.io/issues/16551

Fixes #16551:  Missing failed folder for inventories on relays - rudder repo

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala

https://issues.rudder.io/issues/16522

Fixes #16522: Unecessary call to trim on empty string when creating executionBatch

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/ApplicationLogger.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/reports/execution/ReportsExecutionService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/LoadNodeComplianceCache.scala

https://issues.rudder.io/issues/16557

Fixes #16557: CachedFindRuleNodeStatusReports is a huge source of contention

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/EventLogDetailsGenerator.scala

https://issues.rudder.io/issues/16354

Fixes #16354: Updating some settings leads to an eventlog with empty  "Value" field

---

webapp/sources/rudder/rudder-core/src/main/resources/ldap/bootstrap.ldif

https://issues.rudder.io/issues/16561

Fixes #16561: Debian9 install fails due to rudder-init

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala

https://issues.rudder.io/issues/16570

Fixes #16570: Missing known bugfix workaround in parent patch

---

webapp/sources/pom.xml
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala

https://issues.rudder.io/issues/16577

Fixes #16577: Missing JS lib solved in Lift 3.4.1

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ReportingServiceUtilsTest.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala

https://issues.rudder.io/issues/16565

Fixes #16565: New cache doesn't return all compliance

---

relay/sources/relayd/Cargo.lock
relay/sources/relayd/Cargo.toml
relay/sources/relayd/fuzz/Cargo.lock
relay/sources/relayd/src/configuration/main.rs
relay/sources/relayd/src/processing/inventory.rs
relay/sources/relayd/src/processing/reporting.rs

https://issues.rudder.io/issues/16591

Fixes #16591: Fix warnings in relayd

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/DirectiveApi.scala

https://issues.rudder.io/issues/16592

Fixes #16592: Error when creating a directive with a given id from the API

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/Technique.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestTechniqueWriter.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NcfApi.scala

https://issues.rudder.io/issues/16598

Fixes #16598: Add basic support for categories in techniques from technique editor

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/v1/RestGetGitCommitAsZip.scala

https://issues.rudder.io/issues/16582

Fixes #16582: Archive of techniques miss some files needed for a technique of the technqiue editor

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogDetailsService.scala

https://issues.rudder.io/issues/16603

Fixes #16603: Clarify code of rollback events parsing

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/domain/Constraint.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/domain/TechniqueCategory.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/domain/TechniqueVersion.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/domain/VariableAndSection.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/queries/CmdbQuery.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/CmdbQueryParser.scala
webapp/sources/scala-ldap/src/main/scala/com/normation/ldap/sdk/LDAPEntry.scala
webapp/sources/scala-ldap/src/main/scala/com/normation/ldap/sdk/schema/LDAPObjectClass.scala

https://issues.rudder.io/issues/16606

Fixes #16606: same as parent ticket, but for .length

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/queries/CmdbQuery.scala

https://issues.rudder.io/issues/16607

Fixes #16607: merge error in parent ticket

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala

https://issues.rudder.io/issues/16612

Fixes #16612: New compliance cache must return expired data

---

qa-test

https://issues.rudder.io/issues/16617

Fixes #16617: Add github status for rudder-language build

---

webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/hooks/RunNuCommandTest.scala

https://issues.rudder.io/issues/16622

Fixes #16622: Timeout for `NuCommand` test is too short

---

webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/DataTypes.scala
webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/services/provisioning/GenericIdFinder.scala
webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/services/provisioning/ReportSaver.scala
webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/FusionReportUnmarshaller.scala
webapp/sources/ldap-inventory/inventory-provisioning-core/src/main/scala/com/normation/inventory/ldap/provisioning/DefaultReportSaver.scala
webapp/sources/ldap-inventory/inventory-provisioning-core/src/main/scala/com/normation/inventory/ldap/provisioning/MachineIdFinder.scala
webapp/sources/ldap-inventory/inventory-provisioning-core/src/main/scala/com/normation/inventory/ldap/provisioning/PostCommits.scala
webapp/sources/ldap-inventory/inventory-provisioning-core/src/main/scala/com/normation/inventory/ldap/provisioning/UuidMergerPreCommit.scala
webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/FullInventoryRepositoryImpl.scala
webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/InventoryMapper.scala
webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/ReadOnlySoftwareInventoryDAOImpl.scala
webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/SoftwareService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryFileWatcher.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryProcessor.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/InventoryApi.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/16624

Fixes #16624: Missing log when inventory signature check fails

---

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py

https://issues.rudder.io/issues/16630

Fixes #16630: Message indicating plugin is incompatible at the end of every plugin install from the repo

---

rudder-lang/src/ast.rs
rudder-lang/src/ast/enums.rs
rudder-lang/src/ast/resource.rs
rudder-lang/src/bin/main.rs
rudder-lang/src/compile.rs
rudder-lang/src/error.rs
rudder-lang/src/generators/cfengine.rs
rudder-lang/src/lib.rs
rudder-lang/src/logger.rs
rudder-lang/src/parser.rs
rudder-lang/src/parser/error.rs
rudder-lang/src/parser/tests.rs
rudder-lang/src/translate.rs
rudder-lang/tests/compile.rs
rudder-lang/tests/translate.rs
rudder-lang/tests/utils/mod.rs

https://issues.rudder.io/issues/16614
NO code modification. Only cargo fmt + utils moved to utils/mod.rs

Fixes #16614: format entire rudderlang code according to style guidelines 

---

relay/sources/relayd/src/api/shared_files.rs
relay/sources/relayd/src/api/shared_folder.rs

https://issues.rudder.io/issues/16648

Fixes #16648: Missing logs in shared-files API

---

relay/sources/relayd/src/api.rs

https://issues.rudder.io/issues/16655

Fixes #16655: Missing logs in relay API when an unexpected error occurs

---

relay/sources/relayd/src/api/shared_files.rs

https://issues.rudder.io/issues/16657

Fixes #16657: Hash type parsing in shared-files is broken

---

webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/AgentTypes.scala

https://issues.rudder.io/issues/16627

Fixes #16627: Remove agent type from node details

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SettingsApi.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/16667

Fixes #16667: Add authorized network api

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupCategoryForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/SearchNodeComponent.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/RuleCategoryPopup.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/model/RudderBaseField.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/Groups.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/SearchNodes.scala
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder.js
webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/groups.html
webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/searchNodes.html
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-datatable.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-groups.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-node.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder.css
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentDirectiveEditForm.html
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/NodeGroupForm.html
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/server/server_details.html

https://issues.rudder.io/issues/16473

Fixes #16473: Update UI for group page to new template

---

webapp/sources/ldap-inventory/inventory-provisioning-web/src/main/scala/com/normation/inventory/provisioning/endpoint/InventoryFileWatcher.scala

https://issues.rudder.io/issues/14991

Fixes #14991: NullPointerException with hundreds of inventories 

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SettingsApi.scala

https://issues.rudder.io/issues/16684

Fixes #16684: Inconsistency between GET et POST attribute name for authorizedNetworks JSON API

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SettingsApi.scala

https://issues.rudder.io/issues/16688

Fixes #16688: Changes to extractList break plugin API

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PolicyWriterService.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/write/WriteTechniquesTest.scala

https://issues.rudder.io/issues/16700

Fixes #16700: garbled generated policies in 6.0

---

webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/write/WriteTechniquesTest.scala
webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/16715

Fixes #16715: We still talk about cmdb-endpoint in rudder 6.0 properties

---

webapp/sources/rudder/rudder-web/src/main/resources/eventLogTypeNames.properties

https://issues.rudder.io/issues/16719

Fixes #16719: Missing event name for rudder.log.eventType.names.RudderVerifyCertificates

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderUserDetails.scala

https://issues.rudder.io/issues/16674

Fixes #16674: We should use BCrypt by default for storing user's local password

---

rudder-lang/src/ast/enums.rs
rudder-lang/src/generate_oslib.rs
rudder-lang/src/parser.rs
rudder-lang/src/parser/tests.rs
rudder-lang/src/translate.rs
rudder-lang/tests/compile.rs
rudder-lang/tests/test_files/tester/rl/condition_anybsd.rl

https://issues.rudder.io/issues/16713
logical expressions properly handled with a simple |&, tests passed

Fixes #16713: rl compile fix enum logical expressions

---

rudder-lang/src/translate.rs
rudder-lang/tests/test_files/tester/rl/condition_anybsd.rl

https://issues.rudder.io/issues/16711
small fix to add the exception, tests passed

Fixes #16711: rl translate add exception for kernel_module resource parsing

---

webapp/sources/rudder/rudder-web/src/main/resources/demo-rudder-users.xml

https://issues.rudder.io/issues/16731

Fixes #16731: Adapt user configuration file to remove default admin credentials

---

relay/sources/relayd/src/api/remote_run.rs

https://issues.rudder.io/issues/16760

Fixes #16760: Remote run always timeout for nodes behing relays

---

relay/sources/rudder-server-relay-postinst

https://issues.rudder.io/issues/16765

Fixes #16765: We should not display logs about password creation by htpasswd in relay postinst

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala

https://issues.rudder.io/issues/16777

Fixes #16777: Missing timezone in reports caption header

---

webapp/sources/rudder/rudder-web/src/main/webapp/index.html
webapp/sources/rudder/rudder-web/src/main/webapp/style/login.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/common-layout.html

https://issues.rudder.io/issues/16781

Fixes #16781: Make some changes to facilitate the integration of plugins

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitArchiverUtils.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/ZipUtils.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala

https://issues.rudder.io/issues/16805

Fixes #16805: In zip archive, all files have size 0

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitFindUtils.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/ZipUtils.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/xml/TestGitFindUtils.scala

https://issues.rudder.io/issues/16814

Fixes #16814: In zip archive, files have size zero and parent task correct by luck

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala

https://issues.rudder.io/issues/16810

Fixes #16810: Can not apply directives based on technique built only for non Linux systems if they do not contains conditions

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitParseRudderObjects.scala

https://issues.rudder.io/issues/16816

Fixes #16816: error when restoring an archive in 6.0

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/Technique.scala

https://issues.rudder.io/issues/16817

Fixes #16817: HereString are not generated properly

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/Technique.scala

https://issues.rudder.io/issues/16823

Fixes #16823: HereString wrongly escape " char

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/Lock.scala

https://issues.rudder.io/issues/16839

Fixes #16839: Restoring directive archive timeout and break LDAP

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitParseRudderObjects.scala

https://issues.rudder.io/issues/16835

Fixes #16835: when we import groups, categories are not imported, and groups are not imported either

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/Lock.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/ZipUtils.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/AgentPolicyModeEditForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/ShowNodeDetailsFromNode.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PropertiesManagement.scala
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/auditMode.js

https://issues.rudder.io/issues/16844

Fixes #16844: Changing one node policy mode change the policy mode for all nodes

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala

https://issues.rudder.io/issues/16848

Fixes #16848: It is impossible to use the /nodes/applyPolicy endpoint

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/scala-ldap/src/main/scala/com/normation/ldap/sdk/LDAPConnectionProvider.scala

https://issues.rudder.io/issues/16847

Fixes #16847: LDAP connection pool error are not correctly reported 

---

webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/fileDistribution/copyGitFile/2.3/copyFileFromSharedFolder.ps1.st
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/fileDistribution/copyGitFile/2.3/copyFileFromSharedFolder.st
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/fileDistribution/fileTemplate/1.0/fileTemplate.ps1.st
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/fileDistribution/fileTemplate/1.0/fileTemplate.st
webapp/sources/rudder/rudder-templates/src/main/scala/com/normation/templates/FillTemplatesService.scala

https://issues.rudder.io/issues/16856

Fixes #16856: Don't replace RudderUniqueId in generated policies with a replace, but with StringTemplate

---

relay/sources/api-doc/code_samples/curl/policies/dsc.sh
relay/sources/api-doc/code_samples/curl/remote-run/all.sh
relay/sources/api-doc/code_samples/curl/remote-run/node.sh
relay/sources/api-doc/code_samples/curl/remote-run/nodes.sh
relay/sources/api-doc/code_samples/curl/shared-files/head.sh
relay/sources/api-doc/code_samples/curl/shared-folder/get.sh
relay/sources/api-doc/code_samples/curl/system/info.sh
relay/sources/api-doc/code_samples/curl/system/reload.sh
relay/sources/api-doc/code_samples/curl/system/status.sh
relay/sources/api-doc/components/parameters/file-id.yml
relay/sources/api-doc/components/parameters/node-id.yml
relay/sources/api-doc/components/parameters/shared-folder-path.yml
relay/sources/api-doc/components/parameters/source-node-id.yml
relay/sources/api-doc/components/requestBodies/remote-run.yml
relay/sources/api-doc/components/responses/agent-output.yml
relay/sources/api-doc/introduction.md
relay/sources/api-doc/openapi.src.yml
relay/sources/api-doc/paths/policies.yml
relay/sources/api-doc/paths/remote-run/all.yml
relay/sources/api-doc/paths/remote-run/node.yml
relay/sources/api-doc/paths/remote-run/nodes.yml
relay/sources/api-doc/paths/shared-files.yml
relay/sources/api-doc/paths/shared-folder.yml
relay/sources/api-doc/paths/system/info.yml
relay/sources/api-doc/paths/system/reload.yml
relay/sources/api-doc/paths/system/status.yml
webapp/sources/api-doc/components/schemas/node-settings.yml
webapp/sources/api-doc/components/schemas/settings.yml
webapp/sources/api-doc/openapi.src.yml

https://issues.rudder.io/issues/16866

Fixes #16866: Add relay API and webapp v12 to api doc

---

.gitignore
relay/sources/api-doc/components/parameters/target-node-id.yml

https://issues.rudder.io/issues/16870

Fixes #16870: Missing file in relay API

---

api-doc/build.py

https://issues.rudder.io/issues/16871

Fixes #16871: Rename openapi.html to index.html

---

webapp/sources/api-doc/components/schemas/node-full.yml
webapp/sources/api-doc/openapi.src.yml
webapp/sources/api-doc/paths/change-requests/accept.yml
webapp/sources/api-doc/paths/directives/id-check.yml
webapp/sources/api-doc/paths/directives/id.yml

https://issues.rudder.io/issues/16874

Fixes #16874: Syntax errors in API doc

---

relay/sources/api-doc/paths/remote-run/node.yml

https://issues.rudder.io/issues/16875

Fixes #16875:  Syntax errors in API doc - 6.0

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/policies/Tags.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/policies/TagsTest.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleEditForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/TagsEditForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/ruleDirectives.js
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/tree.js
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-rules.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-tags.css
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentRuleEditForm.html

https://issues.rudder.io/issues/16346

Fixes #16346: Display tags when listing directives

---

relay/sources/rudder-server-relay-postinst

https://issues.rudder.io/issues/16907

Fixes #16907: during upgrade, we change permissions of /var/rudder/share, and it can be really slow

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleDisplayer.scala
webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/directiveManagement.html
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-tags.css
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentRuleEditForm.html
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentTags.html

https://issues.rudder.io/issues/16897

Fixes #16897: Not all tags have the same appearance

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleGrid.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ComplianceData.scala
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-tags.css

https://issues.rudder.io/issues/16869

Fixes #16869: Display directive tags inside Compliance tables

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PolicyWriterService.scala

https://issues.rudder.io/issues/16916

Fixes #16916: Trace log in policy generation is displaying the same value for two differents entries

---

relay/sources/rudder-server-relay-postinst

https://issues.rudder.io/issues/16923

Fixes #16923: shared-files are not writable by relayd on upgraded servers

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/RudderDit.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/NodeGroupRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/NodeRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeGroupRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeRepository.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/16906

Fixes #16906: Be able to save in LDAP a Policy Server Target

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/GitUtils.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/GitTechniqueReader.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/GitUtilsImpl.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPGitRevisionProvider.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/Lock.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitArchiverUtils.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitParseRudderObjects.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/cfclerk/services/JGitPackageReaderTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/cfclerk/services/TechniqueRepositoryTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SystemApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/v1/RestGetGitCommitAsZip.scala
webapp/sources/rudder/rudder-rest/src/test/resources/logback-test.xml
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/SystemApiTest.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/utils/src/test/scala/com/normation/ZioCommonsTest.scala

https://issues.rudder.io/issues/16929

Fixes #16929: Git configuration-repository object is created at each evaluation, impacting performance

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/AutomaticReportsCleaner.scala
webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample

https://issues.rudder.io/issues/16931

Fixes #16931: By default we should not archive reports

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ExpectedReportsJdbcRepository.scala

https://issues.rudder.io/issues/8069

Fixes #8069: Better tracking of last seen state

---

rudder-lang/Cargo.toml
rudder-lang/src/ast.rs
rudder-lang/src/ast/enums.rs
rudder-lang/src/bin/rudderc.rs
rudder-lang/src/file_paths.rs
rudder-lang/src/generators/cfengine.rs
rudder-lang/src/lib.rs
rudder-lang/src/logger.rs
rudder-lang/src/parser.rs
rudder-lang/src/parser/tests.rs

https://issues.rudder.io/issues/16939

Fixes #16939: Improve options

---

rudder-lang/Makefile
rudder-lang/README.adoc
rudder-lang/docs/examples/ntp.rl
rudder-lang/docs/index.adoc

https://issues.rudder.io/issues/16942

Fixes #16942: Test code examples is rudder lang docs

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryFileWatcher.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryProcessor.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/NodeChangesService.scala

https://issues.rudder.io/issues/16946

Fixes #16946: Infinite loop in `for` may leak memory

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeRepository.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/16968

Fixes #16968: remove rudderDit from LDAP Node repository

---

relay/sources/Makefile
relay/sources/relayd/Makefile
rudder-lang/Makefile
rust.makefile

https://issues.rudder.io/issues/16969

Fixes #16969: Display Rust tooling version in build

---

qa-test
relay/sources/relayd/Cargo.lock
relay/sources/relayd/fuzz/Cargo.lock

https://issues.rudder.io/issues/16975

Fixes #16975: Vulnerability in rust dependency

---

rudder-lang/src/ast.rs
rudder-lang/src/ast/enums.rs
rudder-lang/src/error.rs
rudder-lang/src/parser.rs
rudder-lang/src/parser/baseparsers.rs
rudder-lang/src/parser/tests.rs

https://issues.rudder.io/issues/16992

Fixes #16992: non global items can have duplicate names

---

rudder-lang/src/ast.rs
rudder-lang/src/ast/enums.rs
rudder-lang/src/parser.rs
rudder-lang/src/parser/tests.rs

https://issues.rudder.io/issues/16972
Replacing previous PR: https://github.com/Normation/rudder/pull/2846

Fixes #16972: Add enum aliases in rudder lang

---

rudder-lang/src/compile.rs

https://issues.rudder.io/issues/16998

Fixes #16998: Use Pin tu fix source code address

---

webapp/sources/pom.xml

https://issues.rudder.io/issues/17006

Fixes #17006: Upgrade Bouncy Castle GPG to last minor version

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala

https://issues.rudder.io/issues/16898

Fixes #16898: Hide remote run button for Windows agent

---

relay/sources/apache/rudder-apache-relay-ssl.conf

https://issues.rudder.io/issues/17041

Fixes #17041: Windows agents are unable to access shared-folder

---

rudder-lang/Cargo.lock
rudder-lang/Cargo.toml
rudder-lang/src/compile.rs

https://issues.rudder.io/issues/17046

Fixes #17046: Replace SourceList with a typed arena

---

rudder-lang/Cargo.lock
rudder-lang/Cargo.toml
rudder-lang/src/compile.rs

https://issues.rudder.io/issues/17047

Fixes #17047: Load all file from stdlib automatically

---

relay/sources/apache/rudder-apache-relay-ssl.conf

https://issues.rudder.io/issues/16552

Fixes #16552: Webdav password is ignored and access is granted for all nodes in allowed networks

---

webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css

https://issues.rudder.io/issues/17056

Fixes #17056: Menu scroll is broken

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala

https://issues.rudder.io/issues/17059

Fixes #17059: Prevent creating techniques in an empty category

---

rudder-lang/src/ast/value.rs
rudder-lang/src/translate.rs

https://issues.rudder.io/issues/17052

Fixes #17052: Rework os class translation into rudder-lang

---

rudder-lang/src/translate.rs

https://issues.rudder.io/issues/17066

Fixes #17066: Rework os class translation into rudder-lang

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala

https://issues.rudder.io/issues/17062

Fixes #17062: technique Resources are not provided to Windows agent

---

webapp/sources/rudder/rudder-web/src/main/resources/applicationContext-security.xml

https://issues.rudder.io/issues/17072

Fixes #17072: Allow content to be shown in frame

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/fileDistribution/copyGitFile/2.3/copyFileFromSharedFolder.ps1.st
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/1.0/technique.ps1
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/technique.ps1

https://issues.rudder.io/issues/17071

Fixes #17071: Broken dsc technique writer test

---

webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/directive.js
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/tree.js

https://issues.rudder.io/issues/16258

Fixes #16258: Folded categories in the Directive tree should be kept between sessions

---

webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/FusionReportUnmarshaller.scala

https://issues.rudder.io/issues/17081

Fixes #17081: Agent 6.0 can't update policies from Rudder 5.0

---

contributing/setup_dev_env.sh
contributing/webapp.md

https://issues.rudder.io/issues/16914

Fixes #16914: Clarify webapp contributing documentation

---

webapp/sources/rudder/rudder-web/src/main/resources/demo-rudder-users.xml

https://issues.rudder.io/issues/16732

It should be impossible to connect with "admin" password with default config

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/Login.scala
webapp/sources/rudder/rudder-web/src/main/webapp/index.html
webapp/sources/rudder/rudder-web/src/main/webapp/style/login.css

https://issues.rudder.io/issues/17070

Fixes #17070: Display a warning in place of login form if no user are defined

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/SystemVariableService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PathComputer.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestBuildNodeConfiguration.scala

https://issues.rudder.io/issues/17019

Fixes #17019: Policy generation must fail when report is HTTPS only and old agent are present

---

webapp/sources/api-doc/components/schemas/node-full.yml
webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/AgentTypes.scala
webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/NodeInventory.scala
webapp/sources/ldap-inventory/inventory-api/src/test/scala/com/normation/inventory/domain/AgentTypesTest.scala
webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/FusionReportUnmarshaller.scala
webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-report/rudder-tag/one-agent-full.ocs
webapp/sources/ldap-inventory/inventory-fusion/src/test/scala/com/normation/inventory/provisioning/fusion/TestReportParsing.scala
webapp/sources/ldap-inventory/inventory-repository/src/test/scala/com/normation/inventory/ldap/core/TestNodeUnserialisation.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/ldap/InventoryNodeInfoCompatTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/NodeDetailLevel.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala

https://issues.rudder.io/issues/12109

Fixes #12109: Agent capabilities in inventory are not parsed

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/SystemVariableService.scala

https://issues.rudder.io/issues/17085

Fixes #17085: Don't fail generation for HTTPS only reports with  DSC/6.1

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleEditForm.scala

https://issues.rudder.io/issues/17099

Fixes #17099: cannot add directives to a rules

---

webapp/sources/rudder/rudder-web/src/main/resources/demo-rudder-users.xml

https://issues.rudder.io/issues/17105

Fixes #17105: Update default rudder-users.xml

---

webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css

https://issues.rudder.io/issues/17104

Fixes #17104: Generation status color must not be grey

---

relay/sources/systemd/rudder-relayd-hardening

https://issues.rudder.io/issues/17107

Fixes #17107: Systemd hardening generates error message on remote-run

---

rudder-lang/tools/cfjson_tester

https://issues.rudder.io/issues/17097

Bug 17097/diff tester does not clean output properly

---

rudder-lang/tools/tester.sh

https://issues.rudder.io/issues/17114

Fixes #17114: logging adjustments for integration test loop

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/plugins/RudderPlugin.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/PluginExpirationInfo.scala
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder.js
webapp/sources/rudder/rudder-web/src/main/webapp/secure/plugins/pluginInformation.html
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-plugins.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css

https://issues.rudder.io/issues/16910

Fixes #16910: Beautify banner warning for expired plugin

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/plugins/PublicPlugin.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/plugins/RudderPlugin.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PluginManagement.scala
webapp/sources/rudder/rudder-web/src/main/webapp/secure/plugins/pluginInformation.html
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder.css

https://issues.rudder.io/issues/17093

Fixes #17093: Add "technical preview" status for plugins

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/DirectiveRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/NodeGroupRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/RuleRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDirectiveRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeGroupRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPRuleRepository.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/cfclerk/services/TechniqueRepositoryTest.scala

https://issues.rudder.io/issues/17112

Fixes #17112: Missing LDAP write operations to promote a node to relay

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/AutomaticReportsCleaner.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/system/DatabaseManager.scala

https://issues.rudder.io/issues/17129

Fixes #17129: when deletion of reports fails, we don't get meaningful message, and it fails when ComplianceLevels are disabled

---

rudder-lang/src/translate.rs

https://issues.rudder.io/issues/17115

Fixes #17115: make translate methods use stdlib rather than regexes

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDirectiveRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPRuleRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogFactory.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderUserDetails.scala

https://issues.rudder.io/issues/17156

Fixes #17156: Remove warning and "Inconsistance" typo compilation error

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/ComplianceModeEditForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/ShowNodeDetailsFromNode.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PropertiesManagement.scala
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/complianceMode.js
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentComplianceMode.html

https://issues.rudder.io/issues/17154

Fixes #17154: Allow HTTP reporting in changes-only mode

---

webapp/sources/api-doc/code_samples/curl/scale-out-relay/promote.sh
webapp/sources/api-doc/openapi.src.yml
webapp/sources/api-doc/paths/scale-out-relay/promote.yml

https://issues.rudder.io/issues/17162

Fixes #17162: Add promote to relay endpoint in API documentation

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/CheckInventoryUpdate.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/Technique.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestTechniqueWriter.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/ncf/TechniqueReader.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestDataSerializer.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/SharedFilesAPI.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NcfApi.scala
webapp/sources/rudder/rudder-web/src/main/resources/demo-rudder-users.xml
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckNcfTechniqueUpdate.scala

https://issues.rudder.io/issues/17133

Fixes #17133: Rudder should be able to read techniques by itself and not rely on legacy ncf rest api

---

rudder-lang/Makefile

https://issues.rudder.io/issues/17199

Fixes #17199: Do not package docopt, has it conflicts with the one from server-relay

---

webapp/sources/pom.xml

https://issues.rudder.io/issues/17201

Fixes #17201: rudder version is wrong in the login page

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PropertiesManagement.scala
webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/policyServerManagement.html

https://issues.rudder.io/issues/17186

Fixes #17186: Parent is missing changes in the settings form

---

webapp/sources/api-doc/code_samples/curl/usermanagement/add.sh
webapp/sources/api-doc/code_samples/curl/usermanagement/all.sh
webapp/sources/api-doc/code_samples/curl/usermanagement/delete.sh
webapp/sources/api-doc/code_samples/curl/usermanagement/reload.sh
webapp/sources/api-doc/code_samples/curl/usermanagement/roles.sh
webapp/sources/api-doc/code_samples/curl/usermanagement/update.sh
webapp/sources/api-doc/components/parameters/username.yml
webapp/sources/api-doc/components/schemas/users.yml
webapp/sources/api-doc/openapi.src.yml
webapp/sources/api-doc/paths/usermanagement/add.yml
webapp/sources/api-doc/paths/usermanagement/all.yml
webapp/sources/api-doc/paths/usermanagement/id.yml
webapp/sources/api-doc/paths/usermanagement/reload.yml
webapp/sources/api-doc/paths/usermanagement/roles.yml
webapp/sources/api-doc/paths/usermanagement/update.yml

https://issues.rudder.io/issues/17164

Fixes #17164: Add Usermanagement endpoints in API documentation

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/ncf/TechniqueReader.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NcfApi.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckNcfTechniqueUpdate.scala

https://issues.rudder.io/issues/17208

Fixes #17208: create generic method file missing

---

webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/nodeProperties.js
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentNodeProperties.html

https://issues.rudder.io/issues/17203

Fixes #17203: Search does not work in group criteria

---

webapp/sources/api-doc/code_samples/curl/create-node/all.sh
webapp/sources/api-doc/components/parameters/node-info.yml
webapp/sources/api-doc/components/schemas/agent-key.yml
webapp/sources/api-doc/components/schemas/node-add.yml
webapp/sources/api-doc/components/schemas/node-settings.yml
webapp/sources/api-doc/components/schemas/os.yml
webapp/sources/api-doc/components/schemas/timezone.yml
webapp/sources/api-doc/openapi.src.yml
webapp/sources/api-doc/paths/create-node/all.yml

https://issues.rudder.io/issues/17183

Fixes #17183: Add Create Node endpoint in API documentation

---

webapp/sources/pom.xml
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/ApplicationLogger.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/metrics/DataTypes.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/metrics/HistorizeNodeCountService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/metrics/Scheduler.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/metrics/NodeCountHistorizationTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/metrics/SchedulerTest.scala
webapp/sources/rudder/rudder-web/src/main/resources/logback.xml
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/utils/src/main/scala/com/normation/ZioCommons.scala

https://issues.rudder.io/issues/17161

Fixes #17161: Historize node count information

---

webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-node-ready/90-change-perm
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PolicyWriterService.scala

https://issues.rudder.io/issues/17214

Fixes #17214: chmod at the end of policy generation is painfully slow

---

webapp/sources/rudder/rudder-core/pom.xml
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/domain/TechniqueVersion.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/StatusReports.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/cfclerk/domain/TechniqueVersionTest.scala

https://issues.rudder.io/issues/17157

Fixes #17157: TechniqueVersion ordering algorithm is incorrect

---

webapp/sources/rudder/rudder-web/src/main/webapp/index.html

https://issues.rudder.io/issues/17218

Fixes #17218: Update links in login page

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala

https://issues.rudder.io/issues/17221

Fixes #17221: Compilation issue on 6.1, class name changed

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/DynGroupUpdaterService.scala

https://issues.rudder.io/issues/17220

Fixes #17220: when a node is removed from a dynamc group, it log "adding nothing, removing nothing"

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/Login.scala
webapp/sources/rudder/rudder-web/src/main/webapp/style/login.css

https://issues.rudder.io/issues/17163

Fixes #17163: After server install, the "no user" login page link to a 404 documentation page

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/ApplicationLogger.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/17228

Fixes #17228: Rudder 6.1 does not start anymore

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/Technique.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/1.0/metadata.xml
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/1.0/technique.cf
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/metadata.xml
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/technique.cf
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestTechniqueWriter.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala

https://issues.rudder.io/issues/17240

Fixes #17240: Handle parameter description of techniques parameter from editor

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder.js
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentDirectiveEditForm.html

https://issues.rudder.io/issues/17238

Fixes #17238: Display technique description in directive form as markdown

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NcfApi.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/17249

Fixes #17249: Add an endpoint to get technique categories 

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/ApplicationLogger.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupCategoryForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/TechniqueEditForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateActiveTechniqueCategoryPopup.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateCloneDirectivePopup.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateCloneGroupPopup.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/GiveReasonPopup.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/ModificationValidationPopup.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/RuleModificationValidationPopup.scala

https://issues.rudder.io/issues/17211

Fixes #17211: Properties of a group are removed when updating a group

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/RudderLDAPConstants.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/Node.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/MergeNodeProperties.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodePropertiesOverridingService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DataStructures.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/InterpolatedValueCompiler.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PolicyWriterService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PrepareTemplateVariables.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/nodes/TestMergeGroupProperties.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestNodeAndGlobalParameterLookup.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/write/WriteTechniquesTest.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PropertiesManagement.scala
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentNodeProperties.html

https://issues.rudder.io/issues/17173

Fixes #17173: Display node properties inherited from group/global

---

webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-node-ready/90-change-perm

https://issues.rudder.io/issues/17258

Fixes #17258: Parent breaks generation

---

webapp/sources/rudder/rudder-web/src/main/resources/rudder-system-global-parameter.conf
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckRudderGlobalParameter.scala

https://issues.rudder.io/issues/17251

Fixes #17251: Initialize `rudder` global parameter to default value at boot

---

webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/ReadOnlySoftwareInventoryDAOImpl.scala

https://issues.rudder.io/issues/17267

Fixes #17267: exception in ldap search are not correctly caught

---

webapp/sources/api-doc/components/schemas/directive.yml

https://issues.rudder.io/issues/17301

Fixes #17301: API documentation omits the policymode parameter of directives

---

webapp/sources/api-doc/code_samples/curl/rules/update_json.sh
webapp/sources/api-doc/components/schemas/rule-update.yml

https://issues.rudder.io/issues/17292

Fixes #17292: API documentation is lacking of a Json based update of rule/directive

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleCompliance.scala
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentRuleEditForm.html

https://issues.rudder.io/issues/17290

Fixes #17290: RuleID is not trimmed when copied from the GUI

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/InterpolatedValueCompiler.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestNodeAndGlobalParameterLookup.scala

https://issues.rudder.io/issues/17307

Fixes #17307: Improve parsing of non rudder variable in directives fields.

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/ShowNodeDetailsFromNode.scala
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-node.css

https://issues.rudder.io/issues/16515

Fixes #16515: Page for node not found is too minimalist

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/Technique.scala

https://issues.rudder.io/issues/17331

Fixes #17331: method call paramter name key should be name and not methodId

---

webapp/sources/pom.xml
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/MergeNodeProperties.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/nodes/TestMergeGroupProperties.scala
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentNodeProperties.html

https://issues.rudder.io/issues/17324

Fixes #17324: Group properties inheritance error when it should not

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/parameters/GlobalParameter.scala

https://issues.rudder.io/issues/17326
Implicit conversion are evil.

Fixes #17326: JSON global parameter are inherited as string

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/NodeGroup.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDiffMapper.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/InterpolatedValueCompiler.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestNodeAndGlobalParameterLookup.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala

https://issues.rudder.io/issues/17334

Fixes #17334: Property name aren't limited to ascii

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/17341

Fixes #17341: Data for reporting plugin are not generated anymore

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/Login.scala

https://issues.rudder.io/issues/17317

Fixes #17317: Add auto reload of welcome page

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/Technique.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestTechniqueWriter.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala

https://issues.rudder.io/issues/17348

Fixes #17348: when importing a technique with  /api/internal/techniques, the order of parameters is not respected

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/Technique.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestTechniqueWriter.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala

https://issues.rudder.io/issues/17321

Fixes #17321: The generic methods documentation is no longer accessible from the technique editor
