Normation/rudder

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NcfApi.scala

https://issues.rudder.io/issues/17338

Fixes #17338: When defining a category for a new technique, the files are not placed on the correct path in the git repo

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala

https://issues.rudder.io/issues/17358

Fixes #17358: ncf method write test in error

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DataStructures.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/InterpolatedValueCompiler.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestNodeAndGlobalParameterLookup.scala

https://issues.rudder.io/issues/17350

Fixes #17350: Inconsistant syntax for global parameter in directive incompatible with JSON values

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/metrics/HistorizeNodeCountService.scala

https://issues.rudder.io/issues/17372

Fixes #17372: Historization of node count reports wrong value for pending nodes

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala

https://issues.rudder.io/issues/17373

Fixes #17373: duplicates entries when saving node compliance levels

---

webapp/sources/api-doc/components/schemas/node-full.yml
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/NodeDetailLevel.scala

https://issues.rudder.io/issues/17367

Fixes #17367: Missing info about if a node is a relay in API and capabilities need to to in management technologie

---

rudder-lang/src/ast.rs
rudder-lang/src/file_paths.rs
rudder-lang/tests/test_files/tester/parameters/technique.rl
rudder-lang/tools/rudderc-prod.conf

https://issues.rudder.io/issues/17355

Fixes #17355: update reserved keywords list

---

rudder-lang/Cargo.lock
rudder-lang/Cargo.toml
rudder-lang/deny.toml

https://issues.rudder.io/issues/17374

Fixes #17374: Add a cargo-deny config for rudder-lang

---

webapp/sources/rudder/rudder-web/src/main/elm/notifications/build-dev.sh
webapp/sources/rudder/rudder-web/src/main/elm/notifications/sources/rudder-notifications.elm
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-elm.js
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-notifications.css

https://issues.rudder.io/issues/17383

Fixes #17383: Improve notification display in Rudder

---

webapp/sources/rudder/rudder-core/src/main/resources/ldap/rudder.schema
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDiffMapper.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPParameterRepository.scala

https://issues.rudder.io/issues/17396

Fixes #17396: err17: can not update attribute in parameter

---

rudder-lang/src/ast.rs

https://issues.rudder.io/issues/17405

Fixes #17405: fix compilation failure

---

relay/sources/relayd/Cargo.lock

https://issues.rudder.io/issues/17384

Fixes #17384: Update relayd dependencies to remove unmaintained "spin" crate

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestTechniqueWriter.scala
webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/17412

Fixes #17412: Add a feature switch for rudder-lang test loop

---

webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala

https://issues.rudder.io/issues/17411

Fixes #17411: Stacktrace in test introduce in #17341

---

relay/sources/relayd/src/configuration/main.rs
relay/sources/relayd/src/output/upstream.rs
relay/sources/relayd/tests/files/config/main.conf
relay/sources/relayd/tools/config/main.conf

https://issues.rudder.io/issues/17416

Fixes #17416: Inventories from new nodes should be sent using the "rudder" password and not generated one

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateOrUpdateGlobalParameterPopup.scala
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-directives.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css

https://issues.rudder.io/issues/17325

Fixes #17325: We can't choose between string and json for global parameters

---

webapp/sources/api-doc/code_samples/curl/change-requests/remove-valid-users.sh
webapp/sources/api-doc/code_samples/curl/change-requests/update-valid-users.sh
webapp/sources/api-doc/code_samples/curl/change-requests/valid-users.sh
webapp/sources/api-doc/components/schemas/validated-user.yml
webapp/sources/api-doc/openapi.src.yml
webapp/sources/api-doc/paths/change-requests/remove-valid-users.yml
webapp/sources/api-doc/paths/change-requests/update-valid-users.yml
webapp/sources/api-doc/paths/change-requests/valid-users.yml

https://issues.rudder.io/issues/17434

Fixes #17434: Missing validated user endpoints in change validation api doc

---

webapp/sources/api-doc/code_samples/curl/rules/category-id-new.sh
webapp/sources/api-doc/components/schemas/rule-with-category.yml
webapp/sources/api-doc/paths/rules/id.yml

https://issues.rudder.io/issues/17409

Fixes #17409: API documentation on Rules is missing explaination on how to update rule category

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/ShowNodeDetailsFromNode.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/AsyncComplianceService.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/SrvGrid.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/Node.scala
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-bootstrap.css
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/server/server_details.html

https://issues.rudder.io/issues/17427

Fixes #17427: Separate System Rules from USer Defined Rules in Node compliance display

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/RuleValService.scala

https://issues.rudder.io/issues/17441

Fixes #17441: Ignored node lead to an error log during generation

---

rust.makefile

https://issues.rudder.io/issues/17191

Fixes #17191: add debug to makefile

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryFileWatcher.scala
webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/15422

Fixes #15422: Some inventories are not correctly noticed by inotify file watcher

---

webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-node.css

https://issues.rudder.io/issues/17440

Fixes #17440: Ignored (disabled) nodes are show as enabled in details

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/RuleApi.scala

https://issues.rudder.io/issues/17388

Fixes #17388: Bad JSON answer for api PUT /rules

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/TechniqueEditForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala

https://issues.rudder.io/issues/17413

Fixes #17413: Technique doc is not formatted when clicking on technique in tree

---

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py

https://issues.rudder.io/issues/17453

Fixes #17453: rudder package command fails when not run from a terminal

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/RuleApi.scala

https://issues.rudder.io/issues/17455

Fixes #17455: API change in rules upmerge breaks rudder 6.1

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/RuleApi.scala

https://issues.rudder.io/issues/17456

Fixes #17456: Parent ticket on rule api need to be backported on 5.0

---

relay/sources/relayd/src/data/node.rs
relay/sources/relayd/tests/files/nodeslist.json

https://issues.rudder.io/issues/17461

Fixes #17461: Allow nodes not to have a hash

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/nodeProperties.js
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-groups.css
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentNodeProperties.html
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/NodeGroupForm.html

https://issues.rudder.io/issues/17312

Fixes #17312: Group property UX is unclear regarding saving

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeGroupRepository.scala

https://issues.rudder.io/issues/17421

Fixes #17421: error about group consistency at upgrade from Rudder 6.0 to 6.1

---

webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/server/server_details.html

https://issues.rudder.io/issues/17486

Fixes #17486: Move "System status" tab before technical logs

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/reports/execution/ReportsExecutionService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ComplianceRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ComplianceRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/RuleValService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala

https://issues.rudder.io/issues/17410

Fixes #17410: Error log about duplicates entries when saving node compliance levels

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala

https://issues.rudder.io/issues/17487

Fixes #17487: Change message in case of udefined certificate for a node

---

webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/ReadOnlySoftwareInventoryDAOImpl.scala

https://issues.rudder.io/issues/17176

Fixes #17176: Purge of unreferenced software may still fail on very large system

---

relay/sources/selinux/rudder-relay.fc

https://issues.rudder.io/issues/17488

Fixes #17488: Allow httpd to serve policy files for windows

---

webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/ReadOnlySoftwareInventoryDAOImpl.scala

https://issues.rudder.io/issues/17490

Fixes #17490: Build broke in 6.1 due to faulty merge

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/Properties.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/nodes/GenericPropertiesTest.scala

https://issues.rudder.io/issues/17491

Fixes #17491: Global parameter which are a comment string are ignored

---

webapp/sources/rudder/rudder-web/src/main/webapp/images/os/unknown-logo.svg
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-node.css

https://issues.rudder.io/issues/16454

Fixes #16454: OS logo is missing in summary node

---

webapp/sources/api-doc/code_samples/curl/system/get-archive-zip.sh
webapp/sources/api-doc/code_samples/curl/system/restore-archive.sh
webapp/sources/api-doc/components/parameters/archive-kind.yml
webapp/sources/api-doc/openapi.src.yml
webapp/sources/api-doc/paths/system/archives-restore.yml
webapp/sources/api-doc/paths/system/archives-zip.yml
webapp/sources/api-doc/paths/system/archives.yml
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/xmlparsers/VariableSpecParser.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ItemArchiveManager.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPParameterRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/ItemArchiveManagerImpl.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlUnserialisationImpl.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SystemApi.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/Archives.scala
webapp/sources/rudder/rudder-web/src/main/webapp/secure/utilities/archiveManagement.html

https://issues.rudder.io/issues/17457

Fixes #17457: Parameters are not restored from archive

---

webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/nodes/GenericPropertiesTest.scala
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/nodeProperties.js

https://issues.rudder.io/issues/17517

Fixes #17517: Bad API url called when saving properties 

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckNashornWarning.scala

https://issues.rudder.io/issues/17524

Fixes #17524: Nashorn deprecation should be "info" level

---

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py
relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
relay/sources/rudder-pkg/rudder-pkg
relay/sources/rudder-server-relay-postinst

https://issues.rudder.io/issues/17525

Fixes #17525: remove progressive output from postinstall

---

relay/sources/selinux/rudder-relay.te

https://issues.rudder.io/issues/17516

Fixes #17516: Remote-run does not work anymore with SELinux

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/DebugComplianceLogger.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/StatusReports.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ComplianceRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala

https://issues.rudder.io/issues/17527

Fixes #17527: When no User rules are defined on a node, compliance tab on node details shows an error 

---

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py
relay/sources/rudder-pkg/rudder-pkg
relay/sources/rudder-server-relay-postinst

https://issues.rudder.io/issues/17533

Fixes #17533: Parent issue not fixed

---

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py

https://issues.rudder.io/issues/17534

Fixes #17534: Parent issue not fixed

---

contributing/rudder.conf
contributing/setup_dev_env.sh
contributing/webapp.md

https://issues.rudder.io/issues/17502

Fixes #17502: Add explanation to setup technique editor in development environement in 6.1

---

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py

https://issues.rudder.io/issues/17537

Fixes #17537: Parent issue not fixed

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/TechniqueAcceptationDatetimeUpdater.scala

https://issues.rudder.io/issues/17523

Fixes #17523: error when a technique with a directive attached change in 6.1 blocks all technique updates

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleCompliance.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleEditForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/TagsEditForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/RuleManagement.scala
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/tags.js

https://issues.rudder.io/issues/15557

Fixes #15557: When adding tags, if anything is wrong in the directive form, all unsaved tags are wiped out

---

relay/sources/selinux/rudder-relay.te

https://issues.rudder.io/issues/17538

Fixes #17538: Remote-run broken when SELinux is enabled

---

webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentNodeProperties.html

https://issues.rudder.io/issues/17546

Fixes #17546: z-index of group property inherited tooltip is bad

---

webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-plugins.css

https://issues.rudder.io/issues/17553

Fixes #17553: Broken appearance of hover details in node details

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PluginManagement.scala

https://issues.rudder.io/issues/17544

Fixes #17544: Plugin names are not displayed

---

relay/sources/selinux/rudder-relay.te

https://issues.rudder.io/issues/17518

Fixes #17518: postgresl client in relayd tries to read krb conf

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/WriteNodeCertificatesPem.scala

https://issues.rudder.io/issues/17555

Fixes #17555: error in webapp log after upgrade to 6.1-rc1

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/MergeNodeProperties.scala
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/nodeProperties.js
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentNodeProperties.html

https://issues.rudder.io/issues/17547
Depends on PR https://github.com/Normation/rudder/pull/3028

Fixes #17547: Multiple problems with inherited (group, node) properties

---

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py

https://issues.rudder.io/issues/16793

Fixes #16793: Rudder package list should display plugin status

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala

https://issues.rudder.io/issues/17593

Fixes #17593: Workaround tooltip not displaying hover node properties tag

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/RudderDit.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeGroupRepository.scala

https://issues.rudder.io/issues/17476

Fixes #17476: error about group consistency at upgrade from Rudder 6.0 to 6.1

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/AsyncDeploymentActor.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/CheckInventoryUpdate.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/UpdateDynamicGroups.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/PolicyGenerationLogger.scala

https://issues.rudder.io/issues/17599

Fixes #17599: Make logger for policy generation more specific

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/NodeInfo.scala

https://issues.rudder.io/issues/17597

Fixes #17597: NPE when agent key is malformed

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RoleApiMapping.scala

https://issues.rudder.io/issues/17601

Fixes #17601: parent ticket breaks build

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/CheckInventoryUpdate.scala
webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/17602

Fixes #17602: NodeCacheImpl delay is incorrect and should be configurable

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/UpdateDynamicGroups.scala

https://issues.rudder.io/issues/17594

Fixes #17594: no policy generation after accepting many nodes in 6.1

---

webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/ReadOnlySoftwareInventoryDAOImpl.scala

https://issues.rudder.io/issues/17605

Fixes #17605: compilation error in 6.0 because of absence of typo in Inconsistency

---

relay/sources/rudder-pkg/lib/rudder-pkg/plugin.py
relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py
relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgLogger.py
relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
relay/sources/rudder-pkg/rudder-pkg

https://issues.rudder.io/issues/17600

Fixes #17600: rudder package logs are inconsistent

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/BuildBundleSequence.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/write/PrepareTemplateVariableTest.scala

https://issues.rudder.io/issues/17628

Fixes #17628: policy generation fails if we put a " in the directive name

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/nodeProperties.js
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentNodeProperties.html

https://issues.rudder.io/issues/17550

Fixes #17550: tooltip for node properties does not show

---

webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css

https://issues.rudder.io/issues/17575

Fixes #17575: when searching nodes, on the search page, the checkbox "Include Rudder server components" if briefly checked and unchecked

---

webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css

https://issues.rudder.io/issues/17619

Fixes #17619: Plugin expiration warning misalignement problem

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala

https://issues.rudder.io/issues/17556

Fixes #17556: Rudder logo appears in remote-run error message

---

webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentNodeProperties.html

https://issues.rudder.io/issues/17623

Fixes #17623: Overriden pop-up top is missing

---

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py

https://issues.rudder.io/issues/17645

Fixes #17645: ruder package command fails to run in automated setup

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestUtils.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/NodeGroupForm.html

https://issues.rudder.io/issues/17638

Fixes #17638: text explaining hierarchy of groups always shows up for system group

---

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py

https://issues.rudder.io/issues/17645

Fixes #17645: ruder package fails to run in automated setup

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/Technique.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestTechniqueWriter.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala

https://www.rudder-project.org/redmine/issues/17647

Fixes #17647: Deprecated method filter is broken

---

relay/sources/rudder-pkg/lib/rudder-pkg/plugin.py

https://issues.rudder.io/issues/17626

Fixes #17626: Improve rudder package error message when an update is needed

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/Properties.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/ldap/GlobalParamMigration61Test.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateOrUpdateGlobalParameterPopup.scala

https://issues.rudder.io/issues/17674

Fixes #17674: Global parameter "string" doesn't escape json

---

webapp/sources/utils/src/main/scala/com/normation/ZioCommons.scala

https://issues.rudder.io/issues/17684

Fixes #17684: Add exception info when a system error occure 

---

relay/sources/Makefile
relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py

https://issues.rudder.io/issues/17675

Fixes #17675: package key is not trusted by rudder-pkg

---

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py

https://www.rudder-project.org/redmine/issues/17673

Fixes #17673: Cannot download licenses if there is a trailing slash in rudder package config url

---

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py

https://issues.rudder.io/issues/17692

Fixes #17692: gpg import error in rudder-pkg

---

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py

https://issues.rudder.io/issues/17694

Fixes #17694: gpg import error in rudder-pkg -  command doesn't execute

---

relay/sources/Makefile

https://issues.rudder.io/issues/17696

Fixes #17696: Debian part of parent ticket

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/domain/Technique.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/TechniqueTree.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/TechniqueLibraryManagement.scala

https://issues.rudder.io/issues/17698

Fixes #17698: 

---

webapp/sources/rudder/rudder-web/src/main/resources/rudder-system-global-parameter.conf

https://issues.rudder.io/issues/17700

Fixes #17700: description of global parameter "rudder" is misleading

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/SharedFilesAPI.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NcfApi.scala

https://issues.rudder.io/issues/17747

Fixes #17747: Resource path of a technique with a category different thant default category are wrong

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/HistorizationService.scala

https://issues.rudder.io/issues/17778
Replacing previous PR: https://github.com/Normation/rudder/pull/3086

Fixes #17778: table nodes contains on entry per node per generation, which is too much

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateCategoryOrGroupPopup.scala

https://issues.rudder.io/issues/17678

Fixes #17678: when we create a group, we should go directly to the criteria page

---

webapp/sources/rudder/rudder-web/src/main/webapp/secure/plugins/pluginInformation.html
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css

https://issues.rudder.io/issues/17731

Fixes #17731: Content in header of plugin page overflows when custom from branding is activate

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/Technique.scala

https://issues.rudder.io/issues/17812

Fixes #17812: Remove args from data send by technique api

---

rudder-lang/libs/resourcelib.rl
rudder-lang/src/generators.rs
rudder-lang/src/generators/dsc.rs
rudder-lang/src/translate.rs
rudder-lang/tests/test_files/tester/parameters/technique.rl.cf
rudder-lang/tools/generate_lib
rudder-lang/tools/generic_methods.toml

https://issues.rudder.io/issues/17585

Fixes #17585: dsc integration

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala

https://issues.rudder.io/issues/17824

Fixes #17824: parse parameters instead of args, but keep args for migration from old techniques format

---

rudder-lang/tests/helpers/get_server_technique.sh
rudder-lang/tools/rudderc-prod.conf
rudder-lang/tools/tester.sh
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala

https://issues.rudder.io/issues/17737

Fixes #17737: handle techniques location path properly

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala

https://issues.rudder.io/issues/17750

Fixes #17750: "unsaved changed" technique editor pop-up appears when not needed

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeStateForm.scala
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-node.css
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentNodeState.html

https://issues.rudder.io/issues/17627

Fixes #17627: Select node state in settings is confusiing for read_only user 

---

webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/directiveManagement.html
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-directives.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentAgentPolicyMode.html
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/reports_server.html

https://issues.rudder.io/issues/17725

Fixes #17725: user with read_only right has button that allows write actions 

---

rudder-lang/src/ast/context.rs
rudder-lang/src/parser.rs

https://issues.rudder.io/issues/17811

Fixes #17811: fix nasty random generation failure

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/Properties.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/nodes/NodePropertiesTest.scala

https://issues.rudder.io/issues/17830

Fixes #17830: Updating property merge them in place of replacing them

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/TechniqueRepositoryImpl.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/hooks/RunNuCommand.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/ncf/TechniqueReader.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/17775

Fixes #17775: Uncommited generic_methods.json in configuration repo

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitArchiverUtils.scala

https://issues.rudder.io/issues/17777

Fixes #17777: Auto-archive gitRepo.git failure warning is not actionnable, should be info or debug

---

webapp/sources/api-doc/components/schemas/group-new.yml
webapp/sources/api-doc/components/schemas/group.yml
webapp/sources/api-doc/components/schemas/parameter.yml

https://issues.rudder.io/issues/17818

Fixes #17818: Missing doc for group properties and json global parameters

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/model/DirectiveEditor.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentRuleEditForm.html

https://issues.rudder.io/issues/17845

Fixes #17845: Disable action buttons for read_only users

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/nodeconfig/NodeConfigurationCacheRepository.scala

https://issues.rudder.io/issues/17851

Fixes #17851: Wrong error message when policy server of a Node is not found during generation 

---

relay/sources/rudder-server-relay-postinst

https://issues.rudder.io/issues/17802

Fixes #17802: shared-files acls are incorrect on relays

---

webapp/sources/rudder/rudder-web/src/main/elm/build-app.sh

https://issues.rudder.io/issues/17888

Fixes #17888: Optimize elm application

---

relay/sources/rudder-server-relay-postinst

https://issues.rudder.io/issues/17882

Fixes #17882: Shared-files correction in postinst must be recursive

---

webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-datatable.css

https://issues.rudder.io/issues/16032

Fixes #16032: Inconsistent fonts in technical logs

---

rudder-lang/libs/cfengine_core.rl
rudder-lang/src/translate.rs

https://issues.rudder.io/issues/17885

Fixes #17885: make use of parameters instead of args

---

rudder-lang/src/parser/error.rs
rudder-lang/src/parser/tests.rs

https://issues.rudder.io/issues/17914

Fixes #17914: rudderc is way too slow -  Tests fail

---

webapp/sources/api-doc/code_samples/curl/cve/allDetails.sh
webapp/sources/api-doc/code_samples/curl/cve/check.sh
webapp/sources/api-doc/code_samples/curl/cve/checkConfig.sh
webapp/sources/api-doc/code_samples/curl/cve/config.sh
webapp/sources/api-doc/code_samples/curl/cve/getConfig.sh
webapp/sources/api-doc/code_samples/curl/cve/lastCheck.sh
webapp/sources/api-doc/code_samples/curl/cve/listCVE.sh
webapp/sources/api-doc/code_samples/curl/cve/updateCVE.sh
webapp/sources/api-doc/code_samples/curl/cve/updateCVEFS.sh
webapp/sources/api-doc/code_samples/curl/cve/updateConfig.sh
webapp/sources/api-doc/components/schemas/cveCheck.yml
webapp/sources/api-doc/components/schemas/cveDetails.yml
webapp/sources/api-doc/openapi.src.yml
webapp/sources/api-doc/paths/cve/allCVE.yml
webapp/sources/api-doc/paths/cve/check.yml
webapp/sources/api-doc/paths/cve/checkConfig.yml
webapp/sources/api-doc/paths/cve/last.yml
webapp/sources/api-doc/paths/cve/listCVE.yml
webapp/sources/api-doc/paths/cve/update.yml
webapp/sources/api-doc/paths/cve/updateCVE.yml
webapp/sources/api-doc/paths/cve/updateCVEFromFS.yml
webapp/sources/api-doc/paths/cve/updateFS.yml

https://issues.rudder.io/issues/17940

Fixes #17940: CVE plugin api documentation

---

webapp/sources/api-doc/components/schemas/cveDetails.yml
webapp/sources/api-doc/paths/cve/check.yml

https://issues.rudder.io/issues/17943

Fixes #17943: Broken API doc build after parent

---

webapp/sources/api-doc/components/schemas/cveCheck.yml
webapp/sources/api-doc/paths/cve/checkConfig.yml
webapp/sources/api-doc/paths/cve/last.yml

https://issues.rudder.io/issues/17956

Fixes #17956: Typos in CVE api doc

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/domain/TechniqueResource.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PolicyWriterService.scala

https://issues.rudder.io/issues/17944

Fixes #17944: Incorrect error message when a resource is not found

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/EditPolicyServerAllowedNetwork.scala

https://issues.rudder.io/issues/17967

Fixes #17967: Missing interpolator in error message for allowed networks

---

webapp/sources/pom.xml
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitFindUtils.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/xml/TestGitFindUtils.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NcfApi.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/17977

Fixes #17977: Resource automatically added on newly created technique - since 6.1 upgrade

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/HomePage.scala

https://issues.rudder.io/issues/17202

Fixes #17202: Number of groups on the dashboard in incorrect

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/metrics/DataTypes.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/metrics/HistorizeNodeCountService.scala

https://issues.rudder.io/issues/17856

Fixes #17856:  Historization of node count reports inverts pending and accepted

---

api-doc/build.py
relay/sources/api-doc/introduction.md
webapp/sources/api-doc/components/securitySchemes/token.yml
webapp/sources/api-doc/introduction.md
webapp/sources/api-doc/openapi.src.yml

https://issues.rudder.io/issues/18020

Fixes #18020: Fix swagger warnings in api doc

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala

https://issues.rudder.io/issues/18027

Fixes #18027: na reports for Windows techniques on Linux generate broken condition

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/InterpolatedValueCompiler.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestNodeAndGlobalParameterLookup.scala

https://issues.rudder.io/issues/18025

Fixes #18025: Use node properties as path for node properties

---

webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestTechniqueWriter.scala

https://issues.rudder.io/issues/18036

Fixes #18036: fix failling test

---

webapp/sources/api-doc/code_samples/curl/compliance/nodes.sh
webapp/sources/api-doc/code_samples/curl/nodes/all.sh
webapp/sources/api-doc/code_samples/curl/rules/all.sh

https://issues.rudder.io/issues/18021

Fixes #18021: Add request examples to API doc

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DependencyAndDeletionService.scala

https://issues.rudder.io/issues/17906

Fixes #17906: Error when trying to enable a disabled Technique in the technique tree

---

webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentComplianceMode.html

https://issues.rudder.io/issues/16402

Fixes #16402: Cannot set Compliance reporting mode on "Non compliant only" in settings tab

---

rudder-lang/libs/resourcelib.rl
rudder-lang/src/generators/dsc.rs
rudder-lang/tools/generate_lib

https://issues.rudder.io/issues/17904

Fixes #17904: make use of conditional and flow statements for dsc

---

rudder-lang/src/parser/tests.rs

https://issues.rudder.io/issues/18053

Fixes #18053: Switch to nom_locate 2 -  missing tests

---

rudder-lang/src/ast/resource.rs
rudder-lang/src/parser.rs
rudder-lang/src/parser/baseparsers.rs
rudder-lang/src/parser/tests.rs
rudder-lang/src/parser/token.rs

https://issues.rudder.io/issues/18062

Fixes #18062: Add a source context to statements

---

rudder-lang/Cargo.lock
rudder-lang/Cargo.toml
rudder-lang/src/ast.rs
rudder-lang/src/ast/context.rs
rudder-lang/src/ast/enum_tree.rs
rudder-lang/src/ast/enums.rs
rudder-lang/src/ast/resource.rs
rudder-lang/src/ast/value.rs
rudder-lang/src/compile.rs
rudder-lang/src/generators/cfengine.rs
rudder-lang/src/generators/cfengine/syntax.rs
rudder-lang/src/generators/dsc.rs
rudder-lang/src/io.rs
rudder-lang/src/logger.rs
rudder-lang/src/parser.rs
rudder-lang/src/parser/baseparsers.rs
rudder-lang/src/parser/error.rs
rudder-lang/src/parser/tests.rs
rudder-lang/src/parser/token.rs
rudder-lang/src/translate.rs
rudder-lang/tests/utils/mod.rs

https://issues.rudder.io/issues/18064

Fixes #18064: Fix warnings and update dependencies

---

rudder-lang/src/generators/cfengine.rs
rudder-lang/src/generators/cfengine/syntax.rs
rudder-lang/tests/techniques/simplest/technique.rl
rudder-lang/tests/techniques/simplest/technique.rl.cf

https://issues.rudder.io/issues/18066

Fixes #18066: Add proper generation for log and fail methods in CFEngine

---

rudder-lang/Cargo.lock
rudder-lang/Cargo.toml
rudder-lang/src/ast/context.rs
rudder-lang/src/ast/enum_tree.rs
rudder-lang/src/ast/enums.rs
rudder-lang/src/generators/cfengine.rs
rudder-lang/src/generators/cfengine/syntax.rs
rudder-lang/src/generators/dsc.rs
rudder-lang/src/parser.rs
rudder-lang/src/parser/tests.rs

https://issues.rudder.io/issues/18068

Fixes #18068: Add source information in enum expression

---

rudder-lang/docs/DESIGN_DECISIONS
rudder-lang/docs/enums.adoc
rudder-lang/docs/examples/statements.rl
rudder-lang/docs/index.adoc
rudder-lang/docs/items.adoc
rudder-lang/docs/lexical-structure.adoc
rudder-lang/docs/statements-and-expressions.adoc

https://issues.rudder.io/issues/18071

Fixes #18071: Minor rudder-lang doc fixup

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NcfApi.scala

https://issues.rudder.io/issues/18044

Fixes #18044: Generic method are not sorted by alpha-num order

---

rudder-lang/docs/DESIGN_DECISIONS
rudder-lang/libs/resourcelib.rl
rudder-lang/src/ast.rs
rudder-lang/src/ast/enum_tree.rs
rudder-lang/src/ast/enums.rs
rudder-lang/src/ast/resource.rs
rudder-lang/src/generators/cfengine.rs
rudder-lang/src/generators/dsc.rs
rudder-lang/src/parser.rs
rudder-lang/src/parser/error.rs
rudder-lang/src/parser/tests.rs
rudder-lang/src/translate.rs
rudder-lang/tests/compile.rs
rudder-lang/tools/generate_lib

https://issues.rudder.io/issues/18075

Fixes #18075: Switch rudder-lang metadata format to toml

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NcfApi.scala

https://issues.rudder.io/issues/18085

Fixes #18085: Broken technique resources in 6.1.2

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/GitTechniqueReader.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/TechniqueRepositoryImpl.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/TechniqueAcceptationDatetimeUpdater.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestTechniqueWriter.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NcfApi.scala
webapp/sources/rudder/rudder-web/src/main/resources/logback.xml

https://issues.rudder.io/issues/18086

Fixes #18086: Resources changes are not commited in git

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/api/ApiAccountDiff.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDiffMapper.scala

https://issues.rudder.io/issues/18052

Fixes #18052: Error displayed when switching from full access to read only

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/reports/execution/ReportsExecutionRepositoryImpl.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ReportsJdbcRepository.scala

https://issues.rudder.io/issues/18093

Fixes #18093: Simplify queries to detects runs in database, as all runs are complete

---

webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/FusionReportUnmarshaller.scala

https://issues.rudder.io/issues/18097

Fixes #18097: duplicate parsing for hostname in inventory processing

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/rudder_reporting.cf

https://issues.rudder.io/issues/18101

Fixes #18101: "error: Only functions returning scalars can be used as arguments" in verbose output

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/rudder_reporting.cf

https://issues.rudder.io/issues/18100

Fixes #18100: Techniques with conditions on tasks with very long parameters, report "missing" parts on the dashboard

---

rudder-lang/src/ast.rs
rudder-lang/src/ast/context.rs
rudder-lang/src/ast/resource.rs

https://issues.rudder.io/issues/18107

Fixes #18107: Context structure members should be private

---

rudder-lang/libs/cfengine_core.rl
rudder-lang/src/ast.rs
rudder-lang/src/ast/context.rs
rudder-lang/src/parser.rs
rudder-lang/src/parser/tests.rs

https://issues.rudder.io/issues/18115

Fixes #18115: Implement struct type

---

rudder-lang/src/ast.rs
rudder-lang/src/ast/context.rs
rudder-lang/src/ast/enums.rs
rudder-lang/src/ast/resource.rs
rudder-lang/src/ast/value.rs

https://issues.rudder.io/issues/18106

Fixes #18106: Context should contain only variable->type mapping

---

rudder-lang/src/ast.rs
rudder-lang/src/ast/context.rs
rudder-lang/src/ast/enums.rs
rudder-lang/src/ast/resource.rs
rudder-lang/src/bin/rudderc.rs
rudder-lang/src/compile.rs
rudder-lang/src/error.rs
rudder-lang/src/generator.rs
rudder-lang/src/generator/cfengine.rs
rudder-lang/src/io.rs
rudder-lang/src/lib.rs
rudder-lang/src/logger.rs
rudder-lang/src/opt.rs
rudder-lang/src/parser.rs
rudder-lang/src/parser/error.rs
rudder-lang/src/parser/tests.rs
rudder-lang/src/parser/token.rs
rudder-lang/tests/utils/mod.rs

https://issues.rudder.io/issues/18121

Fixes #18121: cargo fmt

---

relay/sources/relayd/Cargo.toml
relay/sources/relayd/deny.toml
rust.makefile

https://issues.rudder.io/issues/18123

Fixes #18123:  Use cargo-deny to replace cargo-audit

---

rudder-lang/Makefile
rudder-lang/src/ast.rs
rudder-lang/src/parser.rs
rudder-lang/tools/generate_lib

https://issues.rudder.io/issues/18126

Fixes #18126: rudder-lang tests fail on system with python2

---

rudder-lang/tools/generate_lib

https://issues.rudder.io/issues/18128

Fixes #18128: Sort the generated lib

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala
webapp/sources/rudder/rudder-core/src/test/resources/ldap-data/inventory-sample-data.ldif
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala

https://issues.rudder.io/issues/18133

Fixes #18133: Group query with OR composition and searching for Node properties return less results than expected

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala

https://issues.rudder.io/issues/14934

Fixes #14934: Rudder directive API seem to take key-value order into account in json POST request 

---

rudder-lang/docs/DESIGN_DECISIONS
rudder-lang/src/ast.rs
rudder-lang/src/ast/context.rs
rudder-lang/src/ast/enums.rs
rudder-lang/src/ast/resource.rs
rudder-lang/src/ast/value.rs
rudder-lang/src/parser.rs
rudder-lang/src/parser/tests.rs

https://issues.rudder.io/issues/18105

Fixes #18105: Implement case within variable declaration

---

rudder-lang/src/ast.rs
rudder-lang/src/ast/resource.rs
rudder-lang/src/ast/variable.rs
rudder-lang/src/parser.rs
rudder-lang/src/parser/tests.rs

https://issues.rudder.io/issues/18136

Fixes #18136: Implement resource level variables

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/reports/execution/ReportsExecutionRepositoryImpl.scala

https://issues.rudder.io/issues/18151

Fixes #18151: AgentRunsTest and ReportsTest not passing on master

---

webapp/sources/rudder/rudder-core/src/main/resources/Migration/dbMigration-6.1-6.2-remove-unused-index-on-ruddersysevents.sql
webapp/sources/rudder/rudder-core/src/main/resources/reportsSchema.sql

https://issues.rudder.io/issues/18110
Replacing previous PR: https://github.com/Normation/rudder/pull/3172

Fixes #18110: Unused index on table Ruddersysevents

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleDisplayer.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleGrid.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/TechniqueEditForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/RuleManagement.scala
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/filters.js
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/directive.js
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder.js
webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/directiveManagement.html
webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/groups.html
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-directives.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-rules.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-tags.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder.css
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentDirectiveEditForm.html
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentTechniqueEditForm.html

https://issues.rudder.io/issues/18076

Fixes #18076: Use new UI template in Directives page

---

rudder-lang/src/ir/ir1.rs

https://issues.rudder.io/issues/18167

Fixes #18167: compilation issue due to misplaced doc

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/LdapQueryProcessor.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala

https://issues.rudder.io/issues/18172

Fixes #18172: Group query with OR composition and searching for Node properties return all nodes in place of none

---

relay/sources/relayd/src/data/runlog.rs
relay/sources/relayd/src/error.rs
relay/sources/relayd/src/output/database.rs

https://issues.rudder.io/issues/18189

Fixes #18189: Do not fail on missing config id

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/Technique.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NcfApi.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckNcfTechniqueUpdate.scala

https://issues.rudder.io/issues/18192

Fixes #18192: Resources are lost during an upgrade from 6.0 to 6.1

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/Technique.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NcfApi.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckNcfTechniqueUpdate.scala

https://issues.rudder.io/issues/18197

Fixes #18197: pending changes of resources (files deleted / modified / added ) are commited automatically during upgrade

---

webapp/sources/rudder/rudder-templates/src/main/scala/com/normation/templates/FillTemplatesService.scala

https://issues.rudder.io/issues/18205

Fixes #18205: Logs from all nodes are always reported in all.log

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeGroupRepository.scala

https://issues.rudder.io/issues/18207

Fixes #18207: Groups are not commited in configuration-repository on modification

---

webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/write/WriteTechniquesTest.scala

https://issues.rudder.io/issues/18209

Fixes #18209: Correct tests for branch 6.1

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/SharedFilesAPI.scala

https://issues.rudder.io/issues/18259

Fixes #18259: Resources API error for subcategories

---

rudder-lang/src/opt.rs

https://issues.rudder.io/issues/18236

Fixes #18236: cli rework: tests

---

rudder-lang/docs/usage.adoc
rudder-lang/src/opt.rs

https://issues.rudder.io/issues/18237

Fixes #18237: cli rework: doc

---

relay/sources/relayd/src/api.rs
relay/sources/relayd/src/configuration/main.rs
relay/sources/relayd/src/error.rs
relay/sources/relayd/src/lib.rs

https://issues.rudder.io/issues/18269

Fixes #18269: relayd should accept to listen on an hostname and not only an IP

---

relay/sources/relayd/src/api.rs
relay/sources/relayd/src/error.rs

https://issues.rudder.io/issues/18270

Fixes #18270: Parent change does not do what it says

---

webapp/sources/api-doc/components/schemas/settings.yml
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/NewNodeManager.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/appconfig/ConfigService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SettingsApi.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/18272

Fixes #18272: Optionally accept node with same hostname as an already accepted one 

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala

https://issues.rudder.io/issues/18266

Fixes #18266: Uncommited rudder_reporting.cf  when creating a with a condition

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/db/Doobie.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/migration/XmlEntityMigration.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/migration/XmlFileFormatMigrationEntities.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/reports/execution/LastProcessedReportRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ExpectedReportsJdbcRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/HistorizationJdbcRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ReportsJdbcRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/RudderPropertiesRepository.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/db/DBCommon.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/db/GenerateCompliance.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/migration/TestManageMigration.scala

https://issues.rudder.io/issues/18227

Fixes #18227: Fiber error when postgres is unavaible breaks generation forever

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NcfApi.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/15024

Fixes #15024: It should be forbidden to create a user technique with the same name as n existing technique

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/Properties.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/nodes/GenericPropertiesTest.scala

https://issues.rudder.io/issues/18285

Fixes #18285: Array as root json are seens as string or only first element is taken

---

relay/sources/api-doc/openapi.src.yml

https://issues.rudder.io/issues/18283

Fixes #18283: Broken url for local api in relay api doc

---

rudder-lang/src/output.rs
rudder-lang/src/technique.rs
rudder-lang/src/technique/from_ir.rs
rudder-lang/tests/techniques/simplest/technique.rl

https://issues.rudder.io/issues/18275

Fixes #18275: internally use a more secured version type for techniques version

---

relay/sources/relayd/src/data/node.rs

https://issues.rudder.io/issues/18303

Fixes #18303: Calling the relay-api to trigger a remote run on all nodes do an infinite loop on root server, killing it

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ComplianceRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ComplianceRepository.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala

https://issues.rudder.io/issues/18188

Fixes #18188: Error log about duplicates entries when saving node compliance levels

---

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py

https://issues.rudder.io/issues/18308

Fixes #18308: rudder package throws exceptions when the connection timeout

---

webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/directiveManagement.html
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css

https://issues.rudder.io/issues/18157

Fixes #18157: Make the filter section of the directives tree foldable

---

relay/sources/relayd/src/api/system.rs

https://issues.rudder.io/issues/18282

Fixes #18282: null value in status API on simple relay

---

rudder-lang/Cargo.lock
rudder-lang/Cargo.toml
rudder-lang/src/bin/rudderc.rs
rudder-lang/src/compile.rs
rudder-lang/src/error.rs
rudder-lang/src/io.rs
rudder-lang/src/lib.rs
rudder-lang/src/logger.rs
rudder-lang/src/migrate.rs
rudder-lang/src/opt.rs
rudder-lang/src/output.rs
rudder-lang/src/rudderlang_lib.rs
rudder-lang/src/technique.rs
rudder-lang/tests/utils/mod.rs

https://issues.rudder.io/issues/18256

Fixes #18256: impl new logger

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/SystemVariableSpecServiceImpl.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/SystemVariableService.scala
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-default-install/rudder.json
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-one-multipolicy/rudder.json
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-two-directives/rudder.json

https://issues.rudder.io/issues/18289

Fixes #18289: Missing system variable "POLICY_SERVER_KEY"

---

webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/rudder.json

https://issues.rudder.io/issues/18321

Fixes #18321: Broken tests after paret ticket

---

relay/sources/apache/rudder-apache-relay-ssl.conf

https://issues.rudder.io/issues/18325

Fixes #18325: 

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/SystemVariableService.scala
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-500-directives/rules/cfengine-community/rudder.json
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-two-directives/rules/cfengine-community/rudder.json
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-gen-var-def-override/rules/cfengine-community/rudder.json

https://issues.rudder.io/issues/18327

Fixes #18327: 

---

webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/techniqueEditor.html
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-technique-editor.css

https://issues.rudder.io/issues/18329

Fixes #18329: Some page sections blink while the Technique Editor is loading

---

webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/techniqueEditor.html

https://issues.rudder.io/issues/18334

Fixes #18334: In the Technique Editor, tooltips no longer appear.

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/EditPolicyServerAllowedNetwork.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PropertiesManagement.scala
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/directive.js
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder.js
webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/policyServerManagement.html
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentAgentPolicyMode.html
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentAgentSchedule.html
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentComplianceMode.html
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentNodeState.html

https://issues.rudder.io/issues/18263

Fixes #18263: Update settings UI

---

webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css

https://issues.rudder.io/issues/18265

Fixes #18265: Broken display of error icon in menu when there is a plugin error

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/domain/Technique.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/xmlparsers/TechniqueParser.scala
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/applications/packageManagement/1.0/metadata.xml
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/applications/rpmPackageInstallation/7.0/metadata.xml
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/fileDistribution/copyGitFile/2.3/metadata.xml
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/systemSettings/misc/clockConfiguration/3.0/metadata.xml
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/systemSettings/misc/genericVariableDefinition/2.0/metadata.xml
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/cfclerk/domain/TechniqueTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/RuleValServiceTest.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/TechniqueEditForm.scala

https://issues.rudder.io/issues/18340

Fixes #18340: Stop parsing os/agent from technique metadata

---

webapp/sources/api-doc/code_samples/curl/healthcheck/all.sh
webapp/sources/api-doc/components/schemas/check.yml
webapp/sources/api-doc/openapi.src.yml
webapp/sources/api-doc/paths/healthcheck/all.yml

https://issues.rudder.io/issues/18351

Fixes #18351: Add Health Check endpoint in API doc

---

webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/services/provisioning/ReportSaver.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/NewNodeManager.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/inventory/TestCertificate.scala

https://issues.rudder.io/issues/18353

Fixes #18353: Intermitent failure test on certificate inventory

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala

https://issues.rudder.io/issues/18370

Fixes #18370: TechniqueWriter doesn't write valid json for technique descriptor

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PolicyWriterService.scala

https://issues.rudder.io/issues/18377

Fixes #18377: Duplicated code from a merge #16513

---

webapp/sources/rudder/rudder-web/src/main/webapp/techeditor/js/ncf.js

https://issues.rudder.io/issues/18374

Fixes #18374: Technique editor doesn't use context path for API call

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleEditForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css

https://issues.rudder.io/issues/18164

Fixes #18164: Add a shortcut to create directive with latest technique version from the tree

---

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py
relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
relay/sources/rudder-pkg/rudder-pkg.conf

https://issues.rudder.io/issues/18326

Fixes #18326: Handle proxies in rudder package command

---

webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-notifications.css
webapp/sources/rudder/rudder-web/src/main/webapp/techeditor/js/ncf.js

https://issues.rudder.io/issues/18324

Fixes #18324: Replace old notifications by those of Rudder

---

webapp/sources/api-doc/components/schemas/node-full.yml
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestDataSerializer.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/NodeDetailLevel.scala

https://issues.rudder.io/issues/18337

Fixes #18337: Format of lastRunDate/lastInventoryDate has changed in api response in 6.0.0

---

webapp/sources/rudder/rudder-web/src/main/webapp/secure/utilities/eventLogs.html

https://issues.rudder.io/issues/18366

Fixes #18366: Beautify Event logs page

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/Archives.scala
webapp/sources/rudder/rudder-web/src/main/webapp/secure/utilities/archiveManagement.html
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css

https://issues.rudder.io/issues/18365

Fixes #18365: Beautify Archives page

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PropertiesManagement.scala
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder.js
webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/policyServerManagement.html
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentAgentPolicyMode.html
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentComplianceMode.html

https://issues.rudder.io/issues/18355

Fixes #18355: Reorganize some sections

---

webapp/sources/api-doc/components/schemas/check.yml
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/healthcheck/HealthcheckService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestDataSerializer.scala

https://issues.rudder.io/issues/18363

Fixes #18363: Add check name in healthcheck API

---

webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/1.0/technique.cf
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/technique.cf

https://issues.rudder.io/issues/18380

Fixes #18380: tests broken by parent ticket

---

webapp/sources/api-doc/components/schemas/node-full.yml

https://issues.rudder.io/issues/18383

Fixes #18383: Broken API doc build

---

webapp/sources/pom.xml
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryFileWatcher.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/metrics/HistorizeNodeCountService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitArchiverImpl.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitArchiverUtils.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/rule/category/GitRuleCategoryArchiver.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/WriteNodeCertificatesPem.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/ncf/TechniqueReader.scala
webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PropertiesManagement.scala

https://issues.rudder.io/issues/18347

Fixes #18347: Group owner of files under configuration-repository are inconsistent

---

webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/databaseManagement.html
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css

https://issues.rudder.io/issues/18388

Fixes #18388: Beautify Reports database page

---

rudder-lang/Makefile
rudder-lang/src/bin/rudderc.rs
rudder-lang/src/io.rs
rudder-lang/src/io/cli_parser.rs
rudder-lang/tools/generate_lib

https://issues.rudder.io/issues/18371

Fixes #18371: Rudder-lang doc build broken by ncf parameter

---

webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/apiManagement.html
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css

https://issues.rudder.io/issues/18389

Fixes #18389: Beautify API accounts page

---

webapp/sources/pom.xml
webapp/sources/rudder/rudder-templates/pom.xml
webapp/sources/rudder/rudder-templates/src/main/scala/com/normation/templates/FillTemplatesService.scala
webapp/sources/rudder/rudder-web/pom.xml

https://issues.rudder.io/issues/18395

Fixes #18395: Update dependencies for the webapp

---

webapp/sources/rudder/rudder-web/src/main/elm/build-app.sh
webapp/sources/rudder/rudder-web/src/main/elm/healthcheck/elm.json
webapp/sources/rudder/rudder-web/src/main/elm/healthcheck/sources/ApiCalls.elm
webapp/sources/rudder/rudder-web/src/main/elm/healthcheck/sources/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/healthcheck/sources/Init.elm
webapp/sources/rudder/rudder-web/src/main/elm/healthcheck/sources/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/healthcheck/sources/View.elm
webapp/sources/rudder/rudder-web/src/main/elm/healthcheck/sources/rudder-healthcheck.elm
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
webapp/sources/rudder/rudder-web/src/main/webapp/secure/utilities/healthcheck.html
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-healthcheck.css
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/common-layout.html

https://issues.rudder.io/issues/18314

Fixes #18314: Create Healthcheck webpage

---

webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/FusionReportUnmarshaller.scala
webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/InventoryMapper.scala
webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/ReadOnlySoftwareInventoryDAOImpl.scala
webapp/sources/pom.xml
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/AutomaticReportsCleaner.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/metrics/Scheduler.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/NodeGroupRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeGroupRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitArchiverImpl.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitParseRudderObjects.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/ItemArchiveManagerImpl.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DependencyAndDeletionService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PrepareTemplateVariables.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/LdapQueryProcessor.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/inventory/TestCertificate.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/metrics/NodeCountHistorizationTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/metrics/SchedulerTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestJsEngine.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NcfApi.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/plugins/RudderPluginJson.scala
webapp/sources/utils/src/main/scala/com/normation/ZioCommons.scala
webapp/sources/utils/src/test/scala/com/normation/ZioCommonsTest.scala

https://issues.rudder.io/issues/18405

Fixes #18405: Upgrade to ZIO 1.0.1 - branch 6.2

---

webapp/sources/pom.xml

https://issues.rudder.io/issues/18411

Fixes #18411: Upgrade ZIO to 1.0.3

---

relay/sources/relayd/src/api/shared_files.rs
relay/sources/relayd/src/configuration/logging.rs
relay/sources/relayd/src/configuration/main.rs
relay/sources/relayd/src/data/node.rs
relay/sources/relayd/src/data/runlog.rs
relay/sources/relayd/src/data/shared_file.rs
relay/sources/relayd/src/error.rs
relay/sources/relayd/src/hashing.rs
relay/sources/relayd/src/output/database.rs
relay/sources/relayd/src/processing/inventory.rs
relay/sources/relayd/src/processing/reporting.rs
relay/sources/relayd/tests/api_system_info.rs
relay/sources/relayd/tests/api_system_reload.rs
relay/sources/relayd/tests/api_system_status.rs
relay/sources/relayd/tests/common.rs
relay/sources/relayd/tests/processing_reporting.rs
relay/sources/relayd/tests/processing_reporting_old.rs
relay/sources/relayd/tests/remote_run.rs
relay/sources/relayd/tests/shared_files.rs
relay/sources/relayd/tests/shared_folder.rs
relay/sources/relayd/tools/create-database.sql

https://issues.rudder.io/issues/18412

Fixes #18412: Update relayd after reporting changes in webapp

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/healthcheck/HealthcheckNotificationService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/healthcheck/HealthcheckService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/HealthcheckApi.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/HealthcheckInfo.scala

https://issues.rudder.io/issues/18328

Fixes #18328: Healthcheck notification in navigation bar

---

webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-inventory-received-accepted/hook-template
webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-inventory-received-accepted/readme.adoc
webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-inventory-received-failed/hook-template
webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-inventory-received-failed/readme.adoc
webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-inventory-received-pending/hook-template
webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-inventory-received-pending/readme.adoc
webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-post-acceptance/readme.adoc
webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-post-deletion/10-clean-policies
webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-post-deletion/hook-template
webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-post-deletion/readme.adoc
webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-pre-deletion/hook-template
webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-pre-deletion/readme.adoc
webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-node-finished/hook-template
webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-node-finished/readme.adoc
webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-node-ready/10-cf-promise-check
webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-node-ready/42-ignore_disabled_non_exec
webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-node-ready/42-ignore_extension.disabled
webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-node-ready/90-change-perm
webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-node-ready/hook-template
webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-node-ready/readme.adoc
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryFileWatcher.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/PostCommits.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/inventory/TestCertificate.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/18379

Fixes #18379: Create hooks for when a node inventory is received

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/18413

Fixes #18413: Missing RudderConfig parameter pour healthcheck period 

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/17666

Fixes #17666: Node status API must not return an error when the node is not here

---

webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/parameterManagement.html
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css

https://issues.rudder.io/issues/18418

Fixes #18418: Beautify Global Parameters page

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/healthcheck/HealthcheckService.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/18414

Fixes #18414: Add check for File Descriptor limit 

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/healthcheck/HealthcheckService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala

https://issues.rudder.io/issues/18443

Fixes #18443: Fix compilation issues after merge

---

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py
relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
relay/sources/rudder-pkg/rudder-pkg

https://issues.rudder.io/issues/18453

Fixes #18453: rudder package config may not have the new parameters and may fail when reading them

---

webapp/sources/api-doc/paths/nodes/apply-policy.yml

https://issues.rudder.io/issues/18457

Fixes #18457: Typo in API doc

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-directives.css
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentDirectiveEditForm.html

https://issues.rudder.io/issues/18401

Fixes #18401: Empty space in Directives header

---

webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-healthcheck.css

https://issues.rudder.io/issues/18460

Fixes #18460: Warning on plugin icon is huge on left menu

---

webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css

https://issues.rudder.io/issues/18463

Fixes #18463: Header of some page hides menu from the left side

---

webapp/sources/rudder/rudder-web/src/main/elm/build-app.sh

https://issues.rudder.io/issues/18461

Fixes #18461: Health check page is not displayed

---

webapp/sources/rudder/rudder-core/src/main/resources/Migration/dbMigration-6.1-7.0-compliance_computation_change.sql
webapp/sources/rudder/rudder-core/src/main/resources/reportsSchema.sql
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/FetchNodeExecutions.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/db/DB.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/DebugComplianceLogger.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/StatusReports.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/reports/execution/LastProcessedReportRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/reports/execution/ReportExecution.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/reports/execution/ReportsExecutionRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/reports/execution/ReportsExecutionRepositoryImpl.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/reports/execution/ReportsExecutionService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ReportsJdbcRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportExecutionTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/LoadNodeComplianceCache.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala

https://issues.rudder.io/issues/18255

Arch 18255/don t compute runs information but use data from rudder relayd

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/ComplianceLevel.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js

https://issues.rudder.io/issues/18473

Fixes #18473: Reduce data send to nodes list and make a faster display

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js

https://issues.rudder.io/issues/18476

Fixes #18476: Store columns used in localstorage in nodes list

---

webapp/sources/api-doc/openapi.src.yml
webapp/sources/api-doc/paths/healthcheck/all.yml
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/healthcheck/HealthcheckService.scala
webapp/sources/rudder/rudder-web/src/main/elm/healthcheck/sources/View.elm
webapp/sources/rudder/rudder-web/src/main/webapp/secure/utilities/healthcheck.html

https://issues.rudder.io/issues/18477

Fixes #18477: Improve health check texts

---

rudder-lang/src/io/output/backtrace.rs
rudder-lang/src/parser.rs
rudder-lang/src/parser/error.rs

https://issues.rudder.io/issues/18478

Fixes #18478: add backtrace to parser

---

webapp/sources/api-doc/openapi.src.yml

https://issues.rudder.io/issues/18481

Fixes #18481: 6.2 API version is 13

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/healthcheck/HealthcheckService.scala

https://issues.rudder.io/issues/18480

Fixes #18480: Check parition should check the lowest space available first

---

webapp/sources/api-doc/code_samples/curl/nodes/status.sh
webapp/sources/api-doc/paths/nodes/status.yml
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala

https://issues.rudder.io/issues/18483

Fixes #18483: Documentation for /nodes/status page

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/16739

Fixes #16739: Error when refusing a node

---

relay/sources/relayd/src/data/report.rs

https://issues.rudder.io/issues/18497

Fixes #18497: Broken report parser on some info messages

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/ItemArchiveManagerImpl.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/inventory/TestCertificate.scala

https://issues.rudder.io/issues/17720

Fixes #17720: If a second rollback starts when a first is processing, system group/technique may be lost

---

webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/common-layout.html

https://issues.rudder.io/issues/18479

Fixes #18479: Notification healthcheck is not displayed on warning

---

webapp/sources/api-doc/openapi.src.yml

https://issues.rudder.io/issues/18513

Fixes #18513: Missing main entry for API doc /nodes/status

---

webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentComplianceMode.html

https://issues.rudder.io/issues/18501

Fixes #18501: spacing is uneven in the settings page

---

webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js

https://issues.rudder.io/issues/18516

Fixes #18516: Reloading a page with a node table or refreshing breaks hostname links and compliance

---

webapp/sources/api-doc/components/parameters/node-ids.yml
webapp/sources/api-doc/paths/nodes/status.yml

https://issues.rudder.io/issues/18515

Fixes #18515: Parent breaks build

---

webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/manageNewNode.html

https://issues.rudder.io/issues/18491

Fixes #18491: Error about missing image in 6.2

---

webapp/sources/rudder/rudder-web/src/main/webapp/secure/utilities/healthcheck.html
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-healthcheck.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/common-layout.html

https://issues.rudder.io/issues/18474

Fixes #18474: Width of the Directive tree changes according to the selected Directive.

---

webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css

https://issues.rudder.io/issues/18503

Fixes #18503: spacing is uneven in reports database page

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/SrvGrid.scala
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js

https://issues.rudder.io/issues/18498

Fixes #18498: after editing columns in the group or serach node page, there's a JS error when doing a search

---

webapp/sources/utils/src/main/scala/com/normation/ZioCommons.scala

https://issues.rudder.io/issues/18528

Fixes #18528: ifTrace/Debug/etcIsEnabled on pure logger does nothings

---

webapp/sources/scala-ldap/src/main/scala/com/normation/ldap/sdk/LDAPConnection.scala

https://issues.rudder.io/issues/18529

Fixes #18529: If LDAP server does not support subtree deletion, we get error when entry does not exists

---

webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala

https://issues.rudder.io/issues/18535

Fixes #18535: test broken because of parent ticket

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/hooks/RunHooks.scala
webapp/sources/rudder/rudder-core/src/test/resources/hooks.d/test/timeout.sh
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/hooks/HooksTest.scala

https://issues.rudder.io/issues/18530

Fixes #18530: We don't know which hook timeout when it happens

---

rudder-lang/src/error.rs
rudder-lang/src/io/output.rs
rudder-lang/src/io/output/backtrace.rs
rudder-lang/src/parser.rs
rudder-lang/src/parser/error.rs

https://issues.rudder.io/issues/18484

Fixes #18484: update backtrace with better performance in parser

---

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py

https://issues.rudder.io/issues/18521

Fixes #18521: Upgrading Rudder 6.2 on centos 7 fails

---

webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-directives.css

https://issues.rudder.io/issues/14841

Fixes #14841: Densify the Directives interface

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala

https://issues.rudder.io/issues/11714

Fixes #11714: Display message if there are no parameters in Directive details 

---

webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-groups.css

https://issues.rudder.io/issues/18533

Fixes #18533: In Groups page, the search filter should take up the full width available

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ComplianceData.scala

https://issues.rudder.io/issues/18543

Fixes #18543: Date displayed in Recent Change table in Rules doesn't contain the proper timezoning

---

webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js

https://issues.rudder.io/issues/18542

Fixes #18542: In added node attribute column, property value is never updated

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js

https://issues.rudder.io/issues/7687

Fixes #7687: Group display: change last seen field to last inventory field

---

webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css

https://issues.rudder.io/issues/18574

Fixes #18574: Light in healthcheck notif are not displayed

---

webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/reports/StatusReportTest.scala

https://issues.rudder.io/issues/18563

Fixes #18563: Skip performance test

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/model/DirectiveEditor.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/Section2FieldService.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala

https://issues.rudder.io/issues/18576

Fixes #18576: Cannot create a directive based on a rudder techniques

---

webapp/sources/api-doc/code_samples/curl/settings/get-allowed-networks.sh
webapp/sources/api-doc/code_samples/curl/settings/set-allowed-networks-diff.sh
webapp/sources/api-doc/code_samples/curl/settings/set-allowed-networks.sh
webapp/sources/api-doc/components/parameters/setting-allowed-networks.yml
webapp/sources/api-doc/openapi.src.yml
webapp/sources/api-doc/paths/settings/allowed_networks.yml
webapp/sources/api-doc/paths/settings/allowed_networks_diff.yml
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/AbstractScheduler.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/PolicyServerManagementService.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SettingsApi.scala

https://issues.rudder.io/issues/18508

Fixes #18508: Missing a PATCH API for allowed networks

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/Properties.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala

https://issues.rudder.io/issues/18580

Fixes #18580: String node properties display quotes

---

webapp/sources/rudder/rudder-web/src/main/resources/load-page/rudder-loading.html
webapp/sources/rudder/rudder-web/src/main/resources/load-page/rudder-not-loaded.html

https://issues.rudder.io/issues/18571

Fixes #18571: missing (404) favicon in rudder loading page

---

webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js

https://issues.rudder.io/issues/18591

Fixes #18591: Rename "Server" node list column to "Policy server"

---

webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css

https://issues.rudder.io/issues/18594

Fixes #18594: Column label moves slightly when hovering remove button

---

webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-healthcheck.css

https://issues.rudder.io/issues/18582

Fixes #18582: Missing lights indicators in healthcheck page

---

webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js

https://issues.rudder.io/issues/18597

Fixes #18597: Removing all node list columns remove the whole table

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/manageNewNode.html

https://issues.rudder.io/issues/18590

Fixes #18590: Rename node menu entries for consistency

---

webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js

https://issues.rudder.io/issues/18603

Fixes #18603: Rename Id to "Node ID" in columns name for consistency

---

webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentDirectiveEditForm.html

https://issues.rudder.io/issues/18604

Fixes #18604: Make capitalization in directove form tabs consistent

---

webapp/sources/rudder/rudder-web/src/main/webapp/style/login.css

https://issues.rudder.io/issues/18606

Fixes #18606: Do not use italics on login page

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/healthcheck/HealthcheckService.scala

https://issues.rudder.io/issues/18605

Fixes #18605: Improve display of partition free space

---

webapp/sources/api-doc/paths/settings/allowed_networks.yml
webapp/sources/api-doc/paths/settings/allowed_networks_diff.yml

https://issues.rudder.io/issues/18608

Fixes #18608: Bad file name in api-doc: set-allowed-networks.yml

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala
webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/techniqueEditor.html
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-technique-editor.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css

https://issues.rudder.io/issues/18588

Fixes #18588: Small UI features are missing from the new 6.2 interface

---

webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js

https://issues.rudder.io/issues/18617

Fixes #18617: Change default columns of nodes tables

---

webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/Popup/accept_new_server.html
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/Popup/expected_policy_popup.html
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/Popup/refuse_new_server.html
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/pending_history_grid.html
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/server_grid.html
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/srv_grid.html

https://issues.rudder.io/issues/18609

Fixes #18609: Column names in pending and accepted nodes are different

---

webapp/sources/api-doc/paths/settings/allowed_networks.yml
webapp/sources/api-doc/paths/settings/allowed_networks_diff.yml

https://issues.rudder.io/issues/18620

Fixes #18620: Bad file name in api-doc: set-allowed-networks.yml

---

webapp/sources/api-doc/components/parameters/node-delete-mode.yml
webapp/sources/api-doc/paths/nodes/id.yml
webapp/sources/api-doc/paths/settings/allowed_networks_diff.yml

https://issues.rudder.io/issues/18622

Fixes #18622: Bad file name in api-doc: some more errors

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeGroupRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPParameterRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPRuleRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/Lock.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/18584

Fixes #18584: semaphore gurading LDAP repos are created each time

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/Properties.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestDataSerializer.scala

https://issues.rudder.io/issues/18578

Fixes #18578: Inherited mode is not returned in API

---

webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/nodes/TestMergeGroupProperties.scala

https://issues.rudder.io/issues/18629

Fixes #18629: Inherited mode is not returned in API 

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/Properties.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/MergeNodeProperties.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/18595

Fixes #18595: Added column for node property does not show inherited value

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckNcfTechniqueUpdate.scala

https://issues.rudder.io/issues/18635

Fixes #18635: Force reload of generic-method cache when app starts

---

rudder-lang/Makefile
rudder-lang/docs/contributing.adoc
rudder-lang/docs/usage.adoc
rudder-lang/src/generator/cfengine/syntax.rs
rudder-lang/tools/generate_lib

https://issues.rudder.io/issues/18581

Fixes #18581: fix ci tests

---

rudder-lang/Cargo.lock
rudder-lang/src/generator/cfengine.rs
rudder-lang/src/generator/cfengine/syntax.rs
rudder-lang/src/generator/dsc.rs
rudder-lang/src/io/output.rs
rudder-lang/src/ir/ir1.rs
rudder-lang/src/ir/resource.rs
rudder-lang/src/ir/value.rs
rudder-lang/src/ir/variable.rs
rudder-lang/src/parser.rs
rudder-lang/src/rudderlang_lib.rs
rudder-lang/src/technique.rs
rudder-lang/tests/techniques/cis/technique.cf
rudder-lang/tests/techniques/cis/technique.json
rudder-lang/tests/techniques/cis/technique.ps1

https://issues.rudder.io/issues/18450

Fixes #18450: impl exception for condition resource conditions

---

rudder-lang/Makefile

https://issues.rudder.io/issues/18649

Fixes #18649: fix makefile

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/NodeGroupForm.html

https://issues.rudder.io/issues/18656

Fixes #18656: Make group tab name capitalization consistent

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala

https://issues.rudder.io/issues/18654

Fixes #18654: API message when a node details is not found is extremelly misleading

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala

https://issues.rudder.io/issues/18601

Fixes #18601: Disable directive button has incorrect capitalization

---

webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js

https://issues.rudder.io/issues/18618

Fixes #18618: Pretty-print json properties in nodes list

---

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py
relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
relay/sources/rudder-pkg/rudder-pkg

https://issues.rudder.io/issues/18555

Fixes #18555: Remove useless output from rudder package

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js

https://issues.rudder.io/issues/18641

Fixes #18641: Add a property column without inherited values in node list

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/HealthcheckInfo.scala

https://issues.rudder.io/issues/18661

Fixes #18661: Typo in healthcheck notification title

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/HealthcheckInfo.scala

https://issues.rudder.io/issues/18662

Fixes #18662: Add line break for partition's list in healthcheck notification

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/18499

Fixes #18499: category.xml is created in place of activeTechniqueSettings.xml in all config-repos/directives

---

webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js

https://issues.rudder.io/issues/18668

Fixes #18668: [object Object] in inherited properties column 

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/api/DataStructures.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/api/TestApiData.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderUserDetails.scala

https://issues.rudder.io/issues/18664

Fixes #18664: API ACL order is lost for users

---

webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-inventory-received-pending/auto-accept-nodes.example

https://issues.rudder.io/issues/18676

Fixes #18676: Typo in example script for auto-accept: POSTT

---

webapp/sources/rudder/rudder-web/src/main/webapp/secure/plugins/pluginInformation.html

https://issues.rudder.io/issues/18658

Fixes #18658: Link to plugins in Rudder interface should point directly to plugins list

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala
webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/techniqueEditor.html

https://issues.rudder.io/issues/18627

Fixes #18627: In read_only mode, many things are editable

---

webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/manageNewNode.html

https://issues.rudder.io/issues/18680

Fixes #18680: If there is a lot of pending nodes, accept button is not displayed

---

webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-technique-editor.css

https://issues.rudder.io/issues/18612

Fixes #18612: Clicking on "show docs" on a generic method scroll down too much

---

webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-node.css
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/server/server_details.html

https://issues.rudder.io/issues/18687

Fixes #18687: it's impossible to see all technical logs in 6.2

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala

https://issues.rudder.io/issues/18682

Fixes #18682: Error code should be 404 and not 500 when a node is not found for details API

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js

https://issues.rudder.io/issues/18681

Fixes #18681: Inherited properties always displayed in the column, even if checkbox unchecked

---

webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/techniqueEditor.html
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-technique-editor.css
webapp/sources/rudder/rudder-web/src/main/webapp/techeditor/js/ncf.js

https://issues.rudder.io/issues/18693

Fixes #18693: Filter for name for generic methods in technique editor doesn't filter

---

webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css

https://issues.rudder.io/issues/18700

Fixes #18700: Create directive button is misplaced

---

webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-directives.css

https://issues.rudder.io/issues/18714

Fixes #18714: When there is an error after saving a directive, impossible to scroll down directive details

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/ShowNodeDetailsFromNode.scala
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentAgentSchedule.html

https://issues.rudder.io/issues/18330

Fixes #18330: Agent run frequency must not be configurable on policy servers

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala

https://issues.rudder.io/issues/18723

Fixes #18723: Tooltip in node summary goes under sidebar

---

webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/manageNewNode.html
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css

https://issues.rudder.io/issues/18691

Fixes #18691: parent ticket doesn't grey out title on accept new nodes when the popup shows up

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/SrvGrid.scala

https://issues.rudder.io/issues/18729

Fixes #18729: Compilation warning (unused variable) in 6.2.0-rc1

---

relay/sources/rudder-pkg/lib/rudder-pkg/plugin.py
relay/sources/rudder-pkg/lib/rudder-pkg/rpkg.py
relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py
relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
relay/sources/rudder-pkg/rudder-pkg

https://issues.rudder.io/issues/18735

Fixes #18735: No newer release compatible versions found for the plugin rudder-plugin-scale-out-relay, disabling it

---

rudder-lang/src/technique.rs

https://issues.rudder.io/issues/18696

Fixes #18696: generation should work whatever order gm parameters are received

---

relay/sources/relayd/Cargo.lock

https://issues.rudder.io/issues/18766

Fixes #18766: Security vulnerability in arc-swap

---

webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-tags.css

https://issues.rudder.io/issues/18733

Fixes #18733: when directive name is long and there are several tags (like with CIS plugin), display is a bit broken

---

rudder-lang/Makefile

https://issues.rudder.io/issues/18798

Fixes #18798: fix doc generation

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-groups.css
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/NodeGroupForm.html

https://issues.rudder.io/issues/18738

Fixes #18738: Message on save for group must appear only when button is disabled

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/ShowNodeDetailsFromNode.scala
webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/node.html

https://issues.rudder.io/issues/18768

Fixes #18768: Node name not visible in node configuration screen

---

webapp/sources/rudder/rudder-rest/src/test/resources/api/api_rules.yml
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/SystemApiTest.scala

https://issues.rudder.io/issues/18804

Fixes #18804: Test broken since merging parent ticket on API testing

---

webapp/sources/api-doc/components/schemas/rule.yml

https://issues.rudder.io/issues/18805

Fixes #18805: Bad doc on API for rules/target

---

webapp/sources/rudder/rudder-web/src/main/webapp/techeditor/js/ncf.js

https://issues.rudder.io/issues/18420

Fixes #18420: saving imported techniques with unknown GM fails with no error prompt

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateOrUpdateGlobalParameterPopup.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/model/RudderBaseField.scala

https://issues.rudder.io/issues/18556

Fixes #18556: Global parameters format is not preserved when editing

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/NewNodeManager.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
webapp/sources/rudder/rudder-web/src/main/resources/logback.xml

https://issues.rudder.io/issues/18677

Fixes #18677: Accepting a node by API or UI doesn't do the same things exactly

---

webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/directiveManagement.html
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-directives.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder.css
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentDirectiveEditForm.html

https://issues.rudder.io/issues/18750

Fixes #18750: Markdown documentation rendering is inconsistent

---

webapp/sources/rudder/rudder-web/src/main/elm/healthcheck/sources/View.elm

https://issues.rudder.io/issues/18815

Fixes #18815: Make check warning message less like "TODO"

---

webapp/sources/api-doc/components/schemas/rule-target.yml
webapp/sources/api-doc/components/schemas/rule-targets.yml

https://issues.rudder.io/issues/18823

Fixes #18823: Broken API doc build

---

webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala

https://issues.rudder.io/issues/18825

Fixes #18825: webapp build broken in 7.0

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ComplianceRepository.scala

https://issues.rudder.io/issues/18814

Fixes #18814:  Error log about duplicates entries when saving node compliance levels

---

webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/DataTypes.scala

https://issues.rudder.io/issues/18813

Fixes #18813: bad logger name for inventory processing

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/reports/execution/ReportsExecutionService.scala

https://issues.rudder.io/issues/18835

Fixes #18835: Make more clear error message when several rudder.war are present

---

webapp/sources/api-doc/code_samples/curl/system/purge-software.sh
webapp/sources/api-doc/openapi.src.yml
webapp/sources/api-doc/paths/system/purge-software.yml

https://issues.rudder.io/issues/18830

Fixes #18830: Missing doc for purgeSoftware API endpoint

---

webapp/sources/api-doc/code_samples/curl/system/purge-software.sh

https://issues.rudder.io/issues/18840

Fixes #18840: Bad URL for doc of purgeSoftware API

---

relay/sources/relayd/Cargo.lock
relay/sources/relayd/Cargo.toml
relay/sources/relayd/deny.toml
relay/sources/relayd/src/api/remote_run.rs
relay/sources/relayd/src/api/shared_files.rs
relay/sources/relayd/src/configuration/main.rs
relay/sources/relayd/src/data/node.rs
relay/sources/relayd/src/error.rs
relay/sources/relayd/src/input/watch.rs
relay/sources/relayd/src/lib.rs
relay/sources/relayd/src/processing/inventory.rs
relay/sources/relayd/src/processing/reporting.rs
relay/sources/relayd/tests/files/config/main.conf
relay/sources/relayd/tests/processing_reporting_old.rs
relay/sources/relayd/tools/config/main.conf
rudder-lang/deny.toml

https://issues.rudder.io/issues/18818

Fixes #18818: Update relayd to tokio 1.0

---

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py

https://issues.rudder.io/issues/18843

Fixes #18843: rudder plugin upgrade-all  states that he will disable plugin, but is does not

---

webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentDirectiveEditForm.html

https://issues.rudder.io/issues/18838

Fixes #18838: Cannot open directive details on Safari 

---

rudder-lang/libs/oslib.rl

https://issues.rudder.io/issues/18799

Fixes #18799: addd sled to rudderlang supported os list

---

rudder-lang/src/command/technique_generate.rs
rudder-lang/src/generator/cfengine.rs
rudder-lang/src/generator/cfengine/syntax.rs
rudder-lang/src/generator/dsc.rs
rudder-lang/src/generator/dsc/syntax.rs
rudder-lang/src/io.rs
rudder-lang/src/parser/token.rs
rudder-lang/src/rudderlang_lib.rs
rudder-lang/src/technique.rs
rudder-lang/src/technique/from_ir.rs
rudder-lang/tests/techniques/stateless/technique.cf
rudder-lang/tests/techniques/stateless/technique.json
rudder-lang/tests/techniques/stateless/technique.ps1
rudder-lang/tools/generate_lib

https://issues.rudder.io/issues/18670

Fixes #18670: handle resources that do not have particular state

---

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py

https://issues.rudder.io/issues/18865

Fixes #18865: parent ticket merge override more recent changes in 6.2 branch

---

rudder-lang/src/parser/token.rs
rudder-lang/src/technique/from_ir.rs
rudder-lang/tools/generate_lib

https://issues.rudder.io/issues/18746

Fixes #18746: library checker should not be hardcoded

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDiffMapper.scala

https://issues.rudder.io/issues/18856

Fixes #18856: Event logs are not written when fields are set to empty (ie short description)

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestDataSerializer.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/RestData.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/RuleApi.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_rules.yml
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TestRestFromFileDef.scala

https://issues.rudder.io/issues/18867

Fixes #18867: id parameter is ignored in rule category creation API and tags are lost on update

---

webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/services/core/SoftwareDAO.scala
webapp/sources/ldap-inventory/inventory-provisioning-core/src/main/scala/com/normation/inventory/ldap/provisioning/DefaultReportSaver.scala
webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/ReadOnlySoftwareInventoryDAOImpl.scala
webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/SoftwareService.scala
webapp/sources/ldap-inventory/inventory-repository/src/test/scala/com/normation/inventory/ldap/core/TestInventory.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/PurgeUnreferencedSoftwares.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryFileWatcher.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/NewNodeManager.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SystemApi.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/18839

Fixes #18839: Backport new inventory priorisation, software deletion API and log correction in 6.1

---

webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css

https://issues.rudder.io/issues/18869

Fixes #18869: Topbar menu is broken on Safari

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/RuleApi.scala

https://issues.rudder.io/issues/18876

Fixes #18876: Workflow rights are not used for rules

---

webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-datatable.css

https://issues.rudder.io/issues/18881

Fixes #18881: Display of DataTables' pagination buttons  is broken.

---

webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala

https://issues.rudder.io/issues/18882

Fixes #18882: Build broken by automatic upmerge of parent ticket

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestComputeSchedule.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ReportingServiceUtilsTest.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ComplianceData.scala
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder.js

https://issues.rudder.io/issues/18877

Fixes #18877: "Skipped" Directives on Rules Screen

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala

https://issues.rudder.io/issues/18883

Fixes #18883: Line break after each ip address

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/18899

Fixes #18899: Error in postCommit pipeline with processor 'post_commit_inventory:pending_node_for_deleted_server'

---

webapp/sources/api-doc/components/schemas/settings.yml
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/AsyncDeploymentActor.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/ClearCacheService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/appconfig/ConfigService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SettingsApi.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/18845

Fixes #18845: Add a settings to delay start of policy generation

---

webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/ReadOnlySoftwareInventoryDAOImpl.scala
webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/SoftwareService.scala
webapp/sources/ldap-inventory/inventory-repository/src/test/scala/com/normation/inventory/ldap/core/TestInventory.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/PurgeUnreferencedSoftwares.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SystemApi.scala

https://issues.rudder.io/issues/18873

Fixes #18873: purge software batch sometime terminate in error without log message

---

webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/policyServerManagement.html

https://issues.rudder.io/issues/18849

Fixes #18849: Save button moves when switching of compliance reporting mode

---

webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportsTest.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestStatusTest.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TestRestFromFileDef.scala

https://issues.rudder.io/issues/18910

Fixes #18910: Simpifying agent run request breaks test

---

rudder-lang/tools/generate_lib

https://issues.rudder.io/issues/18866

Fixes #18866: lib generation does not handle gm parameters order properly

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/AsyncDeploymentActor.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/18922

Fixes #18922: Merge error in parent ticket leads to stackoverflow at boot

---

webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/nodeProperties.js
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentNodeProperties.html

https://issues.rudder.io/issues/18902
Replacing previous PR: https://github.com/Normation/rudder/pull/3505

Fixes #18902: Error message when editing properties in the interface

---

webapp/sources/api-doc/introduction.md

https://issues.rudder.io/issues/18923

Fixes #18923: Missing API addition for version 13 in doc

---

webapp/sources/api-doc/paths/settings/allowed_networks_diff.yml
webapp/sources/api-doc/paths/system/purge-software.yml

https://issues.rudder.io/issues/18930

Fixes #18930: Documentation API doesn't build anymore

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ReportingServiceUtilsTest.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleCompliance.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ComplianceData.scala

https://issues.rudder.io/issues/18931

Fixes #18931: No skipped directives on Rule screen after parent ticket

---

webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css

https://issues.rudder.io/issues/18935

Fixes #18935: Double scrollbar in settings page when branding plugin is enabled

---

webapp/sources/api-doc/code_samples/curl/nodes/pending-all.sh
webapp/sources/api-doc/openapi.src.yml
webapp/sources/api-doc/paths/nodes/pending-all.yml

https://issues.rudder.io/issues/18940

Fixes #18940: rudder api doc doesn't list nodes/pending

---

webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/FullInventoryRepositoryImpl.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala

https://issues.rudder.io/issues/18954

Fixes #18954: Compilation error after 18926 upmerge

---

webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala

https://issues.rudder.io/issues/18957

Fixes #18957: Compilation error after 18926 merge

---

rudder-lang/src/generator/cfengine.rs
rudder-lang/src/generator/dsc.rs
rudder-lang/src/ir/enums.rs
rudder-lang/src/technique/from_ir.rs

https://issues.rudder.io/issues/18827

Fixes #18827: handle external variables in conditions

---

webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/searchNodes.html

https://issues.rudder.io/issues/18791

Fixes #18791: "By agent version" pie chart leads to empty page

---

rudder-lang/src/ir/value.rs
rudder-lang/src/technique.rs
rudder-lang/src/technique/from_ir.rs
rudder-lang/tests/techniques/cis/technique.json
rudder-lang/tests/techniques/cis/technique.ps1

https://issues.rudder.io/issues/18895

Fixes #18895: condition_from fix

---

relay/sources/relayd/Makefile
rudder-lang/Makefile
rudder-lang/tools/generate_lib
rust.makefile

https://issues.rudder.io/issues/18990

Fixes #18990: Rudder-lang doc misses a mkdir

---

rudder-lang/Makefile
rudder-lang/docs/assets/css/rudder.css

https://issues.rudder.io/issues/18991

Fixes #18991: Rudderify doc rudder-lang doc theme

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DataStructures.scala

https://issues.rudder.io/issues/18995

Fixes #18995: Missing mandatory directive parameter doesn't fail policy generation

---

rudder-lang/tests/techniques/condition_alias/technique.cf
rudder-lang/tests/techniques/condition_alias/technique.json
rudder-lang/tests/techniques/condition_alias/technique.ps1
rudder-lang/tools/generated_formats_tester

https://issues.rudder.io/issues/18816

Fixes #18816: accept enum aliases when checking CF diff

---

webapp/sources/ldap-inventory/inventory-provisioning-web/src/main/scala/com/normation/inventory/provisioning/endpoint/config/AppConfig.scala

https://issues.rudder.io/issues/19004

Fixes #19004: FileUploadBaseSizeLimitExceededException with an 10MB inventory

---

webapp/sources/ldap-inventory/pom.xml
webapp/sources/pom.xml
webapp/sources/rudder/pom.xml
webapp/sources/scala-ldap/pom.xml
webapp/sources/utils/pom.xml

https://issues.rudder.io/issues/18978

Fixes #18978: Missing licence info in pom.xml

---

agent/sources/client/Makefile

https://issues.rudder.io/issues/19007

Fixes #19007: Build client everywhere

---

webapp/sources/api-doc/code_samples/curl/nodes/node-inherited-properties.sh
webapp/sources/api-doc/components/parameters/include.yml
webapp/sources/api-doc/components/schemas/node-inherited-properties.yml
webapp/sources/api-doc/openapi.src.yml
webapp/sources/api-doc/paths/nodes/inherited-properties.yml
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala

https://issues.rudder.io/issues/18959

Fixes #18959: Inherited node properties are not returned in API

---

webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-post-acceptance/hook-template
webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-post-deletion/hook-template
webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-pre-deletion/hook-template
webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-failed/hook-template
webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-finished/hook-template
webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-node-finished/hook-template
webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-node-ready/hook-template
webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-started/hook-template
webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/readme.adoc
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/GitTechniqueReader.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/Properties.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/hooks/RunHooks.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PolicyWriterService.scala
webapp/sources/rudder/rudder-core/src/test/resources/hooks.d/test/timeout_ok.sh
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/hooks/HooksTest.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala

https://issues.rudder.io/issues/18915

Fixes #18915: We don't know when generation hooks takes more time than expected, massively impacting generation time

---

agent/sources/client/Makefile

https://issues.rudder.io/issues/19026

Fixes #19026: solaris fail to build

---

agent/sources/client/argtable-aix.patch
agent/sources/client/src/argtable3.c
rudder-lang/tools/generate_lib

https://issues.rudder.io/issues/19028

Fixes #19028: AIX fails to build -  bis

---

webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-post-acceptance/hook-template
webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-post-deletion/hook-template
webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-pre-deletion/hook-template
webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-failed/hook-template
webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-finished/hook-template
webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-node-finished/hook-template
webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-node-ready/hook-template
webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-started/hook-template

https://issues.rudder.io/issues/19032

Fixes #19032: Hook timeout info must specify to add command near the top in the template

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/SharedFilesAPI.scala

https://issues.rudder.io/issues/18200

Fixes #18200: Cannot load file browser when shared-folder contains dead symlinks

---

webapp/sources/rudder/rudder-web/src/main/webapp/techeditor/js/ncf.js

https://issues.rudder.io/issues/19049

Fixes #19049: Error technique in editor

---

rudder-lang/.gitignore
rudder-lang/src/parser.rs
rudder-lang/src/parser/baseparsers.rs
rudder-lang/src/parser/error.rs
rudder-lang/src/parser/tests.rs

https://issues.rudder.io/issues/18669

Fixes #18669: Properly locate entity errors if the source has metadatas attached

---

rudder-lang/tests/techniques/duplicated/technique.cf
rudder-lang/tests/techniques/duplicated/technique.json
rudder-lang/tests/techniques/duplicated/technique.ps1

https://issues.rudder.io/issues/18790

Fixes #18790: multiple calls to the same method join all parameters

---

rudder-lang/src/command/technique_read.rs
rudder-lang/src/error.rs
rudder-lang/src/generator/cfengine.rs
rudder-lang/src/generator/dsc.rs
rudder-lang/src/generator/json.rs
rudder-lang/src/io/output.rs
rudder-lang/src/ir/ir2.rs
rudder-lang/src/ir/resource.rs
rudder-lang/src/technique/from_ir.rs

https://issues.rudder.io/issues/19043

Fixes #19043: ensure state definitions include specific metadatas

---

webapp/sources/api-doc/code_samples/curl/nodes/id-update.sh
webapp/sources/api-doc/components/schemas/agent-key.yml

https://issues.rudder.io/issues/19065

Fixes #19065: Missing example for server key reset

---

rudder-lang/src/command/compile.rs
rudder-lang/src/generator/cfengine.rs
rudder-lang/src/generator/dsc.rs
rudder-lang/src/io.rs
rudder-lang/src/ir/ir1.rs
rudder-lang/src/ir/resource.rs
rudder-lang/src/parser.rs
rudder-lang/src/parser/tests.rs
rudder-lang/src/rudderlang_lib.rs
rudder-lang/src/technique/from_ir.rs
rudder-lang/tools/generate_lib
rudder-lang/tools/rudderc-dev.conf

https://issues.rudder.io/issues/19048

Fixes #19048: replace library metadata by is_dependency based on cli parameters

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryProcessor.scala

https://issues.rudder.io/issues/19072

Fixes #19072: Inventory named as "Report" in log message

---

webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/searchNodes.html

https://issues.rudder.io/issues/19082

Fixes #19082: Search nodes component is not reloaded when reloading page, losing our current request

---

rust.makefile

https://issues.rudder.io/issues/19083

Fixes #19083: Split cargo-deny from qa-test

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/UpdateDynamicGroups.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/DirectiveRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DependencyAndDeletionService.scala
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/systemSettings/misc/genericVariableDefinition/1.0/changelog
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/systemSettings/misc/genericVariableDefinition/1.0/genericVariableDefinition.st
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/systemSettings/misc/genericVariableDefinition/1.0/metadata.xml
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestDataSerializer.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/DirectiveApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/Translator.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_directives.yml
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_parameters.yml
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_rules.yml
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_techniques.yml
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestDataExtractorTest.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TestRestFromFileDef.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/19086

Fixes #19086: Add more tests for API (directives, techniques, parameters)

---

webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-finished/50-reload-policy-file-server

https://issues.rudder.io/issues/19096

Fixes #19096: Reload cf-serverd only is needed

---

webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/parameterManagement.html

https://issues.rudder.io/issues/19108

Fixes #19108: Syntax helper in the parameter page is outdated

---

webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-finished/50-reload-policy-file-server

https://issues.rudder.io/issues/19112

Fixes #19112: reload cf-serverd only if file changed

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/db/DB.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/reports/execution/ReportExecution.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/reports/execution/ReportsExecutionRepositoryImpl.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ReportsJdbcRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportsTest.scala

https://issues.rudder.io/issues/19117

Fixes #19117: Remove call to executions.complete attribute which was removed

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/Technique.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestTechniqueWriter.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala

https://issues.rudder.io/issues/19115

Fixes #19115: Allow to put empty value in technique parameters

---

webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/metadata.xml

https://issues.rudder.io/issues/19118

Fixes #19118: Fix tests according to changes in metadata.xml

---

webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechniqueTabs.elm
webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/rudder-editor.elm

https://issues.rudder.io/issues/19123

Fixes #19123: Add empty technique parameter in technique editor (7.0)

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/GroupsApi.scala

https://issues.rudder.io/issues/19124

Fixes #19124: Group properties fails with missing "displayInheritedProperties" API

---

webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-finished/60-trigger-node-update

https://issues.rudder.io/issues/19136

Fixes #19136: Delay remote trigger on change

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/queries/CmdbQuery.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/CmdbQueryParser.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/LdapQueryProcessor.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/NewNodeManager.scala
webapp/sources/rudder/rudder-core/src/test/resources/ldap-data/inventory-sample-data.ldif
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/nodes/TestMergeGroupProperties.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestJsonQueryLexing.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestPendingNodePolicies.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestStringQueryParser.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckSystemGroups.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/SearchNodeComponent.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateCategoryOrGroupPopup.scala
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/server/server_details.html

https://issues.rudder.io/issues/19138

Fixes #19138: Add an option to invert result of a node query

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala

https://issues.rudder.io/issues/19139

Fixes #19139: "isBlank" is not supported in jvm8

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/LdapQueryProcessor.scala
webapp/sources/rudder/rudder-core/src/test/resources/ldap-data/inventory-sample-data.ldif
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala

https://issues.rudder.io/issues/19143

Fixes #19143: inverting a request with 0 answer leads to 0 answer

---

relay/sources/rudder-pkg/lib/rudder-pkg/rpkg.py
relay/sources/rudder-pkg/lib/rudder-pkg/tests/test.py

https://issues.rudder.io/issues/19145

Fixes #19145: parent ticket broke the rudder-pkg tests

---

webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala

https://issues.rudder.io/issues/19149

Fixes #19149: Fix compilation issue

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/LdapQueryProcessor.scala

https://issues.rudder.io/issues/19146

Fixes #19146: in some case inverting a request leads to an error and 0 results

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/SharedFilesAPI.scala

https://issues.rudder.io/issues/19158

Fixes #19158: Cannot load file browser if subfolders of the shared-folder contain dead symlinks

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/queries/CmdbQuery.scala

https://issues.rudder.io/issues/19160

Fixes #19160: Query type constructor broke scale out relay plugin

---

contributing/settings.xml
webapp/sources/ldap-inventory/pom.xml
webapp/sources/pom.xml
webapp/sources/rudder/pom.xml
webapp/sources/scala-ldap/pom.xml

https://issues.rudder.io/issues/19164

Fixes #19164: 

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/RudderDit.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/NodeGroup.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/NodeGroupDiff.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/queries/CmdbQuery.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogDetailsService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogFactory.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/CmdbQueryParser.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/DynGroupService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/LdapQueryProcessor.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/QueryProcessor.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/NewNodeManager.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/nodes/TestMergeGroupProperties.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestPendingNodePolicies.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestStringQueryParser.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestDataSerializer.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/RestData.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/EventLogDetailsGenerator.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckSystemGroups.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/SearchNodeComponent.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateCategoryOrGroupPopup.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/SearchNodes.scala

https://issues.rudder.io/issues/19170

Fixes #19170: Binary compatibility still broken by query

---

webapp/sources/ldap-inventory/inventory-provisioning-core/src/main/scala/com/normation/inventory/ldap/provisioning/LdifReportLogger.scala

https://issues.rudder.io/issues/19171

Fixes #19171: Lots of files are created in /var/rudder/inventories/debug

---

webapp/sources/pom.xml

https://issues.rudder.io/issues/19180

Fixes #19180: Broken pom after merge

---

relay/sources/rudder-server-relay-postinst

https://issues.rudder.io/issues/19185

Fixes #19185: postinstall fails on machines with long hostname

---

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py

https://issues.rudder.io/issues/19187

Fixes #19187: Detection of dependencies for plugin can fail if the python lib of another distrib is present

---

Jenkinsfile
Jenkinsfile-security
relay/sources/relayd/Makefile
rust.makefile

https://issues.rudder.io/issues/19184

Fixes #19184: Add scripts to setup Rust build environements in CI

---

Jenkinsfile-security

https://issues.rudder.io/issues/19192

Fixes #19192: Broken security checks with cargo

---

Jenkinsfile
Jenkinsfile-security

https://issues.rudder.io/issues/19197

Fixes #19197: Add maven deploy task to pipeline

---

Jenkinsfile-security

https://issues.rudder.io/issues/19198

Fixes #19198: Broken mvn in Jenkinsfile-security

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/technique.ps1

https://issues.rudder.io/issues/19199

Fixes #19199: Conditions containing a variable are not canonfied with dsc agnt

---

Jenkinsfile-security

https://issues.rudder.io/issues/19214

Fixes #19214: Set CVSS limit for failing webapp dependency check

---

Jenkinsfile
relay/sources/relayd/Makefile
rudder-lang/Makefile
rust.makefile

https://issues.rudder.io/issues/19207

Fixes #19207: Enable language tests

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/domain/VariableAndSectionSpec.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/SystemVariableSpecServiceImpl.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/SystemVariableService.scala
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-500-directives/rules/cfengine-community/common/1.0/cf-serverd.cf
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-500-directives/rules/cfengine-community/rudder.json
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-two-directives/rules/cfengine-community/common/1.0/cf-serverd.cf
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-two-directives/rules/cfengine-community/rudder.json
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-gen-var-def-override/rules/cfengine-community/common/1.0/cf-serverd.cf
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-gen-var-def-override/rules/cfengine-community/rudder.json
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-default-install/common/1.0/cf-serverd.cf
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-default-install/rudder.json
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/common/1.0/cf-serverd.cf
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/rudder.json
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-one-multipolicy/common/1.0/cf-serverd.cf
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-one-multipolicy/rudder.json
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-two-directives/common/1.0/cf-serverd.cf
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-two-directives/rudder.json
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala

https://issues.rudder.io/issues/19217

Fixes #19217: AUTHORIZED_NETWORKS system variable must be multivalued

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/nodeconfig/NodeConfigurationCacheRepository.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/19213

Fixes #19213: Put node cache info into a file in place of LDAP

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/nodeconfig/NodeConfigurationCacheRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/NewNodeManager.scala

https://issues.rudder.io/issues/19221

Fixes #19221: isWritable name change in version of betterfiles in 6.2

---

webapp/sources/api-doc/code_samples/curl/settings/set-allowed-networks.sh
webapp/sources/api-doc/paths/settings/allowed_networks.yml

https://issues.rudder.io/issues/18506

Fixes #18506: Missing documentation for POST allowedNetwords API

---

relay/arch-doc/rudder-7-communications-security.md

https://issues.rudder.io/issues/19126

Fixes #19126: Add an arch doc for certificate changes in 7.0

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PolicyWriterService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PromiseWriteDataStructures.scala

https://issues.rudder.io/issues/19222

Fixes #19222: Policy generation does change technique resource files when it should not

---

rust.makefile

https://issues.rudder.io/issues/19225

Fixes #19225: Allow building without sccache

---

webapp/sources/pom.xml
webapp/sources/rudder/rudder-web/pom.xml
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala

https://issues.rudder.io/issues/19216
Replace PR https://github.com/Normation/rudder/pull/3613 by back porting  https://issues.rudder.io/issues/18406

Fixes #19216: Update reflections to remove vulnerable guava dependency

---

Jenkinsfile-security

https://issues.rudder.io/issues/19231

Fixes #19231: Check dependencie fails with NPE

---

webapp/sources/api-doc/components/schemas/settings.yml

https://issues.rudder.io/issues/19235

Fixes #19235: Undocumented API rudder_verify_certificates

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SettingsApi.scala

https://issues.rudder.io/issues/19236

Fixes #19236: Remove unused API setting  use_reverse_dns

---

webapp/sources/api-doc/components/schemas/node-add.yml
webapp/sources/api-doc/paths/settings/allowed_networks_diff.yml

https://issues.rudder.io/issues/19202

Fixes #19202: API documentation is missleading for properties

---

qa-test

https://issues.rudder.io/issues/19245

Fixes #19245: Broken scripts checks in master

---

relay/sources/Makefile

https://issues.rudder.io/issues/19247

Fixes #19247: relay package fails to build on rhel7

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/SystemVariableSpecServiceImpl.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/SystemVariableService.scala
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-500-directives/rules/cfengine-community/rudder.json
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-two-directives/rules/cfengine-community/rudder.json
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-gen-var-def-override/rules/cfengine-community/rudder.json
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-default-install/rudder.json
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/rudder.json
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-one-multipolicy/rudder.json
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-two-directives/rudder.json
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SettingsApi.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/19259

Fixes #19259: Add HTTPS_POLICY_DISTRIBUTION_PORT system variable 

---

.gitignore
Jenkinsfile-security
qa-test
webapp/sources/dependency-check-suppression.xml

https://issues.rudder.io/issues/19265

Fixes #19265: Missing folder exclusion in shell tests

---

.gitignore
Jenkinsfile-security
qa-test
webapp/sources/dependency-check-suppression.xml

https://issues.rudder.io/issues/19271

Fixes #19271: Backport folder exclusion and maven security exclusion in tests

---

webapp/sources/dependency-check-suppression.xml

https://issues.rudder.io/issues/19272

Fixes #19272: Ignore security alert for unused js embeded in scala lib

---

webapp/sources/api-doc/introduction.md
webapp/sources/api-doc/paths/branding/conf.yml
webapp/sources/api-doc/paths/change-requests/accept.yml
webapp/sources/api-doc/paths/change-requests/id.yml
webapp/sources/api-doc/paths/change-requests/update-valid-users.yml
webapp/sources/api-doc/paths/directives/id-check.yml
webapp/sources/api-doc/paths/directives/id.yml
webapp/sources/api-doc/paths/groups/categories.yml
webapp/sources/api-doc/paths/groups/category-id.yml
webapp/sources/api-doc/paths/groups/id.yml
webapp/sources/api-doc/paths/nodes/pending-id.yml
webapp/sources/api-doc/paths/parameters/parameters.yml
webapp/sources/api-doc/paths/rules/categories.yml
webapp/sources/api-doc/paths/rules/category-id.yml
webapp/sources/api-doc/paths/rules/id.yml
webapp/sources/api-doc/paths/settings/allowed_networks.yml
webapp/sources/api-doc/paths/settings/allowed_networks_diff.yml
webapp/sources/api-doc/paths/settings/setting.yml
webapp/sources/api-doc/paths/usermanagement/add.yml
webapp/sources/api-doc/paths/usermanagement/update.yml

https://issues.rudder.io/issues/19276

Fixes #19276: Remove reference to x-www-form-urlencoded in API commands

---

webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
webapp/sources/scala-ldap/src/main/scala/com/normation/ldap/sdk/LDAPConnectionProvider.scala

https://issues.rudder.io/issues/19284

Fixes #19284: Add name to LDAP pool to help debugging

---

Jenkinsfile
Jenkinsfile-security

https://issues.rudder.io/issues/19246

Fixes #19246: Clean workspace at the end of Rust builds and add licence artifacts

---

webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/FusionReportUnmarshaller.scala
webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-report/rudder-tag/minimal-no-rudder.ocs
webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-report/rudder-tag/minimal-one-agent-two-rudder-fails.ocs
webapp/sources/ldap-inventory/inventory-fusion/src/test/scala/com/normation/inventory/provisioning/fusion/TestReportParsing.scala

https://issues.rudder.io/issues/19305

Fixes #19305: Ininventory, if there is two "rudder" tag, uuid are concatenated

---

Jenkinsfile
relay/sources/relayd/deny.toml
relay/sources/relayd/tests/remote_run.rs
relay/sources/relayd/tools/openssl.cnf
relay/sources/rudder-pkg/lib/docopt.py
relay/sources/rudder-pkg/lib/rudder-pkg/plugin.py
relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
rudder-lang/deny.toml
rudder-lang/docs/index.adoc
rudder-lang/docs/operating-systems.adoc
rudder-lang/docs/usage.adoc
rudder-lang/src/generator/dsc/syntax.rs
rudder-lang/src/io/output/backtrace.rs
rudder-lang/src/ir/enums.rs
rudder-lang/src/parser.rs
rudder-lang/src/parser/tests.rs
rudder-lang/src/parser/token.rs
rudder-lang/tests/compile.rs
rudder-lang/tools/docopt.py
rudder-lang/tools/generated_formats_tester
webapp/sources/api-doc/code_samples/curl/compliance/nodes.sh
webapp/sources/api-doc/code_samples/curl/datasources/update.sh
webapp/sources/api-doc/components/schemas/node-full.yml
webapp/sources/api-doc/introduction.md

https://issues.rudder.io/issues/19328

Fixes #19328: Add typos check to CI config

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala

https://issues.rudder.io/issues/19351

Fixes #19351: queryAndChekNodeId sometimes query for 0 nodes

---

Jenkinsfile
relay/sources/relayd/deny.toml
relay/sources/relayd/tests/remote_run.rs
relay/sources/relayd/tools/openssl.cnf
relay/sources/rudder-pkg/lib/docopt.py
relay/sources/rudder-pkg/lib/rudder-pkg/plugin.py
relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
webapp/sources/api-doc/code_samples/curl/compliance/nodes.sh
webapp/sources/api-doc/code_samples/curl/datasources/update.sh
webapp/sources/api-doc/components/schemas/node-full.yml
webapp/sources/api-doc/introduction.md

https://issues.rudder.io/issues/19359

Fixes #19359: Backport typos checks to 6.1

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/api/ApiAccountRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitArchiverUtils.scala

https://issues.rudder.io/issues/19363

Fixes #19363: Semaphore in APIAccountRepository,GitArchiverUtils and maybe PolicyServerManagementService are not semaphoring

---

webapp/sources/rudder/rudder-rest/src/test/resources/api/api_techniques.yml

https://issues.rudder.io/issues/19345

Fixes #19345: Since we forbid chars in technique version, we actually have to not use them

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/NodeDetailLevel.scala

https://issues.rudder.io/issues/19374

Fixes #19374: API shows only part of the memory information

---

relay/sources/relayd/src/input/watch.rs
relay/sources/relayd/src/processing/inventory.rs
relay/sources/relayd/src/processing/reporting.rs

https://issues.rudder.io/issues/19375

Fixes #19375: relayd on relays fails to retry inventories upload

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/AutomaticReportLogger.scala

https://issues.rudder.io/issues/19381

Fixes #19381: Confusing message when we disable non-compliant-report log

---

webapp/sources/api-doc/code_samples/curl/info/all.sh
webapp/sources/api-doc/code_samples/curl/info/get-endpoint.sh
webapp/sources/api-doc/code_samples/curl/info/get-section.sh
webapp/sources/api-doc/components/schemas/api-endpoints.yml
webapp/sources/api-doc/components/schemas/api-version.yml
webapp/sources/api-doc/components/schemas/api-versions.yml
webapp/sources/api-doc/openapi.src.yml
webapp/sources/api-doc/paths/info/all.yml
webapp/sources/api-doc/paths/info/endpoint-id.yml
webapp/sources/api-doc/paths/info/section-id.yml

https://issues.rudder.io/issues/19395

Fixes #19395: Info API is not documented

---

webapp/sources/rudder/rudder-rest/pom.xml

https://issues.rudder.io/issues/19400

Fixes #19400: Update snakeyaml dependency for security

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/RemoveNodeService.scala

https://issues.rudder.io/issues/19394

Fixes #19394: When a node is totally deleted, cache in NodeInfoService can't know about it

---

webapp/sources/pom.xml

https://issues.rudder.io/issues/19407

Fixes #19407: CVE in spring dependency

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/19416

Fixes #19416: Missing default value for HTTPS port

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/CheckInventoryUpdate.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala

https://issues.rudder.io/issues/19414

Fixes #19414: Inventory with updated properties doesn't always start a policy generation

---

relay/sources/relayd/src/processing/reporting.rs

https://issues.rudder.io/issues/19435

Fixes #19435: Missing cleanup of /var/rudder/reports/failed

---

relay/sources/relayd/src/processing/reporting.rs

https://issues.rudder.io/issues/19436

Fixes #19436:  Missing cleanup of /var/rudder/reports/failed - master fix

---

relay/sources/rudder-server-relay-postinst

https://issues.rudder.io/issues/19447

Fixes #19447: Broken short hostname in agent certificate

---

relay/sources/Makefile
relay/sources/rudder-pkg/lib/rudder-pkg/plugin.py
relay/sources/rudder-pkg/lib/rudder-pkg/rpkg.py
relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py
relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgLogger.py
relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
relay/sources/rudder-pkg/lib/rudder-pkg/tests/rudderPkgUtils.test.py
relay/sources/rudder-pkg/lib/rudder-pkg/tests/test.py
relay/sources/rudder-pkg/pyproject.toml
relay/sources/rudder-pkg/rudder-pkg

https://issues.rudder.io/issues/19441

Fixes #19441: Improve pylint config and add formatter to rudder-pkg

---

relay/sources/rudder-pkg/lib/rudder-pkg/rpkg.py
relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py
relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
relay/sources/rudder-pkg/lib/rudder-pkg/tests/test.py

https://issues.rudder.io/issues/19449

Fixes #19449:  Improve pylint config and add formatter to rudder-pkg - master

---

relay/sources/relayd/src/api/remote_run.rs
relay/sources/relayd/tests/remote_run.rs

https://issues.rudder.io/issues/19455

Fixes #19455: 

---

relay/sources/relayd/tests/remote_run.rs

https://issues.rudder.io/issues/19461

Fixes #19461: 

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/ApplicationLogger.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/nodes/NodeInfoServiceCachedTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala

https://issues.rudder.io/issues/19399

Fixes #19399: Improve NodeInfo cache

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala

https://issues.rudder.io/issues/19466

Fixes #19466: upmege of parent ticket is inefficient

---

webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/DataTypes.scala
webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/services/provisioning/CheckInventoryDigest.scala
webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/InventoryMapper.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/queries/CmdbQuery.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/InfoApi.scala

https://issues.rudder.io/issues/19467

Fixes #19467: Inefficient comparision of strings in Rudder

---

language/src/bin/rudderc.rs
language/src/command.rs
language/src/command/lint.rs
language/src/io.rs
language/src/io/cli_parser.rs
language/tools/rudderc-dev.conf

https://issues.rudder.io/issues/19471

Fixes #19471: Add a lint option to rudderc

---

relay/sources/relayd/src/input/watch.rs

https://issues.rudder.io/issues/19478

Fixes #19478: Missing catchup limit in 7.0

---

relay/sources/relayd/Cargo.lock
relay/sources/relayd/src/input/watch.rs
relay/sources/relayd/src/processing/reporting.rs

https://issues.rudder.io/issues/19479

Fixes #19479: Broken reports watcher in 7.0

---

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py

https://issues.rudder.io/issues/19480

Fixes #19480: Parent ticket break the plugin scripts execution

---

webapp/sources/pom.xml

https://issues.rudder.io/issues/19503

Fixes #19503: Vulnerability in spring-security

---

relay/sources/apache/rudder-vhost.conf
relay/sources/rudder-server-relay-postinst
relay/sources/selinux/rudder-relay.fc

https://issues.rudder.io/issues/19504

Fixes #19504: Fix certificate configuration for httpd

---

webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/nodes/NodeInfoServiceCachedTest.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ComplianceData.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/SrvGrid.scala

https://issues.rudder.io/issues/19456

Fixes #19456: 

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/Properties.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/nodes/TestMergeGroupProperties.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/ShowNodeDetailsFromNode.scala
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js

https://issues.rudder.io/issues/19505

Fixes #19505: 

---

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py

https://issues.rudder.io/issues/19516

Fixes #19516: Incorrect program execution

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala

https://issues.rudder.io/issues/19518

Fixes #19518: Property with inherited values display is broken on page reload on node list

---

relay/sources/relayd/Cargo.lock

https://issues.rudder.io/issues/19520

Fixes #19520: Memory corruption in tokio

---

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py

https://issues.rudder.io/issues/19523

Fixes #19523: Improve command error message

---

relay/sources/relayd/Cargo.lock
relay/sources/relayd/Cargo.toml
relay/sources/relayd/src/hashing.rs
relay/sources/relayd/tests/files/nodeslist.json

https://issues.rudder.io/issues/19525

Fixes #19525: Read base64 hash in nodeslist.conf

---

webapp/sources/pom.xml
webapp/sources/rudder/rudder-core/pom.xml

https://issues.rudder.io/issues/19530

Fixes #19530: CVE in jsonpath dependency

---

relay/sources/relayd/src/api/shared_files.rs
relay/sources/relayd/src/api/shared_folder.rs
relay/sources/relayd/src/data/node.rs
relay/sources/relayd/src/data/shared_file.rs
relay/sources/relayd/src/hashing.rs

https://issues.rudder.io/issues/19528

Fixes #19528: Store hashes as bytes

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/xmlparsers/TechniqueParser.scala

https://issues.rudder.io/issues/19536

Fixes #19536: Do not fail technique parsing on missing system variable

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PolicyWriterService.scala

https://issues.rudder.io/issues/19557

Fixes #19557: Compilation error: Path.of does not exist with Java 8

---

language/src/generator/cfengine.rs
language/src/generator/cfengine/syntax.rs
language/src/technique.rs
language/src/technique/from_ir.rs
language/tests/techniques/simple_block/technique.json
language/tests/techniques/simplest/technique.cf
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/EditorTechnique.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/metadata.xml
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/rudder_reporting.cf
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/technique.cf
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestEditorTechniqueWriter.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/JsonEncoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewBlock.elm
webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewMethod.elm
webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechnique.elm
webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/rudder-editor.elm

https://issues.rudder.io/issues/19558

Fixes #19558: Add a way to disable/enable reporting of a method in technique editor

---

webapp/sources/rudder/rudder-core/src/main/resources/ldap/bootstrap.ldif
webapp/sources/rudder/rudder-core/src/main/resources/ldap/init-policy-server.ldif

https://issues.rudder.io/issues/19561

Fixes #19561: Add allowed networks to new bootstrap of system techniques

---

webapp/sources/rudder/rudder-web/src/main/elm/rules/elm.json
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ApiCalls.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/View.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/rudder-rules.elm

https://issues.rudder.io/issues/19555

Fixes #19555: Allow the creation of a rule in the new IU

---

Jenkinsfile

https://issues.rudder.io/issues/19569

Fixes #19569: Prevent race condition in relayd tests

---

webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/View.elm
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-technique-editor.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css

https://issues.rudder.io/issues/19579

Fixes #19579: Create the Actions button dropdown

---

relay/sources/relayd/src/api/shared_files.rs

https://issues.rudder.io/issues/19547

Fixes #19547: Relayd deadlocks when trying to forward a shared-file

---

webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TestRestFromFileDef.scala

https://issues.rudder.io/issues/19587

Fixes #19587: Still a Path.of in TestRestFromFileDef.scala

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/LiftInitContextListener.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/19586

Fixes #19586: Parent task failed to stop jetty when ldap connection is down at boot

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/nodeconfig/NodeConfigurationCacheRepository.scala

https://issues.rudder.io/issues/19589

Fixes #19589: NoSuchFileException: /var/rudder/policy-generation-info/node-configuration-hashes.json

---

webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/rudder-editor.elm

https://issues.rudder.io/issues/19600

Fixes #19600: error getting techniques when coming back on technique page

---

webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-finished/40-nodelist-relay-configuration

https://issues.rudder.io/issues/19607

Fixes #19607: wrong correction in parent ticket

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/policies/Rule.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/PolicyServerManagementService.scala

https://issues.rudder.io/issues/19576

Fixes #19576: Add system configuration object for scale-out-relay plugin

---

webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewBlock.elm
webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewMethod.elm

https://issues.rudder.io/issues/19605

Fixes #19605: "reporting based on" is duplicated on component

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitArchiverImpl.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/HistorizationService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlSerialisation.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchBackendImpl.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/workflows/CommitAndDeployChangeRequestService.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/write/WriteTechniquesTest.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/TechniqueApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/EventLogDetailsGenerator.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala

https://issues.rudder.io/issues/19609

Fixes #19609: versionning is too technical on the directive tree

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala

https://issues.rudder.io/issues/19617

Fixes #19617: Rename settings menu to administration

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala

https://issues.rudder.io/issues/19614

Fixes #19614: Remove server roles in node details

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/ApplicationLogger.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/PropertyEngineService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DataStructures.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/InterpolatedValueCompiler.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/RuleValService.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestEditorTechniqueWriter.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/RuleValServiceTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestBuildNodeConfiguration.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestNodeAndGlobalParameterLookup.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/18772

Fixes #18772: Create a parser for encrypted properties feature

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RoleApiMapping.scala

https://issues.rudder.io/issues/19631

Fixes #19631: It is impossible to read properties with a read-only account

---

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py
relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py

https://issues.rudder.io/issues/19476

Fixes #19476: Make rudder package command use version files

---

webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/View.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/rudder-rules.elm
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-rules.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-technique-editor.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css

https://issues.rudder.io/issues/19581

Fixes #19581: Improving the UX when creating a rule

---

webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-datatable.css

https://issues.rudder.io/issues/19620

Fixes #19620: all small icons are broken in 7.0

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/NodeRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/NodeConfigurationService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/NewNodeManager.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/19633

Fixes #19633: deletenode is used by scaleoutrelay

---

webapp/sources/rudder/rudder-web/src/main/webapp/index.html
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/nodeProperties.js
webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/parameterManagement.html
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-datatable.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-node.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-plugins.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-technique-editor.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder.css

https://issues.rudder.io/issues/19562

Fixes #19562: Multiples UI error on 7.0

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/eventlog/EventLogCategories.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/eventlog/NodeEventLog.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/EventLogRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDirectiveRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPRuleRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogFactory.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/PolicyServerManagementService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/EventLogDetailsGenerator.scala

https://issues.rudder.io/issues/19642
See in combination with https://issues.rudder.io/issues/19641

Fixes #19642: Adapt code to scale-out-relay in rudder 7 

---

webapp/sources/rudder/rudder-core/src/main/resources/ldap/bootstrap.ldif
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchBackendImpl.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchDomain.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/server/server_details.html

https://issues.rudder.io/issues/19630

Fixes #19630: more server role/component cleaning

---

webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/FusionReportUnmarshaller.scala

https://issues.rudder.io/issues/19632

Fixes #19632: Incorrect pattern matching leads to error in inventory parsing

---

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py

https://issues.rudder.io/issues/19649

Fixes #19649: warning when upgrading from 7.0 nightly to 7.0 nightly

---

relay/sources/relayd/src/configuration/main.rs
relay/sources/relayd/src/lib.rs
relay/sources/relayd/tests/files/config/main.conf
relay/sources/relayd/tools/config/main.conf

https://issues.rudder.io/issues/19643

Fixes #19643: Improve certificate handling in relayd

---

webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/nodeProperties.js

https://issues.rudder.io/issues/19654

Fixes #19654: Broken group properties

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleGrid.scala

https://issues.rudder.io/issues/19651

Fixes #19651: Broken rules list in directive form

---

webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ApiCalls.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Init.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/View.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRuleDetails.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/rudder-rules.elm

https://issues.rudder.io/issues/19656

Fixes #19656: Add a button to delete the selected rule

---

webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-elm.js
webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/ruleManagement.html

https://issues.rudder.io/issues/19662

Fixes #19662: JS error while initializing Elm app since we upgrade elm to 0.19.1

---

relay/sources/relayd/src/data/runinfo.rs
relay/sources/relayd/src/data/runlog.rs

https://issues.rudder.io/issues/19615

Fixes #19615: Compliance problem in 7.0

---

webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Rules.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRuleDetails.elm

https://issues.rudder.io/issues/19661

Fixes #19661: Add a button to clone the selected rule

---

webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRuleDetails.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRulesTable.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewTabContent.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewUtilsCompliance.elm
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-rules.css

https://issues.rudder.io/issues/19667

Fixes #19667: Display Directive compliance in the Rules UI

---

webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/policyServerManagement.html

https://issues.rudder.io/issues/19652

Fixes #19652: Update certificate validation setting for 7.0

---

relay/sources/selinux/rudder-relay.fc

https://issues.rudder.io/issues/19674

Fixes #19674: Update SELinux config for new relayd files

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/SystemVariableService.scala

https://issues.rudder.io/issues/19680

Fixes #19680: 

---

webapp/sources/rudder/rudder-web/src/main/elm/onboarding/sources/View.elm

https://issues.rudder.io/issues/19682

Fixes #19682: typo in onboarding program for metrics

---

relay/sources/apache/rudder-apache-relay-ssl.conf

https://issues.rudder.io/issues/19683

Fixes #19683:  Read nodecerts.pem on simple relayd - apache

---

relay/sources/selinux/rudder-relay.fc

https://issues.rudder.io/issues/19687

Fixes #19687: Read nodecerts.pem on simple relayd - SELinux

---

webapp/sources/rudder/rudder-web/src/main/elm/build-app.sh

https://issues.rudder.io/issues/19688

Fixes #19688: build-app does not fail if the elm compiler is not there

---

webapp/sources/rudder/rudder-web/src/main/elm/build-app.sh

https://issues.rudder.io/issues/19689

Fixes #19689: Fail on elm build error

---

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py

https://issues.rudder.io/issues/19690

Fixes #19690: rudder packages refuses to install -SNAPSHOT plugins

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala

https://issues.rudder.io/issues/19694

Fixes #19694: technique editor uses too many quotes to calls rudderc

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala

https://issues.rudder.io/issues/19697

Fixes #19697: technique editor  uses .rl extension instead of .rd

---

language/src/bin/rudderc.rs
language/src/command/save.rs
language/src/command/technique_generate.rs
language/src/technique.rs
language/src/technique/from_ir.rs
language/tests/techniques/CIS/technique.json
language/tests/techniques/cdt/technique.json
language/tests/techniques/condition_alias/technique.json
language/tests/techniques/condition_anybsd/technique.json
language/tests/techniques/condition_dyn/technique.json
language/tests/techniques/condition_errorprone/technique.json
language/tests/techniques/condition_foreign_variable/technique.json
language/tests/techniques/condition_priority/technique.json
language/tests/techniques/condition_useless_brackets/technique.json
language/tests/techniques/conditional_method/technique.json
language/tests/techniques/deprecated/technique.json
language/tests/techniques/dsc/technique.json
language/tests/techniques/duplicated/technique.json
language/tests/techniques/escaped/technique.json
language/tests/techniques/inner_block/technique.json
language/tests/techniques/multiple_simple/technique.json
language/tests/techniques/parameters/technique.json
language/tests/techniques/parameters_mult/technique.json
language/tests/techniques/simple_block/technique.json
language/tests/techniques/simplest/technique.json
language/tests/techniques/stateless/technique.json
language/tests/techniques/supported_formats/technique.json
language/tools/generated_formats_tester
language/tools/test_all_techniques.sh

https://issues.rudder.io/issues/19695

Fixes #19695: rudderc cannot save technique editor data

---

relay/sources/rudder-server-relay-postinst

https://issues.rudder.io/issues/19710

Fixes #19710: Missing nodescerts.pem during postinst

---

language/src/bin/rudderc.rs
language/src/io.rs
language/src/io/cli_parser.rs
language/src/io/cli_parser/options.rs
language/src/io/cli_parser/technique.rs
language/tools/test_all_techniques.sh
language/tools/tester.sh

https://issues.rudder.io/issues/19724

Fixes #19724: rudderc adds .rd to every files it generates

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala

https://issues.rudder.io/issues/19723

Fixes #19723: node properties writen in policies is invalid

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala

https://issues.rudder.io/issues/19728

Fixes #19728: improve fix of parent ticket

---

relay/sources/relayd/deny.toml

https://issues.rudder.io/issues/19731

Fixes #19731: Two vulnerabilities in hyper

---

relay/sources/relayd/deny.toml

https://issues.rudder.io/issues/19732

Fixes #19732:  Two vulnerabilities in hyper - fixed in 7.0

---

webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-datatable.css
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css

https://issues.rudder.io/issues/19665

Fixes #19665: Display of configuration of nodes table column is not great in 7.0

---

relay/sources/apache/rudder-apache-relay-nossl.conf

https://issues.rudder.io/issues/19733

Fixes #19733: Redirect everything to https

---

relay/sources/selinux/rudder-relay.fc
relay/sources/selinux/rudder-relay.te

https://issues.rudder.io/issues/19736

Fixes #19736: Missing changes in SELinux configuration

---

webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-datatable.css

https://issues.rudder.io/issues/19666

Fixes #19666: there is no indication on column sorting in nodes table in rudder 7.0

---

webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/JsonEncoder.elm

https://issues.rudder.io/issues/19744

Fixes #19744: When we save a rule, the directives are not saved

---

webapp/sources/pom.xml

https://issues.rudder.io/issues/19751

Fixes #19751: cannot execute command because of parent ticket - revert nuprocess to 2.0.1

---

relay/sources/rudder-server-relay-postinst

https://issues.rudder.io/issues/19750

Fixes #19750:  Remove useless log messages from packages scripts - rudder side

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala

https://issues.rudder.io/issues/19748

Fixes #19748: Add timing logger to technique editor

---

webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ApiCalls.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Rules.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/View.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRuleDetails.elm
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css

https://issues.rudder.io/issues/19745

Fixes #19745: Add a button to disable or enable the selected rule

---

webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Rules.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/View.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewTabContent.elm

https://issues.rudder.io/issues/19743

Fixes #19743: Refresh the list of Rules after saving

---

relay/sources/rudder-server-relay-postinst

https://issues.rudder.io/issues/19758

Fixes #19758: Missing SELinux for root.pem

---

relay/sources/rudder-server-relay-postinst

https://issues.rudder.io/issues/19759

Fixes #19759: Missing SELinux for root.pem - directory does not exist

---

webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewMethodsList.elm

https://issues.rudder.io/issues/19565

Fixes #19565: Filter on generic methods name should not be case sensitive

---

relay/sources/selinux/rudder-relay.te

https://issues.rudder.io/issues/19770

Fixes #19770: Missing right to read symlinks

---

webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewMethod.elm

https://issues.rudder.io/issues/19773

Fixes #19773: result condition in the technique editor are wrong

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/PolicyServerManagementService.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala

https://issues.rudder.io/issues/19779

Fixes #19779: Allowed networks are not saved for the Relay

---

api-doc/custom.css

https://issues.rudder.io/issues/19798

Fixes #19798: Use the Lato files from the docs in API docs

---

api-doc/custom.css

https://issues.rudder.io/issues/19806

Fixes #19806: Fix API docs CSS

---

webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ApiCalls.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Init.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/JsonEncoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Rules.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/View.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewCategoryDetails.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRuleDetails.elm
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css

https://issues.rudder.io/issues/19753

Fixes #19753: Make rule categories editable

---

relay/sources/relayd/Cargo.lock
relay/sources/relayd/Cargo.toml
relay/sources/relayd/src/api/system.rs
relay/sources/relayd/src/configuration/cli.rs
relay/sources/relayd/src/http_client.rs
relay/sources/relayd/src/lib.rs
relay/sources/relayd/src/main.rs

https://issues.rudder.io/issues/19790

Fixes #19790: Use gumdrop instead of structopt

---

relay/sources/relayd/Cargo.lock
relay/sources/relayd/Cargo.toml
relay/sources/relayd/src/api/system.rs
relay/sources/relayd/src/configuration/cli.rs
relay/sources/relayd/src/http_client.rs
relay/sources/relayd/src/lib.rs
relay/sources/relayd/src/main.rs

https://issues.rudder.io/issues/19810

Fixes #19810:  Use gumdrop instead of structopt - 7.0 branch

---

relay/sources/relayd/src/processing/inventory.rs

https://issues.rudder.io/issues/19813

Fixes #19813: File watchers on inventories do not work

---

relay/sources/relayd/src/api/system.rs
relay/sources/relayd/src/configuration.rs
relay/sources/relayd/src/configuration/main.rs
relay/sources/relayd/src/lib.rs
relay/sources/relayd/src/main.rs

https://issues.rudder.io/issues/19784

Fixes #19784: Warn in check config when relayd has an insecure configuration

---

relay/sources/apache/rudder-apache-relay-common.conf
relay/sources/apache/rudder-apache-relay-nossl.conf
relay/sources/apache/rudder-apache-relay-ssl.conf
relay/sources/apache/rudder-vhost.conf

https://issues.rudder.io/issues/19821

Fixes #19821: Refactor apache configs

---

Jenkinsfile
webapp/sources/rudder/rudder-web/src/main/elm/build-dev.sh
webapp/sources/rudder/rudder-web/src/main/elm/editor/build-dev.sh
webapp/sources/rudder/rudder-web/src/main/elm/editor/elm.json
webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/AgentValueParser.elm
webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/Editor.elm
webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/JsonEncoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewMethod.elm
webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechniqueTabs.elm
webapp/sources/rudder/rudder-web/src/main/elm/editor/tests/AgentValueParserTest.elm
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleGrid.scala

https://issues.rudder.io/issues/19776

Fixes #19776: result condition are canonifying variables

---

webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewMethod.elm
webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechniqueTabs.elm

https://issues.rudder.io/issues/19801

Fixes #19801: copy to clipboard button of resource in Technique editor doesn't copy to clipboard

---

webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/Editor.elm
webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/JsonEncoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewMethod.elm
webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechnique.elm
webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechniqueTabs.elm

https://issues.rudder.io/issues/19802

Fixes #19802: Saving a technique fails when a resource was unchanged (should be untouched)

---

webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-technique-editor.css

https://issues.rudder.io/issues/19818

Fixes #19818: generic method group link has the wrong cursor

---

webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewMethod.elm

https://issues.rudder.io/issues/19819

Fixes #19819: The information pointer on generic method doesn't display information

---

webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-technique-editor.css

https://issues.rudder.io/issues/19714

Fixes #19714: On technique editor, the Categories section doesnt look great

---

webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/hooks/RunNuCommandTest.scala

https://issues.rudder.io/issues/19828

Fixes #19828: RunNuCommandTest fails with timeout on CI

---

webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewMethodsList.elm
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-technique-editor.css

https://issues.rudder.io/issues/19717

Fixes #19717: documentation of generic methods is broken in 7.0 - and t cannot be selected / copy/pasted

---

relay/sources/relayd/Cargo.lock
relay/sources/relayd/Cargo.toml

https://issues.rudder.io/issues/19832

Fixes #19832: nom 7.0

---

relay/sources/relayd/src/api.rs
relay/sources/relayd/src/api/metrics.rs
relay/sources/relayd/src/api/shared_files.rs
relay/sources/relayd/src/api/shared_folder.rs
relay/sources/relayd/src/api/system.rs

https://issues.rudder.io/issues/19834

Fixes #19834: Improve relayd compilation time by 30-40%

---

relay/sources/relayd/Cargo.lock

https://issues.rudder.io/issues/19833

Fixes #19833: Data race in crossbeam-deque

---

relay/sources/relayd/Cargo.lock

https://issues.rudder.io/issues/19835

Fixes #19835:  Data race in crossbeam-deque - 6.2

---

webapp/sources/api-doc/code_samples/curl/secret/add.sh
webapp/sources/api-doc/code_samples/curl/secret/all.sh
webapp/sources/api-doc/code_samples/curl/secret/delete.sh
webapp/sources/api-doc/code_samples/curl/secret/getOne.sh
webapp/sources/api-doc/components/parameters/secret-name.yml
webapp/sources/api-doc/components/schemas/secrets.yml
webapp/sources/api-doc/openapi.src.yml
webapp/sources/api-doc/paths/secret/all.yml
webapp/sources/api-doc/paths/secret/id.yml

https://issues.rudder.io/issues/19730

Fixes #19730: API documentation for secret variabel feature

---

Jenkinsfile

https://issues.rudder.io/issues/19829

Fixes #19829: Move elm test in the webapp step to avoid concurrent builds

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/Constants.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/eventlog/EventLogCategories.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/eventlog/SecretEventLog.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/secret/Secret.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/EventLogRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/EventLogJdbcRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogDetailsService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogFactory.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/SecretEventLogService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlSerialisation.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlSerialisationImpl.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlUnserialisation.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlUnserialisationImpl.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/eventlog/NodeEventLogFormatV6Test.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/EventLogDetailsGenerator.scala
webapp/sources/rudder/rudder-web/src/main/resources/eventLogTypeNames.properties
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/19646
We should merge https://github.com/Normation/rudder/pull/3793 first before merging this

Fixes #19646: Secrets variables event log

---

language/src/generator/dsc.rs
language/src/ir/resource.rs
language/src/ir/value.rs
language/src/parser.rs
language/src/parser/tests.rs
language/src/technique.rs
language/src/technique/from_ir.rs
language/tests/techniques/inner_block/technique.json
language/tests/techniques/simple_block/technique.json

https://issues.rudder.io/issues/19858

Fixes #19858: rudderc fails to read blocks in techniques

---

relay/sources/rudder-pkg/lib/rudder-pkg/plugin.py
relay/sources/rudder-pkg/lib/rudder-pkg/rpkg.py
relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py
relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgLogger.py
relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py

https://issues.rudder.io/issues/19886

Fixes #19886: Format the rudder-pkg python files

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/DebugComplianceLogger.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/reports/execution/ReportsExecutionRepository.scala

https://issues.rudder.io/issues/19894

Fixes #19894: debug_timing debug log is polluted by cache last run hashmap

---

webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechnique.elm

https://issues.rudder.io/issues/19865

Fixes #19865: Technique editor allows empty technique name

---

relay/sources/rudder-pkg/lib/rudder-pkg/plugin.py
relay/sources/rudder-pkg/lib/rudder-pkg/rpkg.py
relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py
relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
relay/sources/rudder-pkg/lib/rudder-pkg/tests/test.py
relay/sources/rudder-pkg/rudder-pkg

https://issues.rudder.io/issues/19868

Fixes #19868: Rudder package should accept plugins with same minor version, not just patch version

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala

https://issues.rudder.io/issues/19897

Fixes #19897: Display result of search with thousands of nodes is really slow on 6.2 & 7.0

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/EditorTechnique.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala

https://issues.rudder.io/issues/19719

Fixes #19719: disable reporting option is not saved in technique editor

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/GitUtils.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/GitUtilsImpl.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitArchiverUtils.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/cfclerk/services/JGitRepositoryTest.scala

https://issues.rudder.io/issues/19398

Fixes #19398: Git error when deleting a node or archiving everything, and very slow git

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/RemoveNodeService.scala

https://issues.rudder.io/issues/19571

Fixes #19571: Error about cfengine key when deleting a node

---

webapp/sources/rudder/rudder-core/src/test/scala/com/normation/cfclerk/services/JGitRepositoryTest.scala

https://issues.rudder.io/issues/19907

Fixes #19907: Compilation error after #19398 merge on upper branches

---

webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechniqueList.elm
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css

https://issues.rudder.io/issues/19913

Fixes #19913: Display number of techniques in the editor

---

webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/JsonDecoder.elm

https://issues.rudder.io/issues/19881

Fixes #19881: Saving groups in the rules UI is broken

---

relay/sources/rudder-pkg/rudder-pkg

https://issues.rudder.io/issues/19923

Fixes #19923: wrong option name in rudder package command

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/Login.scala
webapp/sources/rudder/rudder-web/src/main/webapp/index.html
webapp/sources/rudder/rudder-web/src/main/webapp/style/login.css

https://issues.rudder.io/issues/19938

Fixes #19938: Copy to clipboard button for user creation command in login page

---

webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Init.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Rules.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/View.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewCategoryDetails.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRuleDetails.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewTabContent.elm
webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/ruleManagement.html
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-rules.css

https://issues.rudder.io/issues/19775

Fixes #19775: there aren't any authorizations on the rules pages

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/InterpolatedValueCompiler.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestNodeAndGlobalParameterLookup.scala

https://issues.rudder.io/issues/19943

Fixes #19943: Change format to call engines in properties 

---

webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/Editor.elm
webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/MethodElemUtils.elm
webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewBlock.elm
webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewMethod.elm

https://issues.rudder.io/issues/19959

Fixes #19959: cannot remove a method within a block

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/TechniqueAcceptationDatetimeUpdater.scala

https://issues.rudder.io/issues/19956

Fixes #19956: Typo in log "deletedbut"

---

webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/techniqueEditor.html

https://issues.rudder.io/issues/19953

Fixes #19953: error in technique editor in rudder 7 when copying class result from within a block

---

webapp/sources/rudder/rudder-web/src/main/elm/rules/elm.json
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Init.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Rules.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/View.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewCategoryDetails.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRuleDetails.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRulesTable.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewTabContent.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewUtilsCompliance.elm
webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css

https://issues.rudder.io/issues/19871

Fixes #19871: rules sorting does not work and they are not sorted by default

---

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py
relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
relay/sources/rudder-pkg/rudder-pkg

https://issues.rudder.io/issues/19967

Fixes #19967: Improve rudder package output
