Normation/rudder

- relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py
- relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
https://issues.rudder.io/issues/19969
> Fixes #19969: Don't allow directory traversal through plugin URL

- language/src/technique.rs
- language/src/technique/from_ir.rs
- language/tests/techniques/inner_block/technique.json
- language/tests/techniques/simple_block/technique.json
https://issues.rudder.io/issues/19926
> Fixes #19926: Support reporting logic metadata in language

- webapp/sources/ldap-inventory/inventory-provisioning-core/src/main/scala/com/normation/inventory/ldap/provisioning/DefaultReportSaver.scala
- webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/InventoryMapper.scala
- webapp/sources/scala-ldap/src/main/scala/com/normation/ldap/sdk/LDAPConnection.scala
https://issues.rudder.io/issues/20006
> Fixes #20006: Store processes of an inventory after storing the inventory

- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Rules.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/View.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewCategoryDetails.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRuleDetails.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRulesTable.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewTabContent.elm
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
https://issues.rudder.io/issues/19977
> Fixes #19977: Tags of a rule cannot be deleted

- webapp/sources/ldap-inventory/inventory-provisioning-core/src/main/scala/com/normation/inventory/ldap/provisioning/DefaultInventorySaver.scala
- webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/InventoryMapper.scala
https://issues.rudder.io/issues/20011
> Fixes #20011: Compilation issue on branch 7.0

- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Rules.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRuleDetails.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewTabContent.elm
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
https://issues.rudder.io/issues/19981
> Fixes #19981: Display the name of the groups of a rule instead of their id

- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/DataTypes.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Rules.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/View.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRulesTable.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewUtilsRules.elm
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
https://issues.rudder.io/issues/19971
> Fixes #19971: Make the search bar of the Rules list work

- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NcfApi.scala
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ApiCalls.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/DataTypes.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/Editor.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/JsonDecoder.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/MethodElemUtils.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechnique.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechniqueList.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechniqueTabs.elm
- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
- webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/techniqueEditor.html
https://issues.rudder.io/issues/19985
> Fixes #19985: Make the technique editor more integrated and accessible

- webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/InventoryMapper.scala
https://issues.rudder.io/issues/20027
> Fixes #20027: Compilation issue on branch 6.2

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/EditorTechnique.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
- webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestEditorTechniqueWriter.scala
- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NcfApi.scala
- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/action/CheckNcfTechniqueUpdate.scala
https://issues.rudder.io/issues/20019
> Fixes #20019: Migrate existing techniques to new naming of method  parameters

- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RoleApiMapping.scala
https://issues.rudder.io/issues/20051
> Fixes #20051: Missing rights/role mapping for 7.0 endpoints

- language/src/technique.rs
- language/tests/techniques/CIS/technique.json
- language/tests/techniques/cdt/technique.json
- language/tests/techniques/condition_alias/technique.json
- language/tests/techniques/condition_anybsd/technique.json
- language/tests/techniques/condition_dyn/technique.json
- language/tests/techniques/condition_errorprone/technique.json
- language/tests/techniques/condition_foreign_variable/technique.json
- language/tests/techniques/condition_priority/technique.json
- language/tests/techniques/condition_useless_brackets/technique.json
- language/tests/techniques/conditional_method/technique.json
- language/tests/techniques/deprecated/technique.json
- language/tests/techniques/dsc/technique.json
- language/tests/techniques/duplicated/technique.json
- language/tests/techniques/escaped/technique.json
- language/tests/techniques/inner_block/technique.json
- language/tests/techniques/multiple_simple/technique.json
- language/tests/techniques/parameters/technique.json
- language/tests/techniques/parameters_mult/technique.json
- language/tests/techniques/simple_block/technique.json
- language/tests/techniques/simplest/technique.json
- language/tests/techniques/stateless/technique.json
- language/tests/techniques/supported_formats/technique.json
- language/tools/generate_lib
https://issues.rudder.io/issues/20015
> Fixes #20015: disable reporting in the technique editor does nothing in rudderc

- LICENSE
https://issues.rudder.io/issues/20061
> Fixes #20061: Use standard formatting for GPLv3

- language/libs/oslib.rd
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/MethodConditions.elm
https://issues.rudder.io/issues/20223
> Fixes #20223: Update OS conditions in the technique editor

- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/DataTypes.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/Editor.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewBlock.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewMethod.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechnique.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechniqueTabs.elm
- webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/techniqueEditor.html
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-technique-editor.css
https://issues.rudder.io/issues/19954
> Fixes #19954: it's not possible to reorder method in a block in technique editor

- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/Editor.elm
https://issues.rudder.io/issues/20225
> Fixes #20225: Block clone is not resetting id of blok element

- webapp/sources/rudder/rudder-core/src/main/resources/Migration/dbMigration-6.x-7.0-drop-historization-table.sql
https://issues.rudder.io/issues/20233
> Fixes #20233: create a migration script to remove historization tables

- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/DataTypes.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRuleDetails.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewTabContent.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewUtils.elm
https://issues.rudder.io/issues/20243
> Fixes #20243: Display Groups list in the 'Compliance by nodes' tab

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala
https://issues.rudder.io/issues/20253
> Fixes #20253: improve compliance computation efficiency

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/SystemVariableSpecServiceImpl.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/SystemVariableService.scala
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-500-directives/rules/cfengine-community/rudder.json
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-two-directives/rules/cfengine-community/rudder.json
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-gen-var-def-override/rules/cfengine-community/rudder.json
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-default-install/rudder.json
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/rudder.json
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-one-multipolicy/rudder.json
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-two-directives/rudder.json
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/technique-and-revisions/rudder.json
- webapp/sources/rudder/rudder-templates-cli/src/test/resources/templates1/cf-served.st
- webapp/sources/rudder/rudder-templates-cli/src/test/resources/templates1/variables.json
https://issues.rudder.io/issues/19782
> Fixes #19782: Remove SKIPIDENTIFY system variable

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala
https://issues.rudder.io/issues/20254
> Fixes #20254: same as parent ticket for branch 6.1

- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/Editor.elm
https://issues.rudder.io/issues/20241
> Fixes #20241: Technique draft should be deleted on save

- language/src/error.rs
- language/src/language_lib.rs
- language/src/parser.rs
- language/src/technique.rs
https://issues.rudder.io/issues/19888
> Fixes #19888: technique cannot be compile if name contains \\"x 

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala
https://issues.rudder.io/issues/20257
> Fixes #20257: Automatic merge of perf enhancement breaks compilation

- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ComplianceUtils.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRulesTable.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewTabContent.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewUtils.elm
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
https://issues.rudder.io/issues/20197
> Fixes #20197: Improve compliance bars display in Rules UI

- webapp/sources/pom.xml
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/GitGC.scala
- webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
- webapp/sources/utils/pom.xml
- webapp/sources/utils/src/main/scala/com/normation/utils/CronParser.scala
https://issues.rudder.io/issues/17767
> Fixes #17767: Do a `git gc` periodically

- relay/sources/relayd/deny.toml
https://issues.rudder.io/issues/20269
> Fixes #20269: Vulnerability in tokio

- webapp/sources/api-doc/openapi.src.yml
- webapp/sources/api-doc/paths/scale-out-relay/demote.yml
https://issues.rudder.io/issues/20262
> Fixes #20262: Missing documentation for relay to node demote API

- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechniqueTabs.elm
https://issues.rudder.io/issues/20183
> Fixes #20183: 404 error when opening a technique in the technique editor

- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Init.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewTabContent.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewUtils.elm
- webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/ruleManagement.html
https://issues.rudder.io/issues/19879
> Fixes #19879: Rule editor does not use webapp context path value

- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ComplianceUtils.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/DataTypes.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Init.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewTabContent.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewUtils.elm
- webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/ruleManagement.html
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-datatable.css
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-tags.css
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
https://issues.rudder.io/issues/20236
> Fixes #20236: Make the rows of the compliance tables foldable to show more levels of compliance in Rules UI

- webapp/sources/rudder/rudder-web/src/main/resources/rudder-system-global-parameter.conf
https://issues.rudder.io/issues/20114
> Fixes #20114: add a default value for bind to interface in rudder parameter

- webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
https://issues.rudder.io/issues/20256
> Fixes #20256: Add mock in test lib for secrets eventlogs 

- Jenkinsfile
- Jenkinsfile-security
- api-doc/Dockerfile
- ci/pylint.Dockerfile
- ci/rust.sh
- ci/shellcheck.Dockerfile
- ci/user.sh
- relay/sources/relayd/Dockerfile
- relay/sources/relayd/Makefile
- relay/sources/relayd/README.md
- relay/sources/relayd/src/configuration/main.rs
- relay/sources/relayd/src/output/database.rs
- relay/sources/relayd/tests/files/config/main.conf
- relay/sources/relayd/tests/processing_reporting.rs
- relay/sources/relayd/tools/create-database.sql
- relay/sources/rudder-pkg/Dockerfile
- rudder-lang/Dockerfile
- rudder-lang/Makefile
- rust.makefile
- webapp/sources/Dockerfile
https://issues.rudder.io/issues/20275
> Fixes #20275: Dockerify tests

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala
https://issues.rudder.io/issues/20273
> Fixes #20273: dashboard only shows the compliance of the nodes that really answer when logging on the test platform in 7.0

- Jenkinsfile
- language/Dockerfile
https://issues.rudder.io/issues/20285
> Fixes #20285: Language docs publication does not work

- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/RuleApi.scala
- webapp/sources/rudder/rudder-rest/src/test/resources/api/api_rules.yml
https://issues.rudder.io/issues/20278
> Fixes #20278: Error when creating a rule in 7.0

- webapp/sources/rudder/rudder-core/pom.xml
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/PolicyServerData.scala
https://issues.rudder.io/issues/20289
> Fixes #20289: Can't use rudder with openjdk17: cannot access class sun.net.util.IPAddressUtil

- Jenkinsfile
https://issues.rudder.io/issues/20291
> Fixes #20291: Add redirect to latest API doc version to Jenkinsfile

- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/JsonEncoder.elm
https://issues.rudder.io/issues/20295
> Fixes #20295: Technique editor encoder is not correct with API changes

- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-groups.css
https://issues.rudder.io/issues/20297
> Fixes #20297: by default, group condition should not be displayed

- webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/ruleManagement.html
https://issues.rudder.io/issues/20299
> Fixes #20299: wrong write for rule page 

- webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/ruleManagement.html
https://issues.rudder.io/issues/20298
> Fixes #20298: Redirection does not work on rule page

- Jenkinsfile
https://issues.rudder.io/issues/20320
> Fixes #20320: Split test and build tasks in Jenkins file

- Jenkinsfile
https://issues.rudder.io/issues/20323
> Fixes #20323: Only run compatibility tests during the night

- Jenkinsfile
- Jenkinsfile-security
- ci/asciidoctor.Dockerfile
- ci/shellcheck.Dockerfile
https://issues.rudder.io/issues/20327
> Fixes #20327: Add relayd man page build to Jenkinsfile

- Jenkinsfile
https://issues.rudder.io/issues/20339
> Fixes #20339: Broken 7.0 tests due to missing user_id variable in Jenkinsfile

- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/migration/CheckMigrateSystemTechniques7_0.scala
https://issues.rudder.io/issues/20336
> Fixes #20336: Bad logs for migration error when technique is missing

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/EditorTechnique.scala
https://issues.rudder.io/issues/20333
> Fixes #20333: Wrong deprecation information in technique

- webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/DataTypes.scala
https://issues.rudder.io/issues/20341
> Fixes #20341: Empty value for certificate should not kill rudder

- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewTabContent.elm
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://issues.rudder.io/issues/20286
> Fixes #20286: multiple save buttons on rule page

- docker/rudder-agent/cf-execd.sh
- docker/rudder-relay-split/cf-execd.sh
- docker/rudder-relay/rudder-relay.sh
- relay/arch-doc/rudder-7-communications-security.md
https://issues.rudder.io/issues/20332
> Fixes #20332:  Don't use a passphrase for agent key anymore - rudder  repo

- relay/sources/apache/rudder-apache-relay-ssl.conf
- relay/sources/apache/rudder-vhost.conf
https://issues.rudder.io/issues/20349
> Fixes #20349: Refactor apache configuration for easy separation between agent and web flows

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/GitGC.scala
- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
https://issues.rudder.io/issues/20350
> Fixes #20350: gitgc is always run at start whatever its schedule is and run every 3min42

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/TechniqueAcceptationDatetimeUpdater.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/PolicyServerManagementService.scala
- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/migration/CheckMigrateSystemTechniques7_0.scala
- webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/migration/TestMigrateSystemTechnique7_0.scala
https://issues.rudder.io/issues/20351
> Fixes #20351: System technique migration fails on old server

- relay/sources/rudder-pkg/lib/rudder-pkg/tests/test.py
https://issues.rudder.io/issues/20354
> Fixes #20354: Rudder-pkg tests timeout sometimes

- language/src/technique.rs
- language/src/technique/from_ir.rs
- language/tests/techniques/inner_block/technique.json
- language/tests/techniques/simple_block/technique.json
https://issues.rudder.io/issues/20343
> Fixes #20343:  Add a worst-case, weighted sum for block compliance mode - rudderc

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/StatusReports.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingService.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala
- webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala
- webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala
- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/AsyncComplianceService.scala
https://issues.rudder.io/issues/20318
> Fixes #20318: Improve performance of getUserAndSystemNodeStatusReports by exploring only once cache

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingService.scala
- webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala
- webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala
- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
https://issues.rudder.io/issues/20380
> Fixes #20380: upmerge of parent ticket broke 7.0

- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://issues.rudder.io/issues/20384
> Fixes #20384: User name invisible

- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/ShowNodeDetailsFromNode.scala
- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ComplianceData.scala
- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala
https://issues.rudder.io/issues/20383
> Fixes #20383: Non system technique appears in "System status tab"

- webapp/sources/rudder/rudder-web/src/main/elm/onboarding/sources/Init.elm
https://issues.rudder.io/issues/20394
Before:
After:
> Fixes #20394: Remove metrics section from wizard

- webapp/sources/rudder/rudder-core/pom.xml
- webapp/sources/rudder/rudder-rest/pom.xml
https://issues.rudder.io/issues/20410
> Fixes #20410: Rudder build when skipping tests

- Jenkinsfile
https://issues.rudder.io/issues/20408
> Fixes #20408: Discard old builds

- relay/sources/relayd/tests/default_configuration.rs
https://issues.rudder.io/issues/20416
> Fixes #20416: Test that the distributed config files are valid

- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
- webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/NodeGroupForm.html
https://issues.rudder.io/issues/20293
> Fixes #20293: group page is not scrollable, so we can't see the full list of nodes in 7.0

- webapp/sources/pom.xml
https://issues.rudder.io/issues/20421
> Fixes #20421: Upgrade logback version for LOGBACK-1591 / JNDI

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/DynGroupService.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/LdapQueryProcessor.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/QueryProcessor.scala
- webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestPendingNodePolicies.scala
- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
- webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
https://issues.rudder.io/issues/20281
> Fixes #20281: Query seems to be ignored for pendings nodes

- Jenkinsfile
https://issues.rudder.io/issues/20439
> Fixes #20439: Do not skip tests in when publising maven or else we will miss tests jar that are needed to build plugins

- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://issues.rudder.io/issues/20395
> Fixes #20395: css of generation status is dubious in 7.0

- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewCategoryDetails.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewTabContent.elm
https://issues.rudder.io/issues/20365
> Fixes #20365: when we hit enter key on rule category creation,page is reloaded

- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
https://issues.rudder.io/issues/20390
> Fixes #20390: webapp doesn't start after upgrade from 6.2 to 7.0

- webapp/sources/rudder/rudder-web/src/main/webapp/index.html
- webapp/sources/rudder/rudder-web/src/main/webapp/style/login.css
https://issues.rudder.io/issues/19887
> Fixes #19887: icons on login page are not centered

- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-rules.css
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
https://issues.rudder.io/issues/20364
> Fixes #20364: buttons on rule creation page don't have the same width

- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://issues.rudder.io/issues/20030
> Fixes #20030: The left menu is under the menu bar's shadow

- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/DataTypes.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/Editor.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewBlock.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewMethod.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewMethodsList.elm
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-technique-editor.css
https://issues.rudder.io/issues/2034
> Fixes #20344: It's hard to know how to edit a block/method in editor

- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ApiCalls.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/Editor.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechnique.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechniqueTabs.elm
https://issues.rudder.io/issues/20414
> Fixes #20414: Broken technique resources in drafts

- language/tools/generate_lib
https://issues.rudder.io/issues/20471
> Fixes #20471: generate_lib outputs a debug line

- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/DataTypes.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/JsonDecoder.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/JsonEncoder.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Rules.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRuleDetails.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewTabContent.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewUtils.elm
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-rules.css
https://issues.rudder.io/issues/20348
> Fixes #20348: Missing special target in group selection for rules

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/RestDataSerializer.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/policies/RuleTarget.scala
- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/migration/CheckAddSpecialTargetAllPolicyServers.scala
https://issues.rudder.io/issues/20479
> Fixes #20479: error in webapp log at start

- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechnique.elm
https://issues.rudder.io/issues/20488
> Fixes #20488: Wrong technique name displayed in deletion message 

- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechnique.elm
https://issues.rudder.io/issues/20487
> Fixes #20487: Cancel button is missing when deleting a technique

- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechniqueTabs.elm
https://issues.rudder.io/issues/20445
> Fixes #20445: When we move a technique in editor, resources are not moved

- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala
https://issues.rudder.io/issues/20474
> Fixes #20474: error on system status tabs when there are missing reports

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
https://issues.rudder.io/issues/20498
> Fixes #20498: Compliance issue in 7.0 because of invalid expected reports

- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewBlock.elm
https://issues.rudder.io/issues/20306
> Fixes #20306: when trying to put a generic method within a block, it can replace the whole block

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/api/TokenGenerator.scala
https://issues.rudder.io/issues/20512
> Fixes #20512: 

- webapp/sources/rudder/rudder-web/src/main/elm/editor/elm.json
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ApiCalls.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/DataTypes.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/Editor.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/JsonDecoder.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechnique.elm
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-notifications.css
https://issues.rudder.io/issues/20491
Examples:
> Fixes #20491: Error message in technique editor doesn't help

- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ApiCalls.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/Editor.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechniqueTabs.elm
https://issues.rudder.io/issues/20486
> Fixes #20486: Resources in drafts are not displayed and saved

- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewBlock.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewMethod.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechnique.elm
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-technique-editor.css
https://issues.rudder.io/issues/20415
I add a little feedback to see wich method's parameters are mandatory
> Fixes #20415: The technique editor allows saving methods with missing parameters

- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechnique.elm
https://issues.rudder.io/issues/20497
> Fixes #20497: We can save a technique with a missing component name for a nested block

- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/Compliance.scala
https://issues.rudder.io/issues/20531
> Fixes #20531: Compliance api miss audit state

- webapp/sources/rudder/rudder-web/src/main/elm/rules/elm.json
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewUtils.elm
https://issues.rudder.io/issues/20532
> Fixes #20532: Missing rounding of rules compliance percentage

- relay/sources/relayd/Cargo.lock
- relay/sources/relayd/Cargo.toml
- relay/sources/relayd/src/api/shared_folder.rs
https://issues.rudder.io/issues/20473
> Fixes #20473: Update relayd dependencies

- relay/sources/relayd/deny.toml
https://issues.rudder.io/issues/20533
> Fixes #20533: Fix relayd dependency checks  after update

- language/src/generator/cfengine/syntax.rs
- language/tests/helpers/s_ntp.rd.cf
- language/tests/techniques/CIS/technique.cf
- language/tests/techniques/cdt/technique.cf
- language/tests/techniques/condition_alias/technique.cf
- language/tests/techniques/condition_anybsd/technique.cf
- language/tests/techniques/condition_dyn/technique.cf
- language/tests/techniques/condition_errorprone/technique.cf
- language/tests/techniques/condition_foreign_variable/technique.cf
- language/tests/techniques/condition_priority/technique.cf
- language/tests/techniques/condition_useless_brackets/technique.cf
- language/tests/techniques/conditional_method/technique.cf
- language/tests/techniques/duplicated/technique.cf
- language/tests/techniques/escaped/technique.cf
- language/tests/techniques/inner_block/technique.cf
- language/tests/techniques/multiple_simple/technique.cf
- language/tests/techniques/parameters/technique.cf
- language/tests/techniques/parameters_mult/technique.cf
- language/tests/techniques/simple_block/technique.cf
- language/tests/techniques/stateless/technique.cf
- language/tests/techniques/supported_formats/technique.cf
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
- webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestEditorTechniqueWriter.scala
https://issues.rudder.io/issues/20513
> Fixes #20513: Sometimes the webapp fails to generate the reporting file of new techniques

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/LdapQueryProcessor.scala
- webapp/sources/scala-ldap/src/main/scala/com/normation/ldap/sdk/LDAPEntry.scala
https://issues.rudder.io/issues/20535
> Fixes #20535: We are recreating ldap object while we could duplicate them, leading to suboptimal perf

- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-directives.css
- webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentDirectiveEditForm.html
https://issues.rudder.io/issues/20436
> Fixes #20436: In a directive the technique documentation button is not visibled enough

- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRuleDetails.elm
https://issues.rudder.io/issues/19789
> Fixes #19789: we can save a rule without a name

- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/appconfig/ConfigService.scala
- webapp/sources/rudder/rudder-rest/src/test/resources/api/api_settings.yml
https://issues.rudder.io/issues/20529
> Fixes #20529: Disable rudderc compilation of technique editor technique

- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRepairedReports.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewTabContent.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewUtils.elm
https://issues.rudder.io/issues/20467
> Fixes #20467: Tables look weird when empty in Rules UI

- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/DataTypes.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/Editor.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechniqueList.elm
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
https://issues.rudder.io/issues/20493
> Fixes #20493: Add loading effect for technique editor tree 

- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/ncf/TechniqueReader.scala
- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/TechniqueApi.scala
- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/action/CheckNcfTechniqueUpdate.scala
https://issues.rudder.io/issues/20552
> Fixes #20552: Speed up technique editor

- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewUtils.elm
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-progress-bar.css
https://issues.rudder.io/issues/20553
> Fixes #20553: Regression on displaying small percent in compliance bar

- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/Compliance.scala
https://issues.rudder.io/issues/20490
> Fixes #20490: Compliance by nodes in the Rules page shows the node id rather than it's name

- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
https://issues.rudder.io/issues/20561
> Fixes #20561: error in upmerge from parent ticket

- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RoleApiMapping.scala
https://issues.rudder.io/issues/20567
> Fixes #20567: It is impossible to read group properties with a read-only account

- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/DataTypes.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Rules.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewTabContent.elm
- webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/ruleManagement.html
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-rules.css
https://issues.rudder.io/issues/19876
> Fixes #19876: Missing rule Id in rule details

- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/DataTypes.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/Editor.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewBlock.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewMethod.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechnique.elm
https://issues.rudder.io/issues/20551
> Fixes #20551: block still disapear in technique editor when we put a method in it

- webapp/sources/api-doc/code_samples/curl/nodes/all.sh
https://issues.rudder.io/issues/20577
> Fixes #20577: Add a complex example of node search API request

- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/DataTypes.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/Editor.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewBlock.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewMethod.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechnique.elm
- webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/techniqueEditor.html
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-technique-editor.css
https://issues.rudder.io/issues/20420
> Fixes #20420: It's not possible to select a condition with the dropdownlist on technique editor in rudder 7

- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/NodeDetailLevel.scala
- webapp/sources/rudder/rudder-rest/src/test/resources/api/api_nodes.yml
https://issues.rudder.io/issues/20582
> Fixes #20582: State is missing from node api

- api-doc/Dockerfile
https://issues.rudder.io/issues/20584
> Fixes #20584: Update api-doc tooling

- webapp/sources/rudder/rudder-web/src/main/webapp/index.html
- webapp/sources/rudder/rudder-web/src/main/webapp/style/login.css
https://issues.rudder.io/issues/20596
> Fixes #20596: Underlining of links is cut in firefox

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
https://issues.rudder.io/issues/20591
> Fixes #20591: No na reporting generated by webapp

- webapp/sources/api-doc/components/schemas/settings.yml
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala
- webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ExecutionBatchTest.scala
- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/appconfig/ConfigService.scala
- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SettingsApi.scala
- webapp/sources/rudder/rudder-rest/src/test/resources/api/api_settings.yml
- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PropertiesManagement.scala
- webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/policyServerManagement.html
https://issues.rudder.io/issues/20540
> Fixes #20540: Unexpected reports when using nested blocks

- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/DataTypes.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Init.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Rules.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/View.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewUtils.elm
https://issues.rudder.io/issues/20595
> Fixes #20595: Loading effect on rules tree

- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/RuleApi.scala
https://issues.rudder.io/issues/20606
> Fixes #20606: Remove warning messages

- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ComplianceUtils.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewUtils.elm
https://issues.rudder.io/issues/20573
> Fixes #20573: Compliance of rules should not be rounded to the nearest hundredth

- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RoleApiMapping.scala
https://issues.rudder.io/issues/20609
> Fixes #20609: Missing api rights 

- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/DataTypes.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/Editor.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechniqueList.elm
https://issues.rudder.io/issues/2049
> Fixes #20492: Expand/Hide in technique editor tree not working

- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewMethodsList.elm
https://issues.rudder.io/issues/20608
> Fixes #20608: generic method doc in technique editor in 7.0 doesn't look great

- webapp/sources/rudder/rudder-core/src/test/resources/ldap-data/inventory-sample-data.ldif
- webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala
https://issues.rudder.io/issues/20622
> Fixes #20622: Add a unit test for vm memory search

- webapp/sources/rudder/rudder-web/src/main/elm/onboarding/sources/View.elm
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-wizard.css
https://issues.rudder.io/issues/20616
> Fixes #20616: Change the buttons color in the setup wizard

- relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
https://issues.rudder.io/issues/20649
> Fixes #20649: rudder-pkg can not parse nightly version

- relay/sources/relayd/Cargo.lock
https://issues.rudder.io/issues/20639
> Fixes #20639: Data race in thread-local relayd dependency

- webapp/sources/api-doc/introduction.md
https://issues.rudder.io/issues/10915
> Fixes #10915: No clear error message when calling api with curl and data are not url-encoded

- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/Editor.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechniqueList.elm
https://issues.rudder.io/issues/20454
> Fixes #20454: Selected technique is wrong after cloning

- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechniqueTabs.elm
https://issues.rudder.io/issues/2045
> Fixes #20453: Categories in the technique editor are flattened

- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/Editor.elm
https://issues.rudder.io/issues/20631
> Fixes #20631: Draft infos remaining after deletion 

- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/View.elm
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-rules.css
https://issues.rudder.io/issues/2063
> Fixes #20630: Highlight the rule on the tree when display details

- webapp/sources/api-doc/introduction.md
https://issues.rudder.io/issues/20654
> Fixes #20654: Missing v14 api description for 7.0

- relay/sources/relayd/Cargo.lock
https://issues.rudder.io/issues/20668
> Fixes #20668:  Data race in thread-local relayd dependency - 7.0

- webapp/sources/pom.xml
https://issues.rudder.io/issues/20676
> Fixes #20676: Update xerces version 

- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/Editor.elm
- webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/techniqueEditor.html
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-technique-editor.css
https://issues.rudder.io/issues/20557
> Fixes #20557: Tooltips remains when we remove a generic method

- relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
https://issues.rudder.io/issues/20392
> Fixes #20392: In 6.2.10 the plugin can not uninstall itself in some cases

- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Rules.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewTabContent.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewUtils.elm
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-rules.css
https://issues.rudder.io/issues/20625
> Fixes #20625: Improve directives and groups selection in Rules UI

- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewUtils.elm
https://issues.rudder.io/issues/20501
> Fixes #20501: Tooltip on enforce/audit label in rules tree not working

- language/docs/assets/css/rudder.css
- language/docs/index.adoc
- language/docs/usage.adoc
https://issues.rudder.io/issues/20729
> Fixes #20729: Style fixes in language doc

- Jenkinsfile
- webapp/sources/api-doc/introduction.md
- webapp/sources/api-doc/openapi.src.yml
https://issues.rudder.io/issues/20737
> Fixes #20737: Prepare 7.1 API doc

- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/Editor.elm
https://issues.rudder.io/issues/20703
> Fixes #20703: cloning a generic method creates the method at the end of the technique

- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewTabContent.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewUtils.elm
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
https://issues.rudder.io/issues/20713
> Fixes #20713: when a rule is disabled we cannot see its associated directives

- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewBlock.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewMethod.elm
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-technique-editor.css
https://issues.rudder.io/issues/20679
> Fixes #20679: Broken hover when condition is long

- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala
- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleEditForm.scala
- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala
- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/TechniqueLibraryManagement.scala
- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala
- webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/groupManagement.js
- webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/ruleDirectives.js
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-rules.css
- webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentRuleEditForm.html
https://issues.rudder.io/issues/18672
> Fixes #18672: when there's a disabled directive in a rule, it's really hard to see

- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/Editor.elm
https://issues.rudder.io/issues/20710
> Fixes #20710: Creating a technique with a name normalized to generic method id breaks technique editor

- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/DataTypes.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Rules.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewTabContent.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewUtils.elm
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-rules.css
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
https://issues.rudder.io/issues/20753
> Fixes #20753: Add a link on the Directives and Groups to their own page

- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ApiCalls.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/Editor.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/JsonEncoder.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechnique.elm
https://issues.rudder.io/issues/20184
> Fixes #20184: Ressource not found when creating a draft and comming back to it to save it as a technique

- webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
- webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/SystemApiTest.scala
- webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TestRestFromFileDef.scala
- webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TraitTestApiFromYamlFiles.scala
https://issues.rudder.io/issues/20759
> Fixes #20759: Factor out trait for api test in yaml

- language/tools/generate_lib
https://issues.rudder.io/issues/20761
> Fixes #20761: In some cases, generate_lib rudder-lang utility does throw exception instead of properly parsing the error

- language/docs/statements-and-expressions.adoc
https://issues.rudder.io/issues/20762
> Fixes #20762: Add block syntax in the rudder-lang documentation

- Jenkinsfile
https://issues.rudder.io/issues/20772
> Fixes #20772: Missing clean in webapp publish

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PolicyWriterService.scala
https://issues.rudder.io/issues/20796
> Fixes #20796: Change back group permissions

- webapp/sources/rudder/rudder-core/src/main/resources/Migration/dbMigration-7.0-7.1-serial_to_reporid_change.sql
https://issues.rudder.io/issues/20797
> Fixes #20797: Missing migration script for serial -> reportId column

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/policies/RuleTarget.scala
- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/ExpectedPolicyPopup.scala
https://issues.rudder.io/issues/20736
> Fixes #20736: List of directive for the pending node is invalid

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/queries/CmdbQuery.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/CmdbQueryParser.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/LdapQueryProcessor.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/PolicyServerManagementService.scala
- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/SearchNodeComponent.scala
https://issues.rudder.io/issues/20802
> Fixes #20802: NodeAndPolicyServerReturnType name is misleading for search that include root server

- language/src/generator/cfengine.rs
- language/src/generator/cfengine/syntax.rs
- language/tests/techniques/CIS/technique.cf
- language/tests/techniques/cdt/technique.cf
- language/tests/techniques/condition_alias/technique.cf
- language/tests/techniques/condition_anybsd/technique.cf
- language/tests/techniques/condition_dyn/technique.cf
- language/tests/techniques/condition_errorprone/technique.cf
- language/tests/techniques/condition_foreign_variable/technique.cf
- language/tests/techniques/condition_priority/technique.cf
- language/tests/techniques/condition_useless_brackets/technique.cf
- language/tests/techniques/conditional_method/technique.cf
- language/tests/techniques/deprecated/technique.cf
- language/tests/techniques/dsc/technique.cf
- language/tests/techniques/duplicated/technique.cf
- language/tests/techniques/escaped/technique.cf
- language/tests/techniques/inner_block/technique.cf
- language/tests/techniques/multiple_simple/technique.cf
- language/tests/techniques/parameters/technique.cf
- language/tests/techniques/parameters_mult/technique.cf
- language/tests/techniques/simple_block/technique.cf
- language/tests/techniques/simplest/technique.cf
- language/tests/techniques/stateless/technique.cf
- language/tests/techniques/supported_formats/technique.cf
https://issues.rudder.io/issues/20785
> Fixes #20785:  Use a unique id to identify reports - rudderc

- Jenkinsfile
https://issues.rudder.io/issues/20812
> Fixes #20812: Don't skip tests in webapp publish

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
- webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestTechniqueWriter.scala
https://issues.rudder.io/issues/19006
> Fixes #19006: Suppressed techniques coming back to life forever

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/ExpectedReports.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala
- webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ExecutionBatchTest.scala
https://issues.rudder.io/issues/20808
> Fixes #20808: Missing reports with a reportid are missing in compliance

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/StatusReports.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala
- webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ExecutionBatchTest.scala
https://issues.rudder.io/issues/20815
> Fixes #20815: Ensure variable in component name and values are OK

- webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/JsonSerializers.scala
- webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/NodeInventory.scala
- webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/FusionInventoryParser.scala
- webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-inventories/rudder-tag/one-agent-full.ocs
- webapp/sources/ldap-inventory/inventory-fusion/src/test/scala/com/normation/inventory/provisioning/fusion/TestReportParsing.scala
- webapp/sources/ldap-inventory/inventory-repository/src/test/scala/com/normation/inventory/ldap/core/TestInventory.scala
- webapp/sources/ldap-inventory/inventory-repository/src/test/scala/com/normation/inventory/ldap/core/TestNodeUnserialisation.scala
- webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ExecutionBatchTest.scala
- webapp/sources/rudder/rudder-rest/src/test/resources/api/api_nodes.yml
- webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
https://issues.rudder.io/issues/20819
> Fixes #20819: Persist severity, description, date and id in software update

- webapp/sources/rudder/rudder-web/src/main/elm/accounts/build-dev.sh
- webapp/sources/rudder/rudder-web/src/main/elm/accounts/elm.json
- webapp/sources/rudder/rudder-web/src/main/elm/accounts/sources/Accounts.elm
- webapp/sources/rudder/rudder-web/src/main/elm/accounts/sources/ApiCalls.elm
- webapp/sources/rudder/rudder-web/src/main/elm/accounts/sources/DataTypes.elm
- webapp/sources/rudder/rudder-web/src/main/elm/accounts/sources/DatePickerUtils.elm
- webapp/sources/rudder/rudder-web/src/main/elm/accounts/sources/Init.elm
- webapp/sources/rudder/rudder-web/src/main/elm/accounts/sources/JsonDecoder.elm
- webapp/sources/rudder/rudder-web/src/main/elm/accounts/sources/JsonEncoder.elm
- webapp/sources/rudder/rudder-web/src/main/elm/accounts/sources/View.elm
- webapp/sources/rudder/rudder-web/src/main/elm/accounts/sources/ViewModals.elm
- webapp/sources/rudder/rudder-web/src/main/elm/accounts/sources/ViewUtils.elm
- webapp/sources/rudder/rudder-web/src/main/elm/build-app.sh
- webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/apiManagement.html
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-datatable.css
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-elm-datepicker.css
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
https://issues.rudder.io/issues/20683
> Fixes #20683: Rewrite the API account page in Elm

- webapp/sources/api-doc/code_samples/curl/settings/set-allowed-networks-diff.sh
https://issues.rudder.io/issues/20844
> Fixes #20844: Broken allowed network curl example

- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RudderJsonResponse.scala
- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/DirectiveApi.scala
- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/GroupsApi.scala
- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ParametersApi.scala
- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/RuleApi.scala
- webapp/sources/rudder/rudder-rest/src/test/resources/api/api_directives.yml
https://issues.rudder.io/issues/20871
> Fixes #20871: Some api response have an id field but should'nt have one

- relay/sources/relayd/Cargo.lock
https://issues.rudder.io/issues/20872
> Fixes #20872: Vulnerability in the regex crate

- rudder-lang/Cargo.lock
https://issues.rudder.io/issues/20873
> Fixes #20873:  Vulnerability in the regex crate - rudderc

- webapp/sources/rudder/rudder-core/src/main/resources/Migration/dbMigration-7.0-7.1-serial_to_reportid_change.sql
https://issues.rudder.io/issues/20876
> Fixes #20876: serial needs also to me renamed in archivesysevents table

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/queries/CmdbQuery.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/LdapQueryProcessor.scala
https://issues.rudder.io/issues/20874
> Fixes #20874: Compilation warning on branche 6.2

- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewTabContent.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewUtils.elm
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
https://issues.rudder.io/issues/20856
> Fixes #20856: Applied directive doesn't show up when there is no node

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/BuildBundleSequence.scala
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-500-directives/rules/cfengine-community/rudder-directives.cf
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-500-directives/rules/cfengine-community/rudder-system-directives.cf
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-two-directives/rules/cfengine-community/rudder-directives.cf
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-two-directives/rules/cfengine-community/rudder-system-directives.cf
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-gen-var-def-override/rules/cfengine-community/rudder-directives.cf
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-gen-var-def-override/rules/cfengine-community/rudder-system-directives.cf
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-default-install/rudder-system-directives.cf
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/rudder-system-directives.cf
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-one-multipolicy/rudder-directives.cf
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-one-multipolicy/rudder-system-directives.cf
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-two-directives/rudder-directives.cf
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-two-directives/rudder-system-directives.cf
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/technique-and-revisions/rudder-directives.cf
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/technique-and-revisions/rudder-system-directives.cf
https://issues.rudder.io/issues/20883
> Fixes #20883: Built in Techniques using generic methods have no reports with new report id

- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/DataTypes.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Init.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Rules.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/View.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRulesTable.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewUtils.elm
- webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/ruleManagement.html
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-rules.css
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
https://issues.rudder.io/issues/20848
> Fixes #20848: We cannot filter rules by tag anymore

- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-datatable.css
https://issues.rudder.io/issues/20693
> Fixes #20693: Glitch in node compliance details

- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewUtils.elm
https://issues.rudder.io/issues/20782
> Fixes #20782: Wrong redirect url for system group in rule page

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/nodeconfig/NodeConfigurationCacheRepository.scala
- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/comet/AsyncDeployment.scala
https://issues.rudder.io/issues/20926
> Fixes #20926: Starting policy generation by hand fails if node-configuration-hashes.json 

- webapp/sources/api-doc/components/schemas/node-full.yml
https://issues.rudder.io/issues/20947
> Fixes #20947: Add new software update fields to API doc

- webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentNodeProperties.html
https://issues.rudder.io/issues/20951
> Fixes #20951: Remove the transparent div that covers the Properties tab and prevents interaction with it.

- language/src/generator/dsc/syntax.rs
- language/tests/techniques/CIS/technique.ps1
- language/tests/techniques/cdt/technique.ps1
- language/tests/techniques/condition_alias/technique.ps1
- language/tests/techniques/condition_dyn/technique.ps1
- language/tests/techniques/condition_errorprone/technique.ps1
- language/tests/techniques/condition_foreign_variable/technique.ps1
- language/tests/techniques/condition_priority/technique.ps1
- language/tests/techniques/condition_useless_brackets/technique.ps1
- language/tests/techniques/conditional_method/technique.ps1
- language/tests/techniques/deprecated/technique.ps1
- language/tests/techniques/dsc/technique.ps1
- language/tests/techniques/duplicated/technique.ps1
- language/tests/techniques/escaped/technique.ps1
- language/tests/techniques/inner_block/technique.ps1
- language/tests/techniques/multiple_simple/technique.ps1
- language/tests/techniques/parameters/technique.ps1
- language/tests/techniques/parameters_mult/technique.ps1
- language/tests/techniques/simple_block/technique.ps1
- language/tests/techniques/simplest/technique.ps1
- language/tests/techniques/stateless/technique.ps1
- language/tests/techniques/supported_formats/technique.ps1
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/1.0/technique.ps1
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/2.0/technique.ps1
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/technique.ps1
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_with_blocks/1.0/technique.ps1
https://issues.rudder.io/issues/20897
> Fixes #20897: "Disable reporting" for windows method calls does produce unexpected reports

- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Rules.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRuleDetails.elm
https://issues.rudder.io/issues/20954
> Fixes #20954: Edit mode should be enabled by default when creating a rule

- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewTabContent.elm
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
https://issues.rudder.io/issues/20692
> Fixes #20692: Displays a warning icon for directives that are not used by any rule.

- webapp/sources/pom.xml
https://issues.rudder.io/issues/20969
> Fixes #20969: 

- webapp/sources/pom.xml
https://issues.rudder.io/issues/20972
> Fixes #20972: 

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/domain/TechniqueVersion.scala
https://issues.rudder.io/issues/20976
> Fixes #20976: Show more details in exception when parsing an invalid technique version

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/1.0/technique.ps1
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/2.0/technique.ps1
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/technique.ps1
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_with_blocks/1.0/technique.ps1
https://issues.rudder.io/issues/20978
> Fixes #20978: Fix report parameter in dsc techniques

- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/MethodConditions.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewBlock.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewMethod.elm
https://issues.rudder.io/issues/20973
> Fixes #20973: Correct minor version condition for Ubuntu in technique editor

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/StatusReports.scala
- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ComplianceData.scala
https://issues.rudder.io/issues/20880
> Fixes #20880: Removed report in compliance when calling several times the command_execution with same value

- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/DataTypes.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/Editor.elm
https://issues.rudder.io/issues/21001
> Fixes #21001: When cloning a block with two identical methods, only one is cloned

- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/Editor.elm
https://issues.rudder.io/issues/20787
> Fixes #20787: Unable to open a block within a block when it has just been drop from the list 

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/StatusReports.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala
- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala
https://issues.rudder.io/issues/21000
> Fixes #21000: Bad number of component for 2 block with same name same content

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
- webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeExpectedReportTest.scala
https://issues.rudder.io/issues/21007
> Fixes #21007: Techniques with no component define have no reporting

- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/Editor.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewMethodsList.elm
- webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/techniqueEditor.html
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-technique-editor.css
https://issues.rudder.io/issues/21016
> Fixes #21016: The display of the DSC icon is broken in the technical editor

- webapp/sources/pom.xml
https://issues.rudder.io/issues/21022
> Fixes #21022: Update spring and logback version because of new CVE

- webapp/sources/dependency-check-suppression.xml
https://issues.rudder.io/issues/21027
> Fixes #21027: Ignore CVEs for spring-ldap-core

- webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/homePage.js
https://issues.rudder.io/issues/17728
> Fixes #17728: List of nodes by version does not include windows nodes

- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewMethodsList.elm
https://issues.rudder.io/issues/21055
> Fixes #21055: DSC icon display is broken

- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRulesTable.elm
https://issues.rudder.io/issues/21010
> Fixes #21010: Sort by status does not work on rules table

- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/ModificationValidationPopup.scala
- webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder.js
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder.css
https://issues.rudder.io/issues/21052
> Fixes #21052: Update css related to the change validation plugin

- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-two-directives/rudder-directives.cf
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/technique-and-revisions/rudder-directives.cf
- webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
https://issues.rudder.io/issues/21065
> Fixes #21065: broken test after 20929

- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/DataTypes.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Init.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Rules.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/View.elm
https://issues.rudder.io/issues/2107
> Fixes #21079: Fold and unfold all categories button not working in rules page

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/BuildBundleSequence.scala
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-500-directives/rules/cfengine-community/rudder-directives.cf
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-500-directives/rules/cfengine-community/rudder-system-directives.cf
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-two-directives/rules/cfengine-community/rudder-directives.cf
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-two-directives/rules/cfengine-community/rudder-system-directives.cf
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-gen-var-def-override/rules/cfengine-community/rudder-directives.cf
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-gen-var-def-override/rules/cfengine-community/rudder-system-directives.cf
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-default-install/rudder-system-directives.cf
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/rudder-system-directives.cf
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-one-multipolicy/rudder-directives.cf
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-one-multipolicy/rudder-system-directives.cf
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-two-directives/rudder-directives.cf
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-two-directives/rudder-system-directives.cf
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/technique-and-revisions/rudder-directives.cf
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/technique-and-revisions/rudder-system-directives.cf
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/1.0/technique.cf
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/2.0/technique.cf
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/technique.cf
https://issues.rudder.io/issues/21096
> Fixes #21096: Reporting issues when using multiple directives of the same technique on a node - scala part

- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/HomePage.scala
- webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/homePage.js
- webapp/sources/rudder/rudder-web/src/main/webapp/secure/index.html
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-bootstrap.css
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-dashboard.css
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-progress-bar.css
https://issues.rudder.io/issues/21072
> Fixes #21072: Update the dashboard design with the new graphic charter

- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
https://issues.rudder.io/issues/21077
> Fixes #21077: Don't display oauth/oidc client secret in logs

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/InterpolatedValueCompiler.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchQueryParser.scala
- webapp/sources/utils/src/main/scala/com/normation/utils/Version.scala
https://issues.rudder.io/issues/21107
> Fixes #21107: Scala does not really supports [_:P] syntax

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/domain/TechniqueVersion.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitParseRudderObjects.scala
- webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/write/WriteTechniquesTest.scala
https://issues.rudder.io/issues/21106
> Fixes #21106: Update TechniqueVersion to conform to method visibility

- relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
https://issues.rudder.io/issues/21123
> Fixes #21123: rudder package cannot find version anymore

- relay/sources/rudder-pkg/lib/rudder-pkg/rpkg.py
- relay/sources/rudder-pkg/lib/rudder-pkg/tests/testPluginVersion.py
https://issues.rudder.io/issues/21121
> Fixes #21121: rudder package does not sort plugin version correctly

- webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/NodeInventory.scala
- webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/FusionInventoryParser.scala
- webapp/sources/ldap-inventory/inventory-fusion/src/test/scala/com/normation/inventory/provisioning/fusion/TestReportParsing.scala
- webapp/sources/ldap-inventory/inventory-repository/src/test/scala/com/normation/inventory/ldap/core/TestInventory.scala
- webapp/sources/ldap-inventory/inventory-repository/src/test/scala/com/normation/inventory/ldap/core/TestNodeUnserialisation.scala
- webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
https://issues.rudder.io/issues/21152
> Fixes #21152: Support optionnal fields in software updates

- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewMethodsList.elm
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-technique-editor.css
https://issues.rudder.io/issues/21160
> Fixes #21160: Filter on agent type on technique editor is not correctly shown

- contributing/rust.adoc
https://issues.rudder.io/issues/21162
> Fixes #21162: Update Rust dev environment doc

- webapp/sources/dependency-check-suppression.xml
- webapp/sources/pom.xml
https://issues.rudder.io/issues/21169
> Fixes #21169: 

- Jenkinsfile-security
https://issues.rudder.io/issues/21179
> Fixes #21179: security checks fails because of request to sonatype oss index

- relay/sources/relayd/src/api.rs
- relay/sources/relayd/src/api/remote_run.rs
- relay/sources/relayd/src/api/shared_files.rs
- relay/sources/relayd/src/api/shared_folder.rs
- relay/sources/relayd/src/input/watch.rs
- relay/sources/relayd/src/output/database.rs
- relay/sources/relayd/src/output/upstream.rs
- relay/sources/relayd/src/processing/inventory.rs
- relay/sources/relayd/src/processing/reporting.rs
https://issues.rudder.io/issues/21157
> Fixes #21157: Huge broken logs in relayd

- language/deny.toml
https://issues.rudder.io/issues/21181
> Fixes #21181: Allow BSD-3-Clause dependencies for rudderc

- webapp/sources/rudder/rudder-web/src/main/elm/build.sh
https://issues.rudder.io/issues/21180
> Fixes #21180: Improve elm build consistency with plugins

- Jenkinsfile
- webapp/sources/Dockerfile
- webapp/sources/rudder/rudder-web/src/main/elm/build-app.sh
https://issues.rudder.io/issues/21156
> Fixes #21156: Race condition between elm builds

- relay/sources/relayd/Cargo.toml
- relay/sources/relayd/src/output/database.rs
https://issues.rudder.io/issues/21201
> Fixes #21201: Allow passing options to postgresql connection URL

- relay/sources/relayd/deny.toml
https://issues.rudder.io/issues/21218
> Fixes #21218: Dependency vuln in 7.2

- api-doc/Dockerfile
https://issues.rudder.io/issues/21232
> Fixes #21232: Update api doc tooling

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/JsonResponseObjects.scala
- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/ApiDatastructures.scala
- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RoleApiMapping.scala
- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/HookApi.scala
- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SystemApi.scala
- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
https://issues.rudder.io/issues/21082
> Fixes #21082: List of hooks API

- CONTRIBUTING.adoc
- contributing/fsharp.adoc
https://issues.rudder.io/issues/21259
> Fixes #21259: Add docs about F# dev environment

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/GitTechniqueReader.scala
https://issues.rudder.io/issues/21260
> Fixes #21260: GetMetadataContent does not correctly retrieve content when a revision is given

- webapp/sources/dependency-check-suppression.xml
https://issues.rudder.io/issues/21263
> Fixes #21263: 

- webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
https://issues.rudder.io/issues/21253
> Fixes #21253: Query string is not correctly parsed in test API framework

- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://issues.rudder.io/issues/18918
> Fixes #18918: Missing icon in technical logs for error messages

- relay/sources/relayd/src/processing/inventory.rs
https://issues.rudder.io/issues/21270
> Fixes #21270: Allow .ocs files as inventory

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/JsonResponseObjects.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/EditorTechnique.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/action/CheckNcfTechniqueUpdate.scala
https://issues.rudder.io/issues/21220
> Fixes #21220: When upgrading to 7.1, techniques are not upgraded to the new format and reporting issue occur

- Jenkinsfile
- qa-test
- relay/sources/relayd/src/configuration/main.rs
https://issues.rudder.io/issues/21280
> Fixes #21280: Ignore rudderc/repos in tests

- webapp/sources/api-doc/components/schemas/categories-tree.yml
- webapp/sources/api-doc/paths/techniques/all.yml
- webapp/sources/api-doc/paths/techniques/id-version.yml
- webapp/sources/api-doc/paths/techniques/revisions.yml
- webapp/sources/api-doc/paths/techniques/versions.yml
https://issues.rudder.io/issues/21290
> Fixes #21290: Fix typos in techniques API doc

- policies/rudderc/Makefile
https://issues.rudder.io/issues/21302
> Fixes #21302: Wrong target for rudderc install

- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/plugins/PublicPlugin.scala
https://issues.rudder.io/issues/21319
> Fixes #21319: Allow plugins to have multiple menu entries

- webapp/sources/rudder/rudder-web/src/main/elm/hooks/build-dev.sh
- webapp/sources/rudder/rudder-web/src/main/elm/hooks/elm.json
- webapp/sources/rudder/rudder-web/src/main/elm/hooks/sources/ApiCalls.elm
- webapp/sources/rudder/rudder-web/src/main/elm/hooks/sources/DataTypes.elm
- webapp/sources/rudder/rudder-web/src/main/elm/hooks/sources/Hooks.elm
- webapp/sources/rudder/rudder-web/src/main/elm/hooks/sources/Init.elm
- webapp/sources/rudder/rudder-web/src/main/elm/hooks/sources/JsonDecoder.elm
- webapp/sources/rudder/rudder-web/src/main/elm/hooks/sources/JsonEncoder.elm
- webapp/sources/rudder/rudder-web/src/main/elm/hooks/sources/View.elm
- webapp/sources/rudder/rudder-web/src/main/elm/hooks/sources/ViewUtils.elm
- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
- webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/hooksManagement.html
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-hooks.css
https://issues.rudder.io/issues/21083
> Fixes #21083: Provide a page to list the different hooks of a Rudder server

- webapp/sources/rudder/rudder-rest/src/test/resources/api/api_nodes_properties.yml
https://issues.rudder.io/issues/21336
> Fixes #21336: Tests fail due to policy mode definition in MockServices

- webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
https://issues.rudder.io/issues/21330
> Fixes #21330: Change default behavior from moving node inventories to archive branch to erasing them

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala
https://issues.rudder.io/issues/21352
> Fixes #21352: In HTTPS mode, we may have errors in logs about duplicate messages that are totally legit

- webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
https://issues.rudder.io/issues/21350
> Fixes #21350: Missing comment in configuration.properties.sample

- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/View.elm
https://issues.rudder.io/issues/21171
> Fixes #21171: Cancel button not showed within disable rule menu 

- relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py
- relay/sources/rudder-pkg/rudder-pkg
https://issues.rudder.io/issues/21316
> Fixes #21316: rudder package command should install multiple plugins at once

- qa-test
https://issues.rudder.io/issues/21364
> Fixes #21364: Ignore rudder-lang repos in script checks

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/JsonResponseObjects.scala
https://issues.rudder.io/issues/21355
> Fixes #21355: Remove unused variable newCall in JRTechniqueElem

- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
https://issues.rudder.io/issues/21402
> Fixes #21402: Restrict rights for rudder-web.properties.d

- api-doc/Dockerfile
- webapp/sources/api-doc/introduction.md
- webapp/sources/api-doc/openapi.src.yml
https://issues.rudder.io/issues/21410
> Fixes #21410:  Prepare API doc for 7.2

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitArchivers.scala
https://issues.rudder.io/issues/21430
> Fixes #21430: technique from technique editor not commited in git

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/Reports.scala
https://issues.rudder.io/issues/21435
> Fixes #21435: rudder don't understand the new reports generated for system update

- policies/Dockerfile
- policies/rust-toolchain.toml
- relay/sources/relayd/Dockerfile
- relay/sources/relayd/rust-toolchain.toml
- relay/sources/relayd/src/api/system.rs
- relay/sources/relayd/src/data/report.rs
- relay/sources/relayd/src/data/runlog.rs
https://issues.rudder.io/issues/21440
> Fixes #21440: Update Rust to 1.62.1

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryFileWatcher.scala
https://issues.rudder.io/issues/21423
> Fixes #21423: error when processing inventories in 7.2

- webapp/sources/rudder/rudder-web/src/main/elm/healthcheck/elm.json
- webapp/sources/rudder/rudder-web/src/main/elm/notifications/elm.json
https://issues.rudder.io/issues/21443
> Fixes #21443: 

- webapp/sources/rudder/rudder-web/src/main/webapp/WEB-INF/web.xml
https://issues.rudder.io/issues/21445
> Fixes #21445: 

- webapp/sources/rudder/rudder-web/src/main/elm/editor/elm.json
- webapp/sources/rudder/rudder-web/src/main/elm/onboarding/elm.json
- webapp/sources/rudder/rudder-web/src/main/elm/rules/elm.json
https://issues.rudder.io/issues/21450
> Fixes #21450: 

- webapp/sources/rudder/rudder-web/src/main/elm/accounts/elm.json
https://issues.rudder.io/issues/21453
> Fixes #21453: 

- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/NodeGrid.scala
- webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
https://issues.rudder.io/issues/21452
> Fixes #21452: 

- webapp/sources/rudder/rudder-web/src/main/elm/hooks/elm.json
https://issues.rudder.io/issues/21455
> Fixes #21455: 

- webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder.js
https://issues.rudder.io/issues/21457
> Fixes #21457: 

- webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
https://issues.rudder.io/issues/21458
> Fixes #21458: JS escape in tags

- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
https://issues.rudder.io/issues/21449
> Fixes #21449: 

- webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder.js
https://issues.rudder.io/issues/21461
> Fixes #21461: 

- webapp/sources/rudder/rudder-core/src/main/resources/reportsSchema.sql
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/CampaignEventRepository.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/CampaignRepository.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/DataTypes.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/JsonCampaignSerializer.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/MainCampaignService.scala
- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/CampaignApi.scala
- webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
- webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/CampaignApiTests.scala
- webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
https://issues.rudder.io/issues/21418
> Fixes #21418: Campaign scheduler seems to not look for existing campaign at boot

- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/LiftSpringSecurityFilter.scala
https://issues.rudder.io/issues/21463
> Fixes #21463: URL with "%3B" (ie ';') leads to a stacktrace

- relay/sources/apache/rudder-apache-relay-ssl.conf
- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
https://issues.rudder.io/issues/21170
> Fixes #21170: 502 - Proxy Error when triggering Rudder agent

- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala
- webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/ruleDirectives.js
https://issues.rudder.io/issues/21462
> Fixes #21462: 

- relay/sources/apache/rudder-vhost.conf
https://issues.rudder.io/issues/21438
> Fixes #21438: Add HSTS config (commented for now)

- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/DataTypes.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Rules.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRepairedReports.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewTabContent.elm
https://issues.rudder.io/issues/21264
> Fixes #21264: Refresh Button in Rules menu under Directives Tab is not working

- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewMethodsList.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewUtils.elm
https://issues.rudder.io/issues/21469
> Fixes #21469: 

- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
- webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
- webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder.js
https://issues.rudder.io/issues/21471
> Fixes #21471: 

- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
https://issues.rudder.io/issues/21473
> Fixes #21473: 

- webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/ruleDirectives.js
- webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
- webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/common-layout.html
https://issues.rudder.io/issues/21474
> Fixes #21474: CSS for tags is broken

- webapp/sources/ldap-inventory/inventory-api/pom.xml
- webapp/sources/pom.xml
- webapp/sources/rudder/rudder-core/pom.xml
https://issues.rudder.io/issues/21492
> Fixes #21492: Update bouncycastle for 7.2

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PolicyWriterService.scala
https://issues.rudder.io/issues/21482
> Fixes #21482: Concurrent delete of policy backup directory can lead to useless error

- webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala
- webapp/sources/rudder/rudder-rest/src/test/resources/configuration-repository
- webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
https://issues.rudder.io/issues/21478
> Fixes #21478: Clean up test configuration repository to use it from plugin

- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/fileDistribution/copyGitFile/2.3/copyFileFromSharedFolder.ps1.st
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/fileDistribution/fileTemplate/1.0/fileTemplate.ps1.st
https://issues.rudder.io/issues/21498
> Fixes #21498: Correct BOM file in ps1.st used in test

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/MainCampaignService.scala
- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/CampaignApi.scala
https://issues.rudder.io/issues/21470
> Fixes #21470: Schedule campaign event when saving a new campaign

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/InterpolatedValueCompiler.scala
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/1.0/technique.ps1
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/2.0/technique.ps1
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/technique.ps1
https://issues.rudder.io/issues/21502
> Fixes #21502: Adapt webapp policy generation to 7.2 technique syntax

- qa-test
https://issues.rudder.io/issues/21522
> Fixes #21522: Fix qa-test for 7.2

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
https://issues.rudder.io/issues/21491
> Fixes #21491: Cannot delete technique in the technique editor if it contains a space in its name

- webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala
https://issues.rudder.io/issues/21524
> Fixes #21524: Path.of is not available in java8/rudder 7.1

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/CampaignRepository.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/JSONReportsHandler.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/JsonCampaignSerializer.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/MainCampaignService.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/ApplicationLogger.scala
- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/CampaignApi.scala
- webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
- webapp/sources/utils/src/main/scala/com/normation/ZioCommons.scala
https://issues.rudder.io/issues/21523
> Fixes #21523: Initialisation of campaign blocks rudder

- webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/RuleTests.scala
- webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/SystemApiTest.scala
https://issues.rudder.io/issues/21534
> Fixes #21534: Some tests not run because of bad class name

- webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/ArchiveApiTest.scala
- webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/SystemApiTest.scala
https://issues.rudder.io/issues/21537
> Fixes #21537: Rename test classes so that they are run (7.2)

- relay/sources/relayd/deny.toml
https://issues.rudder.io/issues/21538
> Fixes #21538: Unsoundness in "owning_ref"

- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/AgentValueParser.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/tests/AgentValueParserTest.elm
https://issues.rudder.io/issues/21515
> Fixes #21515: result condition are not correct in the technique editor when using properties or variables

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/1.0/technique.ps1
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/2.0/technique.ps1
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/technique.ps1
https://issues.rudder.io/issues/21551
> Fixes #21551: Adapt (more) technique writing to rudder dsc agent 7.2

- webapp/sources/api-doc/openapi.src.yml
https://issues.rudder.io/issues/21531
> Fixes #21531: Missing import API documentation

- relay/sources/relayd/Cargo.lock
https://issues.rudder.io/issues/21555
> Fixes #21555: Potential segfault in chrono

- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/JsonEncoder.elm
https://issues.rudder.io/issues/21560
> Fixes #21560: When we change the status of a technique parameter from required to may be empty, it returns to required after saving

- webapp/sources/api-doc/components/schemas/node-add.yml
https://issues.rudder.io/issues/21553
> Fixes #21553: Node create api doc for properties is incorrect

- webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/homePage.js
https://issues.rudder.io/issues/21432
> Fixes #21432: no compliance details on dashboard on 7.2

- webapp/sources/rudder/rudder-core/src/main/resources/Migration/dbMigration-7.1-7.2-create-campaign-table.sql
https://issues.rudder.io/issues/21571
> Fixes #21571: Create a migration script for campaign

- webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
https://issues.rudder.io/issues/21558
> Fixes #21558: Filter in URL doest work on tab list of nodes

- webapp/sources/dependency-check-suppression.xml
https://issues.rudder.io/issues/21602
> Fixes #21602: Skip CVE-2022-31197 in checks

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
https://issues.rudder.io/issues/21611
> Fixes #21611: Extra spacing when adding several lines with File-Content generic method

- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-bootstrap.css
https://issues.rudder.io/issues/21528
> Fixes #21528: Orange color of hovered links

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/CampaignEventRepository.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/MainCampaignService.scala
- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/CampaignApi.scala
- webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
https://issues.rudder.io/issues/21618
> Fixes #21618: New parameter to campaign event request

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/MainCampaignService.scala
- webapp/sources/rudder/rudder-rest/src/test/resources/logback-test.xml
- webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/CampaignApiTest.scala
- webapp/sources/rudder/rudder-web/src/main/resources/logback.xml
https://issues.rudder.io/issues/21621
> Fixes #21621: Campaign events are not put in queue again after a new handler service was added, hence they are not treated after boot

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/CampaignRepository.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/JSONReportsHandler.scala
https://issues.rudder.io/issues/21624
> Fixes #21624: First report of batch is treated twice by json report handler

- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupCategoryForm.scala
https://issues.rudder.io/issues/21599
> Fixes #21599: Cannot edit/detele an empty group category

- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala
- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupCategoryForm.scala
- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateCloneDirectivePopup.scala
- webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/common-layout.html
https://issues.rudder.io/issues/18575
> Fixes #18575: when validating change in directive, a popup appear, but the background is only half grayed out

- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala
https://issues.rudder.io/issues/21632
> Fixes #21632: deletion and save popup don't close anymore

- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechniqueTabs.elm
- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/TechniqueLibraryManagement.scala
https://issues.rudder.io/issues/21529
> Fixes #21529: Wrong button color in techniques tree

- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://issues.rudder.io/issues/2125
Can you validate the border color and the chosen background color when clicking @RaphaelGauthier
> Fixes #21258: Most buttons with the new Rudder color briefly show their old color when clicked

- relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py
https://issues.rudder.io/issues/21318
> Fixes #21318: rudder package install can install plugins with short name but cannot remove them

- webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/homePage.js
https://issues.rudder.io/issues/21634
> Fixes #21634: Empty dashboard text does not look good

- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-datatable.css
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder.css
https://issues.rudder.io/issues/21256
> Fixes #21256: Broken display of nodes list footer

- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-dashboard.css
https://issues.rudder.io/issues/21416
> Fixes #21416: dashboards widget are not correctly aligned

- relay/sources/relayd/src/processing/shared_files.rs
- relay/sources/relayd/tests/api_shared_files/37817c4d-fbf7-4850-a985-50021f4e8f41/files/e745a140-40bc-4b86-b6dc-084488fc906b/file-old.metadata
- relay/sources/relayd/tests/api_shared_files/37817c4d-fbf7-4850-a985-50021f4e8f41/files/e745a140-40bc-4b86-b6dc-084488fc906b/file.metadata
https://issues.rudder.io/issues/21641
> Fixes #21641: Shared files cleanup does not work

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/JSONReportsHandler.scala
https://issues.rudder.io/issues/21647
> Fixes #21647: remove report handler log

- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderUserDetailsFile.scala
https://issues.rudder.io/issues/21532
> Fixes #21532: Impossible to log in when login in rudder-users.xml contains uppercase chars and login are case-insensitive

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryFileWatcher.scala
https://issues.rudder.io/issues/21653
> Fixes #21653: when we receive a lot of inventories at once, not all are processed

- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupCategoryForm.scala
- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/ModificationValidationPopup.scala
https://issues.rudder.io/issues/21666
> Fixes #21666: Delete group category popup and directive creation popup are not closing

- webapp/sources/api-doc/code_samples/curl/archives/export.sh
https://issues.rudder.io/issues/21664
> Fixes #21664: Broken archive example in API doc

- webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/AgentTypes.scala
https://issues.rudder.io/issues/21667
> Fixes #21667: Rudder agent version is not detected for windows on pending nodes in 7.2

- webapp/sources/rudder/rudder-core/src/main/resources/Migration/dbMigration-7.1-7.2-create-campaign-table.sql
- webapp/sources/rudder/rudder-core/src/main/resources/reportsSchema.sql
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/CampaignEventRepository.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/CampaignRepository.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/DataTypes.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/JSONReportsHandler.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/MainCampaignService.scala
- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/CampaignApi.scala
- webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
- webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/CampaignApiTest.scala
https://issues.rudder.io/issues/21662
> Fixes #21662: Add a name parameter to campaign event

- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-dashboard.css
https://issues.rudder.io/issues/21652
> Fixes #21652: Graph caption is ugly for overall compliance in dashboard

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/metadata.xml
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/rudder_reporting.cf
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/technique.cf
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/technique.ps1
- webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestEditorTechniqueWriter.scala
https://issues.rudder.io/issues/21686
> Fixes #21686: same as parent ticket in 7.0

- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
https://issues.rudder.io/issues/21367
> Fixes #21367: Node certificate expiration date does not follow the same format than the others dates in the UI

- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/View.elm
Still missing the animation fade in, but this is a quick fix
https://issues.rudder.io/issues/21637
> Fixes #21637: Popups in rules page are missing separation from content

- relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
https://issues.rudder.io/issues/21654
> Fixes #21654: rudder package command fails on amazon linux

- webapp/sources/api-doc/code_samples/curl/nodes/all.sh
https://issues.rudder.io/issues/21690
> Fixes #21690: API documentation on how to query node is invalid

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PolicyWriterService.scala
https://issues.rudder.io/issues/21695
> Fixes #21695: Group permission of policies is not correctly set anymore in 7.2

- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-directives.css
https://issues.rudder.io/issues/21671
> Fixes #21671: missing list of inpacted rules when creating a directive and applying it to a rule

- webapp/sources/rudder/rudder-core/src/main/resources/reportsSchema.sql
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/CampaignEventRepository.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/CampaignRepository.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/DataTypes.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/JsonCampaignSerializer.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/MainCampaignService.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/db/Doobie.scala
- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/CampaignApi.scala
- webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
- webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/CampaignApiTest.scala
https://issues.rudder.io/issues/21698
> Fixes #21698: Add reason field to disabled field in campains and campain events

- relay/sources/rudder-relay-postinst
https://issues.rudder.io/issues/21714
> Fixes #21714: Cleanup cron job for relay not removed on upgrade ot 7.2

- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
https://issues.rudder.io/issues/21711
> Fixes #21711: Add css code to generate datatable loading animation

- webapp/sources/rudder/rudder-web/src/main/elm/editor/elm.json
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewMethodsList.elm
https://issues.rudder.io/issues/21368
> Fixes #21368: Methods markdown documentation in the technique editor are not properly rendered

- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleDisplayer.scala
- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/AcceptNode.scala
https://issues.rudder.io/issues/21748
> Fixes #21748: Syntax errors in scala files

- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/AcceptNode.scala
https://issues.rudder.io/issues/21749
> Fixes #21749: Syntax errors in scala files (bis)

- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewTabContent.elm
https://issues.rudder.io/issues/21371
Need to validate in a proper environment, seems to be working in a dev environment
> Fixes #21371: No link to directives in a rule if the rule is not applied to some nodes

- webapp/sources/rudder/rudder-core/src/main/resources/Migration/dbMigration-7.1-7.2-create-campaign-table.sql
https://issues.rudder.io/issues/21767
> Fixes #21767: Wrong type for state column for campaign events in migration script

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/CampaignEventRepository.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/MainCampaignService.scala
- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/CampaignApi.scala
- webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
- webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/CampaignApiTest.scala
https://issues.rudder.io/issues/21766
> Fixes #21766: Reschedule correclty campaign events when a campaign changes

- webapp/sources/api-doc/paths/techniques/methods-reload.yml
https://issues.rudder.io/issues/21762
> Fixes #21762: Wrong method for reload technique in API doc

- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/Editor.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechnique.elm
https://issues.rudder.io/issues/21768
> Fixes #21768: Cannot save a technique afyter removing a block

- webapp/sources/rudder/rudder-core/src/main/resources/ldap/bootstrap.ldif
https://issues.rudder.io/issues/21730
> Fixes #21730: on a fresh 7.1 install, the number of group displayed for "Global configuration of all nodes" is invalid

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/api/ApiAccountRepository.scala
- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
https://issues.rudder.io/issues/21669
> Fixes #21669: Stop using UUIDs as system token

- webapp/sources/rudder/rudder-core/src/main/resources/Migration/dbMigration-7.1-7.2-create-campaign-table.sql
- webapp/sources/rudder/rudder-core/src/main/resources/reportsSchema.sql
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/CampaignEventRepository.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/MainCampaignService.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/db/Doobie.scala
https://issues.rudder.io/issues/21783
> Fixes #21783: Switch to jsonb for campaign event state

- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
https://issues.rudder.io/issues/21793
> Fixes #21793: API version was not updated to API 15 for addition of node updates

- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
- webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/CampaignApiTest.scala
- webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
https://issues.rudder.io/issues/21794
> Fixes #21794: API version in 7.2 must be 16

- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
https://issues.rudder.io/issues/21801
> Fixes #21801: Bad init order for the token generator used for system api token

- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRuleDetails.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewUtils.elm
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-datatable.css
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
https://issues.rudder.io/issues/21789
> Fixes #21789: Added a warning icon in a rule details if no target has been selected 

- webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
https://issues.rudder.io/issues/21795
> Fixes #21795: Add security headers in Lift config

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/DataTypes.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/JsonCampaignSerializer.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/MainCampaignService.scala
- webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
- webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/CampaignApiTest.scala
https://issues.rudder.io/issues/21792
> Fixes #21792: Switch campaign schedule from a duration to a end time

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/CampaignEventRepository.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/CampaignRepository.scala
- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/CampaignApi.scala
- webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
https://issues.rudder.io/issues/21775
> Fixes #21775: Allow to delete a campaign

- webapp/sources/rudder/rudder-web/src/main/resources/applicationContext-security.xml
- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
- webapp/sources/rudder/rudder-web/src/main/webapp/WEB-INF/web.xml
https://issues.rudder.io/issues/21802
> Fixes #21802:  Add security headers in Lift config - end

- relay/sources/apache/rudder-vhost.conf
https://issues.rudder.io/issues/21803
> Fixes #21803: Remove HSTS header from default config

- webapp/sources/rudder/rudder-web/src/main/resources/load-page/robots.txt
https://issues.rudder.io/issues/21798
> Fixes #21798: Add content in rudder's robots.txt

- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
https://issues.rudder.io/issues/21808
> Fixes #21808: Dont redirect other tabs to login form when session cookie is replaced

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/DataTypes.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/JsonCampaignSerializer.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/MainCampaignService.scala
- webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
- webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/CampaignApiTest.scala
https://issues.rudder.io/issues/21811
> Fixes #21811: Campaign json should be versionned

- webapp/sources/rudder/rudder-web/src/main/webapp/index.html
https://issues.rudder.io/issues/21816
> Fixes #21816: 

- Jenkinsfile-security
- policies/Cargo.lock
- policies/deny.toml
https://issues.rudder.io/issues/21830
> Fixes #21830: Update dependency check for 7.2

- Jenkinsfile-security
https://issues.rudder.io/issues/21834
> Fixes #21834:  Update dependency check for 7.2 - fix log path

- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://issues.rudder.io/issues/21837
> Fixes #21837: colors of mixed mode doesn't match enforce and audit

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/CampaignEventRepository.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/MainCampaignService.scala
- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/CampaignApi.scala
- webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
https://issues.rudder.io/issues/21849
> Fixes #21849: Campaign events api should be sortable

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/MainCampaignService.scala
https://issues.rudder.io/issues/21865
> Fixes #21865: One shot schedule condition is invalid

- webapp/sources/rudder/rudder-web/src/main/resources/applicationContext-security.xml
https://issues.rudder.io/issues/21855
> Fixes #21855: Remove X-XSS-Protection header

- policies/Cargo.lock
- policies/Dockerfile
- policies/resource-types/directory/src/main.rs
- policies/resource-types/template/Cargo.toml
- policies/resource-types/template/src/main.rs
- policies/rudder-commons/src/lib.rs
- policies/rudder-resource-type/Cargo.toml
- policies/rudder-resource-type/src/cfengine/protocol.rs
- policies/rudder-resource-type/src/lib.rs
- policies/rudder-resource-type/src/parameters.rs
- policies/rudderc/Cargo.toml
- policies/rudderc/src/backends/unix/ncf/technique.rs
- policies/rudderc/src/cli.rs
- policies/rudderc/src/frontends/ncf/method.rs
- policies/rudderc/src/ir/native.rs
- policies/rudderc/src/ir/resource.rs
- policies/rudderc/src/logs.rs
- policies/rust-toolchain.toml
- relay/sources/relayd/Cargo.lock
- relay/sources/relayd/Cargo.toml
- relay/sources/relayd/Dockerfile
- relay/sources/relayd/benches/benches.rs
- relay/sources/relayd/rust-toolchain.toml
- relay/sources/relayd/src/data/report.rs
- relay/sources/relayd/src/data/runlog.rs
- relay/sources/relayd/src/output/database.rs
- relay/sources/relayd/tests/processing_reporting.rs
https://issues.rudder.io/issues/21875
> Fixes #21875: Update Rust for 7.3

- webapp/sources/ldap-inventory/inventory-fusion/src/test/scala/com/normation/inventory/provisioning/fusion/TestReportParsing.scala
- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/HomePage.scala
- webapp/sources/rudder/rudder-web/src/test/scala/com/normation/rudder/web/snippet/HomePageTest.scala
https://issues.rudder.io/issues/21411
> Fixes #21411: Epoch is displayed in agent version in webapp

- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala
https://issues.rudder.io/issues/21892
> Fixes #21892: System techniques should not be displayed in directive tree

- webapp/sources/pom.xml
https://issues.rudder.io/issues/21893
> Fixes #21893: CVE in nuprocess 2.03 and below

- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
https://issues.rudder.io/issues/21894
> Fixes #21894: Compile error in master following scalac version update

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
https://issues.rudder.io/issues/21899
> Fixes #21899: Broken technique indentation with jvm >= 12

- webapp/sources/Dockerfile
https://issues.rudder.io/issues/21900
> Fixes #21900: Broken Java 17 tests on 7.2+

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchBackendImpl.scala
https://issues.rudder.io/issues/21901
> Fixes #21901: Quick search does not return node name when looking for properties but node id instead

- webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/homePage.js
https://issues.rudder.io/issues/21911
> Fixes #21911: Chart show the tooltips only when clicking

- webapp/sources/pom.xml
https://issues.rudder.io/issues/21913
> Fixes #21913: scalap and compiler dependency are not correct

- relay/sources/relayd/deny.toml
https://issues.rudder.io/issues/21914
> Fixes #21914: Add authorized license Unicode-DFS-2016 in relayd

- webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
https://issues.rudder.io/issues/21503
> Fixes #21503: Unable to sort on property in list of nodes tab

- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala
https://issues.rudder.io/issues/21917
> Fixes #21917: User technique should be on top in directive tree

- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/RulesInternalAPI.scala
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechniqueList.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/View.elm
- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala
- webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/tree.js
- webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/ruleManagement.html
- webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/techniqueEditor.html
https://issues.rudder.io/issues/21373
> Fixes #21373: Links in {directive|rule|group|technique} "tree" can not be open in a new tab

- webapp/sources/api-doc/components/schemas/rule-new.yml
- webapp/sources/api-doc/components/schemas/rule-targets.yml
- webapp/sources/api-doc/components/schemas/rule-update.yml
- webapp/sources/api-doc/components/schemas/rule-with-category.yml
https://issues.rudder.io/issues/21935
> Fixes #21935: Format of target group is wrong in API doc

- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
https://issues.rudder.io/issues/21943
> Fixes #21943: Broken session - lastNonCometAccessedTime has an unexpected value

- webapp/sources/rudder/rudder-web/src/main/resources/logback.xml
https://issues.rudder.io/issues/21945
> Fixes #21945: logback.xml should contains examples of specific plugins loggers

- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechniqueList.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/View.elm
- webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/tree.js
https://issues.rudder.io/issues/21944
> Fixes #21944: Missing use of contextPath in some js files

- policies/rudderc/docs/examples/ntp.yml
- policies/rudderc/src/backends/unix.rs
- policies/rudderc/src/backends/unix/ncf/method_call.rs
- policies/rudderc/src/ir/resource.rs
- policies/rudderc/tests/cases/general/ntp.cf
- policies/rudderc/tests/cases/general/ntp.yml
- policies/rudderc/tests/cases/general/with-reporting.cf
- policies/rudderc/tests/cases/general/with-reporting.yml
https://issues.rudder.io/issues/21961
> Fixes #21961: Start docs for new technique yaml format

- webapp/sources/rudder/rudder-web/src/main/resources/rudder-system-global-parameter.conf
https://issues.rudder.io/issues/21971
> Fixes #21971: Disable agent syslog logging by default - property

- api-doc/Dockerfile
https://issues.rudder.io/issues/21991
> Fixes #21991: Update api doc tooling

- Jenkinsfile
https://issues.rudder.io/issues/21994
> Fixes #21994: Add jdk 19 to compatibility tests

- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ApiCalls.elm
https://issues.rudder.io/issues/21964
> Fixes #21964: Update technique with / in name lead to error

- webapp/sources/api-doc/components/schemas/node-add.yml
https://issues.rudder.io/issues/22017
> Fixes #22017: [API] Request Sample / documentation false

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/MainCampaignService.scala
https://issues.rudder.io/issues/22041
> Fixes #22041: One shot campaign create event infinitely

- webapp/sources/pom.xml
https://issues.rudder.io/issues/22044
> Fixes #22044: Spring-security is impacted by CVE-2022-31692

- webapp/sources/pom.xml
- webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestNodeAndGlobalParameterLookup.scala
https://issues.rudder.io/issues/22049
> Fixes #22049: Update scala dependencies to latest version

- webapp/sources/rudder/rudder-web/src/main/elm/accounts/elm.json
- webapp/sources/rudder/rudder-web/src/main/elm/editor/elm.json
- webapp/sources/rudder/rudder-web/src/main/elm/healthcheck/elm.json
- webapp/sources/rudder/rudder-web/src/main/elm/healthcheck/sources/ApiCalls.elm
- webapp/sources/rudder/rudder-web/src/main/elm/hooks/elm.json
- webapp/sources/rudder/rudder-web/src/main/elm/notifications/elm.json
- webapp/sources/rudder/rudder-web/src/main/elm/onboarding/elm.json
- webapp/sources/rudder/rudder-web/src/main/elm/onboarding/sources/ApiCalls.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/elm.json
https://issues.rudder.io/issues/22051
> Fixes #22051: Update elm dependencies

- policies/Cargo.lock
- policies/resource-types/template/Cargo.toml
- policies/rudder-commons/src/lib.rs
- policies/rudder-resource-type/src/lib.rs
- policies/rudderc/Cargo.toml
- policies/rudderc/src/backends.rs
- policies/rudderc/src/backends/metadata.rs
- policies/rudderc/src/backends/unix.rs
- policies/rudderc/src/backends/unix/ncf/method_call.rs
- policies/rudderc/src/backends/windows.rs
- policies/rudderc/src/compiler.rs
- policies/rudderc/src/ir.rs
- policies/rudderc/src/ir/technique.rs
- policies/rudderc/templates/technique.ps1
- policies/rudderc/tests/cases/general/min.cf
- policies/rudderc/tests/cases/general/min.ps1
- policies/rudderc/tests/cases/general/min.xml
- policies/rudderc/tests/cases/general/min.yml
- policies/rudderc/tests/cases/general/ntp.cf
- policies/rudderc/tests/cases/general/ntp.ps1
- policies/rudderc/tests/cases/general/ntp.xml
- policies/rudderc/tests/cases/general/ntp.yml
- policies/rudderc/tests/compile.rs
- policies/rudderc/tests/metadata/serialized.xml
- relay/sources/relayd/Cargo.lock
https://issues.rudder.io/issues/22054
> Fixes #22054: Generate a proper metadata.xml

- qa-test
https://issues.rudder.io/issues/22064
> Fixes #22064: Ignore files from policies/repos in shell tests

- webapp/sources/rudder/rudder-core/src/main/resources/ldap/bootstrap.ldif
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/test_import_export_archive/1.0/metadata.xml
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/test_import_export_archive/1.0/technique.cf
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/test_import_export_archive/1.0/technique.json
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/test_import_export_archive/1.0/technique.ps1
- webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala
- webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala
- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ArchiveApi.scala
- webapp/sources/rudder/rudder-rest/src/test/resources/api/api_directives.yml
- webapp/sources/rudder/rudder-rest/src/test/resources/api/api_techniques.yml
- webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
- webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/ArchiveApiTest.scala
https://issues.rudder.io/issues/22036
> Fixes #22036: Import directive API fail for user technique

- relay/sources/rudder-pkg/requirements.txt
- webapp/sources/rudder/rudder-web/src/main/elm/Dockerfile
https://issues.rudder.io/issues/22084
> Fixes #22084: Fix various builds errors after build containers update

- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
https://issues.rudder.io/issues/22083
> Fixes #22083: Make campaign api publuc

- webapp/sources/rudder/rudder-web/src/main/build.sh
https://issues.rudder.io/issues/22093
> Fixes #22093: Install npm dependencies in dev build when not present

- webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
https://issues.rudder.io/issues/22092
> Fixes #22092: Deleting custom column in based on a property in nodes list fails

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/1.0/technique.ps1
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/2.0/technique.ps1
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/technique.ps1
https://issues.rudder.io/issues/22074
> Fixes #22074: Generated policies are invalid for Windows using powershell 4

- webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
https://issues.rudder.io/issues/22121
> Fixes #22121: Delete action for node is not the correct one because of merge 

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/AutomaticReportLogger.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/JSONReportsHandler.scala
https://issues.rudder.io/issues/22129
> Fixes #22129: Id to start looking for report json should not be zero but highest id.

- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RudderJsonResponse.scala
- webapp/sources/rudder/rudder-web/src/main/resources/logback.xml
https://issues.rudder.io/issues/22124
> Fixes #22124: Log all API errors

- webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
https://issues.rudder.io/issues/22133
> Fixes #22133: Parent issue does not address root pb with node deletion config

- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/ncf/TechniqueReader.scala
- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/action/CheckNcfTechniqueUpdate.scala
https://issues.rudder.io/issues/21957
> Fixes #21957: Errors of script that write technique.json during upgrade should be ignored

- webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/homePage.js
https://issues.rudder.io/issues/22131
> Fixes #22131: Change in lib for node dashboard in home page makes it non clickable anymore

- webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/homePage.js
- webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
https://issues.rudder.io/issues/22134
> Fixes #22134: Click on graph node with "applying" compliance lead to JS error 

- webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/homePage.js
https://issues.rudder.io/issues/22138
> Fixes #22138: In dashboard in graph by OS, click for some OS lead to AIX

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/JSONReportsHandler.scala
https://issues.rudder.io/issues/22144
> Fixes #22144: Highest id only fetch at first run, but batch is running

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/MainCampaignService.scala
https://issues.rudder.io/issues/22148
> Fixes #22148: Correction to avoid infinite campaign event does not work in some case

- policies/rudderc/src/ir/technique.rs
- policies/rudderc/tests/cases/general/ntp/ntp.yml
https://issues.rudder.io/issues/22156
> Fixes #22156: Tags entry in yaml technique

- policies/Cargo.lock
- policies/rudderc/Cargo.toml
- policies/rudderc/src/backends/metadata.rs
- policies/rudderc/src/backends/unix.rs
- policies/rudderc/src/backends/unix/cfengine.rs
- policies/rudderc/src/backends/unix/cfengine/promise.rs
- policies/rudderc/src/backends/unix/ncf/method_call.rs
- policies/rudderc/tests/cases/general/min/min.cf
- policies/rudderc/tests/cases/general/min/min.xml
- policies/rudderc/tests/cases/general/ntp/ntp.cf
- policies/rudderc/tests/cases/general/ntp/ntp.xml
- policies/rudderc/tests/metadata/serialized.xml
- relay/sources/relayd/Cargo.lock
https://issues.rudder.io/issues/22153
> Fixes #22153: Various metadata.xml fixes

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/MainCampaignService.scala
- webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/campaign/CampaignSchedulerTest.scala
https://issues.rudder.io/issues/22176
> Fixes #22176: Monthly schedule in January/December can be wrong

- webapp/sources/pom.xml
https://issues.rudder.io/issues/22169
> Fixes #22169: Update spring version to last one on rudder 7.2

- webapp/sources/rudder/rudder-web/src/main/resources/applicationContext-security.xml
- webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
- webapp/sources/rudder/rudder-web/src/main/webapp/WEB-INF/web.xml
https://issues.rudder.io/issues/22146
> Fixes #22146: Backport front end security improvements to 7.2

- webapp/sources/dependency-check-suppression.xml
https://issues.rudder.io/issues/22195
> Fixes #22195: update dependency check exception

- webapp/sources/utils/src/main/scala/com/normation/utils/StandardFieldsValidation.scala
- webapp/sources/utils/src/test/scala/com/normation/utils/TestStandardFieldValidation.scala
https://issues.rudder.io/issues/22186
> Fixes #22186: Authorize "_" (underscore) in hostname / fqdn

- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/Authorizations.scala
- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RoleApiMapping.scala
https://issues.rudder.io/issues/22198
> Fixes #22198: Make authorization and rights pluggable

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryProcessor.scala
https://issues.rudder.io/issues/22211
In addition to move the inventory to `/var/rudder/inventories/failed`, we write a file whose content is the error message for why the inventory was not accepted with the date. It helps a lot for user to understand why the inventory is failed.
> Fixes #22211: Add a log file along with rejected inventories with cause

- Jenkinsfile-security
- webapp/sources/rudder/rudder-web/src/main/.nsprc
- webapp/sources/rudder/rudder-web/src/main/package-lock.json
- webapp/sources/rudder/rudder-web/src/main/package.json
https://issues.rudder.io/issues/22217
> Fixes #22217: Improve npm audit

- webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/NodeInventory.scala
- webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-inventories/windows2022.ocs
- webapp/sources/ldap-inventory/inventory-fusion/src/test/scala/com/normation/inventory/provisioning/fusion/TestReportParsing.scala
- webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/InventoryMapper.scala
- webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/LDAPConstants.scala
- webapp/sources/rudder/rudder-web/src/main/resources/ldapObjectAndAttributes.properties
https://issues.rudder.io/issues/22216
> Fixes #22216: Missing support for Windows 2022

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/UpdateDynamicGroups.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/ApplicationLogger.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/DynGroupService.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/DynGroupUpdaterService.scala
- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SystemApi.scala
- webapp/sources/rudder/rudder-web/src/main/resources/logback.xml
https://issues.rudder.io/issues/22209
> Fixes #22209: Dynamic group logs must not be conflated with scheduled job ones

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/PurgeDeletedInventories.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/PurgeOldInventoryFiles.scala
- webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
https://issues.rudder.io/issues/7526
This is my Christmas present for author of that very old ticket :)
> Fixes #7526: Housekeeping of /var/rudder/inventories/received|failed|etc

- webapp/sources/api-doc/code_samples/curl/settings/set-allowed-networks-diff.sh
https://issues.rudder.io/issues/22225
> Fixes #22225: Documentation for Modify Settings example missing parameter

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/AbstractScheduler.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/FetchNodeExecutions.scala
- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
That's a small contrib as a kind of a christmas present, nothing fancy but as I was browsing the codebase, I tried to actually do a change in the boyscout rule style.
> Fixes #22224: Replace usage of Int + comments as seconds to an actual Duration time

- webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-menu.css
https://issues.rudder.io/issues/22245
> Fixes #22245: Top menu bar display is broken

- webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
https://issues.rudder.io/issues/22248
> Fixes #22248: Add includeSubdomains to HSTS header

- Jenkinsfile
- Jenkinsfile-security
https://issues.rudder.io/issues/22250
> Fixes #22250: Improve ci notification on repaired and error

- webapp/sources/rudder/rudder-web/src/main/gulpfile.js
- webapp/sources/rudder/rudder-web/src/main/package-lock.json
- webapp/sources/rudder/rudder-web/src/main/package.json
- webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/common-layout.html
https://issues.rudder.io/issues/22252
> Fixes #22252: Use npm to maintain angularJS

- policies/techniques/anssi_bp_028.yml
https://issues.rudder.io/issues/22268
> Fixes #22268: Add a first hardening technique draft

- Jenkinsfile
- webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
https://issues.rudder.io/issues/22274
> Fixes #22274: Add includeSubdomains to HSTS header with correct property name

- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechniqueList.elm
https://issues.rudder.io/issues/22283
> Fixes #22283: Make the Techniques search case-insensitive

- webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/databaseManagement.html
https://issues.rudder.io/issues/22291
> Fixes #22291: Today button doesn't work in datepicker in report database page

- policies/Dockerfile
- policies/rust-toolchain.toml
- relay/sources/relayd/Dockerfile
- relay/sources/relayd/rust-toolchain.toml
https://issues.rudder.io/issues/22293
> Fixes #22293: Update to Rust 1.66.1

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryProcessor.scala
https://issues.rudder.io/issues/22299
> Fixes #22299: Add a line break at the end if inventory rejection log file

- .cargo/config.toml
- policies/Cargo.lock
- relay/sources/relayd/Cargo.lock
- relay/sources/relayd/Cargo.toml
https://issues.rudder.io/issues/22300
> Fixes #22300: Update the toml crate to 0.6

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/PurgeOldInventoryFiles.scala
https://issues.rudder.io/issues/22226
> Fixes #22226: Typo and missing log info in cleaning old inventory file parent ticket

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/CampaignEventRepository.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/MainCampaignService.scala
https://issues.rudder.io/issues/22139
> Fixes #22139: Running deleted campaign don't get their directive cleaned-up 

- webapp/sources/rudder/rudder-web/src/main/.nsprc
- webapp/sources/rudder/rudder-web/src/main/package-lock.json
- webapp/sources/rudder/rudder-web/src/main/package.json
https://issues.rudder.io/issues/22307
> Fixes #22307: Fix npm security alerts

- webapp/sources/dependency-check-suppression.xml
https://issues.rudder.io/issues/22308
> Fixes #22308: Ignore datatable prototype pollution

- webapp/sources/rudder/rudder-web/src/main/.nsprc
https://issues.rudder.io/issues/22324
> Fixes #22324: Ignore DoS in npm dependencies

- relay/sources/relayd/deny.toml
- relay/sources/rudder-pkg/requirements.txt
https://issues.rudder.io/issues/22328
> Fixes #22328: Ignore RUSTSEC-2022-0082

- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleDisplayer.scala
- webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-directives.css
- webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-main.css
- webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-menu.css
- webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-tags.css
https://issues.rudder.io/issues/22305
> Fixes #22305: Display of Target Rules is broken

- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala
- webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentDirectiveEditForm.html
https://issues.rudder.io/issues/22254
> Fixes #22254: Directive creation process is counter intuitive in 7.3.0~alpha

- webapp/sources/rudder/rudder-web/src/main/package-lock.json
https://issues.rudder.io/issues/22336
> Fixes #22336: Update outdated npm packages

- webapp/sources/rudder/rudder-core/src/main/resources/ldap/bootstrap.ldif
- webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala
- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/action/RemoveFaultyLdapEntries.scala
https://issues.rudder.io/issues/22314
> Fixes #22314: Cannot list directives with API

- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/Authorizations.scala
- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RoleApiMapping.scala
- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala
- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderUserDetailsFile.scala
- webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/RudderUserDetailsTest.scala
- webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/RudderUserPasswordEncoderTest.scala
https://issues.rudder.io/issues/22318
This PR refactor code around case insensitivity property to make is simpler to maintain in the future. 
The main goals are:
- remove code duplication and xml parsing duplication
- remove dependcies on global parameters
- make responsibility of function more self-contained (avoid scattering around the need to know how the code works to use it and make testing easier)
Also rename the currend test file to describe that it is about testing crypto algo, and add a test file for testing case sensitivity.
> Fixes #22318: Refactor case insensitivity property for users

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/hooks/RunHooks.scala
- webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/hooks/HooksTest.scala
https://issues.rudder.io/issues/22339
> Fixes #22339: Hook timeout may not have the good value

- webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/FusionInventoryParser.scala
- webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-inventories/rudder-tag/invalid-hostname-localhost-alternative-error.ocs
- webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-inventories/rudder-tag/invalid-hostname-localhost-alternative-ok.ocs
- webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-inventories/rudder-tag/invalid-hostname-localhost.ocs
- webapp/sources/ldap-inventory/inventory-fusion/src/test/scala/com/normation/inventory/provisioning/fusion/TestReportParsing.scala
https://issues.rudder.io/issues/22326
> Fixes #22326: some nodes are called "localhost" since #8022

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/CampaignEventRepository.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/CampaignRepository.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/DataTypes.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/MainCampaignService.scala
- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/CampaignApi.scala
- webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
https://issues.rudder.io/issues/22346
> Fixes #22346: New filters on campaign queries to get several campaign types in one request

- relay/sources/relayd/deny.toml
https://issues.rudder.io/issues/22354
> Fixes #22354: Ignore CVE-2023-22895 in relayd

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/workflows/CommitAndDeployChangeRequestService.scala
- webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/workflows/TestCheckMergeDivergence.scala
https://issues.rudder.io/issues/22363
> Fixes #22363: User should be able to accept change request even with divergences

- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
https://issues.rudder.io/issues/22374
> Fixes #22374: Allow iframes from the same origin

- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/Authorizations.scala
- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/CurrentUser.scala
- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderUserDetailsFile.scala
https://issues.rudder.io/issues/22353
> Fixes #22353: Administrator doesn't have any access anymore

- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/Compliance.scala
- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ComplianceApi.scala
https://issues.rudder.io/issues/22376
> Fixes #22376: Refactor Directive compliance to handle blocks

- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/Authorizations.scala
- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderUserDetailsFile.scala
- webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/RudderUserDetailsTest.scala
https://issues.rudder.io/issues/22357
> Fixes #22357: Reloading user must discared previously registered custom-roles

- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/Authorizations.scala
- webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/RudderUserDetailsTest.scala
https://issues.rudder.io/issues/22384
> Fixes #22384: Unknown roles must be ignored, not lead to invalid role

- webapp/sources/api-doc/code_samples/curl/archives/import.sh
- webapp/sources/api-doc/paths/archives/import.yml
- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ArchiveApi.scala
- webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/ArchiveApiTest.scala
- webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
https://issues.rudder.io/issues/22333
> Fixes #22333: Avoid sync group when importing a rule archive

- webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/FusionInventoryParser.scala
- webapp/sources/ldap-inventory/inventory-fusion/src/test/scala/com/normation/inventory/provisioning/fusion/TestReportParsing.scala
- webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
https://issues.rudder.io/issues/22359
> Fixes #22359: Make parsing "process" in inventory optional

- webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ExecutionBatchTest.scala
https://issues.rudder.io/issues/22381
> Fixes #22381: Add unit test for the missing/unexpected parent issue on old runs

- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/Editor.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechnique.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/DataTypes.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Init.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Rules.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/View.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewCategoryDetails.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRuleDetails.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewUtils.elm
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
https://issues.rudder.io/issues/21929
> Fixes #21929: Missing a loading info when a technique it is being saved

- webapp/sources/pom.xml
- webapp/sources/rudder/rudder-web/pom.xml
https://issues.rudder.io/issues/22403
> Fixes #22403: Fix version maven-resources-plugin to 3.1.0, instead of relying on maven default version

- webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
https://issues.rudder.io/issues/22107
> Fixes #22107: Show all in technical details table doesn't work

- webapp/sources/pom.xml
https://issues.rudder.io/issues/22419
> Fixes #22419: Make specs2 test console output more detailed

- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderUserDetailsFile.scala
https://issues.rudder.io/issues/22424
> Fixes #22424: Remove pattern matching warning 

- relay/sources/relayd/deny.toml
- rudder-lang/deny.toml
https://issues.rudder.io/issues/22432
> Fixes #22432: RUSTSEC-2023-0018  in remove_dir_all

- webapp/sources/dependency-check-suppression.xml
- webapp/sources/pom.xml
https://issues.rudder.io/issues/22433
> Fixes #22433: Update commons fileupload dependency to prevent CVE-2023-24998

- webapp/sources/api-doc/openapi.src.yml
- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/ApiDatastructures.scala
- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
https://issues.rudder.io/issues/22435
> Fixes #22435: Directive compliance API version is 10 in place of 17

- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/View.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewUtils.elm
https://issues.rudder.io/issues/22449
> Fixes #22449: Add an animation when the rules table loads

- webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/PreInventoryParserCheckConsistency.scala
https://issues.rudder.io/issues/22453
> Fixes #22453: Inventory error when missing tag POLICY_SERVER_UUID talk about POLICY_SERVER

- webapp/sources/rudder/rudder-web/src/main/javascript/rudder/homePage.js
- webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-dashboard.css
https://issues.rudder.io/issues/21255
> Fixes #21255: Empty dashboard doesn't look good

- webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentNodeProperties.html
https://issues.rudder.io/issues/21918
> Fixes #21918: Edit properties is not intuitive

- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/Authorizations.scala
- webapp/sources/rudder/rudder-web/src/main/resources/demo-rudder-users.xml
- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderUserDetailsFile.scala
- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/Authz.scala
- webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/RudderUserDetailsTest.scala
https://issues.rudder.io/issues/22457
> Fixes #22457: Update rudder-user.xml to use permissions in place of roles attribute

- webapp/sources/api-doc/paths/settings/allowed_networks.yml
- webapp/sources/api-doc/paths/settings/allowed_networks_diff.yml
https://issues.rudder.io/issues/22467
> Fixes #22467: Inconsistency in API doc for allowed network

- policies/rudder-commons/src/lib.rs
- policies/rudderc/src/backends/unix/cfengine.rs
- policies/rudderc/src/backends/unix/cfengine/promise.rs
- policies/rudderc/src/backends/unix/ncf/method_call.rs
- policies/rudderc/src/compiler.rs
- policies/rudderc/src/frontends/methods/method.rs
- policies/rudderc/src/ir/condition.rs
- policies/rudderc/src/lib.rs
- policies/rudderc/tests/cases/general/escaping/metadata.xml
- policies/rudderc/tests/cases/general/escaping/technique.cf
- policies/rudderc/tests/cases/general/escaping/technique.ps1
- policies/rudderc/tests/cases/general/escaping/technique.yml
- policies/rudderc/tests/cases/general/min/technique.cf
- policies/rudderc/tests/cases/general/ntp/technique.cf
- policies/rudderc/tests/cases/general/reporting/technique.cf
https://issues.rudder.io/issues/22468
> Fixes #22468: Fix escaping in rudderc

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlSerialisationImpl.scala
https://issues.rudder.io/issues/18215
> Fixes #18215: Persisted rule should have sorted groups/directives

- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechnique.elm
https://issues.rudder.io/issues/22475
> Fixes #22475: There is one more minus in deleted resources counter within technique editor

- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechniqueTabs.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewTabContent.elm
- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupCategoryForm.scala
- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
https://issues.rudder.io/issues/21369
> Fixes #21369: Technique ID and group ID are juste listed as "ID" in the UI when other IDs are listed with their long name

- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderUserDetailsFile.scala
- webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/RudderUserDetailsTest.scala
https://issues.rudder.io/issues/22383
> Fixes #22383: Password tag should be optionnal

- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala
- webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/tree.js
https://issues.rudder.io/issues/22428
> Fixes #22428: Missing tooltip on unused directives icon

- policies/Cargo.lock
- policies/rudderc/Cargo.toml
- policies/rudderc/src/lib.rs
- policies/rudderc/src/technique.schema.json
- policies/rudderc/tests/compile.rs
https://issues.rudder.io/issues/22489
> Fixes #22489: Add a JSON schema validation

- relay/arch-doc/rudder-7-communications-security.md
https://issues.rudder.io/issues/22505
> Fixes #22505: Update network security arch doc for 7.3 and migration cases

- relay/arch-doc/README.md
- relay/arch-doc/rudder-6-reporting-relayd.md
- relay/arch-doc/rudder-7-communications-security.md
https://issues.rudder.io/issues/22509
> Fixes #22509: Improve introduction of relay arch docs

- policies/rudderc/src/technique.schema.json
https://issues.rudder.io/issues/22511
> Fixes #22511: Add a json schema file to describe the rudder technique yaml format

- policies/Cargo.lock
- policies/rudder-commons/src/lib.rs
- policies/rudderc/Cargo.toml
- policies/rudderc/src/backends.rs
- policies/rudderc/src/backends/metadata.rs
- policies/rudderc/src/compiler.rs
- policies/rudderc/src/lib.rs
- policies/rudderc/templates/doc.html.askama
https://issues.rudder.io/issues/22538
> Fixes #22538: Render methods docs as html

- policies/deny.toml
https://issues.rudder.io/issues/22543
> Fixes #22543: Allow BSD-2-Clause licences

- webapp/arch-doc/rudder-7-3-frontend-security.md
https://issues.rudder.io/issues/22512
> Fixes #22512: Arch doc for frontend security

- webapp/sources/rudder/rudder-web/src/main/resources/applicationContext-security.xml
https://issues.rudder.io/issues/22522
> Fixes #22522: Allow iframes from the same origin

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/1.0/technique.ps1
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/2.0/technique.ps1
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/technique.ps1
https://issues.rudder.io/issues/22535
> Fixes #22535: Mustache template is not capable to render technique parameters

- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://issues.rudder.io/issues/21683
> Fixes #21683: Shadow overlapping on first menu entry

- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-filemanager.css
- webapp/sources/rudder/rudder-web/src/main/webapp/templates/angular/filemanager/main.html
https://issues.rudder.io/issues/22110
> Fixes #22110: When shared folder file list is too long the selector fail

- webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder-datatable.js
https://issues.rudder.io/issues/22560
> Fixes #22560: HTML tag in compliance hover

- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ApiCalls.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/DataTypes.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/View.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewCategoryDetails.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRulesTable.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewTabContent.elm
- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewUtils.elm
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-rules.css
https://issues.rudder.io/issues/22103
> Fixes #22103: Rule list doesn't appear anymore in a rule category

- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
https://issues.rudder.io/issues/22581
> Fixes #22581: Change name parameter "Rudder ID" for group id

- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/Authorizations.scala
- webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/RudderUserDetailsTest.scala
https://issues.rudder.io/issues/22579
We were a bit lenient on the check for authorization: if the authorization had a valid syntaxt BUT no object of the authorization name existed, we still tried to create corresponding right (with an empty set, which failed). 
The solution is to:
- forbid for role the usage of `_`. I could have restricted it to existing `_all`, `read` etc pattern, but it's much much easier to be broad today, and make the restriction smaller latter, than the contrary. On the plus side, it gives the general rule "only built-in permissions (authorizations or role) can have an `_`
- for role name validity, check the syntax, and not the existence of a corresponding authorization, 
- adapt tests
> Fixes #22579: Rudder can't boot when custom role uses cve_read without cve plugin

- webapp/sources/pom.xml
https://issues.rudder.io/issues/22586
> Fixes #22586: Update spring-core to 5.3.26

- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
https://issues.rudder.io/issues/18583
Replacing previous PR: https://github.com/Normation/rudder/pull/4734
> Fixes #18583: System group preview description are not displayed

- webapp/sources/api-doc/code_samples/curl/nodes/apply-all.sh
- webapp/sources/api-doc/code_samples/curl/nodes/apply-id.sh
- webapp/sources/api-doc/paths/nodes/apply-policy-id.yml
https://issues.rudder.io/issues/22565
> Fixes #22565: API Documentation errors for trigger agent run

- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderUserDetailsFile.scala
https://issues.rudder.io/issues/21978
> Fixes #21978: password=LDAP produces error logs in webapp

- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
https://issues.rudder.io/issues/21417
> Fixes #21417: there is a space before all texts in the node details page, so copy and paste include it

- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Rules.elm
https://issues.rudder.io/issues/22524
> Fixes #22524: when we save a rule category, the button save never stops saving

- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewMethod.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechniqueList.elm
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-technique-editor.css
https://issues.rudder.io/issues/12282
> Fixes #12282: In technique editor, technique with missing generic method need a warning icon

- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewTabContent.elm
https://issues.rudder.io/issues/22517
> Fixes #22517: rules/directives/cancel button doesn't work

- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechniqueList.elm
https://issues.rudder.io/issues/22635
> Fixes #22635: Remove "ncf" mentions in warning unknown method

- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/AcceptNode.scala
https://issues.rudder.io/issues/19258
> Fixes #19258:  Pending nodes History Tab shows duplicate entries

- webapp/sources/rudder/rudder-web/src/main/webapp/index.html
https://issues.rudder.io/issues/22644
> Fixes #22644: Remove AdminLTE script from login page

- relay/sources/api-doc/introduction.md
- relay/sources/api-doc/openapi.src.yml
- webapp/sources/api-doc/introduction.md
- webapp/sources/api-doc/openapi.src.yml
https://issues.rudder.io/issues/22648
> Fixes #22648: Relay API documentation is quite hard to find

- webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-inventory-received-pending/auto-accept-nodes.example
https://issues.rudder.io/issues/22649
> Fixes #22649: Log in hook should got to /var/log and not /tmp

- relay/sources/relayd/src/processing/shared_files.rs
https://issues.rudder.io/issues/22652
> Fixes #22652: Broken shared-files cleanup when file id contains a dot

- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SettingsApi.scala
- webapp/sources/rudder/rudder-rest/src/test/resources/api/api_settings.yml
- webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/ArchiveApiTest.scala
- webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
https://issues.rudder.io/issues/22456
> Fixes #22456: Change json structure returned for /settings/allowed_networks

- webapp/sources/pom.xml
https://issues.rudder.io/issues/22637
> Fixes #22637: upgrade postgresql drive for CVE CVE-2022-41946

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/metrics/HistorizeNodeCountService.scala
https://issues.rudder.io/issues/22616
> Fixes #22616: JGitInternalError on HistorizeNodeCountService

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDirectiveRepository.scala
https://issues.rudder.io/issues/22614
- the change is just that we need to look for the parent breadcrump only in the case where the active technique exists
- need to be view with "?w=1" to see the change
- also remove a duplicated `}` in the log
> Fixes #22614: Error log at boot: Can not find active technique with id 'test_import_export_archive}'

- webapp/sources/pom.xml
https://issues.rudder.io/issues/22668
> Fixes #22668: Update spring to 5.3.27 and spring-security 5.7.8

- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
https://issues.rudder.io/issues/22681
> Fixes #22681: Change workflow service type in init to repair plugin build

- Jenkinsfile-security
https://issues.rudder.io/issues/22687
> Fixes #22687: Notify different channel for security dependency check

- webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRuleDetails.elm
https://issues.rudder.io/issues/20788
> Fixes #20788:  Tooltip on enforce/audit label in rules title not working

- webapp/sources/rudder/rudder-web/src/main/.nsprc
https://issues.rudder.io/issues/22707
> Fixes #22707: Vulnerability in decode-uri-component

- webapp/sources/dependency-check-suppression.xml
https://issues.rudder.io/issues/22708
> Fixes #22708: Ignore CVE 2023-20860 

- policies/rudderc/src/cli.rs
- policies/rudderc/src/lib.rs
https://issues.rudder.io/issues/22719
> Fixes #22719: Fallback on /var/rudder/ncf/ for library

- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/HealthcheckInfo.scala
- webapp/sources/rudder/rudder-web/src/main/webapp/secure/utilities/healthcheck.html
https://issues.rudder.io/issues/22625
> Fixes #22625: Healthcheck notification is displayed when a user have no right

- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/HealthcheckInfo.scala
https://issues.rudder.io/issues/22729
> Fixes #22729: Upmerge breaks 7.3/master

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/JsonQueryObjects.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/JsonResponseObjects.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/RestDataSerializer.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/RudderDit.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/NodeGroup.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/NodeGroupDiff.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/queries/CmdbQuery.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogDetailsService.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogFactory.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/CmdbQueryParser.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/DynGroupService.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/LdapQueryProcessor.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/QueryProcessor.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/NewNodeManager.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/PolicyServerManagementService.scala
- webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/nodes/TestMergeGroupProperties.scala
- webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestPendingNodePolicies.scala
- webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala
- webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestStringQueryParser.scala
- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/RestData.scala
- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/EventLogDetailsGenerator.scala
- webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/SearchNodeComponent.scala
- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateCategoryOrGroupPopup.scala
- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/SearchNodes.scala
https://issues.rudder.io/issues/22678
> Fixes #22678: Remove QueryTrait 

- webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/FusionInventoryParser.scala
- webapp/sources/ldap-inventory/inventory-fusion/src/test/scala/com/normation/inventory/provisioning/fusion/TestReportParsing.scala
https://issues.rudder.io/issues/22387
> Fixes #22387: No local account shown on windows

- webapp/sources/rudder/rudder-web/src/main/javascript/rudder/homePage.js
https://issues.rudder.io/issues/22671
> Fixes #22671: Inconsistent colors in hover on the dashboard

- relay/sources/Makefile
https://issues.rudder.io/issues/22768
> Fixes #22768: --break-system-packages is not recognized by older pip

- webapp/sources/rudder/rudder-web/src/main/javascript/rudder/homePage.js
https://issues.rudder.io/issues/22775
> Fixes #22775: inconsistence in hover color

- webapp/sources/rudder/rudder-web/src/main/webapp/secure/utilities/healthcheck.html
https://issues.rudder.io/issues/22774
> Fixes #22774: Heathcheck can not be displayed anymore

- webapp/sources/pom.xml
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/AutomaticReportsCleaner.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/CheckInventoryUpdate.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/PurgeUnreferencedSoftwares.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryProcessor.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/ItemArchiveManagerImpl.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/healthcheck/HealthcheckNotificationService.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlUnserialisationImpl.scala
- webapp/sources/rudder/rudder-core/src/test/scala/com/normation/cfclerk/services/JGitRepositoryTest.scala
- webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestJsEngine.scala
- webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/RudderUserDetailsTest.scala
https://issues.rudder.io/issues/22764
> Fixes #22764: Correct warning due to nowarn or release in 7.2 branch

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/technique.ps1
https://issues.rudder.io/issues/22785
> Fixes #22785: Method calls using a condition are not properly generated when a variable is used in the condition expression

- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/testing_variables_in_conditions/1.0/metadata.xml
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/testing_variables_in_conditions/1.0/rudder_reporting.cf
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/testing_variables_in_conditions/1.0/technique.cf
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/testing_variables_in_conditions/1.0/technique.json
- webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/testing_variables_in_conditions/1.0/technique.ps1
- webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestEditorTechniqueWriter.scala
https://issues.rudder.io/issues/22790
> Fixes #22790: Missing test for parent ticket

- webapp/sources/pom.xml
- webapp/sources/rudder/rudder-core/pom.xml
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/GitGC.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/InterpolatedValueCompiler.scala
https://issues.rudder.io/issues/22800
> Fixes #22800: Update webapp dependencies 

- webapp/sources/api-doc/components/schemas/rule.yml
https://issues.rudder.io/issues/22783
> Fixes #22783: missing parameters in ruledetails api response

- Jenkinsfile-security
- ci/rust.sh
- policies/Cargo.lock
- policies/Dockerfile
- policies/module-types/template/Cargo.toml
- policies/module-types/template/src/main.rs
- policies/module-types/template/tests/minijinja.rs
- policies/rust-toolchain.toml
- policies/supply-chain/audits.toml
- policies/supply-chain/config.toml
- policies/supply-chain/imports.lock
- relay/sources/relayd/Cargo.lock
- relay/sources/relayd/Cargo.toml
- relay/sources/relayd/Dockerfile
- relay/sources/relayd/rust-toolchain.toml
- relay/sources/relayd/supply-chain/audits.toml
- relay/sources/relayd/supply-chain/config.toml
- relay/sources/relayd/supply-chain/imports.lock
https://issues.rudder.io/issues/22816
> Fixes #22816: Use cargo vet to check Rust dependencies

- api-doc/build.py
https://issues.rudder.io/issues/22843
> Fixes #22843: API doc loads files from cdn.redoc.ly

- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
https://issues.rudder.io/issues/22807
> Fixes #22807: OS and hardware inventory information are not discoverable

- Jenkinsfile
- Jenkinsfile-security
- ci/rust.sh
- policies/supply-chain/audits.toml
- policies/supply-chain/config.toml
- policies/supply-chain/imports.lock
- relay/sources/relayd/supply-chain/audits.toml
- relay/sources/relayd/supply-chain/config.toml
- relay/sources/relayd/supply-chain/imports.lock
- webapp/sources/rudder/rudder-web/src/main/.nsprc
- webapp/sources/rudder/rudder-web/src/main/package-lock.json
https://issues.rudder.io/issues/22872
> Fixes #22872: 8.0 dependency check is broken

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryFileWatcher.scala
https://issues.rudder.io/issues/22874
> Fixes #22874: NPE gz inventory file is corrupted

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/ApplicationLogger.scala
https://issues.rudder.io/issues/22877
> Fixes #22877: API are not logged anymore

- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateCloneDirectivePopup.scala
- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateOrUpdateGlobalParameterPopup.scala
https://issues.rudder.io/issues/22880
> Fixes #22880: TODOs in the UI

- webapp/sources/rudder/rudder-web/src/main/elm/elm.json
- webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/JsonDecoder.elm
- webapp/sources/rudder/rudder-web/src/main/elm/sources/DirectiveCompliance/JsonDecoder.elm
- webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/JsonDecoder.elm
https://issues.rudder.io/issues/22881
> Fixes #22881: Update elm dependencies

- webapp/sources/rudder/rudder-web/src/main/elm/elm.json
- webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts.elm
- webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/DataTypes.elm
- webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/DatePickerUtils.elm
- webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/Init.elm
https://issues.rudder.io/issues/22882
> Fixes #22882: One last elm dependency

- relay/sources/relayd/Cargo.lock
- relay/sources/relayd/Dockerfile
- relay/sources/relayd/rust-toolchain.toml
- relay/sources/relayd/src/configuration.rs
- relay/sources/relayd/src/hashing.rs
- relay/sources/relayd/tests/shared_files.rs
https://issues.rudder.io/issues/22887
> Fixes #22887:  Update embedded openssl to 1.1.1u - relayd

- relay/sources/relayd/Cargo.toml
https://issues.rudder.io/issues/22889
> Fixes #22889:  Use system openssl for relayd - relayd

- webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder.js
https://issues.rudder.io/issues/22911
> Fixes #22911: JS diff library stop working

- Jenkinsfile
- ci/typos.Dockerfile
https://issues.rudder.io/issues/22924
> Fixes #22924: Typos-cli does not build anymore

- webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder.js
https://issues.rudder.io/issues/22919
> Fixes #22919: Long change request diff is unusable

- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/RudderUserDetails.scala
https://issues.rudder.io/issues/22908
> Fixes #22908: Exception in page when the user rights list is empty

- relay/sources/relayd/Cargo.lock
https://issues.rudder.io/issues/22943
> Fixes #22943: 

- policies/supply-chain/audits.toml
- policies/supply-chain/config.toml
- policies/supply-chain/imports.lock
- relay/sources/relayd/supply-chain/audits.toml
- relay/sources/relayd/supply-chain/config.toml
- relay/sources/relayd/supply-chain/imports.lock
https://issues.rudder.io/issues/22945
> Fixes #22945: Accept some dependencies with cargo vet

- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateCloneGroupPopup.scala
https://issues.rudder.io/issues/22702
The idea is to get the NodeGroup info refreshed, because when we clone we doesn't get back modifications that can be made without "Save" button up right
Property management is done by an angular app shared between node property and node group
> Fixes #22702: When we clone a group in Rudder 7.2, newly added properties are not cloned

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/properties/Properties.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/EventLogJdbcRepository.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogFactory.scala
- webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/properties/NodePropertiesTest.scala
https://issues.rudder.io/issues/22946
> Fixes #22946: NodeProperties value are not correctly serialized in event log

- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/Editor.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewBlock.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewMethod.elm
- webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechnique.elm
- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-technique-editor.css
https://issues.rudder.io/issues/22896
> Fixes #22896: Improving the display of Generic Methods in the Technique Editor for a better UX

- webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/properties/NodePropertiesTest.scala
- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/ShowNodeDetailsFromNode.scala
- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
https://issues.rudder.io/issues/22941
Make thing identical than in node search / "node summary"
> Fixes #22941: Titles are not consistant in the new Operatin System inventory tab with group search

- api-doc/Dockerfile
- ci/asciidoctor.Dockerfile
- ci/pylint.Dockerfile
- ci/shellcheck.Dockerfile
- ci/typos.Dockerfile
- docker/rudder-agent/cf-execd.Dockerfile
- docker/rudder-agent/cf-serverd.Dockerfile
- docker/rudder-relay-split/cf-execd.Dockerfile
- docker/rudder-relay-split/cf-serverd.Dockerfile
- docker/rudder-relay-split/httpd.Dockerfile
- docker/rudder-relay-split/relayd.Dockerfile
- docker/rudder-relay/Dockerfile
- language/Dockerfile
- policies/Dockerfile
- relay/sources/relayd/Dockerfile
- relay/sources/rudder-pkg/Dockerfile
- webapp/sources/Dockerfile
- webapp/sources/rudder/rudder-web/src/main/elm/Dockerfile
https://issues.rudder.io/issues/22914
> Fixes #22914: add label to rudder docker images

- relay/sources/Makefile
https://issues.rudder.io/issues/22951
> Fixes #22951: backport parent to 7.3

- SECURITY.adoc
- SECURITY.md
https://issues.rudder.io/issues/22964
> Fixes #22964: Fix our GitHub SECURITY file

- policies/rudderc/src/backends/windows.rs
- policies/rudderc/templates/technique.ps1.askama
- policies/rudderc/tests/cases/general/escaping/technique.ps1
- policies/rudderc/tests/cases/general/min/technique.ps1
- policies/rudderc/tests/cases/general/ntp/technique.ps1
- policies/rudderc/tests/cases/general/reporting/technique.ps1
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/InterpolatedValueCompiler.scala
https://issues.rudder.io/issues/22972
> Fixes #22972: Windows generator generates invalid syntax

- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderUserDetailsFile.scala
https://issues.rudder.io/issues/22967
> Fixes #22967: Spurious test error about length of generated password

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/EditorTechnique.scala
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/yaml/YamlTechnique.scala
- webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestEditorTechniqueWriter.scala
- webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/JsonEncoder.elm
- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/action/MigrateOldTechniques.scala
https://issues.rudder.io/issues/22975
> Fixes #22975: Correct scala tags encoder

- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderUserDetailsFile.scala
https://issues.rudder.io/issues/22980
> Fixes #22980: Error in parent correction

- webapp/sources/rudder/rudder-web/src/main/.nsprc
https://issues.rudder.io/issues/22984
> Fixes #22984: JS vulns in 8.0

- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/ncf/TechniqueReader.scala
- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/TechniqueApi.scala
- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/action/CheckNcfTechniqueUpdate.scala
- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala
https://issues.rudder.io/issues/22979
> Fixes #22979: improve error display

- webapp/sources/pom.xml
https://issues.rudder.io/issues/22989
Implementing what is documented here: https://github.com/com-lihaoyi/fastparse/issues/285#issuecomment-1614307764
> Fixes #22989: Finer grained warning exclusion for fastparse nowarn problem

- policies/rudderc/src/cli.rs
- policies/rudderc/src/lib.rs
- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueCompiler.scala
- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
https://issues.rudder.io/issues/22973
> Fixes #22973: Call rudderc with correct parameters

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala
https://issues.rudder.io/issues/23027
> Fixes #23027: Grammar correction in error message

- webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/common-layout.html
https://issues.rudder.io/issues/22626
> Fixes #22626: Beautify no permission page when user have no rights

- webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/ApiCalls.elm
- webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/DataTypes.elm
- webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/Init.elm
- webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/JsonDecoder.elm
- webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/JsonEncoder.elm
- webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/View.elm
- webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/ViewUtils.elm
- webapp/sources/rudder/rudder-web/src/main/elm/sources/Nodeproperties.elm
- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
- webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-datatable.css
- webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-main.css
- webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-node.css
- webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentNodeProperties.html
https://issues.rudder.io/issues/22741
This is part of the plan to completely remove AngularJs from Rudder, for reasons of security and code maintenance.
No new features have been added, this is a rewrite of the AngularJs "nodeProperties" application in Elm. 
The js files related to the old application have been removed
> Fixes #22741: Rewrite angular app "Node properties" in Elm

- webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/common-layout.html
https://issues.rudder.io/issues/23042
Replacing previous PR: https://github.com/Normation/rudder/pull/4881
> Fixes #23042: There is a blank space above almost every Rudder page

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueCompiler.scala
https://issues.rudder.io/issues/23049
> Fixes #23049: Wrong command to call rudderc in webapp

- webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/complianceMode.js
- webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentComplianceMode.html
https://issues.rudder.io/issues/22659
> Fixes #22659: Remove heartbeat configuration from the settings

- webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder.js
https://issues.rudder.io/issues/23057
> Fixes #23057: Remove old IE 5 & 6 JS compatibility code

- webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ApiCalls.elm
- webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/JsonDecoder.elm
https://issues.rudder.io/issues/23058
> Fixes #23058: Error when saving technique

- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
https://issues.rudder.io/issues/23062
Declare `NewNodeManagerHooks` at the different level needed:
- the first is the actual declaration in the return structure of init method, 
- the second is the API declaration in RudderConfig, with the name to use in datasource
- the following is the mod in the service init. It was hidden in `NewNodeManager`, need to take it appart and pass it in the return structure.
> Fixes #23062: Expose NewNodeManagerHooks in RudderConfig API

- relay/sources/Makefile
https://issues.rudder.io/issues/23082
> Fixes #23082: Backport to 7.2

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueCompiler.scala
https://issues.rudder.io/issues/23118
Remove unimplemented "linux only" rudderc call from webapp.
> Fixes #23118: Remove the rudderc "linux only" option from webapp

- policies/Cargo.lock
- policies/rudder-commons/Cargo.toml
- policies/rudder-commons/src/lib.rs
- policies/rudder-commons/src/report.rs
- policies/rudderc/src/backends/metadata.rs
- policies/rudderc/src/backends/unix/cfengine.rs
- policies/rudderc/src/backends/unix/ncf.rs
- policies/rudderc/src/backends/unix/prelude.cf
- policies/rudderc/src/compiler.rs
- policies/rudderc/src/ir/technique.rs
- policies/rudderc/src/lib.rs
- policies/rudderc/tests/compile.rs
- policies/rudderc/tests/lib/common/30_generic_methods/file_content.cf
- relay/sources/relayd/src/data/report.rs
- webapp/sources/pom.xml
https://issues.rudder.io/issues/23102
> Fixes #23102: Improve testing features

- policies/rudderc/docs/src/syntax.md
- policies/rudderc/docs/src/usage.md
https://issues.rudder.io/issues/23134
> Fixes #23134: Document JSON schema

- policies/rudderc/build.rs
- policies/rudderc/src/backends/unix.rs
- policies/rudderc/src/backends/unix/ncf/method_call.rs
- policies/rudderc/src/backends/windows.rs
- policies/rudderc/src/frontends.rs
- policies/rudderc/tests/cases/general/min/technique.ps1
- policies/rudderc/tests/cases/general/ntp/technique.cf
- policies/rudderc/tests/cases/general/ntp/technique.ps1
- policies/rudderc/tests/cases/general/ntp/technique.yml
- policies/rudderc/tests/cases/general/reporting/technique.ps1
https://issues.rudder.io/issues/23136
> Fixes #23136: Rudderc fails to render block conditions

- policies/rudderc/src/backends/unix/cfengine.rs
- policies/rudderc/src/cli.rs
- policies/rudderc/src/lib.rs
- policies/rudderc/tests/test.rs
https://issues.rudder.io/issues/23135
> Fixes #23135: Add an option to start the agent in verbose mode

- Jenkinsfile
- policies/rudderc/build.rs
https://issues.rudder.io/issues/23138
> Fixes #23138: Add versions to rudderc binaires

- policies/rudderc/src/backends/unix/ncf/method_call.rs
- policies/rudderc/tests/cases/general/ntp/technique.cf
https://issues.rudder.io/issues/23149
> Fixes #23149: Broken reports when condition is not defined

- policies/rudderc/docs/src/syntax.md
- policies/rudderc/src/ir/condition.rs
- policies/rudderc/src/technique.schema.json
- policies/rudderc/tests/cases/general/ntp/technique.cf
- policies/rudderc/tests/cases/general/ntp/technique.ps1
- policies/rudderc/tests/cases/general/ntp/technique.yml
https://issues.rudder.io/issues/23151
`true` and `false` are special value, let's accept them as boolean too.
> Fixes #23151: Allow booleans for condition fields

- webapp/sources/rudder/rudder-core/src/main/resources/ldap/bootstrap.ldif
- webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/migration/CheckAddSpecialNodeGroupsDescription.scala
https://issues.rudder.io/issues/23179
> Fixes #23179: Change description of "All Linux nodes" group

- policies/Cargo.lock
- policies/rudderc/Cargo.toml
- policies/rudderc/src/backends/unix.rs
- policies/rudderc/src/backends/unix/cfengine.rs
- policies/rudderc/src/compiler.rs
- policies/rudderc/src/frontends.rs
- policies/rudderc/src/lib.rs
- policies/rudderc/src/logs.rs
- policies/rudderc/src/main.rs
- policies/supply-chain/audits.toml
- policies/supply-chain/config.toml
- policies/supply-chain/imports.lock
https://issues.rudder.io/issues/23180
> Fixes #23180: Switch to tracing for logging

- policies/rudder-commons/src/logs.rs
- policies/rudderc/src/cli.rs
- policies/rudderc/src/logs.rs
- policies/rudderc/src/main.rs
https://issues.rudder.io/issues/23185
> Fixes #23185: Allow JSON output

- policies/rudderc/src/compiler.rs
- policies/rudderc/src/ir/value.rs
https://issues.rudder.io/issues/23194
> Fixes #23194: Warn on deprecated methods

- policies/rudder-commons/src/methods.rs
- policies/rudderc/src/doc.rs
- policies/rudderc/src/lib.rs
https://issues.rudder.io/issues/23195
> Fixes #23195: Fix JSON output of the lib command

- webapp/sources/rudder/rudder-web/src/main/javascript/rudder/directive-inputs.js
- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/model/DirectiveFieldEditors.scala
- webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/passwordInput.html
https://issues.rudder.io/issues/23200
> Fixes #23200: Password form in User directives does not works properly

- api-doc/package-lock.json
- api-doc/package.json
- webapp/sources/api-doc/introduction.md
- webapp/sources/api-doc/openapi.src.yml
https://issues.rudder.io/issues/23205
> Fixes #23205: Prepare API doc for 8.0

- webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-datatable.css
https://issues.rudder.io/issues/23004
> Fixes #23004: Interface color inconsistency for non compliance display

- webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-technique-editor.css
https://issues.rudder.io/issues/23177
> Fixes #23177: in the technique editor, the drop down list for condition is truncated

- webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/ApiCalls.elm
- webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/JsonDecoder.elm
- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala
- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
https://issues.rudder.io/issues/23181
> Fixes #23181: Cannot create group property because of missing UI

- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala
- webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentDirectiveEditForm.html
https://issues.rudder.io/issues/22830
> Fixes #22830: Message “Error getting directive compliance” when creating new directive

- ci/rust.sh
- policies/Cargo.lock
- policies/module-types/template/Cargo.toml
- policies/rudder-commons/Cargo.toml
- policies/rudderc/Cargo.toml
- policies/supply-chain/audits.toml
- policies/supply-chain/config.toml
- policies/supply-chain/imports.lock
- relay/sources/relayd/Cargo.lock
- relay/sources/relayd/Cargo.toml
- relay/sources/relayd/supply-chain/audits.toml
- relay/sources/relayd/supply-chain/config.toml
- relay/sources/relayd/supply-chain/imports.lock
https://issues.rudder.io/issues/23219
* Remove some unused dependencies
* Update build dependencies for 8.0
* Small dependencies upgrades
> Fixes #23219: Remove unused Rust dependencies

- webapp/sources/pom.xml
https://issues.rudder.io/issues/23221
https://spring.io/security/cve-2023-34034
> Fixes #23221: Update spring security

- webapp/sources/api-doc/openapi.src.yml
- webapp/sources/api-doc/paths/parameters/parameters-id.yml
- webapp/sources/api-doc/paths/parameters/parameters.yml
- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateOrUpdateGlobalParameterPopup.scala
- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/ParameterManagement.scala
- webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/parameterManagement.html
https://issues.rudder.io/issues/22379
> Fixes #22379: Rename "global parameters" to "global properties"

- relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py
https://issues.rudder.io/issues/23224
> Fixes #23224: rudder package doesn't upgrade openscap, and it brings a lot of chaos

- relay/sources/api-doc/components/parameters/file-id.yml
- relay/sources/api-doc/paths/shared-files.yml
- relay/sources/relayd/Cargo.lock
- relay/sources/relayd/Cargo.toml
- relay/sources/relayd/src/api.rs
- relay/sources/relayd/src/api/remote_run.rs
- relay/sources/relayd/src/api/shared_files.rs
- relay/sources/relayd/src/api/shared_folder.rs
- relay/sources/relayd/src/data/shared_file.rs
- relay/sources/relayd/src/output/database.rs
https://issues.rudder.io/issues/23226
> Fixes #23226: 

- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/SharedFilesAPI.scala
- webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/SharedFilesApiTest.scala
https://issues.rudder.io/issues/23225
> Fixes #23225: 

- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/SharedFilesAPI.scala
https://issues.rudder.io/issues/23229
> Fixes #23229: 

- webapp/sources/pom.xml
https://issues.rudder.io/issues/23230
> Fixes #23230: 

- webapp/sources/dependency-check-suppression.xml
https://issues.rudder.io/issues/23231
> Fixes #23231: CVE-2016-1000027 false positive detection

- webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/RestApiAccounts.scala
- webapp/sources/rudder/rudder-web/src/main/elm/accounts/sources/Accounts.elm
- webapp/sources/rudder/rudder-web/src/main/elm/accounts/sources/ApiCalls.elm
- webapp/sources/rudder/rudder-web/src/main/elm/accounts/sources/DataTypes.elm
- webapp/sources/rudder/rudder-web/src/main/elm/accounts/sources/ViewUtils.elm
- webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/apiManagement.html
https://issues.rudder.io/issues/23233
* Use token id instead of value in API URLs
* Everything was already in place for this to be done
* Display token id in API accounts table:
* Shorten the token value by removing some `*` to limit width increase
> Fixes #23233: 

- webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/api/DataStructures.scala
https://issues.rudder.io/issues/23228
> Fixes #23228: 

- policies/rudderc/src/backends/windows.rs
- policies/rudderc/templates/technique.ps1.askama
- policies/rudderc/tests/cases/general/escaping/technique.ps1
- policies/rudderc/tests/cases/general/form/technique.ps1
- policies/rudderc/tests/cases/general/min/technique.ps1
- policies/rudderc/tests/cases/general/ntp/metadata.xml
- policies/rudderc/tests/cases/general/ntp/technique.cf
- policies/rudderc/tests/cases/general/ntp/technique.ps1
- policies/rudderc/tests/cases/general/ntp/technique.yml
- policies/rudderc/tests/cases/general/reporting/technique.ps1
https://issues.rudder.io/issues/23240
> Fixes #23240: Windows technique generated function name is incoherent with the generated directives

- relay/sources/relayd/Cargo.lock
https://issues.rudder.io/issues/23247
> Fixes #23247: relayd build broken

- policies/rudderc/templates/technique.ps1.askama
- policies/rudderc/tests/cases/general/escaping/technique.ps1
- policies/rudderc/tests/cases/general/ntp/technique.ps1
https://issues.rudder.io/issues/23246
> Fixes #23246: Rudderc does not escape correctly the double quotes in componentKey in windows techniques

- policies/Cargo.lock
- policies/rudderc/Cargo.toml
- policies/rudderc/src/compiler.rs
- policies/rudderc/src/frontends.rs
- policies/supply-chain/audits.toml
- policies/supply-chain/config.toml
- policies/supply-chain/imports.lock
A lot of line numbers are incorrect, but that was already the case, I'll treat it in a separate PR.
> Fixes #23252: Improve serde deserialization error messages

- webapp/sources/api-doc/paths/settings/allowed_networks.yml
https://issues.rudder.io/issues/23267
> Fixes #23267: Update api doc for new response format for /settings/allowed_networks

- webapp/sources/rudder/rudder-web/src/main/javascript/rudder/homePage.js
- webapp/sources/rudder/rudder-web/src/main/javascript/rudder/tree.js
- webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-bootstrap.css
- webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-technique-editor.css
- webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-template.css
- webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/techniqueEditor.html
https://issues.rudder.io/issues/23274
> Fixes #23274: Speed up fadein animation of pages

- webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTechnique.elm
- webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTechniqueTabs.elm
- webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/View.elm
- webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/ViewRepairedReports.elm
- webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/ViewRuleDetails.elm
- webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/ViewTabContent.elm
- webapp/sources/rudder/rudder-web/src/main/elm/sources/TechniqueVersion/View.elm
- webapp/sources/rudder/rudder-web/src/main/elm/sources/TechniqueVersion/ViewUtils.elm
- webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder.js
- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala
- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleDisplayer.scala
- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala
- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala
- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/Archives.scala
- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala
- webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/manageNewNode.html
- webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/searchNodes.html
- webapp/sources/rudder/rudder-web/src/main/webapp/secure/utilities/archiveManagement.html
- webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentNodeProperties.html
- webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/NodeGroupForm.html
- webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/node_logs_tabs.html
- webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/reports_server.html
https://issues.rudder.io/issues/23275
Mostly capitalization cleanup.
> Fixes #23275: Improve some messages in the interface

- webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/ViewUtils.elm
https://issues.rudder.io/issues/23284
Not ideal but at least available.
> Fixes #23284: Add last generation time on regenerate button

- webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/TechniqueLibraryManagement.scala
- webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/policyServerManagement.html
- webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/techniqueLibraryManagement.html
- webapp/sources/rudder/rudder-web/src/main/webapp/secure/utilities/eventLogs.html
https://issues.rudder.io/issues/23286
> Fixes #23286: Improve some messages in the interface
