webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/EditorTechniqueReader.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueCompiler.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/migration/MigrateOldTechniquesService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/yaml/YamlTechnique.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitArchivers.scala
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/a_simple_yaml_technique/1.0/metadata.xml
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/a_simple_yaml_technique/1.0/technique.cf
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/a_simple_yaml_technique/1.0/technique.ps1
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/a_simple_yaml_technique/1.0/technique.yml
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/test_import_export_archive/1.0/metadata.xml
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestEditorTechniqueWriter.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/migration/TestMigrateOldTechniques.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ArchiveApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/TechniqueApi.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_directives.yml
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_techniques.yml
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/ArchiveApiTest.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/action/CheckNcfTechniqueUpdate.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/action/MigrateOldTechniques.scala

https://issues.rudder.io/issues/23155
Archive adaptation to YAML technique. 
Missing: compilation of YAML techniques. This is harder than it seems (because we have a dozen different "Technique" and we need to rationnalize a bit access to things). 
What is done: 
- we filter out generated files when exporting YAML
- when importing a JSON technique, we migrate it
There is also some changes:
- I tried to remove string for path/file names/etc. For example, I added `TechniqueFiles` that keeps all common technique file names, like `TechniqueFiles.yaml` is `technique.yml`. 
- `MigrateOldTechniquesService` is now in indep object that is used in both bootstrap migration and archive import
- I refactored `YamlTechniqueSerialization` so that:
- encode/decoder are pures (no I/O access) 
- they are in …

Fixes #23155: Regenerate yaml technique and filter generated files in rule archives

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/FileManager/Action.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/FileManager/Env.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/FileManager/Model.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/FileManager/Update.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/FileManager/Util.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/FileManager/View.elm
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-filemanager.css
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-main.css
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-technique-editor.css
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-template.css

https://issues.rudder.io/issues/23285
The aim of this PR is to restore the look and functionality of the previous filemanager to the new one. The new features are :
- the ability to switch the display to a table/grid format
- a search bar
- a sorting system
- a file tree

Fixes #23285: Change the display of the new filemanager to match the previous one

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/EditorTechniqueReader.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueCompiler.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/migration/MigrateOldTechniquesService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitArchivers.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestEditorTechniqueWriter.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestEditorTechniqueWriterFallback.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ArchiveApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/TechniqueApi.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/ArchiveApiTest.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/SharedFilesApiTest.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/action/CheckNcfTechniqueUpdate.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/action/MigrateOldTechniques.scala

https://issues.rudder.io/issues/23326
This PR needs https://github.com/Normation/rudder/pull/4925 to be merged. :heavy_check_mark: 
The main added changes are: 
- `TechniqueCompiler` earn more compilation methods to ease the different cases we know: `compile an EditorTechnique` (always needed for the fallback case) or `we just know the base path of technique` (archive, migration...). 
- `TechniqueCompiler` also get a "migrate json and regenerate yaml if needed", which is basically "do what need to be done to have an up-to-date technique
- On the other hand, I removed methods parameter, since it's only needed for the fallback case, which should not be the  most used (and so it's ok to have on demand query of these info). This change is on a separated commit for now to ease the review.
- …

Fixes #23326: Compile yaml technique on archive import

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/Authorizations.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/ApiDatastructures.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RoleApiMapping.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderUserDetailsFile.scala
webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/RudderUserDetailsTest.scala

https://issues.rudder.io/issues/23098
This PR add the possibility to have new/overridden built-in roles. 
For that, builtin roles are no more object but a case class `Builtin` and are identified by their name (lower case). 
We still keep two special roles, `Administrator` and `NoRights` since they have special semantic. 
Role trait also get a new `addAuthz` method to facilitate the extension of roles - since we don't wan't to remove authz to roles, and that semantic would not be very clear. (note: it could be still possible by making a new role with an existing name and less rights, but it's likely that rudder won't work well then for user with that role).
Then, we add a new `RudderRoles.registerBuiltin` method that will change builtin role set, either by overriding an existing one or …

Fixes #23098: Plugin cannot add custom roles or it will be overwritten by boot custom roles 

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestUtils.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/TechniqueApi.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ApiCalls.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/23352
Adds a new API to check whether a technique is valid or not (accepts a yaml, returns a json) to use to import a yaml technique
Modify getTechnique api to add a format parameter to return a yaml instead of a json to use to export a technique as yaml
modify the technique editor to use both new api/parameters

Fixes #23352: Import/Export yaml with technique editor

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/StatusReports.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/reports/StatusReportTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ExecutionBatchTest.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TestDirectiveComplianceCsv.scala

https://issues.rudder.io/issues/23084
Next step of https://github.com/Normation/rudder/pull/4897 and https://github.com/Normation/rudder/pull/4899
- we completely remove the pattern matching between expected component name & value and actual one for reports with a `reportId`
- we add a `reportId` field (default to `0` for case without a valid `reportId`) for `ComponentValueStatusReport` and addapt grouping in consequence, so that now, two report with same value but different report Id are splitted apart. 
- the grouping is done `componentName` then `reportId` then  `keyValue` to minimize change (reportId first look like we should have something on top of `ComponentStatusReport` with Id, which doesn't match well the current reports structure where each report brings reportid)
- adpat tests …

Fixes #23084: Remove constraint on component name pattern for matching reports

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueCompiler.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/TechniqueApi.scala
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTechnique.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTechniqueTabs.elm
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder.css
webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/migration/TestMigrateJsonTechniquesToYaml.scala

https://issues.rudder.io/issues/23357
The PR adds compilation output to technique api, output entry is defined if there is a valid compilation-output.yml file
it also add the display of it in technique editor, tab is displayed only if there is an output  
data are displayed within the tab if this the valus is not empty (no stdout in the screen, but stderr is displayed
Maybe we could add interpretation of Result code in a next PR (with a check if code is equal to 0, a cross for error return codes)

Fixes #23357: Display compilation output  in technique details

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/TechniqueApi.scala
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ApiCalls.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewMethodsList.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTechnique.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTechniqueList.elm

https://issues.rudder.io/issues/23381
This pr adds a way to display and edit a Technique yaml directly instead of using the editor UI
This feature is based on the check api that was added when adding yaml import, this api allow to check wether a technique is valid or not, it used to only accept yaml as input and responded a json.
I added a parameter to determine input and output types, (yaml or json) that allow to send a yaml and get back a json (will be used when we make some changes in our yaml and modify the technique in UI by getting back a valid json) 
But also to send a json and get a yaml back, so that we can send a json that represents what is currently displayed withtin the inventory and get back our  yaml representing what is displaed in the UI
I added a TechniqueEditInfo, which …

Fixes #23381: Allow to edit yaml in editor

---

relay/sources/relayd/Cargo.lock

https://issues.rudder.io/issues/23383

Fixes #23383: Update embedded openssl to 3.1 in relayd

---

webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ApiCalls.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ChangeRequest.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Init.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/JsonEncoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Rules.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/View.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRuleDetails.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewUtils.elm
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-template.css

https://issues.rudder.io/issues/23372
Putting back the change audit message / change request popup after it was removed when the rules interface was rewritten in version 7.0.
We want to control this popup in Elm, so we're rewriting an Elm module to handle change requests and change audit messages, which we're integrating into the Rules application.
The interface is almost identical to what existed before, the aim here is not to improve the user experience but to restore this functionality which had disappeared.

Fixes #23372: Add a way to set a message if "change audit logs" setting is enabled

---

webapp/sources/rudder/rudder-core/src/main/resources/reportsSchema.sql
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/PurgeOldInventoryData.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/db/Doobie.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/facts/nodes/NodeFact.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/NewNodeManager.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/RemoveNodeService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/history/impl/InventoryHistoryJdbcRepository.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/servers/TestRemoveNodeService.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/migration/MigrateNodeAcceptationInventories.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/NodeHistoryViewer.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/PendingHistoryGrid.scala
webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/migration/TestMigrateNodeAcceptationInventories.scala
webapp/sources/utils/src/main/scala/com/normation/utils/DateFormaterService.scala

https://issues.rudder.io/issues/23406
- create a json codec for `DateTime` in `DateFormaterService` so that it's available everywhere (`zio.json` is available in `utils`)
- we had a problem with log handler for sql statements, it has also a dedicated bug: https://github.com/Normation/rudder/pull/5037
- Until now, we were relying on `eventlog` to know who/when accepted/refused/deleted a node, which can be quite costly for deletion. We want to store these information in the `NodeFact` table so that it is self contained for clean-up. The data will be cleaned-up with the node inventory expiration time. There is duplication, but for immutable log data, and it's rather small (date, actor). 
-  we want to use the same structure for deletion and for accept / refuse => this first commit is just to …

Fixes #23406: Clean-up acceptation inventory

---

webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/groups.html

https://issues.rudder.io/issues/23184
Added a jumbotron to match the technique and directive pages.
The text inside may need to be adjusted

Fixes #23184: Add a placeholder description for groups page like for techniques and directives

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/facts/nodes/NodeFactRepository.scala
webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/23424
Add a new rudder config property, `rudder.facts.repo.writeNodeState`, that when true totally disable node fact-repos (replaced by a no-op implementation). The property is false by default (in new install and migration, too).

Fixes #23424: Make writing node state to fact repos optionnal

---

relay/sources/relayd/Cargo.lock

https://issues.rudder.io/issues/23447

Fixes #23447: Switch back to openssl 1.1 in relayd for now

---

webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala

https://issues.rudder.io/issues/23462
We forgot the clean-up the old "move to LDAP removed node branch" delete mode that was deprecated in Rudder 7.3. 
So limit risk, we just hard code choice to `DeleteMode.Erase` and delete the parameter from config file.
I don't thing a migration script/warn is needed, but a update note will be

Fixes #23462: Undocomment/remove parameter rudder.nodes.delete.defaultMode

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/JsonEncoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/ComplianceUtils.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/Init.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/ViewRulesTable.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/ViewTabContent.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/ViewUtils.elm
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-datatable.css
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-main.css
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-progress-bar.css
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-template.css
webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/ruleManagement.html

https://issues.rudder.io/issues/8166
Addition of a new filter based on compliance status. Users can now decide which statuses to hide or show.

Fixes #8166: Add filters on compliance tables to hide some kind of compliance

---

webapp/sources/rudder/rudder-web/src/main/elm/notifications/sources/Notifications.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Rules.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/View.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewCategoryDetails.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRuleDetails.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewUtils.elm
webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder-elm.js
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-template.css
webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/ruleManagement.html

https://issues.rudder.io/issues/23443
If change requests are enabled, the "Save" button is replaced by a "Create a change request" button.
Once a change request has been created, a success notification appears. This notification contains the link to the CR created, and only disappears if the user clicks on it :

Fixes #23443: After creating a change request, give the user a redirection link to its details

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/ExpectedReports.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/metadata.xml
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/reports/ExpectedReportTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ExecutionBatchTest.scala

https://issues.rudder.io/issues/23466
Focus Reporting logic, which is created to focus a "reportId", matches on component name in later parts of compliance check and not on Id (that we don't have yet, but in 8.0 yes) to fix this in 7.3 i need to translate ids when defining expected reports to a valid component to match.
I also added an id on each block in metadata.xml for techniques in technique editor (which was already defined, but disappeared in metadatra.xl) so that we can match on block children and not just on methods
This adds an id to some expectedBlocks, but since it is optionnal it won't break our serialisation

Fixes #23466: Focus reporting is not working 

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/JsonEncoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/View.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/ViewUtils.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Nodeproperties.elm

https://issues.rudder.io/issues/23482
Now we trim the name and the value of the property before saving it or testing if it is empty or already used.

Fixes #23482: Error when trying to add a JSON property to node

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/GitTechniqueReader.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/EditorTechnique.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/EditorTechniqueReader.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueCompiler.scala

https://issues.rudder.io/issues/23474
That was a bit more complicated than wished, because given the scenario (rudder loading, ncf techniquer regen, etc) we have several entry point where the code can read/load a technique and notice the user - and then, its on cache / not reparsed by technique lib, so the warning may not happen anymore. 
So the different entry point:
- `GitTechniqueReader`: for the case were user is compiling its yaml technique by hand, and then copying all the file into a bad path. We can only detect when the technique lib is reloaded that something is wrong
- `TechniqueCompiler`: that's the case where we are seing outdated generated files compared to `technique.yml` (at different point, notably on technique write) and call the compiler based on path
- …

Fixes #23474: Ensure yaml technique id and technique directory path agree

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/ViewUtils.elm

https://issues.rudder.io/issues/23492
Prevent default was making double click on checkbox keeping its status. 
Also add indeterminate status through property
[Screencast from 2023-09-28 14-29-00.webm](https://github.com/Normation/rudder/assets/1238978/0f114760-6a67-4c8d-8d11-641e81dd478e)

Fixes #23492: Compliance filter is not clear enough when disabling a group of reports

---

policies/rudderc/docs/src/test.md
policies/rudderc/src/compiler.rs
policies/rudderc/tests/cases/general/escaping/metadata.xml
policies/rudderc/tests/cases/general/escaping/technique.cf
policies/rudderc/tests/cases/general/escaping/technique.ps1
policies/rudderc/tests/cases/general/escaping/technique.yml

https://issues.rudder.io/issues/23551
This happens only when using double-quoted strings in YAML. In this case some special chars are escaped using a backslash. We end up with parameters containing unwanted chars (like backspace from `\b`). In addition `quick_xml` does not check its input for forbidden chars, and happily generates invalid XML.
This PR makes a first line of check at the end of the pipeline, to prevent writing broken files. We should find a better way to handle this (but it is tricky as using these escaped chars it is often not what users want...), and maybe make quick_xml properly escape these chars.

Fixes #23551: Broken handling of non-printable characters in techniques

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueCompiler.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitArchivers.scala
webapp/sources/rudder/rudder-web/src/test/resources/configuration-repository-migrate-json-8_0/post-migration/ncf_techniques/technique_with_blocks/1.0/rudder_reporting.cf
webapp/sources/rudder/rudder-web/src/test/resources/configuration-repository-migrate-json-8_0/techniques/ncf_techniques/technique_with_blocks/1.0/rudder_reporting.cf
webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/migration/TestMigrateJsonTechniquesToYaml.scala

https://issues.rudder.io/issues/23547

Fixes #23547: Remove technique.json and rudder_reporting.cf when migrating technique to new format

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/JsonResponseObjects.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/EditorTechnique.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueCompiler.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/migration/MigrateJsonTechniquesService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/yaml/YamlTechnique.scala
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/testing_variables_in_conditions/1.0/metadata.xml
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/testing_variables_in_conditions/1.0/technique.cf
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/testing_variables_in_conditions/1.0/technique.yml
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/1.0/metadata.xml
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/1.0/technique.cf
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/1.0/technique.yml
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/2.0/metadata.xml
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/2.0/technique.cf
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/metadata.xml
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/technique.cf
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/technique.yml
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestEditorTechniqueWriter.scala
webapp/sources/rudder/rudder-web/src/test/resources/configuration-repository-migrate-json-8_0/post-migration/ncf_techniques/technique_with_parameters/1.0/metadata.xml
webapp/sources/rudder/rudder-web/src/test/resources/configuration-repository-migrate-json-8_0/post-migration/ncf_techniques/technique_with_parameters/1.0/technique.cf
webapp/sources/rudder/rudder-web/src/test/resources/configuration-repository-migrate-json-8_0/post-migration/ncf_techniques/technique_with_parameters/1.0/technique.ps1
webapp/sources/rudder/rudder-web/src/test/resources/configuration-repository-migrate-json-8_0/post-migration/ncf_techniques/technique_with_parameters/1.0/technique.yml
webapp/sources/rudder/rudder-web/src/test/resources/configuration-repository-migrate-json-8_0/techniques/ncf_techniques/technique_with_parameters/1.0/metadata.xml
webapp/sources/rudder/rudder-web/src/test/resources/configuration-repository-migrate-json-8_0/techniques/ncf_techniques/technique_with_parameters/1.0/rudder_reporting.cf
webapp/sources/rudder/rudder-web/src/test/resources/configuration-repository-migrate-json-8_0/techniques/ncf_techniques/technique_with_parameters/1.0/technique.cf
webapp/sources/rudder/rudder-web/src/test/resources/configuration-repository-migrate-json-8_0/techniques/ncf_techniques/technique_with_parameters/1.0/technique.json
webapp/sources/rudder/rudder-web/src/test/resources/configuration-repository-migrate-json-8_0/techniques/ncf_techniques/technique_with_parameters/1.0/technique.ps1
webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/migration/TestMigrateJsonTechniquesToYaml.scala

https://issues.rudder.io/issues/23555
Principal changes: 
- add a `variableName` in `EditorTechnique -> parameters`. This is the canonified version of the parameter, the one used in .cf and .ps1 files, 
- remove `canonify` from `NcfId` since we now have access to it in technique param directly
- when we read old technique, do the canonification of `name` for params, and put the result in `variableName`
- map yaml field `name` to editor `variableName`, and `description` to editor `name` 
I didn't touch `JResponseObject`, they will likely need to be updated to add `variableName` field etc

Fixes #23555: When migrating json technique to yaml, canonify parameter name

---

webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewMethod.elm

https://issues.rudder.io/issues/23564

Fixes #23564: Always display generic method name

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/MethodConditions.elm

https://issues.rudder.io/issues/23541
Still a draft while we discuss compatiblity https://rudderio.slack.com/archives/C3X0V8ZL6/p1696609924041829
I considered doing something "smarter" than an big enum, but it seems nothing makes sense if we want to keep it easy to use. We could put the enum on a second level but it would require more clicks and the amound os supported OS versions should stay faily low. Plus it is after Linux in the list so most users won't need to scroll anyway.

Fixes #23541: Add new Windows OS conditions to the technique editor

---

policies/rudderc/src/frontends.rs
policies/rudderc/src/ir/technique.rs

https://issues.rudder.io/issues/23568

Fixes #23568: Mark yaml format as 1.0

---

policies/minifusion/Cargo.toml
policies/minifusion/src/main.rs
policies/rudderc/tests/test.rs

https://issues.rudder.io/issues/23573

Fixes #23573: Make sources compatible with Windows

---

policies/rudderc/src/backends/windows.rs
policies/rudderc/templates/technique.ps1.askama
policies/rudderc/tests/cases/general/long_method_param_name/technique.ps1
policies/rudderc/tests/lib/common/30_generic_methods/package_present.cf
policies/rudderc/tests/lib/common/30_generic_methods/package_present.yml

https://issues.rudder.io/issues/23581

Fixes #23581: Missing NA report on Windows for methods only compatible with Unix

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueCompiler.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/23582
The code parsing `CmdResult` into `RuddercResult` was duplicated with a different logic, it seems due to a refactor not finalized. 
Totally remove `RUDDERC_FALLBACK_RETURN_CODE` logic, we are prefering to have a specific error code for user-directed errors. 
Also add the `userMessage` param in the parsing to have the same param available in `RuddercResult`.

Fixes #23582: Rudderc error code interpretation is done at two places inconsistently

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTechnique.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTechniqueTabs.elm

https://issues.rudder.io/issues/23587

Fixes #23587: Add checks annd validation on parameter name

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/SearchNodeComponent.scala

https://issues.rudder.io/issues/23320
form was added using a raw js script, doing a jquery.replace(id, 'content') where content was a the string containing the new form to insert. if this forms include a ' , the string is then broken.
Using List replace jscommand instead will sanitize your content correctly and escape the single quote

Fixes #23320: Quotes in group name generate JS errors when using GroupId criteria

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/appconfig/ConfigService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ArchiveApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SettingsApi.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_settings.yml
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/ArchiveApiTest.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/23591
Remove the Feature switch and related tests and settings. Nothing fancy, I hope I didn't missed anything. 
Nothing special to do for migration, it is not important to have old settings in LDAP.

Fixes #23591: Feature switch for archive API is still present

---

webapp/sources/pom.xml
webapp/sources/rudder/rudder-core/pom.xml
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/GitGC.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/SharedFilesApiTest.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderUserDetailsFile.scala

https://issues.rudder.io/issues/23609
Update libraries to version without observable changes, or to version with changes already tested in Rudder 8.0 branches (jgit, graalvm). In the latest case, backport Rudder 8.0 changes.

Fixes #23609: Assessments of several low impact CVE in current 7.3.x reported by contrastsecurity tool 

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/policies/DirectiveDiff.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/policies/PolicyMode.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDiffMapper.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogDetailsService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogFactory.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/modification/DiffService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/EventLogDetailsGenerator.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala

https://issues.rudder.io/issues/15019
* Adding a `defaultValue` constant in `PolicyMode` that is used across many files to specify that the policy mode is inferred from the global context
* Add display of diffs for tags using 'simple lines diff' (the same that is used when displaying diffs on properties) :
* Add display of diffs also for the policy mode of a directive :

Fixes #15019: Tag are not displayed with a nice diff in eventLog 

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/SearchNodeComponent.scala

https://issues.rudder.io/issues/16094
The `input` element was only _enabled_ or _disabled_, we needed to also set the value to "" when the comparator cannot have a value (that's the case for the `is defined` or `is not defined` comparators)

Fixes #16094: When we search by "is defined" in the group search, we get the previous search value displayed

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/ViewUtils.elm

https://issues.rudder.io/issues/23639

Fixes #23639: Do not apply syntax highlighting to string properties

---

policies/rudder-commons/src/lib.rs
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/EditorTechniqueReader.scala
webapp/sources/rudder/rudder-core/src/test/resources/ncf/generic_methods.json

https://issues.rudder.io/issues/23607
In 8.0, rudderc has (inadvertently) changed the output format from a list of plain strings to a list of
```json
{
"name": "optional",
"value": "previous value"
}
```
And regex from a string to:
```json
{
"error_message": "optional",
"value": "previous value"
}
```
This change was not expected in the webapp, but the parser for this file was rewritten at the same time, with a typo on the constraint key name (`constraint` instead of `constraints`), which lead to totally ignoring constraints (and hide the error).
As the change in rudderc was made to improve consistency with select parameter type in techniques, this PR changes the expected format on the webapp side. We can do this as rudderc and the webapp come in the same package and are always in sync. …

Fixes #23607: When a mandatory field in a technique is not defined, we can save a technique and we have a nasty error

---

webapp/sources/rudder/rudder-web/pom.xml
webapp/sources/rudder/rudder-web/src/main/elm/rules/elm.json
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRepairedReports.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/tests/ViewRepairedReportsTest.elm

https://issues.rudder.io/issues/22518
I removed the seconds from the formatted date (see the unit tests for examples of what will be displayed)

Fixes #22518: Recent changes drop down cannot be read

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchBackendImpl.scala

https://issues.rudder.io/issues/23665
The "match may not be exhaustive" warning should always be fixed (it will be setup in compiler options in a separate PR)

Fixes #23665: Search bar will not work with filters

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder.js
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/UserInformation.scala

https://issues.rudder.io/issues/23010
The ajax button no longer works after logout because the session is already terminated and all ajax variables mapping are cleaned in Lift...
We need to know if user is already logged out, in that case we do simply redirect instead of making the ajax call.

Fixes #23010: When we are logged out, the logout button doesn't work

---

webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechniqueTabs.elm
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-technique-editor.css
webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/techniqueEditor.html

https://issues.rudder.io/issues/23610
The button has been replaced by a checkbox labelled 'Required'. If it's checked, it means it cannot be empty, it's as simple as that :

Fixes #23610: The "Required/May be empy" button in the parameters of a technique is not intuitive enough

---

webapp/sources/rudder/rudder-templates-cli/src/main/scala/com/normation/templates/cli/TemplateCli.scala

https://issues.rudder.io/issues/23684
The first one in the series of 'migration from lift-json to zio-json' :partying_face: 
A `Json.Obj` is just a `Chunk[(String, Json)]` as a collection of pair in zio-json

Fixes #23684: Migrate rudder-templates-cli package to zio-json

---

webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/a_simple_yaml_technique/1.0/resources/something.txt
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ArchiveApi.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/ArchiveApiTest.scala

https://issues.rudder.io/issues/23688
Add a check that Technique ID from path pattern matches technique from descriptor for YAML and JSON case after parsing the descriptor. We already have everything, just need to test at the correct place. 
The most part of the change is an unit test.

Fixes #23688: Import archive must refuse yaml technique with mismatch directory and id

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/FileManager/Action.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/FileManager/Model.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/FileManager/Port.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/FileManager/Update.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/FileManager/Util.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/FileManager/wrapper.js
webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/techniqueEditor.html
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentDirectiveEditForm.html

https://issues.rudder.io/issues/23606
We don't want the user to rename a file with invalid characters : we display a notification, and we can also avoid making an API request.
Also, when a API request fails, a generic error message will be displayed as notification

Fixes #23606: Creating files with the file explorer fails when using invalid character

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RudderJsonRequest.scala

https://issues.rudder.io/issues/23707
It is about moving code from [a plugin](https://github.com/Normation/rudder-plugins-private/pull/468/files#diff-53797078b2054da1a7e7aee8e315cd630043045f9e1ff19916e01a88a39c32e1L26), because it needs to be shared by many plugins and also probably in the API endpoints definitions when migrating lift-json to zio-json...

Fixes #23707: Implement common zio-json utils for plugins in rudder 

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/EventLogRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/EventLogJdbcRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogServiceImpl.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/InventoryEventLogServiceImpl.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/EventLogAPI.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/EventLogDetailsGenerator.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/EventListDisplayer.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/LogDisplayer.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/EventLogsViewer.scala
webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/migration/TestMigrateSystemTechnique7_0.scala

https://issues.rudder.io/issues/23724
So, most of the PR is about changing string to `doobie.Fragment` which leads to correctly escaped prepared statement (ie `?` + parameter). 
I also cut down information going back to UI, and kept the SQL errors for people able to see webapp logs.
Some subtilities:
- we need to parse `asc` `desc` because they are SQL keyword, so can't be passed with fragment (it seems)
- we need to use correct types for fragments, so for example we need `java.sql.Timestamp` in place of strings
- `Fragment.const` is necessary only for case where we want to avoid to interpolate (in the SQL prepared statement way) a variable but interpolate it as a string. I chose to use it for anything without SQL variable, included constant strings
There does not seems to have a lot of …

Fixes #23724: 

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RudderJsonResponse.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ArchiveApi.scala

https://issues.rudder.io/issues/23736
When migrating from lift-json to zio-json, we do not currently have a way in our zio-json custom definitions to provide an `id` in the json response in case of error. We will need that in order to be compatible and have the same output when migrating.

Fixes #23736: Implement common utils for compatibility of zio-json API response

---

webapp/sources/pom.xml
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/JsonQueryObjects.scala

https://issues.rudder.io/issues/23737
The new version of chimney warns about some deprecated API (that we do not use), and allows a better separation of concerns with implicit instances and derivation according to [the documentation](https://chimney.readthedocs.io/en/stable/cookbook/#automatic-semiautomatic-and-inlined-derivation) : `import io.scalaland.chimney.syntax._` can be used where there is already an implicit `Transformer` in scope, whereas the `import io.scalaland.chimney.dsl._` additionally `import io.scalaland.chimney.auto._` to generate automatic transformers :scream_cat:. 
Recommended usage would be : 
* not use automatic derivation, which is often the case by importing `dsl._`, so avoid using this import 
* import `syntax._`  when there are already instances declared with …

Fixes #23737: Update to chimney 0.8.2

---

webapp/sources/pom.xml

https://issues.rudder.io/issues/23657
"match may not be exhaustive" compiler warning should be an error :scream:
**Edit :** I had to fix other warnings such as unused imports

Fixes #23657: Compiler warnings should prevent build

---

webapp/sources/rudder/rudder-core/src/test/scala/com/normation/BoxSpecMatcher.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/JsonSpecMatcher.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TraitTestApiFromYamlFiles.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala

https://issues.rudder.io/issues/23741
Now when testing for json equality (for instance in this test class [here](https://github.com/Normation/rudder/blob/e62443c97bbcd4f08516479fd974b658b5383438/webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TestRestFromFileDef.scala#L93)), we can call `doTest(Nil, semanticJson = true)` that will check for semantic equality only (key-values in json object have no order).
We could as well do :
```scala
doTest(List("api_x.yaml")) // false by default
doTest(List("api_x.yaml", "api_y.yaml"), semanticJson = true)
```
!

Fixes #23741: Testing json from API definitions in YAML should have a nice display

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder-datatable.js

https://issues.rudder.io/issues/23747
This bug was introduced when we upgraded to version 3 of chart.js. We were still using the syntax from v2 of chart.js, but it has changed in v3.

Fixes #23747: Using deprecated chart.js options generates errors in the console

---

relay/sources/rudder-package/src/archive.rs
relay/sources/rudder-package/src/cli.rs
relay/sources/rudder-package/src/database.rs
relay/sources/rudder-package/src/lib.rs
relay/sources/rudder-package/src/plugin.rs
relay/sources/rudder-package/src/repository.rs

https://issues.rudder.io/issues/23773

Fixes #23773: Make rudder-package able to uninstall packages

---

webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-finished/50-reload-policy-file-server

https://issues.rudder.io/issues/23783

Fixes #23783: Copy the certificates directly without calling the agent after generation

---

webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/facts/nodes/TestSaveInventory.scala

https://issues.rudder.io/issues/23786
Add a retry on the check for the callback part since it is async and can fail. 200 ms should be enough for all case, as Microsoft says.

Fixes #23786: Inventory accept test sometimes fails on callback check

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/queries/CmdbQuery.scala

https://issues.rudder.io/issues/23671
This is a simple fix, it only affects the JavaScript date picker module in group criteria that was not sync with the expected [defined format](https://github.com/Normation/rudder/pull/5201/files#diff-5192ead8ee6e8bbdfc1c1de061965986ff9d79c1e6216b2dc3ac06ba68e61582L567) in the backend to `dd/MM/yyyy`.
In this case, this bug affects the criteria `Last inventory date` in group criteria page. It appears that the format of inventory date is like `2023-08-17 14:31:49+0200` so to the format `yyyy/mm/dd`.
I think the date picker should use the same format. Despite the fact that the date picker and the inventory date doesn't use the same format, this PR fix the problem and the filter seems to work
This is not an ideal solution since we use the format …

Bug #23671 : Locale issue: date picker outputs date in wrong order 

---

Jenkinsfile
relay/sources/Makefile
relay/sources/rudder-package/Cargo.lock
relay/sources/rudder-package/Cargo.toml
relay/sources/rudder-package/Dockerfile
relay/sources/rudder-package/rust-toolchain.toml
relay/sources/rudder-package/src/archive.rs
relay/sources/rudder-package/src/cli.rs
relay/sources/rudder-package/src/config.rs
relay/sources/rudder-package/src/database.rs
relay/sources/rudder-package/src/dependency.rs
relay/sources/rudder-package/src/lib.rs
relay/sources/rudder-package/src/license.rs
relay/sources/rudder-package/src/list.rs
relay/sources/rudder-package/src/plugin.rs
relay/sources/rudder-package/src/repo_index.rs
relay/sources/rudder-package/src/repository.rs
relay/sources/rudder-package/src/versions.rs
relay/sources/rudder-package/src/webapp.rs
relay/sources/rudder-package/tests/database/plugin_database_update_sample.json.expected
relay/sources/rudder-package/tests/licenses/example.license
relay/sources/rudder-package/tests/webapp_xml/example.xml
relay/sources/rudder-package/tools/rudder-package.sh

https://issues.rudder.io/issues/23780
* All data sources are now defined once and passed to the different modules
* Fixes a few commands, especially enable/disable.
* Index is now an `Option<RepoIndex>`
* `jar_files` is now a simple `Vec<>` instead of `Option<Vec<>>`, as there were no semantic differences between `Some(vec![])` and `None`.
* Latest version selection from index is fixed using version ordering.
* Added a `PluginType` and display it.
Update 28 nov.:
* Licenses parsing and display in list
* Fixed upgrade process
* Don't fail on first error but treat all passed packages in all commands
* Enforce HTTPS (to mitigate the risk of malicious index)
Added a few pieces:
* `upgrade --all` (and also allow `upgrade <package>`)
* `upgrade --all-postinst`
* `disable --incompatible` …

Fixes #23780: Implement missing commands

---

policies/rudderc/src/frontends/methods/method.rs
policies/rudderc/tests/methods/package_install.cf

https://issues.rudder.io/issues/23798
Modify the regex to prevent capturing previous bundle calls in the match, so we're matching each bundle, and get back on the previous "first bundle is the main bundle" convention.
Before 
After

Fixes #23798: rudderc method parsing breaks when method contains several bundles

---

webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechniqueList.elm

https://issues.rudder.io/issues/23801
Before : 
After: ![image](https://github.com/Normation/rudder/assets/23410978/6f443d7f-7da8-4b65-9acc-05f4a2891fa7)

Fixes #23801: Content of warning tooltip for unknow method should not overflow

---

webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/LiftInitContextListener.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/23735
The only message that an `ExceptionInInitializerError` provides is `null`, so we do not want to show the message but the cause instead...
Also for config value errors, adopting a standard error format and catching errors could always be beneficial so I used that to improve the errors logs during boot when config errors should prevent the server from running...   
I also took into account the suggestions to add comments to the sample configuration file, and use the main value `rudder.batch.reportsCleaner.deleteLogReport.TTL` in the configuration in favor of `rudder.batch.reportsCleaner.deleteReportLog.TTL` (which we do not use in the code)

Fixes #23735: Exception when bad input for inventory duration config

---

policies/_typos.toml
policies/rudder-commons/src/lib.rs
policies/rudderc/src/backends/unix/ncf/method_call.rs
policies/rudderc/src/backends/windows.rs
policies/rudderc/src/ir/technique.rs
policies/rudderc/src/technique.schema.json
policies/rudderc/templates/technique.ps1.askama
policies/rudderc/tests/cases/general/policy_mode/metadata.xml
policies/rudderc/tests/cases/general/policy_mode/technique.cf
policies/rudderc/tests/cases/general/policy_mode/technique.ps1
policies/rudderc/tests/cases/general/policy_mode/technique.yml

https://issues.rudder.io/issues/23799

Fixes #23799: Make rudderc able to compile techniques using a per method policy mode override

---

policies/.gitignore
policies/rudderc/docs/src/usage.md
policies/rudderc/src/cli.rs
policies/rudderc/src/ir/condition.rs
policies/rudderc/src/lib.rs
policies/rudderc/tests/compile.rs
policies/rudderc/tests/export.rs

https://issues.rudder.io/issues/23802
* Remove the `export` subcommand as we now need to be able to build the techniques, hence identical parameters to `build`, so it becomes an option of the `build` command
* Fix condition serialization. For some reason the `false` condition was serialized to `null`.
* Run export test on all test techniques, and also check validity of the `technique.ids.yml` file by re-building it.

Fixes #23802: rudderc should export a technique with ids

---

policies/rudderc/src/frontends.rs
policies/rudderc/src/ir/technique.rs

https://issues.rudder.io/issues/23332
Solves probably 75% of the problem with a low effort.
The idea is to avoid parsing an untagged enum with serde (as it totally breaks error reporting), and use a plain struct instead, and then convert manually to the different kinds.
The higher level errors still do not point to a line in the source (but it was never the case, and would require heavy lifting, like replacing serde with a lower level YAML parser), but all reporting error line are now correct.

Fixes #23332: Serde errors do not point to the correct line number

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryProcessor.scala

https://issues.rudder.io/issues/23827
* We do not check the keyid in the signature file so we're not sure trh problem is that the key is different
* We now use a certificate everywhere
* API doc URL update

Fixes #23827: Update the error message for failed inventory signature check

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewBlock.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewMethod.elm
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-technique-editor.css

https://issues.rudder.io/issues/23764
The view for the block had no labels for the "name" input : we add `Block name` and `Method name` respectively as labels for block and method components. I copied the same elements structure as for the methods to make the view of the block similar. 
Also, I renamed the placeholder of both inputs to "Enter a friendly name for this component"  :

Fixes #23764: Change "Name" to something else in the technique editor

---

policies/rudderc/src/backends/metadata.rs
policies/rudderc/tests/cases/general/escaping/technique.yml
policies/rudderc/tests/cases/general/form/metadata.xml
policies/rudderc/tests/cases/general/ntp/metadata.xml

https://issues.rudder.io/issues/23847
do the same as select one https://github.com/Normation/rudder/pull/5238/files#diff-9cccbc1bdfe2c43e82d1ceaafe377789de820f127ed601aae82b0ea883225653L139 than classic input
name in metadata.xml is the description of the parameter, long_description the documentation

Fixes #23847: For technique parameter, name, id and doc are mixed up

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/migration/MigrateEventLogEnforceSchema.scala
webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/migration/TestMigrateEventLogEnforceSchema.scala

https://issues.rudder.io/issues/23836
The current migration have some cost with queries such as `UPDATE col SET col=${defaultValue} WHERE col is NULL`, we want to avoid doing that when we know the migration was already applied : it is a simple check on whether the column is nullable or not, from the PG table `information_schemas.columns`.
The should be executed if the result of the check on the column returns a row : 
```sql
SELECT DISTINCT column_name, table_name, is_nullable
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE table_name = tablename AND column_name = migrationcolumn and is_nullable = 'YES'
```
We add a debug log to inform when the migration does not need to be made, and we improve the error log whenever the migration fails (also added database tests)

Fixes #23836: Event log migration should not be done every time

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/migration/DbCommonMigration.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/migration/MigrateChangeValidationEnforceSchema.scala
webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/migration/TestMigrateChangeValidationEnforceSchema.scala

https://issues.rudder.io/issues/23837
We need to add `NOT NULL` constraint to the change-validation plugin tables, in order to enforce the table schema  (until now there does not seem to be a `null` value that has been written in the table, in that case the migration would fail but the user would have a nice error log). I added database tests.
Note that this PR is very similar to https://github.com/Normation/rudder/pull/5232

Fixes #23837: Enforce change request and workflow table schema

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala

https://issues.rudder.io/issues/23869
This bug was introduced by https://github.com/Normation/rudder/pull/5236
Since the property module is shared between the node property page and the group property page, we should reflect changes
In #5236  we have renamed the `hasWriteRights` because some other module was using the same naming (for AgentSchedule) and was interfering with the write rights for the properties

Fixes #23869: Cannot add properties to a group

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeCompliance/ViewUtils.elm

https://issues.rudder.io/issues/23895

Fixes #23895: We can access system rules detail page from node system status tab

---

relay/sources/Makefile

https://issues.rudder.io/issues/23901

Fixes #23901: Missing rudder-pkg folder as destination for old python rudder package

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/ReportType.scala

https://issues.rudder.io/issues/23915
We have no way to decide wether a policy is sending report for correct mode or not since it can now be embedded within the technique details. and can produce report for a different type

Fixes #23915: Remove BadPolicyMode case from computation

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateCategoryOrGroupPopup.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateCloneGroupPopup.scala

https://issues.rudder.io/issues/22170
Nothing special: just remove the init of group at creation, only let `None` - it doesn't seems to break anything (generation, test, coming back to the group page, update dyn groups, api - at least)

Fixes #22170: A new group display no nodes while all linux are selected

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/policies/RuleTarget.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/policies/RuleTargetTest.scala

https://issues.rudder.io/issues/23446
I think we don't want to modify event logs (as a general rule). We should perhaps be able to store old event logs in a "cold storage" (other table, or crypted file, or whatever) and wait for old format to disappear. 
In the meantime, we will just parse the old and new format (it's extermelly limited in that case, so almost without impact)

Fixes #23446: Change request on special:all_nodes_without_role lead to error

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/plugins/PluginStatus.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/plugins/PublicPlugin.scala

https://issues.rudder.io/issues/23932
Some explanation within issue description. The goal here is to be coherent between the trait and all implementation (All to def), this breaks release of some plugins

Fixes #23932: Plugin license implementation is not coherent with interface

---

webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentDirectiveEditForm.html

https://issues.rudder.io/issues/23947
The `id` was deleted in the [bootstrap 5 upgrade](https://github.com/Normation/rudder/pull/5169/files#diff-bd1e6a527605fee54932f2d475c7ed5f1428a5ae0dbd4cccbea39b9054b84af8L96)

Fixes #23947: Directive compliance page loads infinitely

---

policies/rudderc/src/compiler.rs

https://issues.rudder.io/issues/23953

Fixes #23953: Improve rudderc error message when a parameter is missing from a method call

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/policies/RuleApplicationStatus.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/policies/RuleTarget.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/facts/nodes/NodeFact.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/NodeGroupRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/RuleApplicationStatusService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/RuleValService.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/policies/RuleTargetTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/RuleValServiceTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestBuildNodeConfiguration.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/UserService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/ApiAuthorization.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ArchiveApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ComplianceApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/DirectiveApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/GroupsApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ParametersApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/RuleApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SettingsApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/TechniqueApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/CurrentUser.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TraitTestApiFromYamlFiles.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleGrid.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/ExpectedPolicyPopup.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ComplianceData.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/HomePage.scala

https://issues.rudder.io/issues/23856
So this PR brings several things: 
- (a port of https://github.com/Normation/rudder/pull/5267)
- make compliance computation aware of `QueryContext` 
- the last one is a technical change so that `QueryContext` are provided in API `authzToken` parameter, and so we are really able to start porting APIs. 
Well, there is none, because we did the things correctly: compliance computation takes a list of nodes and everything is node-centric. So we are just passing the correct list based on the user tenant, and most of the changes are just about "correctly weaving from web context to compliance computation the `QueryContext` to be able to have the list of node based on tenants".
The main change is in `RuleApplicationStatusService.isApplied` and …

Fixes #23856: Impact of RBAC node filtering on compliance

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/NewNodeManager.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/22197
Not sure what happened in the last refactoring, but here, the failure was yield (as a `Full(Failure(..))` in place of being flatMapped. 
Also: I remove the possibility to write several time the hostname, we know they are all the same, since that's what we are checking. 
Finaly, move that check in first place, because it's really useless to move into accepted, then rollback into pending if the hostname is duplicated: just start by checking if it's ok or not to move.

Fixes #22197: We can accept a node with an existing hostname even if node_accept_duplicated_hostname is false

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/policies/RuleTarget.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RoleApiMapping.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/Compliance.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ComplianceApi.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_compliance.yml
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TestRestFromFileDef.scala

https://issues.rudder.io/issues/23935
This adds two endpoints that return compliance computation by node group : 
- one `/compliance/groups/{id}` for global compliance by taking into account any rule that apply to nodes within the group
- another `/compliance/groups/{id}/target` for targeted compliance by taking into account only rules that target the group (using include/exclude targeting)
In the yaml tests I used concrete examples (a simple one and a more complex one) and the result correspond to what is expected with a some caveats : 
- lists are not sorted, and this could cause some issues because sometimes we use the `Set` collection. Maybe we should sort by 'compliance', from the "worst" ones to best ones ? Or by the name of the _node_/_rule_ ? I left them as is so there is no …

Fixes #23935: API for node group compliance

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/Compliance.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ComplianceApi.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_compliance.yml
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TestRestFromFileDef.scala
webapp/sources/rudder/rudder-web/src/main/elm/sources/GroupCompliance/ApiCalls.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/GroupCompliance/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/GroupCompliance/Init.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/GroupCompliance/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/GroupCompliance/View.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/GroupCompliance/ViewNodesCompliance.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/GroupCompliance/ViewRulesCompliance.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/GroupCompliance/ViewUtils.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Groupcompliance.elm
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-groups.css
webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/groups.html
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/NodeGroupForm.html

https://issues.rudder.io/issues/23926
Creates an Elm app for display of compliance by group (I copied most of the app structure from directives).
It also changes a bit of Scala frontend code in the summary page of a group, which therefore uses javascript to display compliance (this page has not been rewritten in Elm yet).
There is also some change in the Scala backend to add the policy mode of a rule and a node to the API response.
The 'global' and 'targeted' compliance is specific to groups, and it can be seen as filters for the rules and nodes displayed in the compliance tree : 
When the filter value is changed (e.g. from 'global' to 'targeted'), I made the compliance table display in "reload" state until the new compliance data is fetched, as it may take some time for the new data to …

Fixes #23926: Display group compliance

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala

https://issues.rudder.io/issues/18952
Manage the cases where subgroup changes cause chaos on other subgroup, either by being deleted, or becoming static (with dyn dep) or decoming dynamic (used in subgroup of static group). 
There is a lot of lines changed, but most are error handling. 
The logic is similar for both "look if the node becoming dynamic is a dependency of a static group" or "look if the group becoming static as a dynamic group as a subgroup": each time, unwind the the query of the interesting group, look for the nature of dependencies. 
The error is not returned in the IOResult error channel, since it's user-actionnable: it's an option (in that case, the `Some` contains a string for the list of bad groups). 
The configirmation pop-up on deletion is handle by cssSel magic, I …

Fixes #18952: Static group which depends on dynamic subgroup must be forbiden

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/xmlparsers/VariableSpecParser.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/DebugNodeConfigurationLogger.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/policies/RuleTarget.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/migration/XmlEntityMigration.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/DirectiveRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ExpectedReportsJdbcRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ReportsJdbcRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/json/JsonExctractorUtils.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogDetailsService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlUnserialisationImpl.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/MergePolicyService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/AgentSpecificLogic.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/CmdbQueryParser.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/DynGroupUpdaterService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/NewNodeManager.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/workflows/CommitAndDeployChangeRequestService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/DirectiveApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SettingsApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/Section2FieldService.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleGrid.scala
webapp/sources/utils/src/main/scala/com/normation/utils/Control.scala
webapp/sources/utils/src/test/scala/com/normation/utils/TestControl.scala

https://issues.rudder.io/issues/23948
This is a backport in 7.3 for #5276

Fixes #23948: Remove early return to prepare to Scala3 migration in box sequence/traverse

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/SystemVariableSpecServiceImpl.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DataStructures.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/SystemVariableService.scala
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-500-directives/rules/cfengine-community/rudder.json
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-two-directives/rules/cfengine-community/rudder.json
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-gen-var-def-override/rules/cfengine-community/rudder.json
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-default-install/rudder.json
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/rudder.json
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-one-multipolicy/rudder.json
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-two-directives/rudder.json
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/technique-and-revisions/rudder.json
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestComputeSchedule.scala

https://issues.rudder.io/issues/23956
We want to present a new value in `rudder.json`. For that, we need to create a new  `SystemVariable` and its spec. 
The content of the variable is the real start time + a splay time derived from node ID.
The splay time computation was the easy part, and we just assume that the input is random (it's supposed to be an uuid) and get its byte as a BitInt, then just `modulo` so that it fits in the expected interval given by agent run period (in seconds).
I chose to use `java.time` structure since it seems that we will need to switch to it in a near futur, at least we can start to use them on new, isolated content. 
The hardest part was to rediscover that the `start hour` and `start minutes` in the `AgentRunInterval` data structure are not really the start …

Fixes #23956: Rudder agent scheduled runs are not triggered at regular interval

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/Compliance.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ComplianceApi.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/23987

Fixes #23987: Add policy mode info to node compliance API

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchQueryParser.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/RestQuicksearch.scala
webapp/sources/rudder/rudder-web/src/main/elm/sources/QuickSearch/ApiCalls.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/QuickSearch/Datatypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/QuickSearch/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/QuickSearch/Port.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/QuickSearch/Update.elm
webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder-elm.js

https://issues.rudder.io/issues/23402
This formats errors as a nicer message for the user. There is a caveat when doing error transformation from `PureResult` (`Either`s) to `Box`, which is still the "effect type" in this API : if `.toBox` is not used at the end, we will end up with a exception cause message being serialized with both `err1; cause was : err2` and `err2 <- err3` formats...

Fixes #23402: In quicksearch, query error are not displayed which leads to infinite loading result

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/JsonResponseObjects.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/RulesInternalAPI.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/RuleApi.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_rules.yml
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_rulesinternal.yml
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
webapp/sources/rudder/rudder-web/src/main/elm/sources/GroupRelatedRules/ApiCalls.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/GroupRelatedRules/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/GroupRelatedRules/Init.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/GroupRelatedRules/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/GroupRelatedRules/View.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/GroupRelatedRules/ViewUtils.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Grouprelatedrules.elm
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-main.css
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-template.css
webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/groups.html
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/NodeGroupForm.html

https://issues.rudder.io/issues/23961
* We display a rules tree in place of the previous table (most code is copied from the sidebar tree in the rules page).
* We have a badge like the one we have for policy mode, but with the `Included` or `Excluded` label instead.
* For that we create a new Elm app `Grouprelatedrules`. We already have another Elm app for groups compliance, which could be merged with this one later when we migrate the groups page to Elm

Fixes #23961: Display of related rules for groups should avoid detailing compliance

---

webapp/sources/rudder/rudder-core/src/main/resources/reportsSchema.sql
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/ComplianceLevel.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/PostCommits.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/score/ComplianceScore.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/score/GlobalScoreRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/score/Score.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/score/ScoreRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/score/ScoreService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/score/SystemUpdateScore.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/CampaignApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
webapp/sources/rudder/rudder-web/src/main/elm/sources/Node.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Node/View.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Score/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Score/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Score/ViewUtils.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/SystemUpdateScore.elm
webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder-elm.js
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/node.html

https://issues.rudder.io/issues/23967

Fixes #23967: Rudder score backend and API

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/BaseUrl.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/CommonLayout.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/CustomPageJs.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/RegisterToasts.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/SetupRedirect.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/UserInformation.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/WithCachedResource.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/WithNonce.scala
webapp/sources/rudder/rudder-web/src/main/webapp/index.html
webapp/sources/rudder/rudder-web/src/main/webapp/secure/utilities/healthcheck.html
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/common-layout.html

https://issues.rudder.io/issues/24016
Implementing CSP strict headers : 
```
Content-Security-Policy:
  script-src 'nonce-{RANDOM}' 'strict-dynamic';
  object-src 'none';
  base-uri 'none';
...
``` 
Given an html page to be rendered with an HTTP request which should be responded with these strict headers :
* We generate a unique random value during the rendering of request
* We include the nonce value in scripts in the page using `data-lift="with-nonce"` attribute, which will add `nonce="nonce-{RANDOM}"` as attribute to the script 
* For scripts defined in Scala code and generated in the page usually with `Script(OnLoad(JsRaw("...")))`, we also need a call to `WithNonce` to add the attribute to the scripts
* For `onclick` attributes containing javascript code, they are blocked by browser …

Fixes #24016: Implement CSP strict headers with nonce and apply to healtcheck page

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/Compliance.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ComplianceApi.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_compliance.yml
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-web/src/main/elm/sources/GroupCompliance/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/GroupCompliance/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/GroupCompliance/ViewUtils.elm

https://issues.rudder.io/issues/24028
We did not display the policy mode of a rule/node but now we do :

Fixes #24028: Add policy mode info in group compliance details

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Groupcompliance.elm
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/NodeGroupForm.html

https://issues.rudder.io/issues/24034
There is a `not` that was missing in the boolean condition reloading the tab with new data...
Also added accessibility in the html of groups tabs

Fixes #24034: Group compliance tab is loaded only with a double-click

---

webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-main.css

https://issues.rudder.io/issues/24048
A margin-bottom has been added to .form-group elements and the labels inside these elements are now in bold again.

Fixes #24048: Add margin-bottom to form group

---

webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestComputeSchedule.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/write/WriteTechniquesTest.scala

https://issues.rudder.io/issues/24051
Same as https://github.com/Normation/rudder/pull/5337 with indent spotlessed and an additional tests for interval check related to question in https://github.com/Normation/rudder-plugins-private/pull/497

Fixes #24051: Wrong agent type for dsc node in tests

---

relay/sources/relayd/Cargo.lock

https://issues.rudder.io/issues/24068

Fixes #24068: DoS vuln in h2 lib in relayd

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/ApiDatastructures.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/LiftApiDispatcher.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TestRestPlusInPath.scala

https://issues.rudder.io/issues/24036
The problem is that we rely on Lift URL parsing (because URL parsing is complicated and full of worms and we don't want to do by ourself), but lift, being helpfull, remove the last bit if it looks like an extension and put it in an `extension` parameter. 
Here, we just put it back when parsing looking for a REST URL. It won't impact the case where it would be a real site extension, since we don't authorize REST parsing to result in a root site path.

Fixes #24036: If REST url ends with .com, then the .com is removed from path segments

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala

https://issues.rudder.io/issues/24086
We don't want to forbid only group changing from dynamic to static to have dynamic subgroup, but anything that is now static.

Fixes #24086: You can create a static group which depends on a dynamic one

---

webapp/sources/api-doc/components/schemas/node-add.yml
webapp/sources/api-doc/components/schemas/timezone.yml
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/CreateNodeData.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_nodes.yml
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_settings.yml

https://issues.rudder.io/issues/24091
Trivial change, most of it is just adding test and API doc. 
We just add a new case for `machine` deserialisation and choose either it or the old `machineType`. The new `machine` is an object matching format from the GET which allows `manufacturer`.

Fixes #24091: Add manufacturer field in create node API

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/Compliance.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ComplianceApi.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TestDirectiveComplianceCsv.scala
webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeCompliance/JsonDecoder.elm

https://issues.rudder.io/issues/24085
Basically just adding the _policyMode_ field at every level of the compliance tree.
For nodes and directives, _policyMode_ is already an attribute, but for a rule we need to compute it, so this is a bit less performant as it requires the set of node ids by group to be fetched.

Fixes #24085: We need a consistant presence of policyMode in compliance API outputs

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SettingsApi.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_settings.yml

https://issues.rudder.io/issues/24093
Order of nodes in allowed network changes which breaks tests. We fix it to be always root first, then alpha-numerical for other node ID.

Fixes #24093: Backport test correction for allowed networks

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/NewNodeManager.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/CreateNodeData.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala

https://issues.rudder.io/issues/24105
So the problem was only for node created in `Accepted` status. For them, we created the machine directly in `Accepted`, while the node part was created in `Pending`, then accepted. 
So at one point, we have a machine in `Accepted`, and the node is still in `Pending`. So we clean the machine because we chose at some point to enforce the fact that machine and node must have the same status (when we deeply linked machine to node with the machine id being a hash of the node id). And there is no machine with the correct ID in pending. 
Works as expected. We just need to also create the machine in pending.
Other changes are just better logs and log correction.

Fixes #24105: Machine is not correctly create with node create API

---

api-doc/package-lock.json
api-doc/package.json
api-doc/redocly.yml
webapp/sources/api-doc/code_samples/curl/compliance/group-global.sh
webapp/sources/api-doc/code_samples/curl/compliance/group-targeted.sh
webapp/sources/api-doc/components/parameters/node-group-id.yml
webapp/sources/api-doc/components/schemas/group-node-compliance-rules.yml
webapp/sources/api-doc/components/schemas/group-node-compliance.yml
webapp/sources/api-doc/components/schemas/group-rule-compliance-directives.yml
webapp/sources/api-doc/components/schemas/group-rule-compliance.yml
webapp/sources/api-doc/openapi.src.yml
webapp/sources/api-doc/paths/compliance/group-global.yml
webapp/sources/api-doc/paths/compliance/group-targeted.yml

https://issues.rudder.io/issues/24043
Add public API documentation for these endpoints : 
* `/api/compliance/groups/{groupId}` (global compliance) 
* `/api/compliance/groups/{groupId}/target` (targeted compliance)
Also, there was a limitation in redocly to generate examples for nested objects, so we set the config parameter `generatedPayloadSamplesMaxDepth` to `100`. We also update redocly to `1.6.0`

Fixes #24043: API documentation for compliance by group

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/GroupCompliance/ViewNodesCompliance.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/GroupCompliance/ViewRulesCompliance.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/GroupCompliance/ViewUtils.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Groupcompliance.elm
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/NodeGroupForm.html

https://issues.rudder.io/issues/24040
Creating the tooltips to explain the meaning of _global compliance_ and _targeted compliance_ : 
* In the compliance tab : 
* In the groups parameters tab :

Fixes #24040: Group compliance view does not give global and targeted compliance definitions

---

webapp/sources/rudder/rudder-web/src/main/style/rudder/_rudder-variables.scss
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-bootstrap.scss
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-main.css
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-template.css
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-wizard.css
webapp/sources/rudder/rudder-web/src/main/style/rudder/technique-editor-filemanager.css
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/common-layout.html

https://issues.rudder.io/issues/24124
There's still a lot of optimisation to be done on this (like replacing all our colour codes with variables, making sure we override as few bootstrap rules as possible but instead using variable overrides, etc.) but to limit its scope I've just fixed and harmonised the appearance of Rudder's main links and buttons.
This first PR already brings a few changes:
- There is a new **`_rudder-variables.scss`** file
- the underscore means in Sass that this is a "partial" file, i.e. a file that will only be imported into other scss files. It is not compiled in css
- it will contain all our colour codes (text, buttons, compliance, policy mode, warning/error etc.). Only variables, no css rules!
- It is completely independent of bootstrap
- In future, the code in …

Fixes #24124: Links and buttons don't have the right colour since the bootstrap update

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/RemoveNodeService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala

https://issues.rudder.io/issues/24129
Adapt the response to delete so that user using the API can know they perhaps didn't do want they wanted. 
The method seems to use at exactly one place, so it's rather simple to change.

Fixes #24129: For delete API for node, add a message for node already deleted

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitArchivers.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/rule/category/GitRuleCategoryArchiver.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/xml/TestCategoryPathUtils.scala

https://issues.rudder.io/issues/24011
A lot of changes but the main one is throwing an error when accessing files outside the root configuration directory in with git (`/var/rudder/configuration-repository`) : https://github.com/Normation/rudder/pull/5314/files#diff-bb5734a3493073add0df1291f147ac6cd515b8a211f543610446796ed2374441R169-R187...
This should avoid this method to be identified as vulnerable by any smart vulnerability scanners that could also detect the initial vulnerability...

Fixes #24011: Archiving allows to read inconsistent active technique category ids 

---

webapp/sources/rudder/rudder-core/src/main/resources/reportsSchema.sql
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/score/GlobalScoreRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/score/ScoreRepository.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/migration/CheckTableScore.scala

https://issues.rudder.io/issues/24147

Fixes #24147: Add score enum for score in database

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/NodeInfo.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/SystemVariableService.scala

https://issues.rudder.io/issues/24112
So, we want to not generate policies for nodes without a correct security token, for the value of correct == "is pasable as what it's supposed to be". 
We also want to skip these node from appearing into `nodesList.json`. 
=> check that in `system variable` part of node config handling:
- for policy servers, just avoid nodes with an empty `keyHashBase64Sha256` which does what need to be done to check parsability etc 
- for nodes, add a "check security token" check, which uses the same heuristic. The node will be avoided in that case. 
With the change, we get that kind of error message:

Fixes #24112: We must not generate policies for nodes without a well formed certificate

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/tree.js
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNodeGroupTree.scala

https://issues.rudder.io/issues/24152
This looks as a hack but it works as a fix : 
* we store the initial event handlers in the tree, rendered in Scala code by Lift, they always have an `id` prefixed with `lift-event-js-`,
* we create a jstree "plugin" which provides a function `redraw_node` defined by jstree, in which we re-bind the event handler
I think this is the only convenient solution... The plugin would simply delete all events for the node in the DOM if we add an event handler anywhere else
In the groups tree, there was no convenient selector for a node of the tree so I created one "groupTreeNode".
There is also a fix to add _hrefs_ to all nodes of the tree, so that they can be opened in a new tab (e.g. with a middle click)

Fixes #24152: Jstree links are broken

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/GroupCompliance/ViewUtils.elm
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-bootstrap.scss

https://issues.rudder.io/issues/24172
* Added the shadow of active buttons in bootstrap 3 here with the new bootstrap 5 version.
* Some hardcoded style was already patched in Elm code previously, now it can be removed.
I don't know if the shadow color should go in the `rudder-variables` partial, it seems too specific to be reused anywhere else for now...

Fixes #24172: Active buttons no longer have shadow

---

webapp/sources/pom.xml

https://issues.rudder.io/issues/24177
The previous pattern was looking for all subdirectories with scala file. This new one only look at the `src` directory, thus limiting to current project scala sources.

Fixes #24177: Make spotless only check source of current project

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/EditorTechnique.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueSerializer.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/migration/MigrateJsonTechniquesService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/yaml/YamlTechnique.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestEditorTechniqueWriter.scala
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/JsonEncoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewMethod.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTechnique.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTechniqueTabs.elm

https://issues.rudder.io/issues/24099
This feature adds constraints to technique parameter to generate different metadata.xml with support for different inputs. Everything is already ok rudderc side. we juste need to add it into rudder api and also in technique editor  UI

Fixes #24099: Add a select type for technique parameter

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/NodeGroupRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeGroupRepository.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RoleApiMapping.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ComplianceApi.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-web/src/main/elm/sources/GroupRelatedRules/View.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Groups.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Groups/ApiCalls.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Groups/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Groups/Init.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Groups/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Groups/View.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Groups/ViewGroupsTable.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Groups/ViewUtils.elm
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/Groups.scala
webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/groups.html

https://issues.rudder.io/issues/23968
Display all groups compliances summary in the home "Groups" UI : 
* we needed a separate API endpoint to format both "targeted" and "global" compliance summary in two compliance bars, for all groups : `api/compliance/summary/groups`,
* rendering of the compliance table displaying the compliance bars is made in Elm (as in the "Rules" UI); that introduced the need to migrate the groups tree on the sidebar to Elm, as well as boostraping a new Elm app for 'groups'. At some point, the previous Scala code (with liftweb) needs to display the details of the group, of a category, and the modal to create a group/category. So, quite a few Elm ports and subscription are added to make the state of the Elm app consistent with the display with lift...

Fixes #23968: Display a global view of group compliances

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/Authorizations.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderProviderManager.java
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/UserInformation.scala

https://issues.rudder.io/issues/24183
- add an `Role.Alias` type that is just an alias of an other Role. It use the other role `name` so that rudder internal resolution is transparent for it, but allows to have an additionnal `aliasName` (typically provided by an external source to avoid referencing Rudder internal name)
- add a facility to transform roles into meaningfull string usable in log/session log
- also add some facility to provide a `logout` redirect URL. This is a bit of work, since we don't use Spring security logout for historical reasons (it didn't work well with lift logout, session cleaning, etc)

Fixes #24183: Add an Alias type of Role to track role mapping

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/DirectiveCompliance/View.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTechnique.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/GroupCompliance/View.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/ViewCategoryDetails.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/ViewRuleDetails.elm
webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder.js
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupCategoryForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/ShowNodeDetailsFromNode.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/PendingHistoryGrid.scala
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-bootstrap.scss
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-groups.css
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-main.css
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-node.scss
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-template.scss
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder.css
webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/manageNewNode.html
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentDirectiveEditForm.html
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentRuleEditForm.html
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/NodeGroupForm.html
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/server/server_details.html

https://issues.rudder.io/issues/24170
Major changes : 
- Renaming css classes :
- `ul.ui-tabs-nav` into `ul.nav.nav-underline`
- `li.ui-tabs-tab` into `li.nav-item`
- `li > a` into `li > button.nav-link`
- The .active class is no longer applied to the `<li>` element, but to the `<button>` it contains.
- We no longer use jquery's tabs function `$("ul").tabs()`, which added extra CSS classes to our elements.
- A lot of cleaing in the CSS code has been made (using scss Rudder variables, moving certain blocks of code to the right place, deleting old css rules..).

Fixes #24170: The active tab indicator no longer works

---

policies/module-types/directory/tests/test.rs
policies/module-types/template/tests/minijinja.rs
policies/module-types/template/tests/mustache.rs
relay/sources/rudder-pkg/Dockerfile
relay/sources/rudder-pkg/requirements.txt

https://issues.rudder.io/issues/24205

Fixes #24205: Pylint test fails with an exception

---

webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-bootstrap.scss
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-directives.scss
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder.css
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/directiveInput.html

https://issues.rudder.io/issues/24176
Now the directives parameters UI should look very similar to the previous one. Both specific directives html and global css have been changed, but to adapt from previous bootstrap 3 that disappeared in bootstrap 5

Fixes #24176: Directive parameters UI details changed since bootstrap 5

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor.elm

https://issues.rudder.io/issues/24123
IMO we want graphical display of method rather than YAML editor
Before the fix
After the fix

Fixes #24123: Technique import doesn't refresh the list of method in technique editor

---

webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-technique-editor.css

https://issues.rudder.io/issues/24150
Please note that the offset label `Audit from command` that you can see in the gif, for the method after the nested block, is another bug, not introduced by this fix

Fixes #24150: when we have conditions on blocks, the condition text is not correctly positionned when the block is opened

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/facts/nodes/NodeFact.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/facts/nodes/NodeFactRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/tenants/TenantService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/tenants/Tenants.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/facts/nodes/TestCoreNodeFactInventory.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/facts/nodes/TestFullInventoryRepoProxy.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/facts/nodes/TestSaveInventory.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestNodeFactQueryProcessor.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/ApiDatastructures.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderUserDetailsFile.scala
webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/RudderUserDetailsTest.scala

https://issues.rudder.io/issues/24140
That PR introduce a source of "tenants known in that Rudder server". Only tenants know will be allowed to be used for node access, so that we have a kind of prefiltering before the "user/node/tenant" check on "node tenants/available tenants" 
The filtering is done in a `TenantService` that knows about available tenants and wrap low level methods on node. 
These wrapping are then used  in `CoreNodeFactRepository`. 
Nothing in Rudder core manage that list of available tenants. It will be done in plugins. 
Also add tests to check that the available tenants are doing there job.

Fixes #24140: Have a source of known-tenants in rudder-core

---

webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Rules.elm

https://issues.rudder.io/issues/24278
This can happen when change requests are enabled but the Rule may not need a validation change request at all (e.g. groups are empty). So the CR id is not mandatory.
If the Rule API forgets to return the CR id in the JSON, it will be a matter of fixing the API logic.

Fixes #24278: Incorrect error message about change request creation failure when it is not needed

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/UserInformation.scala

https://issues.rudder.io/issues/24282
Hopefully the roles are custom ones and have a pretty display name, otherwise if there are custom roles there will be `anon[node_write], anon[...], ...` in the list but they would still be needed because we can't lie to the user...

Fixes #24282: Display user roles on hover of user profile

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/api/DataStructures.scala

https://issues.rudder.io/issues/24284
This will have effect on debug logs that use string interpolations, the change is introduced to fix this one : https://github.com/Normation/rudder-plugins/pull/655/files#diff-8fe302fecad34e77c8d7fa30f3efdf0110c77048e1f14006e4855dc1c60e73d9R658-R659.
Now we should be able to read it more fluently :
```
[2024-02-28 16:18:00+0100] DEBUG auth-backends - Principal 'test-user' final roles: [inventory], and API authz: /settings/global_policy_mode:[GET];/settings/global_policy_mode_overridable:[GET];/user/api/token:[GET,PUT,POST,DELETE];/nodes/details/property/*:[POST];/nodes/details/software/*:[POST];/nodes/*/displayInheritedProperties:[GET];/nodes/*/inheritedProperties:[GET];/nodes/pending/*:[GET];/nodes/details:[POST];/nodes/pending:[GET];/nodes/status:[GET …
```

Fixes #24284: Log on user api authorizations should be more concise

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/FileManager/Action.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/FileManager/Env.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/FileManager/View.elm

https://issues.rudder.io/issues/24276
We want to reset the current dir of the file manager when opening it. This fix the fact that everyone is lost when using it !
I fixed the recursion problem when a folder had the same name as one of it's parent. It was because a the name of the folder was used as key, so when looking for child file we were getting the parent one, then infinite loop.
I used the full path of the folder instead of just its name

Fixes #24276: An errors occurs within technique editor resource manager when we create a folder that has the same name than another parent folder

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/users/UserRepository.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala

https://issues.rudder.io/issues/24230
We need to know providers properties e.g. : Do they override or extend the user roles defined in the `users.xml` file ? Can they write password in the users file ?
These properties will be used in user-management plugin to handle some providers logic regarding roles and also for the logic of the UI : https://github.com/Normation/rudder-plugins/pull/668

Fixes #24230: Authentication providers and role mapping settings should be exposed

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/users/UserRepository.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala

https://issues.rudder.io/issues/24297
As suggested in [the review of this PR](https://github.com/Normation/rudder/pull/5408#discussion_r1507736417), the role extension is better modeled as an ADT, this allows to instantiate the properties of the provider in a cleaner way.
The file provider has also been added, as it does not affect the logic of handling it in user-management plugin

Fixes #24297: Correct role extension data structure for user management

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/users/UserRepository.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/users/UserRepositoryTest.scala

https://issues.rudder.io/issues/24304
* The change of not updating user origin should not have been made [in this previous PR](https://github.com/Normation/rudder/pull/5408/files#diff-4a2aaf2f76c5556341804a45895b09d281d02773e3dc0ff723507cced5178652R633) : it breaks tests and users can no longer be set as managed by OIDC when logging-in the first time and already being a file user. 
* Users that are from the same origin should not be taken into account when changing user status (`setExistingUsers`)

Fixes #24304: Deleted users should change status on file reload 

---

webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/server/server_details.html

https://issues.rudder.io/issues/24349
Tooltips are useless here, I propose to replace them with their own text :

Fixes #24349: Odd rendering on tooltips in search node page 

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/View.elm

https://issues.rudder.io/issues/24354

Fixes #24354: Description in API account is outside of the header

---

webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-bootstrap.scss
webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/searchNodes.html

https://issues.rudder.io/issues/24347

Fixes #24347: Missing header separator in node search page

---

relay/sources/rudder-package/src/repo_index.rs
relay/sources/rudder-package/tests/repo_index.json

https://issues.rudder.io/issues/24372
Parse as a JSON first to avoid crashing on invalid index entries (but still log a warning, this should not happen anyway).

Fixes #24372: Don't fail on malformed index entries

---

webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-main.css

https://issues.rudder.io/issues/23881
Added a maximum height for markdown containers, and auto scroll when content exceeds this height. Here is the result:

Fixes #23881: When the documentation of a technique is very long, the user has to scroll a long way before creating a directive from this technique

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/homePage.js
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-dashboard.css

https://issues.rudder.io/issues/24283
Not actual data...

Fixes #24283: Margin is too small on Global compliance details module in dashboard

---

webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-bootstrap.scss

https://issues.rudder.io/issues/24317

Fixes #24317: Use bootstrap variables to define the default text size and font

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ComplianceApi.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_compliance.yml
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala

https://issues.rudder.io/issues/24366
The existing test did not catch the bug because it the mock was not doing what happens when getting reports : filter by node and rule ids. I added the filters, and also corrected a test which was also wrong (the expected JSON for targeted compliance on nodes should have `nodes: []` in the test case, because the rules are skipped hence there are no node reports)

Fixes #24366: Group compliance stays empty

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/SystemUpdateScore.elm

https://issues.rudder.io/issues/24420

Fixes #24420: Missing space between badge score and number

---

policies/rudderc/src/doc.rs

https://issues.rudder.io/issues/24302

Fixes #24302: Add outcome conditions in rudderc docs

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Groups.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Groups/ApiCalls.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Groups/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Groups/Init.elm

https://issues.rudder.io/issues/24335
Currently, as the Elm app is within a part of the Scala web page, sometimes they mix with each other.
When doing a group action : _create, clone, delete_, we simply don't want to reload the home page in Elm with the "compliance group summary table", because the Scala web page already handles the display

Fixes #24335: Broken group creation UI

---

webapp/sources/api-doc/components/parameters/target-or-node-group-id.yml
webapp/sources/api-doc/openapi.src.yml
webapp/sources/api-doc/paths/compliance/group-global.yml
webapp/sources/api-doc/paths/compliance/group-targeted.yml
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/Compliance.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ComplianceApi.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala

https://issues.rudder.io/issues/24363
We need to support either a `groupId` (e.g. an uuid) or a target (e.g. `special:...` or even `group:...`). 
Common fields that we need for the compliance result are `id, name, serverList`, the code is refactored accordingly.
**Screenshots** : 
This one needs some change in the UI (in another PR) :

Fixes #24363: Display compliance for system groups

---

policies/rudder-cli/src/lib.rs
policies/rudderc/src/lib.rs
relay/sources/rudder-package/src/lib.rs

https://issues.rudder.io/issues/24432
There were two big options:
* Catch panics and prevent failure with broken pipe
* Replace `println!` and others by a fallible alternative and handle errors everywhere
As there can be `println!` everywhere and properlt handling these errors early would be expensive, let's go for the ugly solution.

Fixes #24432: Broken pipe when piping rudder-package output

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogFactory.scala

https://issues.rudder.io/issues/24277
I only fixed the problem for deleted Technique, but there is some problem on add and update where the technique is not displayed, but this is a problem for another ticket

Fixes #24277: Errors in event log for deleted techniques

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder.js
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder.css
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/reports_server.html

https://issues.rudder.io/issues/24405
We display the `logs` table in two different tabs `Compliance` and `System status`, but having the same `id` for different elements across tables makes it impossible to dispatch event handlers correctly.
Also, the event handlers are not set on the `Show logs` buttons because the tab is has not yet been rendered.  
We just append the tab id to every HTML element, and set the buttons HTML with the correct event handler when the tab is rendered.

Fixes #24405: Node tabs have onclick event handlers assigned on unrendered elements

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/migration/CheckTableUsers.scala

https://issues.rudder.io/issues/24456
What is in the migration and in SQL is not synched. We need to find a way to make it synched, else we will have things like that all the time. 
So:
- correct the initial migration of the table
- add a bit of script to add primary relation if it doesn't exists

Fixes #24456: Missing primary key statement for user sessions table creation when migrating

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/24441
THose actions should be done after plugin init, which is the case (see postPluginInitActions function), but the removed lines were reintroduced after

Fixes #24441: Cannot translate campaign on boot, leading to skipped events

---

webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestWriteNodeCertificatesPem.scala

https://issues.rudder.io/issues/24520
This is an async test so we use `eventually` on the expression to match (content of the output stream byte array)

Fixes #24520: Async tests are failing for node certificates

---

policies/rudderc/src/test.rs

https://issues.rudder.io/issues/24523

Fixes #24523: rudderc test should dump the report file path or workdir when a check step fails

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/JsonResponseObjects.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/properties/Properties.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/MergeNodeProperties.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/nodes/TestMergeGroupProperties.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/GroupsApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_groups.yml
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/View.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/ViewUtils.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Nodeproperties.elm
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/24236
Add a warning field for when a property has some conflict over it's "type hierarchy".
It can be seen in node properties tabs, in different cases : 
* when creating a new property (but we try to infer the property type when we can [here](https://github.com/Normation/rudder/pull/5471/commits/f1ed1b7aa29a5b417c9332118715e5784772371f)) : 
* when editing an existing property : 
* when node property already exists and has type hierarchy conflicts : ![image](https://github.com/Normation/rudder/assets/65616064/9dbb4926-e6a3-4044-bc95-45336852eee4)
N.B. : The feature is available in both "node" and "group" details.

Fixes #24236: Overriding properties should have the same type as overridden

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/api/ApiAccountDiff.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/RestDataSerializer.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDiffMapper.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/RestApiAccounts.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TraitTestApiFromYamlFiles.scala
webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/Init.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/JsonEncoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/View.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/ViewModals.elm
webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/apiManagement.html

https://issues.rudder.io/issues/24475
:warning: 
There is `a lot` of changes that are due to the use of `elm-format` which is extremely happy to give new lines everywhere. I think the result is a bit better, but hell, do they love spaces. You should really look at diff with `?w=1`.
That PR adds the infrastructure to be able to configure tenants for API account. 
The logic is similar to the `api-authorization` plugin: 
- on rudder core, we have check in place to see if the plugin is enable or not, 
- if the plugin is disable, we only diplay the current tenants for the account, in a non updatable way, 
- if the plugin is enable, the the user can change tenants. 
We have three kind of tenants: 
- `*` means "all tenants", and is the defaults for compat reason
- `-` meains "no tenants", and …

Fixes #24475: API account UI needs to provide a configuration for tenants

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder-datatable.js
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-datatable.css
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-template.scss
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/NodeGroupForm.html

https://issues.rudder.io/issues/24528
The `scrollY` and `scrollCollapse` datatable parameters set in https://github.com/Normation/rudder/pull/5470#issuecomment-2004165706 should be applied only on "resizable" tables which have a drag element.
Also, the drag element is now more visible in the group page :

Fixes #24528: Nodes tables height is too small

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/NodeGroupForm.html

https://issues.rudder.io/issues/24381
New screenshot : 
* The tab display needs to be flex to have the compliance on the right side
* The group ID was in duplication, we keep the one on the left-side and add the clipboard icon to it
* The category select dropdown didn't have a full width  
* (sorry for the empty compliance in the screenshot, I didn't setup any)

Fixes #24381: Display of group compliance in group information should be on the right

---

webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/NodeGroupForm.html

https://issues.rudder.io/issues/24546
The `d-flex` class conflicts with the display logic of tabs because it applies `display: flex !important;` and tabs use the `active` class which applies `display: none`... :crying_cat_face: 
We just create another container within the tab which will get the `row d-flex` classes

Fixes #24546: Group parameters tab is always displayed

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/api/DataStructures.scala

https://issues.rudder.io/issues/24558
oups

Fixes #24558: Upmerge removed breaks 8.1 - api acl plugin

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Groups.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Groups/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupCategoryForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/model/RudderBaseField.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/Groups.scala
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-groups.scss
webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/groups.html
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/NodeGroupForm.html

https://issues.rudder.io/issues/24489
* We now have the `Close` button to return on home groups page (since it's diplayed in Elm we need a custom HTML event to conveniently trigger a Elm port for that)
* The new group creation page no longer has label alignment issues (remove `text-end` class)
* The groups table now appears "clickable" on every row, it always redirects to the group details 
* System groups "category" field needed a `w-100` class for full width and consistency between system and non-system groups

Fixes #24489: Group page UI is missing several key things

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder-datatable.js

https://issues.rudder.io/issues/24549

Fixes #24549: Resizing node tab in group page should stop at header

---

webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-menu.scss

https://issues.rudder.io/issues/24433
The selectors have changed now.
Also the `navbar-custom-menu` class no longer exists.
(I couldn't test adding a token, it is currently still broken due to the tenants feature)

Fixes #24433: API authorization menu bellow username is barely usable

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala
webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/directiveManagement.html
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentDirectiveEditForm.html

https://issues.rudder.io/issues/24563

Fixes #24563: JS error when opening directive form more than once 

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTechnique.elm

https://issues.rudder.io/issues/24586
I changed the icon too, a check mark was misleading since this is error compilation

Fixes #24586: Compilation output tab icon in technique is not aligned

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Groups/ViewUtils.elm

https://issues.rudder.io/issues/24567
I should test it in real environment with at least 3 different compliance

Fixes #24567: when sorting by targeted compliance, the No data available should always be last

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Tags/View.elm

https://issues.rudder.io/issues/24548
* The "row" class has changed a lot in bootstrap 5, we don't need it anymore 
* Also the icon for deleting a tag is too eye-catching with the "text-danger" class 
* The "+" button for adding a tag is too small when compared with the one in Rules page

Fixes #24548: Tags displayed in directive form are broken 

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTechnique.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTechniqueTabs.elm
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-technique-editor.css

https://issues.rudder.io/issues/24583
Edit from https://github.com/Normation/rudder/pull/5520#issuecomment-2017581636

Fixes #24583: We should not be able to save a technique with empty enum parameters 

---

policies/rudderc/src/backends/unix.rs
policies/rudderc/src/backends/unix/ncf/method_call.rs
policies/rudderc/src/ir/technique.rs
policies/rudderc/src/technique.schema.json
policies/rudderc/templates/technique.ps1.askama
policies/rudderc/tests/cases/general/escaping/technique.ps1
policies/rudderc/tests/cases/general/form/technique.ps1
policies/rudderc/tests/cases/general/long_method_param_name/technique.ps1
policies/rudderc/tests/cases/general/min/technique.ps1
policies/rudderc/tests/cases/general/ntp/technique.ps1
policies/rudderc/tests/cases/general/param_in_condition/technique.ps1
policies/rudderc/tests/cases/general/reporting/technique.ps1
policies/rudderc/tests/compile.rs

https://issues.rudder.io/issues/24592
* Create a separate type for technique id as the constraints are different
* Modify the schema accordingly
* Add a `Technique-` prefix to all Windows techniques (for consistency, I prefer to avoid a "surprise" prefix in corner cases).

Fixes #24592: Allow technique id starting with a number

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewBlock.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewMethod.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewMethodsList.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTechniqueList.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTechniqueTabs.elm
webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder.js
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-main.scss
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-technique-editor.css
webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/techniqueEditor.html

https://issues.rudder.io/issues/24419
- All the popovers that were acting as tooltips have been replaced with tooltips
- All the unnecessary tooltips (e.g. "Clone this method" on the clone button) have been removed
- Increased number of tooltip cleanings

Fixes #24419: Persistant tooltip on info icon in methods

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Groups/Init.elm
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/Groups.scala
webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/groups.html

https://issues.rudder.io/issues/24466
The Elm `Groups` app is initialized with the action to fetch the group compliance summary, but when it takes some time (e.g. response time within ~seconds, just `Thread.sleep` to reproduce the bug), it receives the data later.
Upon receiving the API response, Elm still appends the DOM that was associated with the response, i.e. the groups table, even if the server templating already took over and displayed a node details.
**Solution :**
Fetch the data for the table only when it is needed : the only case is when the groups page is rendered with an URI ending with `/groups`. When the URI ends with a hash e.g. `/groups#{"groupId":"..."}` we assume on Elm side that we don't need to fetch that data (and the server template will in place display "Group not …

Fixes #24466: when we search for a group in the search engine, the group page we arrive on is messed

---

policies/rudderc/tests/cases/general/policy_mode/technique.ps1
relay/sources/rudder-package/src/lib.rs
relay/sources/rudder-package/src/list.rs
relay/sources/rudder-package/src/versions.rs
relay/sources/rudder-package/src/webapp.rs

https://issues.rudder.io/issues/24401

Fixes #24401: rudder-pkg don't inform that credential are not set up

---

webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-bootstrap.scss
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-main.scss

https://issues.rudder.io/issues/24575
* The [default modal size](https://getbootstrap.com/docs/5.0/components/modal/#optional-sizes) has changed from 600px to 500px, but we are comfortable with the previous value  
* The CSS for the title has disappeared some at some point in time...

Fixes #24575: Make a clear separation between the modification message and change audit log

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryProcessor.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/NodeGroupRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeGroupRepository.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/inventory/TestRenameReceived.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ArchiveApi.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_groups.yml
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/ArchiveApiTest.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/24562
Normalize the file name before moving to received folder. 
We never fail on the normalization, it seems less risky to have several time similar files in received than an unmatch error for an unforseen case.

Fixes #24562: When moving an inventory to "received", check if other file for same node uuid exists and delete it

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder-datatable.js

https://issues.rudder.io/issues/24547
Fortunately when switching tab the scroll bar appears briefly on Firefox and we now see that it is scrollable (in Chrome it will always be displayed when the content is scrollable)

Fixes #24547: When the group tab section is too large it cannot be scrolled

---

webapp/sources/rudder/rudder-web/src/main/package-lock.json
webapp/sources/rudder/rudder-web/src/main/package.json

https://issues.rudder.io/issues/24566
Here is a list of all the dependencies that could be updated :
And after **`npm update`** : 
So, here is the list of updated packages :
- ✅ bootstrap (5.3.2 --> 5.3.3)
- ✅ datatables.net-rowgroup (1.4.1 --> 1.5.0)
- ✅ diff (5.1.0 --> 5.2.0)
- ✅ gaugeJS (1.3.7 --> 1.3.8)
- ✅ sass (1.69.5 --> 1.72.0)
- ✅ xss (1.0.14 --> 1.0.15)
- ✅ gulp-sourcemaps  (2.6.5 --> 3.0.0)
These are only minor update (except for gulp-sourcemaps but there is no braking changes between the two versions)
Some packages have not been updated :
- `datatables.js` and its plugins because they contain breaking changes.
- `chart.js` and `jsondiffpatch`, because it contains breaking changes and must be imported as an EcmaScript module
- and `del`, because it needs to be imported as an …

Fixes #24566: Update js dependencies

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala

https://issues.rudder.io/issues/24591
Nothing special in the code, this looks like that on a node with a tenant:

Fixes #24591: Tenant should be displayed in Node UI detailed

---

webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-plugins.css
webapp/sources/rudder/rudder-web/src/main/webapp/secure/plugins/pluginInformation.html

https://issues.rudder.io/issues/24352

Fixes #24352: Plugin information is too empty when there is no plugin

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/Groups.scala
webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/groups.html
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentNodeProperties.html
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/NodeGroupForm.html

https://issues.rudder.io/issues/24416
The fix consist of : 
* loading the script when the group page loads, or else it will be loaded multiple times
* mounting and initializing an Elm app for node properties when the "Properties" tab content is shown
So we just move everything related to the Elm app "earlier" in the HTML structure, from `NodeGroupForm` details to the main `Group` page.
Caveats of this is that a new Elm app will be initialized each time the "Properties" tab is shown, but changing the Elm model to re-render with every group change action is heavier (we would likely need to make Elm apps global variables, to call ports on every action from the Scala templates). We could do that in another PR.

Fixes #24416: Elm properties app is loaded multiple times

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/NodeGroupRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeGroupRepository.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ArchiveApi.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_groups.yml
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/ArchiveApiTest.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/24295
The chosen new mapping is one that match the LDAP/UI representation of group categories and groups:
```
archive/
`- groups
|- category_with_name
|     |- category.json // the category info: uuid, name, etc
|     `- some_group.json // the group as before
`- some_group_under_root_category.json
```
This mapping is so-so, since the group serialisation also contains the group category id, so we duplicate the information, and if we move a group, it doesn't actually change its category, which is surprising. But I wanted to have the same json serialisation than the one from API.
I hesitated with a mappring like:
```
archive/
|- group-categories.json // one big json will the categories 
`- groups
|- some_group.json // the group as before
`- …
```

Fixes #24295: API export of groups doesn't export the categories as dependencies

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/SystemUpdateScore.elm
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-compliance.scss

https://issues.rudder.io/issues/24421
This what the PR actually does (1)
This is an alternative (2)
Please choose your favorit one!

Fixes #24421: system updates score details is empty when the node is up-to-date

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/DatabaseManagement.scala

https://issues.rudder.io/issues/24408
Result :

Fixes #24408: Button for archiving/deleting reports is not visible

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/Groups.scala
webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/groups.html
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/NodeGroupForm.html
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/server/server_details.html

https://issues.rudder.io/issues/24632
There was some conflicts to resolve regarding rewrite of HTML/JS in bootstrap 5 (tabs, tooltips).
Also for nodes, the variables and Nodeproperties JS script were removed from a common HTML template shared between groups and nodes, and needs to be added back in nodes HTML page

Fixes #24632: Node and group properties will not display in 8.1

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/NodeDetailLevel.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/RestDataSerializer.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala

https://issues.rudder.io/issues/24639
Since tenant is not defined in NodeInfo, and that NodeDetails serialization is still based on it, I thought it was easier to just add one more parameter to the serialization methods.

Fixes #24639: Missing tenant information in API result for node details

---

webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentNodeState.html

https://issues.rudder.io/issues/24668

Fixes #24668: Typos in node state description

---

policies/rudderc/src/technique.schema.json

https://issues.rudder.io/issues/24655

Fixes #24655: Reformat the rudderc technique Json schema to match the one published in the schemastore repository

---

webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-main.scss

https://issues.rudder.io/issues/24605
Numbered lists are now correctly rendered :

Fixes #24605: The ul and ol lists have the same markdown rendering

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/ViewRuleDetails.elm

https://issues.rudder.io/issues/24487

Fixes #24487: Missing icon in the rule creation page

---

webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/NodeInventory.scala
webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/FusionInventoryParser.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/CreateNodeData.scala

https://issues.rudder.io/issues/24703
moved all the `toLowerCase` in the method so that callers don't have to wonder if they should do it or not (what they can't know without looking at the implementation otherwise). 
And so json unserialization is not changed (because it was the faulty one). 
Also homogenize the pattern matching. Windows matches on fullname, Linux on name, but it can be made consistant.

Fixes #24703: OS type / name are not always compared lower case

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/ViewUtils.elm

https://issues.rudder.io/issues/24688

Fixes #24688: Beautify node properties tooltips label badge

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/View.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/ViewUtils.elm
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-datatable.css

https://issues.rudder.io/issues/24498
V2 (last edit)
-----------------

Fixes #24498: There is no easy way to copy a property/inventory variable name to clipboard

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/ViewUtils.elm

https://issues.rudder.io/issues/24497

Fixes #24497: Node properties override hovers are not well rendered

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTechniqueTabs.elm
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/TechniqueCategoryEditForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/RuleCategoryPopup.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/model/RudderBaseField.scala
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-bootstrap.scss
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-main.scss
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder.css
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentDirectiveEditForm.html
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentRuleEditForm.html
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/NodeGroupForm.html
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/server/server_details.html

https://issues.rudder.io/issues/24717

Fixes #24717: The font weight of labels is too low

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala

https://issues.rudder.io/issues/24691
Throwing an exception short-circuits the checks in order to disallow the login of a disabled user.
It will ignore other provisioning logic (e.g. check `enabled` status from Okta) though

Fixes #24691: 

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala

https://issues.rudder.io/issues/12791
Add a button to reset the key status if:
- current user has write admin rights, 
- current key status is "certified". 
On backend, it's just a call to the relevant `woNodeRepository` function, plus some html/ajax to make it works. 
I needed to extract the div with security info to make it displayable again after change. 
I prefered to rebuild it all than just changing the icon because the key/key status logic is complex and I wanted to use the same logic for displaying (so that nothing change after reload). 
[change-key-status.webm](https://github.com/Normation/rudder/assets/44649/3d406506-21d7-45d1-984e-46bf86ca5b56)

Fixes #12791: Have a reset-keys button on the node screen

---

relay/sources/rudder-package/src/archive.rs
relay/sources/rudder-package/src/webapp.rs

https://issues.rudder.io/issues/24740

Fixes #24740: The webapp is needlessly restarted when enabled an already enabled plugin

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/policies/RuleTarget.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/NodeGroupRepository.scala

https://issues.rudder.io/issues/24665
It's likely an older bug than that, I need to check it better. 
EDIT: it's from 7.3. 
But the only usage of that method in all rudder seems to be for badge, so not too important.

Fixes #24665: Number of nodes in rule badge is not correct with tenants

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala

https://issues.rudder.io/issues/24734

Fixes #24734: Remove System compliance from Score

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/Compliance.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ComplianceApi.scala
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewUtils.elm

https://issues.rudder.io/issues/22525
We need to add all the details of a skipped directive in the compliance API (here only for the `Rules` compliance API)
Here we are reusing [the logic](https://github.com/Normation/rudder/blob/branches/rudder/7.3/webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ComplianceData.scala#L438) used in the server-rendered compliance which is now added to the API in a new JSON field : 
```
"skippedDetails": { "overridingRuleId": ..., "overridingRuleName": ... }
```
**Result :**

Fixes #22525: Directives applied twice don't show in rule details (they should be skipped)

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala

https://issues.rudder.io/issues/24712
Correct three loops (one in pending, two in unexpected handled in one case). Tested in the load server, which is now doing nothing in place of continously expiring / computing compliance.

Fixes #24712: ExpiredCompliance events are pilling up

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/View.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/ViewModals.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/ViewUtils.elm

https://issues.rudder.io/issues/24741
We have the case of the [Bootstrap 5 doc](https://getbootstrap.com/docs/5.2/components/modal/#toggle-between-modals) where we have the same modal for different actions (create, edit, regenerate and delete)

Fixes #24741: Close icon does not close the modal for creating an API account

---

webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-template.scss

https://issues.rudder.io/issues/24748
Since we no longer have the nodes table in the "Properties" tab, we no longer need the bottom spacing ("Parameters" and "Criteria" tabs also don't need this spacing)

Fixes #24748: Group property table is cropped

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Score/View.elm
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-compliance.scss

https://issues.rudder.io/issues/24744

Fixes #24744: Score explanation should not move score element when text is too long

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderProviderManager.java
webapp/sources/rudder/rudder-web/src/main/webapp/WEB-INF/web.xml

https://issues.rudder.io/issues/24017
Spring sees the session id as `null` in this case, authentication could happen when the session has not yet been created.
To create it, we just need to [ServletRequestAttributes#getSessionId()](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/context/request/ServletRequestAttributes.html#getSessionId()) which will create a new one, it will still be the one effectively used to login.

Fixes #24017: Webapp can fail to start with null sessionid error 

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala

https://issues.rudder.io/issues/24749
Authentication validation should be the same as with "file" or "OIDC" : call `loadUserByUsername`, which takes into account the user status from the database to refuse authentication of disabled users.
There is some slight change in behavior : for LDAP users which were not found in the "users.xml" file we proceeded with a successful login but with no rights. Now, we fail at the login step. It is more consistent with the behavior for disabled users from "file" or "OIDC" backends.

Fixes #24749:  Disabled LDAP users can still login and use Rudder

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/users/User.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/users/UserRepository.scala

https://issues.rudder.io/issues/24757
The `tenants` column in the database is nullable (it is null especially when server is upgraded from 8.0 to 8.1).
Changing the case class changes the doobie Meta and now the null values before migration will not throw an error

Fixes #24757: Unable to log in - Server error

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/JsonResponseObjects.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/GroupsInternalAPI.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_groupsinternal.yml
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
webapp/sources/rudder/rudder-web/src/main/elm/sources/Groups/ApiCalls.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Groups/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Groups/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/24723
Adding an internal groups API and using it instead of the public one.
All the JSON datatype is made with zio-json and chimney, and it is almost the same model as a full group category, because all the information is needed in the Elm app except the node ids.
Also added API tests for that (FYI the tests for the public groups API does not have one for the tree endpoint)

Fixes #24723: Tree group is slow to load up because it contains the list of nodes in the tree

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/policies/RuleTarget.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/NodeGroupRepository.scala

https://issues.rudder.io/issues/24772
So, the main idea is to have as little computing done as possible in the recurring part. Especially, we want to avoid any `contains` or `set.intersec` in that part. 
Since the parent change was introduced because we need to always know what the real set of node Ids is, and not assume that the content of group's `nodeIds` is the reality, we just always intersect the result of the recurring function with the keySet of the map of "allNodes". 
Also remove reference to map view here, to avoid unecessary cast from SetView to Set, even if that change was tested to account for almost no perf change at all.

Fixes #24772: RuleTarget compliance is very slow to compute

---

relay/sources/relayd/src/processing/reporting.rs
relay/sources/relayd/tests/processing_reporting.rs

https://issues.rudder.io/issues/24792

Fixes #24792: relayd stops runlog processing on invalid run info

---

webapp/sources/Dockerfile
webapp/sources/rudder/rudder-web/pom.xml
webapp/sources/rudder/rudder-web/src/main/elm/elm.json
webapp/sources/rudder/rudder-web/src/main/elm/review/elm.json
webapp/sources/rudder/rudder-web/src/main/elm/review/src/ReviewConfig.elm
webapp/sources/rudder/rudder-web/src/main/package-lock.json
webapp/sources/rudder/rudder-web/src/main/package.json

https://issues.rudder.io/issues/24762
Requires upgrading the node versions used on the CI. Using Node 20 LTS.
I started from jfmengel's "starter pack" for applications, and disabled most rules to allow easy integration, but some rules are interesting, especially some suggestions of the Simplify rule.
Detected and removed 3 unused dependencies:

Fixes #24762: Add basic elm-review config

---

webapp/sources/pom.xml

https://issues.rudder.io/issues/24768

Fixes #24768:  Update Scala dependencies

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/plugins/PluginStatus.scala

https://issues.rudder.io/issues/24817
Successfully where to add the check to be useful. 
Now, the log looks like that at start: 
At at run time, when a limited feature is triggered:

Fixes #24817: When there are more nodes than supported by licenses, no logs in webapp states it

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/homePage.js
webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder-datatable.js
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-dashboard.css
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-progress-bar.css

https://issues.rudder.io/issues/24788
Previously, the width of the compliance bars was calculated as a percentage, which involved many calculations to determine the correct width of each of the bars according to their value.
Thanks to the flexbox CSS property, we no longer need to calculate the width of the bars, and the minimum size is defined in CSS.
This avoids calculation errors and incorrect total bar widths.

Fixes #24788: Empty space in global compliance bar

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/AcceptNode.scala

https://issues.rudder.io/issues/24832

Fixes #24832: Migrate rudder-web to zio-json

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/users/UserRepository.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/users/UserRepositoryTest.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderUserDetailsFile.scala
webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/RudderUserDetailsTest.scala

https://issues.rudder.io/issues/24839
To load a user we both need to consider case-sensitivity when : 
* getting the user id from the database => we need to search with `LOWER(id)`
* getting the user name from the users xml file (which is a map with the original file usernames as keys) => we search the key matching a case-insensitive comparison, there will only be one result because we already ignore duplicates when validating the file

Fixes #24839: We cannot login with a user login containing uppercase letter if the option case-sensitivity is set to false

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/Compliance.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ComplianceApi.scala
webapp/sources/rudder/rudder-web/src/main/elm/sources/Compliance/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeCompliance/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeCompliance/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeCompliance/ViewUtils.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/ViewUtils.elm

https://issues.rudder.io/issues/24097
Essentially the same as https://github.com/Normation/rudder/pull/5600, and with some refactoring : 
* move the Elm model for `SkippedDirective` to the Elm `Compliance.Datatypes` module
* compute the skipped directives in a method which takes the conversion `DirectiveComplianceOverride => T` as a param, either `ByRuleDirectiveCompliance` or `ByRuleDirectiveCompliance` (this PR)

Fixes #24097: Skipped directive does not show in node compliance tree

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitArchivers.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/xml/TestBuildPathUtils.scala

https://issues.rudder.io/issues/24856
Restrict paths to "local" ones i.e. `rules/` for `GitRuleArchiverImpl` class and `parameters/` for `GitParameterArchiverImpl`.
Ideally we should remove all `new File(_)` calls and replace with validated ones, I checked and found only those two, the remaining ones act on categories, for which we made very similar changes in https://github.com/Normation/rudder/pull/5314  but with additional "category" parent (e.g. `techniques/application/cat1/`)

Fixes #24856: 

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/NewNodeManager.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/RemoveNodeService.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/nodes/NodeInfoServiceCachedTest.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/AcceptNode.scala

https://issues.rudder.io/issues/24869
For some reason, the "version" i.e. DateTime of the inventory couldn't be retrieved in the _nodefacts_ table after the `HistorizeNodeStateOnChoice` acceptor saved it, maybe it is just the wrong timing or the ordering of acceptors is wrong...
So instead just pass the same datetime into context everywhere and don't rely on that for logging into the event log :grin:...
(I have not tested this PR but it compiles)

Fixes #24869: Node acceptation or refusal is not logged in event logs in 8.0

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/appconfig/ConfigService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SettingsApi.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_settings.yml

https://issues.rudder.io/issues/24845
The setting key in the API : `enable_validate_all`

Fixes #24845: Option to force validation of change requests cannot be set via API

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/tree.js

https://issues.rudder.io/issues/24854
We need rebind the event handler also when a node is redrawn (which happens when changing the search filter)

Fixes #24854: Cannot open a directive if we search in the directive tree with the filter

---

webapp/sources/rudder/rudder-web/src/main/elm/elm.json

https://issues.rudder.io/issues/24857
Only one package wasn't up to date : `mercurymedia/elm-datetime-picker` (from **8.0.0** to **8.0.1**)

Fixes #24857: Update elm dependencies

---

webapp/sources/api-doc/code_samples/curl/plugins/get-plugins-settings.sh
webapp/sources/api-doc/code_samples/curl/plugins/info.sh
webapp/sources/api-doc/code_samples/curl/plugins/set-plugins-settings.sh
webapp/sources/api-doc/components/schemas/plugins-info.yml
webapp/sources/api-doc/components/schemas/plugins-settings.yml
webapp/sources/api-doc/openapi.src.yml
webapp/sources/api-doc/paths/plugins/info.yml
webapp/sources/api-doc/paths/plugins/settings.yml
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/plugins/PluginSettings.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/PluginApi.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TestRestPluginInfo.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/plugins/PluginStatus.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/plugins/RudderPlugin.scala
webapp/sources/utils/src/main/scala/com/normation/utils/DateFormaterService.scala

https://issues.rudder.io/issues/24826
Add a public API to get information about the installed plugins and their limits. 
The returned JSON structure start by global limits if any, which are computed to present the most restrictive limits (ie, if a plugin limits to 200 nodes and one to 500, then 200 is given). 
Then, we have an array with installed plugins and their specific limits if any. 
Most of the PR is documentation for that API, and for the plugins repo setting API, which was missing. 
There is nothing complicated at all, but two noticable points: 
- I've started using `java.time` API, and added the relevant formatter/etc in `DateTimeFormaterService` ; 
- plugin's license object needed to be migrated from `rudder-web` to `rudder-rest`;

Fixes #24826: Add an API endpoint to get plugin license info

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/Init.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/View.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/ViewModals.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/ViewUtils.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/GroupRelatedRules/View.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/ViewUtils.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/View.elm

https://issues.rudder.io/issues/24834
I had to replace the use of bootstrap attributes with a "hard-coded" display of modals in Elm. + I've made the content of the modal scrollable, so that the height of the modal doesn't exceed the height of the screen.

Fixes #24834: When we save an API Token, the UI is grayed out

---

webapp/sources/api-doc/components/schemas/campaign-details.yml
webapp/sources/api-doc/components/schemas/campaign-schedule-daily.yml
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/DataTypes.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/JsonCampaignSerializer.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/MainCampaignService.scala

https://issues.rudder.io/issues/24701

Fixes #24701: Add daily schedule for campaign

---

deny.toml

https://issues.rudder.io/issues/24895

Fixes #24895: Allow Boost Software License in Rust crates

---

webapp/sources/utils/src/main/scala/zio/syntax.scala

https://issues.rudder.io/issues/24907
So, at some point `ZIO` changed implementation of `ZIO.succeed` to make its parameter call by name, which was not reflected in our syntax add-on, which means that we were capturing the result of the computation and not a real effect.

Fixes #24907: The list of plugin in info API is always empty

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Compliance/Utils.elm

https://issues.rudder.io/issues/24882
The list of status was the list of status to filter out, not the list of statuses to include. hence an empty list of filters was filterint out all statuses making and empty compliance bar

Fixes #24882: Compliance doesn't show up at the top level in rudder 8.1.3~nightly

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/homePage.js
webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder-datatable.js
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/HomePage.scala
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-dashboard.scss
webapp/sources/rudder/rudder-web/src/main/webapp/secure/index.html

https://issues.rudder.io/issues/24829

Fixes #24829: Replace compliance chart with Score chart and and new details score charts

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/tree.js
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/TechniqueLibraryManagement.scala

https://issues.rudder.io/issues/24439
This follows the problem in groups and directives tree in https://github.com/Normation/rudder/pull/5382 : the same problem appeared for the `techniqueLibraryManagement` page.
* The tree almost has the same structure as the directive tree, but we only have "technique nodes" 
* I refactored duplicate code that alters the `allEvent` global variable

Fixes #24439: Clicking on technique in technique tree doesn't do anything

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder-datatable.js
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/SrvGrid.scala

https://issues.rudder.io/issues/24925
Since we now pass the scores list directly as JS object from the _Scala_ code, we need to move the `allColumns` variables into the scope where we have access to the scores list, as it needs the list.
Changes consist of : 
* moving global variables into `createNodesTable`
* propagate `scores` list where it is needed (when refreshing and reloading tables)

Fixes #24925: Refresh on nodes tables leads to datatable and console error 

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/homePage.js
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/HomePage.scala

https://issues.rudder.io/issues/24930
* Replace the black color (empty `""`) with gray (`#d8dde5`, same as the gray color for the gauge in the dashboard)
* Display `No ... score found` instead of `X` which is not very user-friendly. With chart.Js, it seems that the legend text is hard to customize, so need to map the label `No ... score found` back to the `X` label when building query filters when redirecting to nodes page...
**Screenshot :**

Fixes #24930: Compliance score chart for vulnerabilities is all black with X

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/Groups.scala

https://issues.rudder.io/issues/24942
The problem was that the Elm app is not mounted when a refresh of the whole DOM occurs on the server side (it leaves the `<div id="nodeproperties-app"></div>` as is).
We just forgot to initialize the app each time it occurs : on success or failure of the node group form update.

Fixes #24942: Properties tab in groups has no content after a save

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/score/ScoreRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/score/ScoreService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/RemoveNodeService.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/24940

Fixes #24940: Compliance score are still kept for deleted nodes

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/LdapQueryProcessor.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/NodeFactQueryProcessor.scala

https://issues.rudder.io/issues/24937
My initial though was that the query was not translated correctly in LDAP, but it quickly that was not the problem thanks to @clarktsiory with the trace logs we figure it out that the query was finding the node in the logs
`ubuntu22.rudder.local` is the hostname of my pending node in my example
```
2024-05-28 17:24:05+0200 DEBUG query.node-fact.metrics - Analyse query in 1 ms
2024-05-28 17:24:05+0200 DEBUG query.node-fact - (only matches node and relay) && ([node.nodeHostname eq ubuntu22.rudder.local])
2024-05-28 17:24:05+0200 DEBUG query.node-fact -   --'ubuntu22.rudder.local' (76b87d59-479a-4e1c-9c02-582df36d02b8)--
2024-05-28 17:24:05+0200 TRACE query.node-fact -     [true] for only matches node and relay on 'Node'
2024-05-28 17:24:05+0200 TRACE …
```

Fixes #24937: Query in get pending node API doesn't match anything

---

webapp/sources/api-doc/introduction.md

https://issues.rudder.io/issues/24899
New API definitions since v19 : 
Both set of endpoints for tenants are listed under `Multi-tenants` section in the existing API doc

Fixes #24899: API v19 documentation is missing in 8.1

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/ApiCalls.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Agentpolicymode/ApiCalls.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/DirectiveCompliance/ApiCalls.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ApiCalls.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/FileManager/Action.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Filters/ApiCalls.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/GroupCompliance/ApiCalls.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/GroupRelatedRules/ApiCalls.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Groups/ApiCalls.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Hooks/ApiCalls.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Node/ApiCalls.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeCompliance/ApiCalls.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/ApiCalls.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/QuickSearch/ApiCalls.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/ApiCalls.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Score/ApiCalls.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Tags/ApiCalls.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/UserManagement/ApiCalls.elm
webapp/sources/rudder/rudder-web/src/main/resources/applicationContext-security.xml
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RestSecureAuthenticationFilter.java

https://issues.rudder.io/issues/24897
I chose to go with the same header used by jQuery.
Tested with:
```
<LocationMatch /rudder/secure/api/>
<RequireAll>
Require expr %{HTTP:X-Requested-With} == 'XMLHttpRequest'
</RequireAll>
</LocationMatch>
```
in apache configuration. Still lacking the same in API auth code (I could not find where to add it). And we'll obviously have to do the same in the plugins.

Fixes #24897: 

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/users/User.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/users/UserRepository.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/UserManagementApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/users/UserManagement.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_usermanagement.yml
webapp/sources/rudder/rudder-rest/src/test/resources/test-users.xml
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/users/UserSerializationTest.scala
webapp/sources/rudder/rudder-web/src/main/elm/sources/UserManagement/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/UserManagement/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/UserManagement/View.elm
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-user-management.scss

https://issues.rudder.io/issues/24865
Change is both in the API and the UI :
* in the API : 
* add `tenants` as a string, which is sourced from `users.xml` file or the _usersessions_ table. I had no choice but parse it as a regex since from the `tags:[...]` format is not the one we want to display in the table, so API value is either `all`, `none` or `zoneA, zoneB`
* add `previousLogin`, to be distinguished from `lastLogin` which could be the "current login with still an open session"
* in the UI : 
* display tenants as is, but consider `all` and `none` as special values 
* use `previousLogin` everywhere instead of `lastLogin` because that's what we want to display wrt semantic of columns. We will use `lastLogin` information later to infer if the user is currently logged in, and display a …

Fixes #24865: User management should display tenants, last and previous session

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/UserManagementApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/users/RudderUserDetailsFile.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/users/UserManagement.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/users/UserManagementService.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_usermanagement.yml
webapp/sources/rudder/rudder-rest/src/test/resources/test-users.xml
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-web/pom.xml
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/migration/CheckUsersFile.scala
webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/RudderUserDetailsTest.scala
webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/RudderUserPasswordEncoderTest.scala
webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/migration/TestCheckUsersFile.scala

https://issues.rudder.io/issues/24729
* Makes a new `RudderPasswordEncoder` class that acts as a redirection to the correct encoder based on encoded password format
* Try to encapsulate better the internals of password management inside `RudderPasswordEncoder`
* Add a simple `securityLevel` lever to only allow legacy hashes when necessary
* Add the migration logic on the users file, run at startup and on reload, by using a boolean attribute `unsafe-hashes` to still be able to use legacy hashes

Fixes #24729: Allow using a different password hash algorithm for each local user

---

webapp/sources/rudder/rudder-web/src/main/gulpfile.mjs
webapp/sources/rudder/rudder-web/src/main/package-lock.json
webapp/sources/rudder/rudder-web/src/main/package.json

https://issues.rudder.io/issues/24722
Only two js dependencies have been updated in this PR :
- del : from 6.1.1 to 7.1.0
- gulp : from 4.0.2 to 5.0.0
The gulpfile.js file (now **gulpfile.mjs**) has been converted into an Ecmascript module , so that the new version of del package can be imported as a module (that package has become an esm-only package in this new version). `gulp-cli` supports ESM so this change has no side effect.
This implies a few changes to the file :
- Most of them are listed in this guide : https://gist.github.com/noraj/007a943dc781dc8dd3198a29205bae04
- clean() function has been rewritten because of the change in the behaviour of the del package functions
- and in addition, merge-stream has been replaced by merge2 as it did not work with the new changes, and …

Fixes #24722: Update gulp related js dependencies

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/tree.js

https://issues.rudder.io/issues/24784
Within the node details page, the group tree was still having disappearing event handlers (even without the console error) : 
* it seems like the previous selectors for tree elements with `lift-event-js-` id was not applied to the _pencils_ (in the `.treeActions` container) 
* the rendering of the tree only populates event handlers when the `ready.jstree` event is fired
N.B. : the use case here and the fix here are specific to the node details page, the groups page renders the tree using Elm and does not use the modified code

Fixes #24784: Nodes page has console error from the tree script

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/facts/nodes/NodeFact.scala

https://issues.rudder.io/issues/24991
[The change](https://github.com/Normation/rudder/pull/5713/files#r1634555658) introduced a `toLowerCase` but I don't see any reason to add this compatibility, we parse the same JSON that we produced for nodefacts

Fixes #24991: Fix Migrate rest test from yaml file to zio-test

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder-datatable.js
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleDisplayer.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateRulePopup.scala

https://issues.rudder.io/issues/24472
I think this is the simplest solution for bringing the filters back on the target rules (starting with the search bar), while waiting for this interface to be completely rewritten in Elm.
I removed all the dead code linked to the angular application that managed the filters, and replaced it with a simple javascript function, adding an onkeyup event to the search input :

Fixes #24472: We should rework the targets rules page when we create a directive

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RoleApiMapping.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala

https://issues.rudder.io/issues/25008
So, when someone does not have the compliance rights, we want to display a nice message in place of the red frightening pop-up. 
Still, we want that someone with the `node_read` right is able to see the "system status" tab, since that compliance is not really compliance, it's just "how rudder is working on that node" - so totally what `node_read` should give access to. 
So with the correction and a `node_all` right, you now get: 
For compliance: 
For system status:
(same as before)
Code is just an added "if" and a new API right for the system status case.

Fixes #25008: When node compliance right is missing, we don't want a red error pop-up

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/properties/Properties.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/MergeNodeProperties.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/nodes/TestMergeGroupProperties.scala

https://issues.rudder.io/issues/24988
When having an inheritance chain with more than 1 parent/child relationship, properties from child are being merged without really taking the global parameter inherit mode into account...
N.B. : This only fixes the inheritance when there is a global parameter along the chain. By default, the inherit mode for arrays is "override", so it makes sense

Fixes #24988: Property inheritance of type array doesn't work

---

webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/FullInventoryRepositoryImpl.scala
webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/InventoryMapper.scala
webapp/sources/ldap-inventory/inventory-repository/src/test/scala/com/normation/inventory/ldap/core/TestInventory.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/facts/nodes/MockLdapFactStorage.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/facts/nodes/TestCoreNodeFactInventory.scala
webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/25035
So, the problem is that #3899 changed the way processes were stored without changing it in `FullInventory.save`. 
So this was working for new inventories using the `DefaultInventoryAccept` workflow. 
But in 8.1, we changed the way node inventory are persisted to always use  `NodeFactStorage` and thus always using `FullInventoryRepo.save` which didn't have the logic to save processes. 
I added a configurable threshold to switch the behavior between one write request or two write request (many processess), since most of the time, it will be much more efficient to have only one write request. 
The threshold choice at 1000 is the result of a fair negociation with @VinceMacBuche.
~The property is hidden by default, because no user should have a need to …

Fixes #25035: Process are not saved anymore in 8.1

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ExpectedReportsJdbcRepository.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/migration/DeleteArchiveTables.scala

https://issues.rudder.io/issues/25033
Parent pr was not doing what it said it does:
- deleted `nodeCompliance` when it should not have, 
- kept some sql on deleted `archivedNodeCompliance` which will have lead to an exception

Fixes #25033: Do node delete table nodecompliance

---

webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-pre-start/hook-template
webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-pre-start/readme.adoc
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala

https://issues.rudder.io/issues/24944

Fixes #24944: Add pre generation hook

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/facts/nodes/NodeFact.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/ShowNodeDetailsFromNode.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/NodeGrid.scala

https://issues.rudder.io/issues/25044
We were just not querying `processes`, which well explain why we didn't have them. And also validate the fact that `SelectAttrs` works well.

Fixes #25044: Processes are not displayed anymore in 8.1

---

relay/sources/rudder-package/src/lib.rs

https://issues.rudder.io/issues/25048
The problem appeared when errors were made non-fatal (replacing `bail!()` with `error!()`).

Fixes #25048: When a plugin fails to download, the installation is considered successful

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala

https://issues.rudder.io/issues/24827

Fixes #24827: When we have a user without administrator role, the menu "Utilities" exist but leads to a 404

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/TagsEditForm.scala

https://issues.rudder.io/issues/25073
`Str(...).toJsCmd` does not escape all characters (like `'`, `)`, `}`, ...), so we need to use `StringEscapeUtils.escapeEcmaScript`

Fixes #25073: 

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/StatusReports.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ComplianceTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ExecutionBatchTest.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/appconfig/ConfigService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SettingsApi.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_settings.yml
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/AsyncComplianceService.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PropertiesManagement.scala
webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/policyServerManagement.html

https://issues.rudder.io/issues/25088
Some well needed cleaning in `ReportingService` (first step, other will follow): 
**Getting only user/system compliance**
A lot of code in reporting service is based on the pattern : 
``` 
rules <- getRules(system = false) // only user rules
compliance <- computeComplianceForNodes(limitToRules = rules.map(_.id))
```
Or the same thing for system rule, getting all rules then diffing. 
This is not needed anymore since we have now a `Map[PolicyTypeName, AggregatedStatusReport]` now in `NodeStatusReport`. 
**Class methods when they can be object ones**
`ReportingService` trait has several method that are not linked to service dependencies and can be moved to its companion object. 
**Unused methods/classes**
Some methods were just unused anywhere: …

Fixes #25088: Remove unused methods in ReportingService

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Groups.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/QuickSearch/View.elm
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/Groups.scala

https://issues.rudder.io/issues/25046
When [changing the URL hash](https://stackoverflow.com/a/52809105) while navigating to the quicksearch result on the same page, we need to : 
* parse the URL for `{"directiveId":...}` in the directives page, which calls back existing method to display the directive
* parse the URL for `{"groupId":...}` in the groups page, which calls an Elm port to load the group
Also, in every case, when changing the URL from clicking a quicksearch result, we will no longer need the quicksearch so we can send the `Close` message

Fixes #25046: Some results of quicksearch cannot be opened 

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/TechniqueEditForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala
webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/directiveManagement.html
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentRuleEditForm.html

https://issues.rudder.io/issues/25054
- If there is no documentation, then the field is hidden
- The description is no longer formatted in markdown, only the documentation should be

Fixes #25054: No documentation on built-in techniques

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/ViewUtils.elm

https://issues.rudder.io/issues/25109
Just enable editing an "inherited" property, it just works like when editing a node property as usual...
The only thing is, we cannot delete "inherited" properties, but only "overriden" ones

Fixes #25109: Create property from inherited one

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/EventListDisplayer.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/WithEnabledCSP.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/Archives.scala
webapp/sources/rudder/rudder-web/src/main/webapp/secure/utilities/archiveManagement.html
webapp/sources/rudder/rudder-web/src/main/webapp/secure/utilities/eventLogs.html
webapp/sources/rudder/rudder-web/src/main/webapp/secure/utilities/healthcheck.html

https://issues.rudder.io/issues/25032
* :bulb: Replace the regex-based filtering of CSP headers, and use a lift directive instead : `data-lift="with-enabled-csp"` to include in every HTML page for which to enforce strict-CSP
* :hammer: Migrate scripts in Archives page
* :hammer: Migrate scripts in Event logs page
*  :hammer: Reuse the lift directive in the Healthcheck page

Fixes #25032:  Use Content-Security-Policy strict headers in utilities pages

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/DebugComplianceLogger.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/NodeComplianceExpiration.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/StatusReports.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/reports/execution/ReportsExecutionService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ComplianceRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ComplianceExpirationService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ComputeNodeStatusReportService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/NodeChangesService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/NodeStatusReportRepository.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/reports/StatusReportTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ComplianceExpirationServiceTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ExecutionBatchTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ReportingServiceUtilsTest.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala

https://issues.rudder.io/issues/25120
This PR add the possibility to delay node compliance expiration based on a settings given via a node property. 
It implements the bottom service `ComplianceExpirationService` on the schema.
The main changes are: 
- add a new `KeepLastCompliance` run info case 
- change nothin in `ExecutionBatch` - the analysis of weither we keep or not last compliance when we have a `NoReport` is done latter on and is not based on a run/expect report analysis (obviously)
- add the logic to check is a node is configured to keep compliance in `ComputeNodeStatusService` based on `{"rudder": { "keep_compliance_duration": "duration" }}` node property
- the duration format is the standard one for scala: an integer followed by an unit, ie something like `2 days` or `48 …

Fixes #25120: Use node properties to decide how long compliance is valid

---

policies/rudderc/src/backends/metadata.rs
policies/rudderc/tests/cases/general/escaping/metadata.xml
policies/rudderc/tests/cases/general/form/metadata.xml
policies/rudderc/tests/cases/general/ntp/metadata.xml
policies/rudderc/tests/cases/general/param_in_condition/metadata.xml
policies/rudderc/tests/metadata/serialized.xml
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/domain/VariableAndSectionSpec.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/xmlparsers/CfclerkXmlConstants.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/xmlparsers/VariableSpecParser.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueCompiler.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/BuildBundleSequence.scala
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/testing_variables_in_conditions/1.0/metadata.xml
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/1.0/metadata.xml
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/2.0/metadata.xml
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/metadata.xml
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/cfclerk/domain/VariableTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/cfclerk/services/DummyTechniqueRepository.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/policies/SectionValTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeExpectedReportTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/RuleValServiceTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestJsEngine.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestNodeAndGlobalParameterLookup.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/write/PolicyAgregationTest.scala
webapp/sources/rudder/rudder-web/src/test/scala/com/normation/rudder/web/services/Section2FieldServiceTest.scala

https://issues.rudder.io/issues/25091
Add a `VARIABLENAME` metadata parameter that is used only for power geneation (paramter names). 
It hold the technque editor parameter "parameter name", ie a normalized name with only alpha-num and `_` chars. 
This what `NAME` used to be in metadata.xml, but it was change to an UUID at some point so that the technique editor can retrieve parameters.

Fixes #25091: Add VARIABLE_NAME to technique so that we can use valid parameter name in techniques

---

webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/FusionInventoryParser.scala
webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-inventories/dsc-agent.ocs
webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-inventories/rudder-tag/minimal-one-agent.ocs
webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-inventories/rudder-tag/minimal-two-agents-fails.ocs
webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-inventories/rudder-tag/minimal-zero-agent.ocs
webapp/sources/ldap-inventory/inventory-fusion/src/test/scala/com/normation/inventory/provisioning/fusion/TestReportParsing.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/facts/nodes/NodeFact.scala

https://issues.rudder.io/issues/25164
Check for missing agent version in parsing to get a correct error message. 
Relax a bit the check on node fact transformation to make it easier to spot that kind of problem.

Fixes #25164: When agent version is missing in inventory, we get a security token error

---

Cargo.lock
deny.toml

https://issues.rudder.io/issues/25191

Fixes #25191: RUSTSEC-2024-0357 vulnerability in openssl lib - 8.1

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/ApiDatastructures.scala

https://issues.rudder.io/issues/25246

Fixes #25246: Unauthorized access to API should not be logged as error

---

relay/sources/rudder-package/src/archive.rs

https://issues.rudder.io/issues/25275
Current ouput:
```
INFO Installing rudder-plugin-security-benchmarks-8.2.0~alpha2-1.0-nightly.rpkg
INFO Installing rpkg 'rudder-plugin-security-benchmarks-8.2.0~alpha2-1.0-nightly.rpkg'...
```
This makes no sense.

Fixes #25275: Make plugin install log less verbose

---

relay/sources/rudder-package/src/archive.rs

https://issues.rudder.io/issues/25282
The problem here is that the uninstallation rremoves the script after preinst run. So the postinst never actually runs.

Fixes #25282: Postinst script are not run during upgrades

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RoleApiMapping.scala
webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/ApiCalls.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/ChangeRequest.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/Init.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/ViewTabContent.elm
webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/ruleManagement.html

Retargeted from #5678 
https://issues.rudder.io/issues/24863
It seems like there is bigger issue under this one.
The initial problem was that when we go to a rule page, in Elm we initialize the page by fetching many information of which change-request's information that required `administration_read` right.
```
enable_change_message
enable_change_request
enable_self_deployment
enable_self_validation
enable_validate_all
```
In the initialization of the Rule page, we check if change-request is enabled. This fetching is done through [settings API](https://docs.rudder.io/api/v/19/#tag/Settings/operation/getAllSettings) [GetAllSetings](https://github.com/Normation/rudder/blob/master/webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala#L535) that …

Fixes #24863: when we have compliance right, the rule page shows a weird message

---

webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_groups.yml
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_nodes.yml

https://issues.rudder.io/issues/25203
Main change consists of changing `.toLiftResponseOne` to `.toLiftResponseList`.
Everything else is about : 
* adding mock nodes (`node1-pending` for acceptation and `node2-pending` for refusal) 
* adding API tests for the two faulty endpoints
* making other tests pass (groups API tests needs to include the added nodes)

Fixes #25203: The pending nodes API now returns array of arrays of nodes instead of an array of nodes

---

policies/rudderc/src/lib.rs

https://issues.rudder.io/issues/25238

Fixes #25238: rudderc is generating 0 bytes resources when output directory is the same as the input

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/HomePage.scala

https://issues.rudder.io/issues/25095
Indeed, if it is a `SessionVar`, nodes updates only get displayed the same as when logging in.
Previously, there has not been any `Var`, the node info was always requested anyway, it should be fetched from cache so it should not cause performance issues here

Fixes #25095: Dashboard information are not updated when deleting a node

---

webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Rules.elm

https://issues.rudder.io/issues/21668
We just need to backport `initTooltips` command from later versions or Rudder, in which we don't have the issue
(in 7.3, we didn't even initialize tooltips on first page render, but only when we open a Rule details :scream_cat:)

Fixes #21668: tooltips in the rules page persist when switching content

---

webapp/sources/api-doc/code_samples/curl/usermanagement/add.sh
webapp/sources/api-doc/code_samples/curl/usermanagement/update-info.sh
webapp/sources/api-doc/code_samples/curl/usermanagement/update.sh

https://issues.rudder.io/issues/25302
The _.sh_ files need to be valid Bash scripts and using multiline curl arguments for the JSON data is a way to make it a valid command

Fixes #25302: API documentation examples are not valid bash scripts

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/UpdateDynamicGroups.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/properties/Properties.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/NodeComplianceExpiration.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/properties/MergeNodeProperties.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/properties/NodePropertiesService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/properties/PropertiesRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ComplianceExpirationService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ComputeNodeStatusReportService.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/nodes/TestMergeGroupProperties.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestBuildNodeConfiguration.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ComplianceExpirationServiceTest.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/GroupsApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ParametersApi.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_groups.yml
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_nodes.yml
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_parameters.yml
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/25219
This PR add a `PropertiesRepository` that stores the computed/resolved `GroupProperties` and `NodeProperties`. 
The repository is very simple: it is just an pure in-memory one, back by a pair of `Ref[Map[objId,  Chunk[NodePropertyHierarchy]]`.
It is used in place of interactive inheritance computation in group/node API that get inherited props, and in policy generation. 
The part is policy generation is the riskiest change. Moreover, I think we are changing a bit the way things are done, because we use to do: 
- interpolate global props, 
- do inheritance resolution for node props with the result, 
- interpolate resolved node props. 
Now, we directly get inherited props and interpolate that. I *think* it's the same, and no tests show that it's …

Fixes #25219: Cache for node properties and hierarchies

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/UserManagementApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/users/UserManagement.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_usermanagement.yml
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
webapp/sources/rudder/rudder-web/src/main/elm/sources/UserManagement.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/UserManagement/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/UserManagement/Init.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/UserManagement/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/UserManagement/View.elm
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/24976
Change consists of adding the `tenantsEnabled` field in the API (the variable already exists), and conditionally displaying the table header and rows for the "Tenants" column based on a new boolean variable in the Elm model.

Fixes #24976: Tenants column in user-management should depend on plugin activation

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/users/UserManagement.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_usermanagement.yml

https://issues.rudder.io/issues/25296
`Rights` constructor enforce the `NoRights` authorization when passed an empty list. But in JSON we only want an empty list.
Screenshot of result :

Fixes #25296: User management table always shows additional 'no_rights' authorization

---

webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/db/DBCommon.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportsProgressTest.scala
webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/migration/TestMigrateChangeValidationEnforceSchema.scala
webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/migration/TestMigrateEventLogEnforceSchema.scala

https://issues.rudder.io/issues/25303
There is no such `CREATE TEMP TYPE score` in PostgreSQL, even if there is `CREATE TEMP TABLE`.
The solution here is quite radical : use a [schema](https://www.postgresql.org/docs/current/ddl-schemas.html) for tests, all tables, sequence, etc. creation will be under the schema, and it could be dropped at the end of tests, along with any structure that was declared in tests because they are configured to be within the schema.
An alternative solution which could be harder to maintain as we add new Types, is to explicitly drop the Type.

Fixes #25303: Database tests have non temporary DDL that prevents running them twice

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/users/UserRepository.scala
webapp/sources/rudder/rudder-web/src/main/resources/applicationContext-security.xml
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/UserSessionInvalidationFilter.scala

https://issues.rudder.io/issues/25307
We need to check on every request if the current user is still active or not (Lift does not provide a way to match our user sessions with the ones for all users, because there are session fixations from spring security happening at login so session ids are changed). So we use a Spring filter for that.
To be able to that efficiently, especially to avoid querying the users status on every request, we want to cache users status.
And updating the cache is done when the users file is reloaded after a disable/active in `user-management` (to work, it then requires changes from https://github.com/Normation/rudder-plugins/pull/744).

Fixes #25307: 

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/UserManagementApi.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/UserSessionInvalidationFilter.scala

https://issues.rudder.io/issues/25314
Includes the diff as in https://github.com/Normation/rudder-plugins/pull/744 but in Rudder,
and upmerge of https://github.com/Normation/rudder/pull/5816 in 8.2 (due to moving user-management in Rudder, some users classes have different namespaces)

Fixes #25314: Reload users file when user is disabled or activated upmerge in 8.2

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/UserSessionInvalidationFilter.scala

https://issues.rudder.io/issues/25322
* Wrap the whole block with `if (session != null)`, we will avoid as much methods calls as possible because this is executed at every request
* Add error handling and actionability for the control flow of the session : 
* invalidating the session may throw an exception when it is already invalidated (somehow from somewhere else in Rudder), just log it at info level
* invalidating the session successfully should be traced in logs at info level

Fixes #25322: Session could be null when checking user status

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder-datatable.js
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-datatable.css

https://issues.rudder.io/issues/25136
Because the columns in the node table are customisable and this table is still generated by datatable.js, the .head class cannot easily be added to the <tr> tag in the table header (without causing any side-effects). 
The simplest way is to apply the same css rule to this kind of table header
Now this header is identical to that of the other tables :

Fixes #25136: Nodes table sorting is not obvious and we need to guess the sort column and direction 

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/users/UserRepository.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderProviderManager.java
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderProviderManagerUtil.scala

https://issues.rudder.io/issues/25123
We just ignore the `insert` in that case, but it then needs to be done at the last operation of the database transaction because a sql error interrupts the whole transaction (hence the change of order).
Doobie provides a nice API for SQL errors, we just use it to log a user-friendly warning.

Fixes #25123: Authentication happens twice with same session id

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/users/UserRepository.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/users/UserRepositoryTest.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderUserDetailsFile.scala

https://issues.rudder.io/issues/24955
We need to only insert the user when it does not already exist with lowered id : 
```sql
INSERT INTO users (id, ...)
SELECT ?,...,?
WHERE NOT EXISTS (
SELECT 1 from users WHERE LOWER(id) = LOWER(?)
)
```
is the query that does that conditional insertion.
The user are not created in that case, so we need also a `RETURNING` clause to get back inserted users and compare with requested ones, to log non-created users as warning.

Fixes #24955: One user is created each case change even if case sensivity if false

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/JSONReportsHandler.scala

https://issues.rudder.io/issues/25350
This replaces #5835 
There is no error handling on the `loop` block, so when it has defects (uncaught runtime errors the fiber just terminates).
We need to use `catchAllCause` instead of `catchAll` for that purpose to catch other possible runtime errors, this process is really meant to run forever and retried every 5 seconds if needed.

Fixes #25350: no reports in campaign page even if the node sent the data

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/JsonQueryObjects.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestDataExtractorTest.scala

https://issues.rudder.io/issues/25368
The frontend has always posted an empty JSON body, but the current case class model expects at least a JSON object, not a "", so we get the infamous "Unexpected end of input". For simplicity and testability, any non-JSON object input should just be ignored with success.
This was not tested in the API yaml tests because the API response is bytes. We already have error cases for the API yaml tests though, except that the case of an empty string was never supposed to be an error :sweat_smile:

Fixes #25368: Apply policy returns a json error when clicking on trigger agent

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/ApiAuthorization.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/SharedFilesAPI.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_sharedfiles.yml
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/SharedFilesApiTest.scala
webapp/sources/rudder/rudder-web/src/main/elm/sources/FileManager/Action.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/FileManager/Model.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/FileManager/Update.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/FileManager/Util.elm
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/25155
The core of it is about error handling, but most of changes is about bootstraping tests for this API (to also help future zio-json migration), and testing this feature.
Example in Chrome (in Firefox, the client behavior makes it that we receive a browser `NS_ERROR_NET_RESET` error code which maps to a network error in Elm, so we need to also add the message just in case) :

Fixes #25155: Resources upload over 8 MB show error in log and not in UI

---

webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/GroupsApi.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_groups.yml
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_groupsinternal.yml
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupCategoryForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala

https://issues.rudder.io/issues/25348
We need to forbid the deletion of system groups and system group categories in the REST API (this PR adds the error handling and API tests for that).
However, in the UI we now want to allow cloning a system group which has a group target and an ID.
For the CVE groups, we now have them as system in https://github.com/Normation/rudder-plugins-private/pull/720, so we now redirect to CVE details page to delete them :
Illustration of the cloning part :

Fixes #25348: Deleting CVE group is possible even if it is a system group

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/ViewTabContent.elm

https://issues.rudder.io/issues/25371
The display is identical to the other rules which have no compliance.

Fixes #25371: Incorrect display of compliance in newly created rules

---

webapp/sources/ldap-inventory/inventory-repository/src/test/resources/ldap-data/inventory-sample-data.ldif
webapp/sources/ldap-inventory/inventory-repository/src/test/scala/com/normation/inventory/ldap/core/TestInventory.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/facts/nodes/NodeFact.scala
webapp/sources/rudder/rudder-core/src/test/resources/ldap-data/inventory-sample-data.ldif
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/facts/nodes/TestCoreNodeFactInventory.scala

https://issues.rudder.io/issues/25351
Previous inventory class before introduction of `SoftwareFact` already sees the version as optional.
Just add the option, make it compile and add a test to get the software from ldap (we will likely need to see how tests in 8.2 behave, there are many of them and for json).

Fixes #25351: Windows KB don't show up in the inventory anymore

---

webapp/sources/rudder/rudder-core/src/test/resources/node-facts/node-930dccb0-5b06-4385-ab7a-80a7e56eb969-v2.json
webapp/sources/rudder/rudder-core/src/test/resources/node-facts/node-930dccb0-5b06-4385-ab7a-80a7e56eb969.json

https://issues.rudder.io/issues/25387
There is a check that both files end up with the same final nodefact, it tests JSON decoders. The tests should pass because we should be able to decode a software without version this time

Fixes #25387: Add JSON tests for software without versions in 8.2

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/JsonQueryObjects.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/JsonResponseObjects.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/properties/Properties.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/properties/MergeNodeProperties.scala
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-default-install/properties.d/properties.json
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-one-multipolicy/properties.d/properties.json
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-two-directives/properties.d/properties.json
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/nodes/TestMergeGroupProperties.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/write/WriteTechniquesTest.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/GroupsApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ParametersApi.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_nodes.yml
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_parameters.yml
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/ArchiveApiTest.scala

https://issues.rudder.io/issues/25369
This PR add a new `visibility` attribute on properties (global, group, node) that can be either `hidden` or `displayed` (default value). 
That attribute direct the fact that a property is returned or not in API/UI/Archive. Even if `hidden`, a property will still be used for policy generation and transferred to node `properties.d/prorperties.json` file. 
That attribute is inherited, so that if the `benchmark_rsc01` property is defined at global level as `hidden`, then it is also `hidden` when inherited in groups or nodes. 
From a code point of view, it's just one more key in the config value for a properties. 
Contrary to other cases, I choose to never have the default value (`displayed`) stored. The semantic is "if the `visibility` key is not here, …

Fixes #25369: Add an optional visibility attribute on node property 

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchBackendImpl.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchDomain.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchQueryParser.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchService.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/quicksearch/QSRegexQueryParserTest.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/ApiAuthorization.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/RestQuicksearch.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_quicksearch.yml
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala

https://issues.rudder.io/issues/25334
We want the `limit` to be passed as REST query parameter instead of `limit:x` backend search : for now the `Query` case class is passed to the quicksearch backend param to transform into low-level query (LDAP, etc.), but this information is not actually used in any backend.
We only do the `take(limit)` at last when all results from a backend have been returned.
So the changes here removes the support introduced in https://github.com/Normation/rudder/pull/5778 and adds the support of the query parameter in place.
API tests have been bootstrapped for the Quicksearch API, and it was useful to understand and snapshot the behavior of the search (will also be useful when moving from lift-json to zio-json later).
Now it sees the number of requested elements …

Fixes #25334: Node property usage search seems to be limited to 10 elements

---

webapp/sources/pom.xml
webapp/sources/rudder/rudder-rest/pom.xml
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/SharedFilesAPI.scala
webapp/sources/rudder/rudder-web/pom.xml
webapp/sources/rudder/rudder-web/src/main/resources/applicationContext-security.xml
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/BootstrapChecks.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/LiftInitContextListener.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/LiftSpringSecurityFilter.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RestSecureAuthenticationFilter.java
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/UserSessionInvalidationFilter.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/action/LoadNodeComplianceCache.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/consistency/CheckConnections.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/consistency/CheckDIT.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/consistency/CloseOpenUserSessions.scala

https://issues.rudder.io/issues/25377
The update is rather simple once you know what must be done for Spring:
For the servlet part: 
- update the version of lift, spring to the new ones
- use the dependency to `jakarta` servlet 
- change all occurence of `javax.servlet` to `jakarta.servlet`
- update the dependency for commons fileupload to the version 2 for jakarta servlet5 and adapt corresponding namespaces
For Spring Security changes related to the migration from 5 to 6
- enable the SecurityContextPersistenceFilter with `authentication-strategy-explicit-invocation="false"`
- disable the need to explicitly persist in code the security context with `security-context-explicit-save="false"`
It's in draft because we will need a release of lift, in our repos to check this one.

Fixes #25377: Upgrade Rudder core to lift4 and spring 6

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/db/Doobie.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/DebugComplianceLogger.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/StatusReports.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ComplianceRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ComputeNodeStatusReportService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/NodeStatusReportRepository.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/reports/StatusReportTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ReportingServiceUtilsTest.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala

https://issues.rudder.io/issues/25311
Remove the big structure `NodeExpectedReports` that are kept in `NodeStatusReport`, in the `RunAndConfigInfo` part (ie the part where we keep information about the run, because we keep information about the run config information, ie config id and expected reports). Plus, current `RunAndConfigInfo` is too complexe for magnolia serialisation in any case. 
We don't need them appart for information about debugging/message that can be constructed without the whole structure. 
We also want to make the minimum changes and absoltly not touch at the compliance computation logic done in `ExcecutionBatch`. 
For that: 
- we duplicate the `NodeStatusReport` into a `NodeStatusReportInternal` so that nothing change in it, 
- that structure is translated into a …

Fixes #25311: Remove expected reports from NodeStatusReport

---

deny.toml

https://issues.rudder.io/issues/25404

Fixes #25404: Allow MPL-2.0 license in cargo checks

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/UserInformation.scala

https://issues.rudder.io/issues/25409
The name can be saved as an empty string, so we need to reject `Some("")` and display the _id_ instead

Fixes #25409: User identity does not show up in bar when user has last login

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/reports/execution/ReportsExecutionService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ComplianceRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ComplianceExpirationService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ComputeNodeStatusReportService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/NodeStatusReportRepository.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ComplianceExpirationServiceTest.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_groups.yml
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_nodes.yml
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_parameters.yml
webapp/sources/rudder/rudder-web/src/main/resources/logback.xml
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/action/LoadNodeComplianceCache.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala

https://issues.rudder.io/issues/25430
So, there was a lot of small things that got unaligned during the last changes. 
- I added a lot of ops logs that help understand what really happen on prod without a debugger on hand, 
- I renamed the PROP_KEY to PROP_NAME, because in rudder we use "property name" to mean the key (and so PROP_NAME becomes PROP_SUB_NAME)
- which lead to an error, I was looking for the property sub name in place of name to check the expiration policy, whiich was always empty (added a full integration test for that)
- I change the expiration date for computed `NoReportInInterval` in `ExecutionBatch` to never use "now", even when we don't know the date. Since we are persisting things in base now, we were continuously make the expiration date a bit latter, and so node …

Fixes #25430: Property sub-key is used in place of name for lookup

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/domain/VariableAndSectionSpec.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/StatusReports.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/yaml/YamlTechnique.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ExecutionBatchTest.scala
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/JsonEncoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewBlock.elm

https://issues.rudder.io/issues/25383
Adding a new worst reporting logic type "by percent" :
The reporting computation that results takes the worst with respect to computed compliance (using default compliance precision) :

Fixes #25383: Worst report takes the worst component instead of block

---

policies/rudderc/src/lib.rs

https://issues.rudder.io/issues/25439

Fixes #25439: Static rudderc builds are failing due to missing tracing import

---

webapp/sources/Dockerfile
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/domain/TechniqueCategory.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/GitTechniqueReader.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/git/ZipUtils.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ItemArchiveManager.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitArchivers.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitParseRudderObjects.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/cfclerk/services/JGitRepositoryTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestEditorTechniqueWriter.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ArchiveApi.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/ArchiveApiTest.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/24789
This PR introduces import and export of categories for technique. 
It adds a new file descriptors for them, `category.json` which mimics `category.xml` but in JSON for consistency with other file format in archive. 
The logic to parse each format was moved to `TechniqueCategoryMetadata` companion object so that everything is in one place.
Since category information where not updatable by API (internal or rest) up until now, I needed to also add the relevant logic to actually save changes in `/var/rudder/configuration-repository` in ` TechniqueArchiverImpl#saveTechniqueCategory`.
For the reading part, I was similarly forced to add new logic into `TechniqueRevisionRepository` to retrieve information corresponding to a specific revision id. 
The change …

Fixes #24789: Archive API for import/export doesn't know about technique

---

webapp/sources/rudder/rudder-web/src/main/webapp/secure/index.html

https://issues.rudder.io/issues/25448
Just put group after nodes:

Fixes #25448: Group position on dashboard statistics  make no sens

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/domain/VariableAndSection.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DataStructures.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/write/PolicyAgregationTest.scala

https://issues.rudder.io/issues/25429
This one use https://github.com/Normation/rudder/pull/5862
The main idea is that when we produce policy from a draft, we first try to assign default value to missing mandatory ones. 
This exposes a failing test that wasn't making sense: we have one test where we have null values for non-optionnal case. 
This test used to pass because we were only checking `v.values.exists(_ == "")` and not also for null values. I added "may be empty" for that test. 
(it should not change anything in real rudder, because we should never have a null value, and it is likely a scare from the past. Still, the test was false, the code was false, and the two problem were compensating each others)

Fixes #25429: When a mandatory variable has not value but a default one is configured, use it

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/domain/VariableAndSection.scala

https://issues.rudder.io/issues/25428
Replace the check's target from current `values` to new updated `seq` one

Fixes #25428: Update directive variable check constraints on existing values

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/users/User.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/UserSessionInvalidationFilter.scala

https://issues.rudder.io/issues/25407
We previously had a cache of user statuses only, that we processed upon every request (in the `doFilter`) because the status value is sufficient to guess if the user session should be invalidated.
But now, the state management is more complex, since we need to handle a *change* of password and rights, instead of their value alone. The diff would needs to be computed and processed before storing into the cache, hence another cache model with `ValidUser` and `InvalidUser` within the cache, the invalidity being declined into 3 different reasons : invalid status, password change and rights change.
Also, since multiple changes could occur at once, before the session of the user in question is checked, we need to process changes and guarantee to always keep …

Fixes #25407: 

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/users/UserRepository.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderProviderManagerUtil.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/UserSessionInvalidationFilter.scala

https://issues.rudder.io/issues/25469
The users that log in into rudder may come from the users file or from external providers (in which case their passwords are roles are not known until login in Rudder).
We need to update the users cache with all known users from the database, by getting all users with their status, in the existing file reload callback.
Also, for newly provisioned users, the cache will need to be updated with the latest user definition, independently from the file reload callback : it needs to be done at the end of the _authenticate_ mechanism

Fixes #25469: Users from external providers manage to log in but their session is invalidated instantly 

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/CleanupUsers.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/ApplicationLogger.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/users/UserRepository.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/users/UserRepositoryTest.scala
webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/25479
* Add an appropriate log with the `application.authentication` name and use it in the `CleanupUsers` file
* Improve logs globally : add some missing logs (for disable/purged) and use `zio.Duration#render` to display the date
* Only apply deletion of inactive only on disabled users
As for the properties file :
* Allow to parse "never" as `zio.Duration.Infinity`, when used in the config the existing logic of the code is still valid (eventually the code is disabling/deletion is never run)
* Improve the comments and update default to `90 days` for `disableAfterLastLogin`

Fixes #25479: Users cleanup configuration is too strict on disabled users

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/FileManager/Util.elm

https://issues.rudder.io/issues/25488
The error message was not in the right place in https://github.com/Normation/rudder/pull/5828

Fixes #25488: Resource upload with file too big cause network error in firefox

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/ApplicationLogger.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/users/UserRepository.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/Authorizations.scala
webapp/sources/rudder/rudder-web/src/main/resources/logback.xml
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderProviderManager.java
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderUserDetailsFile.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/CommonLayout.scala

https://issues.rudder.io/issues/25478
Just removing `ApplicationLoggerPure.Authz` and `ApplicationLoggerPure.User` definitions, and replacing all usages by `ApplicationLoggerPure.Auth` to make it compile and use the `application.authentication` logger

Fixes #25478: Normalize authentication logs

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/CleanupUsers.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/users/UserRepository.scala

https://issues.rudder.io/issues/25490
* `zio.Duration#render` was forgotten in https://github.com/Normation/rudder/pull/5880
* log conditionally when count is > 0 or list is non empty

Fixes #25490: User cleanup actions are logged every time even there is no change 

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/hooks/RunHooks.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/hooks/RunNuCommand.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/EditorTechniqueReader.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueCompiler.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/healthcheck/HealthcheckService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/WriteNodeCertificatesPem.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/system/DebugInfoService.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/hooks/RunNuCommandTest.scala

https://issues.rudder.io/issues/25498
So, it seems that at some point (perhaps on 2.x, but I didn't find info), `nuProcess` changed the semantic of the current working directory. 
At least, now we can set it, and we don't, and for hooks it seems to be better to set it to the hook directory. 
I also changed for the `debug` script info that is supposed to start a lot of thing from its directory, but I'm not sure it's really used. 
I didn't changed for other command calls like `rudderc`. 
With the change, a hook with PWD change from: 
```
[2024-09-19T15:45:35+02:00] exec hook at /home/fanf/java/workspaces/rudder-project/rudder/webapp/sources
```
To:
```
exec hook at /home/fanf/java/workspaces/rudder-project/rudder/webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-inventory-rec …
```

Fixes #25498: Hooks are not executed anymore from their directory

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder.js
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/EventListDisplayer.scala

https://issues.rudder.io/issues/25499
Make the date picker initializers parameterizable with X hours before the end date (keep 2h from now by default which is used in technical logs). Then specify 48h for the event logs date pickers

Fixes #25499: Event log table default period of two hours is too short

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/LogDisplayer.scala

https://issues.rudder.io/issues/24332
Data refresh needs to happen after the table and form are initialized (same as in [eventlogs](https://github.com/Normation/rudder/blob/be26d0144a78dd6d86f80b7bb57eec8d88d6a4c3/webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/EventListDisplayer.scala#L135))

Fixes #24332: Technical logs are not loaded when visiting the tab - rudder 8.1

---

webapp/sources/api-doc/components/schemas/node-full.yml
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/NodeDetailLevel.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/RestDataSerializer.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_nodes.yml

https://issues.rudder.io/issues/25476
Add the `acceptanceDate` (when the node was accepted in Rudder) in the default pool of node details properties. 
Add `scheduleOverride` in the `managementTechnologyDetails` with details of the overridden values. 
It's in details, and only for the overriding case, because it was simpler technically to do so (and upmerge will be complicated), it doesn't seem to be asked a lot, and it will be possible to later add the run schedule in a more general section if we want (and in 8.2 and up, it will be easier to do so). 
I used `nodeFact` since we have it in 8.2, but in any cases, the upmerge will be interesting.

Fixes #25476: API don't include acceptedSince information

---

webapp/sources/pom.xml

https://issues.rudder.io/issues/25306
The main change are: 
- no more support for java 7 (ok)
- the PR we wanted and tested is merged \o/ https://github.com/brettwooldridge/NuProcess/pull/158
Tests are green, violet are rose, and nuProcess flows.

Fixes #25306: NuProcessHandler.onStart NPE log message

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/api/DataStructures.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/api/ApiTokenTest.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala

https://issues.rudder.io/issues/25555
The problem was that the log message used the raw token and not the typed `ApiToken` (which has a custom `toString`). But it is useful to be able to identify an unknown token, and we can afford to lose a bit of randomness.

Fixes #25555: 

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DataStructures.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PrepareTemplateVariables.scala

https://issues.rudder.io/issues/25579
So, our management of system variable is not very good. We need to idenfy the one that are late bound and allow only these one to be void, but that's a big change. So for now, we are just relaxing the check on system var. It's ok, we never have a failure because of that for system var (which would be a bug) if we don't add/remove system var or change their generation. We will need to correct it in next patch, though.

Fixes #25579: System variable can be empty early on the generation process

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/StatusReports.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ExecutionBatchTest.scala

https://issues.rudder.io/issues/25513
It was not using real percentage of direct sub-components but of all the nested components for blocks :sweat_smile:...
The final result :

Fixes #25513: worst report by percentage seems to be non fonctionnal

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ComplianceApi.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/Node.scala

https://issues.rudder.io/issues/25508
So, the problem was the hardoced "policyTypeName == user" in the middle of the second algo. I replaced the boolean "onlySystem" by the policyTypeName, up to the first caller, and use it in place of the hardcoded value.
I'm not sure why we do such complicated things for getting compliance for the node (in the case of only one node), since we do have its `NodeReportStatus` with all the rules under it. But this is beyond the scope of that change.

Fixes #25508: No system status in 8.2

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/AsyncDeploymentActor.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/CheckPolicyTemplateLibrary.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/StatusLogger.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueCompilationCache.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueCompiler.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitArchivers.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestEditorTechniqueWriter.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestTechniqueCompilationCache.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/TechniqueApi.scala
webapp/sources/rudder/rudder-web/src/main/resources/logback.xml
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/action/CheckTechniqueCompilationStatus.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/migration/MigrateJsonTechniquesToYaml.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/comet/AsyncDeployment.scala
webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/migration/TestMigrateJsonTechniquesToYaml.scala

https://issues.rudder.io/issues/25527
* Create a `TechniqueCompilationStatusService` that **reloads** the global compilation status : 
* it is done every 5 minutes by default (`rudder.batch.techniqueLibrary.updateInterval` property)
* it is reloaded at startup with a new bootstrap check
* it is updated on individual techniques after every update of a techniques from a REST API call
* We call the lift actor that is responsible for updating the UI directly in the method that uploads the status that is computed from a cache. The architecture is a bit weird, but it prevents having to manually call the actor at every place which is also weird (call an UI actor in a REST API method ?). Later we would be exposing the status information in a dedicated endpoint so that we no longer need a stateful …

Fixes #25527: List techniques with compilation failure in bar for generation status

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/GroupsApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/25332
Awaiting for the resolution of properties in the cache after a group update.
It is no big deal : this will benefit for the Rudder UI which queries the inherited properties, that are already resolved in the cache after the `updateAll()`

Fixes #25332: When changing node properties the old table is sometimes still displayed

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/domain/VariableAndSectionSpec.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/StatusReports.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/yaml/YamlTechnique.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ExecutionBatchTest.scala
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/JsonEncoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewBlock.elm

https://issues.rudder.io/issues/25604
Based on https://github.com/Normation/rudder/pull/5913 and expects changes from https://github.com/Normation/rudder/pull/5914
This is a change to have a better name by considering existing semantics, so we need to change the name of the type in our model.
Also :
* Change the serialized value :warning: existing techniques will need to be replaced by changing yml with `sed -ie "s/worst-case-percent/focus-worst/"` technique.yml` then reloading the technique
* Update Elm to support the new value, add a new text with the better description
* Update the ASCII doc
Resulting UI :

Fixes #25604: Reporting type should be focus-worst instead of worst-case-percent

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/JsonResponseObjects.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/UpdateDynamicGroups.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/properties/Properties.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/properties/MergeNodeProperties.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/properties/NodePropertiesService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/properties/PropertiesRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/NodeGroupRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/properties/PropertiesRepositoryTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/nodes/TestMergeGroupProperties.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestBuildNodeConfiguration.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/GroupsApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_groups.yml
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala

https://issues.rudder.io/issues/25592
**Domain :**
* Change the data that is stored in the cache i.e. the resolved node properties (for both node and group properties), it may now contain errors, the model is oriented towards keeping success values despite errors, a model around and based on `Ior` from cats is used for the combinators as there does not seem to be a convenient ZIO equivalent. The ADT in the model is still the mainly used one : `ResolvedNodePropertyHierarchy`
* Errors have previously been into the "Left" channel of `PureResult[A] = Either[RudderError, A]` for all errors that could happen on groups, but now we need to know if the error is specific to a property of not, if so we need to accumulate errors in the left channel with `Ior`, so we bring it in with a new …

Fixes #25592: Add node property errors in inherited properties API

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/policies/RuleTarget.scala

https://issues.rudder.io/issues/25635
`++` is specialized for Chunk, `concat` is on Iterable

Fixes #25635: Chunk appending when resolving node ids from union target can be optimized

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueCompilationCache.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestTechniqueCompilationCache.scala

https://issues.rudder.io/issues/25637
It's weird that it fails sometimes even within ZIO fibers, the `!` method in the lift mock actor has a synchronized lock on the mutable list of messages it receives...
Our common solution for these synchronization issues in tests is `eventually` 
BUT here it does seem to take much time, so using a lock is the fastest solution
**Edit : ** the test above did some change in the state of the cache so we need to take these into account, and make tests reproducible by making them "sequential"

Fixes #25637: Sometimes tests with lift actor fails

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/ApiCalls.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/Init.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/View.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/ViewUtils.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Nodeproperties.elm

https://issues.rudder.io/issues/25610
PR based on #5910 API changes   
Just parse 
* the new `errorMessage` field at root of inherited properties API and display it as alert banner
* the new `errorMessage` field for each inherited property and display a warning for the corresponding property

Fixes #25610: Display properties errors in nodes and groups page

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/AsyncDeploymentActor.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/NodePropertiesSyncService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/UpdateDynamicGroups.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/comet/AsyncDeployment.scala

https://issues.rudder.io/issues/25528
This is very similar to the part in #5905 where we use a separate service to sync the newly updated properties with the UI and add the error to the status : 
**AND**

Fixes #25528: List node with properties inheritance error in status bar for generation

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/queries/NodeQueryCriteriaData.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/queries/CmdbQueryTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/queries/NodeQueryCriteriaDataTest.scala

https://issues.rudder.io/issues/3615
Replacing previous PR: https://github.com/Normation/rudder/pull/5929
Now that we have access to CoreNodeFact, having IP matching on CIDR is easy. But we can only do it for IP in "node summary", not in the "Network Interface" part, which is a bit sad.

Fixes #3615: IP search field with slash notation

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/StatusReports.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ComputeNodeStatusReportService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/NodeStatusReportRepository.scala

https://issues.rudder.io/issues/25650
In persistance, we need to cover all case of "expiring by themself" kind: we were missing `Pending`. So if a pending reached the database, then we were always updating it, always pushing ahead its expiration time. 
Other changes are just additionnal debug info, because I still wasn't able to find quickly what was done.

Fixes #25650: Node in with no reports, pending and keep compliance lead to computation loop

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/JsonResponseObjects.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/StatusReports.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder-datatable.js

https://issues.rudder.io/issues/25649
Add the `runAnalysisKind` field in our node details table API along with the compliance, also remove a duplicate unused method and use accessors for system and user compliance
So :

Fixes #25649: Node with kept compliance should have the clock icon in node list

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/JsonResponseObjects.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/GroupsApi.scala

https://issues.rudder.io/issues/25530
We needed to get the node properties for a group, in order to get errors that applied in them (the type of the properties, to make a warning if it is not the same) 
Now, when the list of nodes is empty for a group, and we apply the same check (including only parent groups and global properties then), so we need to factor it out

Fixes #25530: Group properties wrongly appear empty when group has no member nodes

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/comet/AsyncDeployment.scala

https://issues.rudder.io/issues/25670
Because the date can take too much space the date is moved to the "help" section when on the same day.
The duration is still not refreshed (that would require some JS code)

Fixes #25670: "Started since" time in status zone is not correct

---

policies/module-types/system-updates/src/package_manager/zypper.rs

https://issues.rudder.io/issues/25693

Fixes #25693: Software update campaign does not work on SLES 15

---

api-doc/build.py
api-doc/redocly.yml
webapp/sources/api-doc/openapi.src.yml
webapp/sources/api-doc/paths/nodes/pending-all.yml
webapp/sources/api-doc/paths/nodes/pending-update.yml

https://issues.rudder.io/issues/25709
The linting of the openapi was misplaced, it should be done on split YAML files because loading them into a single `main` replaces duplicate keys silently (it is the behavior of the yaml loader from the Python library).
Also the `relay` could not build unless the [no-server-example-com](https://redocly.com/docs/cli/rules/no-server-example-com#no-server-example.com) rule is set to 'warn', we should at some point use another URL than _localhost_ for our examples.

Fixes #25709: OpenAPI documentation is invalid with duplicate /nodes/pending endpoints

---

webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/MachineInventory.scala
webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/FusionInventoryParser.scala
webapp/sources/ldap-inventory/inventory-fusion/src/test/scala/com/normation/inventory/provisioning/fusion/TestReportParsing.scala
webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/InventoryMapper.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/NodeDetailLevel.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/queries/NodeQueryCriteriaData.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala

https://issues.rudder.io/issues/25589
I simply add a `Manufacturer` and `Serial number` field in the `BIOS` object, these fields were previously present in `HARDWARE` section of the inventory but was cleaned because it was not map to anything.
Since these values are optional, it should not break anything, I add the missing filters in criteria when creating group for the BIOS too
The main strategy was to add the missing value `Manufacturer` and `Serial number` and let the compiler do the work

Fixes #25589: Lost manufacturer & serial for BIOS  between 7.3 and 8.0

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/NewNodeManager.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/25652
There were missing logic to modify the node according to the default global setting for new node. I simply add a `unitAcceptors` that is not really a unit... That fetch the node and modify his policy mode and his state.
It's working, but it can be confusing since theses should me `unitAcceptors` and for pre accepting :grimacing: 
see @clarktsiory comments https://github.com/Normation/rudder/pull/5949#discussion_r1802652374

Fixes #25652: Default settings for new nodes are not applied on a accepted node

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/Node.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/facts/nodes/NodeFactChangeEventCallback.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/facts/nodes/NodeFactRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/EventLogRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogDetailsService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogFactory.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/eventlog/NodeEventLogFormatV6Test.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/EventLogDetailsGenerator.scala

https://issues.rudder.io/issues/25667
I'm really not sure why there was properties info, I wasn't able to reproduce. But clearly, there was a lot of little things not correct: 
- no error reported in case of error of a node update callback, 
- missing node state change,
- missing display of several diff case, 
- added a title before diff of a node change to know what the diff is about
- simplify display. 
I'm not sure if it will correct the described bug, but at least now, I can cleanly display changes on policy mode and other things.
Policy mode / node state: 
Properties still working:

Fixes #25667: switching policy mode on a node from "Enforce" to anything else produce event log about properties

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeCompliance/ViewUtils.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Nodecompliance.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/ViewTabContent.elm

https://issues.rudder.io/issues/25663
The data-attributes used to generate tooltips did not use the bootstrap 5 syntax, and a call to initTooltips was missing.

Fixes #25663: Tooltips in nodes compliance are not displayed

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/queries/NodeQueryCriteriaData.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestNodeFactQueryProcessor.scala

https://issues.rudder.io/issues/25701
I forgot to create the `MemorySize` matcher for `CoreNodeFact` when I switched to `NodeFact` in 8.1. So it was obviously broken.

Fixes #25701: Search on RAM fails in node groups

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/archives/ArchiveType.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SystemApi.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/SystemApiTest.scala
webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder.js
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/Archives.scala

https://issues.rudder.io/issues/25691
The problem is the same as #5941 : we can no longer redirect to a secure API endpoint since they need CSRF headers, so we need to execute AJAX to download the file content (the AJAX consists in saving the archive itself from the browser).
* In this PR the JS functions that do the download are put in global scope (`rudder.js`) they may be reused in more that one place in Rudder (and I checked btw that this one is the last case of redirect).
* The FS mappings for archive types (rules, directives, etc.) have been put in an attribute of an enum type, which helps avoiding the "String" API.
* Also the previous tests about this part were always testing an error because the test setup with commit ids of archive were causing a null pointer exception, I …

Fixes #25691: Full archive export does not work anymore

---

webapp/sources/rudder/rudder-core/src/main/resources/reportsSchema.sql
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/migration/CheckTableReportsExecutionTz.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/migration/DbCommonMigration.scala
webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/migration/TestMigrateTableReportsExecution.scala

https://issues.rudder.io/issues/25713

Fixes #25713: ReportsExecution doesn't have timezone on all fields

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/PurgeOldInventoryData.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/history/impl/InventoryHistoryJdbcRepository.scala

https://issues.rudder.io/issues/25830
The format has always been serialized as ISO8601 (see the Joda date serializer), the bug was in fact in : 
https://github.com/Normation/rudder/pull/5034

Fixes #25830: Bad postgresql time conversion for event log cleaning in 8.1

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/GroupsApi.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateCategoryOrGroupPopup.scala

https://issues.rudder.io/issues/25822
We need to call `propertiesService.updateAll()` to initialize the value of the properties of the group in the cache, the same way when a group properties are updated (same as in https://github.com/Normation/rudder/pull/5920/files).
We need to do this both in the UI and in the API to resolve the group properties hierarchy from global properties once it is created

Fixes #25822: Properties on newly created group are not initialized until policy generation or other group properties update

---

webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-main.scss

https://issues.rudder.io/issues/25762
This bug only appears on Firefox, so I had to add a simple css rule to prevent it.
> Note: In contrast to [word-break](https://developer.mozilla.org/en-US/docs/Web/CSS/word-break), overflow-wrap will only create a break if an entire word cannot be placed on its own line without overflowing.
https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap

Fixes #25762: Sometimes too long properties values move out actions buttons from window

---

relay/sources/rudder-package/tools/rudder-pkg.conf

https://issues.rudder.io/issues/25868

Fixes #25868: Don't configure a broken Rudder account by default

---

webapp/sources/pom.xml
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/UserSessionInvalidationFilter.scala
webapp/sources/utils/src/main/scala/com/normation/ZioCommons.scala

https://issues.rudder.io/issues/24968
New try with last version and the old strategy that all `ResultIO.attempt` are blocking.
I *looks* like it works for everything on one core (compilation, test, policy generation and update, node inventory processing...) BUT I can't log in the webUI anymore. 
The spring trace look normal until a redirect to login page. I'm not sure why ZIO version impact that (idea is something around threadlocal context, but not sure what)
UPDATE: it now works. When dealing with SpringSecurity related code, it seems that we must be careful to now yield other thread with `IOResult.attempt` because then, we loose the `SecurityContext` (which, IIRC, is stored in a ThreadLocal value). 
I didn't found other occurence of that happening, but we're likely going to need a …

Fixes #24968: Upgrade to ZIO 2.1.2

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/DataTypes.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/JsonCampaignSerializer.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/MainCampaignService.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/campaign/CampaignSchedulerTest.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/CampaignApi.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/CampaignApiTest.scala

https://issues.rudder.io/issues/25786
Add `tz: Option[ScheduleTimeZone]` which is the ID of a IANA timezone (offsets are not supported). Also when saving a campaign the tz is the current server timezone. So, `None` means for old campaigns that no timezone was saved and the server one should be used when scheduling campaigns.  
A lot of unit tests were added, mostly to cover different cases for all schedules, and see that the variants with a timezone still work.

Fixes #25786: Add timezone field in campaign schedule

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/plugins/PluginSettings.scala
webapp/sources/rudder/rudder-core/src/test/resources/plugins/rudder-pkg-default.conf
webapp/sources/rudder/rudder-core/src/test/resources/plugins/rudder-pkg-empty.conf
webapp/sources/rudder/rudder-core/src/test/resources/plugins/rudder-pkg-example.conf
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/plugins/TestPluginSettingsService.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/SetupRedirect.scala

https://issues.rudder.io/issues/25847
When settings are "defined" we should not redirect.
We are also on a hot path so we need to mark the setup as done to prevent reading the file at every webpage request

Fixes #25847: The setup initial page should not be displayed if rudder-pkg.conf has been modified

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/JsonQueryObjects.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/RestDataSerializer.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/RudderDit.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/NodeGroup.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/queries/CmdbQuery.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/properties/MergeNodeProperties.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogFactory.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlSerialisationImpl.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/NewNodeManager.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/CmdbQueryParser.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/DynGroupService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/LdapQueryProcessor.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/NodeFactQueryProcessor.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/PolicyServerManagementService.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/facts/nodes/TestCoreNodeFactInventory.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/marshalling/TestXmlUnserialisation.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/nodes/TestMergeGroupProperties.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestJsonQueryLexing.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestNodeFactQueryProcessor.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestPendingNodePolicies.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestStringQueryParser.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/EventLogDetailsGenerator.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/SearchNodeComponent.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/SearchNodes.scala

https://issues.rudder.io/issues/25894
In the same vein as #6020, #6021, #6022, etc
In this one, a part of the refactoring is about putting ADT values in the companion object of the sealed root. 
It also needs to use an intermediary for `CriterionLine` and chimney mapping from it because that case class is just too complicated for the simple encoding only we want. If one day we build a full codec, we will be able to delete `JsonCriterionLine` and the plumbing around. 
A needed to `liftjson.parse(query.toJson)` in group serialization because it awaits a `JValue`. It's not a problem, it will be removed once we have migrated group API.

Fixes #25894: Migrate CmdbQuery to zio-json

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/queries/NodeQueryCriteriaData.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestNodeFactQueryProcessor.scala
webapp/sources/utils/src/main/scala/com/normation/utils/DateFormaterService.scala

https://issues.rudder.io/issues/25934
We tried to parse a `Date` with a `DateTime` parser, which fails. The naming of method is bad and should be change (but it needs to be changed everywhere at once to avoid compilation error in plugins, likely using a deprecation stub for forward). 
Add missing unit tests to check both old and new format consistency.

Fixes #25934: Search is not able to parse new format

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/users/RudderUserDetailsFile.scala
webapp/sources/rudder/rudder-rest/src/test/resources/test-users-wrong-hash.xml
webapp/sources/rudder/rudder-rest/src/test/resources/test-users-wrong-unsafe-hashes.xml
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/migration/CheckUsersFile.scala
webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/migration/TestCheckUsersFile.scala

https://issues.rudder.io/issues/25935
We now have to consider the errored/success value of the `unsafe-hashes` attribute in the boot check, so we need to refactor reading the attribute into a method, similarly to `hash`.
Then we read the attribute and when there is an error reading either of them, we `enforceModern` i.e. we use bcrypt and disallow unsafe hashes.
N.B. : this change only affects the boot check, later when we will want to apply the enforcing at every file reload, we should be backporting that in 8.1

Fixes #25935: 

---

webapp/sources/rudder/rudder-rest/src/test/resources/api/api_nodes.yml
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TestInheritedProperties.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TestRestFromFileDef.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TraitTestApiFromYamlFiles.scala

https://issues.rudder.io/issues/25941
The current "test all files" REST test is not very user friendly because we only have one `restTestSetUp` for all tests. 
It's good for speed, because it means we only do one time the set up, which is quite long. 
But it also means that each file is bounded to others, and the test are not orthogonal at all. 
This means a dev has to think not only to the previous tests in the file (that's OK), but also to all other tests (which means each new test has an additionnal cost, when we want a constant, or reduced cost for adding tests). 
I can't do the change easily since it needs to change the API, and so it implies change in ALL plugins - so it's an other PR. But I think we will need to do it, even if it means one rest set-up by file. 
In the meantime, the …

Fixes #25941: Spurious failing test for inherited properties rest API

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ArchiveApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/CampaignApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ComplianceApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/DirectiveApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/GroupsApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/HookApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/InfoApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/InventoryApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/LiftApiDispatcher.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ParametersApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/PluginApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/RuleApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ScoreApiImpl.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SettingsApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SystemApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/TechniqueApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/UserManagementApi.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/25945
Based on #6023 to takes benefits from already migration Lift stuff. 
Along with the deletion of old api version, I did a clean-up of our existing APIs on 3 points: 
- 1/ normalize pattern matching of API implementation, 
- 2/ remove pre-v14 API alternative (seriously)
- 3/ clean-up all unused services or class parameters I could find. 
We have a rule of pattern-matching the API declared endpoints so that we're sure no implementation is missing, since we can't enforce that point by types (at least I never found a reasonnable way to do it). We had quite a few ways of doing it, I normalized with the shortest form, which also seems the clearest for that reason (and of course keep the exhautivness check): 
```
class UserManagementApiImpl(...) extends …
```

Fixes #25945: Add and Remove/deprecate API for Rudder 8.3

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/RudderDatasourceProvider.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/db/DBCommon.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/db/GenerateCompliance.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/scala-ldap/src/main/scala/com/normation/ldap/sdk/LDAPConnectionProvider.scala

https://issues.rudder.io/issues/25892
This PR replace #6045. It adds some more change in the LDAP pool ergonomics: 
- the main change is still `LDAP_CREATE_IF_NECESSARY` set to `false` which means that the max pool size is really the max pool size, and that yes we want a pool to reuse existing connections, seriously
- the minimum for pool size can be lower than 10. It could likely be even lower than 7, but it seems to work well, even in small servers, and up to big one (10k nodes). 
- add `LDAP_MINIMUM_AVAILABLE_CONNECTION_GOAL` for the number of min alive connexion. Set to 2, which should be OK everywhere. 
- `LDAP_MAX_WAIT_TIME` is the time code will wait for a connection from the pool. It was to 0, which is strange for a pool. Use `30 seconds` like in most pool. 
- deconnect and …

Fixes #25892: Error when accepting 2 or more nodes

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/EventLogDetailsGenerator.scala

https://issues.rudder.io/issues/25974
The whole thing feels broken (the id should be in the event somewhere mandatory for ex). 
But at least, we need to check if the `name` is not empty and have a fallback.

Fixes #25974: Link to node is missing for modified nodes

---

relay/sources/rudder-pkg/README.md

https://issues.rudder.io/issues/25917

Fixes #25917: Add a dedicated Readme for rudder-package

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Groups/View.elm

https://issues.rudder.io/issues/25815
They were just not tagged as bootstrap tooltips...

Fixes #25815: tooltip broken for groups description

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/facts/nodes/NodeFactStorage.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/tenants/TenantService.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/facts/nodes/TestCoreNodeFactInventory.scala

https://issues.rudder.io/issues/25978
We were not correctly mapping back attributes from NodeInventory to Node in the case where we were retrieving both node and inventory info from storage. 
Rebased on top of #6063 which is around the same problems

Fixes #25978: CustomProperties (inventory properties) are not always correctly retrieved from inventory

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/EventLogAPI.scala

https://issues.rudder.io/issues/25705
This part of query is within a larger set of condition, it needs parenthesis, and it knows that the `eventtype` column is there. Also we don't need to consider the exact case even for the user query (EventType is stored as PascalCase). 
The drawback of this is that the user should know the EventType. And we have no way of statically checking for known event types before applying the filter.

Fixes #25705: search on event log must also search on event type

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/JsonQueryObjects.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/config/UserPropertyService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/json/JsonExctractorUtils.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/nodes/TestMergeGroupProperties.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestUtils.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RudderJsonRequest.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/DirectiveApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/GroupsApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/RuleApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SettingsApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/TechniqueApi.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/TechniqueEditForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateCategoryOrGroupPopup.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateCloneDirectivePopup.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateCloneGroupPopup.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateOrUpdateGlobalParameterPopup.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateRulePopup.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/GiveReasonPopup.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/ModificationValidationPopup.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/RuleModificationValidationPopup.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/TechniqueLibraryManagement.scala

https://issues.rudder.io/issues/25960
After #6042 a lot of lift-json methods in rest extractor are left unused : cleanup most of them, and mark the remaining one with a comment to know which API/serializer depends on it.
Along the way I replaced the old `extractPrettify` and `extractReason` in lift-json with the existing equivalent in zio-json (but it needed to move `UserPropertyService` in core), and migrate away from trivial usage == single line of lift-json, to remove as much methods as possible.
After this, remaining migrations that depend on the extractor utils/service are well-known : 
* Tags.scala
* Groups API
* Eventlogs API
* ApiAccounts API
* Technique API
* Compliance API
* Settings API

Fixes #25960: Remove unused and duplicate rest extractor lift-json methods

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/25842
General ideas and hypothesis: 
- we want to reduce the number of `runNow` (each one create more risk that there is a chain of `.runNow/.attemp/.runNow` with the potential for deadlock)
- it's easier to remember to init a service near where it is declared
- we want to keep all service init at the same place if possible
I added a (mutable) buffer in our `def init` method, into which we can add ZIO effect related to services init, and `runNow` it (in parallel, effect result discarded) at the end of the method. 
I used the same construct for post-plugin init.

Fixes #25842: scoreService and scoreServiceManager are not initialized where they should

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/JsonQueryObjects.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/JsonResponseObjects.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/json/JsonExctractorUtils.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestUtils.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/RestData.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/GroupsApi.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_groups.yml
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/25980
Migrating remaining lift-json endpoints in the GroupsApi file : endpoints for rule categories.
It ends up being very similar to the already migrated Rules categories API.
I added some tests for validation error (on the `name`) along the way, I removed what could be removed from the evil  `RestExtractorService`...

Fixes #25980: Migrate Group category API endpoints to zio-json

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/ApplicationLogger.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/json/JsonExctractorUtils.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/ApiAuthorization.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RoleApiMapping.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/EventLog.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/EventLogAPI.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_eventlogs.yml
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TestRestFromFileDef.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/26017
This is the migration of an old internal API : the one for event logs with 3 endpoints.
API YAML tests were added for all endpoints, and the only complexity apart from adding tests is to ensure that the json model are translated correctly in existing doobie queries.
The API endpoints schema were migrated as is, even though they may be changed (`GET /eventlog/id/details/rollback?action=before` is a really weird one, hopefully it's only for internal use in the JS ajax client)

Fixes #26017: Migrate old internal EventLog APIs to zio-json

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/ViewUtils.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Nodeproperties.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Nodes/ApiCalls.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Nodes/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Nodes/Init.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Nodes/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Nodes/JsonEncoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Nodes/View.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Nodes/ViewUtils.elm
webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder.js
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-main.scss

https://issues.rudder.io/issues/25824
Several changes have been made:
- First, this bug has been fixed: tooltips are now reinitialized after the table has been sorted.
- Property tooltips can only be opened by clicking on their label (the mouse cursor is different from other labels when hovering these labels). This means we can scroll freely through their contents.
To close the tooltip, simply click outside (a js event has been added to the <body> for this, as Bootstrap doesn't offer this option by default).
- Tooltips width now adapts to content, and their maximum width has been increased by 100px to make large content easier to read
- A line break is forced when the width of a < pre > in a tooltip exceeds its container
- I've added some missing css classes that were breaking the display …

Fixes #25824: Properties tab : Non-rearrangement of the pop-ups

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/SystemVariableService.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/policyServerManagement.html

https://issues.rudder.io/issues/25982
Only hide the menu part, plus ensure that the system variable always get "no" - but keep the config service, API, etc logic so that it's easy to reinstanciate in 8.3. 
It looks like the pop-up logic was removed and not replaced in bb01e23b8eb48962e37bef93894fc2517b08dcd4 
The pop-up code still exists, it can be clean-up in Rudder 8.3 along with the script etc.

Fixes #25982: Disable metrics pop-up and form

---

webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/PreInventoryParserCheckConsistency.scala
webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/PreInventoryParserCheckInventoryAge.scala
webapp/sources/ldap-inventory/inventory-fusion/src/test/scala/com/normation/inventory/provisioning/fusion/TestPreParsingDate.scala
webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/25996
Nothing special. There unit tests for each bits, and the resulting error log is below. 
The biggest risk is to have other format for date, but it seems that at least in my sample, even windows, the date time format is consistent (and it's the attribute used for inventory date in Rudder node details, so it should really be ok).

Fixes #25996: Refuse inventory too far from "now"

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/JsonQueryObjects.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/JsonResponseObjects.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/Node.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/facts/nodes/NodeFact.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogDetailsService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogFactory.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/eventlog/NodeEventLogFormatV6Test.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/EventLogDetailsGenerator.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala

https://issues.rudder.io/issues/25984
Add a documentation field in node that can be set by API. 
This issue manage the backend, which is: 
- rename `description` to `documentation` in `NodeFact` because we want to support markdown and long format for that field, 
- extends API for updating node info to support that attribute, 
- manage change event for that field
- add a simple place in node details to display that field in markdown. That part will be need to be rework to be replaced by an editable part in an other issue.

Fixes #25984: Add description/doc field to node settable by API

---

relay/sources/rudder-package/src/versions.rs

https://issues.rudder.io/issues/25156

Fixes #25156: rudder-package fails to parse old plugin version numbers, breaking the upgrade

---

webapp/sources/pom.xml
webapp/sources/rudder/rudder-web/src/main/resources/logback.xml

https://issues.rudder.io/issues/26039
Main changes: 
- now, webapp logs go to `/var/log/rudder/webapp/webapp.log`
- add `janino` dependency which is needed for logback `IF` processing, 
- use existing `run.mode` JVM property to decide if logs should go to file (when value is `production`) or to console (other cases),
- now, API logs are under `/var/log/rudder/webapp/api` in place of `/var/log/rudder/api`
- `/var/log/rudder/core/rudder-webapp.log` is deleted: it was a strange, partial duplicate of webapp log.

Fixes #26039: Have a stable webapp log file

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/SharedFilesAPI.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/SharedFilesApiTest.scala
webapp/sources/utils/src/main/scala/com/normation/ZioCommons.scala
webapp/sources/utils/src/main/scala/com/normation/utils/FileUtils.scala
webapp/sources/utils/src/test/scala/com/normation/utils/FileUtilsTest.scala

https://issues.rudder.io/issues/26000
Make a `sanitizePath` util method in a new file utils namespace object. In the long term we may want to add other errors related to file handling (permissions,size), and also other security errors.
So we should have base types, and the returned error should be part of the return type.

Fixes #26000: 

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/JsonQueryObjects.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_groups.yml

https://issues.rudder.io/issues/26064
This is breaking but the previous case was actually not what was in [the documentation](https://docs.rudder.io/api/v/20/#tag/Groups/operation/createGroup) : the previous `returnType` needed to be the default zio-json sealed trait payload with the type discriminator as key : `"returnType":{"NodeAndRootServerReturnType":""}`.

Fixes #26064: Group query select attribute has different name in create and update payload

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/appconfig/RudderWebProperty.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/appconfig/ConfigService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RoleApiMapping.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SettingsApi.scala
webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala

https://issues.rudder.io/issues/25669
Adding a `rudder.auth.{provider}.disableRest` boolean option for each known provider passed to the `rudder.auth.provider` list : just read the configuration for the provider into our case class for provider properties, and keep compatibility with previous behavior by using the `false` value (meaning : DO NOT disable REST authentication for this provider)

Fixes #25669: 

---

webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala

https://issues.rudder.io/issues/26071
For OIDC, the default value is not the global one : the "global values map" should instead be a mapping of default values.
And instead of concatenating the global map with the user-defined properties, we should just use our mapping of default values now.

Fixes #26071: Default configuration for user API tokens should be disabled for OIDC and OAuth2 

---

webapp/sources/rudder/rudder-rest/src/test/resources/api/api_groups.yml
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TestRestFromFileDef.scala

https://issues.rudder.io/issues/26078
Some group updates from https://github.com/Normation/rudder/pull/6083 have impact on master branch

Fixes #26078: Fix API yaml tests on groups and remove restriction to event log

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/DeleteEditorTechnique.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueCompilationCache.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/TechniqueReloadingCallbacks.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestTechniqueCompilationCache.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SystemApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/TechniqueApi.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/26023
The cache update had the semantics of : 
> for each result, add the current result in the cache of error, or remove if it is a success
But this leaves stale results in the cache, what we need is : 
> reset the cache to the error results
We also need to include the status update in the system reload actions, and update all techniques after a public API reload of techniques.

Fixes #26023: Technique compilation errors doesn't seems to be reloaded when the technique is deleted

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueCompilationCache.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestTechniqueCompilationCache.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/comet/AsyncDeployment.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/TechniqueEditForm.scala
webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/migration/TestMigrateJsonTechniquesToYaml.scala

https://issues.rudder.io/issues/26022
When the actor receives the message, we want to ignore disabled techniques, and only process the enabled one for display in the Lift frontend actor.
This adds the `status` field to the data in the cache, so that the frontend actor can ignore disabled one. This also means we have to "sync" the `status`, especially upon changing the status in the UI. The status is still looked up every time we "sync all techniques", so the API is also changed a bit to add the new `TechniqueActiveStatus` data type.

Fixes #26022: Status should not be on error when there is technique compilator error on disable techniques

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlUnserialisationImpl.scala

https://issues.rudder.io/issues/26098
When we add field, we need to give them a default value. 
Since we don't read system library that way, it seems OK to always assume that we have an user technique.

Fixes #26098: error when importing  full archives

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDiffMapper.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/CmdbQueryParser.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/ldap/GlobalParamMigration61Test.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/marshalling/TestXmlUnserialisation.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestNodeFactQueryProcessor.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_groups.yml
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/SearchNodeComponent.scala

https://issues.rudder.io/issues/26075
* LDAP : any invalid stored query in the LDAP causes errors when reading them, we should not care to validate if comparator values is not empty, validation should happen during write,read **is not strict**. So we need to provide a version of parser that does not apply validations to LDAP mapper
* API : we should enforce that having value as empty string is also not valid, since this was the initial error, the parser was missing an invalid case, it should **be strict** against validating `""`
* UI : the save button is currently disabled only when there are form errors. But we need to disable the button also when the a criterion line has been added (or removed), this prevents from saving the query with an empty string : screenshot with the disabled …

Fixes #26075: Trying to save a group with empty criteria removes all entries

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ComplianceApi.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_compliance.yml
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala

https://issues.rudder.io/issues/26119
The directive compliance reports are using rules compliance reports, but currently an empty list of rule reports is just flattened further down as a rule with 0 compliance.
It should instead be deduced from the `Option`, obtained when getting directive reports

Fixes #26119: All rule show up in directive compliance

---

webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-dashboard.scss
webapp/sources/rudder/rudder-web/src/main/webapp/secure/index.html

https://issues.rudder.io/issues/26105
Before:
After:
And now all the boxes in the same line have the same height :

Fixes #26105: The statistics on the dashboard are hardly readable

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/queries/CmdbQuery.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/queries/NodeQueryCriteriaData.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/NodeFactQueryProcessor.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestNodeFactQueryProcessor.scala
webapp/sources/rudder/rudder-web/src/main/resources/ldapObjectAndAttributes.properties
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/SearchNodeComponent.scala

https://issues.rudder.io/issues/26136
Adding an "Instance ID" criterion in groups : 
This criterion needs to be handled differently from other criterion :  
* the value that needs to be searched for comes from the application, `InstanceIdService`, and not from node facts (LDAP) attributes
* when combined with other criterion, if it does not match, it should short-circuit any other LDAP criterion comparison (to avoid doing LDAP search), to do so we introduce the absorption property in the boolean algebra 
* and finally in the UI, it needs to be filled by default (i.e. when the value is still empty) with the current instance ID

Fixes #26136: Add instance ID in group search criteria

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/metrics/DataTypes.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/metrics/HistorizeNodeCountService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/metrics/SystemInfoService.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/metrics/NodeCountHistorizationTest.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/About.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SystemApi.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_system.yml
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/SystemApiTest.scala
webapp/sources/rudder/rudder-web/src/main/elm/sources/About.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/About/ApiCalls.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/About/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/About/Init.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/About/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/About/JsonEncoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/About/View.elm
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/metrics/SystemInfoServiceImpl.scala
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-about.scss
webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/about.html
webapp/sources/utils/src/main/scala/com/normation/utils/DateFormaterService.scala

https://issues.rudder.io/issues/26059
This PR superseeds https://github.com/Normation/rudder/pull/6102
It adds a `SystemInfoService` and two data structures: 
- `PrivateSystemInfo` contains data that can lead to server identification (like `InstanceId`) and should never be pushed in public/sharable metrics
- `PublicSystemInfo` has only sharable data like node counts, jvm info, etc. 
These data are mapped to a JSON equivalent data structure used for the `About` page: `SystemInfoJson`. 
Since we already have a `system/info` page that gives some info (just rudder version and build time for now), I chose to extends it. For backward compatibility, the old data is kept for API version < 20. 
Not finished, remains:

Fixes #26059: Create a new ‘About’ page for easy access to technical information

---

webapp/sources/pom.xml
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/db/Doobie.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/policies/Tags.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/ComplianceLevel.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/StatusReports.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/json/JsonExctractorUtils.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDiffMapper.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/score/ComplianceScore.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchBackendImpl.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/policies/TagsTest.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleGrid.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/TagsEditForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/AsyncComplianceService.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ComplianceData.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/HomePage.scala
webapp/sources/rudder/rudder-web/src/test/scala/com/normation/rudder/web/services/ComplianceLineTest.scala

https://issues.rudder.io/issues/26046
Main change: 
- upgrade to chimney 1.6.0 so that we can avoid `...withFieldComputed(_.a, _.aa.transformInto[AA])` and just use `.withFieldRenamed(_.a, _.aa)` given a transformer `A` to `AA` in scope
- `Tags` needed to be migrated. Only encode is needed at that point, which was created with an intermediate `JsonTag` that is not exposed so that we can keep `Tags` in Json objects in place of `JValue`. 
- where the Json Lift objects were used directly, I mapped to the corresponding `zio.json.ast` objects
- I introduced a `OptPosNum` type for compliance and compliance percent serialization. It's an `Option[Numeric]` (so that it works with int and float, but some quirks because js/java/scala) and so can be eliminated in the json when not present. 
- the …

Fixes #26046: Migrate compliance status from lift-json to zio-json

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/plugins/PluginSettings.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/ApiDatastructures.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RudderJsonResponse.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/PluginInternalApi.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_plugins.yml
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/plugins/PluginStatus.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/plugins/RudderPlugin.scala
webapp/sources/rudder/rudder-web/src/test/scala/com/normation/plugins/PluginSettingTest.scala

https://issues.rudder.io/issues/26162
* Add API tests to previous PR
* Add API endpoints, there are endpoints to install, remove and change status
* Add tests for errors computation 
* Along the way, added the error when a plugin is required as mentioned in https://github.com/Normation/rudder/pull/6114#discussion_r1909262123

Fixes #26162: Install remove and change status of plugins from API

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/plugins/PluginSettings.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/plugins/TestRudderPackageService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/ApiDatastructures.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RudderJsonResponse.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/PluginInternalApi.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_plugins.yml
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/plugins/PluginStatus.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/plugins/RudderPlugin.scala
webapp/sources/rudder/rudder-web/src/test/scala/com/normation/plugins/PluginSettingTest.scala

https://issues.rudder.io/issues/26169
* Adds license information to the plugins API (see yml tests), by refactoring the existing structures 
* Adds credential management on the 'plugins list' endpoint : we need to handle the command-line error message, up to our API response, by adding utility methods to convert an Either with an error into a lift response.

Fixes #26169: License information and credentials management in plugins API

---

webapp/sources/pom.xml
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RoleApiMapping.scala
webapp/sources/rudder/rudder-web/src/main/resources/applicationContext-security.xml
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderProviderManager.java

https://issues.rudder.io/issues/26167
The only meaningful changes are: 
- adde a `name` to the http security filter for API, so that it can be referenced in the plugin, 
- make the current Rudder API filter, `RestAuthenticationFilter`, just pass the request away when the authentication is already done
Other changes are new logger/trying to make msg construction clearer. 
Look a the change with `?w=1` .

Fixes #26167: Make API authentication pluggable

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/JsonEncoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/MethodElemUtils.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewBlock.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewMethod.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewMethodsList.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTechnique.elm
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-technique-editor.scss

https://issues.rudder.io/issues/26153
:warning: work in progress

Fixes #26153: Add a user interface for managing method/block loops in the techniques editor

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DependencyAndDeletionService.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala
webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/directiveManagement.html

https://issues.rudder.io/issues/26161
Add a button to enable/disable technique from the directive tree screen. A validation pop-up is shown with the impacted rules before actually doing the action. 
Nothing hard, just tedious old lift. 
[Screencast_20250116_213950.webm](https://github.com/user-attachments/assets/9360fd9e-be60-43a9-ad77-4f2a10c5cd4f)

Fixes #26161: Allow to enable/disable technique from the directive tree scree

---

policies/module-types/system-updates/src/package_manager.rs
policies/module-types/system-updates/src/package_manager/yum.rs
policies/module-types/system-updates/src/package_manager/zypper.rs

https://issues.rudder.io/issues/26194
No idea about the root cause, hard to reproduce. Let's try this.

Fixes #26194: Patch management campaigns on CentOS 7 end in error

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/plugins/PluginSettings.scala
webapp/sources/rudder/rudder-web/src/main/elm/elm.json
webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/ApiCalls.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/Init.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/View.elm
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-plugins.scss

https://issues.rudder.io/issues/26207
Adding modals to confirm actions on plugins :
Fixing also some other problems :
* in case of missing license, the plugin is not supposed to be selected 
* disable and enable action were not working due to the command being "enabled/disabled" instead of "enable/disable"
* sorting the plugins by their status, then by alphabetical order, using the [elm-ordering](https://package.elm-lang.org/packages/matthewsj/elm-ordering/latest/) lib which is very handy for that
* minor SCSS adjustments

Fixes #26207: Plugin management operations need confirmation popup and license error info

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder.js

https://issues.rudder.io/issues/25586
We now force other tooltips to close when a new tooltip opens or closes.

Fixes #25586: Persistant tooltips on rules page

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala

https://issues.rudder.io/issues/26206
As we don't display techniques based on the window hash, we can just set the hash to empty when clicked (it may leave `#` but it is not an issue, and does not seem to refresh the page, even on the load testing machine)

Fixes #26206: Directive will not be displayed when clicking on a technique then on directive in tree

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/FileManager/Action.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/FileManager/Model.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/FileManager/Update.elm

https://issues.rudder.io/issues/26159
The documentation of `File.Download.url` itself recommends to work with `File.Download.bytes` and AJAX when needing specific authorization to the server (in our case the CSRF headers), since the current one is just an `<a href="" target="_blank"/>`

Fixes #26159: Unable to download technique resources

---

policies/rudderc/src/backends/windows.rs
policies/rudderc/src/ir/value.rs
policies/rudderc/tests/cases/general/escaping/technique.ps1
policies/rudderc/tests/cases/general/ntp/technique.ps1
policies/rudderc/tests/cases/general/param_in_condition/technique.ps1
policies/rudderc/tests/cases/general/variables/technique.ps1

https://issues.rudder.io/issues/26151

Fixes #26151: UTF-8 chars are HTML escaped when used in policy variables

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/DirectiveCompliance/ViewNodesCompliance.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/DirectiveCompliance/ViewRulesCompliance.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/GroupCompliance/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/GroupCompliance/ViewUtils.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Groupcompliance.elm

https://issues.rudder.io/issues/26062
* Directives page (need to mess with css classes for the alignment of both buttons) : 
* Groups page (need to add a new Msg type) :

Fixes #26062: There is no "refresh" on the compliance in directive page and group page

---

relay/sources/rudder-package/src/lib.rs
relay/sources/rudder-package/src/main.rs
relay/sources/rudder-package/src/repository.rs

https://issues.rudder.io/issues/26244
The main can return an `ExitCode`, we only have to map it from the result of running the CLI : we intercept the repository errors and associate specific error codes depending on the HTTP error. For now the exit code are 2 and 3.

Fixes #26244: License repository errors should result in different exit codes

---

webapp/sources/api-doc/code_samples/curl/systemUpdate/report.sh
webapp/sources/api-doc/code_samples/curl/systemUpdate/summaryReport.sh
webapp/sources/api-doc/openapi.src.yml
webapp/sources/api-doc/paths/systemUpdate/report.yml
webapp/sources/api-doc/paths/systemUpdate/summaryReport.yml

https://issues.rudder.io/issues/26114
OpenAPI documentation for the two endpoints added in https://github.com/Normation/rudder-plugins-private/pull/882, they return `text/plain` content type

Fixes #26114: Add campaign API documentation for CSV reporting endpoints

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/JsonEncoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTechnique.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTechniqueList.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTechniqueTabs.elm

https://issues.rudder.io/issues/26249
Upon selection, the whole UI state of the draft is not validated (name and ID), however it should because it may have been left into an invalid state. We just need to refactor the validation of the UI state and apply it upon a new draft selection.
We no longer need to prevent the ID from starting with `_`, it is not validated on the API and is supposed to be prefixed for CFEngine.

Fixes #26249: Technique can be created with technique ID starting with a forbidden character

---

webapp/sources/pom.xml

https://issues.rudder.io/issues/26297
The relevant release notes are:
- zio: https://github.com/zio/zio/releases/tag/v2.1.14
- zio-json: [a lot](https://github.com/zio/zio-json/releases), but in particular https://github.com/zio/zio-json/releases/tag/v0.7.14 corrects a bug that was introduced in 0.7.7 and was impacting us regarding decoder for `Optional[A]`, caught in our unit tests.

Fixes #26297: Update zio and zio-json to take benefits of perf improvments

---

webapp/sources/rudder/rudder-core/src/main/resources/ldap/rudder.schema
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/api/ApiAccountRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/api/DataStructures.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/RestDataSerializer.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDiffMapper.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlSerialisationImpl.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlUnserialisationImpl.scala
webapp/sources/rudder/rudder-core/src/test/resources/ldap-data/schema/099-1-rudder.ldif
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/GroupsInternalAPI.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/RestApiAccounts.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/RulesInternalAPI.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/users/User.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/EventLogDetailsGenerator.scala
webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/ViewModals.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/ViewUtils.elm
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/endconfig/action/CreateSystemToken.scala
webapp/sources/rudder/rudder-web/src/test/resources/ldap-data/schema/099-1-rudder.ldif
webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/endconfig/action/TestCreateSystemToken.scala

https://issues.rudder.io/issues/26292
This PR allow user to choose an api account ID on creation. That allows to match third party token ID for example with an IdP providing OIDC opaque access beare token as done in https://github.com/Normation/rudder-plugins/pull/789. 
For this case, we dont' want to have a secret generated for these accounts. So if the user chose to specify an account ID, we don't generate a token secret. For that, we need to make the "secret" attribute of api account optional, which is a change in LDAP schema. This change is OK since we go from mandatory to optional. This was also the path followed in https://github.com/Normation/rudder/pull/6031. 
More cleaning and enhancement can be done in token secret mananement (signal that an account hasn't any token with a …

Fixes #26292: Allow to choose api account ID on creation

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/BootstrapChecks.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/earlyconfig/db/CheckPostgreConnection.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/earlyconfig/db/CheckTableReportsExecutionTz.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/earlyconfig/db/CheckTableScore.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/earlyconfig/db/CheckTableUsers.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/earlyconfig/db/CheckUsersFile.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/earlyconfig/db/CreateTableNodeFacts.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/earlyconfig/db/DeleteArchiveTables.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/earlyconfig/db/MigrateChangeValidationEnforceSchema.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/earlyconfig/db/MigrateEventLogEnforceSchema.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/earlyconfig/ldap/CheckLdapConnection.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/endconfig/action/CreateInstanceUuid.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/comet/AsyncDeployment.scala
webapp/sources/utils/src/main/scala/com/normation/utils/DateFormaterService.scala

https://issues.rudder.io/issues/26286
It looks like it should have been a five minutes work and well, there was several tangeant in it: 
- I wanted to add an "exec once" bootchecks for instance id, so I rewrote check in zio
- which allows to simplify the exec timing part, with `.timed`, 
- we have a "formatPeriod" method that is extremely specific (it say "less than 1s") and so I renamed it to avoid confusion with strict formatting methods
- then I saw that actually, the formatter is for Joda, not Java, and (re, re)-discovered that there is no formatter for java.time.Duration, so wrote one so that it's done and we don't have to ask ourself again, 
- then, I discovered that I'm not able to find a single way to make a "zio exec once" if the "once" part is called with several runNow. I'm …

Fixes #26286: InstanceId check must be in early bootstrap checks

---

relay/sources/relayd/src/data/report.rs

https://issues.rudder.io/issues/26290

Fixes #26290: The relayd reports parser can break on multiline fields in logs

---

webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-template.scss

https://issues.rudder.io/issues/26261

Fixes #26261: The "Save" button disappears from the group webpage if the group name is too long

---

relay/sources/rudder-package/src/repository.rs

https://issues.rudder.io/issues/26317

Fixes #26317: rudder-package should create the license folder when not already there

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/plugins/PublicPlugin.scala

https://issues.rudder.io/issues/26322
If two plugins are setting the same menu, data that were already set are replaced because we are resetting the menu with the one from the new plugin

Fixes #26322: When several plugins are using the same menu, only the last one is displayed

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/plugins/PluginSettings.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/hooks/RunNuCommand.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/EditorTechniqueReader.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/healthcheck/HealthcheckService.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/plugins/TestRudderPackageService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RudderJsonResponse.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/PluginInternalApi.scala
webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/ApiCalls.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/Init.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/View.elm
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/plugins/RudderPlugin.scala
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-plugins.scss

https://issues.rudder.io/issues/26243
Several improvements, both in the displayed error information and the logic of error display while the list of plugin is showed :  
1. on the API-side : 
- error propagation from [rudder-package](https://github.com/Normation/rudder/pull/6137), and add the response error types for yet other HTTP codes
- error message cleaning : remove color from the rudder-package output
2. on the frontend-side : 
- :bug:  `errorDetails` message was not read correctly, we should never read Bytes in Elm
- disable buttons when there is no selection
- after confirmation the server restarts (and returns 502/503 to the client) so we need a feedback :

Fixes #26243: Improve license errors handling in webapp

---

webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/FullInventoryFromLdapEntriesImpl.scala
webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/FullInventoryRepositoryImpl.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/api/ApiAccountRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/CleanupUsers.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/GitGC.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/PurgeOldInventoryData.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/JSONReportsHandler.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/MainCampaignService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/facts/nodes/NodeFactChangeEventCallback.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryFileWatcher.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryProcessor.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDirectiveRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/RemoveNodeService.scala
webapp/sources/scala-ldap/src/main/scala/com/normation/ldap/sdk/LDAPConnection.scala
webapp/sources/scala-ldap/src/main/scala/com/normation/ldap/sdk/LDAPIOResult.scala
webapp/sources/scala-ldap/src/main/scala/com/normation/ldap/sdk/LDAPTree.scala
webapp/sources/scala-ldap/src/test/scala/com/normation/ldap/sdk/LDAPTreeTest.scala

https://issues.rudder.io/issues/26328
This is the backport (rebased) in 8.1 of several scala 3 related PR that were immediately portable: 
- https://github.com/Normation/rudder/pull/6148
- https://github.com/Normation/rudder/pull/6150
- https://github.com/Normation/rudder/pull/6146
Everything cleaning compile and tests pass. 
They are superseeded by that PR and can be closed once this one is merged.

Fixes #26328: Some more changes needed for scala 3 migrations

---

webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/RudderUserDetailsTest.scala

https://issues.rudder.io/issues/26342
I tried to run the test locally but could not reproduce the error, this line only appears in the CI : `WARN  application.authentication - Role 'role-a2' reference unknown role 'plugin': 'plugin' will be ignored.`, due to the [custom role](https://github.com/Normation/rudder/blob/516eabbfcd0dc9f31b0bf4c8ae03b28d6a3fc994/webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/RudderUserDetailsTest.scala#L156) being expected to exist. 
I searched for any mutable state but did not found out a place where it could be mutated at all...
Let's just hope that making tests sequential will prevent them from failing :crossed_fingers:

Fixes #26342: Roles parsing for custom plugin role may fail in tests

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/About/View.elm
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-about.scss

https://issues.rudder.io/issues/26338
- When there is an empty value, it is replaced by a grey text ‘No data available’, and there is no longer a copy-to-clipboard button in this case.
- The "Launch options" value can now be resized and scrolled, and cannot exceed a certain maximum height so that it doesn't take up too much vertical space

Fixes #26338: Prettify About page

---

Cargo.lock
policies/module-types/system-updates/Cargo.toml
policies/module-types/system-updates/src/db.rs
policies/module-types/system-updates/src/package_manager/apt.rs
policies/module-types/system-updates/src/package_manager/apt/progress.rs

https://issues.rudder.io/issues/25759

Fixes #25759: Improve APT/dpkg output collecter

---

policies/module-types/system-updates/src/hooks.rs
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/servers/TestInstanceIdService.scala

https://issues.rudder.io/issues/26396
Just comment the test as it is not critical one.
Also the geteuid in policies can fail, we can remove that one.

Fixes #26396: Test for instance ID is failing on Docker CI

---

Jenkinsfile

https://issues.rudder.io/issues/26411
To still publish tests, without running them (https://stackoverflow.com/questions/24727536/maven-skip-tests)

Fixes #26411: Publish step for CI runs the tests when they already have previously run

---

qa-test

https://issues.rudder.io/issues/26413
`./qa-test` works since https://github.com/Normation/rudder/pull/6189/files, 
but `./qa-test --shell` has the wrong pattern, it misses the `*/` and `/*`

Fixes #26413: Ignore policies lib tests with qa-tests --shell

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/api/ApiAccountRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/api/DataStructures.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/RestDataSerializer.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RoleApiMapping.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/ApiAccount.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/RestApiAccounts.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ApiAccountApi.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_accounts.yml
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/data/ApiAccountTest.scala
webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/ApiCalls.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/DatePickerUtils.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/Init.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/JsonEncoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/ViewModals.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/ViewUtils.elm
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/ApiAccounts.scala
webapp/sources/rudder/rudder-web/src/main/webapp/secure/access/apiManagement.html
webapp/sources/utils/src/main/scala/com/normation/utils/DateFormaterService.scala

https://issues.rudder.io/issues/26335
WIP status at 2025-02-14
- The backend is working accordingly to what we want, API tests work
- I didn't clean-up things for now: in particular `RestApiAccounts` must be deleted (butI did clean-up things related to the old format)
- elm does not work, at least because elm side isn't able to decode rfc3339 datetime and is expected an other format for the date pickler. 
- there will be some other inconsistencies, since the API input for update / regenerate token / create token have changed a bit
- I don't know if there's other things not working since for now, it's blocked here. 
On the backend side, the most notable change are that we have different data structures for different action and return values. 
In particular: 
- create and update are …

Fixes #26335: Port RestApiAccount api endpoint to zio-json 

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/api/ApiAccountRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/api/DataStructures.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/api/TokenGenerator.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/RestDataSerializer.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDiffMapper.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlSerialisationImpl.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlUnserialisationImpl.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/api/ApiTokenTest.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/ApiAccount.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/RestApiAccounts.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ApiAccountApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/users/User.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/EventLogDetailsGenerator.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/data/ApiAccountTest.scala
webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/View.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/ViewUtils.elm
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/endconfig/action/CreateSystemToken.scala
webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/endconfig/action/TestCreateSystemToken.scala

https://issues.rudder.io/issues/25903
A similar change needs to be done in the api-authorizations plugins for user tokens.
* Since #6030 the old tokens are not usable anymore, this pull request takes advantage of this to refactor this part.
Split the `ApiToken` type, which used to contain both clear-text and hashed values into two separate types to prevent confusions and prevent misusage as much as possible:
* `ApiTokenSecret`: The token value, to be sent to the creator and not stored on the server
* `ApiTokenHash`: The token hash, as stored (either in LDAP or memory)
* Make no effort to prepare for a v3 (appart from storage), it would only be needed in case sha2 is not considered safe anymore. Future changes to the API access would likely be for something quite different (OAUTH/JWT/...), …

Fixes #25903: Refactor API tokens after clear-text removal

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/properties/Properties.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/properties/MergeNodeProperties.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/nodes/TestMergeGroupProperties.scala

https://issues.rudder.io/issues/26325
The logic for overriding properties did not exist yet for groups : until now the specific case of a group defining the order of override of properties from its parents has always resulted in a conflict for the group.
We need to handle this case : to resolve the conflicts (on the left part) we look at the parent properties, and for a given property, we look at the most prioritized parent that defines it (and we leave it as a conflict if there isn't any).

Fixes #26325: Resolved properties conflicts still appear as errors in status 

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewBlock.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewMethod.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTabForeach.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTechnique.elm

https://issues.rudder.io/issues/26278
This PR brings the loops feature to the blocks.
- All the code that manages the display of loops has been placed in a new file, `ViewTabForeach.elm`
- In ViewMethod.elm, `showParam`, `showMethodTab` functions now return an `Element Msg` instead of an `Html Msg` (as in ViewBlock.elm). This way, the code used to display the loops tab and the label is the same for methods and blocks

Fixes #26278: Add foreach on blocks

---

relay/sources/rudder-package/src/plugin.rs

https://issues.rudder.io/issues/26428

Fixes #26428: rudder-pkg reports a success when installing a plugin even if the postinst plugin script was in error

---

Cargo.lock
policies/module-types/system-updates/Cargo.toml
policies/module-types/system-updates/src/package_manager/apt.rs
policies/module-types/system-updates/src/package_manager/apt/progress.rs

https://issues.rudder.io/issues/26438
The problem here is that APT (actually dpkg) writes to stdout which breaks CFEngine's protocl. stdout is then closed, hence the pile of broken pipe errors.
Let's just silence apt, we already collect everything we need through other channels.

Fixes #26438: Parent produces errors on stderr and a global error status for the event

---

rust.makefile

https://issues.rudder.io/issues/26444

Fixes #26444: Update cargo auditable for Rust 2024

---

webapp/sources/rudder/rudder-web/src/main/elm/elm.json
webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/Action.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/ApiCalls.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/Init.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/JsonEncoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/PluginData.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/Select.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/Tests/PluginsTests.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/View.elm
webapp/sources/rudder/rudder-web/src/main/resources/load-page/rudder-loading.html
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/PluginExpirationInfo.scala
webapp/sources/rudder/rudder-web/src/main/style/rudder/_rudder-variables.scss
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-plugins.scss

https://issues.rudder.io/issues/26336
In terms of features, we need to know information about which selected plugins can be installed/enabled/disabled/uninstalled.
To better split this, there are two modules : 
* one which contains all the logic of install/enable,etc. : `Action.elm`
* another which makes the selection of allowed plugins : `Select.elm`
which only expose the needed datatypes (most of them are opaque), the mainly used functions are :  
```mermaid
graph LR
Action --findPluginActions--> Select --select--> DataTypes
```
This model allows to define the action that are allowed/disallowed, then to apply them for selected plugins, and tests have been added for the `select` method on all cases for allowing/disallowing an action on a plugin.
At last, this information is used in …

Fixes #26336: Improve user interaction and displayed information on plugins management page 

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/DirectiveCompliance/ViewUtils.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/GroupCompliance/ViewUtils.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeCompliance/ViewUtils.elm
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-datatable.css
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-template.scss

https://issues.rudder.io/issues/26417
- I've removed the unused css class **.ok** applied on `<td>` element
- I've added a `div.value-container` to "Value" and "Message" cells, on which I've changed the way line breaks are handled, and I've applied a maximum height to it (a scroll bar appears when the content is too long).

Fixes #26417: Keep line breaks in reports

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Hooks/View.elm

https://issues.rudder.io/issues/26399

Fixes #26399: Hooks documentation link redirects to non-existing page

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/administration/PolicyBackup.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/TabUtils.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/Maintenance.scala
webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/maintenance.html

https://issues.rudder.io/issues/26447
The tab system in `Settings` page needs to be refactored, as it is now needed in the `Maintenance` page.
Also the CSS selectors are not similar, we need to be able to insert the tab content at a specific place, instead of just appending it, so we need to specify modes within a `TabUtils`

Fixes #26447: Policy backup and plugins pages should not be available as read-only admin

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/properties/Properties.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DataStructures.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ParametersApi.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateOrUpdateGlobalParameterPopup.scala

https://issues.rudder.io/issues/25962
The idea is to bring make global properties (parameters) follow the same character restriction than group/node properties. 
Today, they have fewer chars allowed which means that we can create node or group properties that can't have a global default. 
This change doesn't affect any existing global properties because it only extends the set of allowed character, none of the existing ones are removed. 
The escaped string must be used in any cfengine-related code which want to refer to the parameter, like in https://github.com/Normation/rudder-techniques/pull/1868
:warning: We don't expose the escaped name to user in the UI or wherever easy, because actually we don't want user to refer directly to that parameter, we want them to use the …

Fixes #25962: Authorize global parameter names that are not alpha numeric only 

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/plugins/cli/RudderPackagePlugin.scala.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/plugins/cli/RudderPackageServiceTest.scala
webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/Init.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/Select.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/Tests/PluginsTests.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/View.elm
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-menu.scss
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-plugins.scss
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-template.scss

https://issues.rudder.io/issues/26449
* Remove colors from API by adding NO_COLOR=1 environment variable
* Refactor the view errors, the previous union type for viewing plugins did not make sense : now we always have a list of plugins, and maybe a modal and an error aside from that.
* Changing the UI for the filter, and the top bar
* Adding several warnings : in the header when account is not found, below the filters :

Fixes #26449: Improve accessibility of filter, actions and errors on plugins page

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/endconfig/migration/FixedPathLoggerMigration.scala
webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/endconfig/migration/TestMigrateLogbackXml.scala

https://issues.rudder.io/issues/26446
The condition on attribute was checking if there was an stdout appender within a if. The condition should be to not have an stdout appender ...

Fixes #26446: Every time webapp starts the logback file gets duplicate XML to configure fixed log file 

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/plugins/PluginData.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/plugins/PluginError.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/plugins/PluginDataTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/plugins/PluginErrorTest.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/About.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_plugins.yml
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
webapp/sources/rudder/rudder-web/src/main/elm/sources/About/View.elm
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/plugins/RudderPlugin.scala
webapp/sources/rudder/rudder-web/src/test/scala/com/normation/plugins/RudderPluginTest.scala

https://issues.rudder.io/issues/26439
* License errors now have a more informative message for the expiration of plugins
* The Rudder version may contain `SNAPSHOT`, but plugins may be built on either snapshot or non-snapshot version, so we need to adjust the error check to ignore this part
* There was a bug for the global license : the tests were not covering the case of combining a list of licenses, an empty `maxNodes` ended up zeroing the license :facepalm:
* In the About page there was a table display issue and the version types were stringified with case class names

Fixes #26439: Fix display of license information

---

webapp/sources/pom.xml
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/plugins/PluginData.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/ComplianceLevel.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/cfclerk/domain/VariableTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/hooks/HooksTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/metrics/NodeCountHistorizationTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestTechniqueCompilationCache.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportsTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/score/ComplianceScoreEventHandlerTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/RuleValServiceTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/servers/TestInstanceIdService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ApiAccountApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/users/UserManagement.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/CampaignApiTest.scala
webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/endconfig/migration/TestMigrateJsonTechniquesToYaml.scala
webapp/sources/scala-ldap/src/test/scala/com/normation/ldap/sdk/LoadDemoDataTest.scala

https://issues.rudder.io/issues/26455
This the backport to branch 8.3 of:
- https://github.com/Normation/rudder/pull/6147
- https://github.com/Normation/rudder/pull/6206
- https://github.com/Normation/rudder/pull/6208
- https://github.com/Normation/rudder/pull/6210
- https://github.com/Normation/rudder/pull/6212
- https://github.com/Normation/rudder/pull/6213
Plus some update of dependencies which were transparent and seemed without risk (no source change, all test pass, rudder starts, etc)

Fixes #26455: Changes for scala 3 migration - branch 8.3

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/ViewUtils.elm
webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder-datatable.js
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-datatable.css
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-main.scss
webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/nodes.html

https://issues.rudder.io/issues/26354
Now the ‘provider’ label is in absolute position, so has no impact on the display of the property value. Here is the result :

Fixes #26354: Adding a property column to nodes list causes lines to double height thus screen shows 2 times less nodes

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/AsyncDeploymentActor.scala

https://issues.rudder.io/issues/26479
Use the actual duration and not the ZIO promise on it. 
Plus that log is important enough to be in `info`, not just debug

Fixes #26479: Bad "OnSuccess" delay in log

---

webapp/sources/rudder/rudder-core/src/main/resources/ldap/rudder.schema
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/RudderLDAPConstants.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/properties/Properties.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlUnserialisationImpl.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/ldap/GlobalParamMigration61Test.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/nodes/TestMergeGroupProperties.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ParametersApi.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TestInheritedProperties.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/endconfig/consistency/CheckRudderGlobalParameter.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateOrUpdateGlobalParameterPopup.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/ParameterManagement.scala

https://issues.rudder.io/issues/26487

Fixes #26487: Global properties generated by security benchmarks are displayed on Global Properties GUI

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder-datatable.js
webapp/sources/rudder/rudder-web/src/main/package-lock.json
webapp/sources/rudder/rudder-web/src/main/package.json
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-datatable.scss
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/common-layout.html

https://issues.rudder.io/issues/467
Adding the `Export` button to every nodes table : 
* add the latest compatible [DataTable Buttons library)](https://cdn.datatables.net/buttons/1.7.1/)
* [options](https://datatables.net/reference/button/csv#Options) : 
* customize the compliance export to only export the percent value
* file name is the table grid ID 
* rework the [sDom](https://datatables.net/reference/option/dom) option for correct alignment, buttons is `B` 
N.B. : This can now be applied to any other table, just by adding `B` to the `dom`/`sDom`

Fixes #467: CSV export of server list (simple)

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder-datatable.js
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/SrvGrid.scala

https://issues.rudder.io/issues/26264
The `nodeIds` variable is no longer a global variable. The table is always initialized with the right node ids now.

Fixes #26264: The refresh button from the nodes webpage change the list of nodes in the other tab

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/HomePage.scala

https://issues.rudder.io/issues/26545
The `RequestVar` needs to be accessed outside of a ZIO for-yield : this is a really surprising behavior :shrug:, maybe specific to the new ZIO version in 8.3  ?

Fixes #26545: No compliance on dashboard in Rudder 8.3

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/HomePage.scala

https://issues.rudder.io/issues/26599
The call `scoreService.getAll()` faces the same issue as in #6274 when it calls `nodeFactsRepo.getAll()` : it sees empty nodes when inside the for-yield, but when initialized early it sees the correct list of nodes
**EDIT:**
the `CurrentUser.queryContext` is a also an access of `RequestVar` which is impure state, it needs to be done early oustide of the for-comprehension

Fixes #26599: Rudder 8.3 Beta 2 : Missing Score pie charts on dashboard

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/ViewUtils.elm
webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder.js
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/administration/policyServerManagement.html

https://issues.rudder.io/issues/26514
The `buildScrollSpyNav` function now takes 2 parameters: 
- the navbar identifier, so as not to override another navbar
- the identifier of the container that contains the titles linked to this menu

Fixes #26514: Change validation and global settings navigation menu got merged

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder-datatable.js
webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder.js
webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/settings.html
webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/nodes.html

https://issues.rudder.io/issues/26590
We can now access tabs directly using an anchor in the url!
- When pages load, if an anchor is used that matches the ID of a tab on the page, then that tab will automatically be opened.
- This anchor is updated when the user changes tab, meaning that when the page is reloaded, the user is redirected to the last open tab.
- If the anchor does not correspond to any tab on the page, then nothing happens.
- :information_source: There is one exception: the Nodes page. This page already uses the anchor to store search data, so the tab id is stored in the anchor's json object.
- :warning: This navigation system is not yet functional in Elm applications (such as Rules, Groups, Techniques...).
**Example below :arrow_down: :** the URL contains the anchor …

Fixes #26590: Make tabs accessible by URL

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/About/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/About/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/About/JsonEncoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/About/View.elm

https://issues.rudder.io/issues/26584
The parsing of the license always ended up as `Nothing` because in case of unlimited number of nodes, the API returns `null`.
The model needs to be changed to be the same as in the API
**EDIT:** re-add license `supportedVersion` for copying it to the clipboard as it has been deleted in #6273

Fixes #26584: License information not displayed on “About” page

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/BootstrapMenu.scala
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-menu.scss

https://issues.rudder.io/issues/26532
- I removed the highlight color from the active parent section, which was confusing because it was lighter than all the other menu items
- I've rotated the arrows indicating the open/closed status of the menus by 90°, to be consistent with the other arrows on the pages ( right : closed, down: open)
Here is the result 
:

Fixes #26532: Menu color leads to unclarity of meaning

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/ApiDatastructures.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RoleApiMapping.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/Index.scala

https://issues.rudder.io/issues/26602
Adding specific access to some settings keys, as they were removed [here](https://github.com/Normation/rudder/commit/ab5cc552a7d7d316a282c8ebd9d6aa7cf50a87e0#diff-29912d1fc9e0387f74c88c27c30606e2cb6bb89912d4dd63d2440d8f9d0fd292L203).
Endpoints need to declare that specific authorizations have access to some of its parts (segments, here in the Settings API : some _settings keys_)
Some cleaning has been made because the compliance has rights to see the "Administration" entry, because or the `technique_read` right : the right is removed in 8.2 in https://github.com/Normation/rudder/pull/6292, and in this PR the menu "Administration" can only be seen with `admin_read`

Fixes #26602: User with "compliance" perm get error on group, directive pages

---

webapp/sources/rudder/rudder-rest/src/test/resources/api/api_compliance.yml

https://issues.rudder.io/issues/26646
So, the change in API output are consistent with the compliance computation evolution from https://github.com/Normation/rudder/pull/6285 and the fact that in 8.3, we added a technique with blocks in test repository.

Fixes #26646: Upmerge of compliance by directive change breaks 8.3

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitArchivers.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestEditorTechniqueWriter.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/26644
We need to expose `techniqueArchiver` for security benchmark technique management in `RudderConfig` API. 
Some services weren't correctly alphabetically sorted in the big declaration, so I put them back in place. 
Also, we need bulk operation for `TechniqueArchiver` 
- mass add a category and all children techniques, 
- delete a category and all children techniques. 
Plus, we need to parse technique. I didn't want to directly expose `TechniqueParser`, because it only knows about `metadata.xml` (which is what we want for now for benchmark), but in the long time, we would like to have something in common with the archive manager that can know what to do with yaml, json, or xml. So I added a `parseTechnique` in archiver too. 
And add `techniqueArchiver` …

Fixes #26644: Expose techniqueArchiver in RudderConfig and Mock objects

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Onboarding/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Onboarding/View.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/View.elm
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/administration/RudderCompanyAccount.scala

https://issues.rudder.io/issues/26620
It just a renaming of displayed info, variable naming etc was not done to prevent potential issue. 
Typically, in many places, we use `Account` for the `Licence Id` for variable naming or pattern matching, also used in API output, but I think that we don't want to change all of that, but let me know if you want to rename some object.

Fixes #26620: Renaming tab and parameter for licence info in setup page

---

webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-datatable.scss
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-directives.scss

https://issues.rudder.io/issues/26639
The css rules that define the height of these table lines have been moved to the wrong scss file. Now it looks like before:

Fixes #26639: Global properties are unfolded in weird way 

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/GroupsApi.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupCategoryForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala

https://issues.rudder.io/issues/26429
* Prevent API modification of system groups (as for deletion)
* Remove the button to save system groups and make all form fields readonly

Fixes #26429: Changing the system group category hierarchy breaks Rudder

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/administration/RudderCompanyAccount.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/SetupRedirect.scala
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-settings.scss

https://issues.rudder.io/issues/26688
* Evaluate Lift variables outside of ZIO context (similar to https://github.com/Normation/rudder/pull/6280)
* Rename the "company account" within the tab ID into something that looks more like onboarding : `welcomeSetupTab`

Fixes #26688: Initial page after Rudder installation should be the license tab at welcome step

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/View.elm

https://issues.rudder.io/issues/26633
Follows the renaming of the tab to "License", and of the tab ID to `welcomeSetupTab` in https://github.com/Normation/rudder/pull/6310

Fixes #26633: License error in plugins should link to settings at licence tab

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/ApiAccount.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_accounts.yml
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/ApiCalls.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/DatePickerUtils.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/View.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/ViewModals.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/ViewUtils.elm

https://issues.rudder.io/issues/26671
So, the main idea is to expose the token state and make the token optional in elm, to match backen semantic. The token state can be `undef`, `generatedV1` for old token, and `generatedV2` for new format. 
It prefred to enumerate all the state because if we do a v3, it's likely that we will need to change all the place and so I made them easy to find. 
That `tokenState` is transferred by API. 
Then, in elm, we just map that into the token account data structure, and I changed the check for the warning messge to look for token with a `GeneratedV1` token state. 
These token also get the `token-disabled` badge.
Finally, I added a check in the LDAP unserialisation method for the token version, so that we can disable `ApiAccount` right here, even if they …

Fixes #26671: Confusing warning header on the plugin webpage

---

webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-menu.scss

https://issues.rudder.io/issues/26680
Here is the result (I also replaced some color codes with the corresponding scss variable) :

Fixes #26680: When the menu is collapsed, category titles have a transparent background.

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/reports/execution/ReportsExecutionService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ComputeNodeStatusReportService.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/26683
Ignore nodes which just got new reports in expiration check. 
Also clean methods and event which were never called anywhere in code.

Fixes #26683: Don't check for expiration nodes that just got new reports

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ComputeNodeStatusReportService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/NodeStatusReportRepository.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/26692
Since we have a queue containing a `Seq[T]` of size 1, it's the same a having a queue of `T` of size N. 
In the previous case, the inner `seq` was unbounded, leading to memory exhaustion in worst case. 
I chose a bounded queue to avoid that. It's sliding, ie keeping the most recent events and dropping the older one when full. 
The use of the queue as intented allows to remove the semaphor used up of it, since it's the whole of a queue to be able to add things atomically. 
It also remove a `takeAll` + `merge two array` from the hot path, likely removing some useless translation between collection. 
Then, on the down side, we do the same thing as before, just `takeAll` (getting a seq of T) in place of `take` (getting a seq of T). 
The sizing of the …

Fixes #26692: Remove semaphore and use a sliding queue for compliance invalidation

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ComputeNodeStatusReportService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/NodeStatusReportRepository.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/26725
The reason of the cpu load is that `queue.takeAll` is non blocking. Which is :exploding_head:

Fixes #26725: Reverting change in queue since it leads to CPU over use

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTechniqueList.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/GroupRelatedRules/View.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Groups/View.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/View.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/ViewTabContent.elm
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/Groups.scala
webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/ruleManagement.html
webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/techniqueEditor.html

https://issues.rudder.io/issues/26106
Remove the `href` from links, because the browser could use it to reload the page, instead of running the `onClick` defined in Elm. 
We used the `href` to open in a new tab e.g. with a middle click. Now, as a replacement, we open a new tab using the `auxclick` event : https://developer.mozilla.org/en-US/docs/Web/API/Element/auxclick_event
This occurs in both rules and technique editor.
**EDIT:**
Simple fix : use [onClickPreventDefault](https://package.elm-lang.org/packages/elm-community/html-extra/3.4.0/Html-Events-Extra#onClickPreventDefault) instead of `onClick`

Fixes #26106: Sometimes when we click on an element (technique or rule), the whole page reloads

---

webapp/sources/pom.xml

https://issues.rudder.io/issues/26707
Upgrading spring/spring-security to last version where the CVE is corrected.

Fixes #26707: Upgrade spring security dependency to correct CVE-2025-22228

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/StatusReports.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/NodeStatusReportRepository.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/NodeStatusReportRepositoryTest.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/26703
So, the culprit is `AggregatedStatusReport` which is a `final class` but not `case`. 
It means that that part of the code in `NodeStatusReportRepositoryImpl` always yield false (since `e` and `report` are built from different paths, their `AggregatedStatusReport` are different objects): 
```
m.get(id) match {
case Some(e) =>
if (e == report) {
None
} else {
Some((id, report))
}
```
So, for *each* checks, we get "it's a new report", so we *always* save it in database. The performance impact must be *huge*.
This is corrected by adding an equals/hashcode, as it must be done. 
Found with the dumbest unit test possible, *sigh*.

Fixes #26703: Make AggregatedStatusReport correct wrt equals

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/ViewRulesTable.elm
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-template.scss

https://issues.rudder.io/issues/26710
I've replaced the “No report” text with a loading animation :

Fixes #26710: There is no indication that the rule page is loading compliance

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/StatusReports.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DataStructures.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/reports/StatusReportTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ExecutionBatchTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ReportingServiceUtilsTest.scala
webapp/sources/rudder/rudder-rest/pom.xml
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/Compliance.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ComplianceApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/ComputePolicyMode.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_compliance.yml
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/domain/reports/JsonPostresqlSerializationTest.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RunComplianceComputation.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TestDirectiveComplianceCsv.scala
webapp/sources/rudder/rudder-web/src/main/elm/sources/DirectiveCompliance/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/DirectiveCompliance/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/DirectiveCompliance/ViewUtils.elm
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/ShowNodeDetailsFromNode.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ComplianceData.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-main.scss

https://issues.rudder.io/issues/26712
So, this is a big, overdue clean-up of the skipped mess that organically growed during the years. 
It shoudl correct all `skipped` problem we got, including https://issues.rudder.io/issues/26712 and https://issues.rudder.io/issues/24843. 
It also lead to a MASSIVE performance improvent, that looks quadratic for number of node or number or rules, and lead to at least an order of magnitude quicker computation of compliance for rules. 
> Note: this PR is rather low risk since it only change the computation of skipped directives in API/UI. I thing that at worst, we get new problems with skipped directive. 
The only idea is that we should really just keep the skipped directives in `NodeStatusReport` with a tag "I'm overridden by that rule`. It's really …

Fixes #26712: When directives are skipped, they are multiplied in the directive tab of the rule

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/HomePage.scala

https://issues.rudder.io/issues/26061
So, for `directives` and `techniques`, we want to display only non-system items. So we used to use the LDAP filter `'(&(objectClass=activeTechnique)(isSystem=FALSE))'` which says : "look for entries with the attribute `objectClass` set to `activeTechnique` and the attribute `isSystem` set to `FALSE`. Which *needs* both attribute to be defined at the given value. 
But `isSystem` is optional and along the way, we lost the habits to set it to `false` when it's the case, because it's the default semantic. So we have `activeTechnique`s without the attribute actually set to `FALSE`. 
All that is due to the fact that we added `policyType` at LDAP level, but we are doing Smart Things at the repository level to make update transparent - at least for things …

Fixes #26061: Number of techniques shows 0 when I have several techniques. They have been imported.

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ArchiveApi.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/ArchiveApiTest.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/lift/MergePolicySpec.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/users/UserManagementServiceTest.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/users/UserSerializationTest.scala

https://issues.rudder.io/issues/23998
Add the new merge policy which is just setting target to empty in addition to previous one when in use.
Also, I want to have a common naming convention, so use a set for names now to keep backward compat with the old name.

Fixes #23998: Completly ignore source target of rules when importing an archive

---

webapp/sources/api-doc/code_samples/curl/archives/import.sh
webapp/sources/api-doc/paths/archives/export.yml
webapp/sources/api-doc/paths/archives/import.yml
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ArchiveApi.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/ArchiveApiTest.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/lift/MergePolicySpec.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/users/UserManagementServiceTest.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/users/UserSerializationTest.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/26801
Add the `all` keyword by making it a special item id. Then, when looking for things to zip, if there is an item with id `all`, get all corresponding ressources in place of the list of provided/dependent ids. 
Based on #5309

Fixes #26801: Add a "all" keyword for archives export

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/earlyconfig/db/CheckTableNodeLastCompliance.scala

https://issues.rudder.io/issues/26869
Adding the `CheckTableNodeLastCompliance` back, it looks like it has been deleted in the upmerge of [#6142](https://github.com/Normation/rudder/pull/6142/files#diff-060592aa1d65bfa1ec057158e1139794df7ad9136723a72ecd4e9695e98891b7L3417).
The ordering of the check is the same as when it was added ([here](https://github.com/Normation/rudder/pull/5854/files#diff-060592aa1d65bfa1ec057158e1139794df7ad9136723a72ecd4e9695e98891b7R3224)), i.e. before actual migrations

Fixes #26869: Logs filled with similar errors : SQL : la relation « nodelastcompliance » n'existe pas.

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/db/DB.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportsTest.scala

https://issues.rudder.io/issues/26865
Since it's only use in one test, we can move (and simplify) the doobie code in the test directly.

Fixes #26865: Clean-up insertion in ruddersysevents

---

Cargo.lock
deny.toml
policies/lib/Cargo.toml
policies/lib/tests/integration/permissions_group_acl_absent_test.rs
policies/module-types/augeas/tests/ariadne.out

https://issues.rudder.io/issues/26872
* The `users` crate was not maintained and had known unsoundness, replace by a maintained fork.
* Make the source checks more precise
* Allow unused allowed license

Fixes #26872: Advisories in Rust deps

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/RestDataSerializer.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/workflows/ChangeRequest.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DependencyAndDeletionService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/workflows/CommitAndDeployChangeRequestService.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/ModificationValidationPopup.scala

https://issues.rudder.io/issues/26853
This is part of the plan to remove the dependency to the lift library (replacing the `Box` type with `ZIO`).
In particular, the change-validation plugin contained a call to `BoxToIO` in `com.normation.plugins.changevalidation.api.ChangeRequestApi`, which required that the return type of `com.normation.rudder.domain.workflows.ChangeRequest#change` be changed. Hence, the return type is now `PureResult[T_CHANGE]` (previously `Box[T_CHANGE]`).
This PR is linked to #6353 , which uses change, as well as https://github.com/Normation/rudder-plugins/pull/827 , which contains the corresponding change (replaces the call to `BoxToIO` with `PureResultToIO` in `ChangeRequestApi`), and removes most of the remaning instances of the `Box` type in change-validation.

Fixes #26853: Migration from Box to ZIO : Refactoring of classes ChangeRequest and ModificationValidationPopup

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/users/User.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/users/UserSerializationTest.scala

https://issues.rudder.io/issues/26898
This is a backport of https://github.com/Normation/rudder/pull/6367 to Rudder 8.2.

Fixes #26898: Prepare EventActor serialization for scala3

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SystemApi.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/SystemApiTest.scala

https://issues.rudder.io/issues/26779
Bad `hh` in place of  `HH`. Plus normalize toward iso and utc

Fixes #26779: Archive “download as zip” creates backup with wrong name (but right contents)

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/ApplicationLogger.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogDetailsService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/TestFileFormat.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlUnserialisation.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlUnserialisationImpl.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/CmdbQueryParser.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/workflows/CommitAndDeployChangeRequestService.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/marshalling/TestXmlUnserialisation.scala

https://issues.rudder.io/issues/26861
This is part of the plan to remove the dependency to the lift library from Rudder and Rudder plugins.
This PR migrates the following classes in XmlUnserialisation : 
- DirectiveUnserialisationImpl
- NodeGroupCategoryUnserialisationImpl
- NodeGroupUnserialisationImpl
- RuleUnserialisationImpl
- RuleCategoryUnserialisationImpl
- GlobalParameterUnserialisationImpl
- ChangeRequestChangesUnserialisationImpl
This change also includes a new `XmlUtils` object, which offers methods to look up a specific child node or attribute of a given XML node, and the error handling that comes with it. XmlUtils may be used in order to migrate the remaining classes in XmlUnserialisation
This PR is part of the migration from Box to ZIO in change-validation, and is linked to …

Fixes #26861: Migration from Box to ZIO : Refactor XmlUnserialisation 

---

webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/FusionInventoryParser.scala
webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-inventories/rudder-tag/linux-8-3-with-agent-version.ocs
webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-inventories/rudder-tag/linux-8-3-without-agent-version.ocs
webapp/sources/ldap-inventory/inventory-fusion/src/test/scala/com/normation/inventory/provisioning/fusion/TestReportParsing.scala
webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/InventoryMapper.scala
webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/LDAPConstants.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/RudderLDAPConstants.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/queries/CmdbQuery.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/queries/NodeQueryCriteriaData.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-web/src/main/javascript/rudder/homePage.js
webapp/sources/rudder/rudder-web/src/main/resources/ldapObjectAndAttributes.properties
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala

https://issues.rudder.io/issues/26918
- We are already saving the agent version in a dedicated structure in LDAP in along with other agent info. 
- We already use the agent version information to build the dashboard donut. 
So that change only does:
- read the new tab `AGENT_VERSION` from XML inventory. If present, it use it for the persistance, else it reverts to the old method (full compatibility with previous agent version - there's a unit test added to ensure of that)
- change the query used when one clicks in the donut for a given agent version. 
- it also add the relevant code to add a "agent version" criteria, similar to "agent type" and that works only on `NodeFact`. 
- there is a renaming from `A_AGENTS_NAME` to `A_AGENT_NAME` for consistency with `A_AGENT_VERSION` since we can …

Fixes #26918: Store agent-version as a dedicated field

---

webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/services/provisioning/InventoryParser.scala
webapp/sources/ldap-inventory/inventory-fusion/src/test/scala/com/normation/inventory/provisioning/fusion/TestPreParsing.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/domain/TechniqueCategory.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/GitTechniqueReader.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/db/Doobie.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitArchivers.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/workflows/CommitAndDeployChangeRequestService.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/cfclerk/domain/SectionTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/cfclerk/domain/TechniqueTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/cfclerk/domain/VariableTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/cfclerk/xmlparsers/ParseTechniqueTest.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/ApiDatastructures.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RudderJsonResponse.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ArchiveApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/LiftApiDispatcher.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/users/RudderUserDetailsFile.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_directives.yml
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_groups.yml
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_parameters.yml
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_rules.yml
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_techniques.yml
webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/earlyconfig/db/TestCheckUsersFile.scala
webapp/sources/utils/src/main/scala/com/normation/ZioCommons.scala
webapp/sources/utils/src/main/scala/com/normation/utils/XmlSafe.scala

https://issues.rudder.io/issues/26936
Move safe `SAXParserFactory` into its own object in `utils`, and use it everywhere. 
Also, create an utility method for technique category parsing to avoid having user not going through the safe parser. 
Also change the returned message of API to avoid letting too much go out (remove stack trace of system error in particular, likely to get displayed when a vulnerability is probed)

Fixes #26936: 

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/UserManagement/View.elm

https://issues.rudder.io/issues/26842
The condition to not display was just too broad.
The result could be improved later, for a few single custom authorizations, we should display each authorization in grey :

Fixes #26842: User management page no longer displays individual authorizations

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ArchiveApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/InventoryApi.scala

https://issues.rudder.io/issues/26944
We were using `filename` as the file name, and not a path, which it is really. So just use the real filename. 
Also changed for archive API, even if there not risk their since the file is never written, but if we change our way of doing things in the futur, I prefer to have that checked.

Fixes #26944: 

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewBlock.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewMethod.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTechnique.elm
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-technique-editor.scss

https://issues.rudder.io/issues/26921
Drag'n drop has undergone some changes:
- when a method is dragged, it remains visible (but greyed out)
- The appearance of drop zones no longer has an impact on the size of the list, so items remain in place when dragged and dropped.
- the appearance of the drop zones has therefore changed: it is no longer a zone delimited by a dotted border, but a separator that indicates the drop zones. This separator is highlighted when it becomes the target for the drop.
- The margins between methods and blocks have been reduced
I've also moved the info icon at the top right of the method to the method name badge, and removes the "method" label to free up space (not visible in the gif) : 
Thanks to these changes, it's now easier to move an element, and harder to …

Fixes #26921: Improve drag'n drop ergonomics in the techniques editor

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/EventLogAPI.scala

https://issues.rudder.io/issues/26979
Change the authz of the rollback endpoint in event logs (like https://github.com/Normation/rudder/pull/6401, upmerge is needed)

Fixes #26979: 

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/SharedFilesAPI.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/TechniqueApi.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_techniques.yml
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
webapp/sources/utils/src/main/scala/com/normation/utils/FileUtils.scala
webapp/sources/utils/src/test/scala/com/normation/utils/FileUtilsTest.scala

https://issues.rudder.io/issues/26957
Remove path trasversal in `TechniqueApi` creation. There's two place, in resources and in technique itself. 
That PR also rework a bit the `FileUtils` sanitization API: 
- change signature from `IOResult[Either[OutsideBaseDir, File]]` to `IOResult[File]` because we really don't want to treat an `OutsideBaseDir` as a potential ok result in the nominal case, and so it simplifies usage for nominal code,
- ass a `checkSanitizedIsIn(baseDir, path)` to add more flexibility in some case (it's just exposing what was internal before)

Fixes #26957: 

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/ViewModals.elm

https://issues.rudder.io/issues/26980
When `Full access` ("rw") is selected, the tenants should not be edited so we just disable it :
Several doubts, the app deserves some improvements :
* the UX ends up being weird : tenants are selected BEFORE selecting the access level. This is not the case for custom ACLs selection, which is turn is after the access level. Please let me know if there is something to do for now.  
* "rw" should not be a string but a known type in Elm.

Fixes #26980: API account form should not display tenants when full access is selected 

---

policies/lib/tree/20_cfe_basics/cfengine/paths.cf

https://issues.rudder.io/issues/26823
Add necessary paths for standard linux utilities for Archlinux family in paths.cf

Fixes #26823: “Users” standard technique : Fails setting secondary groups when already correct.

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder-datatable.js

https://issues.rudder.io/issues/26972
There is only one drag.
When the wrapper is an id `#groupNodesTable_wrapper` then the selectors seems to make the JS behave dreadfully...

Fixes #26972: When there is too many nodes in groups, we can't change criteria anymore

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder-datatable.js

https://issues.rudder.io/issues/27010
Being more strict about typing and validation in the JS code : validate the value of the radio button into `before` or `after`, or `null` (do nothing in that case)

Fixes #27010: 

---

webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestDataExtractorTest.scala
webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/RudderUserDetailsTest.scala

https://issues.rudder.io/issues/27016
The two last test classes with some `Fragments.foreach`. 
Porting was done "as directly as possible" to avoid risking changing test semantic.  It's easier to understand with `?w=1` in url

Fixes #27016: Scala3: port RestDataExtractorTest to ZIO

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/TechniqueApi.scala

https://issues.rudder.io/issues/27026
An optionnal action has become mandatory for no reasons.

Fixes #27026: Workspace directory is missing when saving a technique

---

webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-menu.scss

https://issues.rudder.io/issues/27027
Use the default border color, it needs to be applied to both the badge on hover and the `:before` pseudo-element :

Fixes #27027: Change request count badge needs more contrast on hover

---

webapp/sources/pom.xml
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/ReportType.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/StatusReports.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/domain/reports/JsonPostresqlSerializationTest.scala

https://issues.rudder.io/issues/27035
To make the change transparent for both Scala 2 and 3, I switched `ReportType` to `Enumeratum` and parse by hand. It has also a fallback to the a decoder able to deserialize the old syntaxt for transparent migration. 
It also updates ZIO lib and ZIO json to last version, because there was a ton of serialization bugs corrected in between.

Fixes #27035: ReportType json serialization in base is incorrect

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/plugins/settings/PluginSettings.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/Plugin.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/PluginInternalApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/PluginApi.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TestRestPluginInfo.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/27005
When updating settings in [the public API](https://docs.rudder.io/api/v/21/#tag/Plugins/operation/updateSettings) (the endpoint needs `Administration.Write` rights), the rudder package index needs an attempt to be updated. In case of an error the, like a 401 if credentials are wrong, the response will directly contain the error (the setting file is still updated) 
EDIT: did the cleaning of the APIs, there were some unsuitable JSON encoders, I added a new one that prevents from leaking the password by never encoding it, and added tests

Fixes #27005: License setup should update the list of plugins

---

policies/lib/tree/20_cfe_basics/packages.cf

https://issues.rudder.io/issues/27074

Fixes #27074: rpmvercmp can be called from its old path

---

webapp/sources/pom.xml

https://issues.rudder.io/issues/27079
Addresses https://www.cve.org/CVERecord?id=CVE-2025-49146 
Nothing changes compared to existing version.

Fixes #27079: Postgresql has (non impacting) CVE-2025-49146

---

webapp/sources/rudder/rudder-core/src/main/resources/reportsSchema.sql
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/score/ScoreRepository.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/earlyconfig/db/CheckTableScore.scala

https://issues.rudder.io/issues/26976
Add two migration, each for removing the non empty contstraint on message: one for `GlobalScore`, the other for `ScoreDetails`

Fixes #26976: Rudder webapp migration create table ScoreDetails with message constraint

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder-datatable.js
webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder.js
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala

https://issues.rudder.io/issues/27031
* add the button to all inventories table, wrapping the `B` just like for the nodes table in https://github.com/Normation/rudder/pull/6245 
* making export more flexible with additional button classes
* renaming previous nodes and node search exports to the same naming convention : `rudder_XXXX_<date>.csv`

Fixes #27031: Export node inventories tables into CSV

---

webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/reports_server.html

https://issues.rudder.io/issues/27040
User-based compliance are accessible under `compliance_read`, and can be found in system logs : a user with "inventory" role should not be able to see them. **EDIT: in fact users without `node_read`**
For now, until we know how to specifically handle system policy types in the system logs, that are visible in some parts of the UI, we should hide those parts for such user.

Fixes #27040: Inventory role allows to get system compliance and technical logs 

---

webapp/sources/pom.xml
webapp/sources/rudder/rudder-core/pom.xml
webapp/sources/rudder/rudder-web/pom.xml

https://issues.rudder.io/issues/27107
Dependency was overridden at `test` level in rudder-web, so not included in the final war

Fixes #27107: Still missing cats-effect-std_3

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTabForeach.elm

https://issues.rudder.io/issues/27131
We need to compare the index of the modified item, not its value.

Fixes #27131: Iterator items that have exactly the same values are considered to be a single object

---

webapp/sources/api-doc/code_samples/curl/campaigns/allEvents.sh
webapp/sources/api-doc/code_samples/curl/campaigns/campaignEvents.sh
webapp/sources/api-doc/code_samples/curl/systemUpdate/campaignHistory.sh
webapp/sources/api-doc/components/parameters/campaign-id.yml
webapp/sources/api-doc/components/parameters/order.yml

https://issues.rudder.io/issues/23507
* add exemple query parameters cURL urls (in dates, `+` needs to be encoded as `%2B`)
* fix some query parameters doc and add examples, as there could be a confusion between `order` and `asc` : https://github.com/Normation/rudder/blob/branches/rudder/8.2/webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/CampaignEventRepository.scala#L143-L149

Fixes #23507: API for history does not take before nor order into account

---

webapp/sources/pom.xml
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/JsonQueryObjects.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/queries/CmdbQuery.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/StatusReports.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/CmdbQueryParser.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestJsonQueryLexing.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestNodeFactQueryProcessor.scala

https://issues.rudder.io/issues/27147
Enable back `-Werror`. 
I needed to disable some checks: 
- disable safe initiationlization check. There is too much work to do, and that work is hard, long, and not correlated with the switch to scala 3
- remove an existantial warning on `BoxTrait`, because we can't do anything about it, 
And correct two other: 
- `ExecutionBatch`: actually, all `LastRunAvailable` are also `ExpectedConfigAvailable`. That makes little sense for a run with a deleted exepected config, so I'm not sure what happens here, but the encoding say so and scalac3 saw it - there is an `Unexpected` case
- `Query` lexer/parser : there was `lift-json` objects used as intermediary, that we really don't need anymore. Just use direct `zio-json` decoding, simplify everything. Some tests …

Fixes #27147: Enable fatal warning and disable variable initialization check

---

webapp/sources/rudder/rudder-web/src/main/elm/elm.json
webapp/sources/rudder/rudder-web/src/main/elm/review/elm.json
webapp/sources/rudder/rudder-web/src/main/gulpfile.mjs
webapp/sources/rudder/rudder-web/src/main/package-lock.json
webapp/sources/rudder/rudder-web/src/main/package.json
webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/changeLogs.html

https://issues.rudder.io/issues/27103
We now need to include ESM modules as the newer JS libraries (here [_jsondiffpatch_](https://github.com/benjamine/jsondiffpatch/releases)) are switching paradigm, or we could not upgrade (this is also the case for _chartjs_, but hopefully it still ships UMD dists). So there is some change in the gulpfile, we need to include the modules tree : there are javascripts imports and a single javascript entrypoint file is no longer sufficient to embark a library.
For _bootstrap_, the dependency upgrade is not breaking, there are simply some warnings that can be ignored from gulp, as discussed [here](https://github.com/twbs/bootstrap/issues/40962#issuecomment-2427637501), and it requires pinning the version of _sass_. Also the _gulp-sass_ plugin API exposes a …

Fixes #27103: Update front-end dependencies

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/MethodConditions.elm

https://issues.rudder.io/issues/27144
- Use `rhel*` classes for RHEL.
- Migrate automatically the `redhat_*` classes to `rhel_*` when opening a method.
- Use the `amzn` classes for Amazon Linux.
- Add a version for Amazon Linux as we now have it on the agent.
Rationale:
- `redhat` means “Red Hat family” (direct family, not including Fedora or Amazon Linux)
- The `redhat_*` classes mean RHEL, which makes no sense. We have specific `rhel` classes for this purpose. We should not use them.
- We should the specific classes (with versions) for each distribution, and `redhat` only for the family.
- `rhel`
- `rocky`
- `almalinux`
- `fedora`
- `centos`
- We used `amazon_linux` but we split classes on underscores when parsing, so it has always been broken.
- Amazon Linux actually has an exploitable …

Fixes #27144: Technique editor Operating System condition RHEL generates wrong “redhat” condition

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/MethodConditions.elm

https://issues.rudder.io/issues/27198

Fixes #27198: Remove deprecated Windows versions from the technique editor

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/CampaignEventRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/DataTypes.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/MainCampaignService.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/CampaignApi.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/CampaignApiTest.scala

https://issues.rudder.io/issues/27153
Some cleaning-up in campaign code:
-  use standard layout for CampaignEventState (case object/class in object CampaignEventState)
-  create enums for query parameters in place of string: CampaignSortOrder, CampaignSortDirection
-  factor out default value for CampaignSortOrder in pattern matching
-  use the actual CampaignEventState in place of its string value in query
-  remove MainCampaignService from CampaignHandler which is not used and create a dependency loop
Replaces https://github.com/Normation/rudder/pull/6424
Needed for https://github.com/Normation/rudder-plugins-private/pull/1038

Fixes #27153: Add types to campaign event data structures

---

webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/policies/RuleTargetTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/facts/nodes/TestNodeFactSerialisation.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/ldap/LDAPEntityMapperTest.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/UserManagementApi.scala

https://issues.rudder.io/issues/27234
This is true :
```scala
[ERROR] 743 |  final case object SafeHashes extends UserManagementInternalApi with ZeroParam with StartsAtVersion20 {
[ERROR]     |  ^^^^^
[INFO]     |  Modifier final is redundant for this definition
```

Fixes #27234: Upmerge of user API definition breaks with Scala 3

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/plugins/PluginData.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/plugins/cli/RudderPackagePlugin.scala.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/plugins/PluginDataTest.scala
webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/Action.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/PluginData.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/Select.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/Tests/PluginsTests.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/View.elm
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/plugins/RudderPlugin.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/PluginExpirationInfo.scala

https://issues.rudder.io/issues/27175
* the plugin status displayed in the Plugins page was only taking into account the status from rudder-package, not from the webapp which does license runtime check :
* use the webapp plugin definition to return the correct `status` and details with the `statusMessage` field
* display the `statusMessage` message as an error in Elm, it behaves just like when license is expired/missing
* refactor : 
* some duplicate code in the snippet with the plugins icon warning
* the Elm callouts and handling of license status to avoid code repetition/duplication

Fixes #27175: Plugins get silently disabled when number of licensed nodes exceeded.

---

webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/server/server_details.html

https://issues.rudder.io/issues/27245
Completely hide the tab when it's not relevant. From the data that the table contains, it requires `node_read` and `compliance_read` permissions (so it's the same as in https://github.com/Normation/rudder/pull/6432)

Fixes #27245: Inventory user sees technical logs table

---

relay/sources/rudder-relay-postinst

https://issues.rudder.io/issues/27254
We need to create the file before restoring SELinux policies, else it will be invisible.

Fixes #27254: Apache refuses to start when /var/rudder/lib/ssl/policy_server.pem is a symlink

---

webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-node-finished/91-compress-linux-policies

https://issues.rudder.io/issues/27213
So, the idea is to have a PoC with a `policy-generation-node-finished` hook that will do the archive/compression. 
The script: 
- create an archive in `/var/rudder/shate/${nodeid}/rules/policies.tar.bz2`
- the archive is the content of `/var/rudder/shate/${nodeid}/rules/cfengine-community` with the base directory renamed to `policies_next` 
-  `/var/rudder/shate/${nodeid}/rules/cfengine-community/` is not deleted (so that old nodes can still use that)
The benefits are : 
- it's extermelly quick to reach an E2E working solution and not block the whole feature any longer. 
- it's will become symetric to what is done for Windows agent, so can go forward on the next steps (performance, node generation rework) for both at the same time
- it's easier to …

Fixes #27213: Allow to distribute Linux policies in tar.gz

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/snippet/WithNonce.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala

https://issues.rudder.io/issues/27119
Keep the `script-src: 'nonce-<randomnonce>' 'script-dynamic'` in pages where the nonce has been generated to be put in script tags (`<script nonce="<therandomnonce>/>`),
But in other pages (e.g. served files, like `css`, `svg`, ...) we don't have script tags and the nonce has not been generated so we need `script-src: 'none'` (it's [the safest policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Content-Security-Policy/script-src#none))

Fixes #27119: CSP headers for pages without scripts are always set with static nonce

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder-datatable.js
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/NodeGrid.scala

https://issues.rudder.io/issues/27273
Very tricky solution to find in DataTable documentation, because the datatable for pending nodes is not a "regular" datatable, its data is populated from scala XML (directly as HTML), and the rendering even for CSV export is the "HTML as seen" i.e. the text, without spaces.
* **Problem :** the [CSV export](https://datatables.net/reference/button/csv#exportOptions) relies on the [orthogonal](https://datatables.net/reference/api/buttons.exportData()#buttons.exportData(-[-options-]-)) which relies on the [render](https://datatables.net/reference/option/columns.render#render(-data,-type,-row,-meta-)) function which is called when exporting CSV data function (by default renders the "HTML as seen" too)
* **Solution :** set the `orthogonal` option when …

Fixes #27273: Export in CSV concatenate IPs without spaces or delimiters

---

webapp/sources/.scalafmt.conf
webapp/sources/rudder/rudder-core/src/main/resources/reportsSchema.sql
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/CampaignEventRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/DataTypes.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/JsonCampaignSerializer.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/MainCampaignService.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/CampaignApi.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_campaigns.yml
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/CampaignApiTest.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/earlyconfig/db/MigrateTableCampaignEvents.scala
webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/earlyconfig/db/TestMigrateTableCampaignEvents.scala

https://issues.rudder.io/issues/27154
Needed by https://github.com/Normation/rudder-plugins-private/pull/1071
This PR allows to split the campaign event table into two parts: 
- the old one, `CampaignEvents`, represents the current state of the campaign, 
- the new one, `CampaignEventsStateHistory`, represents the log of states that the campaign went through. 
The migration adds new states to prepare for the future : `deleted` (not sure if needed), `failure` (to differentiate a user-skipped event from a failed one), and the pre/post hooks.
The migration also change the event that were `skipped` but with an error message to `failure` state. 
The other big change is that now, `state` is only an (enum) type, and not the full JSON with added information. This added information is now stored …

Fixes #27154: Create CampaignEventsStateHistory table

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Directivecompliance.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Nodecompliance.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules.elm

https://issues.rudder.io/issues/25584
When toggling compliance rows, the compliance bars HTML is rendered but some JS tooltip initialization is needed in all compliances : node, rules and directive compliance (which also needs an initialization in the Elm _init_)

Fixes #25584: the hover on compliance shows HTML

---

Jenkinsfile
policies/rudderc/Makefile
policies/rudderc/build.rs

https://issues.rudder.io/issues/27308

Fixes #27308: The Rudderc static binary still includes the outdated ncf library rather than the 8.3+ one

---

policies/rudderc/src/backends/unix/ncf/method_call.rs
policies/rudderc/tests/cases/general/escaping/technique.cf
policies/rudderc/tests/cases/general/form/technique.cf
policies/rudderc/tests/cases/general/loops/technique.cf
policies/rudderc/tests/cases/general/loops_with_main_branch_without_condition/technique.cf
policies/rudderc/tests/cases/general/ntp/technique.cf
policies/rudderc/tests/cases/general/param_in_condition/technique.cf
policies/rudderc/tests/cases/general/reporting/technique.cf
policies/rudderc/tests/cases/general/unsupported_methods/technique.cf
policies/rudderc/tests/compile.rs
policies/rudderc/tests/lib/common/10_ncf_internals/initialization.cf

https://issues.rudder.io/issues/27167
The v4 logger is the right fix for this.

Fixes #27167: When the component value of a method is too long, the reporting can be missing

---

webapp/sources/.scalafmt.conf
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/hooks/RunHooks.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryProcessor.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/PostCommits.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/NewNodeManager.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/RemoveNodeService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PolicyWriterService.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/hooks/HooksTest.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/users/Argon2.scala
webapp/sources/rudder/rudder-web/src/main/resources/logback.xml
webapp/sources/utils/src/main/scala/com/normation/ZioCommons.scala

https://issues.rudder.io/issues/27365
The main problem to adress is the cost of multiplying loggers classes in the case of per-campaign (or other ephemeral objects) loggers. 
We could add a cache for the "hook" loggers, which is quite simple, but it duplicates the work of logback that already does exactly that. 
So the chosen solution is to build a 0-cost abstraction in top of `SLF4J` logger to add our own methods. This is possible thanks to scala 3 `opaque` type + `extension methods`. 
I also removed `ZioLogger` to replace it with the new opaque `RudderLogger` because now, ZIO framework has its own logging framework, which blur things. It wasn't use anywhere, so that is a cheap enhancement (`NamedZioLogger` is used everywhere).
Once we have that in place, we can: 
- have one dedicated …

Fixes #27365: Allow per-hook-kind logger

---

webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/27379
Change default (and default in case of missing key) value to 6 months (180j) for disable, never for delete.

Fixes #27379: Users cleanup configuration is still too strict for disabling/deleting

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/DataTypes.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/properties/PropertyHierarchy.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/NodeComplianceExpiration.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/ApiAccount.scala
webapp/sources/utils/src/main/scala/zio/json/other/package.scala
webapp/sources/utils/src/test/scala/zio/json/other/EnumCodecTest.scala

https://issues.rudder.io/issues/27364
An enumeratum json codec that can be used with:
```
import enumeratum.*
import zio.json.other.*
sealed trait A extends EnumEntry
object A extends Enum[A] with EnumCodec[A] {
case object CaseOne extends A
case object casetwo extends A
override def values: IndexedSeq[A] = findValues
}
```
It comes with two variants that differ only in the parsing: 
-  `EnumCodecCaseSensitive[A]` : expects exactly `enumEntry` value
- `EnumCodecCaseInsensitive[A]`: pase case insensively
The default is case insensitive parsing, given by the alias `EnumCodec[A]`

Fixes #27364: Add a generic json codec for enumeratum

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/homePage.js

https://issues.rudder.io/issues/27370
* We need to `destroy()` existing charts present within the given DOM element (this resolves the issue when switching between benchmarks)
* We also need to wait for the element to be present, e.g. in https://github.com/Normation/rudder-plugins-private/pull/1070 there is some Elm code which initializes the chart even if the `view` is not fully rendered yet (this resolves the issue when switching between tabs)

Fixes #27370: Dashboard will not display charts when switching between bechmarks

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/Authorizations.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/ApiAuthorization.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/UserManagementApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/users/RudderUserDetailsFile.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/users/User.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/users/UserManagement.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/users/UserManagementService.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TraitTestApiFromYamlFiles.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala

https://issues.rudder.io/issues/26767
For the Api account, the token is already redacted, we need the same for the user password : add a dedicated structure.
There are some sub-types, and we can avoid invalid representations (empty password, and secret unhashed password was used in the same `String` field)

Fixes #26767: 

---

webapp/sources/rudder/rudder-core/src/main/resources/reportsSchema.sql
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/CampaignEventRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/CampaignHooksService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/CampaignRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/DataTypes.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/MainCampaignService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/hooks/RunHooks.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PolicyWriterService.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/hooks/HooksTest.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/CampaignApi.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/CampaignApiTest.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/earlyconfig/db/TestMigrateTableCampaignEvents.scala

https://issues.rudder.io/issues/26883
Create the `CampaignHooksService` and the corresponding step in campaign workflow and persistence in base. 
There is no unit tests, they will be added after https://github.com/Normation/rudder/pull/6555 make them easier to code. 
So, the main thing is the addition of: 
That adds a service that run campaign related hooks, which are located on FS along with other Rudder hooks. The difference is that for these ones, each campaign can have different hooks and so, under the `.../hook.d/campaign/` directoty, there is one directoty for each campaign with its subdirectories for `pre-hooks` and `post-hooks`. 
- `CampaignHooksRepository` allows to create and delete the relevant directories when a campaign is created/deleted. 
- `CampaignHooksService`: the hook …

Fixes #26883: Add campaign hooks in the campaign workflow engine

---

Cargo.lock
deny.toml
policies/Dockerfile
policies/module-types/augeas/Cargo.toml
policies/module-types/augeas/src/augeas.rs
policies/module-types/augeas/src/dsl/parser.rs
policies/module-types/inventory/Cargo.toml
policies/module-types/system-updates/Cargo.toml
policies/rudder-commons/Cargo.toml
policies/rudder-commons/src/lib.rs
policies/rudderc/Cargo.toml
policies/rudderc/src/ir/value.rs
policies/rudderc/src/lib.rs
relay/sources/relayd/Cargo.toml
relay/sources/relayd/Dockerfile
relay/sources/relayd/src/api.rs
relay/sources/relayd/src/api/remote_run.rs
relay/sources/relayd/tests/common/mod.rs
relay/sources/rudder-package/Cargo.toml
relay/sources/rudder-package/Dockerfile
relay/sources/rudder-package/src/archive.rs
relay/sources/rudder-package/src/dependency.rs
relay/sources/rudder-package/src/list.rs
relay/sources/rudder-package/src/webapp.rs
rust-toolchain.toml
sbom/Dockerfile

https://issues.rudder.io/issues/27404
For `quick-xml`:
* https://github.com/tafia/quick-xml/pull/766: BytesText::unescape and BytesText::unescape_with replaced by BytesText::decode. Now Text events does not contain escaped parts which are reported as Event::GeneralRef. (https://github.com/tafia/quick-xml/blob/master/Changelog.md#0380----2025-06-28)
For the HTTP stack:
* https://seanmonstar.com/blog/warp-v04/
* https://hyper.rs/guides/1/upgrading/
For now I'm pointing to my fork of warp but will switch back once a fix is merged.

Fixes #27404: Finish Rust dependency update

---

policies/rudder-module-type/src/cfengine/log.rs

https://issues.rudder.io/issues/27450
CFEngine offers multiple [log levels](https://docs.cfengine.com/docs/3.26/reference-promise-types.html#log_priority). The `info` level previously used in our macro is intended to be used only in [enforce mode](https://github.com/cfengine/core/blob/37e62318b14c9b581fea20b0f02b069b758223ac/libpromises/mod_custom.c#L1039). The `rudder_info!` macro will now use the `notice` priority level to retain the same semantics while avoiding CFEngine errors when running in audit mode.

Fixes #27450: Fix the rudder_info! macro to make it usable in audit mode

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/properties/Properties.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/nodes/GenericPropertiesTest.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateOrUpdateGlobalParameterPopup.scala

https://issues.rudder.io/issues/26718
The error : 
* no longer has a stack trace
* has a the generic action message fixed ("create"/"update" parameter)
* still has the parsing error message
Result :

Fixes #26718: When the JSON property is invalid in global properties, the error is nasty

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/facts/nodes/NodeFact.scala

https://issues.rudder.io/issues/27112
It's just adding the filter at the correct place, so that the IP is not shown in node list but kept elsewhere:

Fixes #27112: Hosts table contains local ipv6 address

---

webapp/sources/api-doc/code_samples/curl/groups/tree.sh
webapp/sources/api-doc/components/schemas/directive-tree.yml
webapp/sources/api-doc/openapi.src.yml
webapp/sources/api-doc/paths/directives/tree.yml
webapp/sources/api-doc/paths/groups/tree.yml
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/GroupsApi.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_groups.yml

https://issues.rudder.io/issues/27486
Reusing the existing parameter extractor (used in the directives tree).
The filtering is also very similar, see https://github.com/Normation/rudder/blob/cd64fe5017654f3a988080d0c3fb2d6cc5bbc915/webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/DirectiveApi.scala#L280-L288

Fixes #27486: Add includeSystem parameter to filter system groups in API

---

webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/test-migrate-select/1.0/metadata.xml
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/test-migrate-select/1.0/technique.cf
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/test-migrate-select/1.0/technique.ps1
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/test-migrate-select/1.0/technique.yml
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_directives.yml
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_techniques.yml
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/ArchiveApiTest.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/endconfig/migration/MigrateDirectiveWithSelectInputBroken.scala
webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/endconfig/migration/TestMigrateDirectiveWithSelectInputBroken.scala

https://issues.rudder.io/issues/27428
The migration check technique with a select parameter, then get all technique based on this directive, then check if the directives has a parameter using the name of a technique parameter (instead of an id) and if the name is used, remove it and add a parameter with the id of the technique parameter with previous value

Fixes #27428: Missing migration for existing directives with the bad select input identifier

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder-datatable.js
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-main.scss

https://issues.rudder.io/issues/27577
CSP does not supports the `onclick` which added the `toggle` class to collapse the JSON property :
:arrow_right: instead use the [collapse](https://getbootstrap.com/docs/5.3/components/collapse/) from Bootstrap 5, and override some of it's SCSS (to prevent completely hiding the collapsed element)

Fixes #27577: Nodes table has CSP error with column containing JSON property

---

webapp/sources/pom.xml

https://issues.rudder.io/issues/27638
I don't think it breaks anything in CI/etc, but I will happily use a second sight on that. 
Moving to `compile` allows to have a quick(er at least) css compilation, which is needed to have correct resources with the rudder version correctly replaced, which is not the case after a `mvn clean` and a pur intellij compilation.

Fixes #27638: Scala compilation should happen in maven compile phase

---

policies/lib/tree/30_generic_methods/user_password_hash.cf

https://issues.rudder.io/issues/27622

Fixes #27622: Password setting from standard user technique fails after upgrade to Rudder 9.0 Beta 2

---

webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/campaigns/hook-template
webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/campaigns/readme.adoc
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/CampaignEventRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/CampaignHooksService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/CampaignOrchestrationLogic.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/DataTypes.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/hooks/RunHooks.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/campaign/CampaignOrchestrationLogicTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/hooks/HooksTest.scala

https://issues.rudder.io/issues/27574
This commit handle one annoyance and a semantic change for campaign hooks:
- add clearer logs in case of warning or error with the corresponding log level and faulty script
- we always go to `post-hooks`, even if `pre-hooks` failed, so that we let user a chance to correct state changed in `pre-hooks`
Now, when a campaign hook fails or warn, it has a corresponding line in webapp logs: 
```
2025-10-03 22:40:58+0200 ERROR hooks.campaigns.1bb22fc5-f41c-46fb-a44b-54b68b8254f2.pre-hooks - Campaign 'test campaign' pre-hooks returned code '24' in 'test-hook.sh'
```
This needed some adaptation: 
- also keep hook names in the history from `RunHooks.asyncRunHistory`
- post process campaign hook history execution to log to correct level
The idea here is that is …

Fixes #27574: Post-hooks for campaigns should be executed even even if pre-hooks are in failure

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-directives.scss

https://issues.rudder.io/issues/24486
Result :

Fixes #24486: The migrate button in directive pages is always displayed and often useless and ugly

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder.js
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-node.scss

https://issues.rudder.io/issues/27596
The multiple JS errors were caused by the line `$(“pre”).remove();` which was attemptng to remove all <pre> tags from the page, including those from the Elm app.

Fixes #27596: Multiple JS error on properties page
