Normation/rudder

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/model/DirectiveFieldEditors.scala

https://issues.rudder.io/issues/23283
YAML technique doc:

Fixes #23283: Improve password hash scheme names

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/api/ApiAccountRepository.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/action/CreateSystemToken.scala

https://issues.rudder.io/issues/23291

Fixes #23291: Use constant time comparison for system token

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/View.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/ViewUtils.elm

https://issues.rudder.io/issues/23182

Fixes #23182: Node property name is reset to the previous value when editing the value on creation

---

webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-technique-editor.css

https://issues.rudder.io/issues/23170
Replacing previous PR: https://github.com/Normation/rudder/pull/4988

Fixes #23170: Inconsitency background color in generic method section in technique editor

---

webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechnique.elm

https://issues.rudder.io/issues/23256

Fixes #23256: Error when we try to save a draft with a missing parameter name in technique editor

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/QuickSearch/View.elm
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-quicksearch.css

https://issues.rudder.io/issues/23342

Fixes #23342: In quicksearch window, Warning message "please refine your query" is displayed even if there is less than 10 results

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/FileManager/Action.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/FileManager/Env.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/FileManager/Model.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/FileManager/Update.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/FileManager/View.elm
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-filemanager.css

https://issues.rudder.io/issues/23349

Fixes #23349: Allow to edit files in file manager

---

policies/rudderc/src/backends/metadata.rs
policies/rudderc/tests/cases/general/escaping/metadata.xml
policies/rudderc/tests/cases/general/form/metadata.xml
policies/rudderc/tests/cases/general/ntp/metadata.xml

https://issues.rudder.io/issues/23334

Fixes #23334: Move "technique parameters" section at the beginning

---

policies/rudderc/src/backends/windows.rs
policies/rudderc/templates/technique.ps1.askama
policies/rudderc/tests/cases/general/long_method_param_name/metadata.xml
policies/rudderc/tests/cases/general/long_method_param_name/technique.cf
policies/rudderc/tests/cases/general/long_method_param_name/technique.ps1
policies/rudderc/tests/cases/general/long_method_param_name/technique.yml
policies/rudderc/tests/lib/common/30_generic_methods/report_if_condition.cf

https://issues.rudder.io/issues/23341

Fixes #23341: Rudderc transform some method parameter name in an incorrect manner

---

webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-quicksearch.css

https://issues.rudder.io/issues/23345

Fixes #23345: In the quicksearch window, the link for a result is not applied to the entire line

---

webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-main.css

https://issues.rudder.io/issues/23196

Fixes #23196: Inconsistent color of save button in directives

---

relay/arch-doc/rudder-8-policy-synchronization.md

https://issues.rudder.io/issues/22589

Fixes #22589: Arch doc for policy update

---

webapp/sources/pom.xml
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/Authorizations.scala

https://issues.rudder.io/issues/23364

Fixes #23364: Update scala dependencies before beta

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/23361

Fixes #23361: First regenerate methods then migrate to yaml

---

policies/rudderc/src/ir/technique.rs

https://issues.rudder.io/issues/23380

Fixes #23380: Rudderc silently accept unknown parameter constraints

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateCategoryOrGroupPopup.scala

https://issues.rudder.io/issues/2677

Fixes #2677: When I enter the "Create a new item" popup to create a group the default field should be Name

---

policies/rudderc/src/ir/value.rs

https://issues.rudder.io/issues/23377

Fixes #23377: rudderc parses ncf_const.s as const.s

---

relay/sources/relayd/src/data/shared_file.rs

https://issues.rudder.io/issues/23392

Fixes #23392: Allow underscore in file_id in shared-files

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/ViewTabContent.elm

https://issues.rudder.io/issues/23394

Fixes #23394: Elm webapp build is broken in 8.0

---

policies/Cargo.lock
policies/Cargo.toml
policies/_typos.toml
policies/minifusion/Cargo.toml
policies/minifusion/README.md
policies/minifusion/src/main.rs
policies/minifusion/src/os_release.rs
policies/minifusion/src/packages.rs
policies/minifusion/src/packages/rpm.rs
policies/minifusion/src/packages/yum.rs
policies/minifusion/src/properties.rs
policies/minifusion/tools/example-minifusion.xml
policies/minifusion/tools/example.xml
policies/supply-chain/audits.toml
policies/supply-chain/config.toml
policies/supply-chain/imports.lock

https://issues.rudder.io/issues/23033

Fixes #23033: PoC for a minimal inventory engine

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/db/Doobie.scala

https://issues.rudder.io/issues/23414
Our SQL logger need to be given to the transactor initialisation to be taken into account.

Fixes #23414: SQL logger is never called

---

webapp/sources/pom.xml
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryFileWatcher.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/nodes/NodeInfoServiceCachedTest.scala

https://issues.rudder.io/issues/23417

Fixes #23417: Upgrade to scala 2.13.12

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder-datatable.js

https://issues.rudder.io/issues/23427

Fixes #23427: Tables in Rudder UI are sorted alphabetically but should also follow a numerical sort - nodes page

---

webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample

https://issues.rudder.io/issues/23461

Fixes #23461: Missing new historical inventory clean-up properties in config file

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/View.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/ViewUtils.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Nodeproperties.elm
webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder.js
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-datatable.css
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-main.css
webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/techniqueEditor.html

https://issues.rudder.io/issues/23401

Fixes #23401: Node property webpage makes it hard to uses JSON based properties

---

webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-finished/50-reload-policy-file-server

https://issues.rudder.io/issues/23464

Fixes #23464: adapt policy generation hooks to prevent automatic update of policies for each rudder command

---

policies/rudderc/src/backends/metadata.rs
policies/rudderc/tests/cases/general/ntp/metadata.xml
policies/rudderc/tests/cases/general/reporting/metadata.xml
policies/rudderc/tests/metadata/serialized.xml

https://issues.rudder.io/issues/23477

Fixes #23477: Add block id in metadata.xml

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/View.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/ViewUtils.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Nodeproperties.elm

https://issues.rudder.io/issues/23454
We need to check whether the properties are inherited or not. If they are, we can then replace their value.

Fixes #23454: Cannot override global property in Rudder 8.0 beta 3

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/JsonDecoder.elm

https://issues.rudder.io/issues/23472
We were not decoding the result of the query correctly

Fixes #23472: error when create, modify or delete a properties on group

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueCompiler.scala

https://issues.rudder.io/issues/23479

Fixes #23479: Unable to save a technique resource through the file manager

---

webapp/sources/rudder/rudder-web/src/main/elm/elm.json
webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/View.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/ViewUtils.elm
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-main.css

https://issues.rudder.io/issues/23404
**Before**
**After**

Fixes #23404: Node properties are lacking JSON syntax highlighting

---

webapp/sources/pom.xml

https://issues.rudder.io/issues/23495

Fixes #23495: Update jgit to remove CVE-2023-4759 error message

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor.elm

https://issues.rudder.io/issues/23483
I had to resort to file extension, there does not seem to be usable media type for yaml files...

Fixes #23483: import technique doesn't show yaml files

---

webapp/sources/api-doc/components/schemas/campaign-details.yml
webapp/sources/api-doc/components/schemas/campaign-event-details.yml

https://issues.rudder.io/issues/23501

Fixes #23501: Add an enum for campaign type in post request

---

webapp/sources/rudder/rudder-web/src/main/style/rudder/datepicker.css
webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/apiManagement.html

https://issues.rudder.io/issues/23268
Not perfect, but better than before, and probably not blocking anymore.

Fixes #23268: Calendar in token api creation is broken

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTechnique.elm

https://issues.rudder.io/issues/23484

Fixes #23484: LanguageTools module can prevent Yaml editor from extending

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/yaml/YamlTechnique.scala

https://issues.rudder.io/issues/23490

Fixes #23490: Disable reporting option is ignored by the technique editor

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Nodeproperties.elm

https://issues.rudder.io/issues/23496

Fixes #23496: Editing and renaming a group property results in duplicate property

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/ViewUtils.elm

https://issues.rudder.io/issues/23473
I removed custom json type to use elm one.
I  also used value in sort and not the name

Fixes #23473: surprising ordering on values for properties

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/View.elm

https://issues.rudder.io/issues/23405

Fixes #23405: Node property webpage does not give any tips on how to use the properties

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/FileManager/View.elm
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-filemanager.css

https://issues.rudder.io/issues/23512

Fixes #23512: Thumbnail are not available for all type of file in resource editor

---

relay/sources/rudder-pkg/lib/rudder-pkg/plugin.py

https://issues.rudder.io/issues/23524

Fixes #23524: rudder package should not totally fail when parsing index if one entry

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Nodeproperties.elm

https://issues.rudder.io/issues/23514

Fixes #23514: Changing group property value displays spurious “renamed” message

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/ViewUtils.elm

https://issues.rudder.io/issues/23517

Fixes #23517: String node poperties are displayed in quotes

---

policies/rudderc/src/logs.rs
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueCompiler.scala

https://issues.rudder.io/issues/23536

Fixes #23536: Ansi color escape code in captured rudderc output

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/CampaignEventRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/MainCampaignService.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala

https://issues.rudder.io/issues/22527
quick comment:
main change is to update get function in repository to get an option and not directly a campaign event. The fix is made by handling the option.

Fixes #22527: PostgreSQL error doobie.util.invariant$UnexpectedEnd$ 

---

policies/rudderc/src/backends/metadata.rs
policies/rudderc/tests/cases/general/escaping/metadata.xml
policies/rudderc/tests/cases/general/form/metadata.xml
policies/rudderc/tests/cases/general/ntp/metadata.xml

https://issues.rudder.io/issues/23544
What is called technique parameter `name` is actually the parameter ID

Fixes #23544: Parameter name in metadata.xml should be its id

---

policies/rudderc/src/backends/metadata.rs
policies/rudderc/tests/cases/general/escaping/metadata.xml
policies/rudderc/tests/cases/general/form/metadata.xml
policies/rudderc/tests/cases/general/ntp/metadata.xml

https://issues.rudder.io/issues/23545

Fixes #23545: Parameter name in metadata.xml should be its uppercased id

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/EditorTechnique.scala

https://issues.rudder.io/issues/23546

Fixes #23546: Migration of techniques is failling when there is a resource.

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/ViewUtils.elm

https://issues.rudder.io/issues/23553

Fixes #23553: Override process of properties is very misleading at node level

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/EditorTechnique.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/migration/MigrateJsonTechniquesService.scala

https://issues.rudder.io/issues/23558

Fixes #23558: Wrong alias done when migrating technique resource

---

webapp/sources/rudder/rudder-web/src/main/resources/logback.xml

https://issues.rudder.io/issues/23525

Fixes #23525: Document in logback.xml loggers that display secret at debug level 

---

webapp/sources/dependency-check-suppression.xml

https://issues.rudder.io/issues/23574

Fixes #23574: Ignore CVE 2023-4759 (false positive in jgit 6.7.0.202309050840-r)

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/DirectiveCompliance/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/DirectiveCompliance/Init.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/DirectiveCompliance/ViewNodesCompliance.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/DirectiveCompliance/ViewRulesCompliance.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Directivecompliance.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/Init.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/ViewTabContent.elm

https://issues.rudder.io/issues/23539

Fixes #23539: Compliance filter should be shared between the different tables of a same interface

---

policies/rudderc/templates/technique.ps1.askama
policies/rudderc/tests/cases/general/escaping/metadata.xml
policies/rudderc/tests/cases/general/escaping/technique.cf
policies/rudderc/tests/cases/general/escaping/technique.ps1
policies/rudderc/tests/cases/general/escaping/technique.yml
policies/rudderc/tests/cases/general/min/technique.ps1
policies/rudderc/tests/cases/general/reporting/technique.ps1

https://issues.rudder.io/issues/23579

Fixes #23579: Broken double quote escaping in Windows policies

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/EditorTechnique.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueCompiler.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/migration/MigrateJsonTechniquesService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/yaml/YamlTechnique.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestEditorTechniqueWriter.scala
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/AgentValueParser.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/JsonEncoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTechniqueTabs.elm
webapp/sources/rudder/rudder-web/src/test/resources/configuration-repository-migrate-json-8_0/post-migration/ncf_techniques/technique_with_parameters/1.0/technique.yml

https://issues.rudder.io/issues/23586

Fixes #23586: Missing UI for parameter name and description new format

---

policies/rudderc/src/ir/value.rs

https://issues.rudder.io/issues/23583

Fixes #23583: Broken parsing of some complex expressions

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTechnique.elm

https://issues.rudder.io/issues/23590

Fixes #23590: Remove old parameter check

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PluginManagement.scala

https://issues.rudder.io/issues/23592

Fixes #23592: Typo in warning message

---

Jenkinsfile
webapp/sources/Dockerfile

https://issues.rudder.io/issues/23486

Fixes #23486: Add a test on JDK21

---

webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechnique.elm

https://issues.rudder.io/issues/17813

Fixes #17813: user with read_only right has button that allows to create a technique

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala
webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/directiveManagement.html

https://issues.rudder.io/issues/23172

Fixes #23172: Improve deleted directive screen

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala

https://issues.rudder.io/issues/23618
for consistency with https://github.com/Normation/rudder/pull/4953

Fixes #23618: Rename "Parameters" menu entry to "Global properties"

---

relay/sources/rudder-package/src/rpkg/archive.rs
relay/sources/rudder-package/src/rpkg/database.rs
relay/sources/rudder-package/src/rpkg/mod.rs
relay/sources/rudder-package/src/rpkg/plugin.rs
relay/sources/rudder-package/src/rpkg/repo_index.rs
relay/sources/rudder-package/src/rpkg/webapp_xml.rs

https://issues.rudder.io/issues/23624

Fixes #23624: Continue implementing the installation part of the rudder-package rust port

---

Jenkinsfile
Jenkinsfile-security
relay/sources/rudder-package/Cargo.lock
relay/sources/rudder-package/Cargo.toml
relay/sources/rudder-package/Dockerfile
relay/sources/rudder-package/Makefile
relay/sources/rudder-package/deny.toml
relay/sources/rudder-package/rust-toolchain.toml
relay/sources/rudder-package/src/main.rs
relay/sources/rudder-package/src/rpkg/archive.rs
relay/sources/rudder-package/src/rpkg/database.rs
relay/sources/rudder-package/src/rpkg/repo_index.rs
relay/sources/rudder-package/src/rpkg/webapp_xml.rs

Code changes are done according to cargo check/clippy.
https://issues.rudder.io/issues/23625

Fixes #23625: Implement CI config for rudder-package

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder-datatable.js

https://issues.rudder.io/issues/23535

Fixes #23535: On the nodes list, the filter does not work on property based column

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchBackendImpl.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchDomain.scala

https://issues.rudder.io/issues/22516

Fixes #22516: Search bar doesn't work for group properties

---

relay/sources/rudder-package/src/cli.rs
relay/sources/rudder-package/src/config.rs
relay/sources/rudder-package/src/lib.rs

https://issues.rudder.io/issues/23632

Fixes #23632: Add configuration file path to the cli args

---

webapp/sources/api-doc/code_samples/curl/openscap/report.sh
webapp/sources/api-doc/openapi.src.yml
webapp/sources/api-doc/paths/openscap/report.yml

https://issues.rudder.io/issues/23645

Fixes #23645: Add doc for OpenSCAP plugin API

---

api-doc/.redocly.lint-ignore.yaml
api-doc/package-lock.json
api-doc/package.json

https://issues.rudder.io/issues/23651

Fixes #23651: Update api doc tooling

---

qa-test
relay/sources/api-doc/code_samples/curl/shared-folder/get.sh
webapp/sources/api-doc/code_samples/curl/archives/export.sh
webapp/sources/api-doc/code_samples/curl/branding/update.sh
webapp/sources/api-doc/code_samples/curl/directives/create.sh
webapp/sources/api-doc/code_samples/curl/directives/update.sh
webapp/sources/api-doc/code_samples/curl/groups/category-id-new.sh
webapp/sources/api-doc/code_samples/curl/groups/create.sh
webapp/sources/api-doc/code_samples/curl/nodes/id-update.sh
webapp/sources/api-doc/code_samples/curl/scale-out-relay/promote.sh
webapp/sources/api-doc/code_samples/curl/systemUpdate/campaignEventResult.sh

https://issues.rudder.io/issues/23653

Fixes #23653: Lint shell code examples

---

webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechniqueTabs.elm

https://issues.rudder.io/issues/23611

Fixes #23611: In technique editor, the "Name" field appears to be optional, whereas it is not.

---

webapp/sources/rudder/rudder-web/pom.xml
webapp/sources/rudder/rudder-web/src/main/elm/elm.json

https://issues.rudder.io/issues/23666

Fixes #23666: Fix elm tests

---

webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/ruleManagement.html

https://issues.rudder.io/issues/23612

Fixes #23612: The tooltip in the compliance bar does not appear when the mouse is hovered over it

---

webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/parameterManagement.html

https://issues.rudder.io/issues/23661

Fixes #23661: Rename the "parameters" in "global properties" in the whole page

---

policies/rudderc/docs/src/usage.md

https://issues.rudder.io/issues/23674

Fixes #23674: Incorrect rudderc binary download link in documentation

---

policies/rudderc/src/backends/unix/cfengine.rs

https://issues.rudder.io/issues/23686

Fixes #23686: Make the library path passed to CFEngine absolute

---

policies/rudderc/docs/src/syntax.md
policies/rudderc/docs/src/usage.md

https://issues.rudder.io/issues/23689

Fixes #23689: Fix doc for techniques import

---

relay/sources/rudder-package/Cargo.lock
relay/sources/rudder-package/Cargo.toml
relay/sources/rudder-package/src/config.rs
relay/sources/rudder-package/src/lib.rs
relay/sources/rudder-package/src/repository.rs
relay/sources/rudder-package/tests/hash/poem.txt

https://issues.rudder.io/issues/23690

Fixes #23690: Add a downloader for files from plugin repository

---

webapp/sources/api-doc/components/parameters/include.yml

https://issues.rudder.io/issues/23441

Fixes #23441: rudder node api documentation doesn't mention the softwareUpdate

---

relay/sources/rudder-package/Cargo.lock
relay/sources/rudder-package/Cargo.toml
relay/sources/rudder-package/src/lib.rs
relay/sources/rudder-package/src/versions.rs

https://issues.rudder.io/issues/23687

Fixes #23687: Add version parsing to rudder-package

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ArchiveApi.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/ArchiveApiTest.scala

https://issues.rudder.io/issues/23655
So, there were two main problems: 
- we were throwing the `NoSuchFileException` when deleting a file that was not here while it's convergent and we should not, 
- but just correcting would have hidden the real problem: in `zip`, directories are not stored, so we never have them, so in the diff they are always marked as deleted. We need to filter out directories in the `Files.walk`
Clean-up:
- also factored-out the code responsible for making the diff so that I was able to write a unit test just on that part (the new test was failing before the fix). 
- make `trace` log a little better for the deletion (display `none` if nothing is deleted)

Fixes #23655: Import archive does not support technique upgrade

---

relay/sources/rudder-package/src/database.rs
relay/sources/rudder-package/src/plugin.rs
relay/sources/rudder-package/src/repo_index.rs
relay/sources/rudder-package/src/versions.rs
relay/sources/rudder-package/tests/database/plugin_database_update_sample.json.expected

https://issues.rudder.io/issues/23695

Fixes #23695: rudder-package should stroingly type any plugin version

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/migration/MigrateEventLogEnforceSchema.scala

https://issues.rudder.io/issues/23699
COALESCE on the whole table takes a looooong time. An update to remove all null before modifying the column should be enough

Fixes #23699: Event log migration takes too long

---

policies/rudderc/docs/src/test.md
policies/rudderc/src/lib.rs
policies/rudderc/src/test.rs
policies/rudderc/tests/cases/test/one_param/tests/case1.yml

https://issues.rudder.io/issues/23703

Fixes #23703: Add a cleanup step to techniques tests

---

policies/rudderc/src/backends/unix.rs
policies/rudderc/src/backends/unix/ncf/method_call.rs
policies/rudderc/tests/cases/general/escaping/technique.cf
policies/rudderc/tests/cases/general/form/technique.cf
policies/rudderc/tests/cases/general/long_method_param_name/technique.cf
policies/rudderc/tests/cases/general/min/technique.cf
policies/rudderc/tests/cases/general/ntp/technique.cf
policies/rudderc/tests/cases/general/reporting/technique.cf

https://issues.rudder.io/issues/23718

Fixes #23718: Bundle name collision with cloned techniques

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeCompliance/ApiCalls.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeCompliance/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeCompliance/Init.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeCompliance/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeCompliance/View.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeCompliance/ViewUtils.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Nodecompliance.elm
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala
webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/node.html

https://issues.rudder.io/issues/23656

Fixes #23656: Rewrite Nodes compliance table in Elm

---

webapp/sources/rudder/rudder-core/src/test/scala/com/normation/JsonSpecMatcher.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TraitTestApiFromYamlFiles.scala

https://issues.rudder.io/issues/23756
I should not have used `^^` because it returns a generic `Matcher[T]` instead of an `EqualityMatcher[T]`, this suppressed the _Click to see difference_ button in IntelliJ...

Fixes #23756: Comparison json should allow to display json diff

---

webapp/sources/pom.xml

https://issues.rudder.io/issues/23758

Fixes #23758: Update Scala dependencies

---

relay/sources/rudder-package/src/archive.rs

https://issues.rudder.io/issues/23759

Fixes #23759: Make rudder-package able to track installed files

---

webapp/sources/pom.xml
webapp/sources/rudder/rudder-core/pom.xml

https://issues.rudder.io/issues/23761

Fixes #23761: Update graalvm dependency

---

policies/Cargo.lock
policies/Dockerfile
policies/_typos.toml
policies/rudderc/Cargo.toml
policies/rudderc/docs/src/test.md
policies/rudderc/docs/src/usage.md
policies/rudderc/src/backends/unix/cfengine.rs
policies/rudderc/src/backends/windows.rs
policies/rudderc/src/backends/windows/test.rs
policies/rudderc/src/cli.rs
policies/rudderc/src/lib.rs
policies/rudderc/src/test.rs
policies/rudderc/templates/test-directive.ps1.askama
policies/rudderc/templates/test.ps1.askama
policies/rudderc/tests/cases/general/ntp/metadata.xml
policies/rudderc/tests/cases/test/one_param_windows/technique.yml
policies/rudderc/tests/cases/test/one_param_windows/tests/case1.yml
policies/rudderc/tests/cases/test/one_param_windows/tests/case2.yml
policies/rudderc/tests/export.rs
policies/rudderc/tests/test.rs
policies/supply-chain/audits.toml
policies/supply-chain/imports.lock

https://issues.rudder.io/issues/23763
Still to be tested on Windows.

Fixes #23763: Improve techniques tests

---

relay/sources/rudder-package/src/archive.rs
relay/sources/rudder-package/src/cli.rs
relay/sources/rudder-package/src/database.rs
relay/sources/rudder-package/src/lib.rs
relay/sources/rudder-package/src/versions.rs
relay/sources/rudder-package/tests/versions/rudder-server-version

https://issues.rudder.io/issues/23767

Fixes #23767: Make an install subcommand for the new rudder-package

---

relay/sources/rudder-package/src/lib.rs
relay/sources/rudder-package/src/webapp_xml.rs

https://issues.rudder.io/issues/23769

Fixes #23769: Restart the webapp after plugin installation

---

relay/sources/rudder-package/src/lib.rs
relay/sources/rudder-package/src/webapp_xml.rs

https://issues.rudder.io/issues/23771

Fixes #23771: Stop rudder-package if not run as root

---

relay/sources/rudder-package/src/archive.rs
relay/sources/rudder-package/src/lib.rs
relay/sources/rudder-package/src/repo_index.rs
relay/sources/rudder-package/src/repository.rs

https://issues.rudder.io/issues/23772

Fixes #23772: Make rudder-package able to install plugins from the repository

---

policies/rudderc/src/backends/windows.rs
policies/rudderc/templates/technique.ps1.askama
policies/rudderc/tests/cases/general/ntp/technique.ps1

https://issues.rudder.io/issues/23777

Fixes #23777: Fix resources_dir definition on Windows

---

relay/sources/rudder-package/src/lib.rs
relay/sources/rudder-package/src/repository.rs

https://issues.rudder.io/issues/23776

Fixes #23776: Add signature validation for plugins

---

relay/sources/rudder-package/Cargo.lock
relay/sources/rudder-package/Cargo.toml
relay/sources/rudder-package/src/cli.rs
relay/sources/rudder-package/src/lib.rs
relay/sources/rudder-package/src/repository.rs

https://issues.rudder.io/issues/23782

Fixes #23782: Make rudder-package able to download plugin licenses

---

policies/rudderc/src/backends/unix/cfengine.rs
policies/rudderc/src/backends/windows/test.rs
policies/rudderc/src/test.rs

https://issues.rudder.io/issues/23788

Fixes #23788: tests output should be displayed even if not valid utf-8

---

policies/rudderc/src/lib.rs

https://issues.rudder.io/issues/23787

Fixes #23787: rudderc export should use category from technique if existing

---

relay/sources/rudder-package/src/cli.rs
relay/sources/rudder-package/src/lib.rs
relay/sources/rudder-package/src/webapp.rs

https://issues.rudder.io/issues/23791

Fixes #23791: Add enable/disable commands to rudder-package

---

relay/sources/rudder-package/README.md

https://issues.rudder.io/issues/23793

Fixes #23793: Document the rpkg format

---

webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/history/HistoryLogRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/git/GitItemRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/hooks/RunHooks.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/InterpolatedValueCompiler.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/nodeconfig/NodeConfigurationCacheRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/NodeConfigurationService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ArchiveApi.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechniqueList.elm
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/migration/CheckAddSpecialTargetAllPolicyServers.scala
webapp/sources/scala-ldap/src/main/scala/com/normation/ldap/ldif/LDIFFileLogger.scala
webapp/sources/scala-ldap/src/main/scala/com/normation/ldap/sdk/LDAPEntry.scala

https://issues.rudder.io/issues/23800

Fixes #23800: Fix typos in error message in technique editor

---

policies/rudderc/src/lib.rs
policies/rudderc/src/test.rs
policies/rudderc/tests/cases/test/one_param_unix/tests/case2.yml

https://issues.rudder.io/issues/23807

Fixes #23807: Add an env var pointing to reports test file

---

policies/rudderc/docs/src/test.md

https://issues.rudder.io/issues/23810

Fixes #23810: Improve docs for techniques testing

---

webapp/sources/rudder/rudder-web/src/main/package-lock.json

https://issues.rudder.io/issues/23825

Fixes #23825: Update js dependencies

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder.js
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala

https://issues.rudder.io/issues/23819

Fixes #23819: Sometimes, tooltips in the directives tree remain displayed

---

policies/rudderc/src/backends/unix.rs
policies/rudderc/src/backends/unix/ncf.rs
policies/rudderc/src/backends/unix/ncf/dry_run_mode.rs
policies/rudderc/src/backends/unix/ncf/method_call.rs
policies/rudderc/src/backends/windows.rs
policies/rudderc/tests/cases/general/policy_mode/metadata.xml
policies/rudderc/tests/cases/general/policy_mode/technique.cf
policies/rudderc/tests/cases/general/policy_mode/technique.ps1
policies/rudderc/tests/cases/general/policy_mode/technique.yml

https://issues.rudder.io/issues/23835

Fixes #23835: Do the same for Blocks

---

webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/techniqueEditor.html

https://issues.rudder.io/issues/23475

Fixes #23475: Technique saving is blocked because of localstorage of drafts

---

policies/rudderc/docs/src/SUMMARY.md
policies/rudderc/docs/src/installation.md
policies/rudderc/docs/src/syntax.md
policies/rudderc/docs/src/test.md
policies/rudderc/docs/src/usage.md

https://issues.rudder.io/issues/23839

Fixes #23839: Document the policy_mode in yaml rudderc documentation

---

webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-technique-editor.css

https://issues.rudder.io/issues/23588

Fixes #23588: In Technique Editor, the quicksearch window still  appears behind the navigation menu

---

relay/sources/Makefile
relay/sources/rudder-package/Cargo.lock
relay/sources/rudder-package/Cargo.toml
relay/sources/rudder-package/src/cli.rs
relay/sources/rudder-package/src/config.rs
relay/sources/rudder-package/src/info.rs
relay/sources/rudder-package/src/lib.rs
relay/sources/rudder-package/src/license.rs
relay/sources/rudder-package/src/list.rs
relay/sources/rudder-package/src/plugin.rs
relay/sources/rudder-package/src/repo_index.rs
relay/sources/rudder-package/src/repository.rs
relay/sources/rudder-relay-postinst
relay/sources/systemd/rudder-package.service
relay/sources/systemd/rudder-package.timer
relay/sources/systemd/rudder-relayd-hardening
relay/sources/systemd/rudder-relayd.service

https://issues.rudder.io/issues/23838

Fixes #23838: Update rudder-package cli for better UX

---

api-doc/package-lock.json
api-doc/package.json
api-doc/redocly.yml

https://issues.rudder.io/issues/23860

Fixes #23860: Update API doc tooling

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/EditorTechnique.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueCompiler.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueSerializer.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/migration/MigrateJsonTechniquesService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/yaml/YamlTechnique.scala
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/testing_variables_in_conditions/1.0/technique.cf
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/1.0/technique.cf
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/1.0/technique.ps1
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/1.0/technique.yml
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/2.0/technique.cf
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/2.0/technique.ps1
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/rudder_reporting.cf
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/technique.cf
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/technique.ps1
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/technique.yml
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestEditorTechniqueWriter.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestEditorTechniqueWriterFallback.scala
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/JsonEncoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/MethodElemUtils.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewBlock.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewMethod.elm

https://issues.rudder.io/issues/23815

Fixes #23815: Add policy mode override support to the technique editor

---

webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/services/provisioning/InventorySaver.scala
webapp/sources/ldap-inventory/inventory-provisioning-core/src/main/scala/com/normation/inventory/ldap/provisioning/DefaultInventorySaver.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/scala-ldap/src/main/scala/com/normation/ldap/sdk/LDAPConnection.scala

https://issues.rudder.io/issues/23804
To improve system update plugin i need some dependencies that are not available in the plugin. 
I also need to be able to add post hook to inventory saver so that i can act on inventory save
I also need a new ldap request to filter a tree on some attributes only

Fixes #23804: Add some services available to improve system update performance

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ComplianceApi.scala
webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeCompliance/ApiCalls.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeCompliance/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeCompliance/Init.elm
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/ShowNodeDetailsFromNode.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala

https://issues.rudder.io/issues/23789
Add a parameter to node compliance api to get only system rules
Pass this parameter to api calls of nodecompliance

Fixes #23789: system status tab show normal directives rather than system directives

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewBlock.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewMethod.elm

https://issues.rudder.io/issues/23868

Fixes #23868: Make placeholder test more consistent with others

---

policies/Makefile

https://issues.rudder.io/issues/23909

Fixes #23909: rudder-packages does not build the right Rust project

---

policies/Makefile
policies/rudderc/Makefile

https://issues.rudder.io/issues/23910

Fixes #23910: rudder-packages does not build the right Rust project

---

relay/sources/Makefile

https://issues.rudder.io/issues/23911

Fixes #23911: rudder-packages does not build the right Rust project

---

relay/sources/Makefile

https://issues.rudder.io/issues/23914

Fixes #23914: rudder-pkg.Conf should not be executable

---

policies/rudder-cli/src/logs.rs
relay/sources/rudder-package/src/lib.rs
relay/sources/rudder-package/src/main.rs

https://issues.rudder.io/issues/23865

Fixes #23865: Common style for Rust CLI output

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/ParameterManagement.scala

https://issues.rudder.io/issues/23878

Fixes #23878: Rename the "Create global property" button in "Create"

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Healthcheck.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Healthcheck/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Healthcheck/Init.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Healthcheck/View.elm

https://issues.rudder.io/issues/23916

Fixes #23916: The health check page has an unnecessary "Show check list" button in 8.0

---

webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/directiveManagement.html

https://issues.rudder.io/issues/23877

Fixes #23877: Remove the "Edit techniques" button from the directives webpage

---

policies/rudderc/src/backends/unix/ncf/method_call.rs

https://issues.rudder.io/issues/23940

Fixes #23940: rudderc code is not properly formatted due to a failed resolution of merge

---

webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechniqueTabs.elm

https://issues.rudder.io/issues/23883

Fixes #23883: The "Category" field in the technique editor is displayed as a mandatory field even if it is an unmutable one

---

relay/sources/rudder-package/src/lib.rs

https://issues.rudder.io/issues/23949

Fixes #23949: rudder-package fails to compile in release mode

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/homePage.js
webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder-datatable.js
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/ShowNodeDetailsFromNode.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNodeGroupTree.scala
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-dashboard.css
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-node.scss
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-progress-bar.scss
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/server/server_details.html

https://issues.rudder.io/issues/23854

Fixes #23854: Reorganise the node summary tab

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/ApiAuthorization.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/CurrentUser.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala

https://issues.rudder.io/issues/23920
Explanation are in comment: basically, things are complicated and several tools trying to store things in thread local vars lead to problems.

Fixes #23920: Lift Async system is not able to find spring SecurityContextHolder

---

policies/rudderc/src/lib.rs

https://issues.rudder.io/issues/23941

Fixes #23941: Improve rudderc test error message when no library is passed in the parameters

---

webapp/sources/rudder/rudder-web/src/main/elm/healthcheck/sources/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/healthcheck/sources/Healthcheck.elm
webapp/sources/rudder/rudder-web/src/main/elm/healthcheck/sources/Init.elm
webapp/sources/rudder/rudder-web/src/main/elm/healthcheck/sources/View.elm

https://issues.rudder.io/issues/23891

Fixes #23891: The health check page has an unnecessary "Show check list" button

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/NewNodeManager.scala

https://issues.rudder.io/issues/23955
It's the end of merge of #5284

Fixes #23955: Upmerge collision in rudder 8.1

---

qa-test

https://issues.rudder.io/issues/23980

Fixes #23980: Exclude target dirs in qa-test

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/ViewModals.elm
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-accounts.scss
webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/apiManagement.html

https://issues.rudder.io/issues/23943

Fixes #23943: The API accounts creation and editing popup no longer appears

---

webapp/sources/dependency-check-suppression.xml
webapp/sources/pom.xml

https://issues.rudder.io/issues/23983

Fixes #23983: Unimportant CVE on logback and icu4j

---

webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-main.css
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-template.css

https://issues.rudder.io/issues/23938

Fixes #23938: New campaigns button does not conform to our graphic charter

---

relay/sources/rudder-package/src/database.rs
relay/sources/rudder-package/src/plugin.rs

https://issues.rudder.io/issues/23965

Fixes #23965: rudder package fails to install local rpkg

---

webapp/sources/dependency-check-suppression.xml
webapp/sources/pom.xml

https://issues.rudder.io/issues/23982

Fixes #23982: Unaffected CVE on jgit and logback

---

webapp/sources/dependency-check-suppression.xml

https://issues.rudder.io/issues/24005

Fixes #24005: Ignore CVE-2023-51074 (no impact, score too high)

---

webapp/sources/dependency-check-suppression.xml

https://issues.rudder.io/issues/24008

Fixes #24008: wrong syntax in dependency exception

---

Cargo.lock
policies/minifusion/Cargo.toml
policies/rudder-commons/Cargo.toml
policies/rudderc/Cargo.toml

https://issues.rudder.io/issues/24010

Fixes #24010: Vulnerability in zerocopy crate

---

policies/rudderc/src/backends/windows.rs
policies/rudderc/src/backends/windows/test.rs
policies/rudderc/src/ir/value.rs
policies/rudderc/templates/technique.ps1.askama
policies/rudderc/tests/cases/general/escaping/technique.ps1
policies/rudderc/tests/cases/general/form/technique.ps1
policies/rudderc/tests/cases/general/long_method_param_name/technique.ps1
policies/rudderc/tests/cases/general/min/technique.ps1
policies/rudderc/tests/cases/general/ntp/technique.ps1
policies/rudderc/tests/cases/general/param_in_condition/technique.ps1
policies/rudderc/tests/cases/general/policy_mode/technique.ps1
policies/rudderc/tests/cases/general/reporting/technique.ps1

https://issues.rudder.io/issues/23973

Fixes #23973: 

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/SystemVariableSpecServiceImpl.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/SystemVariableService.scala
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-500-directives/rules/cfengine-community/rudder.json
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-two-directives/rules/cfengine-community/rudder.json
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-gen-var-def-override/rules/cfengine-community/rudder.json
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestComputeSchedule.scala

https://issues.rudder.io/issues/24018

Fixes #24018: AGENT_RUN_STARTTIME is not correctly computed with max delay

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/healthcheck/HealthcheckService.scala

https://issues.rudder.io/issues/24006

Fixes #24006: Healthcheck on file descriptor should be max 64000

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/AcceptNode.scala

https://issues.rudder.io/issues/24025

Fixes #24025: It is not possible to accept or refuse pending nodes.

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala

https://issues.rudder.io/issues/24026

Fixes #24026: Cannot save group after refresh criteria 

---

webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentDirectiveEditForm.html

https://issues.rudder.io/issues/24032
... https://github.com/Normation/rudder/pull/5278/files too bad

Fixes #24032: Directive compliance page loads infinitely again

---

webapp/sources/rudder/rudder-web/src/main/resources/demo-rudder-users.xml

https://issues.rudder.io/issues/24024

Fixes #24024: case-sensitivity parameter of rudder-user.xml is not documented

---

relay/sources/rudder-package/src/archive.rs
relay/sources/rudder-package/src/lib.rs

https://issues.rudder.io/issues/24060

Fixes #24060: script.txz is not scripts.txz

---

webapp/sources/dependency-check-suppression.xml

https://issues.rudder.io/issues/24071

Fixes #24071: Ignore cve on ext-js (unused dependency)

---

relay/sources/rudder-package/src/lib.rs
relay/sources/rudder-package/src/repo_index.rs

https://issues.rudder.io/issues/24072

Fixes #24072: Allow running rudder-package with a malformed index

---

webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ApiCalls.elm
webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Rules.elm

https://issues.rudder.io/issues/24082

Fixes #24082: Missing title for pending change request in rule page

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeCompliance/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeCompliance/Init.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeCompliance/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeCompliance/ViewUtils.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Nodecompliance.elm

https://issues.rudder.io/issues/23930
Fixes https://github.com/Normation/rudder/pull/5281:

Fixes #23930: lost audit/enforce on the node compliance page

---

webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewTabContent.elm

https://issues.rudder.io/issues/24079

Fixes #24079: Fix small ui error in the rules information tab

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewMethodsList.elm
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-technique-editor.css

https://issues.rudder.io/issues/23885

Fixes #23885: Technique editor method filters are not aligned correctly

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ComplianceApi.scala

https://issues.rudder.io/issues/24047
* The computation of policy mode of a rule requires knowing the node ids of the rule. Before, the node ids were re-computed every time even if it had already been... Now, they re-use existing values and save some iterations on collections
* The `nodeFacts` map being a `MapView[NodeId, CoreNodeFact]`, we better store the values we will need in an actual `Map` instead of recomputing from the view every time (e.g. a `Map[NodeId, RudderSettings]`, instead of storing the whole `CodeNodeFact` in memory)

Fixes #24047: Compliance has unoptimized usage of map view and policy mode computation  

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewBlock.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewMethod.elm
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-technique-editor.css
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-template.css

https://issues.rudder.io/issues/24080

Fixes #24080: Improve display of audit/enforce mode in technique editor

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/FileManager/Model.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/FileManager/Update.elm
webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/techniqueEditor.html
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentDirectiveEditForm.html

https://issues.rudder.io/issues/24084

Fixes #24084: 404 not found in technique editor resource manager Ajax query

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules.elm

https://issues.rudder.io/issues/24088

Fixes #24088: Don't do REST call if change request plugin is not enabled

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala

https://issues.rudder.io/issues/24101

Fixes #24101: CSP headers are duplicated and missing report-uri

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/ApiCalls.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/ViewUtils.elm
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-main.css
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-template.css
webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/ruleManagement.html

https://issues.rudder.io/issues/24007

Fixes #24007: when we import an archive and rules contains non existant targets, the targets can't be removed from the rules

---

policies/rudder-commons/src/lib.rs
policies/rudderc/tests/lib/common/30_generic_methods/package_install.yml
policies/rudderc/tests/lib/common/30_generic_methods/package_present.yml

https://issues.rudder.io/issues/24100

Fixes #24100: Missing method constraints in rudderc

---

relay/sources/rudder-package/src/archive.rs
relay/sources/rudder-package/src/lib.rs
relay/sources/rudder-package/src/plugin.rs
relay/sources/rudder-package/src/repo_index.rs
relay/sources/rudder-package/src/versions.rs

https://issues.rudder.io/issues/24107

Fixes #24107: Broken parsing of 8.1 plugin index

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Score/ViewUtils.elm
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-compliance.scss

https://issues.rudder.io/issues/24104

Fixes #24104: System updates badges in compliance score have no css

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/migration/CheckTableScore.scala

https://issues.rudder.io/issues/24090

Fixes #24090: Score table migration

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/users/User.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/comet/AsyncDeployment.scala

https://issues.rudder.io/issues/24117
So, this is the continuation of https://github.com/Normation/rudder/pull/5267 and the fact that we needed to change `CurrentUser` from a `SessionVar` to a `RequestVar`. 
Lift helps us for normal ajax requests, keeping `RequestVar` context available, but not for comet, which only knows about sessions. So for the generation probe, which is comet, we lost the information about current user. 
Since we only have *one* comet thing in all Rudder, I didn't produced a generic solution: we just get current user in the comet init part directly from SpringSecurity (since at that point of request processing, we don't have the problems that forced us to skip to `RequestVar` anymore). 
Nonetheless, I changed the location of `checkRights` to `RudderUserDetails`, …

Fixes #24117: Missing policy generation status

---

relay/sources/rudder-package/src/archive.rs

https://issues.rudder.io/issues/24131

Fixes #24131: rudder package unpacks scripts.txz in the wrong place

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/ViewUtils.elm
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-datatable.css

https://issues.rudder.io/issues/23487

Fixes #23487: Editing big properties in elm-based properties interface is very inconvenient

---

webapp/sources/api-doc/components/schemas/node-add.yml

https://issues.rudder.io/issues/24141

Fixes #24141: Bad description for serialNumber attribute of machine

---

relay/sources/rudder-package/src/plugin.rs

https://issues.rudder.io/issues/24126

Fixes #24126: Local install should accept relative path as input

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/ViewUtils.elm

https://issues.rudder.io/issues/24102

Fixes #24102: Unknown rule targets UI is missing icon and border

---

webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-template.css

https://issues.rudder.io/issues/24122

Fixes #24122: Action dropdown list in technique editor goes under parameters

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/score/ComplianceScore.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/score/Score.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/score/SystemUpdateScore.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/ShowNodeDetailsFromNode.scala
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-compliance.scss
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-node.scss
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/server/server_details.html

https://issues.rudder.io/issues/24096

Fixes #24096: Add score on top of tabs

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Score/ViewUtils.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/SystemUpdateScore.elm
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-compliance.scss

https://issues.rudder.io/issues/24155

Fixes #24155: System updates badges css in compliance score is not applied

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/score/Score.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/score/ScoreService.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala

https://issues.rudder.io/issues/24158

Fixes #24158: Add missing score

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewBlock.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewMethod.elm
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-technique-editor.css

https://issues.rudder.io/issues/24181
Moved a bunch of elements because they were above/behind others

Fixes #24181: Some buttons in technique editor are not working since new audit/enforce button were added

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/score/ScoreService.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder-datatable.js
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/SrvGrid.scala
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-compliance.scss

https://issues.rudder.io/issues/24165

Fixes #24165: Add Score in nodes table

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Hooks.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Hooks/Init.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Hooks/View.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Hooks/ViewUtils.elm
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
webapp/sources/rudder/rudder-web/src/main/style/rudder/_rudder-variables.scss
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-hooks.scss
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-template.scss
webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/hooksManagement.html
webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/policyServerManagement.html

https://issues.rudder.io/issues/24204
Fix the display and the scrollspy of the Hooks page :

Fixes #24204: Hooks page looks broken since bootstrap 5 update

---

webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-menu.scss

https://issues.rudder.io/issues/24197

Fixes #24197: The chevron down icon for "Status" is barely visible

---

policies/rudderc/src/backends/unix/cfengine/promise.rs
policies/rudderc/tests/cases/general/escaping/technique.cf
policies/rudderc/tests/cases/general/form/technique.cf
policies/rudderc/tests/cases/general/ntp/technique.cf
policies/rudderc/tests/cases/general/param_in_condition/technique.cf
policies/rudderc/tests/cases/general/reporting/technique.cf

https://issues.rudder.io/issues/24226

Fixes #24226: rudderc canonifies already canonified condition expression resulting in loss of logic operators such as ) and |

---

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py
relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py

https://issues.rudder.io/issues/24201

Fixes #24201: rudder-pkg stops at first install error on the upgrade-all command

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/24203

Fixes #24203: Role API mapping should be exposed in RudderConfig

---

relay/sources/rudder-package/src/cmd.rs
relay/sources/rudder-package/src/plugin.rs

https://issues.rudder.io/issues/24241

Fixes #24241: 8.1 version of parent ticket

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/appconfig/ConfigService.scala

https://issues.rudder.io/issues/24207

Fixes #24207: We need a setting to force change request validation

---

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py
relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py

https://issues.rudder.io/issues/24238

Fixes #24238: Rudder-package should log the package scripts outputs and errors

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/Authorizations.scala

https://issues.rudder.io/issues/24285

Fixes #24285: Empty role in users file is logged as warning

---

policies/rudderc/tests/cases/test/integration_unix/technique.yml
policies/rudderc/tests/cases/test/integration_unix/tests/case1.yml
policies/rudderc/tests/cases/test/integration_unix/tests/case2.yml

https://issues.rudder.io/issues/24291

Fixes #24291: Add integration tests to rudderc

---

webapp/sources/rudder/rudder-core/src/main/resources/reportsSchema.sql

https://issues.rudder.io/issues/24303

Fixes #24303: User sessions sql should contain authz column

---

Jenkinsfile

https://issues.rudder.io/issues/24309

Fixes #24309: Adapt Jenkinsfile after warning-ng plugin upgrade - 8.1

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder.css

https://issues.rudder.io/issues/24310

Fixes #24310: Display of node compliance info message is broken

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/model/DirectiveEditor.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/AcceptNode.scala

https://issues.rudder.io/issues/24311

Fixes #24311: Checkbox for selecting all nodes for acceptance doesn't work

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTechnique.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/ViewUtils.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/View.elm
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-bootstrap.scss
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-main.css

https://issues.rudder.io/issues/24322

Fixes #24322: Modal titles are unreadable

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder-datatable.js

https://issues.rudder.io/issues/24351

Fixes #24351: Tooltips persisted on refresh button on the table in search node page

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/HealthcheckInfo.scala
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-bootstrap.scss
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-main.css
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-menu.scss

https://issues.rudder.io/issues/24346

Fixes #24346: Warning icon on log out should be on healthcheck heart logo

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewMethod.elm

https://issues.rudder.io/issues/24350

Fixes #24350: The technique editor enforces optional parameter presence

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/DirectiveCompliance/View.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/GroupCompliance/View.elm

https://issues.rudder.io/issues/24313

Fixes #24313: Wrong lalel on tab in compliance group

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewBlock.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewMethod.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewMethodsList.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTechniqueList.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTechniqueTabs.elm
webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder.js
webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/techniqueEditor.html

https://issues.rudder.io/issues/24345

Fixes #24345: Popovers don't work anymore

---

webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-node.scss
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/server/server_details.html

https://issues.rudder.io/issues/24369

Fixes #24369: The height of node tabs is higher than the height of their container

---

policies/rudderc/src/compiler.rs

https://issues.rudder.io/issues/24371

Fixes #24371: Broken detection of incorrect parameter names

---

relay/sources/rudder-package/src/cli.rs
relay/sources/rudder-package/src/database.rs
relay/sources/rudder-package/src/lib.rs
relay/sources/rudder-package/src/repo_index.rs

https://issues.rudder.io/issues/24373

Fixes #24373: Add the ability to specify the version to install

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder.js
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentDirectiveEditForm.html
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/NodeGroupForm.html

https://issues.rudder.io/issues/24174

Fixes #24174: The display of the description field is broken

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/ViewModals.elm
webapp/sources/rudder/rudder-web/src/main/style/rudder/_rudder-variables.scss
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-bootstrap.scss
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-compliance.scss
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-elm-datepicker.css
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-main.scss
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-node.scss
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-template.scss
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder.css
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentRuleEditForm.html

https://issues.rudder.io/issues/24233

Fixes #24233: Update Rudder CSS to support bug fixes in plugins interface

---

policies/rudder-commons/src/lib.rs
policies/rudderc/docs/src/syntax.md
policies/rudderc/src/backends/unix.rs
policies/rudderc/src/backends/unix/ncf/method_call.rs
policies/rudderc/src/backends/windows.rs
policies/rudderc/src/ir/technique.rs
policies/rudderc/src/technique.schema.json
policies/rudderc/templates/technique.ps1.askama
policies/rudderc/tests/cases/general/policy_mode/technique.yml
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/yaml/YamlTechnique.scala
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/1.0/technique.yml
webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/technique.yml
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewBlock.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewMethod.elm

https://issues.rudder.io/issues/24380

Fixes #24380: Rename policy_mode to policy_mode_override

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/SystemUpdateScore.elm

https://issues.rudder.io/issues/24316

Fixes #24316: Tooltips on system-updates in score-details is not standard

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/SearchNodeComponent.scala
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-groups.css
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-main.scss
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-node.scss
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-rules.css
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder.css
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/server/server_details.html

https://issues.rudder.io/issues/24348

Fixes #24348: Odd spacing with filters elements in node search page

---

relay/sources/rudder-package/src/cli.rs

https://issues.rudder.io/issues/24389

Fixes #24389: Improve rudder-package CLI doc

---

webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala

https://issues.rudder.io/issues/24289

Fixes #24289: windows Node in tests has invalid  certificate, failing test in plugin windows

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder-datatable.js
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala

https://issues.rudder.io/issues/24383

Fixes #24383: Show logs button in node compliance tab does nothing

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/View.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/ViewModals.elm

https://issues.rudder.io/issues/24391

Fixes #24391: API popup for copying token does not appear

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewBlock.elm

https://issues.rudder.io/issues/24382

Fixes #24382: Enforce policy mode in block method has a different display than audit  

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala

https://issues.rudder.io/issues/24428

Fixes #24428: Directives button to set parameters on new directive does nothing 

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/AcceptNode.scala
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-main.scss
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/Popup/accept_new_server.html

https://issues.rudder.io/issues/24388
Search filter has been removed :

Fixes #24388: There is a search box in the node acceptation pop-up

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/ShowNodeDetailsFromNode.scala
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-bootstrap.scss
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-compliance.scss

https://issues.rudder.io/issues/24447
Score badge is back !

Fixes #24447: Tabs are missing their score

---

relay/sources/rudder-package/src/cli.rs
relay/sources/rudder-package/src/lib.rs

https://issues.rudder.io/issues/24490

Fixes #24490: Add a quiet argument to rudder-package

---

relay/sources/rudder-package/src/plugin.rs

https://issues.rudder.io/issues/24483

Fixes #24483: rudder package log the package scripts in the wrong files

---

relay/sources/relayd/Cargo.lock

https://issues.rudder.io/issues/24516

Fixes #24516: Vulnerability in mio

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/action/CheckNcfTechniqueUpdate.scala

https://issues.rudder.io/issues/24515

Fixes #24515: Rudder should finish to migrate all techniques when booting instead of stopping on first error

---

webapp/sources/rudder/rudder-web/src/main/.nsprc

https://issues.rudder.io/issues/24517

Fixes #24517: Ignore angularjs DoS in 7.3

---

webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-bootstrap.scss

https://issues.rudder.io/issues/24463

Fixes #24463: It is hard to differentiate between real values and placeholders in inputs

---

webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-technique-editor.css

https://issues.rudder.io/issues/24519

Fixes #24519: The "condition" border appears on all methods in the tech. editor.

---

Jenkinsfile-security

https://issues.rudder.io/issues/24522

Fixes #24522: npm dep security checks are ignored

---

Jenkinsfile-security
ci/rust.sh
sbom/Dockerfile
sbom/README.md
sbom/sbom.sh

https://issues.rudder.io/issues/23356
* Use CycloneDX as it's the one with the best coverage for our ecosystem
* We are (presumably) able to convert to SPDX using cyclonedx CLI
* Generate a file by "package" (rpm/dpkg/rpkg/msi/etc.)
* Only support tagged releases

Fixes #23356: Add SBOM tooling

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTechniqueTabs.elm
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-technique-editor.css

https://issues.rudder.io/issues/24467

Fixes #24467: Improve technique parameter UI

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/score/ScoreService.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ScoreApiImpl.scala
webapp/sources/rudder/rudder-web/src/main/elm/sources/Node.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Node/ApiCalls.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Node/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Node/Init.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Node/View.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Score.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Score/ApiCalls.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Score/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Score/Init.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Score/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Score/View.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Score/ViewUtils.elm
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/24527

Fixes #24527: Have list of available score available and define a display name

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder-datatable.js
webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder.js

https://issues.rudder.io/issues/24355

Fixes #24355: Score details are missing in nodes table

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/NodeFactQueryProcessor.scala

https://issues.rudder.io/issues/24324
The missing implementation was causing the error, and it seems the `check` is expected to return an error in both mock version and LDAP implementation of the `QueryChecker` so I also added it

Fixes #24324: Directive applicaton preview  in pending nodes is broken

---

webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/directiveManagement.html

https://issues.rudder.io/issues/23400
As simple as that and it works  (but does not avoid loading a new Elm app each time a technique is displayed)

Fixes #23400: JS error when clicking on a technique with several version in directive screen

---

relay/sources/rudder-package/src/cli.rs

https://issues.rudder.io/issues/24576

Fixes #24576: Rudder-package cli help for install command should document file

---

api-doc/package-lock.json
api-doc/package.json
webapp/sources/api-doc/openapi.src.yml

https://issues.rudder.io/issues/24581

Fixes #24581: Update API doc version to 19

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTechnique.elm

https://issues.rudder.io/issues/24453

Fixes #24453: Delete modal in technique editor is offset

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Node.elm

https://issues.rudder.io/issues/24557

Fixes #24557: Add margin right to system updates badge

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeCompliance/View.elm

https://issues.rudder.io/issues/24499

Fixes #24499: Wrong error message when no result are found when using a compliance filter

---

relay/sources/relayd/src/data/runinfo.rs

https://issues.rudder.io/issues/24564

Fixes #24564: Teach relayd about a new report file name

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/facts/nodes/NodeFactServiceProxies.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/NodeRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeRepository.scala

https://issues.rudder.io/issues/24593

Fixes #24593: Remove unused node function used by scale out relay plugin

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/eventlog/NodeEventLog.scala

https://issues.rudder.io/issues/24596

Fixes #24596: Missing event for Relay Demote preventing demotion

---

relay/sources/rudder-package/src/cli.rs

https://issues.rudder.io/issues/24601

Fixes #24601: Improve the rudder package errors when using commands without any inputs

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala

https://issues.rudder.io/issues/24602

Fixes #24602: Number of software updates available is redundant

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules.elm
webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder.js

https://issues.rudder.io/issues/24436
Nothing magical here, I've just added more tooltip initialisation events until I find a definitive solution to this problem.

Fixes #24436: Tooltip on compliance in rule page is not rendered

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala

https://issues.rudder.io/issues/24590

Fixes #24590: Directive errors section is not consistent and always redirects to first tab

---

webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/policyServerManagement.html

https://issues.rudder.io/issues/24510
Result :

Fixes #24510: "Usage survey" setting select button is way too large

---

webapp/sources/dependency-check-suppression.xml
webapp/sources/pom.xml

https://issues.rudder.io/issues/24606

Fixes #24606: Upgrade postgresql since CVE-2024-1597 and ignore other JS CVEs

---

webapp/sources/pom.xml

https://issues.rudder.io/issues/24607

Fixes #24607: 

---

Cargo.lock
policies/rudder-cli/Cargo.toml
policies/rudder-cli/src/logs.rs
policies/rudderc/src/main.rs
policies/rudderc/tests/compile.rs
relay/sources/rudder-package/src/lib.rs

https://issues.rudder.io/issues/24484

Fixes #24484: rudder package does not log in /var/log/rudder/rudder-pkg/rudder-pkg.log anymore

---

SECURITY.md

https://issues.rudder.io/issues/24608

Fixes #24608: Update the security policy

---

relay/sources/selinux/rudder-relay.te

https://issues.rudder.io/issues/24589

Fixes #24589: SELinux error for downloading files

---

webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/server/server_details.html

https://issues.rudder.io/issues/24633
The scripts were just deleted in https://github.com/Normation/rudder/pull/5477...

Fixes #24633: Node properties do not display in 8.0

---

webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentNodeProperties.html

https://issues.rudder.io/issues/24641
Same purpose as  #5556, it was merged in 8.1, but the bug is still present in 8.0

Fixes #24641: Port #24633 in 8.0 to be able to add and read node properties

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RoleApiMapping.scala

https://issues.rudder.io/issues/24638

Fixes #24638: Score API are not accessible to readonly user

---

webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/Popup/ModificationValidationPopup.html

https://issues.rudder.io/issues/24613

Fixes #24613: Enabling directive modal has margin between table and change log

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala

https://issues.rudder.io/issues/24647

Fixes #24647: Only ignored status is displayed in Node page

---

policies/rudderc/tests/cases/general/policy_mode/metadata.xml
relay/sources/rudder-package/src/dependency.rs

https://issues.rudder.io/issues/24677

Fixes #24677: Improve apt/rpm package dependency detection

---

relay/sources/rudder-package/src/webapp.rs

https://issues.rudder.io/issues/24676

Fixes #24676: Don't hardcode systemctl path

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/facts/nodes/NodeFactChangeEventCallback.scala

https://issues.rudder.io/issues/24669

Fixes #24669: Typo "dynmaci" in logs

---

webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/FullInventoryRepositoryImpl.scala

https://issues.rudder.io/issues/24675

Fixes #24675: When sending inventory with no software update anymore, inventory stored is not updated and keeps previous updates

---

Cargo.lock
relay/sources/rudder-package/Cargo.toml
relay/sources/rudder-package/src/database.rs
relay/sources/rudder-package/src/lib.rs
relay/sources/rudder-package/tests/status_backup_file/backup.expected

https://issues.rudder.io/issues/24568

Fixes #24568: Disabled plugins are enabled when upgrading to 8.1

---

webapp/sources/api-doc/code_samples/curl/securitytags/deleteOnNodes.sh
webapp/sources/api-doc/code_samples/curl/securitytags/nodes.sh
webapp/sources/api-doc/code_samples/curl/securitytags/setOnNodes.sh
webapp/sources/api-doc/code_samples/curl/tenants/add.sh
webapp/sources/api-doc/code_samples/curl/tenants/delete.sh
webapp/sources/api-doc/code_samples/curl/tenants/set.sh
webapp/sources/api-doc/paths/securitytags/nodes.yml
webapp/sources/api-doc/paths/tenants/all.yml

https://issues.rudder.io/issues/24674

Fixes #24674: Tenant API documentation has several problems

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Node/View.elm
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-node.scss

https://issues.rudder.io/issues/24611

Fixes #24611: Node rudder information section is clipped and needs scroll 

---

webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/NodeGroupForm.html

https://issues.rudder.io/issues/24682

Fixes #24682: Group close button does not appear for readonly user

---

webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/FullInventoryRepositoryImpl.scala

https://issues.rudder.io/issues/24681

Fixes #24681: Also remove tree from machine

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder-datatable.js
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/SearchNodeComponent.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/SrvGrid.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/Nodes.scala
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-template.scss

https://issues.rudder.io/issues/24550

Fixes #24550: Nodes table should not be displayed in every tab of group details

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/JsonResponseObjects.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/EditorTechnique.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueCompiler.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/migration/MigrateJsonTechniquesService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/yaml/YamlTechnique.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestEditorTechniqueWriter.scala
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/JsonEncoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTechnique.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTechniqueTabs.elm
webapp/sources/rudder/rudder-web/src/test/resources/configuration-repository-migrate-json-8_0/post-migration/ncf_techniques/technique_with_parameters/1.0/metadata.xml
webapp/sources/rudder/rudder-web/src/test/resources/configuration-repository-migrate-json-8_0/post-migration/ncf_techniques/technique_with_parameters/1.0/technique.yml
webapp/sources/rudder/rudder-web/src/test/resources/configuration-repository-migrate-json-8_0/techniques/ncf_techniques/technique_with_parameters/1.0/metadata.xml

https://issues.rudder.io/issues/24698

Fixes #24698: Empty description of technique parameter is not allowed

---

relay/sources/rudder-package/src/webapp.rs

https://issues.rudder.io/issues/24738

Fixes #24738: The webapp is not restarted when upgrading a plugin

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RoleApiMapping.scala

https://issues.rudder.io/issues/24671

Fixes #24671: API authorization error: secure/api/compliance/nodes/{id}/system

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/SystemUpdateScore.elm
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-compliance.scss

https://issues.rudder.io/issues/24742
Before
After
Before
After

Fixes #24742: Badge style is not coherent in the whole UI 

---

relay/sources/rudder-package/src/lib.rs

https://issues.rudder.io/issues/24750

Fixes #24750: Restart webapp even if some plugin installation failed

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/AcceptNode.scala

https://issues.rudder.io/issues/24756
Some code was unused and I prefer to clean it up, dead code in the accept snippet is a stick to get cyber-hit.
The correction is trivial and just filtre the list of nodes with the list of select ones.

Fixes #24756: Accepting one selected pending node pops up a windows that accepts them all

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/score/ComplianceScore.scala

https://issues.rudder.io/issues/24767

Fixes #24767: Broken compliance score for E

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RoleApiMapping.scala

https://issues.rudder.io/issues/24785

Fixes #24785: Read-only user no longer has access to groups

---

relay/sources/rudder-package/src/cli.rs

https://issues.rudder.io/issues/24782

Fixes #24782: Add remove as uninstall alias

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Groups/DataTypes.elm

https://issues.rudder.io/issues/24807

Fixes #24807: Group table should display more elements

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/PluginApi.scala

https://issues.rudder.io/issues/24828

Fixes #24828: Never return a password for plugin settings

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/score/ScoreService.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/24840

Fixes #24840: Clean missing score at start up

---

relay/sources/rudder-package/src/lib.rs
relay/sources/rudder-package/src/webapp.rs

https://issues.rudder.io/issues/24745

Fixes #24745: Add an option to inhibit webapp restart

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Compliance/Utils.elm

https://issues.rudder.io/issues/24501

Fixes #24501: Unexpected results when using compliance filters

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitArchivers.scala

https://issues.rudder.io/issues/24864

Fixes #24864: Fix upmerge of 24856 in 8.1

---

webapp/sources/utils/src/main/scala/com/normation/utils/DateFormaterService.scala

https://issues.rudder.io/issues/24877

Fixes #24877: Upmerge breaks build from 8.0 and up

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/EditorTechnique.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/yaml/YamlTechnique.scala

https://issues.rudder.io/issues/24888

Fixes #24888: Technique tags can be arbitrary objects

---

Cargo.lock
ci/typos.Dockerfile
policies/Dockerfile
policies/minifusion/Cargo.toml
policies/module-types/template/Cargo.toml
policies/rudderc/Cargo.toml
policies/rudderc/src/compiler.rs
policies/rudderc/src/lib.rs
relay/sources/relayd/Cargo.toml
relay/sources/relayd/Dockerfile
relay/sources/relayd/src/data/node.rs
relay/sources/rudder-package/Cargo.toml
relay/sources/rudder-package/Dockerfile
relay/sources/rudder-package/src/database.rs
relay/sources/rudder-package/src/lib.rs
rust-toolchain.toml
sbom/Dockerfile

https://issues.rudder.io/issues/24830

Fixes #24830: Update to Rust 1.78

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder-datatable.js

https://issues.rudder.io/issues/24629

Fixes #24629: Score details columns in node tables cannot be saved 

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/UserManagement.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/UserManagement/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/UserManagement/Init.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/UserManagement/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/UserManagement/View.elm
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-datatable.css
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-user-management.scss
webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/userManagement.html

https://issues.rudder.io/issues/24881

Fixes #24881: Display the list of users in table form

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder-datatable.js

https://issues.rudder.io/issues/24949

Fixes #24949: No-report progress bars are the wrong width

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ComplianceApi.scala

https://issues.rudder.io/issues/24945
So, the root cause of the bug is that some key is not in the map and we try to get it, which fails with an exception. 
The cheap correction could have been just adding a test "if(allRuleInfo.contains(rule.id)" or something like that. 
A better one would have been to pattern match on `allRuleInfo.get(rule.id)`
But what we really want is to make that thing impossible by construction. 
Here, we can just avoid passing both source of rules as parameter and construct the map before, so the problem can't exist at all.

Fixes #24945: Error when going to group page

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala

https://issues.rudder.io/issues/24924

Fixes #24924: wrong id to setup markdown

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/AcceptNode.scala
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder.css

https://issues.rudder.io/issues/24948

Fixes #24948: The Directive button in pending nodes table has an old appearance

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/HomePage.scala

https://issues.rudder.io/issues/24951

Fixes #24951: Change 'No score' label

---

qa-test

https://issues.rudder.io/issues/24954

Fixes #24954: exclude all old rudder package files from python tests 

---

policies/Makefile

https://issues.rudder.io/issues/24956

Fixes #24956: Windows agent used to test windows policies was deleted

---

policies/rudderc/src/main.rs

https://issues.rudder.io/issues/24967
https://docs.rs/anyhow/latest/anyhow/struct.Error.html#display-representations

Fixes #24967: stacktraces from rudderc

---

policies/rudder-cli/src/lib.rs
policies/rudder-cli/src/logs.rs
relay/sources/rudder-package/src/lib.rs

https://issues.rudder.io/issues/24610
* Simplify the log file name handling
* We don't need a non-blocking file logger

Fixes #24610: Improve tracing loggers

---

webapp/sources/api-doc/components/schemas/node-full.yml
webapp/sources/api-doc/introduction.md

https://issues.rudder.io/issues/24975

Fixes #24975: API v20 documentation with Node api changes

---

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py
relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py

https://issues.rudder.io/issues/24982

Fixes #24982: pylint test failing on rudder package 

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/CampaignRepository.scala

https://issues.rudder.io/issues/24959

Fixes #24959: Error message when getting campaign through API

---

relay/sources/Makefile

https://issues.rudder.io/issues/24984

Fixes #24984: relayd man page build is broken

---

webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-compliance.scss

https://issues.rudder.io/issues/24983

Fixes #24983: bugfixes in the list of updates appears in white

---

.gitignore

https://issues.rudder.io/issues/24961

Fixes #24961: Add hotswap agent conf gile to gitignore to prevent surprises in production site

---

webapp/sources/rudder/rudder-web/src/main/.nsprc

https://issues.rudder.io/issues/24995

Fixes #24995: Ignore braces DoS in 7.3

---

policies/rudderc/src/ir/technique.rs
policies/rudderc/src/technique.schema.json
policies/rudderc/tests/cases/general/ntp/technique.yml

https://issues.rudder.io/issues/24962

Fixes #24962: Add description and documentation fields to methods and blocks

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/users/RudderUserDetailsFile.scala

https://issues.rudder.io/issues/25012
This bug is a one with kind : "Oups :see_no_evil:".
The wrong String was passed to the method : the raw password instead of the hashed one...  :sweat_smile:
With the `getOrElse(DEFAULT)` fallback for the encoder being `BCRYPT`, we always ended up accepting BCRYPT only, and ignoring all the logic to map `SHA256`, `MD5`, etc. depending on the password length :sweat_smile:

Fixes #25012: Migrating to bcrypt with unsafe hashes still match bcrypt hash only

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/migration/DeleteArchiveTables.scala

https://issues.rudder.io/issues/25016
Sequence are not tables. 
And table name must not be a sql parameter.

Fixes #25016: On a fresh install of Rudder 8.2 nightly, bootcheck error for table deletion

---

webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TestRestFromFileDef.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TraitTestApiFromYamlFiles.scala
webapp/sources/utils/src/main/scala/com/normation/ZioCommons.scala

https://issues.rudder.io/issues/25017
Just change back the parameter of the function to liftRules

Fixes #25017: TraitTestApiFromYamlFiles must allow to customize liftRules

---

webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/services/core/SoftwareDAO.scala
webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/ReadOnlySoftwareInventoryDAOImpl.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/facts/nodes/NodeFactRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/facts/nodes/NodeFactServiceProxies.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/facts/nodes/TestCoreNodeFactInventory.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/facts/nodes/TestFullInventoryRepoProxy.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/facts/nodes/TestSaveInventory.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestNodeFactQueryProcessor.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/25018
typo

Fixes #25018: Typo in NoopGetNodesbySofwareName prevent merge

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Healthcheck/ApiCalls.elm

https://issues.rudder.io/issues/25024

Fixes #25024: Add CSRF mitigation header for XHR in healthcheck page

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Onboarding/ApiCalls.elm

https://issues.rudder.io/issues/25034

Fixes #25034: Add CSRF mitigation header for XHR in onboarding page

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/ExpectedReports.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/metrics/HistorizeNodeCountService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/reports/ComplianceMode.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/reports/execution/ReportsExecutionService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ExpectedReportsRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ReportsRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ExpectedReportsJdbcRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ReportsJdbcRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportsTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ComplianceApi.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SettingsApi.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/ComplianceModeEditForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/ShowNodeDetailsFromNode.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/AsyncComplianceService.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/HomePage.scala

https://issues.rudder.io/issues/25038
Extremelly interesting PR with a lot of `s/Box/IOResult`
I'm commenting inline the intersting parts. 
EDIT: ok, I didn't find anything interesting at all :/ 
EDIT2: I checked in plugins, none is impacted by these changes.

Fixes #25038: Switch service related to compliance persistance from box to IOResult

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/DeleteEditorTechnique.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/NewNodeManager.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/NodeFactQueryProcessor.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestEditorTechniqueWriter.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/TechniqueApi.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/AcceptNode.scala
webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/migration/TestMigrateJsonTechniquesToYaml.scala

https://issues.rudder.io/issues/25045

Fixes #25045: Node delete has a todoQC

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/reports/ComplianceMode.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/25057

Fixes #25057: There is now a loop in initialization

---

webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-quicksearch.scss

https://issues.rudder.io/issues/25010

Fixes #25010: Quick search bar selection/results box displays over input field, making input field unusable

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder-datatable.js

https://issues.rudder.io/issues/25081
Imperative programming is hard...

Fixes #25081: Directive detail has compliance bar JS error

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ComplianceTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ExecutionBatchTest.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/appconfig/ConfigService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SettingsApi.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_settings.yml
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PropertiesManagement.scala
webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/policyServerManagement.html

https://issues.rudder.io/issues/25087
This is all automatic changes from the deletion of `UnexpectedReportBehavior`

Fixes #25087: Remove unexpected interpretation choice for vars because it's not meaningful anymore

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchBackendImpl.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchDomain.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchService.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/RestQuicksearch.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/model/JsInitContextLinkUtil.scala
webapp/sources/rudder/rudder-web/src/main/elm/sources/QuickSearch/Datatypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/QuickSearch/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/QuickSearch/View.elm
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-quicksearch.scss

https://issues.rudder.io/issues/25060
Replacing previous PR: https://github.com/Normation/rudder/pull/5745

Fixes #25060: Add support of editor techniques in quicksearch

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/comet/AsyncDeployment.scala
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-main.css

https://issues.rudder.io/issues/25042
Before:
After:

Fixes #25042: Generation error logs are unreadable in the interface

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/CampaignRepository.scala

https://issues.rudder.io/issues/25053

Fixes #25053: Error 500 when we visit for the first time the campaign page

---

webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-main.css
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-technique-editor.css

https://issues.rudder.io/issues/24587

Fixes #24587: Windows DSC logo on method are not aligned

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Agentschedule/View.elm

https://issues.rudder.io/issues/25078

Fixes #25078: Second digit of minutes for agent scheduled not displayed

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/25125

Fixes #25125: Some services are not available to build plugins

---

relay/sources/Makefile
relay/sources/apache/rudder-vhost.conf

https://issues.rudder.io/issues/25143

Fixes #25143: Make apache configuration easier to automatically split

---

Jenkinsfile
webapp/sources/pom.xml

https://issues.rudder.io/issues/25168

Fixes #25168: The webapp does not build on jdk22

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/ViewRuleDetails.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/ViewTabContent.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/ViewUtils.elm
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-template.scss

https://issues.rudder.io/issues/25176
Before :
After :

Fixes #25176: Small improvements of Targets selection interface

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchDomain.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchQueryParser.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchService.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/quicksearch/QSRegexQueryParserTest.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/RestQuicksearch.scala

https://issues.rudder.io/issues/25116
Replacing previous PR: https://github.com/Normation/rudder/pull/5767

Fixes #25116: Add parameter to change maximum limit on a quicksearch

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/ApiCalls.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/Init.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/View.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/ViewUtils.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Nodeproperties.elm
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-datatable.css
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-template.scss

https://issues.rudder.io/issues/24634
Replacing previous PR: https://github.com/Normation/rudder/pull/5557

Fixes #24634: API to find usage of a node property in Directives

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/ApiCalls.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/ViewUtils.elm
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-template.scss

https://issues.rudder.io/issues/25184

Fixes #25184: Missing header XMLHttpRequest for quicksearch call in find property usage

---

policies/rudderc/templates/technique.ps1.askama
policies/rudderc/tests/cases/general/escaping/technique.ps1
policies/rudderc/tests/cases/general/form/technique.ps1
policies/rudderc/tests/cases/general/long_method_param_name/technique.ps1
policies/rudderc/tests/cases/general/min/technique.ps1
policies/rudderc/tests/cases/general/ntp/technique.ps1
policies/rudderc/tests/cases/general/param_in_condition/technique.ps1
policies/rudderc/tests/cases/general/policy_mode/technique.ps1
policies/rudderc/tests/cases/general/reporting/technique.ps1
policies/rudderc/tests/cases/general/variables/technique.ps1

https://issues.rudder.io/issues/25190

Fixes #25190: Improve the error handling in the Windows techniques

---

Jenkinsfile
policies/Dockerfile

https://issues.rudder.io/issues/25213

Fixes #25213: The policies Dockerfile does not fail when the rudder agent fails to install

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/PostCommits.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/NewNodeManager.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/25161

Fixes #25161: Node inventory hooks are are not working properly

---

webapp/sources/pom.xml

https://issues.rudder.io/issues/25186

Fixes #25186: Update Scala dependencies

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/plugins/PluginSettings.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/PluginApi.scala
webapp/sources/rudder/rudder-web/src/main/elm/sources/Onboarding.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Onboarding/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Onboarding/Init.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Onboarding/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Onboarding/JsonEncoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Onboarding/View.elm

https://issues.rudder.io/issues/25227

Fixes #25227: Don't update plugin password if nothing was given

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/plugins/PluginSettings.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/PluginApi.scala
webapp/sources/rudder/rudder-web/src/main/elm/sources/Onboarding.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Onboarding/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Onboarding/Init.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Onboarding/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Onboarding/JsonEncoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Onboarding/View.elm
webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/setup.html

https://issues.rudder.io/issues/25228

Fixes #25228: Error when saving

---

webapp/sources/api-doc/code_samples/curl/nodes/pending-update.sh
webapp/sources/api-doc/components/schemas/node-pending-result.yml
webapp/sources/api-doc/openapi.src.yml
webapp/sources/api-doc/paths/nodes/pending-update.yml

https://issues.rudder.io/issues/25285

Fixes #25285: API documentation for pending nodes is missing an endpoint and fields

---

Cargo.lock
relay/sources/Makefile
relay/sources/rudder-package/Cargo.toml
relay/sources/rudder-package/build.rs
relay/sources/rudder-package/src/cli.rs
relay/sources/rudder-package/src/lib.rs
relay/sources/rudder-relay-postinst

https://issues.rudder.io/issues/25208

Fixes #25208: Fix shell autocomplete for "rudder package"

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/View.elm

https://issues.rudder.io/issues/25171

Fixes #25171: Message « This node has no properties » on group

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/UserManagement/View.elm

https://issues.rudder.io/issues/25301
The text is just using the entire list of users instead of the filtered on to display  `Showing 1 to 20 of 20 entries`.
We don't paginate the table, so that text does not really make sense, it should rather be `Showing 20 of 20 entries` and `Showing 5 of 20 entries` when filtered with the search bar.

Fixes #25301: User management table has the wrong count of entries with deleted users

---

relay/sources/Makefile

https://issues.rudder.io/issues/25308

Fixes #25308: rudder-package completion build breaks

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/ApiCalls.elm

https://issues.rudder.io/issues/25310

Fixes #25310:  Implement missing CSRF mitigation headers for Rules XHR

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/25319

Fixes #25319: Inheritance error in properties stop running startup

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/users/UserRepository.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/users/UserRepositoryTest.scala

https://issues.rudder.io/issues/25300
The case with `setExistingUsers(Nil)` should not be `ZIO.unit` because it means that we want to remove all users !

Fixes #25300: Only remaining user managed by file cannot be deleted 

---

webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-bootstrap.scss

https://issues.rudder.io/issues/25326
before/after

Fixes #25326: Make tooltips non-transparent

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/ViewUtils.elm

https://issues.rudder.io/issues/25333
- Use the same display as in properties when there are no usages :
- `start` variable is used for indexing but the displayed value should be is `start + 1` :

Fixes #25333: Some minor UI issues in node property usage search

---

policies/rudderc/src/lib.rs

https://issues.rudder.io/issues/25345

Fixes #25345: Missing import in rudderc

---

Jenkinsfile

https://issues.rudder.io/issues/25346

Fixes #25346: We have no 8.3 build for now

---

ci/rust.sh
policies/module-types/directory/Cargo.toml
policies/module-types/directory/Makefile
policies/module-types/system-updates/Cargo.toml
policies/module-types/system-updates/Makefile
policies/module-types/template/Cargo.toml
policies/module-types/template/Makefile
rust.makefile

https://issues.rudder.io/issues/25342

Fixes #25342: Changes for modules packaging

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/EventLogDetailsGenerator.scala
webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder-datatable.js
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-template.scss
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder.css
webapp/sources/rudder/rudder-web/src/main/webapp/secure/utilities/eventLogs.html

https://issues.rudder.io/issues/25071
**Before:** 
**After:**

Fixes #25071: Event logs details look broken in 8.1

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/PurgeDeletedInventories.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/PurgeUnreferencedSoftwares.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/metrics/Scheduler.scala

https://issues.rudder.io/issues/25365
`UIO[?]` does not mean that all errors have been caught : only `E` ones, when the initial type is `ZIO[R, E, A]` and often `RudderError` in the case of `IOResult`. There could also be [defects](https://zio.dev/reference/error-management/expected-and-unexpected-errors#unexpected-errors-1) (runtime errors within the fiber) which would have been uncaught and would interrupt the currently running fiber.
This PR is for preventing such error from interrupting a repeated process in ZIO (with a delay and running forever), and for logging errors and continuing instead.
The type is not an absolute reference because we could do : 
* `IOResult.attempt: IOResult[A]` which already include error handling of all defects
but doing : 
* `ioResult#catchAll: UIO[A]` is …

Fixes #25365: Scheduled processes could stop on error in ZIO

---

policies/rudderc/src/lib.rs

https://issues.rudder.io/issues/25375

Fixes #25375: rudderc CLI errors are not user friendly enough when the workdir is incorrectly set

---

Jenkinsfile
policies/Dockerfile
policies/rudderc/Makefile
policies/rudderc/PSScriptAnalyzerSettings.psd1
policies/rudderc/generate-all-test-cases.sh
policies/rudderc/templates/technique.ps1.askama
policies/rudderc/tests/cases/general/escaping/technique.ps1
policies/rudderc/tests/cases/general/form/technique.ps1
policies/rudderc/tests/cases/general/long_method_param_name/technique.ps1
policies/rudderc/tests/cases/general/min/technique.ps1
policies/rudderc/tests/cases/general/ntp/technique.ps1
policies/rudderc/tests/cases/general/param_in_condition/technique.ps1
policies/rudderc/tests/cases/general/policy_mode/technique.ps1
policies/rudderc/tests/cases/general/reporting/technique.ps1
policies/rudderc/tests/cases/general/variables/technique.ps1

https://issues.rudder.io/issues/25382

Fixes #25382: Typo in the windows technique generation template

---

webapp/sources/pom.xml
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/CampaignRepository.scala

https://issues.rudder.io/issues/25388
Also add zio test junit runner which is needed for making our tests visible

Fixes #25388: Add log for error in JSON campaigns on FS

---

policies/rudderc/src/lib.rs

https://issues.rudder.io/issues/25390

Fixes #25390: Static builds are failing due to missing lib

---

webapp/sources/pom.xml

https://issues.rudder.io/issues/25398
Everything works as with our internal version.

Fixes #25398: Update to Lift-4-M1 release

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/UserSessionInvalidationFilter.scala

https://issues.rudder.io/issues/25414

Fixes #25414: IO forgot to run in spring filter to invalidate session in 25322

---

policies/rudderc/src/lib.rs

https://issues.rudder.io/issues/25420
See: https://github.com/Normation/rudder/pull/5842

Fixes #25420: Backport parent ticket in 8.1

---

webapp/sources/api-doc/components/schemas/user.yml
webapp/sources/api-doc/openapi.src.yml
webapp/sources/api-doc/paths/usermanagement/add.yml
webapp/sources/api-doc/paths/usermanagement/all.yml
webapp/sources/api-doc/paths/usermanagement/id.yml
webapp/sources/api-doc/paths/usermanagement/reload.yml
webapp/sources/api-doc/paths/usermanagement/roles.yml
webapp/sources/api-doc/paths/usermanagement/update-info.yml
webapp/sources/api-doc/paths/usermanagement/update.yml

https://issues.rudder.io/issues/25293
This also needs changes from https://github.com/Normation/rudder/pull/5808

Fixes #25293: API documentation for user management in 8.2

---

webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-compliance.scss

https://issues.rudder.io/issues/25391

Fixes #25391: Score badge background image should not be repeated

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ArchiveApi.scala

https://issues.rudder.io/issues/25449

Fixes #25449: Upmerge breaks 8.2

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/UserSessionInvalidationFilter.scala

https://issues.rudder.io/issues/25463
* admin check is just more important than status check every time : now admin can still pursue with their session, even new admins 
* forcing redirect to login avoids weird behavior, but also prevents notifications to happen, there is something to change later in our setup of `noCometSessionCmd`

Fixes #25463: Session is still invalidated instantly for admin and does not redirect to login

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/ApplicationLogger.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestUtils.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RudderJsonResponse.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/LiftApiDispatcher.scala
webapp/sources/rudder/rudder-templates/src/main/scala/com/normation/templates/FillTemplatesService.scala

https://issues.rudder.io/issues/25438

Fixes #25438: The severity ERROR for Node with ID ‘xxx’ was not found in Rudder’ is too strict

---

webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala

https://issues.rudder.io/issues/25473

Fixes #25473: Impact of session invalidation in user-management test on userrepository in 8.2

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala

https://issues.rudder.io/issues/25477
Missing a .runNow

Fixes #25477: rootAdmin user can't log-in anymore

---

webapp/sources/api-doc/code_samples/curl/usermanagement/activate.sh
webapp/sources/api-doc/code_samples/curl/usermanagement/coverage.sh
webapp/sources/api-doc/code_samples/curl/usermanagement/disable.sh
webapp/sources/api-doc/components/schemas/user-status.yml
webapp/sources/api-doc/openapi.src.yml
webapp/sources/api-doc/paths/usermanagement/activate.yml
webapp/sources/api-doc/paths/usermanagement/coverage.yml
webapp/sources/api-doc/paths/usermanagement/disable.yml

https://issues.rudder.io/issues/25459

Fixes #25459: API documentation for user-management is missing some endpoints

---

webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala

https://issues.rudder.io/issues/25483

Fixes #25483: User cleanup configuration impact on user-management in 8.2

---

webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala

https://issues.rudder.io/issues/25485
Upmerge of https://github.com/Normation/rudder/pull/5883

Fixes #25485: Normalize authentication logs in user-management 8.2 upmerge

---

policies/rudderc/src/lib.rs

https://issues.rudder.io/issues/25489
Instead of failing try to create directory structure, and allow taking the path to the technique file directly.

Fixes #25489: Parent ticket prevents passing a work directory to rudderc

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Agentschedule/ViewUtils.elm

https://issues.rudder.io/issues/25500

Fixes #25500: Typo in agent schedule selector

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/SystemVariableService.scala

https://issues.rudder.io/issues/25506

Fixes #25506: Add a splay-time for relays

---

rust.makefile

https://issues.rudder.io/issues/25524

Fixes #25524: Limit number of  rust jobs in build jobs

---

rust.makefile

https://issues.rudder.io/issues/25541

Fixes #25541: Set build limit to 2 jobs for Rust programs

---

Cargo.lock
ci/typos.Dockerfile
policies/Dockerfile
policies/minifusion/src/os_release.rs
policies/module-types/system-updates/Cargo.toml
policies/module-types/system-updates/src/campaign.rs
policies/module-types/system-updates/src/cli.rs
policies/module-types/system-updates/src/db.rs
policies/module-types/system-updates/src/output.rs
policies/module-types/system-updates/src/package_manager.rs
policies/module-types/system-updates/src/package_manager/apt.rs
policies/module-types/system-updates/src/package_manager/rpm.rs
policies/module-types/system-updates/src/packages.sql
policies/module-types/system-updates/src/scheduler.rs
policies/module-types/system-updates/src/state.rs
policies/module-types/template/src/main.rs
policies/rudder-module-type/src/lib.rs
relay/sources/relayd/Dockerfile
relay/sources/relayd/src/api/remote_run.rs
relay/sources/relayd/src/api/shared_files.rs
relay/sources/relayd/src/output/upstream.rs
relay/sources/rudder-package/Dockerfile
rust-toolchain.toml
sbom/Dockerfile

https://issues.rudder.io/issues/25364

Fixes #25364: Fix the system-updates module

---

webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-template.scss

https://issues.rudder.io/issues/25507

Fixes #25507: Target selection has a weird vertical text

---

relay/sources/rudder-package/src/database.rs

https://issues.rudder.io/issues/25538

Fixes #25538: Detect local install tentative in rudder package

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/AcceptNode.scala

https://issues.rudder.io/issues/25453

Fixes #25453: When accepting a node with a duplicate hostname, there's no error displayed

---

policies/module-types/system-updates/src/hooks.rs
policies/module-types/system-updates/src/output.rs
policies/module-types/system-updates/src/package_manager.rs
policies/rudder-module-type/src/cfengine/log.rs
policies/rudder-module-type/src/cfengine/protocol.rs

https://issues.rudder.io/issues/25575

Fixes #25575: Fix system-updates module technique compatibility

---

policies/rudderc/docs/src/syntax.md
policies/rudderc/src/ir/technique.rs
policies/rudderc/src/technique.schema.json
policies/rudderc/tests/cases/general/reporting/metadata.xml
policies/rudderc/tests/cases/general/reporting/technique.cf
policies/rudderc/tests/cases/general/reporting/technique.ps1
policies/rudderc/tests/cases/general/reporting/technique.yml

https://issues.rudder.io/issues/25600

Fixes #25600: Compliance reporting with type worst-case-percent is not known by rudderc

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder-datatable.js

https://issues.rudder.io/issues/25536
Fixed :

Fixes #25536: Display for checkbox "Show inherited properties" when adding a property column on node pages is broken

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/UserManagement/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/UserManagement/Init.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/UserManagement/View.elm
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/UserManagementSnippet.scala
webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/userManagement.html

https://issues.rudder.io/issues/25461
Same as https://github.com/Normation/rudder-plugins/pull/752, with a simpler `userManagement.html` without unused classes

Fixes #25461: A user should not be able to disable themselves in user management 8.2

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/UserManagement/View.elm

https://issues.rudder.io/issues/25466
The same as https://github.com/Normation/rudder-plugins/pull/754
but needs #5876

Fixes #25466: A user should not be able to delete themselves in user management 8.2

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-template.scss

https://issues.rudder.io/issues/25609

Fixes #25609: Add missing service for plugins

---

rust.makefile

https://issues.rudder.io/issues/25616

Fixes #25616: Take cargo fetures without the option

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/score/GlobalScoreRepository.scala

https://issues.rudder.io/issues/25633

Fixes #25633: It is impossible to delete a node with "ignored" status

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/homePage.js

https://issues.rudder.io/issues/25638

Fixes #25638: Node search query doesn't find any Windows node

---

README.md

https://issues.rudder.io/issues/25642

Fixes #25642: Anchor link to Rudder Core doent work in the README

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ComplianceApi.scala

https://issues.rudder.io/issues/25517
Similar to https://github.com/Normation/rudder/pull/5915. We have a method that can only have user rules but we were collecting all rule types from node reports.

Fixes #25517: System rules are now always shown in directives compliance

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder.js
webapp/sources/rudder/rudder-web/src/main/package-lock.json
webapp/sources/rudder/rudder-web/src/main/package.json
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/Login.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/Groups.scala
webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/apiManagement.html
webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/hooksManagement.html
webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/ruleManagement.html
webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/techniqueEditor.html

https://issues.rudder.io/issues/25602

Fixes #25602: Add notifications on copy to clipboard 

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/JsonResponseObjects.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/properties/Properties.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/properties/NodePropertiesService.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/nodes/TestMergeGroupProperties.scala

https://issues.rudder.io/issues/25632
* Remove FIXME comments and unused code
* Add more precise tests for DAGError, and one for group (missing parent group when computing group properties) 
* Add details of success properties even in case of error in debug logs

Fixes #25632: Resolved properties need more tests and logging for success values

---

Cargo.lock
policies/module-types/system-updates/Cargo.toml

https://issues.rudder.io/issues/25640

Fixes #25640: Use the fixed rust-apt

---

webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ParametersApi.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_parameters.yml
webapp/sources/rudder/rudder-rest/src/test/resources/api_inherited_prop/global_group_param.yml
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TestInheritedProperties.scala

https://issues.rudder.io/issues/25419
Just adding tests to see the outputs on conflicts. 
There is a lot of duplicated data in these outputs, it clutters it and should be removed. 
And there is no need to the json part when the user asked for html (I'm not even sure why we have that output). If the user wants json, he should not ask for html.

Fixes #25419: Add tests for the case where there is conflicts

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RoleApiMapping.scala

https://issues.rudder.io/issues/25645
We really need [this other PR](https://github.com/Normation/rudder/pull/5669/files#diff-a4856d1cc4cf1a4d42d660a6e4c3f98072e5f685683419c57d1cd6f2612a0843R927) to avoid such errors

Fixes #25645: Related rules return an authorization error in UI for non-admin users

---

policies/module-types/system-updates/src/package_manager.rs

https://issues.rudder.io/issues/25653

Fixes #25653: Fix the package manager detection

---

policies/module-types/system-updates/src/db.rs
policies/module-types/system-updates/src/package_manager/apt.rs
policies/module-types/system-updates/src/package_manager/zypper.rs
policies/module-types/system-updates/src/scheduler.rs
policies/module-types/system-updates/src/state.rs

https://issues.rudder.io/issues/25661

Fixes #25661: Fix APT output collection

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/SupportScript.scala

https://issues.rudder.io/issues/25534
The redirect is now impossible, we need a frontend button with an ajax call, and to keep the same UX we need to download the file from the browser itself, within the context of the ajax call where the file is in-memory.
(If debug info get bigger we would likely need a dedicated non REST API path to serve generated debug files and just open the link to them)

Fixes #25534: Debug information download is broken by anti-CSRF header

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
webapp/sources/rudder/rudder-web/src/main/webapp/index.html
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/common-layout.html

https://issues.rudder.io/issues/25658

Fixes #25658: Remove the Clipboard js library as it is no longer required

---

policies/module-types/system-updates/src/campaign.rs
policies/module-types/system-updates/src/main.rs

https://issues.rudder.io/issues/25677

Fixes #25677: Report more errors to the server

---

relay/sources/apache/rudder-vhost.conf

https://issues.rudder.io/issues/25675

Fixes #25675: Add 127.0.0.1 as ServerAlias for multi-vhost  server configuration

---

policies/rudderc/templates/technique.ps1.askama
policies/rudderc/tests/cases/general/escaping/technique.ps1
policies/rudderc/tests/cases/general/form/technique.ps1
policies/rudderc/tests/cases/general/long_method_param_name/technique.ps1
policies/rudderc/tests/cases/general/min/technique.ps1
policies/rudderc/tests/cases/general/ntp/technique.ps1
policies/rudderc/tests/cases/general/param_in_condition/technique.ps1
policies/rudderc/tests/cases/general/policy_mode/technique.ps1
policies/rudderc/tests/cases/general/reporting/technique.ps1
policies/rudderc/tests/cases/general/variables/technique.ps1

https://issues.rudder.io/issues/25708

Fixes #25708: Windows techniques fail to catch the Nustache.Core.RaiseExceptionOnEmptyStringValue errors

---

policies/module-types/system-updates/README.md
policies/module-types/system-updates/src/db.rs

https://issues.rudder.io/issues/25745

Fixes #25745: db error about pid column

---

policies/module-types/system-updates/src/runner.rs

https://issues.rudder.io/issues/25747

Fixes #25747: Update schedule is not sen anymore

---

policies/module-types/system-updates/src/runner.rs

https://issues.rudder.io/issues/25749

Fixes #25749: Module crashes after upgrade

---

policies/module-types/system-updates/src/package_manager/apt.rs
policies/module-types/system-updates/src/package_manager/apt/progress.rs

https://issues.rudder.io/issues/25751

Fixes #25751: APT update output mis-handles interactive output

---

policies/rudderc/src/ir/value.rs

https://issues.rudder.io/issues/25771

Fixes #25771: Broken parsing of node inventory variable

---

relay/sources/relayd/src/main.rs

https://issues.rudder.io/issues/25754

Fixes #25754: Stacktrace in relayd on invalid run time file name

---

README.md

https://issues.rudder.io/issues/25755

Fixes #25755: Fix the logo in the README

---

policies/rudderc/src/ir/value.rs

https://issues.rudder.io/issues/25775

Fixes #25775: Missing annotation on a rudderc test case

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/history/impl/InventoryHistoryJdbcRepository.scala

https://issues.rudder.io/issues/25782
Consequence of https://github.com/Normation/rudder/pull/5854 json serialization normalisation toward UTC.

Fixes #25782: Bad postgresql time conversion for event log cleaning

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/comet/AsyncDeployment.scala

https://issues.rudder.io/issues/25712
**Root cause :** We cannot use `WithNonce` here because the actor is within a specific "lift actor workflow" and it does not see the nonce value of the request
**Solution :** We use the `partialUpdate` method which is the actor scheduling some AJAX after the main page render, and the AJAX is allowed to execute without the nonce.
We need to factor some functions that are called too many times, to be called at the end, like `initBsTooltips()`

Fixes #25712: CSP violations from status tab in utilities pages

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/GitTechniqueReader.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/cfclerk/services/JGitPackageReaderTest.scala

https://issues.rudder.io/issues/23959

Fixes #23959: When removing files from a technique, it might get disabled unexpectedly

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/users/UserRepository.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/users/UserRepositoryTest.scala

https://issues.rudder.io/issues/25681
We need to _add_ the user instead of _set_ all existing users with the current provisioned one.
It just needs to reuse the `setExistingUsers` method, with the new user appended to the list of existing ones. 
I added unit tests, that were not passing when another `OIDC` user is `set`.

Fixes #25681: OIDC users are marked as deleted after a new user is provisionned

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala

https://issues.rudder.io/issues/25715

Fixes #25715: Avoid Content-Security-Policy-Report-Only headers in dev mode

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder.js
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/EventListDisplayer.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/LogDisplayer.scala

https://issues.rudder.io/issues/25720
The `initDatePicker` function is adapted with an additional `timezone` argument (a IANA one, that can be used to ["convert" a JS date in the right timezone](https://stackoverflow.com/a/53652131) i.e. it has the right value in the datepicker with a selected timezone).
I used the server timezone because all server information is returned in the server timezone so it makes more sense.

Fixes #25720: Technical and event logs get log from browser timezone instead of server timezone

---

webapp/sources/api-doc/openapi.src.yml

https://issues.rudder.io/issues/25800

Fixes #25800: API version for 8.2 is 20

---

webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala

https://issues.rudder.io/issues/25799
Follows https://github.com/Normation/rudder/pull/5951

Fixes #25799: Upmerge addUser method in tests added for OIDC provisioning

---

api-doc/build.py
api-doc/package-lock.json
api-doc/redocly.yml

https://issues.rudder.io/issues/25809

Fixes #25809: Update and fix the API doc tooling

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/GroupsApi.scala

https://issues.rudder.io/issues/25687
Add `nonEmpty` condition similarly to https://github.com/Normation/rudder/pull/5937/files, to return the list of group properties when there are no nodes

Fixes #25687: Same as parent ticket for branch 8.1

---

relay/sources/systemd/rudder-package.service

https://issues.rudder.io/issues/25821

Fixes #25821: rudder package log error when trying to update licence on a relay

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/DynGroupUpdaterService.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/SearchNodeComponent.scala

https://issues.rudder.io/issues/25820
Correct the case where updating a dynamic group with empty query was in error and also make a bit clearer the case where there is no criterion in the UI: 
When group is created: 
When we click on the plus:

Fixes #25820: On new groups, adding a prop leads to "No query defined for group" error

---

policies/rudderc/tests/cases/general/reporting/technique.cf
policies/rudderc/tests/cases/general/variables/technique.cf
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/25829

Fixes #25829: Improve config log wording

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/users/UserRepository.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/users/UserRepositoryTest.scala

https://issues.rudder.io/issues/25825
* Don't add deleted users back : the `computeUpdatedUserList` method which is reused when "setting existing users" has logic to handle "deleted" and "disabled" user differently, deleted users should not be passed back to existing users (the logic of the method will make already disabled ones remain disabled)
* Add unit tests, 2 tests cases are added : 
* a simple one to disable Bob
* another one to check that adding a new user Xavier does not change the state of others : Bob -> disabled, William -> deleted
Every other changes in the test file is just about moving the values used within the test cases right above the block of the test, the diff cannot just guess it

Fixes #25825: Deleted OIDC user are reactivated after new provisioning

---

Cargo.lock
ci/rust.sh
ci/typos.Dockerfile
policies/Dockerfile
policies/minifusion/Cargo.toml
policies/minifusion/src/main.rs
policies/rudder-commons/Cargo.toml
policies/rudderc/Cargo.toml
policies/rudderc/tests/cases/general/escaping/metadata.xml
policies/rudderc/tests/cases/general/form/metadata.xml
policies/rudderc/tests/cases/general/long_method_param_name/metadata.xml
policies/rudderc/tests/cases/general/min/metadata.xml
policies/rudderc/tests/cases/general/ntp/metadata.xml
policies/rudderc/tests/cases/general/param_in_condition/metadata.xml
policies/rudderc/tests/cases/general/policy_mode/metadata.xml
policies/rudderc/tests/cases/general/reporting/metadata.xml
policies/rudderc/tests/cases/general/variables/metadata.xml
policies/rudderc/tests/metadata/serialized.xml
relay/sources/relayd/Cargo.toml
relay/sources/relayd/Dockerfile
relay/sources/relayd/benches/benches.rs
relay/sources/relayd/src/configuration/main.rs
relay/sources/relayd/src/output/database.rs
relay/sources/rudder-package/Cargo.toml
relay/sources/rudder-package/Dockerfile
rust-toolchain.toml
rust.makefile
sbom/Dockerfile

https://issues.rudder.io/issues/25843

Fixes #25843: Update Rust dependencies

---

policies/rudderc/src/backends/unix.rs
policies/rudderc/src/backends/unix/cfengine/bundle.rs
policies/rudderc/src/backends/unix/cfengine/promise.rs
policies/rudderc/src/backends/unix/ncf/dry_run_mode.rs
policies/rudderc/src/backends/unix/ncf/method_call.rs
policies/rudderc/src/backends/unix/ncf/technique.rs
policies/rudderc/tests/cases/general/escaping/technique.cf
policies/rudderc/tests/cases/general/form/technique.cf
policies/rudderc/tests/cases/general/long_method_param_name/technique.cf
policies/rudderc/tests/cases/general/min/technique.cf
policies/rudderc/tests/cases/general/ntp/technique.cf
policies/rudderc/tests/cases/general/param_in_condition/technique.cf
policies/rudderc/tests/cases/general/policy_mode/technique.cf
policies/rudderc/tests/cases/general/reporting/technique.cf
policies/rudderc/tests/cases/general/variables/technique.cf
policies/rudderc/tests/compile.rs

https://issues.rudder.io/issues/25776

Fixes #25776: Create a global method call counter to help provide more unicity

---

policies/module-types/system-updates/src/hooks.rs
policies/module-types/system-updates/src/output.rs
policies/module-types/system-updates/src/package_manager/rpm.rs
policies/module-types/system-updates/src/package_manager/yum.rs
policies/module-types/system-updates/src/package_manager/zypper.rs
policies/module-types/system-updates/src/system.rs

https://issues.rudder.io/issues/25867

Fixes #25867: Error in update campaign

---

deny.toml

https://issues.rudder.io/issues/25872

Fixes #25872: Allow unicode license

---

webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/DataTypes.scala

https://issues.rudder.io/issues/25870

Fixes #25870: Better log for bad node key

---

Cargo.lock
relay/sources/rudder-package/Cargo.toml
relay/sources/rudder-package/src/config.rs
relay/sources/rudder-package/src/repository.rs

https://issues.rudder.io/issues/25873

Fixes #25873: Use secrecy to store the password

---

webapp/sources/pom.xml

https://issues.rudder.io/issues/25758

Fixes #25758: Update Scala dependencies

---

Cargo.lock
policies/rudder-commons/Cargo.toml
policies/rudder-commons/src/lib.rs

https://issues.rudder.io/issues/25871

Fixes #25871: Allow validating JSON parameters in methods

---

Cargo.lock

https://issues.rudder.io/issues/25888

Fixes #25888: Vulnerability in diesel

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/score/ComplianceScore.scala
webapp/sources/rudder/rudder-web/src/main/javascript/rudder/homePage.js

https://issues.rudder.io/issues/25813

Fixes #25813: a node with no rules applied has a score of F

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/facts/nodes/TestCoreNodeFactInventory.scala

https://issues.rudder.io/issues/25866

Fixes #25866: After restart, nodes that were set back to default policy mode return to their previous overriden mode

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/api/ApiAccountRepository.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/facts/nodes/TestCoreNodeFactInventory.scala

https://issues.rudder.io/issues/25902

Fixes #25902: Remove support for clear-text API tokens

---

webapp/sources/api-doc/components/schemas/campaign-schedule-daily.yml
webapp/sources/api-doc/components/schemas/campaign-schedule-monthly.yml
webapp/sources/api-doc/components/schemas/campaign-schedule-weekly.yml

https://issues.rudder.io/issues/25900

Fixes #25900: Add API documentation for campaign schedules for tz field

---

policies/module-types/system-updates/src/package_manager/yum.rs

https://issues.rudder.io/issues/25925

Fixes #25925: Error in update campaign - yum always reboots

---

policies/module-types/system-updates/src/hooks.rs
policies/module-types/system-updates/src/output.rs
policies/module-types/system-updates/src/package_manager/apt.rs
policies/module-types/system-updates/src/package_manager/rpm.rs
policies/module-types/system-updates/src/package_manager/yum.rs
policies/module-types/system-updates/src/package_manager/zypper.rs
policies/module-types/system-updates/src/system.rs

https://issues.rudder.io/issues/25926

Fixes #25926: Dont output package lists in report

---

webapp/sources/rudder/rudder-web/src/main/.nsprc

https://issues.rudder.io/issues/25937

Fixes #25937: Remove security check on a js dev dependency 

---

webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-template.scss

https://issues.rudder.io/issues/25923

Fixes #25923: Add padding to trees to prevent the last element from being hidden when a link is hovered

---

policies/module-types/system-updates/src/campaign.rs

https://issues.rudder.io/issues/25940

Fixes #25940: Wrong error message when upgrading a non-existent package

---

Cargo.lock
relay/sources/relayd/Cargo.toml
relay/sources/relayd/benches/benches.rs
relay/sources/relayd/src/configuration/main.rs
relay/sources/relayd/src/output/database.rs
relay/sources/relayd/src/output/upstream.rs
relay/sources/relayd/tests/files/config/main.conf

https://issues.rudder.io/issues/24997

Fixes #24997: Add rsync configuration datastructure to relayd

---

relay/sources/rudder-package/src/lib.rs
relay/sources/rudder-package/src/license.rs

https://issues.rudder.io/issues/25988

Fixes #25988: Allow installing the licenses with rudder-package - bug in parent

---

policies/rudderc/tests/cases/general/escaping/metadata.xml
policies/rudderc/tests/cases/general/escaping/technique.cf

https://issues.rudder.io/issues/25998

Fixes #25998: Broken policies test

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/QuickSearch/View.elm

https://issues.rudder.io/issues/25297

Fixes #25297: Quicksearch filters do not work

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/AcceptNode.scala

https://issues.rudder.io/issues/25973
Highlight with a danger callout, put text in strong to make it pop more (only the callout is too light)

Fixes #25973: Acceptation error with new node on hostname duplication is not hightlitghed

---

policies/rudderc/src/lib.rs
policies/rudderc/tests/cases/general/min_yaml/metadata.xml
policies/rudderc/tests/cases/general/min_yaml/technique.cf
policies/rudderc/tests/cases/general/min_yaml/technique.ps1
policies/rudderc/tests/cases/general/min_yaml/technique.yaml
policies/rudderc/tests/compile.rs

https://issues.rudder.io/issues/26036

Fixes #26036: Allow the yaml extension for YAML files

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/users/UserRepository.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/users/UserRepositoryTest.scala

https://issues.rudder.io/issues/26056
The bug is because of an `OR` instead of `AND` in a `SELECT` query...
The change only impacts the disabling of users, this is the only place where the `select()` is used with both filters, so changing the semantics of the method is safe (and also more consistent).
Tests are added to the Jdbc repository, to validate the filtering behaves as we want

Fixes #26056: Non admin users in file get disabled even if last login parameter does not exceed the scheduled date

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala

https://issues.rudder.io/issues/26002
So, we were calling an ajax method, in the return there was a `window.location.hash = xxxx`, but in https://github.com/Normation/rudder/pull/5760 we added an event listener on window location hash which triggers an ajax call for the same update. 
I'm not sure why it stops after two round, it could have looped for ever.

Fixes #26002: The directive page is much slower with Rudder 8.1 than in 7.3

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Compliance/HtmlString.elm
webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder-datatable.js

https://issues.rudder.io/issues/25617
Remove percent displays that causes the discordance between both tabs

Fixes #25617: Discordance on node compliance between two tabs

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala

https://issues.rudder.io/issues/26068

Fixes #26068: Deny iframes in Rudder

---

deny.toml

https://issues.rudder.io/issues/26085

Fixes #26085: Vulnerability in idna

---

deny.toml

https://issues.rudder.io/issues/26086

Fixes #26086: Allow LGPL license in crates

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/facts/nodes/NodeFactChangeEventCallback.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/PostCommits.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/score/GlobalScoreRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/score/ScoreRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/score/ScoreService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/NewNodeManager.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/RemoveNodeService.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/score/ScoreServiceTest.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/HomePage.scala

https://issues.rudder.io/issues/25948

Fixes #25948: Score breakdown has inconsistent numbers

---

webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_nodes.yml
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/26108

Fixes #26108: Build error in 8.2 (upmerge?)

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTechnique.elm
webapp/sources/rudder/rudder-web/src/main/style/rudder/_rudder-variables.scss
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-bootstrap.scss
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-hooks.scss
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-menu.scss
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-node.scss
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-technique-editor.scss
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-template.scss

https://issues.rudder.io/issues/26028
Replacing previous PR: https://github.com/Normation/rudder/pull/6075

Fixes #26028: Make fold-out menu css accessible everywhere in Rudder

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/EditorTechnique.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/migration/MigrateJsonTechniquesService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/yaml/YamlTechnique.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestEditorTechniqueWriter.scala

https://issues.rudder.io/issues/26116
Just adding two fields to Yaml and Editor techniques classes

Fixes #26116: Add Scala backend for technique loops

---

webapp/sources/rudder/rudder-rest/src/test/resources/api/api_compliance.yml

https://issues.rudder.io/issues/26133
The tests have changed in 8.3, there are different from https://github.com/Normation/rudder/pull/6108

Fixes #26133: Test upmerge fail when getting directive compliance by rule

---

webapp/sources/pom.xml

https://issues.rudder.io/issues/26134

Fixes #26134: Change Rudder current-year to 2025

---

policies/rudderc/src/backends/unix/ncf/method_call.rs
policies/rudderc/src/ir/technique.rs
policies/rudderc/tests/cases/general/loops/technique.cf
policies/rudderc/tests/cases/general/loops/technique.ps1
policies/rudderc/tests/cases/general/loops/technique.yml

https://issues.rudder.io/issues/26120

Fixes #26120: Make sure that bundle arity is always strict when resolving loops

---

webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/node.html

https://issues.rudder.io/issues/26160
There has been a renaming in https://github.com/Normation/rudder/pull/6107/files#diff-2bf9e4ea462799991a98517933eb70ac8cb4841c894d3a354d6f415dc1c8854dL51

Fixes #26160: Node details page is blank

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/plugins/PluginSettings.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/PluginInternalApi.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TestRestPluginInfo.scala
webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/ApiCalls.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/Init.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/JsonEncoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/View.elm
webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/plugins/RudderPlugin.scala
webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/pluginInformation.html

https://issues.rudder.io/issues/26145
Add the structures necessary to be able to display plugin in the UI : 
* backend : structures similar to the plugins public API, error messages on plugins
* frontend : Elm `Plugins` app with a simple `ul li` list of plugin data

Fixes #26145: Bootstrap the list of plugins in the UI

---

api-doc/package-lock.json

https://issues.rudder.io/issues/26188

Fixes #26188: Update api doc tooling

---

Cargo.lock
ci/typos.Dockerfile
policies/Dockerfile
policies/module-types/inventory/src/main.rs
policies/rudder-cli/Cargo.toml
policies/rudder-commons/Cargo.toml
policies/rudder-commons/src/lib.rs
policies/rudderc/src/compiler.rs
relay/sources/relayd/Dockerfile
relay/sources/rudder-package/Cargo.toml
relay/sources/rudder-package/Dockerfile
rust-toolchain.toml
sbom/Dockerfile

https://issues.rudder.io/issues/26186

Fixes #26186: Update to Rust 1.84.0

---

Cargo.lock
policies/module-types/augeas/Cargo.toml

https://issues.rudder.io/issues/26227

Fixes #26227: raugeas does not build on arm

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewMethod.elm
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-technique-editor.scss

https://issues.rudder.io/issues/26213
We can now modify the value of items directly from the list, and a message indicates how to use the iterator syntax.
Here is a preview :

Fixes #26213: Make it possible to edit the values of items in a foreach

---

policies/rudderc/src/backends/unix.rs
policies/rudderc/src/backends/unix/cfengine/bundle.rs
policies/rudderc/src/backends/unix/cfengine/promise.rs
policies/rudderc/src/backends/unix/ncf/method_call.rs
policies/rudderc/tests/cases/general/escaping/technique.cf
policies/rudderc/tests/cases/general/form/technique.cf
policies/rudderc/tests/cases/general/long_method_param_name/technique.cf
policies/rudderc/tests/cases/general/min/technique.cf
policies/rudderc/tests/cases/general/min_yaml/technique.cf
policies/rudderc/tests/cases/general/ntp/technique.cf
policies/rudderc/tests/cases/general/param_in_condition/technique.cf
policies/rudderc/tests/cases/general/policy_mode/technique.cf
policies/rudderc/tests/cases/general/reporting/technique.cf
policies/rudderc/tests/cases/general/variables/technique.cf

https://issues.rudder.io/issues/26138

Fixes #26138: Undefined variables can lead to unwated policy override overrides

---

policies/rudderc/src/backends/unix.rs
policies/rudderc/tests/cases/general/policy_mode/technique.cf

https://issues.rudder.io/issues/26298

Fixes #26298: Force the block policy mode override to occur only in pass3

---

policies/rudderc/src/backends/unix/ncf/method_call.rs
policies/rudderc/tests/cases/general/escaping/technique.cf
policies/rudderc/tests/cases/general/form/technique.cf
policies/rudderc/tests/cases/general/long_method_param_name/technique.cf
policies/rudderc/tests/cases/general/loops/technique.cf
policies/rudderc/tests/cases/general/loops_with_main_branch_without_condition/technique.cf
policies/rudderc/tests/cases/general/min/technique.cf
policies/rudderc/tests/cases/general/min_yaml/technique.cf
policies/rudderc/tests/cases/general/ntp/technique.cf
policies/rudderc/tests/cases/general/param_in_condition/technique.cf
policies/rudderc/tests/cases/general/policy_mode/technique.cf
policies/rudderc/tests/cases/general/reporting/technique.cf
policies/rudderc/tests/cases/general/variables/technique.cf

https://issues.rudder.io/issues/26301

Fixes #26301: Missing the pass3 on the 8.3 branch

---

policies/module-types/platform-support.md

https://issues.rudder.io/issues/26323

Fixes #26323: Create a doc for Rust agent support

---

webapp/sources/rudder/rudder-web/src/main/resources/logback.xml
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/endconfig/migration/FixedPathLoggerMigration.scala
webapp/sources/rudder/rudder-web/src/test/resources/logback-samples/logback-8.2-migrated.xml
webapp/sources/rudder/rudder-web/src/test/resources/logback-samples/logback-8.2.xml
webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/endconfig/migration/TestMigrateLogbackXml.scala

https://issues.rudder.io/issues/26303
Parses logback.xml, check wether fixed logfile appender exist (check if it has an if element that has an appender element that has a STDOUT name), then add/remove elements that are needed in 8.3
Make a backup of the current logback file, replace with new logback file
Comment that are outside the first element are removed ... Maybe we can add them , but i don't they are this important

Fixes #26303: Migrate logback.xml to new fixed logfile 

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/CampaignRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/MainCampaignService.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/CampaignApi.scala

https://issues.rudder.io/issues/26337

Fixes #26337: Get campaign is creating an empty file when campaign does not exist

---

relay/sources/rudder-package/src/lib.rs

https://issues.rudder.io/issues/26175

Fixes #26175: “rudder package upgrade” alone does not upgrade any plugin

---

Jenkinsfile-security

https://issues.rudder.io/issues/26385

Fixes #26385: Add a NVD API key to the Jenkins-security jobs

---

Jenkinsfile-security

https://issues.rudder.io/issues/26394

Fixes #26394: Wrong syntax used in parent ticket

---

policies/lib/tests/acceptance/30_generic_methods/abort_default.cf
policies/lib/tree/30_generic_methods/permissions.cf
policies/lib/tree/30_generic_methods/user_password_hash.cf

https://issues.rudder.io/issues/26401

Fixes #26401: Fix typos in comments from parent ticket

---

qa-test

https://issues.rudder.io/issues/26403

Fixes #26403: Ignore policies tests scripts in shellcheck

---

relay/sources/rudder-package/src/lib.rs

https://issues.rudder.io/issues/26387

Fixes #26387: Parent break enable/disable commands

---

policies/module-types/system-updates/src/hooks.rs

https://issues.rudder.io/issues/26406

Fixes #26406: Test for hooks is failing in Docker CI

---

Jenkinsfile
Jenkinsfile-security

https://issues.rudder.io/issues/26414

Fixes #26414: Cache is not shared anymode

---

relay/sources/rudder-package/src/lib.rs

https://issues.rudder.io/issues/26424

Fixes #26424: Parent break enable/disable commands

---

ci/rust.sh

https://issues.rudder.io/issues/26442

Fixes #26442: Update cargo auditable for Rust 2024

---

policies/module-types/system-updates/src/output.rs

https://issues.rudder.io/issues/26441

Fixes #26441: Sometimes the error output sent to the server only contain only empty lines

---

relay/sources/rudder-package/src/archive.rs
relay/sources/rudder-package/src/lib.rs

https://issues.rudder.io/issues/26451

Fixes #26451: Allow skipping the postinst

---

webapp/sources/pom.xml
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/TechniqueRepositoryImpl.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/AutomaticReportsCleaner.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/facts/nodes/NodeFact.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/properties/MergeNodeProperties.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/healthcheck/HealthcheckNotificationService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/NodeStatusReportRepository.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/queries/NodeQueryCriteriaDataTest.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/reports/StatusReportTest.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RudderJsonResponse.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/Compliance.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ArchiveApi.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TraitTestApiFromYamlFiles.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/earlyconfig/ldap/CheckAddSpecialNodeGroupsDescription.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/AsyncComplianceService.scala
webapp/sources/rudder/rudder-web/src/test/scala/com/normation/plugins/RudderPluginJsonTest.scala
webapp/sources/rudder/rudder-web/src/test/scala/com/normation/rudder/web/services/ReportLineTest.scala
webapp/sources/utils/src/test/scala/com/normation/ZioCommonsTest.scala

https://issues.rudder.io/issues/26459

Fixes #26459: Missing commit in parent PR

---

webapp/sources/api-doc/openapi.src.yml
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/26481

Fixes #26481: Add 8.3 api doc and 8.2 api deprecation

---

Jenkinsfile
ci/methods.Dockerfile
policies/lib/tests/integration/mod.rs
policies/lib/tests/testlib/method_test_suite.rs
policies/rudderc/src/backends/unix/cfengine.rs

https://issues.rudder.io/issues/26485

Fixes #26485: Integrate the methods tests to the CI

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ComputeNodeStatusReportService.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala

https://issues.rudder.io/issues/26464

Fixes #26464: Stackoverflow in NodeStatusReports event computing

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/score/ScoreService.scala

https://issues.rudder.io/issues/26458

Fixes #26458: Errors in callback 'trigger-score-update' in the logs when a node is deleted

---

policies/lib/tree/30_generic_methods/sharedfile_to_node.cf

https://issues.rudder.io/issues/26501

Fixes #26501: Sharefile to node method doesn't work in audit mode (8.3+)

---

policies/lib/tree/30_generic_methods/user_secondary_group.cf

https://issues.rudder.io/issues/26497

Fixes #26497: user_secondary_groups reporting can conflict with itself when used in foreach loop

---

policies/lib/tree/30_generic_methods/service_disabled.cf

https://issues.rudder.io/issues/26521

Fixes #26521:  Fix the Service-Disabled method on Windows

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder-datatable.js

https://issues.rudder.io/issues/26260
Now with the two nodes tables in the same page, we need to select elements within the table wrapper, this consists in prepending the selector of the wrapper to all selectors (most of them are selector on HTML id but jQuery selectors are not strict on uniqueness)

Fixes #26260: The "Edit columns" button in the nodes webpage is displayed three times

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/score/ScoreService.scala

https://issues.rudder.io/issues/26504

Fixes #26504: Score are not cleaned correctly at startup

---

webapp/sources/api-doc/code_samples/curl/api-accounts/all.sh
webapp/sources/api-doc/code_samples/curl/api-accounts/create.sh
webapp/sources/api-doc/code_samples/curl/api-accounts/delete.sh
webapp/sources/api-doc/code_samples/curl/api-accounts/get.sh
webapp/sources/api-doc/code_samples/curl/api-accounts/regenerate.sh
webapp/sources/api-doc/code_samples/curl/api-accounts/update.sh
webapp/sources/api-doc/components/parameters/api-account-id.yml
webapp/sources/api-doc/components/schemas/api-account-new.yml
webapp/sources/api-doc/components/schemas/api-account-update.yml
webapp/sources/api-doc/components/schemas/api-account.yml
webapp/sources/api-doc/openapi.src.yml
webapp/sources/api-doc/paths/api-accounts/all.yml
webapp/sources/api-doc/paths/api-accounts/id.yml
webapp/sources/api-doc/paths/api-accounts/regenerate-token.yml

https://issues.rudder.io/issues/26503
Add openapi documentation for `/apiaccounts*` paths.

Fixes #26503: API documentation for API account rest API

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/Archives.scala
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/administration/policyBackup.html

https://issues.rudder.io/issues/26531

Fixes #26531: Naming inconsistencies for archive/backup page

---

policies/rudderc/src/backends/unix/ncf/method_call.rs

https://issues.rudder.io/issues/26512

Fixes #26512: rudderc generate invalid method call when using methods that are not compatible with Linux 

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/PluginData.elm

https://issues.rudder.io/issues/26565

Fixes #26565: Links in plugins page should redirect to the local doc

---

policies/rudderc/src/backends/windows.rs
policies/rudderc/tests/cases/general/form/technique.ps1
policies/rudderc/tests/cases/general/long_method_param_name/technique.ps1
policies/rudderc/tests/cases/general/min/technique.ps1
policies/rudderc/tests/cases/general/min_yaml/technique.ps1
policies/rudderc/tests/cases/general/ntp/technique.ps1
policies/rudderc/tests/cases/general/param_in_condition/technique.ps1
policies/rudderc/tests/cases/general/policy_mode/technique.ps1
policies/rudderc/tests/cases/general/reporting/technique.ps1
policies/rudderc/tests/cases/general/variables/technique.ps1

https://issues.rudder.io/issues/26558

Fixes #26558: Character in method name reports an error while agent run

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RudderJsonResponse.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/LiftApiDispatcher.scala

https://issues.rudder.io/issues/26535

Fixes #26535: prettify parameter is ignored in API calls

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/api/ApiAccountDiff.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDiffMapper.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/ApiAccount.scala
webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/ViewUtils.elm

https://issues.rudder.io/issues/26515
- the case for creation time was missing, so adding it
- also changed a little bit UI so that we can see if a token exists or no. It will need more changes because we will want to be able to just delete a token, perhaps think about the look => https://issues.rudder.io/issues/26538

Fixes #26515: Missing api account account creation diff element

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewMethod.elm

https://issues.rudder.io/issues/26560

Fixes #26560: Rudder 8.3 Beta 2 : Result conditions duplicated in technique editor

---

policies/rudderc/tests/cases/general/unsupported_methods/metadata.xml
policies/rudderc/tests/cases/general/unsupported_methods/technique.cf
policies/rudderc/tests/cases/general/unsupported_methods/technique.ps1
policies/rudderc/tests/cases/general/unsupported_methods/technique.yml
policies/rudderc/tests/lib/common/30_generic_methods/powershell_execution.cf
policies/rudderc/tests/lib/common/30_generic_methods/user_group.cf

https://issues.rudder.io/issues/26556

Fixes #26556: Add a technique test case on unsupported methods

---

relay/sources/rudder-package/src/repository.rs

https://issues.rudder.io/issues/26493

Fixes #26493: rudder package update never test nor use the crendentials

---

Jenkinsfile

https://issues.rudder.io/issues/26588

Fixes #26588: Use 8.3 package in 9.0 tests for now

---

policies/lib/tests/integration/condition_from_expression_test.rs
policies/lib/tests/integration/condition_from_variable_existence_test.rs
policies/lib/tests/integration/condition_from_variable_match_test.rs
policies/lib/tests/integration/mod.rs
policies/lib/tests/testlib/given.rs
policies/lib/tests/testlib/method_to_test.rs
policies/lib/tests/testlib/test_result.rs
policies/lib/tree/30_generic_methods/condition_from_expression.cf
policies/lib/tree/30_generic_methods/condition_from_expression_persistent.cf
policies/lib/tree/30_generic_methods/condition_from_variable_existence.cf
policies/lib/tree/30_generic_methods/condition_from_variable_match.cf
policies/lib/tree/30_generic_methods/condition_once.cf
policies/lib/tree/30_generic_methods/directory_absent.cf

https://issues.rudder.io/issues/25936

Fixes #25936: Port condition_from methods to log v4+

---

webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/NodeInventory.scala
webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/InventoryMapper.scala
webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/LDAPConstants.scala
webapp/sources/rudder/rudder-web/src/main/resources/ldapObjectAndAttributes.properties
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-main.scss

https://issues.rudder.io/issues/26557

Fixes #26557: Missing Windows 11 OS Name

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/tree.js

https://issues.rudder.io/issues/26348
Optimizing the lookup for the events to reassign to a node in the directive tree : instead of searching every node to their corresponding events in `O(n)`, we can use a `Map` and use the DOM element ID as key when traversing it.
Querying for the DOM element by the ID is quite fast, and negligible even on the load-testing machine with a thousand directives.

Fixes #26348: Timeout on directive save

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/View.elm

https://issues.rudder.io/issues/26575

Fixes #26575: Error message in plugin page is not visible at all

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/RuleValGeneratedHookService.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/26595

Fixes #26595: Add a hook during policy generation

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/score/ScoreRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/score/ScoreService.scala

https://issues.rudder.io/issues/26596

Fixes #26596: Add a function to clean a type of score for a node

---

policies/rudderc/tests/cases/general/unsupported_methods/technique.ps1

https://issues.rudder.io/issues/26618

Fixes #26618: Broken policies test in 8.2

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala

https://issues.rudder.io/issues/26616

Fixes #26616: Upmerge need spotless fix

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/26416

Fixes #26416: JVM platform limit requires splitting services in RudderConfig

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/TechniqueReader.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitArchivers.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/AcceptNode.scala

https://issues.rudder.io/issues/26625
`AcceptNode` wasn't a `DispatchSnippet` so we had a direct call from the HTML to scala method without indirection. I changed it to dispatch snippet, so that we can refactor without fearing to break thing without compiler error.
Also correct some unrelated typos

Fixes #26625: Ubuntu 22.04 agent cannot be accepted on the server

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/homePage.js

https://issues.rudder.io/issues/26544

Fixes #26544: SearchNodes page in Rudder : Error 404

---

Cargo.lock
policies/module-types/template/Cargo.toml
policies/module-types/template/README.md
policies/module-types/template/src/cli.rs
policies/module-types/template/src/lib.rs
policies/module-types/template/src/minijinja_filters.rs
policies/module-types/template/tests/cli.rs
policies/module-types/template/tests/minijinja.rs

https://issues.rudder.io/issues/26614

Fixes #26614: Adding Ansible compatible filters for minijinja engine

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewMethod.elm
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-technique-editor.scss

https://issues.rudder.io/issues/26630
I've tried to fix vertical alignment issues as much as possible using flexbox properties, but some problems seem to be related to the browser font (for example, no specific css rule is applied to the “_A friendly name for this component_” input placeholder, in my firefox and chrome my text is well aligned, but the font seems different from the one on the ticket screenshots).
So I don't know if there's a universal way of fixing these problems...

Fixes #26630: Dubius vertical alignement in generic method

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/MethodConditions.elm

https://issues.rudder.io/issues/26628

Fixes #26628: Windows Server 2025 not present in technique editor conditions

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/StatusReports.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/reports/TestBlockCompliance.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/Compliance.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_compliance.yml

https://issues.rudder.io/issues/26604

Fixes #26604: Compliance by directive is broken

---

policies/lib/tests/acceptance/30_generic_methods/permissions_acl_entry.non_recursive.audit.error.cf
policies/lib/tests/acceptance/30_generic_methods/permissions_acl_entry.non_recursive.error.cf
policies/lib/tests/acceptance/30_generic_methods/permissions_acl_entry.recursive.audit.error.cf
policies/lib/tests/acceptance/30_generic_methods/permissions_acl_entry.recursive.error.cf

https://issues.rudder.io/issues/26660

Fixes #26660: Fix several typos

---

webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-settings.scss

https://issues.rudder.io/issues/26587

Fixes #26587: Some settings buttons are grey

---

policies/rudderc/src/ir/technique.rs
policies/rudderc/tests/cases/general/loops/metadata.xml
policies/rudderc/tests/cases/general/loops/technique.cf
policies/rudderc/tests/cases/general/loops/technique.ps1
policies/rudderc/tests/cases/general/loops_with_main_branch_without_condition/metadata.xml
policies/rudderc/tests/cases/general/loops_with_main_branch_without_condition/technique.cf
policies/rudderc/tests/cases/general/loops_with_main_branch_without_condition/technique.ps1

https://issues.rudder.io/issues/26652

Fixes #26652: Compliance repeated when using the new “foreach” loops

---

policies/lib/tree/30_generic_methods/rudder_inventory_trigger.cf

https://issues.rudder.io/issues/26684

Fixes #26684: Inventory trigger method broken on Linux

---

policies/rudderc/src/backends/unix/ncf/method_call.rs
policies/rudderc/tests/cases/general/loops/technique.cf
policies/rudderc/tests/cases/general/loops_with_main_branch_without_condition/technique.cf

https://issues.rudder.io/issues/26687

Fixes #26687: Invalid promises generated when using loop, missing call bundles

---

webapp/sources/api-doc/paths/change-requests/accept.yml
webapp/sources/api-doc/paths/change-requests/all.yml
webapp/sources/api-doc/paths/change-requests/id.yml

https://issues.rudder.io/issues/26675

Fixes #26675: Error in documentation /api/changeRequests response data

---

webapp/sources/rudder/rudder-web/src/main/elm/elm.json

https://issues.rudder.io/issues/26694
Running the recommended fix: 
```
[nix-shell:~/IdeaProjects/rudder/webapp/sources/rudder/rudder-web/src/main/elm]$ elm-json uninstall justinmimbs/date
-- PACKAGE CHANGES READY -------------------------------------------------------
I want to make some changes to your direct dependencies
- [DEL] justinmimbs/date 4.1.0
I want to make some changes to your indirect dependencies
- [ADD] justinmimbs/date 4.1.0
```

Fixes #26694: Unused justinmimbs/date Elm dependency

---

policies/lib/tree/20_cfe_basics/files.cf
policies/lib/tree/30_generic_methods/file_augeas.cf
policies/module-types/augeas/src/augeas.rs
policies/module-types/augeas/src/dsl/interpreter.rs
policies/module-types/augeas/src/lib.rs
policies/module-types/augeas/src/parameters.rs
policies/rudderc/src/backends/unix/ncf/method_call.rs

https://issues.rudder.io/issues/26619

Fixes #26619: Fix augeas method

---

relay/sources/rudder-package/src/plugin.rs

https://issues.rudder.io/issues/26715

Fixes #26715: Add a mechanism to bypass plugin indexing in the public repositories

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTabForeach.elm

https://issues.rudder.io/issues/26650

Fixes #26650: Technique loop copy box pastes wrong value

---

Cargo.lock

https://issues.rudder.io/issues/26753

Fixes #26753: Vulnerabilities in Rust dependencies

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala

https://issues.rudder.io/issues/26690

Fixes #26690: User with limited rights gets Ajax error

---

relay/sources/rudder-relay-postinst

https://issues.rudder.io/issues/26679

Fixes #26679: Remove leftover apache config backup files

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/appconfig/ConfigService.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_settings.yml

https://issues.rudder.io/issues/26773

Fixes #26773: Do not store nodecompliancelevels by default

---

policies/module-types/system-updates/src/package_manager.rs

https://issues.rudder.io/issues/26681

Fixes #26681: Services restart fails on RedHat 9 after successful update campaign

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTechnique.elm

https://issues.rudder.io/issues/26685
Replacing previous PR: https://github.com/Normation/rudder/pull/6331

Fixes #26685: Can't save technique when modifying a resource file

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/Authorizations.scala
webapp/sources/rudder/rudder-rest/src/test/resources/api/api_usermanagement.yml

https://issues.rudder.io/issues/26642

Fixes #26642: Compliance right should not give access to techniques and global parameters

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala

https://issues.rudder.io/issues/25374

Fixes #25374: System group description is editable in the UI but cannot be saved

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/CampaignArchiver.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/MainCampaignService.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/MockServices.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/22675

Fixes #22675: Commit campaign definition in the configuration repository

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Onboarding/View.elm
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-settings.scss
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-template.scss
webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/settings.html
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/administration/policyServerManagement.html

https://issues.rudder.io/issues/26648
The review of this PR must be followed by the review of this other PR : 
https://github.com/Normation/rudder-plugins/pull/823

Fixes #26648: We cannot scroll to the bottom page of all Settings pages

---

webapp/sources/rudder/rudder-web/src/main/webapp/secure/index.html

https://issues.rudder.io/issues/26844

Fixes #26844: Techniques count in dashboard leads to 404 page

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala

https://issues.rudder.io/issues/26847

Fixes #26847: A user that has only the "deployer_read" right does not have access to the settings API

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala

https://issues.rudder.io/issues/26843

Fixes #26843: User with 'user' role cannot get token status

---

Jenkinsfile-security
deny.toml

https://issues.rudder.io/issues/26870

Fixes #26870: Allow LGPL license 2.1 dependencies

---

policies/module-types/template/src/lib.rs

https://issues.rudder.io/issues/26884

Fixes #26884: Change default template engine to Minijinja

---

webapp/sources/pom.xml
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/CampaignEventRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/db/DB.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/db/Doobie.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/metrics/HistorizeNodeCountService.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/EventLogJdbcRepository.scala
webapp/sources/rudder/rudder-rest/pom.xml
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/Compliance.scala
webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/SystemApiTest.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/EventListDisplayer.scala

https://issues.rudder.io/issues/26792

Fixes #26792: Update scala dependencies

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlUnserialisationImpl.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/marshalling/TestXmlUnserialisation.scala

https://issues.rudder.io/issues/26888
Backporting https://github.com/Normation/rudder/pull/6364 to branch 8.2 since it's a real bug and not only scala 3 change.

Fixes #26888: XML unserialization of ACL is incorrect

---

webapp/sources/rudder/rudder-core/src/main/resources/ldap/init-policy-server.ldif
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/endconfig/action/RemoveDefaultRootDescription.scala

https://issues.rudder.io/issues/26878

Fixes #26878: Remove default root description 

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala

https://issues.rudder.io/issues/26832

Fixes #26832: Groups with special target has clone button but cannot be cloned

---

policies/module-types/template/src/lib.rs

https://issues.rudder.io/issues/26914

Fixes #26914: fixing windows compatibility for the template module

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/EditorTechniqueReader.scala

https://issues.rudder.io/issues/26922
Add a log + formatting

Fixes #26922: Add a logger for rudderc gm lib command

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/properties/ParameterDiff.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDiffMapper.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SystemApi.scala

https://issues.rudder.io/issues/26889
When we added `Visibility` in https://issues.rudder.io/issues/26487 we forgot to add the diffability part leading to `Unknown diff attribute: visibility`

Fixes #26889: Missing visibility change for parameter

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SystemApi.scala

https://issues.rudder.io/issues/26945

Fixes #26945: 

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/plugins/cli/RudderPackagePlugin.scala.scala
webapp/sources/rudder/rudder-core/src/test/scala/com/normation/plugins/cli/RudderPackageServiceTest.scala

https://issues.rudder.io/issues/26940

Fixes #26940: Plugin successful install can display an error because of service restart

---

api-doc/package-lock.json
qa-test

https://issues.rudder.io/issues/26999

Fixes #26999: Update api doc tooling

---

webapp/sources/pom.xml

https://issues.rudder.io/issues/27011

Fixes #27011: JGit vulnerability (XXE)

---

policies/lib/tests/acceptance/30_generic_methods/command_execution.cf
policies/lib/tests/acceptance/default.cf.sub
policies/lib/tests/acceptance/testall
policies/lib/tests/quick/all_shell_test_should_be_set_e.sh
policies/lib/tests/quick/bundles_starting_with_underscore_must_not_modify_the_system.sh
policies/lib/tests/quick/dont_use_perms_on_group_root.sh
policies/lib/tree/10_ncf_internals/modules/packages/freebsd_ports
policies/lib/tree/20_cfe_basics/cfengine/packages.cf
policies/lib/tree/20_cfe_basics/services.cf

https://issues.rudder.io/issues/26810

Fixes #26810: rudder agent check complains “egrep: warning: egrep is obsolescent; using grep -E”

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/GitTechniqueReader.scala

https://issues.rudder.io/issues/26912
I could not identify the source of the corrupted state (I could not even boot my server anymore), nor apply a workaround (I even reset my configuration repo git history), but to avoid any inconsistency in the immutable map, just   skip non-existing keys

Fixes #26912: Creating technique with resources in folders can break technique library

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/ViewTabContent.elm

https://issues.rudder.io/issues/26711
A skeleton loading animation now appears in the compliance tabs during compliance loading :

Fixes #26711: Rule detail compliance has no indication that it is loading

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder-datatable.js
webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-menu.scss

https://issues.rudder.io/issues/27051
the previous condition was always true, the condition needs to be checked the other way around
EDIT: there is some compilation issue in SCSS because of a missing import

Fixes #27051: Event logs rollback does not do any action

---

policies/lib/tree/10_ncf_internals/configuration.cf
policies/lib/tree/10_ncf_internals/initialization.cf
policies/lib/tree/30_generic_methods/file_from_template_jinja2.cf
policies/lib/tree/30_generic_methods/permissions_posix_acl_entry_parent.cf

https://issues.rudder.io/issues/27057

Fixes #27057: Make ncf compatible with old and new path of modules

---

webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-node-ready/10-cf-promise-check

https://issues.rudder.io/issues/27061

Fixes #27061: Rudder server depends on cf-promises being in old path

---

policies/lib/tree/30_generic_methods/file_from_template_jinja2.cf

https://issues.rudder.io/issues/27065

Fixes #27065: double path in parent code

---

.github/workflows/ci.yml
Cargo.lock
ci/rust.sh
policies/Dockerfile
policies/lib/tests/integration/user_methods_test.rs
policies/module-types/augeas/src/augeas.rs
policies/rudderc/src/backends/unix/cfengine/promise.rs
relay/sources/relayd/Dockerfile
relay/sources/rudder-package/Dockerfile
relay/sources/rudder-package/src/archive.rs
rust-toolchain.toml
sbom/Dockerfile

https://issues.rudder.io/issues/27066

Fixes #27066: Updating Rust dependencies and compiler version

---

webapp/sources/api-doc/paths/usermanagement/reload.yml

https://issues.rudder.io/issues/26948

Fixes #26948: Doc for user management API reload has wrong method

---

policies/rudderc/src/backends/unix/ncf/method_call.rs
policies/rudderc/tests/cases/general/escaping/technique.cf
policies/rudderc/tests/cases/general/form/technique.cf
policies/rudderc/tests/cases/general/loops/technique.cf
policies/rudderc/tests/cases/general/loops_with_main_branch_without_condition/technique.cf
policies/rudderc/tests/cases/general/ntp/technique.cf
policies/rudderc/tests/cases/general/param_in_condition/technique.cf
policies/rudderc/tests/cases/general/reporting/technique.cf
policies/rudderc/tests/cases/general/unsupported_methods/technique.cf

https://issues.rudder.io/issues/26814

Fixes #26814: Hundreds of “n/a” when iterator used in a simple package installation technique.

---

webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-node.scss

https://issues.rudder.io/issues/27050
Some CSS that was forgotten with the CSS refactoring of https://github.com/Normation/rudder/pull/6028

Fixes #27050: Technical logs date pickers are misaligned in UI

---

policies/module-types/template/src/cli.rs
policies/module-types/template/src/lib.rs

https://issues.rudder.io/issues/27094

Fixes #27094: Improving the clarity of error messages in the template module.

---

webapp/sources/pom.xml

https://issues.rudder.io/issues/27098

Fixes #27098: Missing webapp dependency

---

webapp/sources/rudder/rudder-web/src/main/gulpfile.mjs
webapp/sources/rudder/rudder-web/src/main/package-lock.json
webapp/sources/rudder/rudder-web/src/main/package.json
webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/common-layout.html

https://issues.rudder.io/issues/27104
The way we use the API did not break, we only need to change the compiled umd JS file

Fixes #27104: Update chartjs version to 4

---

policies/module-types/augeas/src/augeas.rs

https://issues.rudder.io/issues/27122

Fixes #27122: Fix warnings in augeas module

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala

https://issues.rudder.io/issues/27090
- only use one logger
- call the logger statically to know what is uses where. 
The rule is: 
- if it's about authencation module configuration, it's just `application` logger, 
- if it's about an actual authentication attempt, it's `application.authentication`. 
There was the same error for REST authentication failure. 
Now:

Fixes #27090: Bad logger used for authentication error

---

policies/lib/tree/20_cfe_basics/files.cf
policies/lib/tree/30_generic_methods/sharedfile_from_any.cf

https://issues.rudder.io/issues/25877

Fixes #25877: Add a generic method to retreive more tha one file shared by other nodes

---

webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/earlyconfig/db/TestCheckUsersFile.scala

https://issues.rudder.io/issues/27152

Fixes #27152: Bad package for TestCheckUsersFile

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/users/RudderUserDetailsFile.scala
webapp/sources/rudder/rudder-rest/src/test/resources/test-users.xml
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala
webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/earlyconfig/db/CheckUsersFile.scala
webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/PasswordEncoderTypeTest.scala
webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/RudderPasswordEncoderTest.scala
webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/earlyconfig/db/TestCheckUsersFile.scala

https://issues.rudder.io/issues/27128

Fixes #27128: Drop support for legacy password hash algorithms

---

relay/sources/rudder-relay-postinst

https://issues.rudder.io/issues/27174

Fixes #27174: CA list is not initialized at installation

---

relay/sources/apache/rudder-apache-relay-ssl.conf

https://issues.rudder.io/issues/27138

Fixes #27138: Add apache configuration to publish policy archives

---

webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-technique-editor.css

https://issues.rudder.io/issues/22355

Fixes #22355: When editing a long textarea browser scrolls to top

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/MethodConditions.elm

https://issues.rudder.io/issues/27192

Fixes #27192: Remove old OSes from technique editor conditions

---

policies/Makefile
policies/module-types/inventory/Makefile

https://issues.rudder.io/issues/27207

Fixes #27207: Add makefile for the inventory module

---

policies/rudderc/src/backends/unix.rs
policies/rudderc/src/backends/unix/ncf/method_call.rs
policies/rudderc/tests/cases/general/escaping/technique.cf
policies/rudderc/tests/cases/general/form/technique.cf
policies/rudderc/tests/cases/general/long_method_param_name/technique.cf
policies/rudderc/tests/cases/general/min/technique.cf
policies/rudderc/tests/cases/general/min_yaml/technique.cf
policies/rudderc/tests/cases/general/ntp/technique.cf
policies/rudderc/tests/cases/general/param_in_condition/technique.cf
policies/rudderc/tests/cases/general/policy_mode/technique.cf
policies/rudderc/tests/cases/general/reporting/technique.cf
policies/rudderc/tests/cases/general/unsupported_methods/technique.cf
policies/rudderc/tests/cases/general/variables/technique.cf

https://issues.rudder.io/issues/27169

Fixes #27169: Remove any reference to class_prefix in the generated technique

---

policies/module-types/inventory/src/os_release.rs
policies/rudderc/src/backends/unix/ncf/method_call.rs

https://issues.rudder.io/issues/27217

Fixes #27217: Syntax error in the upmerge of parent ticket

---

policies/lib/tree/30_generic_methods/audit_from_osquery.cf

https://issues.rudder.io/issues/27228

Fixes #27228:  Add windows support to the Audit from osquery generic method

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder-datatable.js
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/NodeGrid.scala
webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/PendingHistoryGrid.scala

https://issues.rudder.io/issues/27272
Similar to https://github.com/Normation/rudder/pull/6435

Fixes #27272: Export pending nodes tables into CSV

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/workflows/WorkflowService.scala

https://issues.rudder.io/issues/27274

Fixes #27274: Migrate the ChangeRequestDetails snippet from Scala/lift to Elm

---

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/score/ScoreRepository.scala
webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/score/ScoreService.scala

https://issues.rudder.io/issues/26900

Fixes #26900: Score service does not really clean unmanaged score, only remove them in cache but they are still in database

---

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/charting.js
webapp/sources/rudder/rudder-web/src/main/javascript/rudder/homePage.js
webapp/sources/rudder/rudder-web/src/main/webapp/secure/index.html

https://issues.rudder.io/issues/27329
Replacing previous PR: https://github.com/Normation/rudder/pull/6534

Fixes #27329: Move the graph creation functions from homepage.js to another js file.

---

webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/server/server_details.html

https://issues.rudder.io/issues/27358

Fixes #27358: Add an ID for node details tab content container

---

policies/module-types/system-updates/src/campaign.rs

https://issues.rudder.io/issues/27367

Fixes #27367: Log restarted services

---

relay/sources/rudder-package/src/webapp.rs

https://issues.rudder.io/issues/27371

Fixes #27371: Quiet option still show spinner in rudder package

---

policies/module-types/system-updates/src/package_manager/apt.rs
policies/module-types/system-updates/src/package_manager/apt/filter.rs
relay/sources/rudder-package/src/webapp.rs

https://issues.rudder.io/issues/26855

Fixes #26855: Security updates not applied on Debian 12, but campaign ends without error

---

policies/rudderc/src/backends/metadata.rs
policies/rudderc/tests/cases/general/form/metadata.xml

https://issues.rudder.io/issues/27363

Fixes #27363: Constraint doesn't allow to change variable

---

webapp/sources/dependency-check-suppression.xml

https://issues.rudder.io/issues/27437

Fixes #27437:  Ignore CVEs for icu4j

---

Cargo.lock
policies/module-types/system-updates/Cargo.toml

https://issues.rudder.io/issues/27438

Fixes #27438: Allow building with newer APT versions

---

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/users/RudderUserDetailsFile.scala

https://issues.rudder.io/issues/27449

Fixes #27449: Fix spotless in 27310

---

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/HomePage.scala

https://issues.rudder.io/issues/27446

Fixes #27446: Ignored nodes should be excluded from compliance and score processing

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala

https://issues.rudder.io/issues/27522
Display a pretty-rendered duration in logs

Fixes #27522: Fix logs for users configuration properties with a duration 

---

webapp/sources/api-doc/code_samples/curl/usermanagement/add.sh
webapp/sources/api-doc/code_samples/curl/usermanagement/coverage.sh
webapp/sources/api-doc/code_samples/curl/usermanagement/delete.sh
webapp/sources/api-doc/code_samples/curl/usermanagement/update-info.sh
webapp/sources/api-doc/code_samples/curl/usermanagement/update.sh

https://issues.rudder.io/issues/27521

Fixes #27521: User API update documentation is incorrect

---

deny.toml

https://issues.rudder.io/issues/27539

Fixes #27539: Ignore adler advisory in 8.2

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/DataTypes.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/JsonDecoder.elm
webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/ViewUtils.elm

https://issues.rudder.io/issues/27456

Fixes #27456: Inherited properties API change in parent 

---

relay/sources/apache/rudder-apache-relay-ssl.conf.j2

https://issues.rudder.io/issues/27587

Fixes #27587: Allow a deeper SSLVerifyDepth

---

policies/lib/tree/30_generic_methods/file_from_template_options.cf
policies/module-types/template/src/lib.rs
policies/module-types/template/src/minijinja_filters.rs
policies/module-types/template/tests/minijinja.rs

https://issues.rudder.io/issues/27636

Fixes #27636: The file_from_template_options method should accept inline JSON in its data field

---

webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTechniqueList.elm

https://issues.rudder.io/issues/27595

Fixes #27595: In technique editor the number of techniqes is under "techniques" big title

---

policies/lib/tests/integration/command_execution_options_test.rs
policies/lib/tests/integration/mod.rs
policies/lib/tests/quick/ordering.pl
policies/lib/tree/20_cfe_basics/common.cf
policies/lib/tree/30_generic_methods/command_execution_options.cf
policies/module-types/commands/src/lib.rs

https://issues.rudder.io/issues/27585

Fixes #27585: Test the command_execution_options generic method

---

policies/rudderc/src/backends/windows/test.rs
relay/sources/rudder-package/src/repository.rs
webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample

https://issues.rudder.io/issues/27659

Fixes #27659: Typo in rudder-web.properties

---

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/earlyconfig/db/MigrateTableCampaignEvents.scala

https://issues.rudder.io/issues/27674
oups

Fixes #27674: Inconsistency in campaigneventstate between init and DB migration

---

ci/common.Dockerfile
policies/rudderc/src/backends/windows/test.rs
relay/sources/rudder-package/src/repository.rs

https://issues.rudder.io/issues/27684

Fixes #27684: Pin the typos-cli version

---

policies/module-types/commands/src/lib.rs

https://issues.rudder.io/issues/27683

Fixes #27683: Error with command_execution_results but everything looks ok
