rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala, rudder-core/src/main/scala/com/normation/rudder/services/queries/LdapQueryProcessor.scala, rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala, rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala
Major performance improvment on "nodeInfo" with a "cached" implementation of the nodeInfoService in place of the dumb one. 
The propose change lead to two major perf improvment:
- for dynGroup, reduce the number of request from "Number of node in group" to one (1000x improvment with > 1000 nodes in groups)
- when getting the list of all nodeInfo, time from ~4000ms to ~20ms
=> Fixes #5452: Performance issue for node list

rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
http://www.rudder-project.org/redmine/issues/6157
=> Fixes #6157: Rudder stores too much or too big cookies, causing white page with HTTP status: 413: FULL head (branch 2.11)

rudder-web/src/main/scala/com/normation/rudder/web/rest/RestExtractorService.scala
http://www.rudder-project.org/redmine/issues/6176
=> Fixes #6176: cannot use \"enabled\" json parameter in Directive API

rudder-core/src/main/scala/com/normation/rudder/reports/ReportingConfiguration.scala, rudder-core/src/main/scala/com/normation/rudder/reports/execution/ReportsExecutionRepository.scala
Cache are hard :/)
DO not add run that are not complete in the cache. We don't want them. Bad run. Bad.
=> Fixes #6211: If a run is not completed, compliance computation goes mad

rudder-core/src/main/scala/com/normation/rudder/domain/policies/RuleTarget.scala, rudder-core/src/main/scala/com/normation/rudder/domain/servers/Srv.scala, rudder-core/src/main/scala/com/normation/rudder/repository/NodeGroupRepository.scala, rudder-core/src/main/scala/com/normation/rudder/services/servers/ServerSummaryService.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/popup/ExpectedPolicyPopup.scala, rudder-web/src/main/scala/com/normation/rudder/web/services/NodeGrid.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/AcceptNode.scala
The main idea here is to leverage the big piece of logic from FullNodeGroupCategory that allows to get the set of nodeIds matching RuleTarget in the context of the group library, and to allows to give it an other context (and works with less information than nodeInfo). 
Once that done, we get a piece of code factored out between acceptNode and FullNodeGroupCategory (so no divergence in that touchy logic). More over, the code pattern match on sealed class, so we won't have anymore "missing" case like the one in bug #5764
=> Fixes #5764: List of impacted rules when accepting nodes or modifing directives is not accurate

rudder-web/src/main/scala/com/normation/rudder/web/components/RuleGrid.scala
http://www.rudder-project.org/redmine/issues/6260
=> Fixes #6260: Cannot apply a Directive to all visible Rules

rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNodeGroupTree.scala
http://www.rudder-project.org/redmine/issues/6276
=> Fixes #6276: The \"+\" button to add a group to a Rule redirects to the group edition page instead of adding the group to the Rule

rudder-web/src/main/resources/logback.xml
This ticket only add the log rotation from logback. We still need to remove the log rotation done by logrotate, and the two pull request must be merged together. 
It superseeds https://github.com/Normation/rudder/pull/836
=> Fixes #6381: File /var/log/rudder/compliance/non-compliant-reports.log is not correctly rotated

rudder-core/src/main/scala/com/normation/rudder/domain/policies/RuleTarget.scala
http://www.rudder-project.org/redmine/issues/6454
=> Fixes #6454: networks.conf empty on relay

rudder-core/src/main/scala/com/normation/rudder/services/policies/nodeconfig/NodeConfigurationServiceImpl.scala, rudder-core/src/test/scala/com/normation/rudder/services/nodes/NodeConfigurationChangeDetectServiceTest.scala
The rational here is to prevent undue serial upgrade when adding a node in a rule.
The serial change should be only for "change" of config
The huge benefit of that is that we don't lose compliance info of the rule when accepting node
The second great benefit is that promise generation is faster: less change
This picture show the rule screen after having accepted a node
=> Bug 6519/don t increase serial when adding nodes

rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/compliance/ComplianceAPI6.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/compliance/ComplianceAPIData.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/compliance/ComplianceAPIService.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/compliance/ComplianceApi.scala
See http://www.rudder-project.org/redmine/issues/6137 for details about what is added
=> Issue #6137: add an API for compliance by node or rule

rudder-core/src/main/resources/Migration/ldapMigration-3.0-3.1-set-syslog-protocol.ldif, rudder-core/src/main/resources/ldap/bootstrap.ldif, rudder-core/src/main/scala/com/normation/rudder/domain/eventlog/EventLogCategories.scala, rudder-core/src/main/scala/com/normation/rudder/domain/eventlog/ModifyGlobalProperty.scala, rudder-core/src/main/scala/com/normation/rudder/reports/ReportingConfiguration.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/SystemVariableService.scala, rudder-web/src/main/resources/eventLogTypeNames.properties, rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala, rudder-web/src/main/scala/com/normation/rudder/appconfig/ConfigService.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PropertiesManagement.scala, rudder-web/src/main/webapp/secure/administration/policyServerManagement.html
https://www.rudder-project.org/redmine/issues/5796
=> Fixes #5796: Make syslog transport configurable from web interface

rudder-web/src/main/webapp/javascript/rudder/angular/ruleDirectives.js, rudder-web/src/main/webapp/templates-hidden/components/ComponentRuleEditForm.html
https://www.rudder-project.org/redmine/issues/7059
Some information about that pull request: AngularJS needs to have stable JS object or it goes in infinite loop. So I need to have both the data I need, with the model I want to handle AND a copy of them on an angularjs-no-infinity-loop compatible way. That su**s. Not found anything else.
=> Fixes #7059: In UI, directives in a rule are not sorted as their bundle order

rudder-core/src/main/scala/com/normation/rudder/domain/reports/ExpectedReports.scala, rudder-core/src/main/scala/com/normation/rudder/domain/reports/bean/ExecutionBatch.scala, rudder-core/src/main/scala/com/normation/rudder/domain/reports/bean/ReportType.scala, rudder-core/src/test/scala/com/normation/rudder/domain/reports/bean/ExecutionBatchTest.scala, rudder-core/src/test/scala/com/normation/rudder/services/path/PathComputerTest.scala, rudder-web/src/main/scala/com/normation/rudder/web/services/ComplianceData.scala
This PR is just a version of #902 but rebased to current state of branche 2.11.
=> Fixes #7055: Reporting cannot be used when there is several component with the same value and several messages

rudder-core/src/main/scala/com/normation/cfclerk/services/impl/Cf3PromisesFileWriterServiceImpl.scala, rudder-core/src/main/scala/com/normation/cfclerk/services/impl/SystemVariableSpecServiceImpl.scala
https://www.rudder-project.org/redmine/issues/7126
=> Fixes #7126: Add a new system variable for the \"rudder_directives\" bundle

rudder-web/src/main/resources/rudder-apache-common.conf
Restrict for both apache versions via IfVersion for WebDAV PUT requests
=> Fix #7267 Restrict WebDAV PUT via IfVersion

rudder-core/src/main/scala/com/normation/rudder/domain/logger/ComplianceDebugLogger.scala, rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala, rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala, rudder-web/src/main/resources/logback.xml
https://www.rudder-project.org/redmine/issues/7353
That PR is best view with ?w=1 (lots of code displaced / spaces changed). 
There is two main things done here to help debug compliance:
- the first one is to add logging possibility to use : explain_compliance.nodeid logger to debug a specific node
- the second is to split the method that find the big case, function of compliance mode, last run, expected config, so that the comparison time and the last valid time are more understandable.
=> Fixes #7353: Missing debuging information for explain_compliance

rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeRepository.scala, rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala, rudder-core/src/main/scala/com/normation/rudder/services/nodes/QuickSearchService.scala, rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala
https://www.rudder-project.org/redmine/issues/7357
Some explanation: in fact, the tests don't pass anymore because we are using OpenLDAP specific filters for efficiency, that are not available in the test directory. 
So we need to split the "nodeinfoservice" service into an efficient version used in the real web app, and a "naive" one, that is used in test. 
Of course, we must share most of the logic, else we don't test anything. So the split is done only on the way we retrieve entries, and if we should update cache (always true).
=> Fixes #7357: Inventory query test are not passing anymore in Rudder 3.0

rudder-core/src/test/scala/com/normation/rudder/domain/reports/StatusReportTest.scala, rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala
https://www.rudder-project.org/redmine/issues/7378
=> Fixes #7378: Test no passing in Rudder 3.1 since #7331 and #7357

rudder-core/src/main/scala/com/normation/cfclerk/services/impl/SystemVariableSpecServiceImpl.scala, rudder-core/src/main/scala/com/normation/rudder/domain/logger/ComplianceDebugLogger.scala, rudder-core/src/main/scala/com/normation/rudder/reports/ComplianceMode.scala, rudder-core/src/main/scala/com/normation/rudder/reports/ReportingConfiguration.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/SystemVariableService.scala, rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala, rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala, rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala, rudder-core/src/test/scala/com/normation/rudder/services/reports/ExecutionBatchTest.scala, rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala, rudder-web/src/main/scala/com/normation/rudder/appconfig/ConfigService.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/AgentScheduleEditForm.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/ComplianceModeEditForm.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/ShowNodeDetailsFromNode.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PropertiesManagement.scala, rudder-web/src/main/webapp/javascript/rudder/angular/complianceMode.js, rudder-web/src/main/webapp/templates-hidden/components/ComponentComplianceMode.html
https://www.rudder-project.org/redmine/issues/7375
=> Fixes #7375: Add an option in the web interface to completely disable reporting

rudder-core/src/main/scala/com/normation/rudder/services/policies/write/Cf3PromisesFileWriterService.scala
https://www.rudder-project.org/redmine/issues/7407
=> Fixes #7407: Display failed cf-promises to make it easier to re-run while debugging

rudder-core/src/main/scala/com/normation/rudder/domain/logger/ComplianceDebugLogger.scala, rudder-core/src/main/scala/com/normation/rudder/domain/queries/CmdbQuery.scala, rudder-core/src/main/scala/com/normation/rudder/domain/reports/ComplianceLevel.scala, rudder-core/src/main/scala/com/normation/rudder/domain/reports/ReportType.scala, rudder-core/src/main/scala/com/normation/rudder/reports/ComplianceMode.scala, rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ExpectedReportsJdbcRepository.scala, rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala, rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala, rudder-core/src/test/scala/com/normation/rudder/services/reports/ExecutionBatchTest.scala, rudder-web/src/main/resources/default.properties, rudder-web/src/main/scala/com/normation/rudder/web/components/ComplianceModeEditForm.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/compliance/ComplianceAPIData.scala, rudder-web/src/main/scala/com/normation/rudder/web/services/AsyncComplianceService.scala, rudder-web/src/main/scala/com/normation/rudder/web/services/JsTableData.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/HomePage.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/Groups.scala, rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js, rudder-web/src/main/webapp/style/bootstrap-rudder-bridge.css
https://www.rudder-project.org/redmine/issues/7398
=> Fixes #7398: Update compliance UI to manage disable mode

rudder-web/src/main/scala/com/normation/rudder/web/components/RuleGrid.scala, rudder-web/src/main/webapp/javascript/rudder/angular/apiAccount.js, rudder-web/src/main/webapp/style/rudder.css
https://www.rudder-project.org/redmine/issues/7416
=> Fixes #7416: Compliance detail and compliance summary use different colours

rudder-core/src/main/scala/com/normation/cfclerk/domain/Technique.scala, rudder-core/src/main/scala/com/normation/cfclerk/domain/TechniqueResource.scala, rudder-core/src/main/scala/com/normation/cfclerk/services/TechniqueReader.scala, rudder-core/src/main/scala/com/normation/cfclerk/services/TechniqueRepository.scala, rudder-core/src/main/scala/com/normation/cfclerk/services/impl/GitTechniqueReader.scala, rudder-core/src/main/scala/com/normation/cfclerk/services/impl/TechniqueRepositoryImpl.scala, rudder-core/src/main/scala/com/normation/cfclerk/xmlparsers/CfclerkXmlConstants.scala, rudder-core/src/main/scala/com/normation/cfclerk/xmlparsers/TechniqueParser.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/write/Cf3PolicyDraft.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/write/Cf3PromisesFileWriterService.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PrepareTemplateVariables.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PromiseWriteDataStructures.scala, rudder-core/src/test/resources/techniquesRoot/cat1/p1_1/1.0/file2.txt, rudder-core/src/test/resources/techniquesRoot/cat1/p1_1/1.0/metadata.xml, rudder-core/src/test/scala/com/normation/cfclerk/services/DummyTechniqueRepository.scala, rudder-core/src/test/scala/com/normation/cfclerk/services/JGitPackageReaderTest.scala, rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ExpectedReportTest.scala, rudder-core/src/test/scala/com/normation/rudder/services/nodes/NodeConfigurationChangeDetectServiceTest.scala, rudder-core/src/test/scala/com/normation/rudder/services/policies/RuleValServiceTest.scala, rudder-core/src/test/scala/com/normation/rudder/services/policies/write/PolicyInstanceAgregationTest.scala
https://www.rudder-project.org/redmine/issues/7402
This ticket add the `<FILE>` tag in Techniques for resources that we just want to copy for each node. 
It also bring some refactoring in the "write promise" pipeline, trying to make it a little clearer (create some datastructure to holds things, rename other things to denote what they actually are, and not what they were 5 years ago, etc...) and more correct (for instance, expected_reports.csv is now written only *one* time for each node/agent, not one time for each template of each technique...).
=> Fixes #7402: Add a <FILE> tag in metadata.xml to allow simple file copy into techniques

rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PrepareTemplateVariables.scala, rudder-core/src/test/scala/com/normation/rudder/services/policies/write/PrepareTemplateVariableTest.scala
https://www.rudder-project.org/redmine/issues/7454
=> Fixes #7454: Directives with double quotes in their name need to be escaped before going in rudder_directives.cf and rudder_expected_reports.csv

rudder-core/src/main/scala/com/normation/rudder/domain/policies/RuleVal.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala, rudder-core/src/test/scala/com/normation/rudder/services/policies/TestNodeAndParameterLookup.scala
https://www.rudder-project.org/redmine/issues/7541
=> Fixes #7541: Major performance hit in promise generation for unused inventories fetch

rudder-core/src/main/scala/com/normation/rudder/services/servers/NewNodeManager.scala
https://www.rudder-project.org/redmine/issues/7689
=> Fixes #7689: Error on promise generation after accepting a node

rudder-core/src/main/scala/com/normation/rudder/domain/eventlog/AssetsEventLog.scala, rudder-core/src/main/scala/com/normation/rudder/domain/nodes/Node.scala, rudder-core/src/main/scala/com/normation/rudder/domain/nodes/NodeInfo.scala, rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala, rudder-core/src/test/scala/com/normation/rudder/domain/policies/RuleTargetTest.scala, rudder-core/src/test/scala/com/normation/rudder/services/nodes/NodeConfigurationChangeDetectServiceTest.scala, rudder-core/src/test/scala/com/normation/rudder/services/path/PathComputerTest.scala, rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala, rudder-core/src/test/scala/com/normation/rudder/services/policies/TestNodeAndParameterLookup.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/ShowNodeDetailsFromNode.scala, rudder-web/src/main/scala/com/normation/rudder/web/services/EventListDisplayer.scala
https://www.rudder-project.org/redmine/issues/7634
=> Fixes #7634: Make NodeInfo more dependant on Node

rudder-web/src/main/scala/com/normation/rudder/web/snippet/HomePage.scala
https://www.rudder-project.org/redmine/issues/7757
=> Fixes #7757: Blue colour in \"Nodes by overall compliance\" chart is confusingly the same as \"No report\" blue

rudder-core/src/main/scala/com/normation/rudder/domain/reports/StatusReports.scala, rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala, rudder-core/src/test/scala/com/normation/rudder/services/reports/ExecutionBatchTest.scala
https://www.rudder-project.org/redmine/issues/7758
The PR is quite big but there is in fact 4 things in it:
- 1. I factored out some logic in test so that it's much more easy to write test for value with CFEngine variables. Most of ExecutionBatchTest.scala changes are due to that, but there was ALSO uncoherencies and things that were not good, showed by 2. and 3. above
- 2. I found a bug with the logic for getting simple value from reports. The algo was too greedy and was not letting "unused" reports to possible match for cfengine variables
- 3. We weren't merging to worst type the values for the same component/directive/rule/node. In practice, it may have never been seen, because that case is only for value with cardinality > 1, but somes tests were testing a bad expectation
- 4. And …
=> Fixes #7758: When several directives value have a CFEngine var, we get \"unexpected\" due to bad regex matching

rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
https://www.rudder-project.org/redmine/issues/3749
=> Fixes #3749: The Motherboard UUID doesn't appear on the inventory on a Node

rudder-core/src/main/scala/com/normation/rudder/domain/queries/DitQueryData.scala, rudder-web/src/main/resources/ldapObjectAndAttributes.properties, rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
See http://www.rudder-project.org/redmine/issues/2543
There is litterary only 3 things added:
- the attribute is added as a searcheable one, 
- configure its name in the dropdown, 
- add a line in the "OS" part of node details to show it.
=> Fixes #2543: Allow to make a group with only 32bits or 64bits nodes

rudder-core/src/main/scala/com/normation/rudder/migration/EventLogMigration_2_3.scala, rudder-core/src/main/scala/com/normation/rudder/migration/XmlEntityMigration.scala, rudder-core/src/main/scala/com/normation/rudder/migration/XmlFileFormatMigration_3_4.scala, rudder-core/src/main/scala/com/normation/rudder/migration/XmlFileFormatMigration_4_5.scala, rudder-core/src/test/scala/com/normation/rudder/migration/TestDbMigration.scala, rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckMigrationXmlFileFormat.scala
https://www.rudder-project.org/redmine/issues/7524
There is two main point of that change: 
- make each migration be only by step of "max batch", so that we can't explose the memory consumption. I set up the batch size to 1000, because eventlog object use ~10kb, but can use to up to ~50kb for very big events (say, group update with thousand of nodes). So with that, we should keep the memory consumption below 100Mo for the migration
- make the process async so that the event log migration, which is not necessary for Rudder to work, is done in background. It can be stop and restart as many time as needed, so no problem if Rudder stop before the end of migration
=> Fixes #7524: Java OOM during Java's log migration

rudder-core/src/main/scala/com/normation/rudder/batch/AutomaticReportLogger.scala, rudder-core/src/main/scala/com/normation/rudder/reports/execution/ReportsExecutionService.scala, rudder-core/src/main/scala/com/normation/rudder/repository/ReportsRepository.scala, rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ReportsJdbcRepository.scala
https://www.rudder-project.org/redmine/issues/8195
Some information: 
- a lot of modification in the ReportsJdbcRepository are cosmetic and just help see what are the differences between queries
- the previous code was doing 3 i/o (get directive, rule, technique) for each log to write, which can be made more efficient by just getting all the rules/directives/techniques. There are already in Rudder memory, that doesn't change the memory profile of the app, but it won a LOT of time (from > 15min to ~10s for writting 250 000 lines)
- the whole process is split in little batch of 10 000 non-compliant-reports. I didn't see much interest in making them bigger, since it could help only for some fixes cost like getting the connection from pool, which is clearly not a big problem. 
One question …
=> Fixes #8195: Correct memory profile and efficiency of error report logger

rudder-core/src/main/scala/com/normation/rudder/repository/ReportsRepository.scala, rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ReportsJdbcRepository.scala, rudder-core/src/main/scala/com/normation/rudder/services/reports/NodeChangesService.scala, rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/RuleCompliance.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/RuleEditForm.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/RuleGrid.scala
https://www.rudder-project.org/redmine/issues/7735
For information, with the 3 patches applied (+https://www.rudder-project.org/redmine/issues/8195), with > 1.2 Millions changes in the last 3 days (with one 6h interval at 1M changes), we are able to start a Rudder with -Xmx600m, have the non-compliant report be iteratively written, login, go to rule details, see graphes, click and see details on all interval, and everything is fast - with a top heap consomption at 290MB. 
So, there is still some cleaning to do, but the general architecture of the patch is ok. It is in 3 parts, I'm letting them in three commits to make them better understandable. Perhaps it could be split in 3 tickets, to, but they are highly coupled (at least the last two), so not sure. 
1/ Today, we reload compliance …
=> Fixes #7735: OOM in Rudder when there are too many repaired reports

rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/nodeconfig/NodeConfigurationCacheRepository.scala
https://www.rudder-project.org/redmine/issues/8246
=> Fixes #8246: Node configuration cache is invalidated too often

rudder-core/src/main/scala/com/normation/rudder/reports/execution/ReportsExecutionService.scala, rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala, rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala, rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala
https://www.rudder-project.org/redmine/issues/8051
So it seems that somehow, the calls to future { } lead to some king of deadlock, and the corresponding code was never executed. It may be linked to the fact that there was a future{} in an method called from a future{}, or not. 
At least, removing the future and making the order of execution stricter lead to a comprehensive behavior from the user. If the last run in "select * from reportsexecution order by date desc limit 5;" is marked as finished, just after - and BEFORE the next processing of runs - the compliance is reprocessed, and the debug output of ```<logger name="com.normation.rudder.services.reports.CachedReportingServiceImpl" level="debug" />``` and 
```
<logger name="explain_compliance.root" level="trace" additivity="false"> …
```
=> Fixes #8051: Compliance is not correctly computed if we receive run agent right after generation

rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala
https://www.rudder-project.org/redmine/issues/8399
=> Fixes #8399: Misleading message on node compliance detail when run's configID is unknown

rudder-core/src/main/scala/com/normation/rudder/services/policies/RudderPromiseWriterServiceImpl.scala
https://www.rudder-project.org/redmine/issues/8427
Replacing previous PR: https://github.com/Normation/rudder/pull/1107
=> Fixes #8427: Parallel traversal of new promises directories causes rules.new to remain after generation

rudder-web/src/main/scala/com/normation/rudder/web/services/AsyncComplianceService.scala
https://www.rudder-project.org/redmine/issues/8118
=> Fixes #8118: When a node send reports with a wrong config_id it is never marked as unresponsive

rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/RestDataSerializer.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/group/GroupAPI6.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/technique/TechniqueAPI6.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/technique/TechniqueAPIService6.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/technique/TechniqueApi.scala
https://www.rudder-project.org/redmine/issues/8534
=> Fixes #8534: Add an technique API endpoint to display directives based on a technique

rudder-core/pom.xml, rudder-web/pom.xml, rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/ChangeRequestManagement.scala
https://www.rudder-project.org/redmine/issues/8656
Not that that one need to be carefully upmerge to remove the lines ine Boot.scala about the HTML parser.
=> Fixes #8656: Adapt Rudder project to Scala 2.11 / Lift 2.6 dependencies

rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala, rudder-web/src/main/scala/com/normation/rudder/web/model/DirectiveEditor.scala, rudder-web/src/main/scala/com/normation/rudder/web/model/DirectiveFieldEditors.scala, rudder-web/src/main/scala/com/normation/rudder/web/model/RudderBaseField.scala, rudder-web/src/main/scala/com/normation/rudder/web/services/DirectiveFieldFactory.scala, rudder-web/src/main/scala/com/normation/rudder/web/services/Section2FieldService.scala
https://www.rudder-project.org/redmine/issues/8626
There is two main part in that pull request: 
- add masterPassword and slavePassword field. MasterPassword is almost a verbatim copy of the old Password field, but it feeds slassPasswords from its constructor with user inputs, and display more generic names for algo choice in the select box.
- handle the plumbing to make use of the ```<USES>``` constraint. Its almost all in  Section2FieldService.scala
=> Fixes #8626: Adapt DirectiveEditor for master-slave password fields

rudder-core/src/main/scala/com/normation/rudder/domain/logger/ComplianceDebugLogger.scala, rudder-core/src/main/scala/com/normation/rudder/domain/reports/StatusReports.scala, rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala, rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala, rudder-core/src/test/scala/com/normation/rudder/services/reports/ExecutionBatchTest.scala, rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala, rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
https://www.rudder-project.org/redmine/issues/8409
Replace https://github.com/Normation/rudder/pull/1118 because a closed PR forced-pushed can't be reopened, see https://github.com/isaacs/github/issues/361
=> Fixes #8409: Explain all unexpected compliance in node details and only display expected reports when nothing else matter

rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala, rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
https://www.rudder-project.org/redmine/issues/8773
=> Fixes #8773: n/a is counted both separately and in succes in compliance display

rudder-core/src/main/scala/com/normation/rudder/services/policies/JavascriptEngine.scala, rudder-core/src/test/scala/com/normation/rudder/services/policies/TestJsEngine.scala
https://www.rudder-project.org/redmine/issues/8782
=> Fixes #8782: Fix details on script (remove $ from token and fix double password prefix)

rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala, rudder-web/src/main/scala/com/normation/rudder/web/model/DirectiveFieldEditors.scala, rudder-web/src/main/webapp/javascript/rudder/angular/passwordForm.js, rudder-web/src/main/webapp/secure/administration/policyServerManagement.html, rudder-web/src/main/webapp/templates-hidden/components/passwordInput.html
https://www.rudder-project.org/redmine/issues/8785
=> Fixes #8785: Improve Script field behavior in passwords

rudder-core/src/main/scala/com/normation/rudder/services/policies/JavascriptEngine.scala
https://www.rudder-project.org/redmine/issues/8801
=> Fixes #8801: Inconsistent hashing algorithms used in passwords generated in the script engine

rudder-core/src/main/scala/com/normation/rudder/services/policies/JavascriptEngine.scala
https://www.rudder-project.org/redmine/issues/8856
=> Fixes #8856: JS engine tests broken due to security exeception when using jdk 1.8

rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala
https://www.rudder-project.org/redmine/issues/8885
=> Fixes #8885: Typo in in log line when no master admin account is defined

rudder-web/src/main/scala/com/normation/rudder/web/rest/compliance/ComplianceAPIService.scala
https://www.rudder-project.org/redmine/issues/9122
=> Fixes #9122: Use hostname for Nodes instead of name in compliance api names

rudder-core/src/main/scala/com/normation/rudder/domain/nodes/Node.scala, rudder-core/src/main/scala/com/normation/rudder/domain/policies/RuleVal.scala, rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogDetailsService.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/InterpolatedValueCompiler.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/RuleValService.scala, rudder-core/src/test/scala/com/normation/rudder/services/policies/RuleValServiceTest.scala, rudder-core/src/test/scala/com/normation/rudder/services/policies/TestNodeAndParameterLookup.scala, rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala, rudder-web/src/main/scala/com/normation/rudder/appconfig/ConfigService.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/RestExtractorService.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/node/NodeAPIService5.scala, rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PropertiesManagement.scala, rudder-web/src/main/webapp/secure/administration/policyServerManagement.html
Don't merge yet: we need a guard for people saving data in json, then disabling the feature. Now, it is an exception because the unserializer is lost. 
==> in fact, it's OK. It's just in a case you come back to a rudder version that does not understand json in nodeproperties. 
=> that means that you can't have migration from more recent to older with JSON values
https://www.rudder-project.org/redmine/issues/9057
This pull request allows to use node properties un directive parameters. The implemented rules are: 
- the syntax is *exactly* the same than in ncf/technique, i.e: ${node.properties[key1][key2]} 
- when there is only one level of key, the left hand side can be a simple string (as it is for now). If there is several level of keys, then the left hand side must be a valid json data …
=> Fixes #9057: Allow the use of node properties info in Directive parameters

rudder-web/src/main/scala/com/normation/rudder/web/rest/RestQuicksearch.scala
https://www.rudder-project.org/redmine/issues/9133
=> Fixes #9133: 

rudder-core/src/main/resources/Migration/ldapMigration-3.1.x-3.1.14-3.2.7-disable-js-directive.ldif, rudder-core/src/main/resources/Migration/ldapMigration-3.1.x-3.1.14-3.2.7-disable-json-properties.ldif, rudder-core/src/main/resources/Migration/ldapMigration-3.1.x-3.1.14-3.2.7-disable-quicksearch.ldif, rudder-core/src/main/resources/ldap/bootstrap.ldif, rudder-web/src/main/scala/com/normation/rudder/appconfig/ConfigService.scala
https://www.rudder-project.org/redmine/issues/9157
=> Fixes #9157: JS Script, Node Properties expansion and Quicksearch should be disabled on migration

rudder-core/src/main/scala/com/normation/rudder/services/policies/RuleValService.scala
https://www.rudder-project.org/redmine/issues/9184
=> Fixes #9184: If a technique ncf has a ${node.properties[..]}, generation fails

rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchBackendImpl.scala, rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchDomain.scala
https://www.rudder-project.org/redmine/issues/9195
=> Fixes #9195: Quicksearch does not work on "is enable", directive name, and a lot of others

rudder-core/pom.xml, rudder-core/src/main/scala/com/normation/cfclerk/services/impl/SystemVariableSpecServiceImpl.scala, rudder-core/src/main/scala/com/normation/rudder/domain/nodes/NodeInfo.scala, rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/SystemVariableService.scala, rudder-core/src/test/scala/com/normation/rudder/domain/nodes/CFEngineRSAKeyHashTest.scala, rudder-core/src/test/scala/com/normation/rudder/domain/policies/RuleTargetTest.scala, rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala
https://www.rudder-project.org/redmine/issues/8985
=> Fixes #8985: Add node key in managed_nodes system variable

rudder-core/src/main/scala/com/normation/rudder/domain/policies/PolicyMode.scala, rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ReportsJdbcRepository.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/write/BuildBundleSequence.scala, rudder-core/src/test/scala/com/normation/rudder/domain/policies/PolicyModeTest.scala, rudder-core/src/test/scala/com/normation/rudder/services/policies/write/WriteSystemTechniquesTest.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/RestExtractorService.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/node/NodeAPI8.scala, rudder-web/src/main/scala/com/normation/rudder/web/services/ComplianceData.scala, rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala, rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala, rudder-web/src/main/scala/com/normation/rudder/web/services/SrvGrid.scala, rudder-web/src/main/webapp/javascript/rudder/rudder.js, rudder-web/src/main/webapp/style/rudder/rudder-menu.css, rudder-web/src/main/webapp/templates-hidden/components/ComponentAgentPolicyMode.html
https://www.rudder-project.org/redmine/issues/9258
=> Fixes #9258: Rename to audit instead of verify in backend

rudder-web/pom.xml, rudder-web/src/main/scala/com/normation/rudder/web/rest/RestExtractorService.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/node/NodeAPI8.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/node/NodeAPIService8.scala
https://www.rudder-project.org/redmine/issues/9290
=> Fixes #9290: Add an API endpoint to call rudder-remote-run

rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/Groups.scala, rudder-web/src/main/webapp/style/rudder/rudder-menu.css, rudder-web/src/main/webapp/templates-hidden/components/NodeGroupForm.html
https://www.rudder-project.org/redmine/issues/9341
=> Fixes #9341: Wrong alignement of fields on group page

rudder-web/src/main/scala/com/normation/rudder/web/components/ShowNodeDetailsFromNode.scala, rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/SearchNodes.scala, rudder-web/src/main/webapp/javascript/rudder/angular/auditMode.js, rudder-web/src/main/webapp/style/rudder/rudder-jquery-ui.css
https://www.rudder-project.org/redmine/issues/9251
=> Fixes #9251: Infamous "Server cannot be contacted at this time" when trying to access node details of a deleted node

rudder-core/src/main/scala/com/normation/rudder/domain/reports/ReportType.scala
https://www.rudder-project.org/redmine/issues/9458
=> Fixes #9458: Invalid display in compliance for non-compliant report: shows "Not applicable" when not compliance

rudder-web/src/main/webapp/secure/nodeManager/searchNodes.html, rudder-web/src/main/webapp/style/rudder/rudder-menu.css, rudder-web/src/main/webapp/style/rudder/rudder.css
https://www.rudder-project.org/redmine/issues/9454
=> Fixes #9454: The query based search in the node details is inside the hardware table

rudder-core/src/main/scala/com/normation/rudder/domain/reports/StatusReports.scala, rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala, rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingService.scala, rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala, rudder-core/src/test/scala/com/normation/rudder/domain/reports/StatusReportTest.scala, rudder-core/src/test/scala/com/normation/rudder/services/reports/ExecutionBatchTest.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/compliance/ComplianceAPIService.scala, rudder-web/src/main/scala/com/normation/rudder/web/services/AsyncComplianceService.scala, rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/HomePage.scala
https://www.rudder-project.org/redmine/issues/9353
There seems to be a lot of changes, but in fact we just really:
- Add a RunComplianceStatus object and add it to NodeStatusReports,
- Use NodeStatusReports as the return type for a run analysis in ExecutionBatch, 
- during the analysis, add the correct RunComplianceStatus info based on reports and statusReports, 
- display a new message in ReportsDisplayer based on that new information.
All the remaining if just modifying everywhere to change (RunAndConfigInfo, Set[RuleNodeStatusInfo]) into a NodeStatusReports.
=> Fixes #9353: Adapt compliance computing to process abort message

rudder-core/src/main/scala/com/normation/rudder/reports/execution/ReportsExecutionRepositoryImpl.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala, rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala
https://www.rudder-project.org/redmine/issues/9518
WARNING: this PR is making NodeConfigID UNIQUE EVEN IF CONFIG IS THE SAME
=> Fixes #9518: When we just apply a configuration, reports is "missing" (not "pending")

rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/nodeconfig/NodeConfiguration.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/nodeconfig/NodeConfigurationCacheRepository.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/nodeconfig/NodeConfigurationService.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/nodeconfig/NodeConfigurationServiceImpl.scala, rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala, rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala
https://www.rudder-project.org/redmine/issues/9530
There was several problems:
- the nodeconfigId was regenerated too many times, 
- the date used in the new hashcode was not consistent, 
- there was a missing case in run analysis when the runConfigId and expectedConfigId were not the same, 
-  there was a missing case in compare/merge when directives were added to an existing rule.
=> Fixes #9530: Each policy generation lead to a new nodeconnfigid even without promise written

rudder-core/src/main/resources/reportsSchema.sql
https://www.rudder-project.org/redmine/issues/9517
=> Fixes #9517: On a fresh Rudder 4.0 install, expectedreports and expectedreportsnodes table are still present

rudder-web/src/main/webapp/javascript/rudder/angular/auditMode.js, rudder-web/src/main/webapp/templates-hidden/components/ComponentAgentPolicyMode.html
https://www.rudder-project.org/redmine/issues/9539
=> Fixes #9539: Two generation are started after changing the global policy mode

rudder-web/pom.xml, rudder-web/src/test/resources/api/api_v1.yml, rudder-web/src/test/resources/api/api_v2.yml, rudder-web/src/test/scala/com/normation/rudder/web/rest/RestStatusTest.scala, rudder-web/src/test/scala/com/normation/rudder/web/rest/RestTestSetUp.scala, rudder-web/src/test/scala/com/normation/rudder/web/rest/TestRestFromFileDef.scala
https://www.rudder-project.org/redmine/issues/9201
=> Fixes #9201: Add basic infrastructure to test REST API

rudder-core/src/main/resources/reportsSchema.sql, rudder-core/src/main/scala/com/normation/rudder/db/Doobie.scala, rudder-core/src/main/scala/com/normation/rudder/domain/reports/ComplianceLevel.scala, rudder-core/src/main/scala/com/normation/rudder/domain/reports/StatusReports.scala, rudder-core/src/main/scala/com/normation/rudder/reports/execution/ReportsExecutionService.scala, rudder-core/src/main/scala/com/normation/rudder/repository/ComplianceRepository.scala, rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ComplianceRepository.scala, rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala, rudder-core/src/test/scala/com/normation/rudder/domain/reports/StatusReportTest.scala, rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala, rudder-core/src/test/scala/com/normation/rudder/services/reports/ExecutionBatchTest.scala, rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/compliance/ComplianceAPIData.scala, rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala
https://www.rudder-project.org/redmine/issues/9645
This PR add the storage of the compliance by node by run in a new Postgres Table. 
The only interesting things are: 
- when we call the store action: in ReportsExecutionService, just after having updated the node compliance cache (we use the result, all calculus are done)
- the database structure. 
There is a good description on the table declaration of field. Some more "what/why":
- nodeId, runTimestamp, nodeConfigId: what we are interested in to do queries. We would much likely want to get the last line by runTimestamp for a nodeId. 
- endOfLife: date after which the compliance is not valide anymore. If no new runs, it means the node doesn't send reports anymore. Perhaps the name is not that good, and "endDate" should be used. 
- …
=> Fixes #9645: Add a table for node compliance

rudder-web/src/main/scala/com/normation/rudder/web/components/RuleGrid.scala
https://www.rudder-project.org/redmine/issues/9802
=> Fixes #9802: Error when displaying Rules when a rule is applying a directive that does not exists anymore

rudder-core/src/test/scala/com/normation/rudder/services/policies/write/WriteSystemTechniquesTest.scala, rudder-web/src/main/resources/configuration.properties.sample, rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala
https://www.rudder-project.org/redmine/issues/9865
=> Fixes #9865: Move hooks to /opt/rudder/etc/

rudder-core/src/main/scala/com/normation/rudder/domain/reports/StatusReports.scala, rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala, rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/HomePage.scala
https://www.rudder-project.org/redmine/issues/9857
=> Fixes #9857: ReportingServiceImpl moves around a lot of data and is fairly slow

rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
https://www.rudder-project.org/redmine/issues/9885
=> Fixes #9885: In group page, remove reference to CFEngine in generated classes

rudder-core/src/main/resources/reportsSchema.sql, rudder-core/src/main/scala/com/normation/rudder/datasources/DataSource.scala, rudder-core/src/main/scala/com/normation/rudder/datasources/DataSourceRepository.scala, rudder-core/src/main/scala/com/normation/rudder/datasources/DataSourceSerializer.scala, rudder-core/src/main/scala/com/normation/rudder/db/Doobie.scala, rudder-core/src/main/scala/com/normation/rudder/repository/json/JsonExctractorUtils.scala, rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/RestDataSerializer.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/RestExtractorService.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/datasource/DataSourceApiService.scala, rudder-web/src/test/scala/com/normation/rudder/web/rest/RestDataSourceTest.scala
https://www.rudder-project.org/redmine/issues/9701
This PR consists in two things:
Adding a backend for datasources, easy part
Having one json serialization that will work both for backend and rest api. Most complicated part was that it has not the same needs (backend data must be complete, rest API may be partial)
I used some Monad magic from Scalaz (but I think i need an implicit somewere to make it much more readable) 
Two implementation on json serialization, one with monad Id (backend, fails if a data is missing), one with Option (allow to have partial data)
enjoy!
=> Fixes #9701: Store data sources in backend

rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/RuleCompliance.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/RuleDisplayer.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/RuleGrid.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/TagsEditForm.scala, rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala, rudder-web/src/main/webapp/javascript/rudder/angular/filters.js, rudder-web/src/main/webapp/javascript/rudder/angular/tags.js, rudder-web/src/main/webapp/javascript/rudder/directive.js, rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js, rudder-web/src/main/webapp/javascript/rudder/rudder.js, rudder-web/src/main/webapp/javascript/rudder/tree.js, rudder-web/src/main/webapp/secure/configurationManager/directiveManagement.html, rudder-web/src/main/webapp/secure/configurationManager/ruleManagement.html, rudder-web/src/main/webapp/style/rudder/rudder-menu.css, rudder-web/src/main/webapp/style/rudder/rudder-tags.css, rudder-web/src/main/webapp/style/rudder/rudder.css, rudder-web/src/main/webapp/templates-hidden/components/ComponentDirectiveEditForm.html, rudder-web/src/main/webapp/templates-hidden/components/ComponentRuleEditForm.html, rudder-web/src/main/webapp/templates-hidden/components/ComponentTags.html
https://www.rudder-project.org/redmine/issues/9798
=> Fixes #9798: UI to display tags

rudder-core/src/main/resources/Migration/dbMigration-4.0.x-4.1-add-datasource-table.sql, rudder-core/src/main/resources/reportsSchema.sql, rudder-core/src/main/scala/com/normation/rudder/datasources/DataSourceService.scala, rudder-core/src/main/scala/com/normation/rudder/datasources/UpdateHttpDataset.scala
https://www.rudder-project.org/redmine/issues/9942
=> Fixes #9942: Migration script to add missing table in Postgres

rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala
https://www.rudder-project.org/redmine/issues/9836
=> Fixes #9836: Deprecate API v5, v6 and v7, and remove API v2,3,4

rudder-core/src/main/scala/com/normation/rudder/datasources/DataSourceSerializer.scala, rudder-core/src/main/scala/com/normation/rudder/repository/json/JsonExctractorUtils.scala, rudder-web/src/test/scala/com/normation/rudder/web/rest/RestDataSourceTest.scala
https://www.rudder-project.org/redmine/issues/10054
=> Fixes #10054: Change headers AND params in datasource api to be an array

rudder-web/pom.xml, rudder-web/src/main/webapp/javascript/rudder/angular/dataSource.js, rudder-web/src/main/webapp/javascript/rudder/rudder.js, rudder-web/src/main/webapp/secure/administration/dataSourceManagement.html, rudder-web/src/main/webapp/style/rudder/rudder-datasource.css, rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/10017
=> Fixes #10017: Improve data sources UI

rudder-web/src/main/scala/com/normation/rudder/web/components/SearchNodeComponent.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/Groups.scala, rudder-web/src/main/webapp/javascript/rudder/rudder.js, rudder-web/src/main/webapp/style/rudder/rudder-menu.css, rudder-web/src/main/webapp/style/rudder/rudder.css
https://www.rudder-project.org/redmine/issues/10116
=> Fixes #10116: On Group creation, the tooltip on the "Save" button doesn't appear when it is disabled

rudder-web/src/main/scala/com/normation/rudder/appconfig/ConfigService.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/RuleDisplayer.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/RuleGrid.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/popup/ExpectedPolicyPopup.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/popup/ModificationValidationPopup.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PropertiesManagement.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/RuleManagement.scala, rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js, rudder-web/src/main/webapp/secure/administration/policyServerManagement.html
https://www.rudder-project.org/redmine/issues/10157
=> Fixes #10157: Add an option to not display rule status/recent changes in directives screen

rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/RuleDisplayer.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala, rudder-web/src/main/webapp/javascript/rudder/angular/filters.js, rudder-web/src/main/webapp/javascript/rudder/rudder.js, rudder-web/src/main/webapp/secure/configurationManager/directiveManagement.html, rudder-web/src/main/webapp/secure/configurationManager/ruleManagement.html, rudder-web/src/main/webapp/style/rudder/rudder-directives.css, rudder-web/src/main/webapp/style/rudder/rudder-menu.css, rudder-web/src/main/webapp/style/rudder/rudder-rules.css, rudder-web/src/main/webapp/style/rudder/rudder-tags.css, rudder-web/src/main/webapp/style/rudder/rudder.css, rudder-web/src/main/webapp/templates-hidden/components/ComponentDirectiveEditForm.html, rudder-web/src/main/webapp/templates-hidden/components/ComponentRuleEditForm.html, rudder-web/src/main/webapp/templates-hidden/components/ComponentTags.html
https://www.rudder-project.org/redmine/issues/10080
=> Fixes #10080: Reorganize Directives page interface

rudder-web/src/main/webapp/secure/administration/apiManagement.html
https://www.rudder-project.org/redmine/issues/10250
=> Fixes #10250: When trying to create a new API account that has the same name as an existing acocunt, nothing happen

rudder-core/src/main/scala/com/normation/rudder/domain/policies/DirectiveDiff.scala, rudder-core/src/main/scala/com/normation/rudder/domain/policies/RuleDiff.scala, rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDiffMapper.scala, rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogFactory.scala, rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlSerialisationImpl.scala, rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlUnserialisationImpl.scala
https://www.rudder-project.org/redmine/issues/10275
=> Fixes #10275: When we add/remove/update a tag to a Directive/Rule, we get an empty event log

rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
https://www.rudder-project.org/redmine/issues/7092
=> Fixes #7092: Include Timezone in Node Info

rudder-web/src/main/scala/com/normation/rudder/web/rest/RestCompletion.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala, rudder-web/src/main/webapp/javascript/rudder/angular/filters.js, rudder-web/src/main/webapp/javascript/rudder/rudder.js
https://www.rudder-project.org/redmine/issues/10271
=> Fixes #10271: When we filter directive by tags, and update a directive, the tree is refreshed without taking into account the filter

rudder-core/src/main/scala/com/normation/rudder/domain/nodes/Node.scala, rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogDetailsService.scala, rudder-core/src/test/scala/com/normation/rudder/domain/nodes/NodePropertiesTest.scala, rudder-core/src/test/scala/com/normation/rudder/services/eventlog/NodeEventLogFormatV6Test.scala, rudder-core/src/test/scala/com/normation/rudder/services/policies/TestNodeAndParameterLookup.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/RestExtractorService.scala
https://www.rudder-project.org/redmine/issues/10301
=> Fixes #10301: Remove "rights" in node property

rudder-web/src/main/scala/com/normation/rudder/web/snippet/HomePage.scala, rudder-web/src/main/webapp/javascript/rudder/homePage.js, rudder-web/src/main/webapp/secure/index.html, rudder-web/src/main/webapp/style/rudder/rudder-bootstrap.css, rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/10315
=> Fixes #10315: Small fixes on dashboard display

rudder-web/src/main/scala/com/normation/rudder/web/comet/AsyncDeployment.scala, rudder-web/src/main/scala/com/normation/rudder/web/services/EventListDisplayer.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/ClearCache.scala
https://www.rudder-project.org/redmine/issues/10383
=> Fixes #10383: If I click on "Regenerate all policies", it clears the cache of changes, and slows down a lot the web interface

rudder-web/src/main/resources/logback.xml
https://www.rudder-project.org/redmine/issues/10471
=> Fixes #10471: In debug verbosity, logs are overflowed by logs about com.zaxxer.hikari.pool

rudder-web/src/main/scala/com/normation/rudder/web/comet/AsyncDeployment.scala
https://www.rudder-project.org/redmine/issues/10451
=> Fixes #10451: A running Policy generation is not displayed on the Status dropdown

rudder-web/src/main/scala/com/normation/rudder/web/services/LogDisplayer.scala
https://www.rudder-project.org/redmine/issues/10553
=> Fixes #10553: Log contains debug info  "**** got string: {"start":"2017-03-09 00:00:00", "end", "2017-03-11 00:00:00"}"

rudder-web/src/main/webapp/javascript/rudder/angular/auditMode.js, rudder-web/src/main/webapp/javascript/rudder/angular/nodeProperties.js
https://www.rudder-project.org/redmine/issues/10578
=> Fixes #10578: Cannot add node property when audit message is mandatory

rudder-web/src/main/webapp/javascript/rudder/angular/nodeProperties.js
https://www.rudder-project.org/redmine/issues/10569
=> Fixes #10569: Adding a json node property by UI make it a string

rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala
https://www.rudder-project.org/redmine/issues/10636
=> Fixes #10636: When no reports has been received from a node for new policy, message contains unexpanded variable

rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckConnections.scala
https://www.rudder-project.org/redmine/issues/10654
=> Fixes #10654: If an error happen during boostrap, the webapp starts but is in a zombie state and the error page is not displayed

rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckDIT.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/EditPolicyServerAllowedNetwork.scala
https://www.rudder-project.org/redmine/issues/8017
=> Fixes #8017: Adding an authorized network when "common-root" directive is missing seems to work, but actually fails

rudder-core/src/main/scala/com/normation/rudder/services/policies/write/Cf3PromisesFileWriterService.scala
https://www.rudder-project.org/redmine/issues/10908
=> Fixes #10908: When hooks in policy-generation-node-ready or policy-generation-node-finished fails, there is no error in the generation

rudder-core/src/main/resources/hooks.d/node-post-acceptance/hook-template, rudder-core/src/main/resources/hooks.d/node-post-acceptance/readme.adoc, rudder-core/src/main/scala/com/normation/rudder/services/servers/NewNodeManager.scala, rudder-core/src/main/scala/com/normation/rudder/services/servers/RemoveNodeService.scala, rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala
https://www.rudder-project.org/redmine/issues/11191
=> Fixes #11191: Add a post-node-acceptation hook

rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
https://www.rudder-project.org/redmine/issues/11229
=> Fixes #11229: Wrong sort on compliance in tables

rudder-core/src/main/resources/hooks.d/node-post-deletion/readme.adoc, rudder-core/src/main/resources/hooks.d/node-pre-deletion/readme.adoc
https://www.rudder-project.org/redmine/issues/11307
=> Fixes #11307: There is no "node-post-deletion" hook directory but a "node-pre-deletion" one

rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala, rudder-web/src/main/webapp/secure/configurationManager/directiveManagement.html, rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://www.rudder-project.org/redmine/issues/11291
=> Fixes #11291: Highlight DSC compatible technique versions in the available versions table.

rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/Groups.scala
https://www.rudder-project.org/redmine/issues/11323
=> Fixes #11323: Fold automatically Group categories if there are too many of them (4.1)

rudder-web/src/main/scala/com/normation/rudder/web/snippet/HomePage.scala
https://www.rudder-project.org/redmine/issues/11353
=> Fixes #11353: The Rudder version graph in the dashboard only display major version for windows nodes

rudder-core/src/main/scala/com/normation/rudder/domain/queries/CmdbQuery.scala, rudder-core/src/test/resources/ldap-data/inventory-sample-data.ldif, rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala
https://www.rudder-project.org/redmine/issues/11168
=> Fixes #11168: Search believe that CFEngine agents with "dsc" in their keys are also DSC agent 

rudder-core/src/main/scala/com/normation/cfclerk/domain/RegexConstraint.scala
https://www.rudder-project.org/redmine/issues/11449
=> Fixes #11449: Allow variable as directive parameters in regexp validated inputs 

rudder-core/src/main/resources/hooks.d/node-post-acceptance/hook-template, rudder-core/src/main/resources/hooks.d/node-post-deletion/hook-template, rudder-core/src/main/resources/hooks.d/node-pre-deletion/hook-template, rudder-core/src/main/resources/hooks.d/policy-generation-node-finished/hook-template, rudder-core/src/main/resources/hooks.d/policy-generation-node-ready/10-cf-promise-check, rudder-core/src/main/resources/hooks.d/policy-generation-node-ready/42-ignore_disabled_non_exec, rudder-core/src/main/resources/hooks.d/policy-generation-node-ready/42-ignore_extension.disabled, rudder-core/src/main/resources/hooks.d/policy-generation-node-ready/90-change-perm, rudder-core/src/main/resources/hooks.d/policy-generation-node-ready/hook-template
https://www.rudder-project.org/redmine/issues/11671
=> Fixes #11671: Update doc of hooks to add DSC mention and remove cfengine-nova

rudder-core/src/main/scala/com/normation/rudder/domain/queries/CmdbQuery.scala, rudder-core/src/main/scala/com/normation/rudder/domain/queries/DitQueryData.scala, rudder-core/src/main/scala/com/normation/rudder/services/queries/LdapQueryProcessor.scala, rudder-core/src/test/resources/ldap-data/inventory-sample-data.ldif, rudder-core/src/test/resources/logback-test.xml, rudder-core/src/test/scala/com/normation/rudder/domain/queries/CmdbQueryTest.scala, rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala, rudder-web/src/main/resources/ldapObjectAndAttributes.properties
https://www.rudder-project.org/redmine/issues/10599
This PR allows to corretly process JSON values stored in LDAP for the three kind of object needed to be search for in group: Process, Environment variables, and Node properties. 
The first commit split the common JsonComparator in three specialized one, one for each case, which allows to simplify the simple case, and make a special case for node properties. 
The strategie to correctly handle node properties is to make precise filter for eq/not eq for both quoted and quoted values. It means that we are now extremelly dependant of serialization format (we already were, now it is consumed). 
And for regex case, we had a pre-regex JSON parsing which allows to filter out other field than name/value so that we are sure to not return false …
=> Fixes #10599: Impossible to search or build groups based on JSON values in node properties

rudder-core/src/main/scala/com/normation/rudder/services/policies/SystemVariableService.scala, rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala, rudder-rest/src/main/scala/com/normation/appconfig/ConfigService.scala, rudder-rest/src/main/scala/com/normation/rudder/rest/settings/SettingsApi.scala, rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PropertiesManagement.scala, rudder-web/src/main/webapp/secure/administration/policyServerManagement.html
https://www.rudder-project.org/redmine/issues/10719
=> Fixes #10719: Remove the skipidentify variable and settings page entry

rudder-core/pom.xml
https://www.rudder-project.org/redmine/issues/11777
=> Fixes #11777: Lift-webkit has a dependency toward rhino (which conflicts with JS param eval)

rudder-core/src/main/scala/com/normation/rudder/batch/CheckInventoryUpdate.scala, rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala, rudder-web/src/main/resources/logback.xml, rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala
https://www.rudder-project.org/redmine/issues/1411
Be careful to notice that only a SUBSET of inventories are observed, ie only node properties, node main information (what is in node summary), machine type. 
Other inventory information are not important aspect for policy generation (appart for groups of course, but that is covered in dynamic group update scheduled job). So it should be fine.
=> Fixes #1411: Node (hostname,policyserver,...) modification should trigger promises regeneration

rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/EditPolicyServerAllowedNetwork.scala, rudder-web/src/main/webapp/javascript/rudder/authorizedNetworks.js, rudder-web/src/main/webapp/secure/administration/policyServerManagement.html
https://www.rudder-project.org/redmine/issues/11797
=> Fixes #11797: Impossible to add authorized network for relay

rudder-web/src/main/scala/com/normation/rudder/web/components/NodeStateForm.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/ShowNodeDetailsFromNode.scala, rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala, rudder-web/src/main/scala/com/normation/rudder/web/services/SrvGrid.scala, rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js, rudder-web/src/main/webapp/style/rudder/rudder-menu.css, rudder-web/src/main/webapp/templates-hidden/components/ComponentNodeState.html
https://www.rudder-project.org/redmine/issues/11810
The PR also add a little label in node list when the state is not "enabled" so that we get a chance to find back node that are not in the default state.
=> Fixes #11810: Make node state configurable in node details

rudder-core/src/main/scala/com/normation/rudder/domain/reports/ExpectedReports.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/DataStructures.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala, rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala, rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeExpectedReportTest.scala, rudder-core/src/test/scala/com/normation/rudder/services/policies/RuleValServiceTest.scala, rudder-core/src/test/scala/com/normation/rudder/services/policies/write/WriteSystemTechniquesTest.scala, rudder-core/src/test/scala/com/normation/rudder/services/reports/ExecutionBatchTest.scala
https://www.rudder-project.org/redmine/issues/11876
=> Fixes #11876: Broken reporting in Rudder 4.3 with standart directives

rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PolicyWriterService.scala
https://www.rudder-project.org/redmine/issues/11862
=> Fixes #11862: RudderUniqueID is not replaced  when used in OUTPATH

rudder-core/src/main/resources/ldap/rudder.schema, rudder-core/src/main/scala/com/normation/rudder/api/ApiAccountRepository.scala, rudder-core/src/main/scala/com/normation/rudder/api/DataStructures.scala, rudder-core/src/main/scala/com/normation/rudder/domain/RudderLDAPConstants.scala, rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala, rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlSerialisationImpl.scala, rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlUnserialisationImpl.scala, rudder-rest/src/main/scala/com/normation/rudder/rest/ApiAuthorization.scala, rudder-rest/src/main/scala/com/normation/rudder/rest/ApiDatastructures.scala, rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala, rudder-rest/src/main/scala/com/normation/rudder/rest/RoleApiMapping.scala, rudder-rest/src/main/scala/com/normation/rudder/rest/internal/RestApiAccounts.scala, rudder-rest/src/main/scala/com/normation/rudder/rest/lift/LiftApiDispather.scala, rudder-rest/src/main/scala/com/normation/rudder/rest/lift/UserApi.scala, rudder-rest/src/main/scala/com/normation/rudder/service/user/UserService.scala, rudder-rest/src/test/scala/com/normation/rudder/web/rest/RestTestSetUp.scala, rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala, rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala, rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckApiTokenAutorizationKind.scala, rudder-web/src/main/scala/com/normation/rudder/web/model/CurrentUser.scala
Issue: https://www.rudder-project.org/redmine/issues/12111
The main changes are:
- the ApiAccounKind now holds authorization for PublicApi type, other types don't have specific authz (they are induced by account kind),
- we have 5 ApiAuthorizationKind: None, RO, RW, ACL
- ACL is interpreted only when the plugin is enable. When that kind is used without the plugin, authorization are interpreted as *RO* (but actual ACL are kept, so that re-enableling the plugin make find back ACLs)
- when migrating from 4.2, authorization are set to *RW*
- also corrected the logs so that we can have relevant information in debug mode:
```
[2018-02-16 12:17:24] DEBUG api-processing - Processing request: POST /rudder-web/api/latest/settings/node_onaccept_default_policyMode [JSON request with valid JSON body] …
```
=> Fixes #12111 Make fine-grained API authorization a plugin

rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala
https://www.rudder-project.org/redmine/issues/12216
We were using an User account in place of an API account, so that went throught the User authentication pipeline which forbid un authenticated request.
=> Fixes #12216: Unathenticated API v1 are not accessible anymore

rudder-core/src/main/scala/com/normation/rudder/batch/UpdateDynamicGroups.scala, rudder-core/src/main/scala/com/normation/rudder/domain/logger/ApplicationLogger.scala, rudder-core/src/main/scala/com/normation/rudder/services/queries/DynGroupService.scala, rudder-core/src/main/scala/com/normation/rudder/services/servers/NewNodeManager.scala, rudder-core/src/test/scala/com/normation/rudder/services/queries/TestPendingNodePolicies.scala, rudder-web/src/main/resources/logback.xml, rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/popup/ExpectedPolicyPopup.scala
https://www.rudder-project.org/redmine/issues/12060
Implements algorithm described in above ticket (with a test!)
I also added a "NodeLogger" / "NodeLogger.Pending" / "NodeLogger.Pending.Policies" to be able to log (in trace) the behavior of the algo in case we need to debug in prod. 
And I changed the use of logger in NewNodeManager to use NodeLogger.Pending (nothing interesing in that file)
=> Fixes #12060: Incomplete "Rules to be applied" summary when accepting a new nodes when using groups of groups

rudder-core/src/main/scala/com/normation/cfclerk/domain/Constraint.scala, rudder-core/src/main/scala/com/normation/cfclerk/domain/VariableAndSection.scala, rudder-core/src/main/scala/com/normation/rudder/domain/nodes/Node.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/write/AgentSpecificLogic.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/write/BuildBundleSequence.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/write/Cf3PolicyDraft.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PrepareTemplateVariables.scala, rudder-core/src/test/scala/com/normation/cfclerk/domain/VariableTest.scala, rudder-core/src/test/scala/com/normation/rudder/services/policies/write/PolicyInstanceAgregationTest.scala, rudder-core/src/test/scala/com/normation/rudder/services/policies/write/PrepareTemplateVariableTest.scala, rudder-core/src/test/scala/com/normation/rudder/services/policies/write/WriteSystemTechniquesTest.scala, rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala
https://www.rudder-project.org/redmine/issues/12390
This is an API breaking change for Windows DSC plugin. 
So, the main problem was that we escaped value set in Directive only for a CFEngine Agent. 
The pull request change two majors things.  
First, it changes where the escape logic is in the code: 
- now, each agent has its own "escape" method bundled in its "agent specific generation" (where the agent-specific policy writing was stored). 
- this change make the fact that we needed an "agent register" apparent. So that `AgentRegister` is now a standalone class, with utility method to find what agent matches an `AgentType`/`osDetails` and does things with it. 
Secondly, it changes the types of values in string template. Until now, we were allowing values of type `Any`. But we don't …
=> Fixes #12390: Doubled "\" in GM call

rudder-core/src/main/scala/com/normation/rudder/domain/queries/CmdbQuery.scala, rudder-core/src/main/scala/com/normation/rudder/domain/queries/DitQueryData.scala, rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala, rudder-core/src/main/scala/com/normation/rudder/services/queries/LdapQueryProcessor.scala, rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala, rudder-web/src/main/resources/ldapObjectAndAttributes.properties, rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala, rudder-web/src/main/scala/com/normation/rudder/web/components/SearchNodeComponent.scala
https://www.rudder-project.org/redmine/issues/12439
=> Fixes #12439:  Allow to search on machine type in search nodes request (backport 4.1)

rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala, rudder-core/src/test/scala/com/normation/rudder/services/reports/ExecutionBatchTest.scala
https://www.rudder-project.org/redmine/issues/12616
=> Fixes #12616: ${const.dollar} in generic method parameter leads to missing report

rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PrepareTemplateVariables.scala
https://www.rudder-project.org/redmine/issues/12674
=> Fixes #12674: Policies regeneration error when using a parameters with " char

rudder-core/src/main/resources/rudder-js.policy, rudder-core/src/main/scala/com/normation/rudder/domain/logger/ApplicationLogger.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/JavascriptEngine.scala, rudder-core/src/test/scala/com/normation/rudder/services/policies/TestJsEngine.scala, rudder-web/src/test/scala/com/normation/rudder/javascript/CalculateComplianceTest.scala
https://www.rudder-project.org/redmine/issues/12450
This PR is done against 4.3. We will keep a basic, limited support of Java 9/10 for rudder 4.1, and we will have an extendable one in 4.3.
=> Fixes #12450: JS sandbox permission must be defined in a file

qa-test, rudder-core/src/test/resources/convertOpenLDAPSchema.py
https://www.rudder-project.org/redmine/issues/12655
=> Fixes #12655: Use pylint to verify python code in rudder repo

rudder-core/src/main/scala/com/normation/rudder/services/policies/write/Cf3PromisesFileWriterService.scala
https://www.rudder-project.org/redmine/issues/12730
=> Fixes #12730: Moving policies to their final position (last step of policies writing) could be improved

rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala, rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala, rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala, rudder-core/src/test/scala/com/normation/rudder/services/reports/ComplianceTest.scala, rudder-core/src/test/scala/com/normation/rudder/services/reports/ExecutionBatchTest.scala, rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala, rudder-web/src/main/scala/com/normation/rudder/appconfig/ConfigService.scala, rudder-web/src/main/scala/com/normation/rudder/web/rest/settings/SettingsApi.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PropertiesManagement.scala, rudder-web/src/main/webapp/secure/administration/policyServerManagement.html
https://www.rudder-project.org/redmine/issues/12719
Not yet finished (remains the we selection part in Setting). But it's a fairly big change. 
I'm quite confident on it, because we have a very good test coverage on that part. 
So, basically, I completly changed the way we pair report <-> expected component value. This was needed to allows to be more lenient in case of ducplicate keys and unbounded variable size (from iterators). 
The main modification are: 
- we have a parameter set to keep what is the unexpected interpretation: UnexpectedReportInterpretation
- we don't sort anymore the kind of component values in 3 cases (None, simple value, var pattern). In place of that, we create for each component value a Value utility class with the following info: 
-  value / unexpanded value: the …
=> Fixes #12719: Some reports are duplicated between agent and postgres leading to "unexpected" compliance 

rudder-core/src/main/scala/com/normation/rudder/services/policies/write/Cf3PromisesFileWriterService.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PromiseWriteDataStructures.scala
https://www.rudder-project.org/redmine/issues/12702
=> Fixes #12702: Method copyResourceFile is quite inefficient

rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala, rudder-web/src/main/scala/com/normation/rudder/web/comet/AsyncDeployment.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/Authz.scala, rudder-web/src/main/scala/com/normation/rudder/web/snippet/CommonLayout.scala, rudder-web/src/main/webapp/templates-hidden/common-layout.html
https://www.rudder-project.org/redmine/issues/13026
=> Fixes #13026: Removing workflow comet leads to missing user information and session is destroyed

rudder-core/pom.xml
https://www.rudder-project.org/redmine/issues/12832
=> Fixes #12832: nuProcess 1.2.0 crashes on JDK 10

rudder-web/src/main/resources/content-types.properties
https://www.rudder-project.org/redmine/issues/13334
Replacing previous PR: https://github.com/Normation/rudder/pull/2014
=> Fixes #13334: Bad mime type for our js files: application/js

rudder-core/src/main/resources/reportsSchema.sql, rudder-core/src/main/scala/com/normation/rudder/batch/AutomaticReportsCleaner.scala, rudder-core/src/main/scala/com/normation/rudder/domain/reports/CleanReportsAction.scala, rudder-core/src/main/scala/com/normation/rudder/repository/ExpectedReportsRepository.scala, rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ComplianceRepository.scala, rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ExpectedReportsJdbcRepository.scala, rudder-core/src/main/scala/com/normation/rudder/services/system/DatabaseManager.scala, rudder-core/src/test/scala/com/normation/rudder/db/GenerateCompliance.scala, rudder-web/src/main/resources/configuration.properties.sample, rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
https://www.rudder-project.org/redmine/issues/13432
=> Fixes #13432: Git merge issue between Rudder 4.3 and Rudder 5.0

rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala
https://www.rudder-project.org/redmine/issues/13615
=> Fixes #13615: Bad explanation for generic variable overide priority cause people making the opposite of what is needed

rudder-core/src/main/resources/rudder-js.policy, rudder-core/src/main/scala/com/normation/rudder/batch/AsyncDeploymentAgent.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/JavascriptEngine.scala, rudder-web/src/main/resources/logback.xml
https://www.rudder-project.org/redmine/issues/13014
So, more information: the problem is due to security check that are initiated during other security checks. Typically, trying to execute:
```
....
681          case x: FilePermission if( x.getActions == "read" && (x.getName.contains(".class") || x.getName.endsWith(".jar")  || x.getName.endsWith(".so") ) ) => // ok
```
needs to load FilePermission class file, and that need to resolve URL (more permission), and then load a file from fs (more perm).
It seems that something changed in later JVM 1.8 JDK releases about what classes are loaded when. And that results in infinite loops due to impossibility to linearize the graphe of dependance check.
I thought about two resolutions, a correct one and a hacky one. Unfortunatly, I'm not able to …
=> Fixes #13014: StackOverflowError during policy generation in JavascriptEngine - debian 9.5 with jdk 1.8.0_181

rudder-web/src/main/resources/applicationContext-security-auth-rootAdmin.xml, rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala, rudder-web/src/main/scala/bootstrap/liftweb/DynamicRudderProviderManager.java, rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala, rudder-web/src/main/scala/bootstrap/liftweb/RudderProviderManager.java
https://www.rudder-project.org/redmine/issues/13695
As we can't control when and how spring is initializing its beans, I changed the spring authentication provider that is in charge of asking to backends is authentication is OK and did one for Rudder which dynamically get the list of beans depending of plugin status. 
The part that give the list of allowed backends is controled by Rudder, and is independant from the spring init part. So it accpets latter binding of plugins. 
Still, that means that all the code/config files must be present at boot time. To restrict the scope of possible unwanted error, we only look (and let spring load) code for plugins in the `rudder.auth.provider` list. 
(that also mean that allowing runtime change of authentication is still out of reach)
=> Fixes #13695: Authentication providers are not loaded before authentication is initialized

rudder-core/src/main/scala/com/normation/rudder/services/policies/MergePolicyService.scala, rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala, rudder-core/src/test/scala/com/normation/rudder/services/policies/write/WriteSystemTechniquesTest.scala
https://issues.rudder.io/issues/13674
In fact, we don't want to put "skipped" for the directive in other rules (meaning: already exec in previous rule) because that's not the same semantic as "skipped" for unique technique (meaning: not exec at all)
=> Fixes #13674: Compliance error (missing) when a directive is applied by two rules on a node

rudder-web/src/main/scala/com/normation/rudder/web/services/JsTableData.scala
https://issues.rudder.io/issues/13349
=> Fixes #13349: Quotes in reports are displayed as &quot; in the web interface

rudder-core/src/main/resources/hooks.d/node-post-deletion/10-clean-policies, rudder-core/src/main/scala/com/normation/rudder/services/servers/RemoveNodeService.scala
https://issues.rudder.io/issues/4709
=> Fixes #4709: When a node is deleted, its generated promises are not removed

rudder-core/src/main/scala/com/normation/rudder/services/servers/RemoveNodeService.scala
https://issues.rudder.io/issues/13843
=> Fixes #13843:  Inventory keeps its key certified when node is deleted even is keystatus is erased

rudder-core/src/main/scala/com/normation/cfclerk/domain/TechniqueResource.scala, rudder-core/src/main/scala/com/normation/cfclerk/xmlparsers/TechniqueParser.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/DataStructures.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/write/BuildBundleSequence.scala
https://issues.rudder.io/issues/14041
=> Fixes #14041: Replace all RudderUniqueID in paths for inputs list and rudder.json, and correctly generate paths based on agent type

rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala, rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckApiTokenAutorizationKind.scala
https://issues.rudder.io/issues/13913
=> Fixes #13913: Logs full of WARN  Attribute 'apiAuthorizationKind' or 'expirationTimestamp' is defined for API account but it will be ignored

rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala, rudder-core/src/main/scala/com/normation/rudder/services/policies/write/Cf3PromisesFileWriterService.scala
https://issues.rudder.io/issues/10973
I'm not sure it won't still explode the stack, because perhaps the problem was in the `Task.gather` part, and in that case, we can't do much. But I suspect it was in the processing of the big errors messages which were most likely done in the stack. 
I changed the way they are gathered so that all identical error messages for the hooks are group together. It should be much smaller (and it is actually far better for understanding).
The new results looks like: 
```
[2019-01-09 17:51:21] ERROR com.normation.rudder.batch.AsyncDeploymentAgent$DeployerAgent - Error when updating policy, reason Cannot write nodes configuration <- Error when executing hooks:
Exit code=-2147483648 for hook: '/opt/rudder/etc/hooks.d/policy-generation-node-ready/10-cf-promise-che …
```
=> Fixes #10973: When hooks are exiting an error we can have stackoverfloww error if there are many of them

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala, webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/NodeGroupForm.html
https://issues.rudder.io/issues/11911
=> Fixes #11911: Rule list on group

webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/FullInventoryRepositoryImpl.scala
https://issues.rudder.io/issues/14533
=> Fixes #14533: Build fails in 4.3 after correcting " Error about fail move of machine doesn't give sufficient context information"

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/TechniqueLibraryUpdateNotification.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/TechniqueReader.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/GitTechniqueReader.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/TechniqueRepositoryImpl.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/eventlog/EventLogCategories.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/eventlog/TechniqueEventLog.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/policies/TechniqueDiff.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/EventLogRepository.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogFactory.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/TechniqueAcceptationDatetimeUpdater.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/TechniqueReloadingCallbacks.scala, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/EventListDisplayer.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/TechniqueReloadingCallbacks.scala
https://issues.rudder.io/issues/14312
the provided commitid is the revision tree one, not a real commit id. The problem is that we totally can have several git commit without a reload, and to we can only log the state of the git when the reload is done. It is not possible to change that without changing all the logic on technique library, which is extremelly dangerous.
=> Fixes #14312: Missing eventlogs for technique editor action and technique update

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/model/JsInitContextLinkUtil.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleEditForm.scala, webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/groupManagement.js, webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/ruleDirectives.js, webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css, webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-rules.css, webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder.css, webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentRuleEditForm.html
https://issues.rudder.io/issues/14536
=> Fixes #14536: Add a button to show/hide Directives and Groups tree in Rule details

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
https://issues.rudder.io/issues/14568
=> Fixes #14568: Exception at Rudder start: com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'rudder.jvm'

webapp/sources/rudder/rudder-core/pom.xml, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/reports/ReportingConfiguration.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/BoxSpecMatcher.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportExecutionTest.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportsProgressTest.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportsTest.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala, webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/RudderUncaughtExceptionExample.scala
https://issues.rudder.io/issues/14599
=> Fixes #14599: Rudder postgres unit test are broken

relay/sources/Makefile
https://issues.rudder.io/issues/14670
=> Fixes #14670: Adapt relay makefile for rudder repo

relay/sources/Makefile
https://issues.rudder.io/issues/14693
=> Fixes #14693: Failed build of rudder-relayd man page on debian 9

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/HistorizationService.scala
https://issues.rudder.io/issues/14770
=> Fixes #14770: Invalid comparision of String and Option[String] in HistorizationService 

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/UpdateDynamicGroups.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/ItemArchiveManagerImpl.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/DynGroupUpdaterService.scala, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala
https://issues.rudder.io/issues/4480
=> Fixes #4480: When restoring archive (full or groups) dynamic groups are created empty

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/InfoApi.scala
https://issues.rudder.io/issues/14807
=> Fixes #14807: API info does not list endpoints in their sorted order 

relay/sources/Makefile
https://issues.rudder.io/issues/14897
=> Fixes #14897: Relay packages uses python3 to build virtualenv

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/MergePolicyService.scala
https://issues.rudder.io/issues/15022
=> Fixes #15022: NON STABLE POLICY ON NODE warning when the same directive is used in two rules 

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ReportsRepository.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ReportsJdbcRepository.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/NodeChangesService.scala
https://issues.rudder.io/issues/15041
=> Fixes #15041: The computation of changes by rules, at start of web interface, is quite slow 

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/reports/execution/ReportsExecutionService.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ReportsRepository.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ReportsJdbcRepository.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala, webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
https://issues.rudder.io/issues/15062
=> Fixes #15062: store run agent batch may never catch up on very loaded system because of inefficient index and the way it handles reports

relay/sources/relayd/src/configuration.rs, relay/sources/relayd/src/remote_run.rs, relay/sources/relayd/tests/fake_agent.sh, relay/sources/relayd/tests/files/config/main.conf, relay/sources/relayd/tests/relay_api.rs, relay/sources/relayd/tests/test_simple/config/main.conf, relay/sources/relayd/tools/config/main.conf
https://issues.rudder.io/issues/15206
=> Fixes #15206: Handling keept_output and asynchronous parameters in the remote-run API

relay/sources/relayd/src/remote_run.rs, relay/sources/relayd/src/shared_files.rs
https://issues.rudder.io/issues/15247
=> Fixes #15247: Validating signatures in shared-files API

relay/sources/Makefile, relay/sources/relayd/src/error.rs, relay/sources/relayd/src/lib.rs
https://issues.rudder.io/issues/15274
=> Fixes #15274: Handle errors in log filter

relay/sources/Makefile
https://issues.rudder.io/issues/15295
=> Fixes #15295: Move /opt/rudder/etc/ssl/nodeslist.cert to /var/rudder/lib/ssl

relay/sources/Makefile
https://issues.rudder.io/issues/15298
=> Fixes #15298: Move /opt/rudder/etc/ssl/nodeslist.cert to /var/rudder/lib/ssl

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/workflows/ChangeRequestService.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestTechniqueWriter.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NcfApi.scala, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
https://issues.rudder.io/issues/15265
=> Fixes #15265: Migrate ncf delete api and improve workflow

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ExpectedReportsJdbcRepository.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ReportsJdbcRepository.scala
https://issues.rudder.io/issues/15372
=> Fixes #15372: Missing logs on NodeCompliance archive/deletion

relay/sources/rudder-server-relay-postinst
https://issues.rudder.io/issues/15384
=> Fixes #15384: Relayd service is not loaded

relay/sources/rudder-server-relay-postinst
https://issues.rudder.io/issues/15393
=> Fixes #15393: Cleanup relay postinstall 

webapp/sources/ldap-inventory/inventory-provisioning-web/src/main/resources/configuration.properties.sample, webapp/sources/ldap-inventory/inventory-provisioning-web/src/main/scala/com/normation/inventory/provisioning/endpoint/InventoryProcessor.scala, webapp/sources/ldap-inventory/inventory-provisioning-web/src/main/scala/com/normation/inventory/provisioning/endpoint/config/AppConfig.scala, webapp/sources/ldap-inventory/inventory-provisioning-web/src/main/webapp/WEB-INF/web.xml, webapp/sources/ldap-inventory/inventory-provisioning-web/src/test/scala/com/normation/inventory/provisioning/endpoint/TestCertificate.scala, webapp/sources/scala-ldap/src/main/scala/com/normation/ldap/listener/InMemoryDsConnectionProvider.scala
https://issues.rudder.io/issues/15012
=> Fixes #15012: When receving pleinty of inventories at the same time, the web interface starts to parse them all at once 

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/WriteNodeCertificatesPem.scala
https://issues.rudder.io/issues/15434
=> Fixes #15434: Cannot start relayd

relay/sources/rudder-server-relay-postinst
https://issues.rudder.io/issues/15444
=> Fixes #15444: postinstall of rudder-server-relay may fail if httpd is too slow to shut down

relay/sources/rudder-pkg/lib/rudder-pkg/rpkg.py, relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py, relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
https://issues.rudder.io/issues/15463
=> Fixes #15463: Remove tabulate python lib from rudder pkg

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SettingsApi.scala
https://issues.rudder.io/issues/15475
=> Fixes #15475: typo in api setting: rudder.report.protocol.default rather than rudder_report_protocol_default

relay/sources/relayd/src/api.rs, relay/sources/relayd/src/shared_files.rs
https://issues.rudder.io/issues/15456
=> Fixes #15456: Handle ttl parameter correctly in shared-files API

relay/sources/Makefile
https://issues.rudder.io/issues/15483
=> Fixes #15483: rudder-pkg python lib are missplaced on the server

relay/sources/relayd/Cargo.lock, relay/sources/relayd/Cargo.toml, relay/sources/relayd/src/api.rs, relay/sources/relayd/src/shared_files.rs
https://issues.rudder.io/issues/15469
=> Fixes #15469: Verifying signatures correctly in shared-files API

relay/sources/Makefile
https://issues.rudder.io/issues/15538
=> Fixes #15538: Missing export PYTHONPATH to build rudder-pkg autocompletion

relay/sources/Makefile
https://issues.rudder.io/issues/15555
=> Fixes #15555: Missing directories in relay install target

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/reports/ReportingConfiguration.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PropertiesManagement.scala, webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/policyServerManagement.html
https://issues.rudder.io/issues/15531
=> Fixes #15531: Add an Interface to select reporting protocol

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/TechniqueLibraryUpdateNotification.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/TechniqueRepositoryImpl.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/TechniqueAcceptationDatetimeUpdater.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/TechniqueReloadingCallbacks.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/TechniqueReloadingCallbacks.scala
https://issues.rudder.io/issues/2613
This pr allow to create, update, move categories (delete is not supported for non empty directories).
Hypothesis: all category directory name are unique in the tree.
=> Fixes #2613: Problem when updating a category name for Technique Management in /var/rudder

relay/sources/relayd/Cargo.lock, relay/sources/relayd/Cargo.toml
https://issues.rudder.io/issues/15597
=> Fixes #15597: Update relayd dependencies to fix RUSTSEC-2019-0013

webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/MachineInventory.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/TechniqueLibraryUpdateNotification.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/TechniqueRepository.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/TechniqueRepositoryImpl.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/RudderDit.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/DirectiveRepository.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDirectiveRepository.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/TechniqueAcceptationDatetimeUpdater.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/cfclerk/services/DummyTechniqueRepository.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/cfclerk/services/TechniqueRepositoryTest.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/EventListDisplayer.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/TechniqueLibraryManagement.scala
https://issues.rudder.io/issues/15590
=> Fixes #15590: Renaming/moving technique category fails in several way

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/DirectiveApi.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/RuleApi.scala
https://issues.rudder.io/issues/15608
=> Fixes #15608: When creating a rule via the API the id parameter is only read from url parameters, and not from json

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py, relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
https://issues.rudder.io/issues/15631
=> Fixes #15631: Rudder-pkg prints tables on a dict base source, which lead to unconsistent columns ordering

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
https://issues.rudder.io/issues/15646
=> Fixes #15646: Memory Leak in Rudder 5.0

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckNashornWarning.scala
https://issues.rudder.io/issues/15661
=> Fixes #15661: Manage nashorn warning parameter from code

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/PurgeDeletedInventories.scala
https://issues.rudder.io/issues/15710
=> Fixes #15710: Batch to purge deleted inventories starts 10 minutes after startup, rather than the defined interval after startup

webapp/sources/ldap-inventory/inventory-provisioning-web/src/main/scala/com/normation/inventory/provisioning/endpoint/FusionReportEndpoint.scala, webapp/sources/ldap-inventory/inventory-provisioning-web/src/main/scala/com/normation/inventory/provisioning/endpoint/InventoryFileWatcher.scala, webapp/sources/ldap-inventory/inventory-provisioning-web/src/main/scala/com/normation/inventory/provisioning/endpoint/InventoryProcessor.scala
https://issues.rudder.io/issues/15768
=> Fixes #15768: Make inventory processing less memory consuming

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PolicyWriterService.scala
https://issues.rudder.io/issues/15792
=> Fixes #15792: When writing policies, we replace the RudderUniqueId with replaceAll which is twice as slow as StringUtils.replace

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NcfApi.scala, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckNcfTechniqueUpdate.scala
https://issues.rudder.io/issues/15809
=> Fixes #15809: Cannot update editor techniques at webapp startup if the request to get techniques timeout (5 seconds)

relay/sources/relayd/Cargo.lock, relay/sources/relayd/src/remote_run.rs, relay/sources/relayd/tests/remote_run.rs
https://issues.rudder.io/issues/15836
=> Fixes #15836: Fix async & keep_output behavior

relay/sources/Makefile
https://issues.rudder.io/issues/15880
=> Fixes #15880: Cache relayd builds

relay/sources/Makefile
https://issues.rudder.io/issues/15902
=> Fixes #15902: Only cache dependencies

webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/services/provisioning/ReportSaver.scala, webapp/sources/ldap-inventory/inventory-provisioning-web/src/main/scala/com/normation/inventory/provisioning/endpoint/InventoryProcessor.scala, webapp/sources/ldap-inventory/inventory-repository/src/main/resources/ldap/inventory.schema, webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/InventoryMapper.scala, webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/LDAPConstants.scala, webapp/sources/ldap-inventory/inventory-repository/src/test/resources/ldap-data/schema/099-0-inventory.ldif
https://issues.rudder.io/issues/15903
=> Fixes #15903: Impossible to save virtuozzo inventory (missing LDAP object)

relay/sources/relayd/Cargo.toml
https://issues.rudder.io/issues/15909
=> Fixes #15909: Disable lto for relayd release builds

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/EventLogRepository.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/EventLogJdbcRepository.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/EventLogAPI.scala, webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
https://issues.rudder.io/issues/15948
=> Fixes #15948: Event log page must only load one day back of logs by default

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/ApplicationLogger.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/TimingDebugLogger.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DataStructures.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/InterpolatedValueCompiler.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/JavascriptEngine.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/RuleValService.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/RuleValServiceTest.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestBuildNodeConfiguration.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestJsEngine.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestNodeAndParameterLookup.scala, webapp/sources/rudder/rudder-web/src/test/scala/com/normation/rudder/javascript/CalculateComplianceTest.scala, webapp/sources/utils/src/main/scala/com/normation/ZioCommons.scala
https://issues.rudder.io/issues/15775
=> Fixes #15775: Performance problems with ZIO

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/JavascriptEngine.scala
https://issues.rudder.io/issues/15981
=> Fixes #15981: Generation fails with: RejectedExecutionException'. Perhaps the thread pool was stopped?

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/LdapQueryProcessor.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala
https://issues.rudder.io/issues/16010
=> Fixes #16010: Dynamic group based on another dynamic group don't work correctly in 6.0

relay/sources/relayd/src/api/remote_run.rs
https://issues.rudder.io/issues/16044
=> Fixes #16044: Remote-run starts commands with no host name

relay/sources/Makefile
https://issues.rudder.io/issues/16052
=> Fixes #16052: Missing /var/rudder/lib/relay dir in packaging

relay/sources/relayd/Cargo.lock, relay/sources/relayd/fuzz/Cargo.lock, relay/sources/relayd/src/relayd.rs
https://issues.rudder.io/issues/16063
=> Fixes #16063: Enable backtrace in relayd

relay/sources/relayd/Cargo.lock, relay/sources/relayd/fuzz/Cargo.lock, relay/sources/relayd/src/processing.rs
https://issues.rudder.io/issues/16065
=> Fixes #16065: HTTP errors when forwarding relays or inventories should generally be considered as transient

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
https://issues.rudder.io/issues/16077
=> Fixes #16077: Rudder-pkg fails to build since subprocess.DEVNULL is undefined before python 3.3

relay/sources/apache/rudder-apache-relay-common.conf, relay/sources/apache/rudder-apache-relay-nossl.conf, relay/sources/apache/rudder-apache-relay-ssl.conf
https://issues.rudder.io/issues/16122
=> Fixes #16122: Stop listenning for inventories on port 80

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/EventLogDetailsGenerator.scala, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala, webapp/sources/utils/src/main/scala/com/normation/ZioCommons.scala, webapp/sources/utils/src/test/scala/com/normation/ZioCommonsTest.scala
https://issues.rudder.io/issues/16133
=> Fixes #16133: Missing diffDisplayer service in 6.0

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/ApiAuthorization.scala
https://issues.rudder.io/issues/12440
=> Fixes #12440: When the api authorization plugin is disabled tokens become read only

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/AgentSpecificLogic.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PrepareTemplateVariables.scala
https://issues.rudder.io/issues/15798
=> Fixes #15798: Rationalize the handling of variable during a policy generation

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ExpectedReportsRepository.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ExpectedReportsJdbcRepository.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ReportsJdbcRepository.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportsTest.scala, webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
https://issues.rudder.io/issues/16083
=> Fixes #16083: Big memory usage when fetching/writing ndoe configuration and expected reports

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingService.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/HomePage.scala
https://issues.rudder.io/issues/16201
=> Fixes #16201: Inefficient computing of compliance on home page

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/MergePolicyService.scala
https://issues.rudder.io/issues/16232
=> Fixes #16232: Directive based on a multivalued technique are not marked overriden

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryProcessor.scala
https://issues.rudder.io/issues/16260
=> Fixes #16260: Unsigned inventories must not be accepted anymore in 6.0

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/appconfig/ConfigService.scala
https://issues.rudder.io/issues/16294
=> Fixes #16294: Set HTTP reporting protocol by default on new rudder 6.0 installation

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/ApplicationLogger.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
https://issues.rudder.io/issues/16222
So, it works, but with some caveats: 
- it's synchrone
- there is something very strange happening during execution. It seems that the request result is processed two times (the part in `request.exec`), but the second time, there is a problem with (likely) piped input stream, and so all write to pipe output stream wait forever. I added a timeout, which allows to break the lock and display the result (which is correct!).
=> Fixes #16222: Exception "fiberFailed" when running agent from UI

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/Technique.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestTechniqueWriter.scala
https://issues.rudder.io/issues/16357
=> Fixes #16357: Broken test on whitespace matching and regex is invalid for multiline

webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/write/WriteTechniquesTest.scala, webapp/sources/rudder/rudder-templates/src/main/scala/com/normation/templates/FillTemplatesService.scala
https://issues.rudder.io/issues/16374
=> Fixes #16374: Race condition in technique variable filling

rudder-lang/README.adoc, rudder-lang/src/cfg.ini, rudder-lang/src/generate-lib, rudder-lang/src/ncf, rudder-lang/src/tester.sh
Should work on Rudder servers as I only installed a server/agent on a clean debian distro. The script works on it.
Did not moove paths to external config files as I am unsure it would have been cleaner
=> Fixes #16334: More generic lib linding of the rudder-lang tester script

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/ComplianceLevel.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/reports/StatusReportTest.scala
https://issues.rudder.io/issues/16468
=> Fixes #16468: Computation of ComplianceLevel generates too many objects

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/appconfig/ConfigService.scala
https://issues.rudder.io/issues/16465
=> Fixes #16465: get/set of rudder reporting protocol uses . rather than _

relay/sources/relayd/Cargo.lock, relay/sources/relayd/Cargo.toml, relay/sources/relayd/fuzz/Cargo.lock, relay/sources/relayd/src/api/shared_files.rs, relay/sources/relayd/src/configuration/cli.rs, relay/sources/relayd/src/configuration/main.rs, relay/sources/relayd/src/error.rs, relay/sources/relayd/src/input/watch.rs, relay/sources/relayd/src/processing/inventory.rs, relay/sources/relayd/src/processing/reporting.rs, relay/sources/relayd/tests/files/config/main.conf, relay/sources/relayd/tests/processing_reporting.rs, relay/sources/relayd/tests/processing_reporting_old.rs, relay/sources/relayd/tools/config/main.conf
https://issues.rudder.io/issues/16479
=> Fixes #16479: Add a cleanup job for old reports and inventories in relayd

webapp/sources/ldap-inventory/inventory-fusion/src/test/scala/com/normation/inventory/provisioning/fusion/TestSignatureService.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryFileWatcher.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryProcessor.scala
https://issues.rudder.io/issues/16492
=> Fixes #16492: We use not the correct InputStream at several place

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/GitTechniqueReader.scala
https://issues.rudder.io/issues/16493
=> Fixes #16493: Missing store git commit lead to fatal exception

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/AsyncComplianceService.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala, webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-node.css
https://issues.rudder.io/issues/16326
=> Fixes #16326: Display compliance bar in Node details

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/hooks/RunHooks.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/hooks/RunNuCommand.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/hooks/HooksTest.scala, webapp/sources/utils/src/main/scala/com/normation/ZioCommons.scala
https://issues.rudder.io/issues/16506
=> Fixes #16506: Improve Hook exec  performance

rudder-lang/src/data/corelib.rl, rudder-lang/src/data/test.rl.cf, rudder-lang/src/error.rs, rudder-lang/src/parser.rs, rudder-lang/src/parser/error.rs, rudder-lang/src/parser/tests.rs
Integration of a non-blocking error parser
Integration of another way to implement and catch error contexts allowing to catch more accurate informations about errors
https://issues.rudder.io/issues/16483
=> Fixes #16483: nonblocking errors parser, more precise context capture

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/nodeconfig/NodeConfigurationLogger.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PolicyWriterService.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PrepareTemplateVariables.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/write/WriteTechniquesTest.scala
https://issues.rudder.io/issues/16513
=> Fixes #16513: JVM GC cannot clean objects in scope in a for { } yield {} even if they are not referenced anymore

webapp/sources/utils/src/main/scala/com/normation/ZioCommons.scala, webapp/sources/utils/src/main/scala/zio/internal/RudderBlockingService.scala
https://issues.rudder.io/issues/16505
=> Fixes #16505: Change ZIO runtime ergonomics

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py, relay/sources/rudder-pkg/rudder-pkg
https://issues.rudder.io/issues/16569
=> Fixes #16569: Add an "upgrade-all" command to rudder-pkg

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/AgentPolicyModeEditForm.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/AgentScheduleEditForm.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/ComplianceModeEditForm.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/PendingChangeRequestDisplayer.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleCompliance.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleDisplayer.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleEditForm.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleGrid.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/SearchNodeComponent.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/ShowNodeDetailsFromNode.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/TagsEditForm.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/TechniqueEditForm.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateActiveTechniqueCategoryPopup.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateCategoryOrGroupPopup.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateCloneGroupPopup.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateOrUpdateGlobalParameterPopup.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateRulePopup.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/ExpectedPolicyPopup.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/GiveReasonPopup.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/ModificationValidationPopup.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/RuleCategoryPopup.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/RuleModificationValidationPopup.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/BaseUrl.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/HomePage.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/DatabaseManagement.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/AcceptNode.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/Nodes.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/PendingHistoryGrid.scala
https://issues.rudder.io/issues/16578
=> Fixes #16578: Node details show properties in each pages

rudder-lang/src/parser/tests.rs, rudder-lang/stdlib.rl.cf, rudder-lang/tests/compile.rs, rudder-lang/tests/compile_utils.rs
Fixed failing tests, and cleaned integration tests so compile.rs stays clean of code logic. Added tests comments to highlight that some tests could be meant to fail : uncomment to ensure tests are still working the way they are intended to.
https://issues.rudder.io/issues/16575
=> Fixes#16484: rl fix failed tests

rudder-lang/.gitignore, rudder-lang/Cargo.lock, rudder-lang/Cargo.toml, rudder-lang/src/bin/main.rs, rudder-lang/src/compile.rs, rudder-lang/src/generators/cfengine.rs, rudder-lang/src/lib.rs, rudder-lang/src/logger.rs, rudder-lang/src/translate.rs, rudder-lang/tests/compile.rs, rudder-lang/tests/compile_utils.rs, rudder-lang/tests/tester.sh, rudder-lang/tests/virtual_files.toml
Adds a logger to rudder-lang. Several levels of verbosity.
Adds an optional json output format with associated refactorisation changes to the log system.
Also sets a different panic! output message
Following code is cced (eventually truncated) output.
Checked: json output works fine with `| jq .`
panic:
```
{
"time": "1579624983507",
"logs": [
{
"status": "debug",
"message": "TMP DEBUG SHOWCASE",
"timestamp": "2020-01-21T15:04:43Z"
},
{
"Compilation result": {
"status": "unrecoverable error",
"message": "The following unrecoverable error occured in file 'src/compile.rs' at line 56: 'PANIC SHOWCASE'"
}
}
]
}
```
json:
```
{
"time": "1579624983569",
"logs": [
{
"status": "debug",
"message": "DEBUG SHOWCASE"
},
...
{
"status": "info",
"message": "Processing compilation of …
```
=> Fixes #16583: rl logger: several verbose levels + opt json output

webapp/sources/pom.xml, webapp/sources/rudder/rudder-core/pom.xml, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/domain/HashAlgoConstraint.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/TechniqueReader.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/TechniqueRepository.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/GitTechniqueReader.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/TechniqueRepositoryImpl.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/PolicyGenerationLogger.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/hooks/RunNuCommand.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DataStructures.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/JavascriptEngine.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/MergePolicyService.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/BuildBundleSequence.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PathComputer.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PolicyWriterService.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PrepareTemplateVariables.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PromiseWriteDataStructures.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/RemoveNodeService.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/cfclerk/services/DummyTechniqueRepository.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/cfclerk/services/JGitPackageReaderTest.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestTechniqueWriter.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestBuildNodeConfiguration.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestNodeAndParameterLookup.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/write/PathComputerTest.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/write/WriteTechniquesTest.scala, webapp/sources/rudder/rudder-templates-cli/src/main/scala/com/normation/templates/cli/TemplateCli.scala, webapp/sources/rudder/rudder-templates-cli/src/test/scala/com/normation/templates/cli/JsonVariablesTest.scala, webapp/sources/rudder/rudder-templates/pom.xml, webapp/sources/rudder/rudder-templates/src/main/scala/com/normation/templates/FillTemplatesService.scala
https://issues.rudder.io/issues/16382
This PR try to make the abysmal performances of policy generation in 6.0 less abysmal. 
Most of that PR was split in smaller amount, but there is a big part remaining: I change (most) of the the write logic, and that part can't really be done in smaller bit. 
The big changes are:
- port a bit more GitTemplateReader & friends to ZIO to avoid switching from in/out ZIO;
- change the way policies are done so that now, it' not by node but by template, which avoid to lock on them 
- add A LOT of timing information, which are now pretty cool
- use atomic move when possible, but it doesn't yield a lot of perf, 
- parallelise move of policies to their final place, 
- use ArraySeq for string template values, which avoid to switch between list and array which …
=> Fixes #16382: Improve performance of policy generation writer

webapp/sources/rudder-parent-pom/pom.xml
https://issues.rudder.io/issues/16651
=> Fixes #16651: Change in maven repository URL from http://repo1.maven.org/maven2/ to https://repo1.maven.org/maven2/

webapp/sources/pom.xml, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogDetailsService.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlUnserialisationImpl.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala
https://issues.rudder.io/issues/16673
=> Fixes #16673: Avoid Seq[Node] in place of NodeSeq with updated version of scala-xml

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SettingsApi.scala
https://issues.rudder.io/issues/16692
- change "authorized networks" to "allowed networks" so that it matches UI/documentation, 
- if a policy server is missing allowed network policy, we want to return an empty list of networks in place of failing,
- if the user didn't specify "allowed_networks" param, don't erase all allowed networks but fail.
=> Fixes #16692: Authorized networks are actually called allowed networks

webapp/sources/rudder/rudder-web/src/main/resources/demo-rudder-users.xml
https://issues.rudder.io/issues/16730
=> Fixes #16730: Update users configuration file to add BCrypt support

webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/write/WriteTechniquesTest.scala
https://issues.rudder.io/issues/16759
=> Fixes #16759: Compilation warning for unused variable in WriteTechniquesTest.scala

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
https://issues.rudder.io/issues/16448
=> Fixes #16448: Trigger remote run in node details says it timeeout

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryProcessor.scala
https://issues.rudder.io/issues/16783
=> Fixes #16783: If an inventory has no signature, the error message in log is thousands of line long

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/db/Doobie.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/StatusReports.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ComplianceRepository.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingService.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/reports/StatusReportTest.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ExecutionBatchTest.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ReportingServiceTest.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ComplianceApi.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/AsyncComplianceService.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/HomePage.scala
https://issues.rudder.io/issues/16661
=> Fixes #16661: inneficient computation of RuleStatusReports and NodeStatusReports

rudder-lang/src/ast.rs, rudder-lang/src/ast/enums.rs, rudder-lang/src/bin/rudderc.rs, rudder-lang/src/file_paths.rs, rudder-lang/src/generators/cfengine.rs, rudder-lang/src/logger.rs, rudder-lang/src/parser.rs, rudder-lang/src/translate.rs
https://issues.rudder.io/issues/16943
=> Fixes #16943: Fix clippy warnings in rudder-lang

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala, webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/nodeProperties.js, webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentNodeProperties.html
https://issues.rudder.io/issues/16854
=> Fixes #16854: Users with readonly rights should be able to view the node properties and their value

webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/reports/StatusReportTest.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/hooks/HooksTest.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestTechniqueWriter.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala
https://issues.rudder.io/issues/17079
=> Fixes #17079: Test files are not correctly clean

rudder-lang/libs/oslib.rl, rudder-lang/src/translate.rs
https://issues.rudder.io/issues/17075
=> Fixes #17075: translation into rudder-lang doesn't handle any class

webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-groups.css, webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css, webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder.css
https://issues.rudder.io/issues/16430
=> Fixes #16430: Some alignement issues

relay/arch-doc/rudder-6-reporting-relayd.md
https://issues.rudder.io/issues/16623
=> Fixes #16623: Publish arch-doc for http reporting/relayd in the repo

webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/ReadOnlySoftwareInventoryDAOImpl.scala
https://issues.rudder.io/issues/16636
=> Fixes #16636: Purge of unreferenced software may fail on very large system

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderUserDetails.scala
https://issues.rudder.io/issues/17108
=> Fixes #17108: cannot login in Rudder 6.1

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
https://issues.rudder.io/issues/17141
=> Fixes #17141: when we add a multiline description in Technique, it breaks policy generation and technique loading

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/Node.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/parameters/GlobalParameter.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/parameters/ParameterDiff.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDiffMapper.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogDetailsService.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogFactory.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlSerialisationImpl.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlUnserialisationImpl.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/modification/DiffService.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DataStructures.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/InterpolatedValueCompiler.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/ParameterService.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/workflows/CommitAndDeployChangeRequestService.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestNodeAndGlobalParameterLookup.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestDataSerializer.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/RestData.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ParametersApi.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/EventLogDetailsGenerator.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateOrUpdateGlobalParameterPopup.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/ParameterManagement.scala
https://issues.rudder.io/issues/16301
This commit is based on `groups properties` one, PR https://github.com/Normation/rudder/pull/2890 need to be review/merged first. Also, you should only look at last commit for that PR until that time. 
This PR main changes are: 
- GlobalParameter value is now a `JValue` to be homogeneous with `GroupProperties` and `NodeProperties`
- also, removed `overridable` since that field wasn't ever used, and overriding logic don't match it. 
Then, the other big change is about inheritance logic. To be able to use `parameters` value when we build `NodeProperties` in `getNodeContexts > buildParams`, we need to evaluate `Param` interpollation there. It's ok, because we have all needed info for that at that point, and we could have done it all along here, but it …
=> Fixes #16301: Add JSON support for global parameters

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala
https://issues.rudder.io/issues/17172
=> Fixes #17172: Concurrent access to node info cache cause exception to be thrown when accessing cache content

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/UpdateDynamicGroups.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/DynGroupService.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestPendingNodePolicies.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SystemApi.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/v1/RestDyngroupReload.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/DyngroupReloading.scala
https://issues.rudder.io/issues/17237
=> Fixes #17237: Do not compute dynamic groups if nothing changed in LDAP

webapp/sources/pom.xml, webapp/sources/rudder/rudder-core/pom.xml, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/domain/Constraint.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/domain/RegexConstraint.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/InterpolatedValueCompiler.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchQueryParser.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchService.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestNodeAndGlobalParameterLookup.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/quicksearch/QSRegexQueryParserTest.scala, webapp/sources/rudder/rudder-web/pom.xml, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PropertiesManagement.scala
https://issues.rudder.io/issues/7006
"oups". 
It was *really* too complicated to add non-rudder variable to our compiler with scala lib parser combintor. Since we now have `fastparse` in the path, I tried to see if it was easier... And it was thanks to its amazing log possibilities (the parsing by itself is a bit tricky). 
The most interesting is how little code changes from scala regex combinator to fastparse. And the perf are just in other league (it does not change much in our case, since node prop interpolation is in second range, but now we are in the 10s of millisec - it may still be interesting with group properties and many more parsing to do). 
So I also switch the last parser we had (the one for our "search anything" bar queries), what allows to get ride of one dependancy and …
=> Fixes #7006: Parameter validation in Rudder should accept rudder variables ( ${ } )

relay/sources/Makefile, relay/sources/relayd/Cargo.toml, relay/sources/relayd/Makefile, relay/sources/relayd/deny.toml
https://issues.rudder.io/issues/17308
=> Fixes #17308: Use cargo-deny to replace cargo-audit

relay/sources/relayd/src/data/node.rs, relay/sources/relayd/src/hashing.rs, relay/sources/relayd/tests/files/nodeslist.json
https://issues.rudder.io/issues/17458
=> Fixes #17458: Ignore invalid hash in nodeslist

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryFileWatcher.scala, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
https://issues.rudder.io/issues/17482
=> Fixes #17482: Webapp block at start on inventory processing

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/SystemVariableSpecServiceImpl.scala
https://issues.rudder.io/issues/17313
=> Fixes #17313: Upgrading Rudder from 5.0.18 to 6.1-nightly does not update techniques

webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
https://issues.rudder.io/issues/17521
=> Fixes #17521: A repaired in system policies should not be seen as a problem for warning display in nodes list

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryFileWatcher.scala
https://issues.rudder.io/issues/17507
=> Fixes #17507: inventory watcher should ignore uuid.hive file

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/ncf/TechniqueReader.scala
https://issues.rudder.io/issues/17568
=> Fixes #17568: Allow to regenerate generic methods when there is a new one

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/Properties.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/MergeNodeProperties.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/nodes/TestMergeGroupProperties.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/GroupsApi.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
https://issues.rudder.io/issues/17549
There was some renaming/moving things around which make the PR seems harder than it is really. 
The renaming/moving allow to create a method similar to the one that merge properties for node but for group, and the only really interesting piece is in that method: before that, we were not getting parents of group, and so when the merge occured, they weren't found (suprisingly). So the new method `getParents` before doing the merge. 
Renaming are: 
- remove useless parameter for `ParentProperty`, since we only have `ConfigValue` and all these parameters were starting to be confusing (and remove corresponding useless trait level)
- extract logic that change a group to a `GroupProp` so that it can be used (also) in new method
- rename `withDefaults` to …
=> Fixes #17549: Property error message for group with parent group

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RoleApiMapping.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
https://issues.rudder.io/issues/17596
=> Fixes #17596: User with some to access technique editor api

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/CheckInventoryUpdate.scala
https://issues.rudder.io/issues/17595
=> Fixes #17595: when a policy generation is triggered by a dynamic group update, it states in event logs "Manually update policies"

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/Properties.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/MergeNodeProperties.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/nodes/TestMergeGroupProperties.scala, webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/nodeProperties.js, webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/node.html, webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentNodeProperties.html
https://issues.rudder.io/issues/17625
This PR change a bit the logic for merge properties: 
- in a property hierarchy, we had in head of parents property the original value of the object property in the `overriden` case (when it's purely inherited, nothing change - this is done in method `MergeNodeProperties#mergeDefault`), 
- change name from `parents` to hierarchy since it doesn't hold only parents anymore, 
- for the api case, add the original value in a `origval` attribute, 
- when editing an existing property, if the provider is `overridden`, use `origval`
- for each action among `add`, `delete`, `edit`, reload all properties on save success because inheritance/overriding need to be computed again, and front end doesn't have all information to do it.
When viewing:
When editing:
=> Fixes #17625: Group value should only display value for that element in main table

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/Properties.scala
https://issues.rudder.io/issues/17682
=> Fixes #17682: Make clear in parent that parsing code is common

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/ncf/TechniqueReader.scala
https://issues.rudder.io/issues/17683
=> Fixes #17683: Error in technique editor "could not get generic method metadata" after upgrade from 6.0

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDirectiveRepository.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/TechniqueAcceptationDatetimeUpdater.scala
https://issues.rudder.io/issues/17774
=> Fixes #17774: Duplicate category name error when saving a new user technique

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/Properties.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ParameterRepository.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPParameterRepository.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/ParameterService.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/workflows/CommitAndDeployChangeRequestService.scala
https://issues.rudder.io/issues/17702
Main changes:
- if parsing of serialized global value fails, get value as string. It should be an extremely rare case (likely due to direct modification of LDAP), 
- make delete not fails if the param is not found and use provider, so that we can't delete a parameter with a different provider than our
=> Fixes #17702: When there is a serialisation error for parameter, their edit screen is unavaible

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDirectiveRepository.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeGroupRepository.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/GroupsApi.scala
https://issues.rudder.io/issues/17815
The bug correction is only the change in `None` position, but while debugging I foudn some missing `id.value` for logs/errors
=> Fixes #17815: Group API compatibility broken as it now always expects "properties"

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/SystemVariableSpecServiceImpl.scala
https://issues.rudder.io/issues/17836
=> Fixes #17836: Upgrading from rudder 5.0 to 6.0 leads to `distributePolicy not available` error

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/EventLogJdbcRepository.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlUnserialisationImpl.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/workflows/CommitAndDeployChangeRequestService.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestDataSerializer.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala, webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/nodeProperties.js
https://issues.rudder.io/issues/17804
=> Fixes #17804: Trying to add a group property with change request plugin enabled lead to blank property

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlUnserialisationImpl.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/AsyncComplianceService.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
https://issues.rudder.io/issues/17660
=> Fixes #17660: Node details summary compliance contains system rules

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NcfApi.scala
https://issues.rudder.io/issues/17872
=> Fixes #17872: unsaved change technique popup when not necessary

relay/sources/rudder-server-relay-postinst
https://issues.rudder.io/issues/17884
=> Fixes #17884: Error when installing relayd on root: missing file /var/rudder/configuration-repository/shared-files/*

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestTechniqueWriter.scala, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
https://issues.rudder.io/issues/18015
=> Fixes #18015: Remove technique from technique tree when deleting technique in the technique editor

rudder-lang/.gitignore, rudder-lang/tools/cfjson_tester, rudder-lang/tools/tester.sh
https://issues.rudder.io/issues/17950
=> Fixes #17950: testing loop should report an error when rudderc does

webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/reports/StatusReportTest.scala
https://issues.rudder.io/issues/18050
=> Fixes #18050: Test fails because takes too long

rudder-lang/src/ast.rs, rudder-lang/src/ast/resource.rs, rudder-lang/src/generators/cfengine.rs, rudder-lang/src/generators/dsc.rs, rudder-lang/src/parser.rs, rudder-lang/tests/compile.rs, rudder-lang/tests/compile_techniques/s_state_case.rl, rudder-lang/tests/tmp/s_state_case/technique.rl
https://issues.rudder.io/issues/18069
=> Fixes #18069: Parse log_* keywords

rudder-lang/docs/DESIGN_DECISIONS, rudder-lang/src/ast.rs, rudder-lang/src/ast/context.rs, rudder-lang/src/ast/resource.rs, rudder-lang/src/parser.rs, rudder-lang/src/parser/tests.rs
https://issues.rudder.io/issues/18108
=> Fixes #18108: Parsing of variable declaration and definition should be split

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/RestData.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/GroupsApi.scala
https://issues.rudder.io/issues/10216
=> Fixes #10216: "id" setting is silently ignored for new group created through the REST API.

webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/FusionReportUnmarshaller.scala, webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/InventoryMapper.scala, webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/ReadOnlySoftwareInventoryDAOImpl.scala, webapp/sources/pom.xml, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/AutomaticReportsCleaner.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/metrics/Scheduler.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/NodeGroupRepository.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeGroupRepository.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeRepository.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitArchiverImpl.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitParseRudderObjects.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/ItemArchiveManagerImpl.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DependencyAndDeletionService.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PrepareTemplateVariables.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/LdapQueryProcessor.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/metrics/NodeCountHistorizationTest.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/metrics/SchedulerTest.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestJsEngine.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NcfApi.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/plugins/RudderPluginJson.scala, webapp/sources/utils/src/main/scala/com/normation/ZioCommons.scala, webapp/sources/utils/src/test/scala/com/normation/ZioCommonsTest.scala
https://issues.rudder.io/issues/18149
Update went smoothly, three noticable changes: 
- update cats dependencies because of `zio-compatc-cats`. I think I found back a consistent set of lib for `fs2` etc, 
- change in `TestClock.sleep`. Now it actually sleep the fiber, so it needs a `fork`. Also, `TestClock.adjust` doesn't need a sleep to notify the adjust anymore (good!);
- the biggest change is a change in `foreach` signature, which used to take only a `items: Iterable[A]` parameter and was *always* returning a `List[A]` and that now takes 5 differents parameters (`Option[A]`, `Map[A, B]`, `Set[A]`, `NonEmptyChunk[A]`, and `Collection[+Element] <: Iterable[Element]` and return the same type). That need some `.toList` or spelling to scalac that no, really, I want an iteration on map …
=> Fixes #18149: Upgrade to ZIO 1.0.1

rudder-lang/docs/examples/statements.rl
https://issues.rudder.io/issues/18169
=> Fixes #18169: rudder-lang fails to test its documentation examples

rudder-lang/src/bin/rudderc.rs, rudder-lang/src/compile.rs, rudder-lang/src/generator.rs, rudder-lang/src/io.rs, rudder-lang/src/lib.rs, rudder-lang/src/opt.rs, rudder-lang/src/technique.rs, rudder-lang/tests/utils/mod.rs
https://issues.rudder.io/issues/18168
=> Fixes #18168: command line rework

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/db/Doobie.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/RudderDatasourceProvider.scala
https://issues.rudder.io/issues/18224
Important part is replacing `connectEC` (`val ce = ...`) by `zio-default-blocking` executor/threadpool. 
Plus: create only one transactor by app, as adviced. 
More information about transactor in threadpools in doobie: https://tpolecat.github.io/doobie/docs/14-Managing-Connections.html
=> Fixes #18224: Possible deadlock when connection pool is full

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NcfApi.scala, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
https://issues.rudder.io/issues/18277
=> Fixes #18277: Bad condition on name checking for technique existence

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/HealthcheckLogger.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/healthcheck/HealthcheckService.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestDataSerializer.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RoleApiMapping.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/HealthcheckApi.scala, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
https://issues.rudder.io/issues/18306
=> Fixes #18306: Create healthcheck API 

relay/sources/apache/rudder-vhost.conf
https://issues.rudder.io/issues/18338
Replacing previous PR: https://github.com/Normation/rudder/pull/3263
=> Fixes #18338: Rudder SSL default configuration should follow the system default one

webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/server/server_details.html
https://issues.rudder.io/issues/18346
=> Fixes #18346: Make the group option to include the Rudder server or not in the group more clear

webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/NodeGroupForm.html
https://issues.rudder.io/issues/17634
Replacing previous PR: https://github.com/Normation/rudder/pull/3284
=> Fixes #17634: Group description button should not be clickable in read_only

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py, relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py, relay/sources/rudder-pkg/rudder-pkg
https://issues.rudder.io/issues/18311
=> Fixes #18311: Changes to rudder package command to improve plugin management

webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/Software.scala, webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/FusionReportUnmarshaller.scala, webapp/sources/ldap-inventory/inventory-provisioning-core/src/main/scala/com/normation/inventory/ldap/provisioning/SoftwareIdFinder.scala, webapp/sources/ldap-inventory/inventory-repository/src/main/resources/ldap/inventory.schema, webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/InventoryMapper.scala, webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/LDAPConstants.scala
https://issues.rudder.io/issues/18317
=> Fixes #18317: Support source package in Rudder inventory

webapp/sources/pom.xml, webapp/sources/rudder/rudder-web/pom.xml, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
https://issues.rudder.io/issues/18406
=> Fixes #18406: Missing base class of plugins breaks `reflections` with caffeine version 2.8.2

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/healthcheck/HealthcheckService.scala, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
https://issues.rudder.io/issues/18357
=> Fixes #18357: Add check for free space

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/healthcheck/HealthcheckService.scala, webapp/sources/rudder/rudder-web/src/main/elm/healthcheck/sources/View.elm
https://issues.rudder.io/issues/18417
=> Fixes #18417: Improve freeSpace check messages

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingService.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/SrvGrid.scala, webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
https://issues.rudder.io/issues/18462
=> Fixes #18462: Compliance does not show up if you don't click on refresh

webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
https://issues.rudder.io/issues/18495
=> Fixes #18495: Add a reset columns button and some guard on localstorage cache

webapp/sources/rudder/rudder-core/src/main/resources/ldap/rudder.schema, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/RudderLDAPConstants.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/Properties.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/parameters/GlobalParameter.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/parameters/ParameterDiff.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDiffMapper.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogDetailsService.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlSerialisationImpl.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlUnserialisationImpl.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/MergeNodeProperties.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/nodes/GenericPropertiesTest.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/nodes/NodePropertiesTest.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/ldap/GlobalParamMigration61Test.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/eventlog/NodeEventLogFormatV6Test.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/nodes/TestMergeGroupProperties.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestNodeAndGlobalParameterLookup.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/RestData.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/GroupsApi.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ParametersApi.scala, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckRudderGlobalParameter.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateOrUpdateGlobalParameterPopup.scala
https://issues.rudder.io/issues/18466
Replacing previous PR: https://github.com/Normation/rudder/pull/3319
Add a "inheritMode" optionnal attribute in all properties (global param, group, node). Only global param has an UI (because it's likely where people want to change that, and because I have 0 idea about how to do one for group/node properties). 
inheritMode is a 3 char strings:
- 1: behavior for json object; m = merge (default), o = override
- 2: behavior for array: o = override (defaut), a = append, p = prepend
- 3: behavior for strings: o = override (defaut), a = append, p = prepend
=> Fixes #18466: Inherited node prop arrays are replaced not merged contrary to doc

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala
https://issues.rudder.io/issues/18510
=> Fixes #18510: Loading directive's page is very slow

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/healthcheck/HealthcheckService.scala
https://issues.rudder.io/issues/18534
=> Fixes #18534: Skip non-standard moint FS for free-space check

relay/sources/relayd/Cargo.lock
https://issues.rudder.io/issues/18437
=> Fixes #18437: Too many open files in relayd when disk is full

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/healthcheck/HealthcheckNotificationService.scala, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
https://issues.rudder.io/issues/18540
=> Fixes #18540: Healthcheck checks happen to often 

rudder-lang/src/technique.rs
https://issues.rudder.io/issues/18486
=> Fixes #18486: interpolated variable in conditions should not treat dots as AND operators 

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestDataSerializer.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/NodeDetailLevel.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/EventLogAPI.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/EventLogDetailsGenerator.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/comet/AsyncDeployment.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ComplianceData.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/LogDisplayer.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/SrvGrid.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/Archives.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/DatabaseManagement.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/AcceptNode.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/PendingHistoryGrid.scala, webapp/sources/utils/src/main/scala/com/normation/utils/DateFormaterService.scala
https://issues.rudder.io/issues/15915
=> Fixes #15915: Move date formatter service to a more common project 

webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
https://issues.rudder.io/issues/18538
=> Fixes #18538: Column name to add are not sorted alphabetically

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryFileWatcher.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryProcessor.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/inventory/TestCertificate.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/InventoryApi.scala, webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
https://issues.rudder.io/issues/16773
Add a `saveInventoryBuffer` that stays between inotify watcher (in charge of the complexe logic of making sense of inotify events and waiting for signature) and the part that [parse inventory, check signature, forward to backend] and is heavy on CPU and RAM. 
That buffer can be big (chose 1024 without much rationnal safe that it's big and a power of 2, as asked in ZQueue comment).
The main benefits are: 
- info about the file to process are cheap (a string with name, 3 functions to open stream or test if the file exists)
- we can deduplicate files while they are in the buffer super easily (and so avoid starvation case where some node goes made and send a lot of inventory). 
Only the code path for inventories coming from file system has the buffer, …
=> Fixes #16773: Batch of new nodes can overflow rudder server with inventories

webapp/sources/api-doc/paths/nodes/id.yml, webapp/sources/pom.xml, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/ApplicationLogger.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ExpectedReportsRepository.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/NodeGroupRepository.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ExpectedReportsJdbcRepository.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeGroupRepository.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/Lock.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/PolicyServerManagementService.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/RemoveNodeService.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/servers/TestRemoveNodeService.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SettingsApi.scala, webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
https://issues.rudder.io/issues/18035
So, there is two goal in that PR:
- be able to control if a node is moved to "removed inventories" or totally erased thanks to a parameter of node deletion api (`DELETE .../nodes/uuid?mode=erase`)
- clean-up everything regarding a node when it is deleted.
That PR also add the possibility to change the default behavior of rudder regarding node deletion with the configuration parameter `rudder.nodes.delete.defaultMode` in `rudder-web.properties` config file. That parameter is not mandatory, and the default value remains the same. 
From a code perspective, the main changes are: 
- add a NodeApiService12 that know how to deal with the "mode" parameter
- add some bridge methods in existing services (`UpdateExpectedReportsRepository`, `NodeInfoService`, …
=> Fixes #18035: API to totally erase a node everywhere

relay/sources/rudder-server-relay-postinst
https://issues.rudder.io/issues/18639
=> Fixes #18639: Rudder server relay install should use the up-to-date commands and not deprecated ones

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RoleApiMapping.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
https://issues.rudder.io/issues/18626
=> Fixes #18626: Popup error on group page with a readonly user in 6.2

webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-inventory-received-pending/auto-accept-nodes.example, webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-inventory-received-pending/hook-template, webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-inventory-received-pending/readme.adoc
https://issues.rudder.io/issues/18634
=> Fixes #18634: Add a script example for auto-acceptation of nodes by hook

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py
https://issues.rudder.io/issues/18645
=> Fixes #18645: Upgrading 6.2 nightly to 6.2 nightly with plugins fails

webapp/sources/rudder/rudder-web/src/main/webapp/secure/index.html, webapp/sources/rudder/rudder-web/src/main/webapp/style/login.css, webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-datatable.css, webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-groups.css, webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css, webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
https://issues.rudder.io/issues/18610
=> Fixes #18610: Many alignement issues on 6.2

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py
https://issues.rudder.io/issues/18694
=> Fixes #18694: Rudder-pkg fails at upgrade when no newer version of a plugin are available

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py, relay/sources/rudder-pkg/rudder-pkg
https://issues.rudder.io/issues/18740
=> Fixes #18740: rudder package now detect new version, but still install old package during upgrade on CentOS

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/RuleApi.scala
https://issues.rudder.io/issues/18777
=> Fixes #18777: Clone rule API fails with "rule already exists with that id"

relay/sources/relayd/Cargo.lock
https://issues.rudder.io/issues/18824
=> Fixes #18824: Security advisories for relayd dependencies

webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/services/core/SoftwareDAO.scala, webapp/sources/ldap-inventory/inventory-provisioning-core/src/main/scala/com/normation/inventory/ldap/provisioning/DefaultReportSaver.scala, webapp/sources/ldap-inventory/inventory-provisioning-core/src/main/scala/com/normation/inventory/ldap/provisioning/SoftwareIdFinder.scala, webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/ReadOnlySoftwareInventoryDAOImpl.scala, webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/SoftwareService.scala, webapp/sources/ldap-inventory/inventory-repository/src/test/scala/com/normation/inventory/ldap/core/TestInventory.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/PurgeUnreferencedSoftwares.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryFileWatcher.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SystemApi.scala, webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
https://issues.rudder.io/issues/12937
This PR correct the core problem in merge_uuid in rudder 6.2: we weren't requesting `sourceName` and `sourceVersion` attribute in the search request for software, but we were using them for comparison. So as soon as we had an inventory with non null value for these attribute, the merge alway failed: they were non empty in inventory, but all existing soft had them empty (from the point of view of the request). So new soft created each time, and so explosion of their number, of indexes, etc. 
That PR also addresses the following points: 
- add logs when unreference software are purged (+ batch deletion by 1000 software, so that user can see that something happens), 
- add an API endpoint to trigger software delete (`POST on …
=> Fixes #12937: When receiving an inventory, the merge_uuid part can be painfully slow

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py, relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
https://issues.rudder.io/issues/18841
=> Fixes #18841: rudder package upgrade-all does not upgrade each plugin independently

webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/directiveManagement.html, webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
https://issues.rudder.io/issues/18871
=> Fixes #18871: Directive filter display is broken on Safari

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py
https://issues.rudder.io/issues/18874
=> Fixes #18874: Do not try to upgrade cis or openscap plugins

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/ExpectedReports.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/reports/ReportingConfiguration.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/SystemVariableService.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestComputeSchedule.scala, webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
https://issues.rudder.io/issues/18846
The main problem was that there was two places where we mixed up start minutes / start hours / splay time after getting values from json. 
Other part of the PR is removing dead code:
- an Empty case that was never reachable (and so I changed it to a pure result);
- call to `getAgentRunInterval` etc in `PromiseGenerationService` which were never use (we directly use `agentRun`)
=> Fixes #18846: Agent run schedule problem

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py
https://issues.rudder.io/issues/18829
=> Fixes #18829: rudder package should now look for rpkg.index in the dedicated plugin repository instead of its root

webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/DataTypes.scala, webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/FullInventoryRepositoryImpl.scala, webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/InventoryMapper.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala, webapp/sources/rudder/rudder-rest/src/test/resources/api/api_nodes.yml, webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala, webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala, webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TestRestFromFileDef.scala
https://issues.rudder.io/issues/18926
=> Fixes #18926: nodes API with include managementTechnologyDetails leads to error 500 response

contributing/webapp.md
https://issues.rudder.io/issues/18947
=> Fixes #18947: Symlink to rudder-api-client is not documented to use rtf

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DependencyAndDeletionService.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/ModificationValidationPopup.scala
https://issues.rudder.io/issues/18900
=> Fixes #18900: Missing exception details in change request update

agent/sources/client/Makefile
https://issues.rudder.io/issues/19012
=> Fixes #19012: Do not pass xFLAGS as environment

agent/sources/client/Makefile
https://issues.rudder.io/issues/19015
=> Fixes #19015: Do not pass xFLAGS as environment -  missing cflags for toml

agent/sources/client/Makefile, agent/sources/client/argtable-aix.patch, agent/sources/client/src/argtable3.c, agent/sources/client/src/cli.c
https://issues.rudder.io/issues/19025
=> Fixes #19025: AIX fails to build

agent/sources/client/Makefile, agent/sources/client/toml.patch
https://issues.rudder.io/issues/19046
=> Fixes #19046: Add windows support to http client build

relay/sources/relayd/Cargo.lock
https://issues.rudder.io/issues/18903
=> Fixes #18903: Vulnerabilities in relayd hyper dependency

relay/sources/relayd/Cargo.lock
https://issues.rudder.io/issues/19087
=> Fixes #19087: Vulnerability in relayd dependencies diesel and generic-array

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/Properties.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala, webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/nodeProperties.js
https://issues.rudder.io/issues/19085
Several problems here: 
- the public api was using a json string in place of a json object leading to too many quote in json => use the correct method, 
- the update in public api to not use HTML lead to breaking node properties tab display => create an internal API with the old HTML rendering, 
- node properties "inheritedProperty" attribute was still using the HTML rendering.
=> Fixes #19085: Inherited node properties are displayed with escape

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ReportingServiceUtilsTest.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ComplianceData.scala
https://issues.rudder.io/issues/19114
So, the problem was that we were filtering the overriden directive globally, and not by rule, so we had only one overridden for all overrides. 
So now, we filter rule by rule (in a smarter way, and at a place where we can do test, even better) and don't filter with the big axe when building the list of directive lines.
=> Fixes #19114: Overridden directives in the same rule are missing (not even "skipped")

webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/techniqueEditor.html, webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-technique-editor.css, webapp/sources/rudder/rudder-web/src/main/webapp/techeditor/js/ncf.js
https://issues.rudder.io/issues/19119
=> Fixes #19119: Add empty technique parameter in technique editor (6.2 only)

webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-finished/50-reload-policy-file-server
https://issues.rudder.io/issues/19131
=> Fixes #19131: cf-serverd always reloads

webapp/sources/api-doc/paths/groups/all.yml, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/UpdateDynamicGroups.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/NodeGroupDiff.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDiffMapper.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestDataSerializer.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/RestData.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/GroupsApi.scala, webapp/sources/rudder/rudder-rest/src/test/resources/api/api_groups.yml, webapp/sources/rudder/rudder-rest/src/test/resources/api/api_nodes.yml, webapp/sources/rudder/rudder-rest/src/test/resources/api/api_rules.yml, webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala, webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
https://issues.rudder.io/issues/19129
=> Fixes #19129: Clone group via API ask for query

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
https://issues.rudder.io/issues/18999
=> Fixes #18999: when we install a plugin, if the dependency (package manager) is not met, it still tries to install it and fails

Jenkinsfile, relay/sources/relayd/tests/common.rs, relay/sources/relayd/tests/processing_reporting.rs, rudder-lang/src/parser/error.rs, rudder-lang/src/technique.rs, rudder-lang/tests/utils/mod.rs, rust.makefile
https://issues.rudder.io/issues/19195
=> Fixes #19195: Add rudder-lang publication to Jenkinsfile

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PathComputer.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PolicyWriterService.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PromiseWriteDataStructures.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/RemoveNodeService.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/write/PathComputerTest.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/write/WriteTechniquesTest.scala, webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
https://issues.rudder.io/issues/19218
=> Fixes #19218: backup file are not copied correctly when the destination directory is on another FS

webapp/sources/api-doc/components/schemas/settings.yml, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/UpdateDynamicGroups.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/DynGroupService.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/LdapQueryProcessor.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/utils/Utils.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestPendingNodePolicies.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/appconfig/ConfigService.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SettingsApi.scala, webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
https://issues.rudder.io/issues/18981
=> Fixes #18981: Slow computation of dynamic groups on large system

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/queries/CmdbQuery.scala, webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/databaseManagement.html
https://issues.rudder.io/issues/19228
At some point, the localisation name changed from `en-GB` to just `en`
=> Fixes #19228: Date format in search is French localised and the datepicker is broken

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryFileWatcher.scala
https://issues.rudder.io/issues/19268
So it appaers that `java.nio.Files.walk` throws exception if the file is deleted during the walk. It may be possible to take care of that with dozen of line of java, but really, WTH. Switched to `FileUtils`
=> Fixes #19268: Error when processing old inventories with davfs temporary files

webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala
https://issues.rudder.io/issues/19308
=> Fixes #19308: rudder.auth.admin.pass should be stored in bcrypt format

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/domain/TechniqueVersion.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/cfclerk/domain/TechniqueVersionTest.scala
https://issues.rudder.io/issues/19340
=> Fixes #19340: Parent ticket brokes technique version tests

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
https://issues.rudder.io/issues/19367
=> Fixes #19367:  Backport typos checks to 6.2

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala
https://issues.rudder.io/issues/19396
=> Fixes #19396: Move use of cache outside of semaphore in NodeInfoService

relay/sources/rudder-pkg/lib/rudder-pkg/tests/testall
https://issues.rudder.io/issues/19405
=> Fixes #19405: rudder-pkg test should use python3

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
https://issues.rudder.io/issues/19413
=> Fixes #19413: rudder-pkg version parsing does not support version numbers containing a git hash

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/EditorTechnique.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestEditorTechniqueWriter.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/ncf/TechniqueReader.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NcfApi.scala, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala, webapp/sources/rudder/rudder-web/src/test/scala/com/normation/rudder/javascript/CalculateComplianceTest.scala
https://issues.rudder.io/issues/19061
=> Fixes #19061: Use rudderc to compile technique from the editor instead of rudder logic

relay/sources/relayd/src/configuration/logging.rs
https://issues.rudder.io/issues/19470
=> Fixes #19470: Relayd does not start since some keys are missing from its logging.conf file

webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
https://issues.rudder.io/issues/19487
=> Fixes #19487: Directive details display is broken if the name of a directive is too long.

relay/sources/apache/rudder-apache-relay-ssl.conf, relay/sources/rudder-server-relay-postinst
https://issues.rudder.io/issues/18788
=> Fixes #18788: Use agent certificate in httpd configuration

relay/sources/relayd/src/configuration/logging.rs
https://issues.rudder.io/issues/19497
=> Fixes #19497: relayd fails to start because of incorrect default logging config handling

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/Properties.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/nodes/TestMergeGroupProperties.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/GroupsApi.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/ShowNodeDetailsFromNode.scala, webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/nodeProperties.js
https://issues.rudder.io/issues/19513
This escape JS in hostname and inherited properties. For inherited properties, it needed to backport https://github.com/Normation/rudder/pull/3568 and https://github.com/Normation/rudder/pull/3576/
We also gain nice looking inherited properties, and correct json values from API (without additional quotes)
=> Fixes #19513: Hostname is not escpaed in page details title

webapp/sources/api-doc/components/parameters/setting-allowed-networks.yml, webapp/sources/api-doc/components/schemas/api-version.yml, webapp/sources/api-doc/components/schemas/api-versions.yml, webapp/sources/api-doc/openapi.src.yml, webapp/sources/api-doc/paths/settings/allowed_networks.yml, webapp/sources/api-doc/paths/settings/allowed_networks_diff.yml
https://issues.rudder.io/issues/19502
=> Fixes #19502: Missing 'settings' layer in the allowed_networks API doc

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/queries/CmdbQuery.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/LdapQueryProcessor.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala
https://issues.rudder.io/issues/19538
Correct two bugs:
- the filter was incorrect when there wasn't any filters for`Or` case. openldap just returns nothing in that case, which was by luck what we want, but any composition with that filter lead to the same empty result (bad for or)
- in the case where LDAP queries didn't return any nodes, if we are in `Or` case, we STILL need to do the search on all nodes for the properties case
Plus add debugging info to help spot other such errors and move the query logic for properties in the same file than other to make it more easier to look at.
=> Fixes #19538: Or selector for property Name=Value selector returns 0 elements

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/SystemVariableSpecServiceImpl.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/NodeInfo.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/ExpectedReports.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/SystemVariableService.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/RemoveNodeService.scala, webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-500-directives/rules/cfengine-community/rudder.json, webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-two-directives/rules/cfengine-community/rudder.json, webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-gen-var-def-override/rules/cfengine-community/rudder.json, webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-default-install/distributePolicy/1.0/nodeslist.json, webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-default-install/rudder.json, webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/distributePolicy/1.0/nodeslist.json, webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/rudder.json, webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-one-multipolicy/distributePolicy/1.0/nodeslist.json, webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-one-multipolicy/rudder.json, webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-two-directives/distributePolicy/1.0/nodeslist.json, webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-two-directives/rudder.json, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/nodes/NodeKeyHashTest.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
https://issues.rudder.io/issues/19492
Main changes: 
- output for the root server hash in nodelist is now base64 encoded and starts with `sha256//` in place of being hex encoded and start by `sha256:`
- renamed `CfengineKey` utility class to `NodeKeyHash`, since it deals with all kind of hashes
- refactor a bit key crypto processing to factor out common parts, even if bouncy castle and java api try hard to make that difficult, 
- add `POLICY_SERVER_KEY_HASH` which holds the base64 encoded string. This one also has the prefix `sha256//` - is it what we want ?
Also, in node details, we are displaying certificate "fingerprint", which is yet something different: `SHA1 Fingerprint: </label> <samp>{SHA1.hash(cert.getEncoded).grouped(2).mkString(":")}`. Do we want to also display the base64 …
=> Fixes #19492: Add policy server certificate information to policies

relay/sources/rudder-server-relay-postinst
https://issues.rudder.io/issues/19550
=> Fixes #19550: Rudder-server-relay postinstall script fails to modify the certificate paths in the apache configuration

webapp/sources/rudder/rudder-core/src/main/resources/ldap/bootstrap.ldif, webapp/sources/rudder/rudder-core/src/main/resources/ldap/init-policy-server.ldif, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala
https://issues.rudder.io/issues/19556
=> Fixes #19556: Modify the internal rules and directives at install time to support the new system techniques

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/LiftInitContextListener.scala, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
https://issues.rudder.io/issues/19567
=> Fixes #19567: Rudder fails to stop on boot error

language/tools/rudderc-prod.conf
https://issues.rudder.io/issues/19588
=> Fixes #19588: Missing lint section in rudderc config file

webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/nodeProperties.js
https://issues.rudder.io/issues/19597
It's a bad merge from https://issues.rudder.io/issues/18879 which revert change from 6.2 https://issues.rudder.io/issues/19085
=> Fixes #19597: Properties tab is broken in rudder 7.0

webapp/sources/pom.xml, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeRepository.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/JsonSchema.scala
https://issues.rudder.io/issues/19639
- *lot* of security / decoding problem fixed
- amazing perf boost thanks to jsoniter author, 
- availability of an `Json` ast from/to which we can parse objects. Much more flexible for complexe cases.
=> Fixes #19639: Updgrade zio-json to last version for rudder 7.0

relay/sources/rudder-server-relay-postinst
https://issues.rudder.io/issues/19746
=> Fixes #19746: Move SELinux policy application into postinst script

relay/sources/relayd/Cargo.lock
https://issues.rudder.io/issues/19856
=> Fixes #19856: Update openssl embedded in relayd to 1.1.1l

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
https://issues.rudder.io/issues/19874
=> Fixes #19874: rudder package does not print the plugin content at install time

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDiffMapper.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestDataSerializer.scala, webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
https://issues.rudder.io/issues/19786
The problem was that by changing the serialisation format in LDAP for directive ids in a rule id (from `ab459975-7116-40ad-aab7-6479694ff606` to `{"id":"ab459975-7116-40ad-aab7-6479694ff606"}` (with optionnaly `, "revision":"xxx"`), we broken LDAP search on directive IDs in rules used for cleaning-up thing when a directive was deleted. 
So I reverted to the same format that used for displaying ID (ie: `uuid+revision`). 
I also changed that format for the API case, because it will likely result in the same kind of breakages. 
But now, I'm sad because we have two formats for object ID: 
- when we talk about the object own ID, it's two fields (both in LDAP and in API): `{... "id":"xxx", "revision":... }`. 
- when we talk about IDs of objects referenced …
=> Fixes #19786: When we delete a directive, it's not removed from the rules

webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ApiCalls.elm, webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/DataTypes.elm, webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Init.elm, webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/JsonDecoder.elm, webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/JsonEncoder.elm, webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Rules.elm, webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/View.elm, webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewCategoryDetails.elm, webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRuleDetails.elm, webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
https://issues.rudder.io/issues/19808
=> Fixes #19808: Add a button to create a new Rule category

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/NodeConfigurationService.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
https://issues.rudder.io/issues/19740
=> Fixes #19740: When 2 changes are close in time,  expected report on the compliance page don't show the new config

Jenkinsfile, language/Cargo.toml, relay/sources/relayd/Cargo.lock, relay/sources/relayd/Cargo.toml, rust.makefile
https://issues.rudder.io/issues/19915
=> Fixes #19915: Improve rust build times

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/model/JsInitContextLinkUtil.scala, webapp/sources/rudder/rudder-web/src/main/elm/rules/elm.json, webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ApiCalls.elm, webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/DataTypes.elm, webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Init.elm, webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Rules.elm, webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/View.elm, webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRulesTable.elm, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala, webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js, webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/ruleManagement.html
https://issues.rudder.io/issues/19872
So, there is apparently no turnkey solution to set up a URL system the way we want it. Here is my workaround, which I think can be highly improved: 
I used 2 new ports:
- `pushUrl` which updates the url based on what happens in the Elm app (e.g. when a rule is selected):
<pre>
OpenRuleDetails rId ->
(model, Cmd.batch [(getRuleDetails model rId), (pushUrl ((getUrl model) ++ "/rule/" ++rId.value))])
</pre>      
- `onUrlChange` which updates the Elm app when the page loads and when the url is changed. This port calls the `UrlChanged` function, which parses the url and determines what action to take based on the result. (All the Url rewriting logic is done on the Elm side.
I also added redirections to avoid 404 errors when the url looks like …
=> Fixes #19872: Rules can't be accessed directly by url, all redirection broken

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/PolicyServerManagementService.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/ldap/LoadDemoDataTest.scala, webapp/sources/rudder/rudder-web/src/test/resources/ldap-data/schema/00-core.ldif, webapp/sources/rudder/rudder-web/src/test/resources/ldap-data/schema/01-pwpolicy.ldif, webapp/sources/rudder/rudder-web/src/test/resources/ldap-data/schema/04-rfc2307bis.ldif, webapp/sources/rudder/rudder-web/src/test/resources/ldap-data/schema/05-rfc4876.ldif, webapp/sources/rudder/rudder-web/src/test/resources/ldap-data/schema/099-0-inventory.ldif, webapp/sources/rudder/rudder-web/src/test/resources/ldap-data/schema/099-1-rudder.ldif, webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/migration/TestMigrateSystemTechnique7_0.scala
https://issues.rudder.io/issues/20009
So, the problem is that we tried to use a generic "InMemoryLdap" for test whose class is in `rudder-core`. That server need files, in `src/main/resources/ldap-data` to work. They are loaded with a `getClass/classloader/getResource/getpath`.
That works great when you use it for tests from `rudder-core`. That works well when used from `rudder-web` and maven knows that `rudder-core` is in the build task and so knows that it can actually access classes there. 
That does not work when maven try to build `rudder-web` autonoumously, because in that case, it gets `rudder-core-test.jar`, and files can't be accessed with a `getPath` in a jar. And java being what it is in expressivity, it does not say so but prefer a very informative NPE.
This PR just copy all …
=> Fixes #20009: In CI, technique migration test sometimes throw an NPE

language/Makefile
https://issues.rudder.io/issues/20041
=> Fixes #20041: rudder-lang in 7.0 should use ncf 7.0

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/plugins/PublicPlugin.scala
https://issues.rudder.io/issues/20264
=> Fixes #20264: Allow to customize in which menu plugins are set

webapp/sources/scala-ldap/src/main/scala/com/normation/ldap/sdk/LDAPIOResult.scala
https://issues.rudder.io/issues/19980
=> Fixes #19980: spurious "connection_read(9): no connection!" in /var/log/rudder/ldap/slapd.log

webapp/sources/Dockerfile
https://issues.rudder.io/issues/20322
=> Fixes #20322: Make JVM version configurable

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/PolicyServerManagementService.scala, webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/migration/TestMigrateSystemTechnique7_0.scala
Fixes #20359: techniques are seens as deleted even if there are there in Rudder 7.0
=> Fixes #20359: techniques are seens as deleted even if there are there in Rudder 7.0

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ComplianceApi.scala
https://issues.rudder.io/issues/20310
=> Fixes #20310: Method getByRulesCompliance used by API is highly inefficient

webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/DataTypes.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/domain/VariableAndSectionSpec.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/xmlparsers/SectionSpecParser.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/ExpectedReports.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/StatusReports.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/EditorTechnique.scala, webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/metadata.xml, webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_with_blocks/1.0/metadata.xml, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestEditorTechniqueWriter.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeExpectedReportTest.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ExecutionBatchTest.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala, webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/DataTypes.elm, webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/Editor.elm, webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/JsonDecoder.elm, webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/JsonEncoder.elm, webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewBlock.elm
https://issues.rudder.io/issues/20342
Implemented with a sub-select for worst case:
=> Fixes #20342: Add a worst-case, weighted 1 for block compliance mode

webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewMethod.elm, webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-technique-editor.css
https://issues.rudder.io/issues/20308
Before :
After :
=> Fixes #20308: when we edit the content of a generic method in 7.0, there is no way to know which method it is

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/policies/RuleApplicationStatus.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/rule/category/LDAPRuleCategoryRepository.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/RuleApplicationStatusService.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/RuleApi.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/ComputePolicyMode.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleGrid.scala
https://issues.rudder.io/issues/20367
=> Fixes #20367: first go at improving perfs for rules/tree

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/Compliance.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ComplianceApi.scala, webapp/sources/rudder/rudder-web/src/main/elm/rules/elm.json, webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ApiCalls.elm, webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ComplianceUtils.elm, webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/DataTypes.elm, webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Init.elm, webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/JsonDecoder.elm, webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Rules.elm, webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRulesTable.elm, webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewTabContent.elm, webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewUtils.elm
https://issues.rudder.io/issues/20302
* rule compliance was not aware of blocks, so client side was failing on that case => added all the decoding logic for blocks in elm, + rewrite lots of structures to be able to deal with that.
* compliance for nodes from rule was done in client side, but was not always consistant with backend => done in backend
* rule list was abysmally slow => first call for API only get minimal info so that the list is quick, and compliance details are loaded when the user click on rule details
=> Fixes #20302: Repair compliance display in Rules page

relay/sources/relayd/Cargo.lock
https://issues.rudder.io/issues/20429
=> Fixes #20429:  Update openssl to 1.1.1m - relayd

relay/sources/relayd/benches/benches.rs, relay/sources/relayd/src/data/report.rs, relay/sources/relayd/src/data/runlog.rs, relay/sources/relayd/src/output/database.rs, relay/sources/relayd/src/processing/reporting.rs, relay/sources/relayd/tests/files/runlogs/2020-03-24T12:29:54+00:00@root.json
https://issues.rudder.io/issues/20446
=> Fixes #20446: Don't insert partial runs as run logs

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/domain/VariableAndSectionSpec.scala
https://issues.rudder.io/issues/20459
=> Fixes #20459: Value 'focus:48137400-7f48-48bd-a888-9522167b5b81' is not a valid reporting composition rule

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala, webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
https://issues.rudder.io/issues/20437
There was (at least) three problem in previous code: 
- we duplicated the use of `outputpath`, and it was hard to see because we duplicated much code in path creation => factor out common path in an object specific to a compiler instance, and use it to remove some boilerplate
- we we using bad extension for compilation => corrected 
- we were always using the cfengine extension, whatever current target was => corrected
=> Fixes #20437: Error when writing techniques via the technique editor

webapp/sources/api-doc/components/schemas/rule-target.yml, webapp/sources/api-doc/paths/rules/tree.yml, webapp/sources/rudder/rudder-core/src/main/resources/ldap/bootstrap.ldif, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/policies/RuleTarget.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/migration/CheckAddSpecialTargetAllPolicyServers.scala, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/migration/CheckMigrateSystemTechniques7_0.scala, webapp/sources/rudder/rudder-web/src/test/resources/ldap-data/bootstrap-6_2.ldif, webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/migration/TestMigrateSystemTechnique7_0.scala
https://issues.rudder.io/issues/20460
Add migration logic for rules that were using special target related to server roles. 
That PR:
- migrate `all_nodes_without_role` to existing special target `special:all_exceptPolicyServers`
- add a new special target for "all policy servers" (not sure why we didn't have it): `special:all_policyServers`
- migrate `special:all_servers_with_role` to the new `special:all_policyServers` target
- add a new boot check to create the special target if needed. 
And add some cleaning related to previous migration enhancement: remove dead code and unused import, update API doc
=> Fixes #20460: Invalid attribute 'special:all_servers_with_role' (or special:all_nodes_without_role) for entry ruleTarget

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/AsyncDeploymentActor.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/PolicyGenerationLogger.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/NodeGroupRepository.scala, webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
https://issues.rudder.io/issues/20462
That PR add a promise (ie something that can be done exactly once, and that other things can wait for it to be done) that is checked for completion before actually starting policy generation.
The promise is completed at end of `Boot.boot` method, ie once lift knows rudder is started.
To be able to use the `promise.await` in policy generation agent, I needed to transform the code into a ZIO effect.
Also remove a warning for missing pattern match which would lead to a runtime exception, likely introduced in pr #4065
=> Fixes #20462: Delay policy generation until rudder app is fully boot

webapp/sources/rudder/rudder-web/src/main/elm/onboarding/sources/ApiCalls.elm, webapp/sources/rudder/rudder-web/src/main/elm/onboarding/sources/DataTypes.elm, webapp/sources/rudder/rudder-web/src/main/elm/onboarding/sources/JsonDecoder.elm, webapp/sources/rudder/rudder-web/src/main/elm/onboarding/sources/JsonEncoder.elm, webapp/sources/rudder/rudder-web/src/main/elm/onboarding/sources/Onboarding.elm, webapp/sources/rudder/rudder-web/src/main/elm/onboarding/sources/View.elm
https://issues.rudder.io/issues/20478
=> Fixes #20478: metrics are still present in wizard, and wizard doesn't end

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/TechniqueApi.scala, webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechniqueTabs.elm, webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-technique-editor.css
https://issues.rudder.io/issues/20133
=> Fixes #20133: Technique editor allows id with only case difference, do an error, but still save technique

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/plugins/PublicPlugin.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/plugins/RudderPlugin.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PluginManagement.scala, webapp/sources/rudder/rudder-web/src/main/webapp/secure/plugins/pluginInformation.html, webapp/sources/rudder/rudder-web/src/test/scala/com/normation/plugins/RudderPluginJsonTest.scala, webapp/sources/rudder/rudder-web/src/test/scala/com/normation/plugins/RudderPluginTest.scala, webapp/sources/utils/src/main/scala/com/normation/utils/Version.scala
https://issues.rudder.io/issues/20261
This change needs https://github.com/Normation/rudder-plugins/pull/433 to work. 
It brings back the old version format to Plugin version (in the code at least). 
The main changes are: 
- it needs `main-build.conf` in the classpath at the same place as `build.conf` to have access to rudder ABI version (ie the version of rudder used to build that plugin jar)
- simplify `PluginVersion`: in place of being some kind of poor copy of  `Version` from utils, it's now just two `Version`s: one for the rudder ABI, the other for the plugin version
- normalize each version on at least 3 dot separated numbers, adding "0" for missing parts
- use the full plugin version (ie `rudderABI-pluginOwnVersion`) for the plugin object field `version`
- compare between …
=> Fixes #20261: Add a warning in plugin page if a version mismatches rudder patch one

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/ComplianceLevel.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/ReportType.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/reports/TestComplianceLevel.scala
https://issues.rudder.io/issues/20373
I was not able to reproduce the mentionned cases in rudder (99.99% missing) but I *believe* it was something around 3 components having each 1 missing, and so each contributed 33.33% percent. 
Nonetheless, I was able to make a failing unit test with a compliance with 1 success, 1 na, 1 error that sum to 99.99% corrected by that PR, so I believe that that PR should also correct the composition since AFAIK (and found) compliance percent are not coupounded/summed, it's always the compliane level (which is good). 
So, this PR centralize all computing of percent in the `CompliancePercent` class, and in particular it adds a `CompliancePercent.fromLevels` method that build percents with a sum of 100 by construction. It also remove any percent computing from …
=> Fixes #20373: compliance from API doesn't always adds up to 100%

webapp/sources/scala-ldap/src/main/scala/com/normation/ldap/sdk/LDAPConnection.scala
https://issues.rudder.io/issues/20541
by continuing change from parent ticket, it leads to a steady 1m19/1m20 for dynamic group computation, rather than 1m22/25
=> Fixes #20541: continu change of parent ticket

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/RuleApi.scala, webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/DataTypes.elm, webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Rules.elm, webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/View.elm, webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewTabContent.elm, webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-rules.css
https://issues.rudder.io/issues/20095
=> Fixes #20095: If a rule is in a category that no longer exists, it can't be accessed in rule tree

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/Compliance.scala
https://issues.rudder.io/issues/20585
=> Fixes #20585: First node name is used for all nodes in rule compliance details "by node"

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
https://issues.rudder.io/issues/20602
=> Fixes #20602: rpm python API incompatible in python3

webapp/sources/api-doc/components/parameters/compliance-percent-precision.yml, webapp/sources/api-doc/paths/compliance/global.yml, webapp/sources/api-doc/paths/compliance/node.yml, webapp/sources/api-doc/paths/compliance/nodes.yml, webapp/sources/api-doc/paths/compliance/rule.yml, webapp/sources/api-doc/paths/compliance/rules.yml, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/db/Doobie.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/ComplianceLevel.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/StatusReports.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ComplianceRepository.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/reports/StatusReportTest.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/reports/TestComplianceLevel.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ExecutionBatchTest.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/Compliance.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ComplianceApi.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/RuleApi.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ComplianceData.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/HomePage.scala
https://issues.rudder.io/issues/20607
Superseed #4115 and keep #4110 for correction of https://issues.rudder.io/issues/20573
The idea is to be able to specify what precision we want for compliance percent in the API calls, and let the backend compute compliance with that value. Most of the pr is passing the `precision` parameter around. 
Note that we can't specify `precision` value for the  `lazy val pc` attribute in `ComplianceLevel` instance, so a default value of `2` is kept. That `pc` value does not seems to be used in the compliance displaying for UI, so it makes me wonder if we really need an heavy lazy val in each `ComplianceLevel` objects, perhaps we should only compute it when needed with `CompliancePercent.fromLevels(c, precision)` - cc @ncharles for that. 
The 2nd commit totaly …
=> Fixes #20607: Make possible to choose precision in compliance percent API

webapp/sources/api-doc/introduction.md
https://issues.rudder.io/issues/3881
=> Fixes #3881: API : URL ending with / are seen like /[empty string parameter]

webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRuleDetails.elm, webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRulesTable.elm, webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewUtils.elm
https://issues.rudder.io/issues/20638
Maybe i'm wrong, is the count of recent changes should be the same as "changes"  count displayed in table rows ?
=> Fixes #20638: Reccent changes count on rule tab

webapp/sources/pom.xml
https://issues.rudder.io/issues/20727
=> Fixes #20727: Maven needs <version> tag even if version is in <dependency-management>

webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewBlock.elm
https://issues.rudder.io/issues/20738
=> Fixes #20738: Once we decided on which generic method we focus report in a block, it shows the uuid rather than its name

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala, webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://issues.rudder.io/issues/20721
=> Fixes #20721: kernel version doesn't show in the node page

webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/DataTypes.elm, webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/Editor.elm, webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewMethod.elm, webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-technique-editor.css
https://issues.rudder.io/issues/19720
When the panel of method is closed and we click on "Show doc" it seems that the auto scroll doesn't go to the right location (see gif at the end) but we can double click (to close the doc and reopen) to trigger the scroll in the right location.
=> Fixes #19720: when clicking on "show docs" on a generic method in the middle part of technique editor, it doesn't unfold the right part

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/queries/CmdbQuery.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/queries/DitQueryData.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeGroupRepository.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/DynGroupUpdaterService.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/LdapQueryProcessor.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/QueryProcessor.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestPendingNodePolicies.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala, webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/SearchNodeComponent.scala
https://issues.rudder.io/issues/20716
This PR corrects the computation of invertion on dynamic groups, that was failing due to the ordering of action (invert was before the properties computation)
It goes the extra mile to improve perf of dynamic group computation, by changing easy ldap search on properties available on nodeinfo to a nodeinfofilter (so that it's a post filter). The drawback is that when we only search on nodeinfo related info, there is no filter to apply, so it fetches all nodes to do the search, so it kind of kill the advantage of doing so, that's why i resolved to add a boolean that says: ok, don't compute anything, and take all from cache
Main changes in code
* in CMDBQuery, the filters on NodeInfo based on LDAP filter have been replaced to filters on NodeInfo ( …
=> Fixes #20716: Correct dynamic group computation onf properties and improve speed

language/docs/usage.adoc
https://issues.rudder.io/issues/20766
=> Fixes #20766: Document the rudder-lang and technique editor incompatibilities

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/StatusReports.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/reports/StatusReportTest.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ExecutionBatchTest.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ComplianceData.scala, webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
https://issues.rudder.io/issues/20851
=> Fixes #20851: Regroup report with their values, not with the expanded value

webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/FusionInventoryParser.scala, webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-inventories/rudder-tag/one-agent-full.ocs
https://issues.rudder.io/issues/20866
=> Fixes #20866: Correct parsing of id in software updates

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DataStructures.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/RuleValService.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeExpectedReportTest.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/RuleValServiceTest.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestNodeAndGlobalParameterLookup.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/write/PolicyAgregationTest.scala
https://issues.rudder.io/issues/20828
So, as explained in the ticket, the problem was that we were building expected reports at the end of generation, we were looking at possible variables for each component expecting reporting. 
But during Policy/PolicyDraft/etc generaly earlier, we missed to differentiate variables based on reportId. So, for us, all variable with the same component name were the same, and we kept just one (adapting cardinality I think, but actually we don't care much about cardinality in any case, because of iterators and the like). 
So, we ended with just ONE variable. 
And so, the expected component creation was looking around, correctly finding its variables with report id (because they come from elsewhere), but when it tries to reconciliate with the policy to get …
=> Fixes #20828: Unexpected/missing for same component, same value

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/SharedFilesAPI.scala, webapp/sources/rudder/rudder-web/src/main/webapp/templates/angular/technique-editor-filemanager/modals.html
https://issues.rudder.io/issues/19319
=> Fixes #19319: When editing files with the technique editor resources manager, newlines at the end of file are trimmed

webapp/sources/rudder/rudder-web/src/main/resources/applicationContext-security.xml, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderProviderManager.java
https://issues.rudder.io/issues/20886
We need to set a name to the main http configuration filter chain so that we can change it programmatically in a plugin at runtime to add Oauthv2 filters
=> Fixes #20886: Add name for spring security main auth configuration bean to be used by oauth2 

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala, webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/1.0/technique.ps1, webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/2.0/technique.ps1, webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/technique.ps1
https://issues.rudder.io/issues/20963
=> Fixes #20963: Add suport for report id reporting with Windows agent

webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/FusionReportUnmarshaller.scala
https://issues.rudder.io/issues/20984
=> Fixes #20984: Two same envvar modulo a space at begining of name leads to LDAP error when saving inventory

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SettingsApi.scala
https://issues.rudder.io/issues/20979
=> Fixes #20979: Generation not started when modifying authorized network via API

api-doc/Dockerfile, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/NodeGroupRepository.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeGroupRepository.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ComplianceApi.scala, webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
https://issues.rudder.io/issues/21028
This change makes the lock more tight on getting all groups, and introduce a method that only get the NodeGroupId, Set[NodeId] to make the fetching of nodes per group faster.
Impact is minimal (from 400-800ms to 300-500ms) but nonetheless wlecomed
=> Fixes #21028: The way groups are fetched when responding to API compliance is inefficient

Jenkinsfile, webapp/sources/pom.xml
https://issues.rudder.io/issues/21091
=> Fixes #21091: Require Java 11

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/LiftApiDispatcher.scala, webapp/sources/rudder/rudder-rest/src/test/resources/api/api_nodes.yml, webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala, webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TestRestPlusInPath.scala
https://issues.rudder.io/issues/20943
When on API, correct back "+" that were changed inot " " by lift 
Also correct tests that were not returning the correct node :/
=> Fixes #20943: Rudder incorectly parse URL with a '+' in the path into spaces

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/ComplianceLevel.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/reports/TestComplianceLevel.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/Compliance.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ComplianceApi.scala
https://issues.rudder.io/issues/20998
This PR revisits the way ComplianceLevel are computed, to make it faster, and to fix issue in specific cases (ex,  200 succes, 199 repaired, 1 error, 1 missing, 1 unexpected , 1 non compliancere gives 47% success and 50% repaired with 0 precision)
All in all, the computation is ~4 times faster, mainly by using Long computation rather than BigDecimal
The drawback is that we can't go further than precision 5 (I can't seem to see which use case would need more than that), so computation are made using Long, by multiplying with the power of ten, and then truncating.
It also introduces a method to compute compliance directly without pending result, so that we can skip the duplication of ComplianceLevel and the creation of a CompliantPercent
It is *not* …
=> Fixes #20998: Performance of compliance computation in ComplianceLevel can be improved

webapp/sources/rudder/rudder-web/src/main/resources/demo-rudder-users.xml, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderUserDetailsFile.scala
https://issues.rudder.io/issues/21068
=> Fixes #21068: Make user login not case sensitive

relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
https://issues.rudder.io/issues/21124
=> Fixes #21124: rudder package cannot find version anymore -  typo

webapp/sources/pom.xml, webapp/sources/rudder/rudder-core/pom.xml, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/db/Doobie.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/ExpectedReports.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitParseRudderObjects.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/write/WriteTechniquesTest.scala, webapp/sources/rudder/rudder-rest/pom.xml
https://issues.rudder.io/issues/21102
Update dependencies for Rudder 7.2. The notable updates are:
- we don't change to `scala3` obviously, but last minor in `2.13` branch gives hint about what won't work anymore
- updates on mvn plugin, but AFAIS no API changes
- no major changes in the complicated framework: `zio`, `spring`
- `spring-security` has major upgrade, but it seems to continue to work as before (some deprecation warning in oauth module, they can be traited with oauth updates),
- `liftweb`: a minor version update, but given the readme, it's just a deprecation of squeryl record, that we don't use, 
- `doobie`: major update, but it seems to change... Nothing for us.
- but it made the upgrade of `fs2`/`http4s`/`zio-cats-compat` impossible; since `http4s` is only used in one test …
=> Fixes #21102: Update scala dependencies for rudder 7.2

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/policies/Directive.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/policies/Rule.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/DirectiveApi.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/RuleApi.scala, webapp/sources/utils/src/main/scala/com/normation/ObjectVersionCommons.scala
There was a typo in the method name which is used to parse ID, perhaps it's why it was not used on some API (and more likely, when I did the refactoring from request parameter to `uuid+revision` format, I forgot /some/ API endpoints).
https://issues.rudder.io/issues/21150
=> Fixes #21150: Directive and rule revision is not parsed in API

relay/sources/rudder-server-relay-postinst
https://issues.rudder.io/issues/21143
=> Fixes #21143: Backup ca.cert like other cert files

webapp/sources/rudder/rudder-web/src/main/resources/logback.xml
https://issues.rudder.io/issues/21166
=> Fixes #21166: Root log explain_compliance is in debug by default

webapp/sources/api-doc/paths/inventories/upload.yml, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryFileWatcher.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryProcessor.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/inventory/TestCertificate.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RudderJsonResponse.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/InventoryApi.scala, webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
- now, API put files in the usual directory, and they are processed as other inventories
- create `trait` to make more clear what are the public API in services and how the are used in other services (code on interfaces)
- removed the logic to have a non-blocking inventory save for API case
- remove the saveInventory queue. Now, the whole [xml parsing, signature checking, ldap save] is a blocking method with a parallelism of configured by `inventory.parse.parallelization`, default `1` because it seems that in general, there is little advantage of making it more appart stressing LDAP
- add inventory cleaning in the garbage collector: remove inventories older than `inventories.watcher.max.age.before.deletion`, remove unmatched pairs
https://issues.rudder.io/issues/19920
=> Fixes #19920: root inventory is missing and need to be resent after install

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/HomePage.scala
https://issues.rudder.io/issues/21230
=> Fixes #21230: Improve performance of display for agent version on homepage

relay/sources/relayd/src/configuration/logging.rs, relay/sources/relayd/src/configuration/main.rs, relay/sources/relayd/src/data/node.rs, relay/sources/relayd/src/main.rs, relay/sources/relayd/tests/api_system_status.rs
https://issues.rudder.io/issues/21279
=> Fixes #21279: relayd error messages about config files are lacking path information

webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/NodeInventory.scala, webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/FusionInventoryParser.scala, webapp/sources/ldap-inventory/inventory-fusion/src/test/scala/com/normation/inventory/provisioning/fusion/TestPreParsing.scala, webapp/sources/ldap-inventory/inventory-fusion/src/test/scala/com/normation/inventory/provisioning/fusion/TestReportParsing.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestUtils.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RoleApiMapping.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/CreateNodeData.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/RulesInternalAPI.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala, webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala, webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/NodeApiTest.scala, webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
https://issues.rudder.io/issues/21117
Add the node create API to Rudder. 
Also refactored out of InventoryParsing the OS detection part so that the code is not duplicated, it's already brittle enought like that, we really don't want to have an other place to change when we add support for new OS.
=> Fixes #21117: Moving create node plugin into Rudder

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestDataSerializer.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/NodeDetailLevel.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala, webapp/sources/rudder/rudder-rest/src/test/resources/api/api_nodes_properties.yml, webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala, webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
https://issues.rudder.io/issues/21322
Sorting properties in returned JSON request is to ease tests and be consistent with what we do in 7.0 and latter.
The real change is just not serializing then parsing again the property when it's already a JValue.
Other changes are just for test infra.
=> Fixes #21322: Using '{' in node property lead to error

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/RuleApi.scala, webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/RuleTests.scala
https://issues.rudder.io/issues/21175
=> Fixes #21175: Impossible to put a Rule in a subcategory

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
https://issues.rudder.io/issues/21293
Add the use of an overriding configuration directory. By default, it is the name of the config file with `d.`  appended to it but can be overridden if needed with a JVM parameter.
Log info for such things are important, they looks like: 
```
[2022-06-20 10:42:57+0200] INFO  application - Use configuration file defined by JVM property -Drudder.configFile : /home/fanf/java/workspaces/rudder-project/static-config/configuration-rudder-7.1.properties
[2022-06-20 10:42:57+0200] INFO  application - JVM property -Drudder.configDir is not defined: using /home/fanf/java/workspaces/rudder-project/static-config/configuration-rudder-7.1.properties.d directory
[2022-06-20 10:42:57+0200] DEBUG application - Overriding configuration files in …
```
=> Fixes #21293: Allow overriding rudder-web.properties parameters with files in rudder-web.properties.d

webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/AgentTypes.scala, webapp/sources/rudder/rudder-core/src/main/resources/ldap/bootstrap.ldif, webapp/sources/rudder/rudder-core/src/main/resources/ldap/init-policy-server.ldif, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/NodeInfo.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala, webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewMethodsList.elm, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/migration/CheckAddSpecialNodeGroupsDescription.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala, webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/directiveManagement.html, webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/migration/TestMigrateSystemTechnique7_0.scala
https://issues.rudder.io/issues/21238
=> Fixes #21238: Rename "classic nodes" to "unix node"

relay/sources/relayd/Cargo.lock
https://issues.rudder.io/issues/21362
=> Fixes #21362: Update embedded openssl to 1.1.1q - relayd

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala, webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/1.0/technique.cf, webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/2.0/technique.cf, webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/rudder_reporting.cf, webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/technique.cf
https://issues.rudder.io/issues/20603
This PR changes the way ncf techniques are generated to support (at least partially) iterators.
The main idea is to create a *bundle* that will set the context and call the effective generic method. This is necessary so that any iterator within the arguments of the generic method are not iterated once for the reporting context, and then once for the generic method
One bundle is created by generic method, named by the promiser of the generic method plus an increment id.
The resulting code looks like
```
"id1_${report_data.directive_id}" usebundle => id1_0("Customized component", "${node.properties[apache_package_name]}", "id1", "${node.properties[apache_package_name]}", "2.2.11"),
if => concat("(debian)");`
```
and the bundle doing the action being
``` …
```
=> Fixes #20603: Reports on method using iterator are wrong in the cli output

webapp/sources/api-doc/code_samples/curl/archives/export.sh, webapp/sources/api-doc/code_samples/curl/archives/import.sh, webapp/sources/api-doc/openapi.src.yml, webapp/sources/api-doc/paths/archives/export.yml, webapp/sources/api-doc/paths/archives/import.yml, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ArchiveApi.scala, webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
https://issues.rudder.io/issues/21394
Add missing API documentation for import/export. 
Also, split the checking archive part of "save archive service" so that it is easier to understand goals and to add checking point latter on.
=> Fixes #21394: Missing API documentation for import/export policies with dependencies

webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/Identifiers.scala, webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/InventoryDit.scala, webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/ReadOnlySoftwareInventoryDAOImpl.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/NodeDetailLevel.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
https://issues.rudder.io/issues/21241
This PR improves performance of node API when we fetch softwares, and overall some of the perfs for software related topic
However, it is not sufficient to make improvement enough to get many softwares out of Ruder with the API:
* getting inventory with software from 1 node takes 10s with this change (never ended before).
* getting inventories with software from 111 nodes don't finish
Adding an index on softwareId makes the inventory from 1 node respond in 1 second, and 20s for the 111 nodes
=> Fixes #21241: API to fetch nodes + software times out on large instance

webapp/sources/rudder/rudder-web/src/main/elm/accounts/sources/ViewUtils.elm
https://issues.rudder.io/issues/21468
=> Fixes #21468: 

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/queries/CmdbQuery.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/DynGroupUpdaterService.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/LdapQueryProcessor.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/QueryProcessor.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/NewNodeManager.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala, webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/SearchNodeComponent.scala, webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/migration/TestMigrateSystemTechnique7_0.scala
Based on https://github.com/Normation/rudder/pull/4164
Changing the types to remove most of the hashCode computation, most notably, using Set for NodeInfo is a really bad idea
With this (unfinished) code, computation of dynamic group goes from 1m15 (pr 4164) to 35s
Do not merge for now, this is only exploration
The only relevant thing is to return nodeId rather than NodeInfos now that we don't need serverrole info
=> Fixes #20758: Improve node computation

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/CampaignEventRepository.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/DataTypes.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/JsonCampaignSerializer.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/MainCampaignService.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/CampaignApi.scala, webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala, webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/CampaignApiTest.scala, webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/SystemApiTest.scala
https://issues.rudder.io/issues/21539
=> Fixes #21539: Make campaign test work

webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/CampaignApiTest.scala
https://issues.rudder.io/issues/21554
=> Fixes #21554: One of campaign test is flaky

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryFileWatcher.scala
https://issues.rudder.io/issues/21665
the correction is to handle the `OVERFLOW` event kind and trigger the clean-up process on it. We wait a bit before doing that, because if we got `OVERFLOW`, likely the server is very busy.
That need a bit of refactoring for the clean-up process: now, one part knows all about cleaning, and the other is just the scheduling. 
Also handle the exception case for inotify with an error log.
=> Fixes #21665: When we receive a lot of inventories, inotify "OVERFLOW" is not handled 

webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRuleDetails.elm, webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewUtils.elm
We also count excluded groups.
When we move a group from excluded to included (vice versa), we considere that there is a deletion and addition
https://issues.rudder.io/issues/21546
=> Fixes #21546: When editing a rule, the groups changes do not behave like the directives changes

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ArchiveApi.scala, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
https://issues.rudder.io/issues/21707
- this pr make the technique library be reloaded and triggers policy generation
- there was also a bug in the parsing of technique path and translation to categories: regex was eager, so that if the categorie name ended by `techniques`, it was ignored (which happens for `ncf_techniques`, fortunately)
- also add debug/trace logs to be able to better understand what is happening on archive import if needed
=> Fixes #21707: Archive import does regenerate techniques/policies

relay/sources/relayd/src/data/report.rs
https://issues.rudder.io/issues/21736
=> Fixes #21736: when a key is multi-line, the reporting fails because agent add the datetime in fron of each new line

webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewMethod.elm
https://issues.rudder.io/issues/21172
=> Fixes #21172: Input Text disapear in technic editor when entering a space with Grammarly/LanguageTool extension

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
https://issues.rudder.io/issues/21755
=> Fixes #21755: Impossible to move groups

webapp/sources/rudder/rudder-web/src/main/resources/rudder-system-global-parameter.conf
https://issues.rudder.io/issues/21784
=> Fixes #21784: add a default value for syslog facility output for agent and server compontent

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
https://issues.rudder.io/issues/21854
=> Fixes #21854: Properly configure CSP violation handler

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
https://issues.rudder.io/issues/21809
=> Fixes #21809:  Dont redirect other tabs to login form when session cookie is replaced - add a notification

webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
https://issues.rudder.io/issues/21806
=> Fixes #21806: 

webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/homePage.js
https://issues.rudder.io/issues/22015
=> Fixes #22015: Missing epoch string in search node query from pie chart

webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewMethod.elm, webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-technique-editor.css
https://issues.rudder.io/issues/21323
=> Fixes #21323: Focus change on the firest caracter in input box for method's condition

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleDisplayer.scala, webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-directives.css, webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css, webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder.css, webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentDirectiveEditForm.html
https://issues.rudder.io/issues/22086
=> Fixes #22086: Transform tabs of the directives into real tabs

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/ncf/TechniqueReader.scala
https://issues.rudder.io/issues/22100
=> Fixes #22100: When reading methods, if generic_methods.json does not exists, rudder should generate it

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala, webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/1.0/technique.ps1, webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/2.0/technique.ps1, webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/technique.ps1
https://issues.rudder.io/issues/14371
So, the problem is that the parameter name of the technique is:
- "transformed" to be a valide power shell name in the list of parameters (ie the name of the parameter is changed to removed "_"), 
- not transformed when call with `${}`
The mismatch between declaration and call-site lead to the problem. 
Plus, it seems that we don't need a "power shell valid name" for the parameter name, and that "_" are ok.
=> Fixes #14371: At least on windows, technique editor parameters can not handle "_" char

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala, webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/technique.ps1, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestEditorTechniqueWriter.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeExpectedReportTest.scala
https://issues.rudder.io/issues/22126
=> Fixes #22126: Windows generic method parameters are always written "mandatory=true" even when "mayBeEmpty" 

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/parameters/ParameterDiff.scala
https://issues.rudder.io/issues/22106
=> Fixes #22106: Creating a global parameter doesn't trigger a policy generation in Rudder 6.2, 7.1 and 7.2

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/DynGroupService.scala
https://issues.rudder.io/issues/22210
=> Fixes #22210: Do not trigger a group reload if last check is younged than 100 ms

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingService.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RoleApiMapping.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/Compliance.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ComplianceApi.scala
https://issues.rudder.io/issues/22150
=> Fixes #22150: API for directive compliance

relay/sources/relayd/deny.toml
https://issues.rudder.io/issues/22249
=> Fixes #22249: Ignore RUSTSEC-2023-0001 in relayd

.cargo/config.toml
https://issues.rudder.io/issues/22294
=> Fixes #22294: Workaround for CVE-2022-46176 in cargo

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingService.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RoleApiMapping.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/Compliance.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ComplianceApi.scala, webapp/sources/rudder/rudder-web/src/main/elm/directivecompliance/elm.json, webapp/sources/rudder/rudder-web/src/main/elm/directivecompliance/sources/ApiCalls.elm, webapp/sources/rudder/rudder-web/src/main/elm/directivecompliance/sources/ComplianceUtils.elm, webapp/sources/rudder/rudder-web/src/main/elm/directivecompliance/sources/DataTypes.elm, webapp/sources/rudder/rudder-web/src/main/elm/directivecompliance/sources/Directivecompliance.elm, webapp/sources/rudder/rudder-web/src/main/elm/directivecompliance/sources/Init.elm, webapp/sources/rudder/rudder-web/src/main/elm/directivecompliance/sources/JsonDecoder.elm, webapp/sources/rudder/rudder-web/src/main/elm/directivecompliance/sources/View.elm, webapp/sources/rudder/rudder-web/src/main/elm/directivecompliance/sources/ViewNodesCompliance.elm, webapp/sources/rudder/rudder-web/src/main/elm/directivecompliance/sources/ViewRulesCompliance.elm, webapp/sources/rudder/rudder-web/src/main/elm/directivecompliance/sources/ViewUtils.elm, webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewUtils.elm, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala, webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-directives.css, webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-menu.css, webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-progress-bar.css, webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-template.css, webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/directiveManagement.html, webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentDirectiveEditForm.html
https://issues.rudder.io/issues/22072
=> Fixes #22072: Display compliance by directive

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/ApplicationLogger.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/Authorizations.scala, webapp/sources/rudder/rudder-web/src/main/resources/demo-rudder-users.xml, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderUserDetailsFile.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/Authz.scala, webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/RudderUserDetailsTest.scala
https://issues.rudder.io/issues/22206
Introduce the possibility to have user-defined roles in the `rudder-users.xml` file. 
The main changes are:
- the user file parsing steps are not more cleanly separated, with the parsing first step that just check for the XML structure, extract data but doesn't do any consistancy check ; then we have a different step for custom role check and an other for user roles,
- for the parsing of users, both `role` (as before 7.3) and `roles` (7.3 normalization) tags are accepted,
- parsing authorisation (ie `node_read` etc) is moved to the `AuthorizationType` class,
- authorisation type (`read`, `write`, `edit`) are defined in a sealed class so that we can check that a custom role doesn't overlap an authorisation
- `RoleToAuthz` object is renamed …
=> Fixes #22206: Allow user to define custom roles in rudder-user.xml

relay/sources/relayd/Cargo.lock
https://issues.rudder.io/issues/22351
=> Fixes #22351: Update the embedded openssl to 1.1.1t

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/MainCampaignService.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/hooks/RunHooks.scala, webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
https://issues.rudder.io/issues/22378
=> Fixes #22378: Generate policies for campaigns before it starts officially, delete them after it stops (1 hour delay each)

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/DebugComplianceLogger.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/StatusReports.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ComplianceRepository.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala
https://issues.rudder.io/issues/22375
So, the reason was that in the case were we had a valid old run, with a config id, but the expected report for that config id were missing (because they were old and so they got deleted since then), THEN we were going into a `UnexpectedUnknownVersion` in place of a `NoReportInInterval`. 
So now, we first check the date of the old run, and if the run is expired, we return `NoReturnInInterval`, else we return `UnexpectedUnknownVersion` (because in that case, we should really have the config id in base)
=> Fixes #22375: Nodes not answering are seen in "missing" rather than in "no reports"

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ExecutionBatchTest.scala
https://issues.rudder.io/issues/22371
=> Fixes #22371: missing report in change only

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/healthcheck/HealthcheckService.scala
https://issues.rudder.io/issues/22430
=> Fixes #22430: Healthcheck on file descriptor should be max 64000

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RoleApiMapping.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/Compliance.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ComplianceApi.scala, webapp/sources/rudder/rudder-web/src/main/elm/directivecompliance/sources/ApiCalls.elm, webapp/sources/rudder/rudder-web/src/main/elm/directivecompliance/sources/JsonDecoder.elm
https://issues.rudder.io/issues/22338
=> Fixes #22338: Refactor some code and changes API url for compliance by directive

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/ComputePolicyMode.scala, webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/web/services/ComputePolicyModeTest.scala
https://issues.rudder.io/issues/21731
=> Fixes #21731: Rule is in mixed mode even though she has only one directive in audit

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/MergeNodeProperties.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/nodes/TestMergeGroupProperties.scala
https://issues.rudder.io/issues/21924
=> Fixes #21924: Policy generation broken when defining a group with invert result of inclusion of another group

webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/DataTypes.elm, webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/JsonDecoder.elm, webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewUtils.elm
https://issues.rudder.io/issues/21182
=> Fixes #21182: Sorting by Compliance doesn't sort in the rule details

webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/services/core/FullInventoryRepository.scala, webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/FullInventoryRepositoryImpl.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/ApplicationLogger.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/inventory/TestCertificate.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/ApiDatastructures.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/LiftApiDispatcher.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala, webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala, webapp/sources/scala-ldap/src/main/scala/com/normation/ldap/sdk/LDAPConnection.scala, webapp/sources/utils/src/main/scala/com/normation/ZioCommons.scala
https://issues.rudder.io/issues/22534
Add a methode to be able to filter out entries in a subtree research. 
Then use it in the LDAP "get inventories" to limit the subtrees to the one of the looked for nodes. 
We need a second request to get relevant machine (which use the same id of only requesting machines actually linked to nodes by filtering out the tree)
=> Fixes #22534: List Managed Nodes API with any of the fields listed in the "full" never answer

webapp/sources/api-doc/code_samples/curl/compliance/directive.sh, webapp/sources/api-doc/code_samples/curl/compliance/directives.sh, webapp/sources/api-doc/components/responses/compliance-directive-id-csv.yml, webapp/sources/api-doc/components/responses/compliance-directive-id.yml, webapp/sources/api-doc/components/schemas/directive-node-compliance.yml, webapp/sources/api-doc/components/schemas/directive-rule-compliance.yml, webapp/sources/api-doc/components/schemas/methods.yml, webapp/sources/api-doc/components/schemas/node-compliance-component.yml, webapp/sources/api-doc/components/schemas/rule-compliance-component.yml, webapp/sources/api-doc/openapi.src.yml, webapp/sources/api-doc/paths/compliance/directive.yml, webapp/sources/api-doc/paths/compliance/directives.yml
https://issues.rudder.io/issues/22151
=> Fixes #22151: API documentation for compliance by directive

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/db/Doobie.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/StatusReports.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ExpectedReportsRepository.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ReportsRepository.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ExpectedReportsJdbcRepository.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ReportsJdbcRepository.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/NodeConfigurationService.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingService.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportsTest.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/Compliance.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ComplianceApi.scala, webapp/sources/rudder/rudder-web/src/main/elm/directivecompliance/sources/ApiCalls.elm, webapp/sources/rudder/rudder-web/src/main/elm/directivecompliance/sources/DataTypes.elm, webapp/sources/rudder/rudder-web/src/main/elm/directivecompliance/sources/Directivecompliance.elm, webapp/sources/rudder/rudder-web/src/main/elm/directivecompliance/sources/Init.elm, webapp/sources/rudder/rudder-web/src/main/elm/directivecompliance/sources/JsonDecoder.elm, webapp/sources/rudder/rudder-web/src/main/elm/directivecompliance/sources/ViewNodesCompliance.elm, webapp/sources/rudder/rudder-web/src/main/elm/directivecompliance/sources/ViewUtils.elm
https://issues.rudder.io/issues/22552
=> Fixes #22552: General improvements on Directive compliance API

webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/DynamicRudderProviderManager.java, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderProviderManager.java
https://issues.rudder.io/issues/20396
Tested with file, ldap and OIDC backends. That's a lot of different case from springsecurity, whose API is just plan horrible. 
So nothing facny: 
- we need a new class `RudderAuthenticationProvider` that implements `AuthenticationProvider` else we don't have access to our provider identifier at login
- then, the hard part was trying to understand where in Spring we can put the log - it's in a finally, because control flow by exception is a thing in java
- then trying to understand all the things that can get null, and well anything can be null.
=> Fixes #20396: It's hard to understand what authentication backend failed when a fallback happens

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/ApplicationLogger.scala, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderUserDetailsFile.scala, webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/RudderUserDetailsTest.scala, webapp/sources/utils/src/main/scala/com/normation/ZioCommons.scala
https://issues.rudder.io/issues/22645
(you should look at that PR without spaces change: https://github.com/Normation/rudder/pull/4760/files?w=1)
I found a way to keep compat and implement something that both make locks on init object a non existing problem and make rudder starts much faster (30~50%, I sometime get to "webapp started" log under 10s and it is now really CPU bounded, ie switching to "low energy" CPU policy increase boot time, max speed decrease it, etc)
So, the strategy is: 
- add a `RudderConfigInit`, with nothing in its constructor so that it returns immediately and a massive `init()` method that does all what RudderConfig used to be
- everything is a `lazy val` in that `init()` method. It allows JVM to sort instanciations and ensure there is no deadlock (scala compiler …
=> Fixes #22645: Deadlock in rudder 7.3 (and perhaps 7.2)

relay/sources/relayd/deny.toml
https://issues.rudder.io/issues/22706
=> Fixes #22706: Ignore RUSTSEC-2023-0034 in relayd

policies/Cargo.lock, policies/rudderc/docs/src/introduction.md, policies/rudderc/docs/src/test.md, policies/rudderc/docs/src/usage.md, policies/rudderc/src/lib.rs, policies/rudderc/src/test.rs, policies/rudderc/tests/cases/test/zero_param/technique.yml, policies/rudderc/tests/cases/test/zero_param/tests/case1.yml, policies/rudderc/tests/cases/test/zero_param/tests/reference.conf, relay/sources/relayd/Cargo.lock
https://issues.rudder.io/issues/22721
=> Fixes #22721: Update rudderc documentation

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogFactory.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlSerialisationImpl.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlUnserialisationImpl.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/marshalling/TestXmlUnserialisation.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/AcceptNode.scala
https://issues.rudder.io/issues/19519
Funny, we have an `xml.Utility.escape(...)` and an `xml.Utility.unescape()`, but they don't do the same thing at all. Really funny. 
I checked that restoring a node group archive is identity
=> Fixes #19519: 

webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/marshalling/TestXmlUnserialisation.scala
https://issues.rudder.io/issues/22761
=> Fixes #22761: Compilation error in Rudder 8.0 due to QueryTrait removal

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/model/DirectiveEditor.scala
https://issues.rudder.io/issues/22654
=> Fixes #22654: Button to add/remove more entries indirectives are inside entries

relay/sources/Makefile
https://issues.rudder.io/issues/22868
=> Fixes #22868: docopt completion is installed in /usr/local/bin

webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-inventory-received-accepted/hook-template, webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-inventory-received-accepted/readme.adoc, webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-inventory-received-failed/hook-template, webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-inventory-received-pending/auto-accept-nodes.example, webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-inventory-received-pending/hook-template, webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-inventory-received-pending/readme.adoc, webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-post-acceptance/hook-template, webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-post-deletion/10-clean-policies, webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-post-deletion/hook-template, webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-pre-deletion/hook-template, webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-failed/hook-template, webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-finished/40-nodelist-relay-configuration, webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-finished/50-reload-policy-file-server, webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-finished/60-trigger-node-update, webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-finished/hook-template, webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-finished/readme.adoc, webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-node-finished/hook-template, webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-node-ready/10-cf-promise-check, webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-node-ready/42-ignore_disabled_non_exec, webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-node-ready/42-ignore_extension.disabled, webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-node-ready/hook-template, webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-started/hook-template, webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/readme.adoc
https://issues.rudder.io/issues/22870
=> Fixes #22870: Use 8080 port to talk with the webapp in hooks

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/SearchNodes.scala, webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder.js, webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/searchNodes.html
https://issues.rudder.io/issues/21236
=> Fixes #21236: When we arrive on the node search page with a query pre-filed, the query is done twice

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/AsyncDeploymentActor.scala
https://issues.rudder.io/issues/22879
Remove useless automatic start event log and normalized log level and format at debug level in rudder app, with the patter: 
```
[Automatic|Manual] policy generation request: [start|queued|dropped] policy generation [(none running)|one policy generation already running]
```
=> Fixes #22879: Too many "Policy Update Started" in event logs

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/ShowNodeDetailsFromNode.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala, webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-datatable.css, webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-node.css, webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css, webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentNodeProperties.html
https://issues.rudder.io/issues/22864
=> Fixes #22864: Display inventory variables and values in node details

webapp/sources/pom.xml, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestEditorTechniqueWriterFallback.scala
https://issues.rudder.io/issues/22986
The warning problem will need to be kept on mind so that we can enable again the warning (removing the compiler flag)
See https://github.com/com-lihaoyi/fastparse/issues/285 for details.
Also revert https://github.com/Normation/rudder/pull/4862 because finaly, there was API changes:
=> Fixes #22986: Rudder 8.0 compilation is broken

webapp/sources/utils/src/main/scala/com/normation/utils/Version.scala
https://issues.rudder.io/issues/22978
We have a parser for `Version` object which create instance of `Numeric`, `Chars` etc part for each segment of a version (each part separated by `.`, `~`, etc). 
So typically for version `1.2.3`, we get 3 new instances of `Numeric(1)`, `Numeric(2)`, `Numeric(3)`. When we have thousands of versions processed, that create a lot of churn. We also know that the low numeric values are over represented in version, so we can easily create a cache for values under 100 and have only one instance of these `Numeric` in RAM at any point. 100 `Numeric` consume almost nothing, it doesn't change memory requirements for rudder. 
The cache is implemented by making the `Numeric` constructor private and always using its factory, which was already the usage case since …
=> Fixes #22978: Cache most current Version number to save lots of memory

webapp/sources/pom.xml, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/api/DataStructures.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/db/Doobie.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/NodeDit.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/RudderDit.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/properties/Properties.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/ExpectedReports.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DataStructures.scala, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/JavascriptEngine.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/cfclerk/services/TechniqueRepositoryTest.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/nodes/NodePropertiesTest.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/GitModificationRepositoryTest.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportsTest.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/write/PolicyAgregationTest.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ExecutionBatchTest.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/Authorizations.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RudderJsonResponse.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/InventoryApi.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ParametersApi.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/TechniqueApi.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/DiffDisplayer.scala, webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala, webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
https://issues.rudder.io/issues/23037
=> Fixes #23037: New round of dependencies to update ! 

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueCompiler.scala
https://issues.rudder.io/issues/23053
- if `target` subdir (`compilationOutputDir`) exists, then move all things in it to technique dir
- also, clean-up `compilation-output.yml` at the begining of the generation to avoid having stalled output.
=> Fixes #23053: Rudderc produces metadata.xml under target directory which breaks webapp

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/AsyncDeploymentActor.scala
https://issues.rudder.io/issues/23074
In PR https://github.com/Normation/rudder/pull/4832/files#diff-2bfd5f67b4c377de308d2c78906f3ecf1684b561fc7c22739dfd18aea93156afL275 we removed the actual queuing, not only the save of log event, which breaks the state machine.
=> Fixes #23074: Generation not queued when one already started

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/facts/nodes/NodeFactRepository.scala, webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
https://issues.rudder.io/issues/23045
The whole thing is about adding a boolean "actually do things with git" in `GitNodeFactRepository`. The parameter is taken from config file (default false if missing, ie in case of upgrade but also for new install). 
Then, it's just adding `ZIO.when(xxxx)` where needed, and compensate when the commit was doing more than just commit (deletion).
=> Fixes #23045: Make commiting nodes to fact-repo optionnal

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ExecutionBatchTest.scala
https://issues.rudder.io/issues/23090
Our regex for matching what is expanded from an variable didn't have the "dot all" modifier, which makes it unable to match multiline string.
=> Fixes #23090: Multiline string in component name or value breaks pattern comparison for expected report

webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala, webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ExecutionBatchTest.scala
https://issues.rudder.io/issues/22388
- backport the tests change from https://github.com/Normation/rudder/pull/4897
- make the pattern check for component name and variable with `$` more lenient: now, we only compare that what is before the `$` is identical (ie whole string when no variable, nothing when the variable is at the begining, etc)
=> Fixes #22388: Bad report maching when reportid are present

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/TechniqueApi.scala
https://issues.rudder.io/issues/23000
Since technique editor doesn't manage reason popup (need to be corrected, at least along with https://issues.rudder.io/issues/22895) we always provide one. We already had reimplemented part of `RestUtils` methods in technique editor API (not sure why), so it's just copying more code. Since it will be removed in 8.0, that's not too bad. 
The other part about `wrapper` is needed else we always evaluate response before wrapping in it: it's `Box`, not `ZIO`, so it's strict and not lazy. The consequence here was that even when the `extractReason` was returning an error, the `writeTechniqueAndUpdateLib` was already done which was false.
=> Fixes #23000: When changes messages are mandatory and saving a technique we have an error message about missing info but technique is saved

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
https://issues.rudder.io/issues/23093
Rights were used in the angular app, now it's fully managed from elm side of the rewritten app, see: https://github.com/Normation/rudder/pull/4839
=> Fixes #23093: Warning for unused vars in 8.0 compilation

webapp/sources/pom.xml
https://issues.rudder.io/issues/23147
Change ZIO version to avoid https://github.com/zio/zio/issues/7608
=> Fixes #23147: Version 2.0.3 of ZIO cause OutOfMemory error and high CPU load

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/TagsEditForm.scala
https://issues.rudder.io/issues/23148
Workaround the tag limitation by providing a hard coded value that is clearly not something that we want to keep. 
Note: it will put that value in directive tags, so it must not outlive alpha cycle.
=> Fixes #23148: Temporary workaround for tag creation in rudder 8.0 alpha

policies/rudderc/src/backends/unix/ncf/technique.rs, policies/rudderc/tests/cases/general/reporting/technique.cf
Bundle should be in the order they run, not alphanumeric order.
=> Fixes #23150: Sort bundles in CFEngine output

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/RegisterToasts.scala, webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/common-layout.html
https://issues.rudder.io/issues/7008
The redirection part is trivial: it's just two `RedirectTo` for the `onSuccess/onFailure` case. Can't be simpler. 
Safe, we want a notification that the node was deleted (or that there was an error), and we can't do that in JS since we are doing a redirect. 
So I created a simple snippet with a session var (`UnpublishedToasts`) that display the list of toast when the comon layout is loaded (ie at each actual load of a rudder page). 
You can register toasts with `RegisterToasts .register` anywhere in Rudder where the HTML session is defined (so mostly lift snippet). Toast are cleaned when displayed. 
The are session-bound, so linked to an user, and cleaned-up on loggout in any case.
=> Fixes #7008: After deleting a node, the user should be redirected to nodes list page

relay/sources/relayd/Cargo.lock, relay/sources/relayd/Cargo.toml, relay/sources/relayd/benches/benches.rs, relay/sources/relayd/src/configuration.rs, relay/sources/relayd/src/configuration/main.rs, relay/sources/relayd/src/output/database.rs, relay/sources/relayd/src/output/upstream.rs, relay/sources/relayd/supply-chain/audits.toml, relay/sources/relayd/supply-chain/config.toml, relay/sources/relayd/supply-chain/imports.lock
https://issues.rudder.io/issues/23159
Improves secret security:
* Zero-ed memory on Drop
* Immutable secrets (avoid accidental copies)
* No access possible outside of `expose_secret()`, even for only a comparison
* `expose_secret()` is more explicit than `value()`
=> Fixes #23159: Use the secrecy crate for wrapping passwords

policies/Cargo.lock, policies/rudderc/src/backends/windows.rs, policies/rudderc/src/ir/condition.rs, policies/rudderc/src/ir/value.rs, policies/rudderc/templates/technique.ps1.askama, policies/rudderc/tests/cases/general/escaping/technique.ps1, policies/rudderc/tests/cases/general/form/technique.ps1, policies/rudderc/tests/cases/general/ntp/technique.ps1, policies/rudderc/tests/cases/general/reporting/technique.ps1, webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueCompiler.scala
* Fix double double-quotes around conditions
* Fix parser to allow `[]{}$` outside substitution contexts
* Fix parser to fail when non-complete
* Remove an confusing unused scala function
=> Fixes #23152: Conditions syntax broken on Windows

policies/rudderc/src/backends/unix/ncf/method_call.rs, policies/rudderc/tests/cases/general/escaping/technique.cf, policies/rudderc/tests/cases/general/ntp/metadata.xml, policies/rudderc/tests/cases/general/ntp/technique.cf, policies/rudderc/tests/cases/general/ntp/technique.ps1, policies/rudderc/tests/cases/general/ntp/technique.yml
https://issues.rudder.io/issues/23178
=> Fixes #23178: " are not correctly escaped in technique for classes_noop in rudder 8.0

ci/rust.sh, policies/Makefile, rust.makefile
https://issues.rudder.io/issues/23175
* Build binaries with https://github.com/rust-secure-code/cargo-auditable
* Embeds dependencies list in binary
* Allows SBOM and vulnerability audit directly on produced artifacts
=> Fixes #23175: Build rust binaries with cargo auditable

webapp/sources/rudder/rudder-web/src/main/javascript/rudder/angular/passwordForm.js, webapp/sources/rudder/rudder-web/src/main/javascript/rudder/directive-inputs.js, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/model/DirectiveFieldEditors.scala, webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-directives.css, webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-main.css, webapp/sources/rudder/rudder-web/src/main/webapp/index.html, webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/passwordInput.html
https://issues.rudder.io/issues/23060
=> Fixes #23060: Rewrite angular app "passwordForm" in JavaScript

rust.makefile
https://issues.rudder.io/issues/23191
=> Fixes #23191: Install cargo-auditable before building

webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala, webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css
https://issues.rudder.io/issues/23087
=> Fixes #23087: Inventory variable that are Json types are listed as plain string types in the UI

relay/sources/relayd/Cargo.lock
https://issues.rudder.io/issues/23217
=> Fixes #23217: Update embedded openssl to 1.1.1v - relayd

policies/Dockerfile, policies/rudder-module-type/src/cfengine/protocol.rs, policies/rudderc/src/ir/technique.rs, policies/rudderc/src/logs.rs, policies/rust-toolchain.toml, relay/sources/relayd/Dockerfile, relay/sources/relayd/rust-toolchain.toml
https://issues.rudder.io/issues/23216
=> Fixes #23216: Update Rust compiler to 1.71.1 for security fix

webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-finished/50-reload-policy-file-server
https://issues.rudder.io/issues/23218
Windows agent fetchs their policies with apache2, based on their certificate
This changes runs the part that is made to update the access rules, and reload apache2 if necessary, so that we can do a rudder agent update on window node once it's been accepted
=> Fixes #23218: Windows agent cannot get immediatly its policies right after being accepted

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/ApiAuthorization.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/EventLogAPI.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/RestApiAccounts.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/RestCompletion.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/RestQuicksearch.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/SharedFilesAPI.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
https://issues.rudder.io/issues/23227
Correct right checking for old APIs that don't take benefits of the framework with shema definition that manages that automatically. 
The idea is just to encapsulate each API endpoint logic with a `with[ActionType][ActionObject]` check that will do the correct check or else return an error.
For example for quicksearch:
```
....
case Get("secure" :: "api" :: "quicksearch" :: Nil, req) => {
OldInternalApiAuthz.withReadUser {
... the same code than before ...
}
...
```
The error is logged two times: by hand at warn level for logger `api`, and automaticaly by the rest logger of the old API because it's an API error and they are always logger. Perhaps it's useless, but it seems strange that no logs are traced for `api`. The warn log can be removed by …
=> Fixes #23227: 

policies/rudderc/src/backends/unix/prelude.cf, relay/sources/apache/rudder-apache-relay-ssl.conf, relay/sources/relayd/src/http_client.rs
https://issues.rudder.io/issues/23292
=> Fixes #23292: TLS 1.3 everywhere

webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewBlock.elm, webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechnique.elm, webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-technique-editor.css
https://issues.rudder.io/issues/23303
To improve feedback during drag'n drop, I've added an animation of the border colour and box-shadow of the targeted drop zone :
However, I couldn't do anything to highlight the selected method - no css can be applied to the moving element during drag'n drop.
I took the opportunity to fix a bug with empty blocks: 2 drop zones would appear when a method was dragged over them :
=> Fixes #23303: When drag'n drop, the selected method and the targeted drop zone should be more highlighted

webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/Authorizations.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RoleApiMapping.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/CurrentUser.scala, webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/RudderUserDetails.scala, webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderUserDetailsFile.scala, webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/RegisterToasts.scala, webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/RudderUserDetailsTest.scala
https://issues.rudder.io/issues/23305
We used to forbid creation of a rights without any `Authorization` - which is good ! But the correct way to forbid it is by making creation impossible, not throwing a runtime error. 
This PR change the `Rights` class to a case class but with a private constructor to force the use of its object factory which does the correct checking and succeed in all case, returning the `NoRights` special value if needed. 
Remaining part of the PR are change to accomodate the use of the factory in place of `new`.
All over, it's a nice simplification.
PR https://github.com/Normation/rudder-plugins/pull/593 needs that one before being merged.
=> Fixes #23305: When custom role permission list is empty, reload lead to stack trace

webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/JsonDecoder.elm
https://issues.rudder.io/issues/23244
Changes were not made to json decoder when we modified the format of technique for a technique block reporting logic
(gone from an object to a string)
=> Fixes #23244: Technique editor throws errors when using blocks with the weighted default reporting option

webapp/sources/utils/src/main/scala/zio/yaml/YamlOps.scala, webapp/sources/utils/src/test/scala/zio/yaml/ZioYamlTest.scala
https://issues.rudder.io/issues/23325
As far as I saw, the only change was the addition of `dumperOptions.setIndentWithIndicator(true)`, so I removed everything else that was possible to rely on what the lib provide and avoid duplicating code. 
I also reodered code so that it follows the original one and make comparison easier. 
I've added a test so that we are informed if at some point, the base lib bug is corrected (and that our encoder works). 
Alse change licence header (that's not our copyright, we copied it, so it must be said, even if the original license allows that).
=> Fixes #23325: Simplify YAML encoding workaround
